- sky/backends/backend_utils.py
```
resources:
zone: europe-west4-a
```
would print
```
» sky launch t.yaml                                                                          
Task from YAML spec: t.yaml
ValueError: Invalid resources YAML: The following fields are invalid:
```
because there's no similar fields to `zone`. This PR fixes that.
> UX: Fix empty 'The following fields are invalid:' outputs.

- sky/backends/cloud_vm_ray_backend.py
This fixes the provision retry for a cluster with long name. 
Before, the following command will directly fail without failover to aws:
```
sky launch --use-spot -c test-spot-retry-longname-gcp-failxxxxxxxxxxxxxxxxxxxxxxxx ''
```
Tested:
> Fix cluster name check for failover

- sky/templates/aws-ray.yml.j2
- sky/templates/gcp-ray.yml.j2
This fixes the file not exist problem for modifying `/etc/fuse.conf` on a custom image.
Tested:
> Fix permission error for custom image without /etc/fuse.conf

- sky/clouds/service_catalog/data_fetchers/fetch_azure.py
I found that the three GPU VMs are missing in the Azure service catalog. While we cannot currently use those VMs due to the quota limit, I think it's good to include them in the catalog.
*This PR fixes the catalog fetcher, but does not directly add the GPU VMs to the catalog. The VMs will be added in the next catalog update.
StandardNCADSA100v4Family (1x, 2x, 4x A100-80GB): https://docs.microsoft.com/en-us/azure/virtual-machines/nc-a100-v4-series
standardNDSFamily (P40): https://docs.microsoft.com/en-us/azure/virtual-machines/nd-series
StandardNVADSA10v5Family (A10): https://docs.microsoft.com/en-us/azure/virtual-machines/nva10v5-series
> Add 3 GPU VMs to Azure catalog fetcher

- sky/templates/aws-ray.yml.j2
- sky/templates/azure-ray.yml.j2
- sky/templates/gcp-ray.yml.j2
Thanks for the issue reported by @lhqing! For some custom images, the `~/.ssh/config` can be missing, causing the commands in the following lines fail. This PR fixes the problem by creating the `~/.ssh/config` file after the cluster is launched.
https://github.com/skypilot-org/skypilot/blob/122ce0e921c1c64fbe6ffd5bcc71eef91556f09e/sky/templates/aws-ray.yml.j2#L103
https://github.com/skypilot-org/skypilot/blob/122ce0e921c1c64fbe6ffd5bcc71eef91556f09e/sky/templates/gcp-ray.yml.j2#L140
https://github.com/skypilot-org/skypilot/blob/122ce0e921c1c64fbe6ffd5bcc71eef91556f09e/sky/templates/azure-ray.yml.j2#L108
> Add ssh config during start

- examples/huggingface_glue_imdb_app.yaml
- sky/backends/backend_utils.py
- sky/backends/cloud_vm_ray_backend.py
- sky/skylet/job_lib.py
- sky/skylet/log_lib.py
- tests/test_smoke.py
Thanks to the observation by @michaelzhiluo (https://github.com/skypilot-org/skypilot/pull/969#issuecomment-1203440396), we found that there is a bug in mismatching of `job_lib.query_job_status` and `job_lib.get_status`.
Previously, we map the ray job status to sky job status with
```
'PENDING': JobStatus.PENDING
'RUNNING': JobStatus.RUNNING
```
This will cause a problem for the job status transition. When a job has not been allocated with required resources, the job will be set to RUNNING in the skylet, due to the following line.
https://github.com/skypilot-org/skypilot/blob/2cb62c542cfc48761d710586bb926f661722ac94/sky/skylet/job_lib.py#L278
**This PR also fixes the race condition caused by periodic job status update by skylet and job status set in generated ray program.**
Tested:
> Fix job status transition

- sky/cli.py
Fixes bug discovered by @concretevitamin.
`sky queue on-prem-test`
```
Fetching and parsing job queue...
Job queue of cluster on-prem-test
ID  NAME     SUBMITTED    STARTED      DURATION  RESOURCES     STATUS     LOG                                        
1   sky-cmd  43 mins ago  43 mins ago  1s        1x [CPU:0.5]  SUCCEEDED  ~/sky_logs/sky-2022-08-02-22-31-40-033756  
Local cluster azure-onprem-test1 is uninitialized; skipped.
Local cluster on-prem-smoke-test is uninitialized; skipped.
Local cluster dev-production is uninitialized; skipped.
Local cluster azure-onprem is uninitialized; skipped.
```
`sky queue on-prem-test`
```
Fetching and parsing job queue...
Job queue of cluster on-prem-test
ID  NAME     SUBMITTED    STARTED      DURATION  RESOURCES     STATUS     LOG …
```
> [Onprem] Sky Queue Logging

- sky/backends/cloud_vm_ray_backend.py
- sky/utils/subprocess_utils.py
Closes #518.
It surfaces the setup error at the end of the error message, as proposed by @concretevitamin.
Tested yaml:
```
setup: |
set -ex
somenonexit command
echo "running setup"
```
Previously,
```
sky.exceptions.CommandError: Command /bin/bash -i /tmp/sky_setup_jsyb5vgm 2>&1 failed with return code 127.
Failed to setup with return code 127.
```
Currently,
```
sky.exceptions.CommandError: Command /bin/bash -i /tmp/sky_setup_jsyb5vgm 2>&1 failed with return code 127.
Failed to setup with return code 127. Check the details in log: ~/sky_logs/sky-2022-08-07-00-19-04-685768/setup-34.227.105.10.log.
****** START Last lines of setup output ******
+ somenonexit command
+ '[' -x /usr/lib/command-not-found ']'
+ /usr/lib/command-not-found -- somenonexit
somenonexit: command not found
******* …
```
> Surface setup error

- docs/source/getting-started/installation.rst
- sky/setup_files/setup.py
Based on the offline discussion, we found it makes sense to install AWS CLI by default when installing skypilot:
1. The AWS most commonly used by our users.
2. It makes no sense to install a no-cloud version of skypilot with `pip install skypilot`
3. The installation of AWS CLI is pretty quick.
This also fixes the hint in the document for installing `grpc` for Apple Silicon.
I will cherry-pick this PR into the `releases/0.1.1`.
> Install aws by default

- .github/workflows/pylint.yml
- .github/workflows/pytest-generic.yml
- .github/workflows/pytest.yml
- .github/workflows/yapf.yml
This makes sure the actions are triggered for the releases branches.
Reference: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#using-filters
> Fix github action for PR on releases branches

- docs/source/reference/yaml-spec.rst
A quick fix for zone typo in YAML. Thanks @concretevitamin for catching this!
> fix typo in YAML

- sky/execution.py
Fixes #982, encountered by Erick a while ago.
Before
```
> sky.exec('echo hi', cluster_name=name)
...
assert len(dag) == 1, f’Sky assumes 1 task for now. {dag}'
AssertionError: Sky assumes 1 task for now. echo hi
```
Now hinting with a copy-pasteable snippet:
```
> sky.exec('echo hi', cluster_name=name)
...
raise TypeError(_EXEC_STRING_AS_DAG_HINT_MESSAGE)
TypeError: Programmatic API sky.exec() expects a sky.Dag but received a string.
If you meant to run a command, make it a Task's run command and wrap as a Dag:
def to_dag(command, gpu=None):
with sky.Dag() as dag:
sky.Task(run=command).set_resources(
sky.Resources(accelerators=gpu))
return dag
sky.exec(to_dag(cmd), cluster_name=..., ...)
If the task needs accelerators:
sky.exec(to_dag(cmd, gpu='V100'), …
```
> UX: type check sky.exec()'s first argument, and hint.

- docs/source/getting-started/quickstart.rst
- docs/source/reference/faq.rst
- docs/source/reference/yaml-spec.rst
- sky/backends/cloud_vm_ray_backend.py
- sky/cli.py
- sky/core.py
The programmatic API PR changed some prior logging messages from just print() to logger.info() in core.py. This PR reverts those changes for the old behavior, which is arguably a more CLI-like experience.
Before this PR (note the `core.py` prefixed messages):
```
» sky queue c2
Fetching and parsing job queue...
I 08-10 19:11:14 core.py:264]
I 08-10 19:11:14 core.py:264] Sky Job Queue of Cluster c2
ID  NAME     SUBMITTED    STARTED      DURATION     RESOURCES     STATUS     LOG
20  sky-cmd  1 hr ago     1 hr ago     < 1s         1x [CPU:1]    SUCCEEDED  ~/sky_logs/sky-2022-08-10-17-16-20-247074
» sky cancel c2 -a
I 08-10 19:11:29 core.py:303] Cancelling all jobs on cluster 'c2'...
» sky logs c2 20
I 08-10 19:11:50 core.py:334] Tailing logs of job 20 on cluster 'c2'...
I 08-11 02:11:51 …
```
> For CLI-like messages, use print() not logging.

- sky/clouds/service_catalog/data_fetchers/fetch_gcp.py
I found two typos in the GCP website that affect our catalog.
1. In `us-central1-b`, a comma is omitted between T2A and N1.
2. In `us-central1-c`, a space is omitted between C2 and C2D.
This PR fixes the gcp catalog crawler to handle these typos. However, the 4 instances (T2A and N1 on us-central1-b, and C2 and C2D on us-central1-c) will not be available until the next catalog update.
> Fix GCP catalog bugs due to website typos

- sky/cli.py
- Modified `start` cli.py to allow for restarting of all clusters
- Users can now use `sky start --all / -a` to restart clusters, in the same way they would use this `--all / -a` to currently down all clusters
- Addresses [Issue 1029](https://github.com/skypilot-org/skypilot/issues/1029#issue-1325020354)
> Add sky start --all feature

- sky/data/storage.py
- sky/execution.py
- sky/spot/recovery_strategy.py
This fixes the problem caused by #1014, which disables launching the cluster with region specified but without cloud specified. That makes the spot recovery strategy fails to recover a spot task without cloud specified.
> Fix spot recovery without cloud specified

- sky/usage/loki-s3-config.yaml
This fixes the problem where our dashboard fails to get all the users as the number latest operations for some users grows too large which exceeds the original query limitation.
> Fix the line limitation for query of loki

- sky/clouds/gcp.py
Bug report from Daniel: `nvidia-smi` doesn't work on `sky gpunode --cloud gcp`.
```
NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.
```
Reason: K80 requires nvidia-driver version to be <=470. (see details [here](https://cloud.google.com/compute/docs/gpus/install-drivers-gpu))
Before it worked fine as the cuda version was older on GCP images but several days ago GCP upgrades the driver version to 510 for all the deep learning images (see release note [here](https://cloud.google.com/deep-learning-vm/docs/release-notes)). From the note
```
The latest NVIDIA driver version does not support K80 GPUs. To use K80 GPUs, you must use an M94 or earlier environment.
```
This PR fixes this issue by using a …
> Fix K80 gpunode by correcting GCP image version

- sky/clouds/gcp.py
As suggested by @infwinston, we should add version after CPU image, due to the change in #1090.
Tested:
> Fix version number for GCP CPU image

- sky/authentication.py
- sky/backends/backend_utils.py
- sky/backends/cloud_vm_ray_backend.py
- sky/cli.py
- sky/setup_files/setup.py
- sky/skylet/ray_patches/__init__.py
- sky/skylet/ray_patches/command_runner.py.patch
- sky/templates/gcp-ray.yml.j2
- sky/utils/command_runner.py
- sky/utils/log_utils.py
- sky/utils/timeline.py
- tests/test_smoke.py
`sky launch --cloud gcp`
Before, master 054402e3d77 - median 3:02
```
sky launch -c no-opt --cloud gcp -y ''  22.03s user 4.66s system 14% cpu 3:02.50 total
sky launch -c no-opt1 --cloud gcp -y ''  19.38s user 3.81s system 12% cpu 3:06.32 total
sky launch -c no-opt2 --cloud gcp -y ''  19.02s user 3.73s system 12% cpu 2:58.92 total
```
After - median 2:40 (12% speed up)
```
sky launch -c opt --cloud gcp -y ''  13.89s user 3.17s system 10% cpu 2:43.79 total
sky launch -c opt2 --cloud gcp -y ''  11.78s user 2.37s system 8% cpu 2:40.32 total
sky launch -c opt9 --cloud gcp -y ''  11.49s user 2.37s system 9% cpu 2:31.00 total
```
After, but **additionally comment out any credentials upload** (see below) - median 2:13 (27% speedup)
```
sky launch -c test1 --cloud gcp -y ''  12.68s user 2.68s …
```
> Optimize provision speed a bit, focusing on 1-node GCP

- sky/cli.py
- sky/core.py
- sky/execution.py
- sky/spot/__init__.py
- sky/spot/constants.py
- sky/spot/spot_utils.py
- sky/usage/usage_lib.py
- sky/utils/common_utils.py
- tests/test_spot.py
Closes #1100.
Warning: This will be not backward compatible. Please `sky down -p sky-spot-controller` first before updating to this commit to avoid leakage of the old `sky-spot-controller`.
Tested:
> [Spot] Distinguish spot controller names for different users (!! backward incompatible for spot controller !!)

- sky/skylet/events.py
- sky/skylet/job_lib.py
- sky/spot/spot_utils.py
- tests/test_smoke.py
This is an attempt for #1088. It reduces the parallel query through the same port for the ray job.
Profiling: (The original time is not that large (reduced by 3x), but the list_jobs can reduce the number of http requests by the number of jobs to be queried.)
```bash
$ python ./query_jobs.py 
Parallel Time spend: 0.10391879081726074
job list Time spend: 0.03846001625061035
```
```python
from sky.skylet import job_lib
from sky.utils import subprocess_utils
import time
client = job_lib._create_ray_job_submission_client()
ray_job_ids = [f'{i}-gcpuser' for i in range(60, 90)]
def get_job_status(job_id):
try:
ray_status = client.get_job_status(job_id)
return job_lib._RAY_TO_JOB_STATUS_MAP[ray_status]
except RuntimeError as e:
if 'does not exist' in str(e):
return None
raise
start = time.time() …
```
> Reduce the frequency of job status update and remove parallel query

- sky/backends/backend_utils.py
- sky/cli.py
- sky/core.py
- sky/exceptions.py
- sky/execution.py
- sky/spot/controller.py
- sky/spot/recovery_strategy.py
- sky/templates/spot-controller.yaml.j2
This fixes #1097.
Main changes:
1. Add the `--retry-until-up` option for the `sky spot launch`, i.e. the controller will retry launching/recovering for the request resources forever until the cluster is UP.
2. Improve the responsiveness for job cancelling for spot jobs. Previously, when the spot controller is retrying to launch or recovering the cluster (especially recovering which can take more than 4 hours), it will ignore the cancel signal from the user until the cluster is UP. Now, instead, we will check the signal at the beginning of each retry.
Tested:
> [Spot] Add retry-until-up for spot jobs and improve the responsiveness for cancelling

- sky/backends/backend_utils.py
- sky/backends/cloud_vm_ray_backend.py
- sky/templates/gcp-ray.yml.j2
- tests/test_smoke.py
File mounting our runtime files hurts provisioning speed. This PR bundles them into 1 file mount. Copying them locally takes 10-20ms.
Currently for GCP only. Will be ported to other clouds later.
Before (taken from #1092) - median 2:40
```
sky launch -c opt --cloud gcp -y ''  13.89s user 3.17s system 10% cpu 2:43.79 total
sky launch -c opt2 --cloud gcp -y ''  11.78s user 2.37s system 8% cpu 2:40.32 total
sky launch -c opt9 --cloud gcp -y ''  11.49s user 2.37s system 9% cpu 2:31.00 total
```
After - median 2:05 (22% speedup)
```
sky launch -c opt6 --cloud gcp -y ''  12.54s user 2.62s system 12% cpu 2:05.92 total
sky launch -c opt7 --cloud gcp -y ''  11.73s user 2.29s system 11% cpu 2:02.68 total
sky launch -c opt8 --cloud gcp -y ''  10.92s user 2.06s system 10% cpu 2:05.78 total
``` …
> Optimize GCP provisioning speed: bundle all runtime file_mounts.

- sky/authentication.py
- sky/backends/backend_utils.py
In the GCP cluster launched by `ray up`, our uploaded GCP credentials `~/.config/gcloud/configurations/config_default` will be reset to empty, probably because `ray` needs to use the service account instead of the user's account. This will affect our spot controller, as it requires that file to decide the username used for the spot clusters, when oslogin is enabled in the user project. https://github.com/skypilot-org/skypilot/blob/783adc9d6685de24a30408704a437108880de57a/sky/authentication.py#L201-L226
To solve the problem, we make a backup of that file in the same folder, which will be uploaded by the credential uploads. SkyPilot will read the backup file instead.
Hey @lhqing, please check out if this can fix your problem with the `sky spot launch` when you get time. ; )
> [Spot] Fix oslogin username in clusters

- sky/authentication.py
- sky/backends/backend_utils.py
- sky/templates/gcp-ray.yml.j2
- tests/test_smoke.py
This PR refactors the file_mounts optimization to make it lazy until all the file mounts are added. The file_mounts optimization will be applied to all clouds now.
It should also fix the oslogin issue mentioned in https://github.com/skypilot-org/skypilot/pull/1106#issuecomment-1221455039 , as previously we place the backup file in the same directory as `config_default` whose parent directory will be overwritten by ray autoscaler, instead we now place the backup file in `~/.sky/.sky_gcp_config_default` on the remote instance.
Hey @lhqing, would you like to switch to this branch `git checkout refactor-file-mount-optimization; pip install -e ".[gcp]"` and try if this solves the problem?
Tested:
> Refactor the file_mounts optimization and oslogin

- sky/clouds/azure.py
- sky/clouds/cloud.py
- sky/skylet/ray_patches/__init__.py
- sky/skylet/ray_patches/job_manager.py.patch
Closes #1088.
This fixes the ray dashboard hanging problem. By checking the `py-spy dump --locals --pid <dashboard.py pid>`, we found that the dashboard has some leaked thread `_monitor_job` in the `dashboard/modules/job/job_manager.py`. The problem is caused by `await job_supervisor.ping.remote()`, which may not normally raise the exception after the actor `job_supervisor` is exited.
After switching the `await` to `ray.get`, it seems the problem is solved.
Tested:
> Fixes ray dashboard hanging problem (#1088)

- sky/backends/cloud_vm_ray_backend.py
- sky/skylet/providers/gcp/node.py
- sky/skylet/providers/gcp/node_provider.py
- sky/utils/cli_utils/status_utils.py
Fix a long existing resource leak issue on GCP triggered by `test_stale_job` smoke test.
This bug happened because GCP doesn't fully stop an instance even after a stop operation is finished.
This PR make `sky stop` wait until the instance actually stopped.
I tried to benchmark whether adding this status check for loop increases the running time of `sky stop`.
Turns out the running time is almost the same as before (~40s) for normal use cases. Only if you create a VM and immediately stop it then it'd take 2mins to finish (like what happened in our smoke test).
On the other hand, I also add safe guard to `sky start` to avoid launching new VM. Now if user `sky start` a STOPPING VM (this only happens when user stops the VM on web console) then it'd return below error message.
```
sky start …
```
> Fix GCP VM leak issue

- sky/templates/aws-ray.yml.j2
- sky/templates/gcp-ray.yml.j2
Porting #1092 to AWS.
Before - 2:42
```
sky launch --cloud aws -y ''  8.31s user 1.59s system 5% cpu 2:53.42 total
sky launch --cloud aws -y ''  9.59s user 2.10s system 7% cpu 2:42.28 total
sky launch --cloud aws -y ''  8.17s user 1.54s system 6% cpu 2:31.57 total
```
After - 2:17 (22% speedup)
```
sky launch --cloud aws '' -y  9.69s user 2.09s system 7% cpu 2:32.80 total
sky launch --cloud aws '' -y  7.99s user 1.48s system 7% cpu 2:15.23 total
sky launch --cloud aws '' -y  8.20s user 1.50s system 7% cpu 2:17.38 total
```
Tested:
- `TestStorageWithCredentials`: failed on master for me
- `test_spot_storage`: known access denied
- `test_spot`, `test_use_spot`: AWS related, tracked in #1026 -- they passed when using a non-problematic region
> Port .j2 provision speed optimizations to AWS.

- sky/data/storage.py
- tests/test_smoke.py
Closes #977.
`GetPublicAccessBlock` is no longer a reliable method to check if a s3 bucket is public. Buckets can be publicly readable yet not allow access to `GetPublicAccessBlock`. I'm not sure what caused it (and I can't find a clear reason). 
Some buckets still allow it (e.g., `s3://tcga-2-open`, which is used in our smoke tests and thus was passing), but others have blocked it (e.g., `s3://digitalcorpora`, `s3://imagenet-bucket`). 
Using `head_bucket` API now, as recommended by [boto3 docs](https://docs.aws.amazon.com/cli/latest/reference/s3api/head-bucket.html#head-bucket).
Also added storage tests for non-existent and private buckets.
Tested:
> [Storage] Fix public bucket source check in SkyPilot Storage

- sky/setup_files/setup.py
Now installing SkyPilot would trigger below error due to a recent update of Ray 2.0.
```
File "/Users/weichiang/opt/miniconda3/envs/tmp/lib/python3.8/site-packages/sky/skylet/providers/aws/__init__.py", line 2, in <module>
from sky.skylet.providers.aws.node_provider import AWSNodeProvider
File "/Users/weichiang/opt/miniconda3/envs/tmp/lib/python3.8/site-packages/sky/skylet/providers/aws/node_provider.py", line 28, in <module>
import ray.ray_constants as ray_constants
ModuleNotFoundError: No module named 'ray.ray_constants'
```
Temp fix to force the ray version to be `>=1.9.0,<=1.13.0`.
> Correct ray version

- docs/source/getting-started/installation.rst
We recommend users to install SkyPilot from PyPI and move installing from source later.
> Update installation doc

- sky/skylet/ray_patches/job_manager.py.patch
This is an optimization of #1109, suggested by Sanbin Cho from the ray team.
In the thread: https://ray-distributed.slack.com/archives/CP950VC76/p1660955297652409
This should also closes #1127 .
TL;DR:
If any bad thing happens, the new code can yield for the other coroutines, instead of blocking it as the `ray.get` did. It will not affect the happy path, e.g. the job_supervisor normally ends.
Tested:
> Optimize dashboard patching

- sky/cli.py
- sky/utils/cli_utils/status_utils.py
DURATION is the same as LAUNCHED.
Moving HOURLY_PRICE next to region/zone looks better, and is easier to read for clusters with long COMMAND.
For the truncated output `sky status` I'm still keeping COMMAND, as it seems arguably useful.
> UX: remove DURATION, move HOURLY_PRICE in status table (-a)

- sky/templates/aws-ray.yml.j2
- sky/templates/azure-ray.yml.j2
- sky/templates/gcp-ray.yml.j2
No speed change (slightly slower, but Azure has high variance), because the bottleneck is on the Azure response times. Followup to #1111.
Before
```
sky launch --cloud azure '' -y  17.10s user 3.72s system 3% cpu 9:58.35 total
sky launch --cloud azure '' -y  14.47s user 2.91s system 3% cpu 9:02.75 total
sky launch --cloud azure '' -y  13.57s user 2.37s system 3% cpu 8:35.56 total
```
After
```
sky launch --cloud azure '' -y  16.04s user 3.05s system 3% cpu 9:38.06 total
sky launch --cloud azure '' -y  15.48s user 2.86s system 3% cpu 9:15.08 total
sky launch --cloud azure '' -y  14.57s user 2.64s system 2% cpu 9:38.50 total
```
Tested:
> Port .j2 optimizations (no actual speed change) to Azure.

- sky/cli.py
- sky/global_user_state.py
- Modified `storage delete` in cli.py to specifying glob names for bucket
- Users can now use blobbing such as `sky down test-*` for sky storage delete, allowing for batch bucket deleting
- Addresses [960](https://github.com/skypilot-org/skypilot/issues/960#issue-1299509218)
> Add glob for sky storage delete

- sky/backends/cloud_vm_ray_backend.py
- tests/test_smoke.py
Fixes #1130 
Using `localhost` or `127.0.0.1` in the `ray.init` will cause `ray.get(pg.ready())` fail to unblock. The problem should be a ray bug, but setting the address to `auto` or `internal_ip_address` will solve the problem. (PS: ray gets the internal ip when the `auto` is specified by the following function, which read the file `/tmp/ray/current_ray_cluster` https://github.com/ray-project/ray/blob/cba26cc83f6b5b8a2ff166594a65cb74c0ec8740/python/ray/_private/utils.py#L84).
@michaelzhiluo Can you remind me why you change the address from `auto` to `localhost` in https://github.com/skypilot-org/skypilot/pull/763 ?
Tested:
> Fix placement group not scheduled issue (issue #1130)

- sky/core.py
- sky/spot/spot_utils.py
Caught by @concretevitamin where the resources and region are `'-'` even when the cluster and region is available.
Tested:
> Fix `sky spot status -a` for resources and region information

- sky/backends/backend_utils.py
- sky/backends/wheel_utils.py
- sky/execution.py
- sky/setup_files/setup.py
- sky/templates/aws-ray.yml.j2
- sky/templates/azure-ray.yml.j2
- sky/templates/gcp-ray.yml.j2
- sky/templates/spot-controller.yaml.j2
Previously, if a user log into the remote cluster and run `sky launch`, the hash based wheel dir (introduced by #1139) will be destroyed.
This PR aligns the local wheel directory hierarchy with the remote wheel directory.
Tested:
> Makes the local wheel dir the same hierarchy as the remote

- sky/skylet/events.py
- sky/skylet/skylet.py
- sky/spot/spot_utils.py
Fixes #1141
Previously, if the controller failed abnormally, the spot status of the job will only be updated if the user run `sky spot cancel <job_id>`. 
Now we move the status update to the skylet, so that the spot status will be updated automatically.
Tested:
> [Spot] Show FAILED_CONTROLLER when controller exit abnormally

- sky/skylet/job_lib.py
Previously, our `start_at` for each job is default to NULL. When the job is set to FAILED by skylet, the `get_job_timestamp` below will fail, due to cannot convert `None` to float. We now make the `start_at` default to -1, so that the value will always be available. 
https://github.com/skypilot-org/skypilot/blob/b36bbcffa2d3ea3adedb78a9f7ca7e80c1a32a89/sky/spot/recovery_strategy.py#L159
The problem was caught by @concretevitamin  in spot jobs:
```
(zongheng-107 pid=467225) I 09-01 18:39:30 recovery_strategy.py:147] Failed to launch the spot cluster with error: Command rsync -Pavz --filter='dir-merge,- .gitignore' -e "ssh -i ~/.ssh/sky-key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o ExitOnForwardFailure=yes -o ServerAliveInterval=5 -o …
```
> [Spot] Make get_job_timestamp fetching more robust

- examples/using_file_mounts.yaml
[Issue and fix identified thanks to excellent debugging by @Michaelvll]
Our `using_file_mounts` test fails at `readlink -e /tmp/workdir/circle-link` when the test is run as user `ubuntu`. This is because `readlink -f` tests for the existence of all but the last component in the symlink target (i.e., `/home/ubuntu` should exist, existence of `/home/ubuntu/tmp-workdir` does not matter). When the test is run as ubuntu user, `readlink -f` passes because `/home/ubuntu` exists on the new VM.
A simple fix is to change it to `readlink -e`, which checks for the existence of all components, including the last one.
Tested:
> Fix `using_file_mounts` to use `readlink -e`

- sky/spot/recovery_strategy.py
- sky/spot/spot_utils.py
- tests/run_smoke_tests.sh
Attempt for solving #1132 
Previously, the retry for the spot cluster launching has a bug, where even if the cluster is failed to launch (cluster is UP, but the task is failed to be submitted), we will still start checking the job status until it is RUNNING. The job status checking will keep the program stuck forever, as no job was submitted.
Tested:
> [Spot] Fix the retry logic for spot cluster launching

- sky/clouds/service_catalog/gcp_catalog.py
Currently, `sky launch --gpus A100:1 --instance-type a2-highgpu-1g  "gpustat"` raises the error:
```
File "/Users/woosuk/workspace/sky-proj/skypilot/sky/clouds/service_catalog/gcp_catalog.py", line 405, in check_accelerator_attachable_to_host
max_cpus, max_memory = _NUM_ACC_TO_MAX_CPU_AND_MEMORY[acc_name][acc_count]
KeyError: 'A100'
```
This is a bug introduced by #989, and this PR fixes it.
> Fix GCP A100 launch error

- sky/clouds/service_catalog/data_fetchers/fetch_gcp.py
The recent introduction of A100-80GB GPUs to GCP broke the current GCP catalog crawler. This PR fixes this bug, and enables adding A100-80GB to the new catalog that will be uploaded soon.
> Update GCP catalog crawler

- sky/backends/backend_utils.py
Set `~/.ssh/config` permissions to `644` if newly created by sky so `ray up` does not fail. This fixes #1123.
Tested: `sky launch` on Azure, with and without a `~/.ssh/config` file.
> Change `~/.ssh/config` permissions

- sky/backends/cloud_vm_ray_backend.py
- sky/utils/common_utils.py
Closes #1138.
Since this is also requested by @lhqing to share the `~/.sky` folder across different devices, we may want to have this PR to unblock the issue. This PR replaces the path for the cluster yaml to the relative path as suggested by @concretevitamin in https://github.com/skypilot-org/skypilot/issues/1138#issuecomment-1241083339
Tested:
> Relative cluster yaml

- docs/source/getting-started/installation.rst
- sky/cli.py
- sky/global_user_state.py
This adds support for [shell completion using click](https://click.palletsprojects.com/en/8.1.x/shell-completion/). Under the hood, the CLI runs SQL queries against the local data store to figure out what cluster names can be used to autocomplete the command.
To enable shell completion, the user needs to modify their shell configuration as discussed [here](https://click.palletsprojects.com/en/8.1.x/shell-completion/). To simplify this process, I added a `--install-shell-completion` option to the CLI that automates this process for a specific shell. For example, to enable shell completion for `zsh`, the user will need to run `sky --install-shell-completion zsh` **once** after installing SkyPilot, and this will modify the `~/.zshrc` file accordingly. I've updated the docs to reflect this as …
> Add shell completion support for CLI

- sky/backends/backend_utils.py
- sky/backends/cloud_vm_ray_backend.py
- sky/exceptions.py
- sky/spot/recovery_strategy.py
> Fail early when spot cluster name too long occurs on GCP

- sky/cli.py
- sky/execution.py
Added --no-setup to sky launch in cli.py and propagated changes to _execute in execution.py. If --no-setup flag is set, then backend.setup() call is skipped and logger informs user that setup was skipped. Did simple testing by attempting to relaunch a stopped cluster using the --no-setup flag. Meant to address issue #1157.
> Add --no-setup option to sky launch to allow for remounting of files without having to go through setup instructions again

- sky/backends/backend_utils.py
- sky/backends/cloud_vm_ray_backend.py
- sky/cli.py
- sky/clouds/gcp.py
- sky/execution.py
- sky/resources.py
- sky/spot/spot_utils.py
- sky/templates/aws-ray.yml.j2
- sky/templates/azure-ray.yml.j2
- sky/templates/gcp-ray.yml.j2
- sky/templates/spot-controller.yaml.j2
Many changes from a few weeks ago.
UX
- Make entrypoint optional -- no more `sky launch <flags> ''`, simply do `sky launch <flags>`
- Several reworded logging messages
- After a `spot launch`, no longer print the first few entries from `spot status` as it's too verbose
Reliability
- Handle rate limit exceeded errors from GCP (triggered when launching a bunch of things)
- Fail the runtime setup if ray patching somehow failed
> UX/reliability changes.

- sky/clouds/aws.py
Fixes #1177. Checks if the AWS credentials are valid and can connect to AWS services.
> AWS Credentials Check

- sky/authentication.py
- sky/clouds/gcp.py
- sky/templates/gcp-tpu-create.sh.j2
Fixes #1019 by making `sky check` automatically enable the 3 required APIs & optional TPU API.
Tested:
Create a new project on GCP console.
Run `gcloud init` to choose the new project. Run `gcloud auth application-default login`.
`sky cpunode --cloud gcp` would trigger a hint:
First run
```
» sky check                                                                              
AWS: enabled
Azure: enabled
Checking GCP...
Enabling Compute Engine API (may take a minute)...
Done. Took 54.8 secs.
Enabling Cloud Resource Manager API...
Done. Took 1.8 secs.
Enabling Identity and Access Management (IAM) API...
Done. Took 4.2 secs.
Hint: Enabled GCP API(s) may take a few minutes to take effect. If any SkyPilot commands/calls failed, retry after …
```
> GCP: make `sky check` enable the 3 required APIs & optional TPU API.

- sky/authentication.py
Commit bbfa0de uses the `googleapiclient` module. This will error if `google-api-python-client` is not installed (e.g. see the currently generated [cli reference](https://skypilot.readthedocs.io/en/latest/reference/cli.html)).
> Fix `googleapiclient` import

- sky/execution.py
Tested:
```
file_mounts:
/file: /tmpfile
run: sleep 5
```
> [Spot] Fix variable name in spot local file mount translation

- sky/cli.py
Add `--retry-until-up`, `--region`, and `--idle-minutes-to-autostop` for interactive nodes. This fixes #1131 and #1205.
Tested: `sky {cpunode, gpunode}` on Azure:
I also used print statements to verify `_launch_with_confirm` is called with the correct `retry_until_up` argument. Not sure how else to test that on Azure.
> Add `--retry-until-up`, `--region`, `--zone`, and `--idle-minutes-to-autostop` for interactive nodes

- .gitignore
- sky/clouds/gcp.py
- sky/clouds/service_catalog/azure_catalog.py
- sky/clouds/service_catalog/common.py
- sky/clouds/service_catalog/constants.py
- sky/clouds/service_catalog/data_fetchers/analyze.py
- sky/clouds/service_catalog/data_fetchers/fetch_aws.py
- sky/clouds/service_catalog/data_fetchers/fetch_azure.py
- sky/clouds/service_catalog/data_fetchers/fetch_gcp.py
- sky/clouds/service_catalog/gcp_catalog.py
- tests/test_list_accelerators.py
This PR adopts the changes of the catalog from our private experimental repo. The Azure fetching implementation is significantly faster than (roughly 10x),  by using much more efficient `join` operation instead of the row-wise `apply` method.
It also fixes #1167
This PR also adds `p4de.24xlarge` into the catalog (requested in #1201), but the `ray up` still has some problem launching the cluster.
Just identified the problem that the p4de instance require a signup for an aws account, which could be the reason that `aws ec2 describe-instance-types` cannot find the instance.
The following are the updates in the new catalog
```
#resources  #prices  #spot_prices
aws           385      407          4486
azure          67       70          2602
gcp           264      489          1381
```
Tested:
> Add all region option in catalog fetcher and speed up azure fetcher

- sky/cli.py
Reverts skypilot-org/skypilot#1207 due to https://github.com/skypilot-org/skypilot/pull/1207#issuecomment-1273914381.
We should revert this to prep for the 0.2.0 release.
> Revert "Add `--retry-until-up`, `--region`, `--zone`, and `--idle-minutes-to-autostop` for interactive nodes"

- sky/__init__.py
- sky/data/__init__.py
Adds `StorageMode` enum to the `sky` module to make using Storage programmatic API easier.
Before:
```
sky.Storage(source='s3://example/', mode=sky.data.storage.StorageMode.MOUNT)
```
After:
```
sky.Storage(source='s3://example/', mode=sky.StorageMode.MOUNT)
```
Tested:
> [Storage] Add `StorageMode` to __init__

- examples/docker/echo_app.py
- examples/docker/echo_app.yaml
- examples/docker/echo_app/Dockerfile
- examples/docker/echo_app/README.md
- examples/docker/echo_app/echo.py
This PR adds a simple example for a containerized app for demonstrating how to build run containers and write their outputs to an object store with SkyPilot. This PR is motivated by recent interactions with users and is intended to be the introductory example for users thinking about running containers with SkyPilot. Our existing container examples were either too complex (`detectron2_docker.yaml`), did not demonstrate how the container can be built with SkyPilot (`containerized_app.py`) or did not mention how file/storage mounts can be used to write outputs.
In this PR, we:
1. Add a simple echo app that reads a file and writes to an output directory.
2. Containerize this app by defining a simple Dockerfile.
3. Add SkyPilot YAML demonstrating how this app container can be built remotely …
> [Example] Minimal containerized app example

- sky/templates/aws-ray.yml.j2
Our current default instance created on the AWS has the volume with the maximum IOPs, i.e. 16000. However, by default, the instance created on the AWS console only has 3000 IOPs by default.
Our volume costs (16000-3000) * 0.005 / 30 / 24 = $0.09 / hour, which is 20% of the cost for our default CPU machine on AWS m6i.2xlarge.
Todo item: make this IOPs configurable across the clouds (probably simplify it by only having three tier: low, medium, high).
Tested:
> Reduce iops for aws instances

- sky/templates/aws-ray.yml.j2
Reverts skypilot-org/skypilot#1221
It is not back-compat, if the user has a stopped cluster. We need to keep the original configuration for the existing cluster.
> Revert "Reduce iops for aws instances"

- sky/data/storage.py
- sky/execution.py
Tested:
Should not print:
Should print:
```
/data.txt:
source: ~/data.txt
```
cannot test due to #1226
> [spot] Suppress unnecessary `spot launch` filemount translation logging.

- sky/templates/aws-ray.yml.j2
- sky/templates/azure-ray.yml.j2
- sky/templates/gcp-ray.yml.j2
- sky/utils/common_utils.py
The current prlimit will fail sometimes due to the pid does not exist. We add `|| true` to avoid the error, as the `prlimit` setting is not critical.
Tested:
> [Launch] Avoid prlimit error fail the ray up

- docs/source/examples/syncing-code-artifacts.rst
- docs/source/reference/storage.rst
- examples/storage_demo.yaml
- sky/data/storage.py
- sky/task.py
- tests/test_storage.py
Mitigates #1226 by raising an exception if files are uploaded to sky storage.
```
(base) romilb@romilbx1yoga:$ sky launch storage_test.yaml 
Task from YAML spec: storage_test.yaml
sky.exceptions.StorageSourceError: Storage source path cannot be a file - only directories are supported as a source. To upload a single file, either
1) Use regular file mounts by writing ~/tmpfile: ~/tmpfile in the file_mounts section of your YAML, or
2) Place the file in a directory and specify the directory as the source.
```
Tested:
> [Storage] Disallow single files for upload to Storage

- sky/backends/backend_utils.py
- sky/backends/cloud_vm_ray_backend.py
- sky/templates/aws-ray.yml.j2
- sky/utils/common_utils.py
- tests/backward_comaptibility_tests.sh
It resubmits #1221 , and add backward compatibility for it.
Update (Oct 13th):
* this fixes https://github.com/skypilot-org/skypilot/issues/640, ensuring restarting stopped clusters would not create new duplicate ones
* this reduces spot controller cost by 20%
Our current default instance created on the AWS has the volume with the maximum IOPs, i.e. 16000. However, by default, the instance created on the AWS console only has 3000 IOPs by default.
Our volume costs (16000-3000) * 0.005 / 30 / 24 = $0.09 / hour, which is 20% of the cost for our default CPU machine on AWS m6i.2xlarge.
Todo item: make this IOPs configurable across the clouds (probably simplify it by only having three tiers: low, medium, high).
Tested:
> [Backward Compatibility][Spot] Avoid cluster leakage by ray yaml overwritten and reduce spot controller cost on AWS

- sky/backends/backend_utils.py
Fixes https://github.com/skypilot-org/skypilot/issues/1246.
This error can be triggered when users link their `~/.sky` to some directory path containing spaces. (such as Google Drive)
> Fix bug when .sky absolute path contains space

- sky/backends/backend_utils.py
- sky/backends/cloud_vm_ray_backend.py
- sky/cli.py
- sky/core.py
- sky/execution.py
- sky/global_user_state.py
- sky/skylet/autostop_lib.py
- sky/skylet/events.py
- sky/utils/cli_utils/status_utils.py
- tests/test_smoke.py
- tests/test_spot.py
Closes #954.
Please refer to the following tests for the design of the CLI.
Main changes:
1. Add an option `--terminate` for`sky launch` and `sky start`
2. Add an option `--terminate` for `sky autostop`
3. `sky.launch` replaces the `teardown` option with `terminate`.
Tested:
```
NAME             LAUNCHED        RESOURCES             STATUS   AUTOSTOP      COMMAND                         
test-autodown    a few secs ago  1x AWS(m6i.2xlarge)   UP       2 min (down)  sky launch -c test-autodown...  
smoke-test-zhwu  4 days ago      1x GCP(n1-highmem-8)  STOPPED  -             sky start smoke-test-zhwu      
```
> [Autodown] Support for autodown

- sky/backends/backend_utils.py
- sky/cli.py
- sky/execution.py
- tests/test_smoke.py
As mentioned by @concretevitamin, the current logging. for `sky status -r` is a bit scary, when the cluster with autodown is terminated. This PR handles the logging for the clusters with autodown differently against the normal clusters.
The new logging for the clusters with autodown:
```
sky status -r                                                                                                                                          ✈ ✱
I 10-14 13:17:38 backend_utils.py:1819] The following cluster was autodowned and removed from the cluster table: test-autodown
NAME             LAUNCHED  RESOURCES             STATUS  AUTOSTOP  COMMAND                    
smoke-test-zhwu  1 hr ago  1x GCP(n1-highmem-8)  UP      -         sky start smoke-test-zhwu 
```
> [Autodown] Better logging for `sky status -r` for autodown cluster

- sky/backends/backend_utils.py
This PR fixes the incomplete https://github.com/skypilot-org/skypilot/pull/1247 as reported in https://github.com/skypilot-org/skypilot/issues/1246. This time I'm doing a complete test to avoid the same issue recurring again.
> Fix bug when .sky absolute path contains space (continue)

- sky/data/data_transfer.py
- sky/data/storage.py
Adopt changes for storage from #1152.
Tested:
```
gsutil mb gs://sky-imagenet-bucket-gcp
python - <<EOF
from sky.data import data_transfer
data_transfer.s3_to_gcs('sky-imagenet-bucket', 'sky-imagenet-bucket-gcp') 
EOF
```
> [Storage] Refactor storage and fix data transfer service

- sky/authentication.py
Fixes #1240.
Tested:
- Launched a new task, observed color
- Observed https://github.com/skypilot-org/skypilot/blob/master/sky/authentication.py#L217-L230 is still printed with colors on a new GCP project
> Remove extra colorama.init() causing task logging prefix to have no color.

- docs/source/conf.py
Currently, the title of https://skypilot.readthedocs.io/ still shows 0.1.1, a hard coded version. We now read `sky.__version__`.
Tested:
> [docs] use the correct version in source/conf.py, shown in doc html title.

- docs/source/getting-started/installation.rst
- sky/cli.py
- sky/setup_files/setup.py
As discussed in #1253, the `shell_complete` argument is only available on `click` >= 8.0. To prevent errors when running SkyPilot with earlier version of `click`, this PR updates it such that the argument is only specified on valid versions of click.
Tested:
> Specify shell complete arguments for `click` >=8.0 only

- sky/clouds/gcp.py
- tests/test_smoke.py
Now `sky spot launch` a TPU VM will fail due to `gcloud` not fully setup on the spot controller.
This PR fixes it by uploading `~/.config/gcloud/active_config`.
> Fix sky spot launch TPU

- README.md
This is a nit, switching the slack badge to markdown instead of the html. Markdown can be easier to read and robust to other renders. :)
> [Docs] Use markdown for slack badge in Readme

- docs/source/examples/spot-jobs.rst
- sky/backends/backend_utils.py
- sky/cli.py
- sky/core.py
- sky/spot/constants.py
- sky/utils/cli_utils/status_utils.py
- tests/test_spot.py
According to the offline discussion with @concretevitamin, we decided to add the spot controller in the `sky status` to avoid confusion caused by the controller in the cloud console. (Part of the efforts for fixing #1269)
After this PR, the `sky status` will be:
When tearing down the controller, the output would be (no `--purge` required, as purging can lead to resource leakage):
TODO:
> [Spot] Show spot controller in sky status and simplify tearing down

- sky/cli.py
- sky/utils/cli_utils/status_utils.py
Previously, the hint about auto{stop,down} was too dim to easily notice on a dark scheme terminal. This changes it to normal font, as it's an important message.
@Michaelvll could you help check if this looks OK on a light theme?
Also reworded some messages.
> UX change to status table display.

- sky/skylet/ray_patches/__init__.py
- sky/skylet/ray_patches/azure_cli.py.patch
Fixes #1273 
Before this PR, the error is deterministic. We patch the timeout by replacing the timeout value in the `azure.identity._credentials.azure_cli` from 10 to 30 (from https://github.com/Azure/azure-cli/issues/20404#issuecomment-1249575110)
Tested:
> [Azure] Patch azure cli timeout issue

- docs/source/index.rst
- docs/source/reference/api.rst
- docs/source/reference/cli.rst
- sky/backends/backend_utils.py
- sky/cli.py
- sky/core.py
- sky/execution.py
This PR only handles the Core APIs -- the 7 functions backing https://skypilot.readthedocs.io/en/latest/reference/cli.html#core-cli. It does not properly go through core classes Task, Dag, etc. yet, which will be done in future PRs.
Made some minor changes to core funcs signatures; ran smoke tests to confirm they are working.
Tested
> docs: document core programmatic APIs, and add them to docs website.

- examples/huggingface_glue_imdb_grid_search_app.py
- examples/multi_echo.py
- examples/resnet_app.py
- examples/resnet_distributed_torch_app.py
- examples/resnet_distributed_torch_with_script.yaml
- examples/tensorboard_app.py
- sky/cli.py
- sky/execution.py
This PR is a proposal to support `sky.Task` in launch/exec/spot_launch directly in addition to our previous `sky.Dag` API. That is because none of our users is using the dag abstraction for now and we do not support dag with more than 1 task in our programmatic API.
Tested:
> [UX/Programmatic API] Support task in launch/exec/spot_launch

- docs/source/conf.py
Removes version from docs html titles, which makes it easier to see in Google Analytics what page titles are popular across versions.
E.g., currently both `Managed Spot Jobs — SkyPilot 0.1.1 documentation` and `Managed Spot Jobs — SkyPilot 1.0.0-dev0 documentation` shows up as separate entries. This change would merge them.
Tested
> docs: Remove version from docs html titles.

- sky/data/storage.py
Closes #1281. 
The problem was stemming from gcsfuse not allowing directory renames, which is used by tensorflow-dataset. From gcsfuse docs:
> Renaming directories is by default not supported. A directory rename cannot be performed atomically in GCS and would therefore be arbitrarily expensive in terms of GCS operations, and for large directories would have high probability of failure, leaving the two directories in an inconsistent state.
> 
> However, if your application can tolerate the risks, you may enable renaming directories in a non-atomic way in gcsfuse starting v0.35.0, by setting --rename-dir-limit. If a directory contains fewer files than this limit and no subdirectory, it can be renamed.
This is a tradeoff between (cost, consistency) and functionality - you can have low cost …
> Set `--rename-dir-limit` for gcsfuse to allow dir renames

- docs/source/conf.py
- docs/source/reference/api.rst
- docs/source/reference/cli.rst
- sky/cli.py
- sky/execution.py
- sky/task.py
Changes
- Expose a subset of methods of `sky.Task` to docs
- Excluded:
- Experimental/internal-facing: `:exclude-members: estimate_runtime, get_inputs_cloud, set_time_estimator, sync_storage_mounts`
- Some undocumented methods
- "Hidden" methods `__rshift__, __repr__`
- CLI docs: tweak order.
Tested:
> Docs: polish `sky.Task` doc strings.

- sky/data/storage.py
Closes #1154.
`--implicit-dirs` flag for gcsfuse allows [implicitly defined directories](https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/docs/semantics.md#implicit-directories) to show up in mounts. 
The [gcsfuse documentation](https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/docs/semantics.md#implicit-directories) suggests this may have performance and cost implications. I did some simple performance measurements with and without `--implicit-dirs`. See benchmark numbers at the end.
* I don't see a significant performance difference with `--implicit-dirs` on or off. 
* It is hard to measure the cost implications, but I expect them to be [small](https://cloud.google.com/storage/pricing#operations-by-class).
* There exists an [alternative …
> [Storage] add `--implicit-dirs` for gcsfuse

- sky/data/mounting_utils.py
Closes #1319.
This is caused when a process holds onto a file on the mounted path. Our fix makes the unmounting lazy (similar to `umount -l`), which will detach the filesystem from the filesystem hierarchy immediately, and cleanup all references to the filesystem as soon as it is released by the offending process.
Tested:
```yaml
file_mounts:
/data:
name: sky-romilb-test
run: |
tail -f /dev/null > /data/myfile &
```
> [Storage] Add lazy unmount flag

- sky/templates/aws-ray.yml.j2
- sky/templates/azure-ray.yml.j2
- sky/templates/gcp-ray.yml.j2
Closes #950 
Thanks to @michaelzhiluo for identifying this issue and proposing the solution! The checking is used to avoid creating multiple `skylet` process, but our previous check will always have non-zero returncode.
Tested:
> [Core] Fix skylet checking

- sky/backends/backend_utils.py
- sky/skylet/log_lib.py
- sky/utils/command_runner.py
Closes #1169 
This PR removes the long stack trace due to the broken pipe. (The `--no-follow` is a better way to get rid of the broken pipe issue.)
Tested:
```
sky logs test-log | grep il                         
Tailing logs of the last job on cluster 'test-log'...
INFO: Tip: use Ctrl-C to exit log streaming (task will not be killed).
INFO: Waiting for task resources on 1 node. This will block if the cluster is full.
^C
Aborted!
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
```
> [UX] remove stacktrace for pipe and ssh info

- sky/core.py
- sky/data/storage.py
- sky/setup_files/setup.py
Closes #1321 
The is caused by ray installing `colorama` for third-party packages without version constraint ([here](https://github.com/ray-project/ray/blob/03b6bc7b5a305877501110ec04710a9c57011479/python/setup.py#L529)), which somehow breaks the dependency of `awscli==1.25.8`, which is used in our storage. 
After this fix, the user may need to install again with `pip install .` to make the dependency take effect.
This PR also fixes a little bit of the UX for the `sky storage delete`
Tested:
> [Dependency] Fix colorama dependency issue with awscli

- ROADMAP.md
To ease and align community contributions, this PR adds a roadmap doc, starting with directions for the next major release (v0.3).
The directions and detailed items are not meant to be totally comprehensive. That said, they cover the most actively discussed/worked-on items.
> Add roadmap.

- sky/backends/backend_utils.py
- sky/backends/cloud_vm_ray_backend.py
As discussed in #1206, this PR ensures that SKY_NODE_RANK is always 0 on the head node, and that it is assigned to the worker nodes in a stable fashion when executing tasks on multi-node clusters. 
To accomplish this, in each call to `_execute_task_n_nodes`, we create a map of internal node ips to their correct rank, and pass this map into the Ray code generator, which assigns to correct rank to each node.
Tested:
```
resources:
cloud: aws
disk_size: 1024
instance_type: m6i.large
workdir: .
num_nodes: 4
run: |
echo $SKY_NODE_RANK
```
> Fix SKY_NODE_RANK environment variable

- sky/spot/spot_utils.py
This PR attempts to fix #1328.
The problem could happen due to a race condition, where the cluster is removed due to the preemption, but the `spot_status` has not been set to the correct state yet. In that case, the `handle` will be `None` and fails the log tailing.
i.e., after the following lines the cluster can be already removed from the cluster table, but the `spot_status` has not been set to `RECOVERING` yet.
https://github.com/skypilot-org/skypilot/blob/a66aa263325cec34f28c36a7f16f7ca1b23d130d/sky/spot/controller.py#L101-L107
Tested:
> [Spot] Fix race condition for spot logs

- sky/templates/aws-ray.yml.j2
- sky/templates/azure-ray.yml.j2
- sky/templates/gcp-ray.yml.j2
This is a temporary fix for #1341
Tested:
```
resources:
cloud: aws
region: us-west-2
image_id: ami-0594ad5e1bbf8185f
```
```
set -e
for i in {1..10}; do
sky launch -y -c test-image$i ./test.yaml
sky down -y test-image$i
done
```
> [Image] Fix blocking by unattended-upgrade

- docs/source/running-jobs/distributed-jobs.rst
As discussed in #1336, this updates the docs to include a tip for how to store the cluster IPs to a file so that users can access it via SSH or manipulate it via other methods.
> Update `SKY_NODE_RANK` docs

- sky/cli.py
This pull request builds on https://github.com/skypilot-org/skypilot/pull/1207 by setting `user_requested_resources` appropriately and handling the autostop edge case.
Tested:
`sky {cpunode, gpunode}` on GCP:
I used print statements to verify `_launch_with_confirm` is called with the correct `retry_until_up` argument. 
I tested the autostop edge case by running:
I tested that `user_requested_resources` was set correctly by running:
@concretevitamin @Michaelvll
> Add `--retry-until-up`, `--region`, `--zone`, and `--idle-minutes-to-autostop` for interactive nodes (v2)

- sky/clouds/service_catalog/common.py
Currently, our style checker prints the below messages:
```
Sky Pylint:
************* Module sky.clouds.service_catalog.common
sky/clouds/service_catalog/common.py:240:16: E1130: bad operand type for unary ~: NoneType (invalid-unary-operand-type)
sky/clouds/service_catalog/common.py:240:16: E1130: bad operand type for unary ~: NoneType (invalid-unary-operand-type)
sky/clouds/service_catalog/common.py:240:16: E1130: bad operand type for unary ~: NoneType (invalid-unary-operand-type)
sky/clouds/service_catalog/common.py:240:16: E1130: bad operand type for unary ~: NoneType (invalid-unary-operand-type)
sky/clouds/service_catalog/common.py:240:16: E1130: bad operand type for unary ~: NoneType (invalid-unary-operand-type)
```
This PR fixes it.
> Minor fix for yapf warnings

- docs/source/reference/storage.rst
- examples/perf/results.md
Fixes some incorrect statements about storage mounting in our perf benchmark.
> [Docs] Clarify Storage mounting details

- sky/clouds/service_catalog/data_fetchers/fetch_gcp.py
Fixes #1367 
This PR basically rolls back the changes in our GCP crawler by PR #1204. When using the new catalog, the GCP A100 prices will be correct.
Tested:
> Fix bugs in GCP A100 prices

- sky/backends/backend_utils.py
- sky/backends/cloud_vm_ray_backend.py
- sky/backends/onprem_utils.py
- sky/resources.py
Adds support for the 1080, 2080, A5000, A6000 GPU types (GPUs NOT supported by Ray's backend) and allows scheduling for such types.
Also, fixes the bug introduced in #1287.
`sky status`
```
Local clusters:
NAME                USER    HEAD_IP        RESOURCES                 COMMAND                         
shelby              ubuntu  3.144.21.13    [{'V100': 1}]             sky exec shelby --gpus V1...    
thomas              ubuntu  3.94.208.15    [{'1080': 1, '2080': 1}]  sky launch -c thomas --gpus... 
```
- `sky launch -c thomas --gpus 1080:1 -- 'echo hi'` works and occupies the right placement groups
- `sky launch -c shelby --gpus V100:1 -- 'echo hi'` still works and occupies the right placement group (+ Ray's automatic `GPU` placement group)
> [Onprem] Support for Different Type of GPUs + Small Bugfix

- docs/source/examples/spot-jobs.rst
- docs/source/getting-started/tutorial.rst
- examples/spot/bert_qa.yaml
Tested:
- Ran on both AWS and GCP.
> Pin `torch` in various examples to avoid cuda version issues.

- sky/cli.py
- sky/core.py
Before:
```
» sky cancel stopped-cluster 2    
....
File "/Users/zongheng/Dropbox/workspace/riselab/sky-computing/sky/cli.py", line 1586, in cancel
raise e
File "/Users/zongheng/Dropbox/workspace/riselab/sky-computing/sky/cli.py", line 1582, in cancel
core.cancel(cluster, all, jobs)
File "/Users/zongheng/Dropbox/workspace/riselab/sky-computing/sky/utils/common_utils.py", line 209, in _record
File "/Users/zongheng/Dropbox/workspace/riselab/sky-computing/sky/core.py", line 422, in cancel
handle = _check_cluster_available(cluster_name, 'cancelling jobs')
File "/Users/zongheng/Dropbox/workspace/riselab/sky-computing/sky/core.py", line 336, in _check_cluster_available
f'{colorama.Fore.YELLOW}Cluster {cluster_name!r} is not up '
sky.exceptions.ClusterNotUpError: …
```
> Minor UX fix: `sky cancel` should not print stacktraces.

- sky/backends/backend_utils.py
- sky/backends/cloud_vm_ray_backend.py
- sky/utils/command_runner.py
Our user raises that the ssh-agent forwarding fails for the setup step. The main reason caused by that we are using ssh connection sharing for the setup stage, which will make the `ssh-add` not take effect immediately when there is a master connection in the background without the forwarding setup.
Tested:
1. `ps aux | grep ssh | awk '{print $2}' | xargs kill`
2. `sky launch -c test-ssh test.yaml` (fails due to key permission)
```
setup: |
git clone git://my-private-repo
```
3. `eval $(ssh-agent -s); ssh-add ~/.ssh/id_rsa`
4. `sky launch -c test-ssh test.yaml` succeeded (previously, this will fail due to the previous master connection still connected)
> [UX] Disable ssh connection sharing for setup

- sky/backends/backend_utils.py
- sky/backends/onprem_utils.py
- sky/optimizer.py
Fixes #1381.
- `sky launch` on a manually provisioned AWS machine (with no credentials).
```
ubuntu@ip-172-31-37-168:~/skypilot/sky$ sky launch
Defaulting to local cloud as there are no enabled public clouds in `sky check`.
Error: Specify -c [local_cluster] to launch on a local cluster.
See `sky status` for local cluster name(s).
```
> Fix Logging for `sky launch` on new machine

- docs/source/reference/yaml-spec.rst
- examples/per_region_images.yaml
- sky/backends/cloud_vm_ray_backend.py
- sky/cli.py
- sky/clouds/aws.py
- sky/clouds/gcp.py
- sky/clouds/service_catalog/__init__.py
- sky/clouds/service_catalog/aws_catalog.py
- sky/clouds/service_catalog/azure_catalog.py
- sky/clouds/service_catalog/common.py
- sky/clouds/service_catalog/gcp_catalog.py
- sky/core.py
- sky/execution.py
- sky/resources.py
- sky/utils/schemas.py
- tests/test_smoke.py
Closes #1345 
Main changes:
1. Support a dict for `image_id`
2. Added 3 smoke tests for the image_id dict.
Notes:
1. The failover will only go through the regions listed in the `image_id`.
3. If a region or zone is specified and not in the `image_ids`, it will throw an error.
4. If a task to be run on a existing cluster has a different `image_id` (even if it is the same in the same region the cluster is in), we will just error out.
Tested:
```
resources:
cloud: aws
image_id:
us-east-1: ami-0fb70a87623506e3e
us-west-2: ami-03e40ee6f58eea284
```
```
resources:
cloud: aws
image_id:
us-east-1: ami-0fb70a87623506e3e
us-west-2: invalid
```
> [Image] Support passing AMIs for different regions

- examples/env_check.yaml
- sky/backends/cloud_vm_ray_backend.py
- tests/test_smoke.py
> [Setup] unset CUDA_VISIBLE_DEVICES for detach setup

- sky/backends/cloud_vm_ray_backend.py
- sky/cli.py
- sky/core.py
- sky/spot/controller.py
- sky/spot/spot_state.py
- sky/spot/spot_utils.py
- sky/task.py
- tests/test_smoke.py
Fixes #1399 
Also, fixes the testing for the `SKYPILOT_JOB_ID`.
~~This PR also adds the `SKYPILOT_JOB_ID` to the `sky spot queue -a` to make it easier for the user to find.~~
```
(sky-dev) ➜  sky-experiment-dev (fix-sky-job-id) sky spot queue -a                                                                                                                                                                               ✱
Fetching managed spot job statuses...
Managed spot jobs:
In progress jobs: 1 STARTING
ID  NAME                            RESOURCES     SUBMITTED                      TOT. DURATION  JOB DURATION  #RECOVERIES  STATUS             STARTED                        CLUSTER                    REGION     SKYPILOT_JOB_ID                           
14  sky-9e85-zhwu …
```
> [Spot] Keep SKYPILOT_JOB_ID the same for the same spot job

- sky/backends/backend_utils.py
- sky/backends/onprem_utils.py
- sky/cli.py
- sky/optimizer.py
Related to #1382
The following are tested in `docker run -it continuumio/miniconda`:
Previously, 
```
> sky launch
sky launch
I 11-12 09:38:00 optimizer.py:881] No resource satisfying None on [].
sky.exceptions.ResourcesUnavailableError: No launchable resource found for task sky-cmd. To fix: relax its resource requirements.
Hint: 'sky show-gpus --all' to list available accelerators.
'sky check' to check the enabled clouds.
> sky launch -c test
sky.exceptions.ResourcesUnavailableError: No launchable resource found for task sky-cmd. To fix: relax its resource requirements.
Hint: 'sky show-gpus --all' to list available accelerators.
'sky check' to check the enabled clouds.
> sky check
> sky launch
File "/opt/conda/envs/sky/bin/sky", line 8, in <module> …
```
> [UX] fix the error for the first time `sky launch`

- sky/setup_files/setup.py
This PR removes the dark mode switcher for pypi description due to lack of support from PyPi.
Tested:
- https://test.pypi.org/project/skypilot/0.2.1rc2/
> [Release] Fix pypi description

- sky/setup_files/setup.py
> [Release] Fix pypi description (#1416)

- sky/backends/cloud_vm_ray_backend.py
When Skypilot infers the head_ip from the Ray output message, it can capture a few extra characters (“’\n\x1b[0m”) which end up beinbg appended to the IP, which causes failures if you try to use the command runner. This PR replaces that capture with a regex to exactly match the IP.
> [Bug fix] head_ip extraction from Ray stdout

- docs/source/reference/faq.rst
- sky/clouds/service_catalog/data_fetchers/analyze.py
- sky/clouds/service_catalog/data_fetchers/fetch_aws.py
- sky/clouds/service_catalog/data_fetchers/fetch_azure.py
- sky/clouds/service_catalog/data_fetchers/fetch_gcp.py
- sky/setup_files/MANIFEST.in
Previously, the user cannot find the `data_fetchers` in the spot controller (or the user installing skypilot with pypi) because we did not include them in the skypilot wheel (missing `__init__.py`). As the `data_fetchers` are important for users who want to use the global regions, we would like to have them in the wheel.
The main change is to add `__init__.py`, and the other changes are mainly for formatting, as our formatter did not consider those files without the `__init__.py` file.
https://skypilot.readthedocs.io/en/latest/reference/faq.html#advanced-how-to-make-skypilot-use-all-global-regions
Tested:
- Launch a CPU instance, run the following commands on the VM.
> [Global Regions] Add data fetchers into wheel

- sky/spot/controller.py
- sky/spot/recovery_strategy.py
- sky/spot/spot_utils.py
- tests/test_smoke.py
> [Spot] Let cancel interrupt the spot job

- sky/authentication.py
- sky/backends/backend_utils.py
- sky/templates/aws-ray.yml.j2
- sky/templates/azure-ray.yml.j2
- sky/templates/gcp-ray.yml.j2
- tests/backward_comaptibility_tests.sh
Closes #1425 
This PR uses the cloud-init to setup the authorized keys to avoid using `ec2.describe_key_pairs` reducing the permission requirement.
Backward compatibility should be guaranteed by our old yaml content restoring mechanism.
Tested:
`rm ~/.ssh/sky-key*`
> [AWS] Avoid key pair permission issue by using cloud-init for authorized keys

- sky/backends/cloud_vm_ray_backend.py
Previously, a `sky spot launch echo hi` will show an extra line (see `***` line):
```
...
I 11-18 18:05:20 cloud_vm_ray_backend.py:2128] Setup completed.
I 11-18 18:05:24 cloud_vm_ray_backend.py:2193] Job submitted with Job ID: 12
I 11-19 02:08:05 cloud_vm_ray_backend.py:2500] Job ID not provided. Streaming the logs of the latest job. ***
I 11-19 02:08:06 log_lib.py:388] Start streaming logs for spot job 12.
INFO: Tip: use Ctrl-C to exit log streaming (task will not be killed).
INFO: Waiting for task resources on 1 node. This will block if the cluster is full.
```
This seems a bit confusing. This PR removes it.
> Minor spot logs fix: don't print job id not provided on spot launch.

- sky/clouds/service_catalog/data_fetchers/fetch_gcp.py
This PR removes the hardcoded URL we use for fetching A2 machine prices. Instead of directly getting A2 machine prices, we first obtain A2 machine "total" cost, which is A2 host VM price + A100 GPU price, from the GCP website (https://cloud.google.com/compute/vm-instance-pricing). Then we get the true A2 host machine price by deducting the A100 (or A100-80GB) GPU price from the total cost.
This PR also fixes a bug that our current GCP catalog does not contain the A2 machines in `us-west1-b`. This bug happens because https://cloud.google.com/compute/docs/regions-zones is not correct.
> [Catalog] Remove hardcoded A2 pricing URL & Fix a bug in A2 machine zones

- sky/usage/usage_lib.py
- sky/utils/common_utils.py
This PR is to robustify the user hash, to avoid getting empty user hash from the file. It could happen before when the program crashed before writing to the file.
https://github.com/skypilot-org/skypilot/blob/48d4a84865821b468d0a608ef4860d7f352859f0/sky/utils/common_utils.py#L55-L56
> [Usage] Robustify the user hash to avoid empty string

- sky/cli.py
- sky/spot/recovery_strategy.py
Fix a few logging UX issues:
1. Previously:
```
» sky spot logs 3                                                                                                                 
Spot controller sky-spot-controller-8a3968f2 is INIT.
Please wait for the controller to be ready.
sky.exceptions.ClusterNotUpError
```
This PR removes the last line.
2. Previously, the controller log for a preempted spot job shows:
The red text is part of the "Exception" in the line above, but looks weird when joining with `)`. This PR rearranges it a bit.
3. Previously `sky spot status` shows:
```
WARNING: `status` is deprecated and will be removed in a future release. Please use `queue` instead.
```
This may be a bit confusing as to whether it also refers to `sky status`. This PR makes it more clear.
> Logging fixes.

- examples/managed_spot_with_storage.yaml
- examples/using_file_mounts.yaml
- sky/backends/cloud_vm_ray_backend.py
- sky/cloud_stores.py
> [Storage] Fix copy monuts for file with s3 bucket url

- sky/authentication.py
- sky/utils/common_utils.py
I'm in a network where pinging Google results in 100% packet loss:
```
» ping google.com
PING google.com (172.217.163.46): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
Request timeout for icmp_seq 2
Request timeout for icmp_seq 3
Request timeout for icmp_seq 4
^C
--- google.com ping statistics ---
6 packets transmitted, 0 packets received, 100.0% packet loss
```
This means I can't launch GCP clusters. This PR adds some error messages to hint at what's up:
```
» sky cpunode -t n2d-highmem-96 --down -y                                                                                130 ↵
...
I 11-28 07:48:51 cloud_vm_ray_backend.py:988] To view detailed progress: tail -n100 -f /Users/zongheng/sky_logs/sky-2022-11-28-07-48-50-387576/provision.log
E 11-28 07:49:52 …
```
> Print errors for GCP timeout.

- sky/backends/cloud_vm_ray_backend.py
- sky/skylet/autostop_lib.py
- sky/skylet/configs.py
- sky/skylet/events.py
- tests/test_smoke.py
Support restarting the autostop timer via
- `sky autostop --cancel` then `sky autostop -i <minutes>`
- submitting a job
This is requested by a user, and possibly also can close #1418 (TBD).
Tested:
```
» cat test_db.py
from sky.skylet.autostop_lib import set_last_active_time_to_now
set_last_active_time_to_now()
» for i in {1..200}; do python -u test_db.py &; done; wait
```
```
» sky launch -i1 -c autostop     
» for i in {1..30}; do sky exec autostop echo hi; done
```
> [autostop] Support restarting the autostop timer.

- sky/spot/controller.py
- sky/spot/recovery_strategy.py
- tests/test_smoke.py
A user found the `cluster_status` to be `None`, at the place we modified. It seems to be a very rare case, where the controller can connect to the spot cluster with ssh to check the job status, but found the whole cluster is preempted right after the succeeded ssh. However, it is good to make sure that won't cause a problem.
The following is the error from the user:
```
(segm-4-nodes pid=2494) I 11-28 14:41:32 spot_utils.py:67] ==================================
(segm-4-nodes pid=2494) I 11-28 14:41:54 spot_utils.py:58] === Checking the job status... ===
(segm-4-nodes pid=2494) I 11-28 14:41:57 spot_utils.py:64] Job status: JobStatus.RUNNING
(segm-4-nodes pid=2494) I 11-28 14:41:57 spot_utils.py:67] ==================================
(segm-4-nodes pid=2494) E 11-28 14:41:59 …
```
> [Spot] Make sure the cluster status is not None when showing

- sky/backends/backend_utils.py
- sky/backends/cloud_vm_ray_backend.py
A hotfix to temporarily close https://github.com/skypilot-org/skypilot/issues/1468. We may need to modify the controller logic to make it more future proof. 
The issue is: When preemption happens, our spot controller won't cleanup preempted VMs before running another `sky launch`. This causes two VMs to co-exist and both the preempted one and the recovered one will be returned.
> Hotfix for spot TPU pod recovery

- sky/backends/backend_utils.py
- sky/cli.py
- sky/core.py
- tests/test_smoke.py
- tests/test_spot.py
Fixes #1447.
If controller is to be started:
- disallow: -i, --down; disallow being specified with other clusters
Tested:
CLI
```
sky start sky-cpunode-zongheng sky-spot-controller-8a3968f2
sky start sky-spot-controller-8a3968f2 -i1
sky start sky-spot-controller-8a3968f2 -i1 --down
sky start sky-spot-controller-8a3968f2 --down
sky start sky-spot-controller-8a3968f2  
sky start sky-spot-controller-8a3968f2 --force 
```
Python API
Smoke
> Make `sky start` on the spot controller aware of autostop.

- sky/backends/backend_utils.py
Currently, in `get_node_ips`, we continue retrying even if the call to `ray get-worker-ip` succeeds. This PR fixes that.
> Fix bug with retrieving node IPs

- sky/cli.py
- sky/core.py
Fixes a bug introduced in #1453 where starting the controller via the CLI raises a ValueError.
Tested:
CLI
```
sky start sky-cpunode-zongheng sky-spot-controller-8a3968f2
sky start sky-spot-controller-8a3968f2 -i1
sky start sky-spot-controller-8a3968f2 -i1 --down
sky start sky-spot-controller-8a3968f2 --down
sky start sky-spot-controller-8a3968f2  
sky start sky-spot-controller-8a3968f2 --force 
```
Smoke
> Fix start spot controller bug.

- sky/backends/backend_utils.py
- sky/backends/cloud_vm_ray_backend.py
- tests/test_smoke.py
This fixes the following issues with the new `ResourceHandle` introduced in #1380.
- For clusters from the older version that are in INIT status, `sky status -r` will not update them to the latest version, causing the IPs for these clusters to be queried on each call which is slow. This PR updates it such that these clusters will be updated to the latest version on refresh.
- #1480: fixes the handling of TPU pods 
- ~The `external_ips` and `internal_ips` methods should always return a list as that is what is expected by the rest of the code~
Tested:
> Fix `ResourceHandle` semantics

- sky/backends/backend_utils.py
- sky/backends/cloud_vm_ray_backend.py
- sky/spot/controller.py
- sky/spot/recovery_strategy.py
This PR implements a better fix for https://github.com/skypilot-org/skypilot/issues/1468.
The preempted VM has to be cleaned up otherwise it'd occupy the quota.
Another choice is to modify the Autoscaler node provider, but I think that might complicate the semantic of `create_node` function. because for normal compute VM, we instead want to keep and reuse the preempted resources.
https://github.com/skypilot-org/skypilot/blob/1955bee5a337508af67de28615ed03a594fa30cf/sky/skylet/providers/gcp/node_provider.py#L178
Explicitly calling `terminate_cluster` on higher level might be better. @Michaelvll wdyt?
https://github.com/skypilot-org/skypilot/blob/1955bee5a337508af67de28615ed03a594fa30cf/sky/spot/recovery_strategy.py#L99
TODO
> Clean up preempted resources for TPU

- .github/workflows/pylint.yml
- .github/workflows/pytest-generic.yml
- .github/workflows/pytest.yml
- .github/workflows/yapf.yml
This fixes the GitHub CI, because the GitHub runner recently updated the OS used by `ubuntu-latest` to `ubuntu-22.04`, which does not support python 3.6 anymore, as mentioned in https://github.com/actions/runner-images/issues/6399.
https://github.blog/changelog/2022-12-01-github-actions-larger-runners-using-ubuntu-latest-label-will-now-use-ubuntu-22-04/
PS, we may also want to consider deprecating the Python 3.6 support #609 
This PR separates the CI fix from #1493 and #1489. 
Tested:
- the github CI is green now.
> [Tests] Fix github CI

- sky/clouds/service_catalog/aws_catalog.py
- sky/clouds/service_catalog/data_fetchers/fetch_aws.py
Our user requested to use `ap-east-1` region, we now enable this for the user so that the auto-updated catalog works.
> [AWS] Add regions requested by the user

- docs/source/examples/spot-jobs.rst
- examples/spot/bert_qa.yaml
- sky/data/storage.py
This is a quick patch to make s3 exclude `.git` for https://github.com/skypilot-org/skypilot/issues/1485. However, this might be a surprising behavior to some users.
Alternative is to implement our own code to read `.gitignore` and generate corresponding directories to exclude (i.e., parsing those `**/*.pyc` syntax ourselves)
Should we implement that?
Note `sky launch` will respect `.gitignore` and putting `.git/` inside is enough to exclude the directory. or should we make it default for all `rsync`?
Tested
> Exclude .git for cloud storage

- sky/skylet/configs.py
This PR is to mitigate the problem in #1507
Enable the WAL mode for the database we are using for autostop to eliminate the undesired locking.
After this PR, the snippet in #1507 fails 1/30, while it fails 30/30 when using the current master branch.
```
import time
from multiprocessing.pool import Pool
def import_skylet_config(i):
from sky.skylet import configs
print('Process', i)
configs.set_config('autostop_last_active_time', str(time.time()))
if __name__ == '__main__':
cnt = 0
total = 30
for i in range(total):
try:
with Pool(100) as p:
p.map(import_skylet_config, range(10000))
except Exception as e:
print(e)
cnt += 1
print('Failed', cnt, 'times out of', total)
```
Future TODO:
> [sqlite] Mitigate the database locked problem for skylet config

- sky/utils/command_runner.py
- tests/test_smoke.py
#1190 introduced a bug for downloading the logs from the remote cluster, as we are giving the `runner.rsync` the wrong source path (resolved the path locally, though it is a remote path). This PR fixes the issue.
Reproducible code:
```
sky launch -i10 -c master-branch "echo hi"
sky logs master-branch 1 -s  
```
The downloaded folder does not contain any `run.log`.
TODO:
> [Logs] Fix logs download

- sky/backends/backend_utils.py
- sky/execution.py
- sky/templates/aws-ray.yml.j2
- sky/templates/spot-controller.yaml.j2
Tag all SkyPilot AWS nodes with `skypilot-user: $USER`.
This works for spot controller-launched nodes too.
NOTE
- All existing nodes will continue to function and will not be tagged
- All new nodes will be tagged
Two users have requested this, for
- seeing who launched what in a shared-account scenario
- programmatically tracking all SkyPilot-launched VMs (for cost reporting)
**Tested**:
1. Two-node cluster:
2. A controller-launched cluster
2. Backward compat:
on master
- launch a spot controller 
- wait for it to autostop
switch to this branch
- spot launch
> Tag all SkyPilot AWS nodes with "skypilot-user: $USER".

- sky/clouds/local.py
Add return values to `validate_region_zone` for local cloud because it is expected. For instance, see [here](https://github.com/skypilot-org/skypilot/blob/master/sky/resources.py#L275).
@michaelzhiluo
> Add return value to `validate_region_zone` for local cloud

- sky/backends/backend_utils.py
- sky/cli.py
Closes #1161.
We now clean up the username (used as suffix in the cluster name) by:
1. Making all characters lowercase
2. Removing any non-alphanumeric characters (excluding hyphens)
3. Removing any numbers and/or hyphens at the start of the username.
4. Removing any hyphens at the end of the username
e.g. `1SkY-PiLot2-` becomes `sky-pilot2` when it is used for generating cluster name.
Manual tests by overriding the username read by getpass.getuser():
> [Provisioner] Generate valid cluster names when username has invalid characters

- sky/adaptors/aws.py
- sky/adaptors/gcp.py
- sky/backends/cloud_vm_ray_backend.py
- sky/clouds/aws.py
- sky/clouds/cloud.py
- sky/clouds/gcp.py
- sky/data/storage.py
- sky/resources.py
This PR adds the check for the image size and existence, so that any problematic image id will fail early. It should also fix #1506 
```
ValueError: Image 'ami-0729d913a335efca7' is 45GB, which is larger than the specified disk_size: 40 GB. Please specify a larger disk_size.
```
```
ValueError: Image 'projects/deeplearning-platform-release/global/images/common-cu113-v20220701' is 50.0GB, which is larger than the specified disk_size: 40 GB. Please specify a larger disk_size.
```
```
ValueError: Image 'ami-0729d913a335efca7' is 45GB, which is larger than the specified disk_size: 40 GB. Please specify a larger disk_size.
```
> [Image] Check image size and existence

- sky/backends/cloud_vm_ray_backend.py
Fixes #1527. It will now rsync to a file that will not be deleted.
> [Onprem] Fix `run.log` not appearing during `run` when laptop = local cluster

- sky/backends/onprem_utils.py
Fix #1530. It is possible that preinstalled python and Ray versions are not up to date with Sky's requirements. In this case, we need to detect this and raise an error.
> [Onprem] Add check for Python versions

- sky/resources.py
- sky/spot/controller.py
- sky/spot/recovery_strategy.py
- tests/test_smoke.py
https://github.com/skypilot-org/skypilot/pull/1500 didn't consider the case when `cloud` is not specified by users and a bug will be triggered during recovery.
This PR fixes it by checking the `launched_resources` in `handle` to make sure cloud is not `None`.
====
Details:
The reason why I introduce `self.launched_resources` in `StrategyExecutor` is because the `handle` returns by
```
(cluster_status,
handle) = backend_utils.refresh_cluster_status_handle(
self._cluster_name, force_refresh=True)
```
in `controller.py` could be `None` if the spot VM is preempted. I thought adding `self.launched_resources` under `StrategyExecutor` would be a better design.
Please let me know if there's a better alternative.
====
- Add a new …
> Bugfix for spot controller

- docs/source/reference/storage.rst
- examples/storage/pingpong.yaml
- examples/storage_demo.yaml
- sky/design_docs/onprem-design.md
Simple documentation fix.
"it's" = "it is"
"its" = possessive
> Simple documentation fix

- sky/backends/backend_utils.py
(related to #1513) This PR fixes the identity check for the `sky status -r` as it does not go through `refresh_cluster_status_handle`.
> [User identity] Fix identity check

- sky/execution.py
Before
```
» sky exec dbg2 echo hi                                                                                                                                                          1 ↵
Task from command: echo hi
Executing task on cluster dbg2...
sky.exceptions.ClusterNotUpError: Executing tasks on: skipped for cluster 'dbg2' (status: INIT). It is only allowed for UP clusters.
```
After
```
» sky exec dbg2 echo hi
Task from command: echo hi
Executing task on cluster dbg2...
sky.exceptions.ClusterNotUpError: Executing tasks: skipped for cluster 'dbg2' (status: STOPPED). It is only allowed for UP clusters.
```
> Minor logging fix.

- sky/backends/backend_utils.py
- sky/backends/cloud_vm_ray_backend.py
- sky/clouds/gcp.py
- sky/resources.py
- sky/utils/tpu_utils.py
Our user observe that terminating an TPU VM can cause a infinite recursion (checked with py-spy) for status refreshing and tearing down the cluster. The reason could be the following:
1. The spot TPU VM is in the local cluster cache table, but already terminated in the console.
2. When the user try to terminate the cluster with `sky down cluster-name`, SkyPilot tries to refresh the cluster status using gcloud and try to clean up the TPU VM as we cannot find the cluster in the console. https://github.com/skypilot-org/skypilot/blob/1ad086874dc51751232ea7fa540c975709d915a5/sky/backends/backend_utils.py#L1610-L1613
3. In the `teardown_no_lock`, we will call the refresh again causing the infinite recursion. …
> [TPU VM] Avoid infinite recursion when cleaning up spot TPU VM

- sky/skylet/autostop_lib.py
It looks like `__set_state__` is being used for setting `down=False` during deserialization. However, this is a typo so it never works (https://docs.python.org/3/library/pickle.html#object.__setstate__). Also it does not look like `state.setdefault` will work as `self.down` is always set.
@Michaelvll could you confirm its the original intention is for deserialization? Otherwise, we should remove it as it is not been used in other places.
> [autostop] setstate instead of set_state

- sky/backends/backend_utils.py
- sky/setup_files/setup.py
This is to update the azure cli and ray version to avoid strict version pinning.
- Create a docker container and install skypilot; `az login`; `sky launch -c azure-test --cloud azure`
> [setup] Allow newer version of azure cli and ray

- sky/data/storage.py
Switch to using a newer version of GCSFuse to address issue from slack:
> user observed that when they tried to continuously read from the mounted GCS bucket with multiple processes (about 40, each process may read different files), the gcsfuse seems stuck causing failure for reading files (ls also stuck in the folder).
> [Storage] Bump gcsfuse version to 0.41.10

- sky/backends/backend_utils.py
- sky/core.py
Required by our user. This Pr adds `cluster_names` argument to `sky.status`, so the user can query/refresh the status for part of the clusters.
- `sky.status('non-exist')` returns empty list
- `sky.status('sky-spot-controller-...')  returns the stopped status
- `sky.status(['mycluster1', 'mycluster2'], refresh=True)` where both clusters exist
- `sky.status(['mycluster1', 'non-exists'], refresh=True)`
> [API] Add support for specifying the clusters to query

- sky/backends/backend_utils.py
- sky/execution.py
Per user request, this PR supports per-region ssh proxy command.
Here is the new `~/.sky/config.yaml`:
```
aws:
#
#
vpc_name: skypilot-vpc
#
#
use_internal_ips: True
#
#
#
us-east-1: ssh -W %h:%p -i ~/.ssh/key1 -o StrictHostKeyChecking=no ec2-user@ip1
us-east-2: ssh -W %h:%p -i ~/.ssh/key2 -o StrictHostKeyChecking=no ec2-user@ip2
```
TODO:
> [AWS] Support per-region ssh proxy command

- sky/usage/loki-s3-config.yaml
This fix the issue that our hosted loki server cannot be executed on a smaller instance. After increasing the timeout, the loki server can now be run on a1.xlarge instance, which is 73% cheaper than the previous m6i.2xlarge.
> [Usage] Increase timeout for queries

- sky/clouds/local.py
Fixes #1580. Sky Onprem will not error out anymore with the new Sky optimizer.
> [Onprem] Update Onprem with the New Optimizer

- sky/global_user_state.py
- sky/skylet/configs.py
A user experienced the database locked problem for her spot jobs again #1509 ([detailed logs](https://gist.github.com/Michaelvll/ef9757fa4752300c6714a734c322cf85))
The problem is caused by the sqlite command is called whenever the `autostop_lib`  module is imported, even though it is not used, creating a lot of concurrent sqlite commands.
To mitigate the problem, this PR ensures the commands are only called when needed. Also, we changed to using `cursor` to run the command for setting WAL mode instead of `connection`.
- `sky launch --use-spot --cloud gcp -i 1 echo hi` and check the `~/.sky/skylet.log`
- `sky status -r`
- `sky spot launch -n test-autostop --cloud gcp "echo hi; sleep 1800; echo bye"` and check `sky logs sky-spot-controller...` no database …
> [sqlite] Do not run sqlite when autostop is imported to avoid database locked

- sky/backends/cloud_vm_ray_backend.py
- sky/cli.py
- sky/core.py
- sky/spot/spot_state.py
- sky/spot/spot_utils.py
- sky/utils/cli_utils/status_utils.py
Addresses #1565, #1570, #1482 and various other bug fixes/small additions:
* Add move hourly price computation from `status_utils` to `get_hourly_price` method so it can be accessed after `core.status`
* Added confirmation before cancelling jobs
* Remove confirmation when `--yes` is specified for `sky down` of spot controller
* Add `--skip-finished` flag to `sky spot queue`
* Color statuses in `sky spot queue`
> Various UX Fixes

- sky/backends/backend_utils.py
- sky/backends/cloud_vm_ray_backend.py
- sky/skylet/providers/aws/config.py
- sky/skylet/providers/aws/node_provider.py
- sky/utils/accelerator_registry.py
User trying out private VPC triggered the following error, because it hits a zone that doesn't have a private subnet, and the node provider threw `cli_logger.abort()` that crashed the whole program rather than triggering failover.
```
I 01-04 21:07:45 cloud_vm_ray_backend.py:1377] Launching on AWS us-east-1 (us-east-1c)
I 01-04 21:07:50 cloud_vm_ray_backend.py:733] ====== stdout ======
2023-01-04 21:07:46,516	INFO commands.py:270 -- Cluster: generate-embeddings
2023-01-04 21:07:47,009	INFO commands.py:349 -- Checking External environment settings
2023-01-04 21:07:47,009	VINFO utils.py:150 -- Creating AWS resource `ec2` in `us-east-1`
2023-01-04 21:07:49,416	VINFO utils.py:150 -- Creating AWS resource `iam` in `us-east-1`
2023-01-04 21:07:49,818	VINFO utils.py:150 -- Creating AWS resource …
```
> AWS/private VPC: make no-usable-subnet errors trigger failover.

- sky/cli.py
- sky/execution.py
- sky/spot/recovery_strategy.py
- sky/task.py
Fixes #1553.
- Hint for unmanaged spot
- Some logging changes in `sky spot queue [-s]`
`spot queue` logging:
Checked that `sky launch --use-spot` (unmanaged) prints:
Checked that `sky spot launch` then `sky logs <controller>` (managed) does not print the above.
> UX: hint for unmanaged spot; spot queue logging.

- sky/cli.py
- sky/optimizer.py
- sky/templates/azure-ray.yml.j2
- sky/templates/gcp-ray.yml.j2
For better accountability.
**Tested (run the relevant ones):**
GCP head + worker (note: they have "labels" and "tags"; former is used):
Azure head + worker:
Also tested (previously was throwing an error from within optimizer, `No resource satisfying None on Azure`):
```
» sky launch --use-spot -i10 --down --cloud azure
Usage: sky launch [OPTIONS] [ENTRYPOINT]...
Try 'sky launch -h' for help.
Error: SkyPilot currently has not implemented support for spot instances on Azure. Please file an issue if you need this feature.
```
> GCP/Azure: add `skypilot-user` tags to VMs on these clouds.

- sky/backends/cloud_vm_ray_backend.py
- sky/optimizer.py
Fixes #1584 
- Any manual or new tests for this PR (please specify below)
> [core] Respect the block list when failover

- sky/global_user_state.py
To reproduce the problem:
1. `sky launch -c min` with the commit before #1301 
2. `ssh min; ray stop`
3. switch to the latest master. `sky status -r`
Since we will call the `global_user_state.add_or_update_cluster` with the `requested_resources=None` in the following line, the status refresh will fail. 
https://github.com/skypilot-org/skypilot/blob/6fd21d7fadb65e2f889e47f9616ef4e54a22f72e/sky/backends/backend_utils.py#L1965
> Fix backward compatibility for cost tracking

- sky/backends/cloud_vm_ray_backend.py
- sky/spot/controller.py
- sky/spot/recovery_strategy.py
- tests/conftest.py
- tests/test_smoke.py
- tests/test_yamls/failed_setup.yaml
This PR reverts #1579, because if the cluster is preempted during the setup stage of a recovery, the changes in #1579 will fail the whole job instead of trying again or moving to another region. cc @infwinston 
Reproducible process:
1. `sky spot launch long-setup.yaml`
2. Delete the instance on the console during the setup process
3. The spot job fails directly.
Future TODO:
> Revert spot job setup failure handling (revert #1579)

- sky/skylet/job_lib.py
- sky/skylet/log_lib.py
Fixes #1607.
```
» sky logs sky-spot-controller-8a3968f2  1099
Tailing logs of job 1099 on cluster 'sky-spot-controller-8a3968f2'...
Job 1099 not found (see `sky queue`).
Shared connection to 34.27.229.46 closed.
```
> [UX] Make `sky logs <nonexistent job id>` not error out.

- sky/backends/backend_utils.py
- sky/backends/cloud_vm_ray_backend.py
A user reports that sometimes `ssh cluster-name` will complain about `REMOTE HOST IDENTIFICATION HAS CHANGED` error.
> [UX] Avoid known hosts check

- sky/backends/cloud_vm_ray_backend.py
This PR fixes a problem introduced by #1585, which assume the `zones` to be a list while it can be NoneType, causing the following error during `pytest tests/test_smoke.py::test_azure_start_stop`. This is another evidence for the importance of #1564 ; )
```
File "/home/gcpuser/skypilot/sky/utils/common_utils.py", line 239, in _record
File "/home/gcpuser/skypilot/sky/backends/cloud_vm_ray_backend.py", line 1637, in provision_with_retries
config_dict = self._retry_region_zones(
File "/home/gcpuser/skypilot/sky/backends/cloud_vm_ray_backend.py", line 1103, in _retry_region_zones
for zone in zones:
TypeError: 'NoneType' object is not iterable
^[[31mFailed^[[0m.
Reason: sky start -y t-azure-start-stop-c884-b5
Log: less /tmp/azure-start-stop-3h69lw1t.log
```
Tested …
> [Azure] Fix azure launch

- sky/spot/spot_state.py
- sky/spot/spot_utils.py
- tests/test_smoke.py
This PR patches #1479 which left out the `FAILED_SETUP` in the terminal_statuses. The problem would cause leakage of the spot cluster after the `FAILED_SETUP` happened.
> Fix spot terminal status

- sky/authentication.py
- tests/test_smoke.py
Fixes https://github.com/skypilot-org/skypilot/issues/1616 in which `sky launch` was stuck forever during `ray up`.
-  Tested with the Ubuntu Server 20.04 LTS (HVM) AMI
```sky launch -c ubuntu2004 --cloud aws --region us-east-1 --image-id ami-0778521d914d23bc1```
> Fix ubuntu ami

- sky/authentication.py
Closes #1626 by 1) moving the sky check suggestion to the end and 2) explicitly stating that sky check is the fix.
> [UX] Clarify fix for GCP disabled API error

- sky/backends/backend_utils.py
Fixes UX issue of #1633
```
sky launch -y -d -c test --num-nodes 2 --cloud gcp tests/test_yamls/minimal.yaml
sky status test --refresh
sky autostop -y test -i 1
sleep 120
sky status test --refresh
```
> Fix status refresh logging

- tests/test_smoke.py
Aims to partially mitigate `test_autostop` failing (#1633) due to `sky status --refresh` being called when worker nodes are stopped but head node is not.
Sleep has been bumped from 150->250s. I tried 200s sleep but it failed 2/5 times I ran the test, so sticking with 250s. For reference, this was run on GCP n2-standard-8.
Tested:
> [Tests] Bump test_autostop sleep

- sky/backends/backend_utils.py
- sky/backends/cloud_vm_ray_backend.py
- sky/skylet/autostop_lib.py
- sky/skylet/configs.py
- sky/skylet/events.py
Fixes #1633 
Fixes the confusion of cluster being in `INIT` status, when it is being autostopped and is partially stopped.
Changes:
1. keep the autostop column in the cluster table, when the cluster is partially stopped
2. Print a hint that the cluster is being autostopped when it is in INIT status
```
sky launch -y -d -c test --num-nodes 2 --cloud gcp tests/test_yamls/minimal.yaml
sky status test --refresh
sky autostop -y test -i 0
sleep 60
sky status test --refresh
```
```
sky launch -y -d -c test --num-nodes 2 --cloud gcp tests/test_yamls/minimal.yaml
sky status test --refresh
sky autostop -y test -i 5
sky status -r
```
> [Autostop/UX] Better UX when the cluster is partially stopped due to autostopping

- docs/source/reference/yaml-spec.rst
- examples/example_app.py
- sky/cli.py
- sky/clouds/aws.py
- sky/clouds/azure.py
- sky/clouds/cloud.py
- sky/clouds/gcp.py
- sky/clouds/local.py
- sky/clouds/service_catalog/__init__.py
- sky/clouds/service_catalog/aws_catalog.py
- sky/clouds/service_catalog/azure_catalog.py
- sky/clouds/service_catalog/common.py
- sky/clouds/service_catalog/gcp_catalog.py
- sky/execution.py
- sky/optimizer.py
- sky/resources.py
- sky/task.py
- sky/utils/schemas.py
- tests/test_optimizer_dryruns.py
Closes #387
This PR introduces the ability for users to specify resource requirements in terms of the number of vCPUs in the `Resources` class and the `resources` section in the SkyPilot yaml.
**Semantics**
1. If the instance type and accelerators are not specified, SkyPilot will use the `cpus` parameter to select an appropriate VM size from the cloud's **default** VM family (i.e., m6i for AWS, Dv5 for Azure, and n2-standard for GCP).
For example,
* `sky launch --cpus 8` or `Resources(cpus=8)`: SkyPilot will find the VMs that have exactly 8 vCPUs. Namely,
* AWS: m6i.2xlarge
* Azure: Standard_D8_v5
* GCP: n2-standard-8
* `sky launch --cpus 12+` or `Resources(cpus='12+')`: SkyPilot will consider the VMs that have 12 or more vCPUs. Namely,
* AWS: m6i.4xlarge
* Azure: Standard_D16_v5
* GCP: …
> [Resources] Add `cpus` in resource specification

- sky/backends/backend_utils.py
- sky/backends/cloud_vm_ray_backend.py
- sky/cli.py
- sky/clouds/aws.py
- sky/clouds/azure.py
- sky/clouds/cloud.py
- sky/clouds/gcp.py
- sky/clouds/lambda_cloud.py
- sky/clouds/local.py
- sky/core.py
- sky/utils/common_utils.py
This PR
1. fixes the first part of the TODOs in #963, to unblock the user from using a long name for spot jobs on AWS. 
2. moves the cluster name checking into each Cloud.
3. refactors the `cloud.supports` to `cloud.check_features_are_supported` and change the boolean return value to exception raising.
4. optimizes the failover for `InvalidClusterNameError` and `ClusterUserIdentityError` to directly move to the next cloud, as those errors apply to the whole cloud.
5. fixes minor UX issues for failover:
Previously:
Now:
> Allow longer name for AWS/Azure cluster and refactoring

- sky/backends/backend_utils.py
From @concretevitamin, the output from `sky down` a TPU Pod VM can be confusing.
To reproduce
```
> sky launch TPU-Pod
> Ctrl-C  # after 30 secs
> sky down --all -y
Terminating 1 cluster ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% -:--:--
TPU VM ray-sky-a2e9-gcpuser-head-d806ba73-tpu is not in READY state. Skipping...
```
With this PR, it becomes
```
> sky down --all -y
... Skipping IP query...
```
> Fix TPU message

- sky/skylet/providers/gcp/config.py
- sky/skylet/providers/gcp/constants.py
In this PR, we
1. reduce one required firewall rule (ICMP) as SkyPilot doesn't necessary need it to function
2. make the VPC creation idempotent to avoid user accidentally touch the VPC and robust against failure during VPC creation. 
> Make GCP VPC creation more robust

- sky/clouds/cloud.py
This patches #1648 that breaks the `sky spot launch`
> [Spot] Fix spot launch failure introduced by #1648

- sky/setup_files/setup.py
This is to fix the issue in https://github.com/pallets/jinja/issues/1585, raised by one of our user.
> [Setup] Pin Jinja2 version to avoid an markupsafe version

- docs/source/reference/yaml-spec.rst
Adds a simple example to explain how the cpu+ field works.
Tested:
> [Docs] CPU docs update

- sky/adaptors/aws.py
A user reported a transient error when running the `sky status -r` 
```
[2023-02-02 22:04:47.820926 HKT] Failed to connect to cluster; refreshing cluster status...
W 02-02 22:05:14 backend_utils.py:2324] Failed to refresh status for 6 clusters:
W 02-02 22:05:14 backend_utils.py:2327]   cluster1: Failed to get AWS user.
W 02-02 22:05:14 backend_utils.py:2327]   Reason: [builtins.KeyError]: 'credential_provider'.
W 02-02 22:05:14 backend_utils.py:2327]   cluster2: Failed to get AWS user.
W 02-02 22:05:14 backend_utils.py:2327]   Reason: [builtins.KeyError]: 'endpoint_resolver'.
W 02-02 22:05:14 backend_utils.py:2327]   cluster3: Failed to get AWS user.
W 02-02 22:05:14 backend_utils.py:2327]   Reason: [builtins.KeyError]: 'credential_provider'.
W 02-02 22:05:14 backend_utils.py:2327] …
```
> Add lock for aws session creation

- README.md
- docs/source/getting-started/installation.rst
- docs/source/index.rst
- sky/setup_files/setup.py
- sky/templates/lambda-ray.yml.j2
Add Lambda Cloud to documentation and add the `[lambda]` option. (The `[lambda]` option does not install anything extra, but is included for uniformity).
> [Lambda Cloud] Update docs and add `[lambda]` install option

- sky/spot/recovery_strategy.py
This PR is to make sure the usage collection for the spot jobs contain the cancellation and termination action.
> [Spot] Add termination and cancellation for spot jobs into the usage collection

- sky/global_user_state.py
- sky/utils/cli_utils/status_utils.py
Added a status column, which includes a new ClusterStatus type TERMINATED, to the cost report. 
Tested (each the same cluster, just when calling `sky cost-report` at different times:
'''
cluster  1 min ago    1m 8s     1x GCP(n1-highmem-8, {'V100': 1})  INIT        $ 2.953       $0.056       
cluster  4 mins ago   4m 31s    1x GCP(n1-highmem-8, {'V100': 1})  UP          $ 2.953       $0.222       
cluster  21 mins ago  15m 9s    1x GCP(n1-highmem-8, {'V100': 1})  STOPPED     $ 2.953       $0.746   
cluster  34 mins ago  22m 31s   1x GCP(n1-highmem-8, {'V100': 1})  TERMINATED  $ 2.953       $1.108       
'''
> [Cost Report] Add status for cost report

- CONTRIBUTING.md
- sky/execution.py
- sky/utils/env_options.py
- tests/conftest.py
- tests/test_smoke.py
1. Add option for termination on failure to avoid clusters forgot to be terminated after failure. `--terminate-on-failure`
2. Set the cloud for spot controller to the generic cloud if the controller does not exist.
> [test] Add option for termination on failure and set spot controller cloud for testing

- sky/backends/cloud_vm_ray_backend.py
This is a quick fix for launching azure cluster. Since the `zones` for Azure can be `None`, the previous code complains about `TypeError: 'NoneType' object is not iterable`, when an error happens in a region.
> [Azure/Core] Fix blocklist for azure

- sky/cli.py
- sky/execution.py
Fixes #1672 
This PR allows specifying CPU requirements in re-launching (or executing a job on) an existing cluster (i.e., `sky launch -c existing-cluster --cpus x` and `sky exec existing-cluster --cpus x`). Note that in both cases the specified `cpus` will just be silently ignored. That is, 1) we do not check if the CPU requirement is valid, and 2) in `sky exec`, the specified number of CPUs will not work as a scheduling constraint.
* `sky launch 'echo hi' --cpus 8 -c test-cpus`
* `sky launch 'echo hihi' --cpus 100 -c test-cpus`
* `sky exec test-cpus 'echo hihihi' --cpus 9999`
> Allow --cpus for existing clusters

- docs/source/getting-started/installation.rst
Make each cloud's setup instruction a section, so that we can use URL to refer to a cloud's instructions.
- rendered HTMLs locally
> [docs] Make each cloud's setup instruction a section.

- sky/usage/constants.py
This is to easily swap out the logging server and its IP.
Tested that the new URL works.
> [usage] Change usage logging URL.

- sky/sky_logging.py
We should change the logging level of the handler, instead of the logging level of the logger. The logging level of logger should be set to `DEBUG`, so that other (new) handlers could dump debug info to a logging file. Setting the logging level of the logger to `INFO` would prevent streaming any lower level messages via logging handlers.
This PR does not affect the behavior of Skypilot. No smoke tests required.
> [Logging] Fix logging handling

- sky/backends/backend_utils.py
- sky/backends/cloud_vm_ray_backend.py
- sky/clouds/aws.py
- sky/clouds/azure.py
- sky/clouds/cloud.py
- sky/clouds/gcp.py
- sky/clouds/lambda_cloud.py
- sky/clouds/local.py
- sky/clouds/service_catalog/data_fetchers/fetch_aws.py
1. Fixes #1054
2. Refactors the cloud vm ray backend to make it more efficient.
3. Fix the AWS catalog fetching by excluding availability zones that do not contain the instance type: some instance types are not available on all the availability zones within a region even if it is on-demand (e.g., p4d.24xlarge is only supported in `use1-az1`, `use-az2`, `use-az6`, but our previous catalog fetcher assumed that all the zones contain the instance type).
A potential leakage that may not be solved by this PR:
1. The user Ctrl-C during the launching process of a new cluster `sky launch -c new-cluster --cloud aws` and the actual node was successfully launched on `us-east-1a`.
2. The user manually stopped the node on the AWS console
3. After that, the user do `sky launch -c new-cluster` again, the …
> [core] Launching existing cluster in the same zone to avoid leakage

- sky/skylet/providers/lambda_cloud/node_provider.py
This fixes a KeyError which occurs when listing instances that were manually launched on the Lambda Cloud dashboard which do not have a name attribute set.
Channged the name key indexing into a call to .get which will return `None` if the key 'name' is not set. The key 'name' is not set when you manually launch an instance in our cloud.
I edited the node_providers.py file manually that was installed by pip install skypilot[lambda]
Running the command line tool now works.
Here is the trace from the error:
```
sabalaba@tensorbook:~$ sky launch --gpus A10
SkyPilot collects usage data to improve its services. `setup` and `run` commands are not collected to ensure privacy.
Usage logging can be disabled by setting the environment variable …
```
> Fix KeyError when listing instances

- sky/global_user_state.py
For clusters that are very old and have no history due to being present before changes to `cluster_history` tracking for `sky cost-report`, we return zero duration and cost as a form of error-handling.
Simulated null usage intervals and start times and triggered the error-handling as seen below:
```
(sky) sumanth@MacBook-Pro-5 skypilot % sky cost-report
Clusters
NAME     LAUNCHED      DURATION  RESOURCES                          HOURLY_PRICE  COST (est.)  
cluster  2 weeks ago   -         1x GCP(n1-highmem-8, {'V100': 1})  $ 2.953       -            
cluster  2 weeks ago   -         1x GCP(n1-highmem-8, {'V100': 1})  $ 2.953       -            
cluster  1 month ago   -         1x GCP(n1-highmem-8)               $ 0.473       -            
cluster  1 month …
```
> Handle null usage intervals in duration computing

- sky/backends/cloud_vm_ray_backend.py
- sky/execution.py
- sky/spot/recovery_strategy.py
Patches #1655
When the cloud is specified, we don't raise the `ResourcesUnavailableError` but the actual precheck errors. We need to catch those exceptions in the `recovery_strategy`.
> [Spot] Fix spot failure reason when cloud is specified

- sky/backends/backend_utils.py
- sky/optimizer.py
Bug fixes for GCP status list and `region.zones is None` handling.
> Fix GCP status and region.zones is `None`

- sky/clouds/gcp.py
Previously, if the user only runs `gcloud init` without `gcloud auth application-default login`, the `sky check` still passed for GCP and `sky launch --cloud gcp` will raise the following issue:
```
cp: cannot stat '/root/.config/gcloud/application_default_credentials.json': No such file or directory
```
> [GCP] Fix sky check for not having application default set

- sky/backends/backend_utils.py
- sky/backends/cloud_vm_ray_backend.py
- sky/clouds/aws.py
- sky/clouds/azure.py
- sky/clouds/cloud.py
- sky/clouds/gcp.py
- sky/clouds/lambda_cloud.py
- sky/clouds/local.py
- sky/clouds/service_catalog/__init__.py
- sky/clouds/service_catalog/lambda_catalog.py
- sky/optimizer.py
- sky/resources.py
- sky/skypilot_config.py
Previously we filter the regions not in proxy commands in `skypilot_config` when we failover to that region. This will print messages about the region in the optimizer output, making it confusing.
Now we filter out the regions not included to short-circuit the optimizer and failover for them.
```
aws:
us-east-2: ssh -W %h:%p -i ~/.ssh/sky-key  -o StrictHostKeyChecking=no ec2-user@18.188.102.65
```
Previous output
```
> sky launch -c vpc-aws-spot --cloud aws -t t3.micro --use-spot                                                                                                     
I 02-26 14:41:00 optimizer.py:617] == Optimizer ==
I 02-26 14:41:00 optimizer.py:628] Target: minimizing cost
I 02-26 14:41:00 optimizer.py:640] Estimated cost: $0.0 / hour
I 02-26 14:41:00 …
```
> [core] Filter out regions not in proxy command earlier

- sky/clouds/service_catalog/data_fetchers/fetch_lambda_cloud.py
This pr adds a script to generate the Lambda cloud catalog.
The script requires a Lambda API key. You can specify the API key by using `--api-key` or `--api-key-path`. If no API key is specified, this script will parse `~/.lambda_cloud/lambda_keys` to find one. 
Tested:
> [Lambda Cloud] Catalog generator

- sky/setup_files/setup.py
Add support for ray 2.3.0 local version.
> [Setup] Upgrade support for local ray version to 2.3.0

- sky/backends/cloud_vm_ray_backend.py
- sky/backends/docker_utils.py
- sky/backends/local_docker_backend.py
Fixes https://github.com/skypilot-org/skypilot/issues/1694.
After removing the `init()`, I was trying to add
```
from colorama import just_fix_windows_console
just_fix_windows_console()
```
as suggested by https://github.com/tartley/colorama#initialisation
But this function only introduced after `0.4.5` and we pin `colorama<0.4.5` because it conflicts with `aws-cli` for some reason.
https://github.com/skypilot-org/skypilot/blob/e4b99e08fc585ffde28ef84229cc7d83f4664d4c/sky/setup_files/setup.py#L73
Related issue: https://github.com/skypilot-org/skypilot/pull/1323
Is this still the case after we upgrade ray version? @Michaelvll 
or is it safe to add `colorama.init()` in `sky/__init__.py`?
> Remove unsafe colorama.init 

- sky/authentication.py
- sky/core.py
- sky/execution.py
This PR fixes #1472 by disallowing spot autostop.
Tested:
> [Spot] Disallow spot autostop

- sky/backends/backend_utils.py
- tests/test_smoke.py
To reproduce this bug:
- Clear `~/.sky/config.yaml`, launch a cluster `dbg`, have it autostopped
- Now fill in `~/.sky/config.yaml` with private VPC configured
```yaml
aws:
vpc_name: nonexisting-vpc
use_internal_ips: True
ssh_proxy_command: ssh -W %h:%p -i ~/.ssh/sky-key -o StrictHostKeyChecking=no ec2-user@1.2.3.4
```
- `sky launch -c dbg -i0` again
- Observe that it correctly restarted in the old default VPC; however, the autostopping would fail, due to `~/.sky/sky_ray.yml` on the remote containing wrong contents:
```yaml
provider:
...  # other fields are correct/preserved
vpc_name: nonexisting-vpc
auth:
...
ssh_proxy_command: ssh -W %h:%p -i ~/.ssh/sky-key -o StrictHostKeyChecking=no ec2-user@1.2.3.4
```
This is due to the ordering of when we call …
> [back compat] Fix configuring private VPC causing old clusters to have wrong `sky_ray.yml`

- sky/backends/backend_utils.py
- sky/backends/cloud_vm_ray_backend.py
- sky/cli.py
- sky/clouds/service_catalog/common.py
- sky/core.py
- sky/data/data_transfer.py
- sky/data/storage.py
- sky/sky_logging.py
- sky/spot/spot_utils.py
- sky/utils/cli_utils/status_utils.py
- sky/utils/log_utils.py
- sky/utils/ux_utils.py
- tests/test_smoke.py
Changes in this PR:
1. We refactored the code to show a similar message for the spot queue in `sky spot queue` and `sky status`.
2. Make `core` able to be silent with `with core.silent():` context manager
3. Remove the cache for the spot queue as it causes much confusion while providing not many benefits.
> [UX] Fix the output of `sky spot queue`

- sky/cli.py
- sky/clouds/service_catalog/config.py
- sky/sky_logging.py
- sky/utils/common_utils.py
- tests/conftest.py
This is to fix the issue when the `sky status` meet other exceptions during the spot job query. It could happen when the current active account is different from the one used for the spot controller.
Previous:
```
Managed spot jobs
multiprocessing.pool.RemoteTraceback: 
"""
sky.exceptions.ClusterOwnerIdentityMismatchError: 'sky-spot-controller-9ce1ce58' (GCP) is owned by account 'zhwu@berkeley.edu\n [project_id=skypilot-375900]', but the activated account is 'zhwu@berkeley.edu\n [project_id=skypilot-managed-spot]'.
"""
The above exception was the direct cause of the following exception:
File "/Users/zhwu/miniconda3/envs/sky-dev/bin/sky", line 33, in <module>
sys.exit(load_entry_point('skypilot', 'console_scripts', 'sky')())
File …
```
> [UX] Catch any exception for the spot queue fetching failure

- sky/backends/backend_utils.py
SkyPilot occasionally adds duplicate entries into my .ssh/config for the same cluster, which creates issues when I down the cluster or create a new one with the same name (but new IP). I found the bug, where it's not scanning for existing clusters in the config file all the way to the start of the file, only the second line. This fixes that.
Not sure which tests to run here? Running the full suite seems like overkill?
> .ssh/config overwriting bug

- sky/benchmark/benchmark_utils.py
- sky/cli.py
- sky/clouds/aws.py
- sky/clouds/azure.py
- sky/clouds/cloud.py
- sky/clouds/gcp.py
- sky/clouds/lambda_cloud.py
- sky/clouds/local.py
- sky/clouds/service_catalog/__init__.py
- sky/clouds/service_catalog/aws_catalog.py
- sky/clouds/service_catalog/azure_catalog.py
- sky/clouds/service_catalog/common.py
- sky/clouds/service_catalog/data_fetchers/fetch_azure.py
- sky/clouds/service_catalog/gcp_catalog.py
- sky/clouds/service_catalog/lambda_catalog.py
- sky/execution.py
- sky/optimizer.py
- sky/resources.py
- sky/utils/schemas.py
- sky/utils/ux_utils.py
- tests/test_optimizer_dryruns.py
- tests/test_optimizer_random_dag.py
Fixes #1673, this simulates the behavior of `cpus` in resources, thanks to the great effort from @WoosukKwon in #1622 
Added a memory filtering field for the resources:
1. `memory: 16` the memory should be 16GB
2. `memory: 16+` the memory should be more than 16GB
3. ~~`memory: 4x` the memory to core ratio should be larger than 4 times.~~ (Not expose this API as it might be confusing)
Logics for choosing the CPU instance to use:
1. Use the general-purpose CPU instance by default, when the `--memory` is not specified
2. Use the cheapest CPU instance that satisfies the requirement, when the `--memory` is specified.
1. `sky launch -c normal`
```
I 03-07 21:32:21 optimizer.py:712] Considered resources (1 node):
I 03-07 21:32:21 optimizer.py:760] …
```
> [Resources] Add memory in resources

- sky/clouds/azure.py
This is a fix for the user without `knack` installed. To reproduce:
```
pip uninstall knack
sky launch --cloud azure
```
The following error is raised:
```
File "/home/eli/src/my/skypilot/sky/clouds/azure.py", line 356, in get_current_user_identity
import knack  # pylint: disable=import-outside-toplevel
ModuleNotFoundError: No module named 'knack'
During handling of the above exception, another exception occurred:
File "/home/eli/src/my/skypilot/sky/usage/usage_lib.py", line 416, in entrypoint_context
yield
File "/home/eli/src/my/skypilot/sky/utils/common_utils.py", line 241, in _record
File "/home/eli/src/my/skypilot/sky/cli.py", line 2872, in check
sky_check.check()
File …
```
> [UX] Fix azure import error handling

- sky/clouds/gcp.py
This PR aims to fix https://github.com/skypilot-org/skypilot/issues/1755 by adding permission checking for GCP.
> Add GCP permission check

- sky/cli.py
Add the following disclaimer to the end of cost-report output:
```
NOTE: This feature is experimental.
Costs for autostop clusters may not be accurate.
```
> [Cost Report] Add cost report auto-stop disclaimer

- sky/backends/backend_utils.py
- sky/execution.py
- sky/spot/controller.py
- sky/templates/spot-controller.yaml.j2
To reproduce the overwriting problem:
1. `sky spot launch -n test 'echo hi'` 
2. `sky spot launch -n test 'echo hi2'` in parallel with the first one.
One of the job will overwrite the test.yaml and test.config_yaml of the other one on the spot controller, which may cause an issue that the two tasks have the same run commands, if we add a `sleep 40` before the controller process starts in `spot-controller.yaml.j2`, i.e. both task will show `hi2`.
- the snippets above
> [Spot] Avoid spot jobs files being overwritten on spot controller

- sky/spot/controller.py
- sky/spot/recovery_strategy.py
- sky/utils/subprocess_utils.py
- tests/test_smoke.py
Previously, we send an interruption signal to the controller process and the controller process handles cleanup. However, we figure out the behavior differs from cloud to cloud (e.g., GCP ignore 'SIGINT'). A possible reason is https://unix.stackexchange.com/questions/356408/strange-problem-with-trap-and-sigint. But anyway, a clean solution is killing the controller process directly, and then cleanup the cluster state.
> [spot] Fix multiprocessing signal handling in spot controller

- sky/cli.py
- sky/spot/controller.py
- sky/spot/spot_state.py
- tests/test_smoke.py
According to the #1745, we now set the CANCELLED state after the spot cluster is fully clean up. That will keep the spot job in the previous job for a while, which can feels unresponsive.
Thanks to @suquark 's [great idea](https://github.com/skypilot-org/skypilot/pull/1745#discussion_r1137558903), we are now adding a CANCELLING state for the spot job to improve the UX.
This will also solve the issue https://github.com/skypilot-org/skypilot/pull/1745#issuecomment-1472176053
Because, previously, our spot job is not set to terminal state immediately, the log streaming will misclassified it as preempted.
TODOs:
> [Spot] Add cancelling state for the spot job

- sky/cli.py
Partially fixes #1331 by making `sky gpunode` reuse existing cluster if possible.
Before:
```
$ sky gpunode --gpus V100
$ sky gpunode --gpus V100 # fails
```
After
```
$ sky gpunode --gpus V100
$ sky gpunode --gpus V100 # reuses gpunode
```
Tested
Notes:
- I wanted to add a smoke test, but I couldn't because `sky gpunode` automatically ssh's into the cluster and there is no detach option.
- It is not possible to check if `sky gpunode` was launched with the exact same resource specification (since some resources are decided during execution), so we reuse the cluster if the required resources are a subset of the launched resources.
> Make `sky gpunode` reuse existing cluster if possible

- sky/backends/backend_utils.py
We've seen reports that 8.8.8.8 can be unreachable (#1767).
Changes to Cloudflare's 1.1.1.1 as a mitigation.
- (US) `sky launch --cloud gcp --down`
- Confirmed with friend in China that 1.1.1.1 is reachable
> Use 1.1.1.1 instead of 8.8.8.8 as IP for network check.

- sky/cli.py
- sky/spot/controller.py
- sky/task.py
The current behavior of our cli for `sky launch -c test cluster.yaml --env WANDB_API_KEY` will remove all the environments specified in `cluster.yaml` which is not desired.
> Update envs instead of replacing

- sky/backends/backend_utils.py
- sky/cli.py
Repro: create a YAML like this
```yaml
resources:
```
Previously:
```
» sky launch test.yaml
...
File .. sky/backends/onprem_utils.py", line 492, in check_local_cloud_args
yaml_cloud = yaml_config['resources'].get('cloud')
AttributeError: 'NoneType' object has no attribute 'get'
```
Now:
```
» sky launch test.yaml
Task from YAML spec: test.yaml
ValueError: Invalid task YAML: None is not of type 'object'. Check problematic field(s): $.resources
```
The fix is we do `check_local_cloud_args()` after `Task` ctor which performs schema validation.
- above
> Fix errors from empty 'resources' field in YAML.

- sky/backends/backend_utils.py
- sky/cli.py
- sky/clouds/aws.py
- sky/exceptions.py
- sky/execution.py
- sky/optimizer.py
- sky/spot/recovery_strategy.py
A user reported that when using AWS SSO account, the `sky spot launch` will fail due to the controller does not have any cloud access enabled. That is a bug with our current SSO implementation, as the controller is assigned with an assumed IAM-role, which has the access to create the spot cluster and will not have static credential files, but our cloud access checking will fail when it finds there is no credential files.
Another problem with the spot controller is: the controller will keep retrying even if the all cloud disabled exception is raised, causing the spot job in STARTING status forever.
To reproduce:
1. Run in a new docker container
2. log in with SSO account
3. `sky spot launch -n test echo hi --retry-until-up`
This PR fixes:
1. The spot controller will now be able to launch …
> [SSO/Spot] Fix spot controller failed to launch spot cluster when using SSO

- sky/clouds/service_catalog/data_fetchers/fetch_aws.py
Since our AWS credential does not have permission to query the offerings for A100-80GB instances, we now hardcoded it in our `fetch_aws` to unblock the uses of that instance for users.
Fixes #1201
> [AWS] Enable p4de in the catalog

- sky/adaptors/gcp.py
- sky/cli.py
- sky/clouds/service_catalog/common.py
Partially address #1764: only AWS & Lambda catalogs have the relevant info for now.
Azure / GCP's offerings will show a `-` under the `DEVICE_MEM` column.
- `sky show-gpus -a`
> Show DEVICE_MEMORY in `show-gpus` for AWS & Lambda.

- sky/clouds/service_catalog/data_fetchers/fetch_aws.py
This fixes the auto catalog fetcher error: https://github.com/skypilot-org/skypilot-catalog/actions/runs/4601334620/jobs/8129070712
To reproduce:
`python -m sky.clouds.service_catalog.data_fetchers.fetch_aws --no-az-mappings --check-all-regions-enabled-for-account` locally with `pandas==2.0`
> [catalog] Fix aws_fetcher by avoiding deprecated df.append

- sky/backends/backend_utils.py
- sky/utils/command_runner.py
Closes #1538.
- `rsync` related errors are normally related to transient network issues, so this adds "to fix" information for the user in error messages
- This also adds retrying to the `rsync` command to reduce the frequency of failures due to transient network issues
> Make rsync more resilient

- sky/clouds/service_catalog/data_fetchers/fetch_azure.py
Fixes #1768
Thanks to @carloscdias for pointing this out! There are two regions, `'eastus2euap'` and `'centraluseuap'`, not having `'ProductName'` in the table.
- `python -m sky.clouds.service_catalog.data_fetchers.fetch_azure --all-regions`
> [Catalog] Fix the `fetch_azure --all-regions` to exclude the unsupported region

- sky/backends/backend_utils.py
- sky/cli.py
- sky/clouds/cloud.py
- sky/optimizer.py
Changes
- some more friendly messages adding "to fix"
- fix `sky show-gpus --cloud xxx` which previously throws a long stacktrace
```
..
ValueError: Cannot find module "sky.clouds.service_catalog.xxx_catalog" for cloud "xxx".
```
currently
```
ValueError: Cloud 'xxx' is not a valid cloud among ['aws', 'azure', 'gcp', 'lambda', 'local']
```
consistent with `sky launch --cloud xxx`.
- above
- `sky exec cluster-in-init echo hi`
> [UX] Minor UX fixes.

- sky/backends/cloud_vm_ray_backend.py
Fixes #1797.
I've tried a few days and finally got a set_trace inside `need_ray_up()`, tested that the `re.search()` there works. This doesn't test things end-to-end, however.
```
sky launch -y --gpus A100-80GB:8 --cloud gcp --down -c dbg -r 
```
> GCP/provisioner: Handle the RESOURCE_NOT_FOUND error.

- sky/clouds/gcp.py
- sky/data/mounting_utils.py
- sky/data/storage.py
We encountered an issue with the gcsfuse that the saved large model checkpoints on a mounted GCS bucket can be incomplete. It could be a problem with the old gcsfuse we were using:
in the release note of gcsfuse (discovered by @infwinston):
> Fixed a critical bug in write workflow - although it was very rare, but gcsfuse was writing wrong file content while doing append operation on larger file.
https://github.com/GoogleCloudPlatform/gcsfuse/releases/tag/v0.41.11
> [GCP Storage] Upgrade GCSFuse version

- sky/cli.py
- sky/clouds/service_catalog/__init__.py
Changes
- A10/A10G are popular GPUs and are available/in-demand
- Rename header `NVIDIA_GPU` -> `COMMON_GPU`
- Added some hint
We still need to fix some other logging issues, e.g., removing
```
*NOTE*: for most GCP accelerators, INSTANCE_TYPE == (attachable) means the host VM's cost is not included.
```
if GCP is not queried. cc @ewzeng 
```
sky show-gpus
sky show-gpus A10
sky show-gpus --cloud aws
sky show-gpus --cloud aws A10
sky show-gpus --cloud aws -a
```
> `show-gpus`: make A10/A10G "common" GPUs, and add hints.

- sky/cli.py
From user feedback, it's unintuitive that a managed spot job by default don't have this flag to True. Forgetting to set this flag made the job fail with `FAILED_NO_RESOURCES`.
> Make `sky spot launch` default `-r/--retry-until-up` to True.

- sky/cli.py
- sky/global_user_state.py
- sky/utils/cli_utils/status_utils.py
Limit lines in each table to 5 lines (this number is up for debate).
Display total cost across all reports in cost-report (even costs that are not displayed due to the above limit).
```
(sky) sumanth@MacBook-Pro-5 skypilot % sky cost-report   
Clusters
NAME     LAUNCHED      DURATION  RESOURCES                          STATUS      HOURLY_PRICE  COST (est.)  
cluster  1 month ago   6m 19s    1x GCP(n1-highmem-8, {'V100': 1})  TERMINATED  $ 2.953       $0.311       
cluster  1 month ago   22m 31s   1x GCP(n1-highmem-8, {'V100': 1})  TERMINATED  $ 2.953       $1.108       
cluster  2 months ago  3m 41s    1x GCP(n1-highmem-8)               TERMINATED  $ 0.473       $0.029       
cluster  2 months ago  10m 13s   1x GCP(n1-highmem-8)               TERMINATED  $ 0.473       $0.081 …
```
> [Cost Report] Add some UI fixes

- sky/data/storage.py
- tests/test_smoke.py
- tests/test_storage.py
If the user specifies an invalid `name`, the error is thrown quite deep into the stack after we've sent the bucket request to boto3/gcs. We should catch it early and show it cleanly to the user.
This PR adds name validation for S3, R2 and GCSStores. 
Example:
```
file_mounts:
/mydata/:
name: s3://romil-bucket
store: s3
```
Before:
```
<Long stack trace>
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid bucket name "s3://romil-bucket": Bucket name must match the regex "^[a-zA-Z0-9.\-_]{1,255}$" or be an ARN matching the regex "^arn:(aws).*:(s3|s3-object-lambda):[a-z\-0-9]*:[0-9]{12}:accesspoint[/:][a-zA-Z0-9\-.]{1,63}$|^arn:(aws).*:s3-outposts:[a-z\-0-9]+:[0-9]{12}:outpost[/:][a-zA-Z0-9\-]{1,63}[/:]accesspoint[/:][a-zA-Z0-9\-]{1,63}$"
```
After:
```
Task from …
```
> [Storage] Add validation checks for Store Name

- sky/data/storage.py
Changes the error message when a bucket is not accessible to focus on fix rather than the problem. Considered moving the root error (boto3/gcloud) to after our exception or removing it altogether, but decided it's better to let it come first, followed by our exception.
Before:
```
botocore.exceptions.ClientError: An error occurred (403) when calling the HeadBucket operation: Forbidden
The above exception was the direct cause of the following exception:
sky.exceptions.StorageBucketGetError: Failed to connect to an existing bucket 'mybucket'.
Please check if:
1. the bucket name is taken and/or 
2. the bucket permissions are not setup correctly. To debug, consider using aws s3 ls checkpoint.
```
After:
```
botocore.exceptions.ClientError: An error occurred (403) when calling the HeadBucket …
```
> [Storage] Improve UX for error message when bucket is not accessible

- sky/optimizer.py
- sky/resources.py
- sky/task.py
Repro
```
resources:
cloud: aws
accelerators: A100-80GB:8
use_spot: true
```
Previously
```
I 04-10 18:34:24 optimizer.py:998] No resource satisfying AWS([Spot], {'A100-80GB': 8}) on [AWS].
sky.exceptions.ResourcesUnavailableError: No launchable resource found for task Task(run=None)
resources: {AWS([Spot], {'A100-80GB': 8})} (AWS([Spot], {'A100-80GB': 8})). This means the catalog does not contain any instance types to satisfy the request. To fix: relax/change its resource requirements.
Hint: 'sky show-gpus --all' to list available accelerators.
'sky check' to check the enabled clouds.
```
Now
```
I 04-10 18:34:05 optimizer.py:990] No resource satisfying AWS([Spot], {'A100-80GB': 8}) on [AWS].
sky.exceptions.ResourcesUnavailableError: No launchable resource found for task Task(run=None) …
```
> Logging UX: update Resources repr & make an optimizer logging nicer.

- docs/source/reference/storage.rst
> Fix a typo in storage.rst

- sky/setup_files/setup.py
The latest Azure cli does not install the `azure-mgmt-network` by default, which will be used by our `node_provider` for Azure. Adding this to our `setup.py`.
> Add missing azure dependency `azure-mgmt-network`

- docs/source/reference/yaml-spec.rst
- sky/backends/backend_utils.py
- sky/cli.py
- sky/clouds/aws.py
- sky/clouds/azure.py
- sky/clouds/cloud.py
- sky/clouds/gcp.py
- sky/clouds/lambda_cloud.py
- sky/clouds/local.py
- sky/clouds/service_catalog/__init__.py
- sky/clouds/service_catalog/aws_catalog.py
- sky/clouds/service_catalog/azure_catalog.py
- sky/clouds/service_catalog/gcp_catalog.py
- sky/clouds/service_catalog/lambda_catalog.py
- sky/resources.py
- sky/skylet/providers/azure/azure-vm-template.json
- sky/templates/aws-ray.yml.j2
- sky/templates/azure-ray.yml.j2
- sky/templates/gcp-ray.yml.j2
- sky/templates/spot-controller.yaml.j2
- sky/utils/schemas.py
- tests/test_optimizer_dryruns.py
- tests/test_smoke.py
This PR introduces multi-level performance disks in all clouds. By specifying `disk_tier` in `sky.Resources` to one of `high`, `medium`, and `low`, a user could use a disk with custom performance. All clouds' current decisions and prices (256 GB for example) are shown below.
`disk_tier=low`
|Cloud|Disk Type|Benchmarked Read Throughput|Benchmarked Read IOPS|Benchmarked Write Throughput|Benchmarked Write IOPS|Price (GiB/mo)|Price (IOPS/mo)|Total Price Each Month|
|-|-|-|-|-|-|-|-|-|
|GCP|pd-standard|13.87 MB/s|211.63|37.17 MB/s|567.13|0.048|-|12.288|
|Azure|Standard_LRS|861.92 MB/s|13151.92|36.67 MB/s|559.54|-|-|11.328|
|AWS|standard|20.33 MB/s|310.14|282.19 MB/s|4305.91|0.066|-|16.896|
`disk_tier=medium`
|Cloud|Disk Type|Benchmarked Read Throughput|Benchmarked Read IOPS|Benchmarked Write …
> [Provisioner] Support multi level performance disk

- sky/optimizer.py
- sky/resources.py
- sky/task.py
#1848 accidentally added region/zone info in Resources, which is undesirable:
```
I 04-16 12:11:12 cloud_vm_ray_backend.py:3350] Creating a new cluster: "dbg-private" [1x AWS(m6i.large, region='us-east-1')].
Clusters
NAME                          LAUNCHED    RESOURCES                                                                  STATUS   AUTOSTOP  COMMAND             
sky-65b4-zongheng             4 days ago  1x Azure(Standard_ND40rs_v2, {'V100-32GB': 8}, region='eastus')            STOPPED  -         sky exec sky-65b4-zongheng...
```
This PR 
- reverted that part of the change
- brought back the location hint in "no instance types found" Optimizer outputs
- fixed `Task.__repr__()` for `sky-cmd` tasks
With
```yaml
resources:
cloud: aws
accelerators: A100-80GB:8
use_spot: true
```
This …
> UX: fix Resources/Task repr.

- sky/skylet/events.py
User reported autostop stopped (!) working a few days ago under a weird SSO + custom AWS env vars setup:
- The VM has an assumed role from local SSO credentials, as expected
- However, the VM image has `/etc/profile.d/set-aws-credentials.sh` which sets some default AWS_ACCESS_KEY_ID / AWS_SECRET_ACCESS_KEY
- This takes precedence over assumed role, so in our autostop’s ray up, the latter is used, which means the private VPC is not found, causing autostop to fail
- It’s unclear why this same setup worked before and stopped working since 2 days ago
This PR  changes the autostop sequence of actions from
- ray up (this is where the error occurred)
- ray down --workers-only
- ray down
to
- if num nodes > 1
- ray up
- ray down --workers-only
- ray down
I considered unsetting AWS_ACCESS_KEY_ID / …
> Change autostop for 1-node clusters to fix SSO/AWS env vars bug.

- llm/vicuna/serve.yaml
- llm/vicuna/train.yaml
We now use the high-performance disk for the vicuna example, so as to get much better checkpointing efficiency and align with the configuration we used in the actual training.
> Add disk tier to vicuna example for better performance

- sky/skylet/events.py
#1880 didn't fix user's issue because the "final ray down" still calls bootstrap in the node provider, which then throws the VPC-not-found error. 
This PR explicitly drops AWS keys from env vars for all `ray` commands during autostop/down. Confirmed with user this fixed things for them.
```
pytest tests/test_smoke.py::test_autostop --aws
pytest tests/test_smoke.py::test_autodown --aws
```
> Fix autostop/autodown rare bug: drop AWS keys from env vars.

- sky/backends/cloud_vm_ray_backend.py
Sometimes when the command line has already printed `To view detailed progress: tail [filename]`, the file has not been created yet, which will cause running the tail command to raise a file not found error. This PR fixes this issue.
> Fix inexistent log file

- sky/data/storage.py
- tests/test_smoke.py
Closes #1322.
If a bucket is deleted externally, then store.delete() now does a no-op (instead of creating and deleting like before). The logging has been updated. 
Now:
```
(base) ➜  repro git:(storage_deletionfix) ✗ SKYPILOT_DEBUG=0 sky storage delete -a
Deleting all storage objects.
I 04-16 22:47:19 storage.py:1029] S3 bucket romilmybucket may have been deleted externally. Removing from local state.
```
> [Storage] Fix `sky storage delete` for externally deleted buckets

- sky/backends/cloud_vm_ray_backend.py
In one of my previous PR #1907 , touching the logfile raised a 'No such file or directory' error. This PR calls `os.makedirs` to eliminate this error.
> Fix a bug when touching logfile

- docs/source/running-jobs/distributed-jobs.rst
Users can't find how to ssh into worker nodes in multi-node clusters. Distributed jobs page is missing instructions on how to ssh.
User comments:
> When launching multi-node clusters, is there an easy way to ssh into non-head nodes (other than looking up the public DNS on e.g., AWS)?  I understand that the necessary ssh config is automatically set up such that ssh cluster-name works -- possible to do this for other cluster nodes as well?
> ...
> I read through most of the docs
> ...
> remember coming across ssh mycluster somewhere but couldn't find anything on worker node login
> I agree with this matter. I was also looking for a way to ssh into non-head nodes recently and found the instruction in [getting-started](https://skypilot.readthedocs.io/en/latest/getting-started/quickstart.html?h …
> [Docs] Add instructions for ssh-ing into multi-node jobs

- sky/skylet/events.py
`AWS_SECRETE_ACCESS_KEY` -> `AWS_SECRET_ACCESS_KEY`.
> Fix AWS secret access key typo in autostop codepath

- sky/authentication.py
- sky/backends/backend_utils.py
- sky/templates/aws-ray.yml.j2
- tests/test_smoke.py
This PR is separated from #1641, as the disabling of the unattended upgrade for AWS is more urgent for the AWS user.
We are now using the cloud-init to disable the `unattended-upgrade` which holds the lock for `apt`. The user's `sudo apt install` locked issue should now be fixed and deterministic.
> [AWS] Disable unattended-upgrade with cloud-init

- sky/sky_logging.py
- sky/spot/controller.py
Previously, the log from the controller process was left out of the spot jobs' output, which made the debugging harder. This PR fixes the logging from the spot controller.
Another change made: add a grace period between the job status check and the cluster status check to make the annotation of the job failure more conservative. This is to avoid the case when the job fails due to the preemption while the cluster's status on the cloud has not been set to non-UP status yet.
> [Spot] Show logging from the controller and grace period for cluster status checking

- .github/workflows/stale.yml
This PR adds a bot to automatically make the old PR and issue stale to make it easier to track the more important issues and PRs.
reference: https://github.com/actions/stale
Tested (run the relevant ones)
> Add a stale bot for issues and PRs

- sky/templates/aws-ray.yml.j2
The previous way to disable the unattended-upgrade significantly increase the provisioning time of AWS cluster, due to the apt remove run in the beginning of the system. We now switch to the configuration method which will reduce the provision time from 3m40s to 2m30s with `time sky launch -c min-aws --cloud aws -y`
> [AWS] Faster cloud-init for disabling unattended-upgrade

- .github/workflows/format.yml
- .github/workflows/mypy-generic.yml
- .github/workflows/mypy.yml
- .github/workflows/pylint.yml
- .github/workflows/pytest-generic.yml
- .github/workflows/pytest.yml
- CONTRIBUTING.md
- docs/source/getting-started/installation.rst
- docs/source/reference/local/setup.rst
- sky/design_docs/onprem-design.md
- sky/setup_files/setup.py
- sky/skylet/providers/azure/config.py
- sky/skylet/providers/azure/node_provider.py
- sky/skylet/ray_patches/__init__.py
- sky/skylet/ray_patches/azure_cli.py.patch
Our previous patch for the `azure-identity` is outdated and causing trouble launching azure cluster. Since the latest `azure-identity` contains the `process_timeout` argument, we can directly use that to solve the problem we mentioned in https://github.com/skypilot-org/skypilot/blob/bbdd5b1512aae7cb1172b91b2b74cd8b0187f002/sky/skylet/ray_patches/__init__.py#L88-L91
Also, closes #609 
Based on #1954 
> [Dependency] Drop Python 3.6 support, switch to Python>=3.7 and fix azure launching issue

- .github/workflows/stale.yml
This is to make the stale bot go from the oldest issues / PRs, and increase the number of issues/PRs processed by it each run.
It will only do 100 operations per-run, this can reduce the burden for us to handle the flood of staled issues per-day.
- Manually triggered the workflow, and it works
> [Stale Bot] Change the order of the stale

- sky/backends/backend_utils.py
A minor issue from user where `total_bytes` in this func can be a str of a float.
> Minor: fix backend_utils.path_size_megabytes() rounding.

- sky/cli.py
Previously `sky show-gpus --cloud ibm -a` was failing. This PR fixes it. Thanks to @Cohen-J-Omer for pointing out the fix.
```
sky show-gpus --cloud ibm -a
sky show-gpus --cloud aws -a
sky show-gpus --cloud gcp -a
sky show-gpus --cloud lambda -a
sky show-gpus --cloud azure -a
```
> Minor: `show-gpus --cloud ibm -a` fix (int parsing).

- sky/skylet/providers/lambda_cloud/node_provider.py
According to [RFC 1918](https://datatracker.ietf.org/doc/html/rfc1918#section-3), the IP range `172.16.0.0` - `172.31.255.255` can be used as internal IP address, which Lambda Cloud seems to be actually doing so for the new H100 GPU instances. ([img](https://github.com/skypilot-org/skypilot/assets/3784687/cf35dbe7-1783-4dc5-bcf2-19a6aeb2f14e))
Therefore, users may get a `Failed to obtain private IP from node` error while launching those new instances on Lambda Cloud. ([#1948](https://github.com/skypilot-org/skypilot/issues/1948#issuecomment-1552988437))
This PR modifies the regex used by `ray get-head-ip` to also match IPs `172.16.*` - `172.32.*`.
The new Regex is tested as: https://regex101.com/r/jHHWti/2 and with
```
curl https://gist.githubusercontent.com/zetavg/8712abde098f3b287dca0f3f …
```
> [Lambda Cloud] Update Regex of Internal IP for H100 Support

- sky/backends/backend_utils.py
- sky/backends/cloud_vm_ray_backend.py
Fixes #1761.
Repro:
```
AWS_PROFILE=AdministratorAccess-1234 sky launch -c sso -t t3.large -i0 -y
sky down sso -p -y
```
Now:
```
E 04-22 19:31:29 cloud_vm_ray_backend.py:2805] 'sso' (AWS) is owned by account ['A<stuff>:zongheng', '1234'], but the activated account is ['5678', '5678'].
W 04-22 19:31:29 cloud_vm_ray_backend.py:2807] Purge (-p/--purge) is set, ignoring the above error.
W 04-22 19:31:29 cloud_vm_ray_backend.py:2807] It is the user's responsibility to ensure that this cluster is actually terminated on the cloud.
E 04-22 19:33:38 cloud_vm_ray_backend.py:2805] 'sso' (AWS) is owned by account ['A<stuff>:zongheng', '1234'], but the activated account is ['5678', '5678'].
W 04-22 19:33:38 cloud_vm_ray_backend.py:2807] Purge (-p/--purge) is set, ignoring the above error.
W 04-22 …
```
> Core/CLI: make `down -p` bypass identity mismatch errors.

- docs/source/getting-started/installation.rst
- sky/cli.py
- sky/clouds/service_catalog/__init__.py
- sky/clouds/service_catalog/aws_catalog.py
- sky/clouds/service_catalog/azure_catalog.py
- sky/clouds/service_catalog/common.py
- sky/clouds/service_catalog/gcp_catalog.py
- sky/clouds/service_catalog/ibm_catalog.py
- sky/clouds/service_catalog/lambda_catalog.py
This PR fixes issue #1915. Previously, users were not able to specify the GPU quantity that they wanted. This PR allows users to do so by running sky show-gpus V100:4 to find the cloud providers and regions that offer 4 V100 GPUs.
The output is now as follows:
```
sky show-gpus V100:8
GPU   QTY  CLOUD   INSTANCE_TYPE  DEVICE_MEM  vCPUs  HOST_MEM  HOURLY_PRICE  HOURLY_SPOT_PRICE  REGION            
V100  8    AWS     p3.16xlarge    16GB        64     488GB     $ 24.480      $ 7.344            ap-northeast-1    
V100  8    GCP     (attachable)   -           -      -         $ 19.840      $ 5.920            us-central1       
V100  8    Lambda  gpu_8x_v100    16GB        92     448GB     $ 4.400       -                  asia-northeast-1  
GPU        QTY  CLOUD  INSTANCE_TYPE       DEVICE_MEM …
```
> Added functionality to support specifying quantity of a resource in call to show-gpus

- sky/backends/cloud_vm_ray_backend.py
- sky/clouds/aws.py
- tests/test_cli.py
We have seen the following case: user is using an Okta wrapper which generates temporary env vars for AWS credentials (including AWS_SESSION_TOKEN). 
- https://github.com/washingtonpost/clokta/blob/main/INSTRUCTIONS.md#docker-containers-and-scripts
- https://github.com/washingtonpost/clokta/blob/main/clokta/aws_cred_generator.py#L110-L117
The `aws configure list` output check below would show `env` in the Type column, which meant we then proceeded to upload ~/.aws/credentails. The latter is not the same identity as the env vars, causing troubles when creating multinode clusters.
- running
> AWS: correctly detect credentials provided by temporary env vars.

- sky/clouds/ibm.py
When the IBM cloud is enabled in the `sky check`, `sky launch --use-spot` will fail due to an assertion in the `IBM` cloud, with the following error:
```
> sky launch --use-spot
...
assert use_spot is False, (
AssertionError: current IBM implementation doesn't support spot instances
```
After this PR, SkyPilot will correctly skip IBM cloud:
```
> sky launch --use-spot
I 05-24 17:19:21 optimizer.py:636] == Optimizer ==
I 05-24 17:19:21 optimizer.py:647] Target: minimizing cost
I 05-24 17:19:21 optimizer.py:659] Estimated cost: $0.1 / hour
I 05-24 17:19:21 optimizer.py:659] 
I 05-24 17:19:21 optimizer.py:732] Considered resources (1 node):
I 05-24 17:19:21 optimizer.py:781] --------------------------------------------------------------------------------------------------
I 05-24 17:19:21 …
```
> [Spot] Fix spot failover when ibm enabled

- docs/source/getting-started/installation.rst
- sky/adaptors/cloudflare.py
- sky/cloud_stores.py
- sky/data/storage.py
- tests/test_smoke.py
Closes #1979.
These changes may potentially disrupt existing R2 users since the credentials path has changed. To mitigate, added a nicer message suggesting them to run `sky check`, which tells precisely the commands need to be run to get them running again.
E.g: switched from master to new branch -> run `sky launch` with R2 storage:
```
$ SKYPILOT_DEBUG=0 sky launch -c storage --cloud gcp test.yaml
Task from YAML spec: test.yaml
ValueError: Cloudflare credentials not found. Run `sky check` to verify credentials are correctly setup.
$ sky check
...
Cloudflare (for R2 object store): disabled          
Reason: [r2] profile is not set in ~/.cloudflare/r2credentials Run the following commands:
$ pip install boto3
$ AWS_SHARED_CREDENTIALS_FILE=~/.cloudflare/r2credentials aws configure --profile …
```
> [R2] Change credentials path for R2

- sky/backends/backend_utils.py
User has run into this rare error with spot controller (which has an assumed IAM role and is working fine most of the time).
We do not know the root cause. For now, the hypothesis is instance metadata service is temporarily unavailable. So, we retry the query.
- `sky status -r` (no-error case)
> AWS: Retry status fetch on 'Unable to locate credentials' error.

- .github/workflows/pytest.yml
The `test_optimizer_dryruns.py` takes long to finish in CI. This PR tries to reduce the parallelism for pytest to speed it up on github.
> [CI] Reduce parallelism for pytest

- docs/source/reference/cli.rst
- sky/cli.py
> Docs: add `sky cost-report` docstr to docs.

- sky/execution.py
- sky/skypilot_config.py
Repro
- `~/.sky/config.yaml` has some fields set, but not `aws.ssh_proxy_command`:
```
aws:
#
my-tag-1: my-value-1
my-tag-2: my-value-2
tag with spaces: my-value
value-with-spaces: my value
```
On master
```
» sky spot launch echo hi
...
File "/Users/zongheng/Dropbox/workspace/riselab/sky-computing/sky/execution.py", line 651, in spot_launch
common_utils.dump_yaml(tmpfile.name, config_dict)
UnboundLocalError: local variable 'config_dict' referenced before assignment
```
With this PR, the command went through.
(Useful: VSCode's Pylance correctly warned that `config_dict` is possibly unbound.)
> Fix `spot launch` error if config.yaml doesn't set ssh_proxy_command

- sky/cli.py
Previously, when `sky spot launch --retry-until-up echo hi` is executed, the retry_until_up will be set to False (weird semantics of the click package). This PR fixes that issue from #1781 
> [Spot] Retry until up for spot

- sky/backends/cloud_vm_ray_backend.py
Thanks for the report from a user. #1913 had a bug where sometimes we call `os.makedirs('~/sky_logs/...', ...)`, causing `$PWD/~/sky_logs` to be created in some cases.
Repro:
```
sky spot launch --cloud gcp echo hi  # Or pass a YAML where _execute_file_mounts() is to be triggered
```
With this PR, the above succeeds & `$PWD/~/sky_logs` is no longer created.
cc @cblmemo to take a look too.
> Fix creating `$PWD/~/sky_logs` in some cases.

- sky/backends/backend_utils.py
- sky/core.py
- sky/exceptions.py
- sky/spot/recovery_strategy.py
This PR is an attempt to fix a potential bug when running multi-node spot job. If the head node is preempted, the worker nodes may still have the job remaining there holding the system resources (e.g. GPU memory) and our original cancellation of the job will take no effect as the head node does not exist. We add a safeguard to stop all the nodes if the cancellation fails. 
Previously, the `sky.cancel` in the recovery_strategy does not take effect even if the worker node is preempted. To reproduce:
1. `sky launch -c test-4-nodes --cloud aws --use-spot --cpus 2+ sleep 10000`
2. manually terminate a worker node
3. `python -c "sky.cancel('test-4-nodes', all=True)` The cancel fails, and if we log into the cluster and run `ray job list` the job is still running.
To fix this issue, we add …
> [Spot] Stop the cluster if the cancellation fails

- sky/setup_files/setup.py
Current: https://skypilot.readthedocs.io/en/latest/reference/cli.html
This PR: https://skypilot.readthedocs.io/en/fix-docs-blockquotes/reference/cli.html
ef08910142723fe50bd97 changed `click<=8.0.4,>=7.0` to `click>=7.0`, which generated some weird blockquotes.
> Docs: fix blockquotes by adding back click<=8.0.4

- sky/clouds/aws.py
Several users (including https://github.com/skypilot-org/skypilot/issues/1997) have faced some `sky check` errors. This PR tries to surface the underlying exceptions to make it easier to debug.
> `sky check` UX: show underlying exceptions for AWS errors.

- sky/clouds/service_catalog/gcp_catalog.py
Previously, since we recently added the `L4` GPU in the GCP catalog, but have not supported it in SkyPilot yet. It causes the KeyError when the following command is called:
```
sky launch --cloud gcp --gpus L4 -t n1-highmem-8
```
It also causes the CI error here: https://github.com/skypilot-org/skypilot/actions/runs/5154043404/jobs/9294593850?pr=1909
> [GCP] Remove unsupported GPUs from the list_accelerators

- sky/clouds/service_catalog/data_fetchers/fetch_lambda_cloud.py
Update lambda data fetcher with new region (us-west-3) and H100.
The generated catalog can be found [here](https://github.com/skypilot-org/skypilot-catalog/pull/29)
> Update lambda data fetcher with new region (us-west-3) and H100

- sky/clouds/scp.py
Before this PR, the `sky check` is not well formated for the SCP, as the following:
```
SCP: disabled
Reason: Failed to access SCP with credentials. To configure credentials, go to:
https://cloud.samsungsds.com/openapiguide
to generate API key and add the line
access_key = [YOUR API ACCESS KEY]
secret_key = [YOUR API SECRET KEY]
project_id = [YOUR PROJECT ID]
to ~/.scp/scp_credential
```
After this PR:
```
SCP: disabled          
Reason: Failed to access SCP with credentials. To configure credentials, see: https://cloud.samsungsds.com/openapiguide
Generate API key and add the following line to ~/.scp/scp_credential:
access_key = [YOUR API ACCESS KEY]
secret_key = [YOUR API SECRET KEY]
project_id = [YOUR PROJECT ID]
```
> [SCP] Format the scp check

- sky/check.py
- sky/cloud_stores.py
- sky/clouds/gcp.py
- sky/data/storage.py
- sky/execution.py
- sky/templates/spot-controller.yaml.j2
Fixes #2016.
This PR also fixes an issue that the `$USER` is empty when under `root` account. This will cause the `SKYPILOT_USER` in `spot-controller.yaml` to be set to `None`, causing the failure for the controller to launch GCP cluster
```
Got googleapiclient.errors.HttpError: <HttpError 400 when requesting https://compute.googleapis.com/compute/v1/projects/skypilot-375900/zones/asia-south2-c/instances?alt=json returned "Invalid value for field 'resource.labels': ''. Label value 'None' violates format constraints. Th
e value can only contain lowercase letters, numeric characters, underscores and dashes. The value can be at most 63 characters long. International characters are allowed.". Details: "[{'message': "Invalid value for field 'resource.labels': ''. Label value 'None' violates …
```
> [Storage] Fix the storage cloud checking before sky.check is called.

- sky/backends/onprem_utils.py
on prem machines with a6000 or a5000 didn't work correctly because of a missing comma in the array the grep was for `lspci | grep 'A5000A6000'` which... isn't a card anyone has. 
I think it may make sense to have a look at this script, it feels quite fragile. Probably best would be to do this via `nvidia-smi -L` and just map against the ./.sky/catalog to find supported gpus.
Also, the way this made things fail was rather frustrating. 
Local clusters:
NAME   USER  HEAD_IP       RESOURCES    COMMAND
local  sky   [ip]  [(no GPUs)]  sky launch -c local --  -...
sky status showed (no GPUs) and sky launch fails predictably with `AssertionError: (Local(None), 'cloud, region and instance_type must have been set by optimizer')`  
sky launch -c local totally misreported the error as
```
Failed to …
```
> one byte fixing a5000 and a6000 on-prem

- sky/templates/aws-ray.yml.j2
- sky/templates/azure-ray.yml.j2
- sky/templates/gcp-ray.yml.j2
- sky/templates/ibm-ray.yml.j2
- sky/templates/lambda-ray.yml.j2
- sky/templates/scp-ray.yml.j2
- tests/test_smoke.py
Ray recently added the feature to duplicate the output from multiple workers, which is not desired in our case. https://docs.ray.io/en/latest/ray-observability/ray-logging.html#log-deduplication
To reproduce:
```
sky launch --num-nodes 4 --cloud gcp --cpus 2+  -c test-mn4 'echo $(hostname)'
```
> [Core] Avoid deduplication of the logs for multi-node job

- sky/task.py
Fixes #2021 
Reproducible task
```
resources:
cloud: Azure
file_mounts:
/tmp:
name: asdfasdfasdf
```
`sky launch -c test-storage` will raise error after confirmation for the storage:
```
ValueError: Unknown cloud type: Azure
```
> [Storage] Fix default storage selection

- sky/backends/backend_utils.py
- sky/backends/cloud_vm_ray_backend.py
- sky/skylet/constants.py
- sky/skylet/job_lib.py
- tests/test_smoke.py
> [Core] User ray cluster causes SkyPilot cluster in INIT state

- sky/templates/spot-controller.yaml.j2
Remove two messages that are printed in the `setup` part of every `spot launch`.
> Minor: remove two messages from `spot launch`.

- sky/backends/backend_utils.py
With OCI supported and enabled, I encountered the following error on every `sky launch`:
```
...
File "/Users/zongheng/Dropbox/workspace/riselab/sky-computing/sky/backends/backend_utils.py", line 975, in write_cluster_config
_optimize_file_mounts(tmp_yaml_path)
File "/Users/zongheng/Dropbox/workspace/riselab/sky-computing/sky/backends/backend_utils.py", line 228, in _optimize_file_mounts
f'Duplicated src basename: {src_basename}; mounts: {file_mounts}')
AssertionError: Duplicated src basename: config; mounts: {'~/.sky/sky_ray.yml': '/Users/zongheng/.sky/generated/sky-0fe1-zongheng.yml.tmp', '~/.sky/wheels/4ae6677e0222ae99e0d7c13323ab1f16': '/var/folders/8f/56gzvwkd3n3293xjlrztr6600000gp/T/4ae6677e0222ae99e0d7c13323ab1f16', '~/.aws/credentials': '~/.aws/credentials', …
```
> Fix: Allow credential files with the same basename.

- docs/source/examples/spot-jobs.rst
- sky/backends/backend_utils.py
- sky/execution.py
- sky/resources.py
- sky/spot/constants.py
- sky/templates/spot-controller.yaml.j2
Closing #2007, #1974, #1078.
It also mitigates #1094, as the user now can specify more CPUs for the controller.
With this PR, the user can specify resources spec for the spot controller so as to change the default cloud, customize the disk size or change the number of CPU cores (the maximum number of spot jobs == 2x #CPUs).
To customize the spot controller resources, the user can have a `~/.sky/config.yaml` with the following fields:
```
spot:
controller:
resources:
cloud: gcp
cpus: 20+
```
> [Spot] Make the controller resources configurable

- sky/backends/backend_utils.py
- sky/backends/cloud_vm_ray_backend.py
- sky/skylet/log_lib.py
- sky/spot/spot_utils.py
This PR fixes a problem caused by #1636, where the spot job not showing up in the `sky spot queue` if the spot job is in PENDING status. This is found when running the test in #2041.
Before this PR:
Only 1 pending spot job will show up in the `sky spot queue`, other later pending jobs will only appear when it starts running.
After this PR:
All the pending spot jobs will also appear in the `sky spot queue` with PENDING status.
> [Spot] Fix spot pending status

- sky/backends/backend_utils.py
Saw some parsing errors that threw ValueError.
This change
- uses regex to look for 'total size is ...'
- on error, return -1 as estimated size, as it's used for warnings only
- `sky launch test.yaml` with `workdir: .`; checked that sizes are correct
> Make path_size_megabytes() more robust.

- sky/setup_files/setup.py
> [Dependency] Avoid buggy grpcio version

- .github/pull_request_template.md
Updates the PR template to include a reminder to run format.sh - useful for first-time contributors who may not know about it or may have missed it.
> [Meta] Add format.sh to PR template

- sky/clouds/oci.py
- sky/clouds/service_catalog/oci_catalog.py
- sky/skylet/providers/oci/query_helper.py
This is a change made corresponding with the OCI catalog file (please kindly review the catalog file PR as well). In previous catalog file, there is a prefix in the AvailabilityZone, which is tenancy specific. So customer need to manually replace this prefix with according to his tenancy. This fix removes this neccesarity. The prefix in the catalog file is removed, and the program will find the correct prefix in runtime.
- Sky launch / sky down
- [v] Any manual or new tests for this PR (please specify below)
- [v] All smoke tests: `pytest tests/test_smoke.py` 
- [v] Relevant individual smoke tests: `pytest tests/test_smoke.py::test_fill_in_the_name` 
- [v] Backward compatibility tests: `bash tests/backward_comaptibility_tests.sh`
> [OCI fix] Add tenancy specific prefix to zone in runtime (use general catalog file)

- sky/core.py
Reported by Pylance in vscode.
Related: `pyright sky` found a ton of errors, a lot of them related to typing errors caused by decorators (pyright is what Pylance uses: https://microsoft.github.io/pyright/#/). The same as my vscode showing tons of warnings/errors. So we can’t integrate in one go into CI.
```
» pyright sky/core.py                           1 ↵
/Users/zongheng/Dropbox/workspace/riselab/sky-computing/sky/core.py
/Users/zongheng/Dropbox/workspace/riselab/sky-computing/sky/core.py:167:30 - error: "_Wrapped[(...), Unknown, (*args: Unknown, **kwargs: Unknown), Unknown]" is not iterable
  "__iter__" method not defined (reportGeneralTypeIssues)
/Users/zongheng/Dropbox/workspace/riselab/sky-computing/sky/core.py:204:32 - error: Expected 0 positional arguments …
```
> API: fix a possibly unbound error in core.cancel().

- tests/conftest.py
This is to avoid the tests to have leakage resources, if the people forgot to terminate the cluster after a test fails.
> [test] Default to terminate on failure

- sky/cli.py
> UX: don't print refresh hint on `status -r`.

- sky/skylet/providers/oci/node_provider.py
- sky/templates/oci-ray.yml.j2
This is a corner case. If start an existing cluster, but the backed nodes (or part of them) now have different ray-launch-config tag   value with the tags parameter in the create_node interface, the ray autoscaler will not accept those nodes as reusable. It will then stop those nodes, which are recognized by the OCI node provider as reusable, and then start new nodes instead. This is not expected behavior. We expect the nodes in the same cluster can be reused even if the ray-launch-config tag is different. 
- [v] Code formatting: `bash format.sh`
- [v] Any manual or new tests for this PR (please specify below)
sky launch / sky stop / sky down
- [v] All smoke tests: `pytest tests/test_smoke.py` 
- [v] Relevant individual smoke tests: `pytest …
> [OCI fix] Nodes are not reusable if launch config changed

- sky/backends/backend_utils.py
- sky/spot/recovery_strategy.py
- sky/utils/cli_utils/status_utils.py
I noticed that `status -r` is taking way too long. With some investigation with @Michaelvll, this PR Implemented two optimizations:
- delay the slower `ray status` call 
- use cached IPs
All tests below are 1-node on-demand GCP clusters. These are all "normal" case where the runtime on the cluster did not become problematic.
- TODO: we should keep speeding up refresh in the future.
Results:
**do `ray status` last + use_cached_ips=True**
STOPPED -> STOPPED
- before: 31s
- now: 3.7s
UP, autostop not set -> UP  
- before: 8.9s
- now: 7.1s
UP, autostopped -> STOPPED
- before: 22.2s
- now: 4.2s
UP, autostop set -> UP
- before: 7.6s
- now: 7.3s
INIT -> INIT
- before: 25.7s
- now: 22.3s
**(if we do the first optimization only) do `ray status` last** 
STOPPED -> STOPPED
- before: 31s
- now: 3.9s …
> Speed up refresh: delay the slower `ray status` call & use cached IPs.

- sky/backends/cloud_vm_ray_backend.py
> [ray] Fix the api called for placement group

- sky/clouds/service_catalog/data_fetchers/fetch_gcp.py
Previously, we are having two lists for expressing the supported series in the GCP catalog fetcher, which causes inconsistency and KeyError when any new instance_types are added. 
For example, the current master branch causes the following error:
```
if SERIES_TO_DISCRIPTION[series].lower() not in description.lower():
KeyError: 'ct5p'
```
This PR is to make the fetcher more robust by only using one list.
> [catalog] Make the price fetching more robust

- sky/resources.py
User got this error
> I 05-26 15:09:51 optimizer.py:1002] No resource satisfying AWS({'T4': 8}, image_id={'us-west-2': 'ami-1234'}) on AWS.
sky.exceptions.ResourcesUnavailableError: No launchable resource found for task train-1234. Region: us-west-2.
This means the catalog does not contain any instance types that satisfy this request.
To fix: relax or change the resource requirements.
Hint: 'sky show-gpus --all' to list available accelerators.
'sky check' to check the enabled clouds.
and mentioned
> But the actual reason was because I did not configure ssh_proxy_command in us-west-2
This change adds a friendlier warning.
Repro:
```
aws:
us-east-2: ...
```
```
resources:
cloud: aws
region: us-east-1
image_id: ami-0d8c624d9d0f9af69
```
We now show:
> » sky launch …
> UX: drop image_id warning, and print a hint for a corner case.

- sky/backends/backend_utils.py
- sky/cli.py
User reported that it's confusing an newly-INIT (abnormal) cluster suddenly had its autostop canceled. 
This PR adds a warning when that happens.
```
sky launch -c dbg -i10
sky status -r  # Observed warning.
```
> UX: if a cluster becomes INIT, warn about autostop reset.

- sky/clouds/service_catalog/oci_catalog.py
This is a small enhancement for OCI catalog. The OCI standard images are region specific (different region has different imageid for the same image), however, there are some images that have same imageid across regions, for example, Marketplace listing images. So this kind of cross-region images, we do not need to specify duplicated entries for each region, instead, we can configure a "general" one.
Please kindly also review the OCI catalog file (image.csv) as well. Note that this feature is backward compatible, means that the original images file also works fine.
- [v] Code formatting: `bash format.sh`
- [v] Any manual or new tests for this PR (please specify below)
sky launch (gputask)
- [v] All smoke tests: `pytest tests/test_smoke.py` 
- [v] Relevant …
> [OCI] Remove duplicated entries in images.csv (cross-region images)

- sky/clouds/oci.py
- sky/skylet/providers/oci/config.py
This PR is to fix the TODO action item for OCI disk_tier support. Detail test is performanced to map the skypiot disk_tier value to OCI VPU value:
disk_tier value in skypilot:
low: 500 IOPS; read 20MB/s; write 40 MB/s
medium: 3000 IOPS; read 220 MB/s; write 200 MB/s
high: 6000 IOPS; 340 MB/s; write 250 MB/s
oci vpu (Tested with fio tool, bs=(R) 64.0KiB-64.0KiB, (W) 64.0KiB-64.0KiB, (T) 64.0KiB-64.0KiB):
10:  2000 IOPS; read 127MB/s; write 132MB/s  (This is the default and minimal in OCI)
30:  3100 IOPS; read 203MB/s; write 202MB/s
100: 6700 IOPS; read 439MB/s; write 440MB/s
Relevant constants are defined in config.py (oci provider) with detailed test result information, as following:
DISK_TIER_LOW = 10
DISK_TIER_MEDIUM = 30
DISK_TIER_HIGH = 100
- [v] Code …
> [OCI] disk_tier to VPU mapping

- sky/__init__.py
- sky/backends/backend_utils.py
- sky/backends/cloud_vm_ray_backend.py
- sky/benchmark/benchmark_utils.py
- sky/cli.py
- sky/clouds/aws.py
- sky/clouds/azure.py
- sky/clouds/cloud.py
- sky/clouds/gcp.py
- sky/clouds/ibm.py
- sky/clouds/lambda_cloud.py
- sky/clouds/local.py
- sky/clouds/oci.py
- sky/clouds/scp.py
- sky/core.py
- sky/data/storage.py
- sky/exceptions.py
- sky/global_user_state.py
- sky/spot/controller.py
- sky/spot/recovery_strategy.py
- sky/spot/spot_utils.py
- sky/status_lib.py
- sky/usage/usage_lib.py
- sky/utils/cli_utils/status_utils.py
- tests/test_smoke.py
- tests/test_yamls/pipeline_aws.yaml
Previously, the cloud-specific status query functions are located in the `backend_utils` making adding new clouds and features for clouds not clean.
We now move the status query to the cloud class, making each cloud more modularized.
This PR is to simplify the process of adding cluster migration #2088.
This PR also fixes the status refresh for Azure multi-node cluster! Previously, refreshing the status for the multi-node Azure cluster will remove the cluster from table immediately.
> [Refactor] Move status query into the cloud class

- sky/skylet/configs.py
- sky/spot/spot_state.py
- sky/utils/db_utils.py
When developing a basic Flask app that eventually calls into `spot_state.get_spot_jobs()`, SQLite complained about threading errors. With `safe_cursor()` this error was fixed. This PR changes the entire spot_state module to use it.
- running
> [Spot] Make spot_state use safe_cursor().

- sky/skylet/providers/kubernetes/node_provider.py
- sky/templates/kubernetes-ray.yml.j2
- 'sky down' for `Kubernetes` cloud to remove cluster service resources.
> [k8s_cloud] Delete k8s service resources.

- docs/source/cloud-setup/cloud-auth.rst
- docs/source/getting-started/installation.rst
- sky/clouds/gcp.py
- tests/conftest.py
- tests/test_optimizer_dryruns.py
- tests/test_smoke.py
Fixes #2115 and #2109.
The problem causing the two issues is that we hardcoded the application default key path in our code to find the credentials. However, the user may specify the key in the environment variable `GOOGLE_APPLICATION_CREDENTIALS`
We now first check the env var to look for the credential file, if the env var does not exist, we will use the default path (same as the gcloud's behavior).
TODO:
```
Download the service account key
mv ~/.config/gcloud ~/.config/gcloud.bk
export GOOGLE_APPLICATION_CREDENTIALS="path/to/the/key/file"
gcloud auth activate-service-account --key-file $GOOGLE_APPLICATION_CREDENTIALS
gcloud config set project project-id
sky launch -c test-sa --cloud gcp --cpus 2 -i 0
sleep 120
sky status -r test-sa
```
> [GCP/Auth] Use the application key in the env var

- sky/clouds/azure.py
To reproduce,
1. `sky launch -c test-azure --cloud azure`
2. delete the cluster on the Azure console
3. `sky status -r`
The status query fails.
> [Azure] Fix status query for Azure

- sky/backends/backend_utils.py
- sky/backends/cloud_vm_ray_backend.py
- sky/clouds/gcp.py
Sometimes we see this error in GCP provisioning (see e.g., https://github.com/skypilot-org/skypilot/issues/1006). Here we make sure the provisioning loop doesn't get crashed.
This seems hard to reproduce. Running
```
sky launch --use-spot --gpus A100:8 --down --cloud gcp -c dbg --region us-central1 -ry
```
> GCP provisioning: handle 'wait_ready timeout exceeded'.

- sky/clouds/gcp.py
- sky/utils/ux_utils.py
Previously the `~/.config/gcloud/application_default_credentials.json` was not correctly uploaded due to the expanduser for the constant. To reproduce:
1. `sky launch -c test --cloud gcp --cpus 2`
2. `ssh test`
3. `sky check`
> [GCP] Fix the path to application credential

- sky/cli.py
Issue: #2123 
User feedback
> Small UX feedback: when I run sky spot dashboard, very often the page that opens first shows some error, and after a few seconds it automatically refreshes and loads. Slightly confusing user experience.
Added a delay between ssh command and webbrowser.open.
> [Spot/UX]: Spot dashboard Added delay for ssh_command to initialize

- docs/source/examples/spot-jobs.rst
- examples/spot/bert_qa.yaml
- examples/spot_pipeline/bert_qa_train_eval.yaml
This PR resolves #2127 
Currently, bert_qa example uses v4.18.0 [transformer repository](https://github.com/huggingface/transformers) from Huggingface. And this version contains a symlink that is dangling. The symlink set for directory transformers/examples/legacy/seq2seq/test_data/test_data does not exist in v4.18.0. This corrupted symlink was [recently fixed](https://github.com/huggingface/transformers/pull/22876). Hence, I'm updating the example doc to inform users to `git clone` the recent version, v4.30.1, of the transformer repo.
v4.18.0 will not have an issue when using S3 storage to store `workdir`, since `aws s3 sync` ignores such courrpted symlink and moves on with syncing. But the user with error in #2127 has set GCS to be the `workdir` storage, and `gsutil rsync -r` does not …
> [Spot, doc] Update transformer repository version from bert_qa example

- sky/clouds/azure.py
- sky/clouds/service_catalog/azure_catalog.py
- sky/clouds/service_catalog/common.py
- sky/clouds/service_catalog/data_fetchers/fetch_azure.py
Fixes #2148
Related to https://github.com/skypilot-org/skypilot-catalog/pull/37
> [Catalog/Azure] Add westus3 to the fetcher

- docs/source/getting-started/quickstart.rst
- sky/backends/cloud_vm_ray_backend.py
Motivation: Current Quickstart does not give any pointers on how to go from the simple 1-task example to a more advanced scaling-out mode, which is where SkyPilot shines.
This PR adds a small section there as a hint rather than a complete guide.   I think it's important to give some impression right at Quickstart that we can do it.
> Docs: add a "Scaling out" hint to Quickstart.

- sky/cli.py
- sky/resources.py
Previously, when `spot_recovery: none` is provided in the task.yaml, `sky launch task.yaml` will raise the following error, which is unexpected:
```
Task from YAML spec: test.yaml
ValueError: Spot recovery strategy NONE is not supported. The strategy should be among ['FAILOVER']
```
This PR, makes it go through the check when the `spot_recovery: none` is provided.
> [Spot] Fix the handling for `spot_recovery: none`

- examples/using_file_mounts_with_env_vars.yaml
- sky/backends/backend_utils.py
- sky/cli.py
- sky/clouds/gcp.py
- sky/data/storage.py
- sky/execution.py
- sky/task.py
- sky/utils/common_utils.py
- sky/utils/dag_utils.py
- sky/utils/schemas.py
- tests/test_optimizer_dryruns.py
- tests/test_smoke.py
```
#
file_mounts:
/mydir:
name: ${MY_BUCKET}  # Name of the bucket.
store: gcs
mode: MOUNT
/another-dir:
name: ${MY_BUCKET}-2
source: ["~/${MY_LOCAL_PATH}"]
store: gcs
mode: MOUNT
```
Overriding with `sky launch --env` works too.
Also fixes `sky launch` parsing errors: 
- Do not load YAML twice (which creates storage twice)
- Properly load empty / name-only YAMLs
Fixes #2093.
- `pytest tests/test_smoke.py::test_using_file_mounts_with_env_vars`
- `pytest tests/test_optimizer_dryruns.py`
> API/YAML: Support using env vars to define file_mounts.

- sky/backends/backend_utils.py
- sky/backends/cloud_vm_ray_backend.py
Our storage mounting was failing silently and not raising any exceptions. E.g., if you change the `install_cmd` to `exit 1`, it would still succeed. This was because we were not re-raising the exception when `e.returncode != exceptions.MOUNT_PATH_NON_EMPTY_CODE`.
New output:
```
(base) ➜  test_yamls git:(storage_mounting_fail_handling) ✗ SKYPILOT_DEBUG=0 sky launch -c test --cloud gcp temp_test_storage_mounting.yaml
Task from YAML spec: temp_test_storage_mounting.yaml
I 06-21 15:59:15 optimizer.py:636] == Optimizer ==
I 06-21 15:59:15 optimizer.py:647] Target: minimizing cost
I 06-21 15:59:15 optimizer.py:659] Estimated cost: $0.4 / hour
I 06-21 15:59:15 optimizer.py:659] 
I 06-21 15:59:15 optimizer.py:732] Considered resources (1 node):
I 06-21 15:59:15 optimizer.py:781] …
```
> [Storage] Mount failure exception handling fix

- sky/setup_files/setup.py
The recent release of pydantic 2.0 is not compatible with ray's job API, causing all our job management failed.
To reproduce:
```
sky launch -c test --cpus 2 echo hi
```
> [Dependency] Limit pydantic version

- sky/__init__.py
- sky/resources.py
```
```
```
sky launch -c dbg --cloud aws --num-nodes 16 --cpus 2+ --down  # with or without timeout bump
sky down dbg  
```
```
sky down dbg
```
```
sky launch -c dbg --cloud gcp --num-nodes 16 --cpus 2+ --down  # with or without timeout bump
sky down dbg  
```
```
sky launch -c dbg --cloud gcp --num-nodes 16 --gpus T4 --down 
sky down dbg
```
> Release v0.3.2

- sky/clouds/azure.py
Currently, Azure clusters launched without `disk_tier` specified will have a `disk_tier` in its `Resources` in the `sky status` command. This PR get rid of the redundant information.
```shell
$ sky launch --cloud azure
Clusters
NAME                          LAUNCHED        RESOURCES                                    STATUS   AUTOSTOP  COMMAND                         
cluster-name                  a few secs ago  1x Azure(Standard_D8s_v5, disk_tier=medium)  UP       -         sky launch --cloud azure ...   
```
> [UX] Fix redundant disk tier information when default tier is used

- sky/backends/backend_utils.py
- sky/backends/cloud_vm_ray_backend.py
This PR closes #2113 
When `rsync` is not installed in the user's machine, `ray_up()` is reattempted for `_MAX_RAY_UP_RETRY` number of times without failing. As this is time consuming, this PR fails early in the provisioning step when `rsync` is not installed and gently hints the user to install `rsync`.
Considered failing from `need_ray_up()` as well, but at this point, `state.db` is already updated with `INIT` status of the cluster attempted to provisioned which isn't the most optimal scenario. Also, it takes time for single failure before reaching `need_ray_up()`.
> [UX] Fail early from provisioning when rsync is uninstalled

- sky/data/storage_utils.py
This provides a solution for #2030.
> [Storage] Fix misleading storage ls table column name

- sky/cloud_stores.py
- sky/data/storage.py
This PR closes #2147, which is initially raised by #2127
`aws s3 sync` is a command ran to sync Sky Storages set with `s3`/`r2` storages. When the command sees a dangling symlink, it simply ignores and continue to sync other contents. However, `gsutil rsync`, which is used to set `gcs`, does not support this and fails early. In order to have consistent behavior between `gcs` and `s3`/`r2` storages, I add an additional flag to the command to ignore all the symlinks in the source. Adding `-e` is the [solution gsutil team provides](https://github.com/GoogleCloudPlatform/gsutil/issues/222) to resolve dangling symlink issue. Also, as Sky Storage does not support symlinks, this is a suitable solution.
`
> [Storage] gsutil rsync failing to sync source with dangling symlink

- docs/source/examples/spot-jobs.rst
- docs/source/reference/yaml-spec.rst
- docs/source/running-jobs/environment-variables.rst
- docs/source/running-jobs/index.rst
> Docs: add "Using Environment Variables".

- docs/source/getting-started/quickstart.rst
Our quickstart uses codeblocks to visually indicate important commands that the user should know/run. Example:
However, in the `Stop/terminate a cluster` section, we use inline code, which is easy to miss:
This PR changes the down/stop commands to be code blocks:
> [Docs] Add code blocks for down and stop in Quickstart

- sky/skylet/providers/gcp/node_provider.py
This is a bug in GCP node_provider, where an unnecessary variable is returned, which is not defined in one code path.
Reference: https://github.com/ray-project/ray/blob/547dd8c125b0e2007b1fb8960b514bd2c89e1963/python/ray/autoscaler/_private/gcp/node_provider.py#L183-L205
~~The parallel termination is adopted from: https://github.com/ray-project/ray/commit/46fc66390cb136a52afd6d70808f7c01eb31deb0~~
We revert the adoption of the parallel termination as that implementation is buggy with the following repro:
1. `sky launch -c test --cloud gcp --cpus 2 --num-nodes 8`
2. `sky stop test`, the following error shows up:
```
malloc(): unsorted double linked list corrupted
```
> [GCP] Fix unbounded return value

- docs/source/running-jobs/environment-variables.rst
In last PR, forgot to add a clear snippet to copy paste & adapt.
> Docs: minor touches on env vars doc.

- sky/backends/backend_utils.py
Currently, when launching with Azure, it will generate a warning message indicating multiple IPs found for the `ray get-head-ip` command:
```bash
(sky-dev) ➜  skypilot git:(75ccbf4a) sky launch -c az --cloud azure
I 07-08 16:46:58 optimizer.py:636] == Optimizer ==
I 07-08 16:46:58 optimizer.py:648] Target: minimizing cost
I 07-08 16:46:58 optimizer.py:659] Estimated cost: $0.4 / hour
I 07-08 16:46:58 optimizer.py:659] 
I 07-08 16:46:58 optimizer.py:733] Considered resources (1 node):
I 07-08 16:46:58 optimizer.py:781] ----------------------------------------------------------------------------------------------
I 07-08 16:46:58 optimizer.py:781]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 07-08 16:46:58 optimizer.py:781] …
```
> Remove unintended warning message when provisioning Azure

- sky/clouds/gcp.py
Fixes #2184 
This PR makes the `sky check` provides information based on the status of the user's current setup.
Missing dependency:
```
$ sky check
AWS: enabled          
Azure: enabled          
GCP: disabled          
Reason: GCP tools are not installed. Run the following commands:
$ pip install google-api-python-client
$ conda install -c conda-forge google-cloud-sdk -y
Credentials may also need to be set. Run the following commands:
$ gcloud init
$ gcloud auth application-default login
For more info: https://skypilot.readthedocs.io/en/latest/getting-started/installation.html#google-cloud-platform-gcp
Details: [builtins.ModuleNotFoundError] No module named 'googleapiclient'
Lambda: enabled          
IBM: enabled          
SCP: enabled …
```
> [UX] Make sky check more fine-grained for GCP

- sky/check.py
- sky/cli.py
- sky/clouds/aws.py
- sky/clouds/azure.py
- sky/clouds/cloud.py
- sky/clouds/gcp.py
This PR adds an `--all` option for the `sky check`, so that the user could see more details about the enabled cloud, such as the currently activated account.
This PR also adds checks for the `--disk-tier` option
> [UX] Add currently activated account for the `sky check` and check for disk-tier options

- sky/skylet/log_lib.py
- sky/utils/subprocess_utils.py
Fixes #2205.
The `os.killpg` might be applied to a subprocess that was attached under the root user, due the parent process being killed first. This will cause the `PermissionError: [Errno 1] Operation not permitted`
@concretevitamin Could you verify if this solve the problem?
> [UX] Fix unexpected output for ctrl-c during `sky launch`

- docs/source/getting-started/installation.rst
Typo fix: The command `gcloud project list` should be `gcloud projects list`
> Typo: Fix gcloud command in installation docs

- sky/resources.py
As shown in the title, this PR fixes the `is_empty` function in `resources` class when `disk_tier` is not None.
> Fix `is_empty` when disk tier is not None

- sky/backends/cloud_vm_ray_backend.py
This PR disables the touch of the logfile when using dryrun mode.
> Disable the touch of the logfile when dryrun

- sky/cli.py
- sky/data/storage_utils.py
- sky/utils/cli_utils/status_utils.py
Truncates long `COMMAND` strs in `sky storage ls`, like we do in `sky status`.
Before:
```
(base) ➜  ~ sky storage ls
NAME                       CREATED     STORE  COMMAND                                   STATUS
romil-debug-parq           22 hrs ago  S3     sky launch parquet_test.yaml --cloud gcp  READY
```
After:
```
(base) ➜  ~ sky storage ls
NAME                       CREATED     STORE  COMMAND                       STATUS
romil-debug-parq           22 hrs ago  S3     sky launch parquet_test.y...  READY
...
(base) ➜  ~ sky storage ls -a    
NAME                 CREATED    STORE  COMMAND                                                                                                                            STATUS  
sky-test-1688589264  1 day ago  S3     sky launch -y -c …
```
> [Storage] Truncate long command str in `sky storage ls`

- sky/clouds/lambda_cloud.py
If your internet is down (e.g., wifi is off) or lambda cloud is inaccessible, `sky check` would fail for lambda cloud with a fatal error:
```
Checking Lambda...socket.gaierror: [Errno 8] nodename nor servname provided, or not known
During handling of the above exception, another exception occurred:
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x16d9c7e80>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known
During handling of the above exception, another exception occurred:
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='cloud.lambdalabs.com', port=443): Max retries exceeded with url: /api/v1/instances (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x16d9c7e80>: …
```
> [UX] Add network failure handling for Lambda `sky check`

- sky/clouds/azure.py
- sky/clouds/cloud.py
- sky/clouds/ibm.py
- sky/clouds/lambda_cloud.py
- sky/clouds/scp.py
- sky/resources.py
The failover function in the optimizer helps us get rid of invalid resources for a certain cloud. Say if we specify `--disk-tier high` when `sky launch`, we wanted the optimizer only pick clouds that support the customized `disk_tier` feature.
Previously, we have to manually modify `_get_feasible_launchable_resources` function in all cloud to handle the special case: return an empty list to the optimizer when one unsupported feature is used, so that the optimizer will skip this cloud since no valid resources are found. This PR refactors the implementation of this function, by describing unsupported features in resources with `clouds.CloudImplementationFeatures`, and adding a check before we step in cloud-specific `_get_feasible_launchable_resources` functions.
After this PR is merged, …
> Refactor failover when resources have some unsupported features on certain cloud

- sky/backends/cloud_vm_ray_backend.py
> [Core] Avoid signal when sky.launch is not executed in the main thread

- tests/test_smoke.py
This resolves #2258 
This fixes by running `sky storage delete` on the storage objects created from the test rather than all with `-a`
> [Storage] Fix test_multiple_buckets_creation_and_deletion from test_smoke.py

- sky/__init__.py
```
```
```
sky launch -c dbg --cloud aws --num-nodes 16 --cpus 2+ --down  # with or without timeout bump
sky down dbg  
```
```
sky down dbg
```
```
sky launch -c dbg --cloud gcp --num-nodes 16 --cpus 2+ --down  # with or without timeout bump
sky down dbg  
```
```
sky launch -c dbg --cloud gcp --num-nodes 16 --gpus T4 --down 
sky down dbg
```
> Release v0.3.3

- sky/serve/examples/http_server/README.md
- sky/serve/examples/http_server/server.py
- sky/serve/examples/http_server/task.yaml
Add an HTTP server example for SkyServe.
> [SkyServe] add http server example

- sky/cli.py
- sky/skylet/providers/kubernetes/utils.py
- sky/utils/kubernetes/delete_cluster.sh
Changes:
1. Remove prompt asking for confirmation to override `~/.kube/config` in `sky local up` since `kind` does not override the kube config (it just adds new entries to the `clusters`, `users` and `contexts` list)
2. Set the first available context as `current-context` in kube config after deletion of `kind` cluster in `sky local down`. Upon deletion, `kind` sets the `current-context` field to empty in the kube config, which causes `kubectl` commands to fail. So we set a previous context (if available).
> Handle kube config management for sky local commands

- sky/backends/cloud_vm_ray_backend.py
This PR partially fixes #1603 by adding an error message that indicates rsync is not found in the specified image, so that users don't need to dive deep into SkyPilot code to figure out why.
#1641 and #1910 will add cloud-init support for GCP and Azure. After these two are merged, we could have a new PR to add the installation of rsync.
An example of the error message:
```
(sky-dev) ➜  skypilot git:(fix-rsync-not-exist) ✗ sky launch --cloud gcp --image-id projects/skypilot-375900/global/images/no-rsync-centos
I 07-16 14:41:11 optimizer.py:636] == Optimizer ==
I 07-16 14:41:11 optimizer.py:648] Target: minimizing cost
I 07-16 14:41:11 optimizer.py:659] Estimated cost: $0.4 / hour
I 07-16 14:41:11 optimizer.py:659] 
I 07-16 14:41:11 optimizer.py:733] Considered resources (1 node):
I 07-16 …
```
> Add error message for rsync not found in image

- sky/setup_files/setup.py
<= 3.13 may encounter https://github.com/ultralytics/yolov5/issues/414.
Tested `pip install -e`:
```
Collecting pyyaml<=5.3.1,>3.13
Downloading PyYAML-5.3.1.tar.gz (269 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 269.4/269.4 kB 4.2 MB/s eta 0:00:00
Preparing metadata (setup.py) ... done
```
Note however at the end
```
kubernetes 26.1.0 requires pyyaml>=5.4.1, but you have pyyaml 5.3.1 which is incompatible.
Successfully installed pyyaml-5.3.1 skypilot-1.0.0.dev0
```
which means our k8s support seems to conflict with the explicit `<= 5.3.1` pin. @romilbhardwaj 
> Minor: require pyyaml > 3.13 to avoid an error.

- docs/source/cloud-setup/cloud-permissions/aws.rst
- docs/source/index.rst
- docs/source/reference/config.rst
- docs/source/running-jobs/environment-variables.rst
> Doc: add doc for ~/.sky/config.yaml.

- sky/skylet/constants.py
- sky/templates/aws-ray.yml.j2
- sky/templates/azure-ray.yml.j2
- sky/templates/gcp-ray.yml.j2
- sky/templates/ibm-ray.yml.j2
- sky/templates/lambda-ray.yml.j2
- sky/templates/oci-ray.yml.j2
- sky/templates/scp-ray.yml.j2
- tests/test_smoke.py
Fixes #2273 
Running `conda init` for the cluster with conda installed under `/opt/conda` will cause the problem mentioned in #2273.
This PR fixes that issue
> [Core] Avoid running conda init for the VM with conda installed under /opt/conda

- examples/spot/lightning_cifar10.yaml
- examples/spot/lightning_cifar10/requirements.txt
This PR closes #2224 
With the current [`requirements.txt`](https://github.com/skypilot-org/skypilot/blob/master/examples/spot/lightning_cifar10/requirements.txt), the example fails. After some investigation, figured out that the version of `torchmetrics` installed with `torchmetrics >= 0.3`, 0.11.4(most recent version), has issues of confusing `torchmetrics.functional.accuracy` with `torchmetrics.Accuracy`, which results in an error. `torchmetrics.functional.accuracy`, which is meant to be used in the example, does not take `task` as an argument, but `torchmetrics.Accuracy` [does](https://torchmetrics.readthedocs.io/en/stable/classification/accuracy.html). As other requirements(`pytorch-lightning` and `lightning-bolts`) require `torchmetrics >= 0.4.1`, I am setting `torchmetrics==0.4.1` …
> [Spot, Example] Fix failing example: lightning_cifar10

- sky/backends/backend_utils.py
Fix the bug reported from https://github.com/skypilot-org/skypilot/issues/2270.
In GCP, the `.` in the local OS username violates the 'resource.labels' format constraints.
> clean the username format before using as SKYPILOT_USER

- sky/backends/cloud_vm_ray_backend.py
- sky/provision/__init__.py
- sky/provision/aws/instance.py
- sky/provision/gcp/instance.py
- sky/skylet/events.py
Fixes #2247 
This is a quick draft for the implementation. @suquark please feel free to check it out.
> [Provisioner] Use new termination for autostop

- examples/sample_dotenv
- sky/cli.py
- sky/setup_files/setup.py
- tests/test_smoke.py
Fixes #2295
A new argument is added `--env-file`.  This reads from a dotenv file to read multiple environment variables.  These are merged with any values passed via `--env` arguments with `--env` taking precedence in any conflicts.
No unittests seem to exist for this.  Manually ran the command:
```sh
sky launch -c worker-unified-llama13b --env-file .env sky/fastchat_unified_llama13b.yaml
```
with a local config that depends on two env variables within `.env`.
> Add support for env files. 

- sky/backends/cloud_vm_ray_backend.py
- sky/skylet/providers/lambda_cloud/lambda_utils.py
This PR fixes #2261 by:
* Add retry with backoff to all Lambda API requests when the rate limit exceeds;
* Retry launching when exceeding the rate limit.
TODO: debug and verify it works properly
> Fix Lambda rate limit by backoff and retry when exceeding

- sky/skylet/providers/kubernetes/utils.py
Hi @romilbhardwaj ,
I encountered an issue where ray pods and services are not created under the namespace defined in the current context (by defining it via `kubectl config set-context --current --namespace=<namespace name>`).
This PR seems to fix the issue under my environment. Can you please review it?
Thanks.
Please find below what I did:
`sky local up` # wait for kind to create skypilot cluster
`kubectl config set-context --current --namespace=test`
`kubectl create ns test`
`sky launch   ../tasks/hi.yaml` # very simple task that echoes
Ray pod and services are created under `default` namespace rather than `test`. The provision seems to hang since the secret is being created under `test` namespace.
Looking into it more, it seems that namespace of the current context is located under …
> [k8s_cloud] Ray pod not created under current context namespace.

- sky/utils/cli_utils/status_utils.py
This PR fixes #1779 by introducing `HEAD_IP` column in `sky status -a`.
One example:
```bash
(sky-dev) ➜  skypilot git:(show-ip-in-status) ✗ sky status -a
Clusters
NAME             LAUNCHED        RESOURCES              REGION       ZONE           STATUS  AUTOSTOP  HEAD_IP        COMMAND                 
sky-0a05-memory  a few secs ago  1x GCP(n2-standard-8)  us-central1  us-central1-a  UP      -         34.122.179.25  sky launch --cloud gcp  
Managed spot jobs
No in progress jobs. (See: sky spot -h)
```
> [UX] Show head ip in `sky status -a` 

- sky/authentication.py
- sky/templates/gcp-ray.yml.j2
Fixes #2309
We did not include the metadata ssh key setup code path for the TPU VM in our ray yaml causing the provisioned cluster failed to be connected with the user's ssh key.
> [GCP] Fix TPU VM ssh key setup

- sky/backends/backend_utils.py
- sky/clouds/aws.py
- sky/provision/__init__.py
- sky/provision/aws/__init__.py
- sky/provision/aws/instance.py
Adopt new provisioner to query cluster status, i.e. instances and their status.
> [AWS] Adopt new provisioner to query clusters 

- sky/backends/backend_utils.py
- sky/templates/aws-ray.yml.j2
- sky/templates/azure-ray.yml.j2
- sky/templates/gcp-ray.yml.j2
- sky/templates/ibm-ray.yml.j2
- sky/templates/lambda-ray.yml.j2
- sky/templates/local-ray.yml.j2
- sky/templates/oci-ray.yml.j2
- sky/templates/scp-ray.yml.j2
During the launching process, in https://github.com/skypilot-org/skypilot/blob/ca6d1e841875df290667cee02082ae7e2149126a/sky/backends/cloud_vm_ray_backend.py#L2624 we attempt to restart the remote skylet if the version is mismatched with the version file `sky.skylet.constants.SKYLET_VERSION_FILE`. However, the version file is not synced up or created in the remote VM, which means the `python3 -m sky.skylet.attempt_skylet` command will always restart the skylet. This PR removed the start of skylet in the `head_start_ray_commands` section inside `<cloud>-ray.yml.j2` file and let `python3 -m sky.skylet.attempt_skylet` to start skylet.
> Fix redundant start of skylet

- sky/clouds/service_catalog/__init__.py
Fixes #2317 
I manually tested with using the CLI
```
$ sky show-gpus --cloud lambda
COMMON_GPU  AVAILABLE_QUANTITIES  
A10         1                     
A100        1, 2, 4, 8            
A100-80GB   8                     
H100        1                     
V100        8 
$ sky show-gpus --cloud aws
COMMON_GPU  AVAILABLE_QUANTITIES  
A10G        1, 4, 8               
A100        8                     
A100-80GB   8                     
H100        8                     
K80         1, 8, 16              
M60         1, 2, 4               
T4          1, 4, 8               
V100        1, 4, 8               
V100-32GB   8   
``` 
> add H100 to supported GPUs

- sky/cli.py
Partially address #1877.
When I have only 1 cluster in `status`:
Previously
```
(py37) ~ » sky down
Usage: sky down [OPTIONS] [CLUSTERS]...
Try 'sky down -h' for help.
Error: `sky down` requires either a cluster name (see `sky status`) or --all.
```
This PR makes it so that `down/stop` defaults to it:
```
(py37) ~ » sky down                                                                                            2 ↵
Terminating 1 cluster: admin. Proceed? [Y/n]: ^CAborted!
(py37) ~ » sky stop                                                                                            1 ↵
Stopping 1 cluster: admin. Proceed? [Y/n]: ^CAborted!
```
When I have 0 cluster in `status`: this PR
```
(py37) ~ » sky down
Cluster(s) not found (tip: see `sky status`).
```
Same for `sky start`.
Tested …
> CLI: make `sky down/stop/start` default to a unique cluster if exists.

- sky/setup_files/setup.py
Fixes #2204 
It is hard to decide the minimal AWS dependencies. I am using the minimal dependency that works with SSO.
```
[tool.poetry]
name = "foo"
version = "1.0.0"
authors = ["ZW"]
description = ""
[tool.poetry.dependencies]
python = "3.10.x"
[tool.poetry.group.dev.dependencies]
skypilot = { git = "https://github.com/skypilot-org/skypilot.git", branch = "fix-poetry" }
[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```
```
[tool.poetry]
name = "foo"
version = "1.0.0"
authors = ["ZW"]
description = ""
[tool.poetry.dependencies]
python = "3.10.x"
[tool.poetry.group.dev.dependencies]
skypilot = { git = "https://github.com/skypilot-org/skypilot.git", branch = "fix-poetry" , extras = ["gcp"] }
[build-system]
requires = …
```
> Add minimal version for AWS dependencies to fix poetry

- sky/spot/controller.py
Fixes #2329 
This should make the debugging of the user program much easier.
> [Spot] Switch to download and streaming for the failed user program logs

- sky/cloud_stores.py
During the work on adding minio support I have encountered an issue related to Bucket name where I fixed it in:
https://github.com/skypilot-org/skypilot/pull/2315/commits/e4424db1ba12bf99f0ff8fbeeaab1dc8445b7523
I then noticed that this possible issue can also exist in R2 (which is also S3 compatible). I added this fix in this PR.
I can not validate it since I do not have an R2 account.
- [ v ] Code formatting: `bash format.sh`
> [Storage/R2] Fix possible invalid bucket name.

- sky/adaptors/kubernetes.py
- sky/backends/cloud_vm_ray_backend.py
- sky/clouds/cloud.py
- sky/clouds/kubernetes.py
- sky/task.py
- sky/utils/common_utils.py
Adds a class method to `Cloud` called `query_env_vars` which can query cloud specific env vars. Addresses https://github.com/skypilot-org/skypilot/issues/2287
> Query cloud specific env vars in task setup

- sky/backends/cloud_vm_ray_backend.py
- sky/utils/tpu_utils.py
Fix a bug for TPU pod where the actual number of node ips != `launched_nodes`. (from port PR https://github.com/skypilot-org/skypilot/pull/2210)
the bug caused failures in setup and workdir sync on worker nodes.
> fix tpu bug

- sky/adaptors/aws.py
Address the credential fetching issue mentioned in https://github.com/skypilot-org/skypilot/pull/2288
> Fix AWS credential creation error handling

- sky/callbacks/setup.py
- sky/callbacks/sky_callback/api.py
Fix #2363 
According to [docs](https://docs.python.org/3.7/library/collections.html#:~:text=Deprecated%20since%20version%203.3%2C%20will%20be%20removed%20in%20version%203.9%3A%20Moved%20Collections%20Abstract%20Base%20Classes%20to%20the%20collections.abc%20module.%20For%20backwards%20compatibility%2C%20they%20continue%20to%20be%20visible%20in%20this%20module%20through%20Python%203.8.), It looks like Collections Abstract Base Classes are moved to the second-level module since Python 3.3, but had been available for backwards compatibility through Python 3.8. So existing code can be ran on Python 3.8, but no on Python >= 3.9.
Since SkyPilot's Python dependency is Python >= 3.7 according to [your docs](https://skypilot.readthedocs.io/en/latest/getting-started/installation.html#enabling-shell-c …
> [FIX] SkyCallback not working on newer version of Python

- examples/detectron2_app.yaml
Closes #2365 by changing conda env to py 3.8. `cached_property` was  introduced in `functools` from python 3.8.
Tested:
> [Examples] Fix detectron example

- sky/cli.py
Currently, when installing, skypilot will write `# For SkyPilot shell completion\n. ~/.sky/.sky-complete.zsh` to the end of `~/.zshrc`. If there are no new line at the end of `~/.zshrc`, the comment will append at the last line, such as:
```bash
alias gs="git status"# For SkyPilot shell completion
. ~/.sky/.sky-complete.zsh
```
which will cause some bugs such as:
```bash
git: 'status#' is not a git command. See 'git --help'.
The most similar command is
status
```
This PR add a `\n` before the comment to avoid such bug.
> [FIX] Fix no new line bug when installing sky auto completion

- sky/clouds/cloud.py
- sky/optimizer.py
Our unsupported feature check in the optimizer does not include the multi-node feature. That will make the optimizer output including some clouds that do not support that feature. This will help #2352 fail early, when the `specific_reservations` is specified and multiple nodes are used -- excluding it from the optimizer table, instead of failing during the provisioning.
To reproduce (SCP below does not support multiple nodes):
```
sky launch --num-nodes 2  ✱
I 08-09 14:05:10 optimizer.py:636] == Optimizer ==
I 08-09 14:05:10 optimizer.py:647] Target: minimizing cost
I 08-09 14:05:10 optimizer.py:659] Estimated cost: $0.3 / hour
I 08-09 14:05:10 optimizer.py:659] 
I 08-09 14:05:10 optimizer.py:732] Considered resources (2 nodes):
I 08-09 14:05:10 optimizer.py:781] …
```
> [Core] Filter out cloud that does not support multi node early

- sky/skylet/providers/lambda_cloud/lambda_utils.py
Users have reported seeing this exception being triggered without much info.
> Minor: print more detailed Lambda errors.

- sky/clouds/azure.py
This is to mitigate the problem in #2376, where the user fail to see the detailed error in `sky check`.
> [Azure] Show detailed error for azure credential check

- sky/clouds/gcp.py
To reproduce:
1. `sky launch -c test --cloud gcp` before #2352 
2. `sky start test -f` after #2352
```
in wrapper
c = cache(self)
AttributeError: 'GCP' object has no attribute '_list_reservations_cache'
```
> [GCP] Add default value for cache to fix backward compatibility

- sky/backends/backend_utils.py
- sky/clouds/cloud.py
- tests/conftest.py
- tests/test_optimizer_dryruns.py
This is a follow-up of #2352. 
Since our backend matches the worker name to see if the cluster has been provisioned, we need to update our regex for that matching.
- 2 nodes: 1 specific, 1 auto
- 2 nodes: 2 specific
- 1 node: 1 specific
- 3 nodes: 2 specific, 1 auto
> [GCP] Support reservations for multi-node

- sky/templates/aws-ray.yml.j2
- sky/templates/azure-ray.yml.j2
- sky/templates/gcp-ray.yml.j2
- sky/templates/ibm-ray.yml.j2
- sky/templates/lambda-ray.yml.j2
- sky/templates/oci-ray.yml.j2
- sky/templates/scp-ray.yml.j2
This is a minor improvement of the readability of the setup in ray yaml. ~~It is also an attempt for fixing #2378~~
> [Minor] Create sky_workdir without depending on the ray installation

- sky/resources.py
The reservation pool is not available for the spot VMs. We should avoid using reservations for spot.
To reproduce:
1. Have a specific reservation in us-central1-c with n2-standard-2
2. `sky launch -c test-spot --cpus 2 --cloud gcp`
> [GCP reservation] Avoid using reservation for spot VMs

- examples/resnet_app.py
- examples/resnet_app.yaml
- examples/resnet_app_storage.py
- examples/resnet_app_storage.yaml
- examples/resnet_app_storage_spot.yaml
Closes #2358.
Resnet examples (`resnet_app*.py/yaml`) were not working on master because `CUDNN_PATH` and `LD_LIBRARY_PATH` environment variables were not set correctly. Python examples also had issues with up local workdir.
Fixed by following [tensorflow docs](https://www.tensorflow.org/install/pip#software_requirements) to setup envvars correctly. 
> [Examples] Fix resnet family of examples

- sky/skylet/providers/aws/node_provider.py
- sky/skylet/providers/azure/azure-vm-template.json
- sky/skylet/providers/azure/config.py
- sky/skylet/providers/azure/node_provider.py
- sky/skylet/providers/gcp/node_provider.py
In #2375 some updates to the cloud provider were accidentally removed. IIUC it is from [this commit](https://github.com/skypilot-org/skypilot/pull/2375/commits/780ec2aa446b74c57f634425b7a98657a08d9ca6) in which author directly checkout original master, so some updates got removed. This PR fixed this problem.
- `sky launch -c cbl-test-az --region eastus2 --cloud azure tests/test_yamls/minimal.yaml`
> Fix accidentally removed updates to cloud provider

- sky/serve/examples/llama2/llama2.yaml
without specifying extra dependencies, we'll encounter
```
(task, pid=12740) ModuleNotFoundError: No module named 'torch'
```
also huggingface is no longer needed to install from master.
> fix serve example

- sky/setup_files/setup.py
This helps the user with the latest ray version installed on local machine to use SkyPilot.
> [Dependency] Allow latest ray version on local machine

- sky/backends/cloud_vm_ray_backend.py
- sky/provision/gcp/instance.py
Currently, if our provision loop failed due to out-of-capacity, we’ll proceed to try to tear it down, but the VM may not be created. This PR fixes the problem by not raising exceptions if such resource is not found.
> Fix retry cleanup when resource not created

- sky/authentication.py
- sky/backends/backend_utils.py
- sky/backends/cloud_vm_ray_backend.py
- sky/clouds/kubernetes.py
- sky/skylet/providers/kubernetes/node_provider.py
- sky/skylet/providers/kubernetes/utils.py
- sky/templates/kubernetes-ray.yml.j2
- sky/templates/kubernetes-sshjump.yml.j2
- sky/utils/kubernetes/sshjump-lcm.py
- sky/utils/kubernetes/sshjump_lcm.py
Add an initial support for ssh jump host.
By this, only single port (nodeport) is opened on a target k8s cluster where ssh connections established from skypilot user targeted to ray cluster - are tunneled through ssh jump host pod.
> [k8s_cloud_beta1] Add sshjump host support.

- docs/source/cloud-setup/cloud-permissions/gcp.rst
As mentioned by @alex000kim, for a user from scratch, we need an additional permission to have the skypilot correctly create the service account on GCP.
> [GCP] Additional permission for GCP in doc

- sky/provision/aws/instance.py
Previously our filtering API for port cleanup will only query the security group from the default VPC. When your SG is created elsewhere, the botocore will complain about it:
```
File "/opt/conda/bin/sky", line 8, in <module>
File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1053, in main
File "/opt/conda/lib/python3.10/site-packages/sky/utils/common_utils.py", line 248, in _record
File "/opt/conda/lib/python3.10/site-packages/sky/cli.py", line 1153, in invoke
File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1659, …
```
> [Fix] Fix AWS SecurityGroup cleanup when the SG is not created on default VPC

- sky/backends/backend_utils.py
- sky/backends/cloud_vm_ray_backend.py
- sky/cli.py
- sky/core.py
- sky/skylet/job_lib.py
- sky/utils/common_utils.py
Fixes #2316.
Changes
- Make `sky cancel <cluster>` default to cancel the latest running job of a cluster (From user feedback)
- Print actually cancelled job IDs in all cases
Examples
```console
» sky cancel dbg                                      
No job IDs or --all provided; cancelling the latest running job.
Cancelling the latest running job on cluster 'dbg'. Proceed? [Y/n]:
I 08-18 08:31:23 cloud_vm_ray_backend.py:3461] Cancelled jobs: 10
» sky cancel dbg
No job IDs or --all provided; cancelling the latest running job.
Cancelling the latest running job on cluster 'dbg'. Proceed? [Y/n]:
I 08-18 08:32:09 cloud_vm_ray_backend.py:3465] No jobs cancelled. They may already be in terminal states.
» sky cancel dbg -a
Cancelling all jobs on cluster 'dbg'. Proceed? [Y/n]:
Cancelling all jobs …
```
> CLI/UX: make `sky cancel cluster` cancel latest running job.

- sky/cli.py
https://github.com/skypilot-org/skypilot/issues/2424
- Added a check for bash version using [[ ${BASH_VERSINFO[0]} -ge 4 ]] to check major version >= 4
- Used && to only run install_cmd if both conditions are met:
- "SkyPilot" not found
- Bash version >= 4
> check if bash version is greater than 4

- sky/cli.py
- sky/clouds/aws.py
- sky/clouds/service_catalog/__init__.py
- sky/clouds/service_catalog/aws_catalog.py
- sky/clouds/service_catalog/config.py
- sky/resources.py
Fixes #2414
This PR fixes the following:
1. The read-only operators (`sky show-gpus`/`sky status`) should not require the actual az mapping.
2. The `sky check` should disable AWS if the permission is not enough for fetching the availability zone mappings
Future TODO: #2416 
1. setup an aws account with no permission granted, and have an AWS cluster in the cluster table.
2. `sky status`
3. `sky check`
> [AWS] Fix check/status failure when no permission is granted for the account

- sky/templates/aws-ray.yml.j2
> [AWS] unset AWS env vars to avoid autoscaler using the incorrect credentials

- sky/clouds/azure.py
- sky/skylet/providers/command_runner.py
- sky/templates/azure-ray.yml.j2
- sky/templates/gcp-ray.yml.j2
This PR shut down all jupyter services that were default enabled by our deep learning image in GCP and Azure.
> Shutdown jupyter services to avoid port conflict

- sky/provision/aws/instance.py
This PR makes security group cleanup in AWS gracefully, and with retry. Now it will retry with a backoff and won't raise an error to interrupt `sky down` when cleanup is failed.
- Manually launch an AWS cluster, comment out `instance.wait_until_terminated()` and `sky down` that cluster
> [Provisioner] Gracefully handle security group cleanup and retry in AWS

- sky/cli.py
- sky/serve/examples/gorilla/run_gorilla.py
- sky/serve/examples/misc/cancel/send_cancel_request.py
- sky/serve/examples/misc/cancel/server.py
- sky/serve/examples/vllm.yaml
- sky/serve/infra_providers.py
- tests/test_smoke.py
Currently, the termination of the launch process will kill the whole process group, including the controller process. Thanks for the `SIGINT` signal we used, the controller will keep processing any incoming requests and it won't cause a problem since it is only called in `terminate` method. This PR fixes this bug. (And also some code formatting)
> [SkyServe] Fix interrupt process group and format

- examples/env_check.yaml
- examples/job_queue/cluster.yaml
- examples/job_queue/job.yaml
- examples/multi_echo.py
- sky/cli.py
- tests/test_smoke.py
Thanks to @romilbhardwaj who discovered this bug introduced by #2423. When `-y` is passed, job IDs passed in were ignored.
```
+ sky cancel -y t-job-queue-multc40-2040-1b 4
Cancelling latest running job on cluster 't-job-queue-multc40-2040-1b'...
I 08-24 10:10:36 cloud_vm_ray_backend.py:3469] Cancelled job ID(s): 3
```
Running entire smoke tests now.
> Hot fix `sky cancel -y` bug that ignored job ids.

- sky/backends/cloud_vm_ray_backend.py
#2403 broke Kubernetes support, since some parts of the code was still using `handle.cluster_name`. This PR fixes it.
Tested:
> [K8s] Use `cluster_name_on_cloud` for k8s

- sky/provision/gcp/instance_utils.py
This PR fixes a bug that will raise an error when the firewall rule corresponds to user-specified ports that cannot be found on the cloud.
- `sky down` a cluster that with ports specified and created before #2403
> Fix GCP port cleanup when the firewall rule is not found

- llm/llama-2/chatbot-hf.yaml
`chatbot-hf.yaml` has a duplicated `memory` argument. This PR removes it.
> [Examples] Remove extra `memory` arg from Llama2 example

- sky/check.py
- sky/clouds/service_catalog/aws_catalog.py
- sky/clouds/service_catalog/data_fetchers/fetch_aws.py
- sky/exceptions.py
Fixes #2451 
Current logging for `sky check`:
```console
$ sky check                                                                                                                                                                                          
AWS: [WARNING] Missing availability zone mappings for the following enabled regions:
Regions                                                       Reason                                                                            
['us-east-1', 'ca-central-1', 'ap-southeast-2', 'ap-          Failed to retrieve availability zones. Please ensure that the                     
northeast-2', 'ap-northeast-1', 'ap-south-1', 'eu-north-1',   `ec2:DescribeAvailabilityZones` action is enabled for …
```
> [AWS] Fix fetching AZ when describe zones permission does not exist in all regions

- sky/backends/backend_utils.py
- sky/backends/cloud_vm_ray_backend.py
> [Core] Fix status refresh for INIT cluster

- sky/clouds/aws.py
- sky/clouds/azure.py
- sky/clouds/cloud.py
- sky/clouds/gcp.py
- sky/clouds/ibm.py
- sky/clouds/kubernetes.py
- sky/clouds/lambda_cloud.py
- sky/clouds/local.py
- sky/clouds/oci.py
- sky/clouds/scp.py
- sky/optimizer.py
Minor UX change for a common error. 
Hopefully make the error hint more noticeable.
Before
This PR
> UX: hint fuzzy candidates on 'catalog doesn't have offerings' error.

- .github/workflows/pypi-nightly-build.yml
- sky/backends/wheel_utils.py
- sky/utils/log_utils.py
Our nightly built is broken for launching cluster, because the built wheel has the name `skypilot_nightly-*.whl` while in our code we rely on the package name to be `skypilot`. This PR fixes the issue.
> [Core] Fix wheel build for nightly

- sky/serve/infra_providers.py
Encountered this bug for arena service where occasionally model may not respond in 3s. and the error count accumulates and eventually deemed the service failed.
> Fix serve probe

- sky/setup_files/setup.py
This PR removes the upper bound on `pyyaml`, thus allowing installation of PyYAML 6 and resolving the issues outlined in #2285. This is a blocking issue in order to use the GCP DeepLearning VM images (e.g. `projects/deeplearning-platform-release/global/images/pytorch-1-13-cpu-v20230807-debian-11-py310`), which come with PyYAML 6 already installed.
I manually patched my environment and was able to spin up a GCP VM and successfully run functions using runhouse.
I apologize but I don't have the required cloud accounts need to run the smoke-tests described below.
> Remove version upper bound on `pyyaml`

- llm/localgpt/localgpt.yaml
LocalGPT example was broken - fixed by updating to use the latest commit. We no longer need to maintain our own fork after https://github.com/PromtEngineer/localGPT/pull/204 was merged. 
Also required resource change to L4 from T4 since the newer version requires more VRAM (see https://github.com/PromtEngineer/localGPT/issues/434).
> [Examples] Update localgpt example

- sky/backends/backend_utils.py
- sky/backends/cloud_vm_ray_backend.py
- sky/backends/provision_utils.py
- sky/clouds/aws.py
- sky/provision/common.py
- sky/provision/docker_utils.py
- sky/provision/instance_setup.py
- sky/resources.py
- sky/skylet/providers/aws/node_provider.py
- sky/skylet/providers/azure/node_provider.py
- sky/skylet/providers/command_runner.py
- sky/skylet/providers/gcp/node_provider.py
- sky/task.py
- sky/templates/aws-ray.yml.j2
> [Provisioner] Add docker support back

- .github/workflows/test-poetry-build.yml
This fixes an issue triggered by #2537, where `$github.event.pull_request.head.repo.html_url` does not exist for the master branch.
> [CI] Fix poetry test for master branch

- sky/backends/cloud_vm_ray_backend.py
This PR fixes an issue raised by TPU Pod user. Sometimes GCP may reboot user's TPU pod resources without any notice and the IPs of Pod node may change. This PR disables using cache IPs for TPU Pod
> Fix IP fetching issue for TPU Pod

- sky/clouds/kubernetes.py
Solves https://github.com/skypilot-org/skypilot/issues/2397. The user identity is currently a md5 hash of `{cluster}_{user}_{namespace}`. Open to other suggestions.
> Implement get_current_user_identity for Kubernetes cloud

- sky/utils/kubernetes/gpu_labeler.py
- tests/kubernetes/README.md
Previously `python -m sky.utils.kubernetes.gpu_labeler` would also try to run jobs on nodes without GPUs, which would require a manual clean up with `python -m sky.utils.kubernetes.gpu_labeler --cleanup` since those jobs would never complete.
This PR filters and runs gpu labelling jobs only on nodes with GPUs.
> [k8s] Run GPU labelling job only on nodes with gpus

- sky/skylet/providers/command_runner.py
This PR fixes two problems:
* fix mount mode for docker;
* fix the problem that re-launch an existing cluster with docker will run setup commands twice (thus introduce some random error, also redundant information in `~/.bashrc`.
- Launch following yaml and manually check;
```yaml
resources:
cloud: gcp
image_id: docker:ubuntu:latest
file_mounts:
/data:
name: <bucket-name>
mode: MOUNT
store: gcs
```
- `sky launch --image-id docker:ubuntu -c doc` and `sky launch --image-id docker:ubuntu -c doc` and manually check;
> [Provisioner] Fix docker gcs mount and re-launch

- sky/cli.py
Resolved #2439 .
To discuss: Do we want to enable this feature for multiple clusters? If so, what delimiter shall we use? space or newline?
> [CLI] Support `--ip` option in `sky status` to output cluster IP only

- sky/cli.py
- sky/skylet/constants.py
- sky/task.py
```bash
sky launch \            
--env SKYPILOT_DOCKER_PASSWORD=$(aws ecr get-login-password --region us-east-1) \
--env SKYPILOT_DOCKER_USERNAME=AWS \
--env SKYPILOT_DOCKER_SERVER=679991763071.dkr.ecr.us-east-1.amazonaws.com \
--image-id docker:txia-test-ecr:latest --cloud gcp
```
> [Provisioner] Fix bug when using docker login config and launching without yaml

- sky/skylet/providers/command_runner.py
- sky/task.py
> [Provisioner] Accept both w/ server prefix and w/o server prefix for private docker registry

- docs/source/examples/docker-containers.rst
- docs/source/running-jobs/environment-variables.rst
This PR updates the docker container doc by:
* give a concrete example of SKYPILOT_DOCKER_SERVER;
* suggest passing secrets
> [Docs] Update docker container doc

- docs/source/reference/faq.rst
- sky/clouds/service_catalog/data_fetchers/fetch_azure.py
Add same flag `--single-threaded` for the Azure fetching script. 
`--single-threaded`: Run in single-threaded mode. This is useful when multiple processes don't work well with the azure client due to ssl issues.
> feat: 🎸 add --single-threaded flag to fetch azure

- sky/__init__.py
```
```
```
sky launch -c dbg --cloud aws --num-nodes 16 --cpus 2+ --down  # with or without timeout bump
sky down dbg  
```
```
sky down dbg
```
```
sky launch -c dbg --cloud gcp --num-nodes 16 --cpus 2+ --down  # with or without timeout bump
sky down dbg  
```
> Release 0.4.0

- sky/clouds/service_catalog/common.py
Closes #2582.
- Manual tests - run `sky show-gpus`
> [show-gpus] Change pandas groupby function to str instead of callable

- sky/provision/gcp/instance_utils.py
> [GCP] Allow stopping VM with local SSD

- sky/clouds/service_catalog/data_fetchers/fetch_gcp.py
✅ Closes: #2555
Add `--zones` and `--exclude` flag to fetch_gcp.
`--zones`: Fetch the list of specified zones.
`--exclude`: Exclude the list of specified regions.
> feat: 🎸 Add --zones and --exclude flag to fetch_gcp

- sky/clouds/kubernetes.py
We currently do not support opening ports on Kubernetes clusters. However, it is still picked by the optimizer as a candidate cloud because `CloudImplementationFeatures.OPEN_PORTS` is not excluded in Kubernetes. This PR fixes that.
> [k8s] Add `OPEN_PORTS` to unsupported features for kubernetes

- examples/tpu/tpu_node_mnist.yaml
- sky/cli.py
- sky/resources.py
- sky/utils/cli_utils/status_utils.py
The original version for tensorflow runtime `2.5.0` is no longer supported by TPU node. We now upgrade it `2.12.0`
> [TPU] Update default runtime version for TPU node

- sky/clouds/gcp.py
`cachetools > 5.0` will have different APIs. Dumping the Cache will cause backward compatibility issues.
To reproduce:
1. `pip install "cachetools<5.0"; sky launch -c test --cloud gcp --cpus 2` 
2. `pip install "cachetools>=5.0"; sky launch -c test`
> [GCP] Avoid dumping cachetools for backward compatibilty

- docs/source/reference/tpu.rst
- docs/source/reference/yaml-spec.rst
> [GCP] Update tpu runtime version for doc

- sky/clouds/service_catalog/data_fetchers/fetch_aws.py
The g2.8xlarge has been removed from the list of offerings on eu-west-1, which causes the [recent failure ](https://github.com/skypilot-org/skypilot-catalog/actions/runs/6318325483/job/17157750092)of catalog fetcher. We now avoid the spot pricing table introducing `nan` rows.
> [Catalog] Fix aws catalog fetcher for removed offerings

- llm/vllm/README.md
This is a minor update to use `sky status --ip` to simplify the fetching of IP.
> [LLM] Use `--ip` CLI to get cluster IPs

- README.md
> News: Mistral 7B

- sky/setup_files/setup.py
The `reason` attribute in `googleapiclient.errors.HttpError` is widely used in our system's error handling, for instance, [authentication](https://github.com/skypilot-org/skypilot/blob/bc4acc88159f3b7aa2d52b499bbf3e6e87ef6663/sky/authentication.py#L163) and [firewall rule creation](https://github.com/skypilot-org/skypilot/blob/bc4acc88159f3b7aa2d52b499bbf3e6e87ef6663/sky/provision/gcp/instance_utils.py#L272). However, this attribute is introduced in version `2.19.1` of `google-api-python-client` ([Reference](https://github.com/googleapis/google-api-python-client/releases/tag/v2.19.1)). We should add a dependency constraint for this attribute.
- `pip install ".[all]"` and no dependency conflict found
> [Core] Fix version requirements for `google-api-python-client`

- README.md
> News: tweak width.

- examples/serve/ray_serve/ray_serve.yaml
- examples/serve/ray_serve/serve.py
Adds an example for running a simple Ray Serve application via SkyServe.
```
> sky serve up examples/serve/ray_serve/ray_serve.yaml
> curl -L 34.41.136.95:30007
{"result": "Hello Ray Serve!"}
```
> [SkyServe] Add Ray Serve example

- sky/cli.py
- sky/execution.py
- sky/optimizer.py
- sky/utils/dag_utils.py
Fixes https://github.com/skypilot-org/skypilot/issues/2591. This is an alternative that hopefully is clearer.
> UX: Fix spot launch hint.

- sky/setup_files/setup.py
This is an issue introduced by #2625, as the `typing_extensions` is not installed by default after removing ray dependency. The issue did not occur during the previous testing, because the docker image `berkeleyskypilot/skypilot-debug` has `typing_extensions` installed in the base environment.
> [Dependency] install typin_extensions for all versions

- sky/benchmark/benchmark_utils.py
- sky/cli.py
- sky/skylet/job_lib.py
- sky/skylet/log_lib.py
Previously, our `common_utils.encode_payload` used `json.dumps` to handle a dictionary with integer and `None` type as key, which will not be restored as the original type in default `json.loads` implementation; also, our click treat `job_id` as string, causing a lot of problems. This PR fixes these problems.
```bash
$ sky logs --status g 1
Getting job status...
{'1': None, 1: 'SUCCEEDED'}
<sky-payload>{"1": null, "1": "SUCCEEDED"}</sky-payload>
{'1': <JobStatus.SUCCEEDED: 'SUCCEEDED'>}
Job 1: SUCCEEDED
```
- `sky logs --status cluster-with-no-job-submitted`
- `sky logs --status cluster-with-job`
```python
>>> import sky
>>> sky.core.job_status('cluster-with-no-job-submitted', None)
Getting job status...
{None: None}
>>> …
```
> [Core] Fix type of `job_id` when querying job status

- sky/utils/kubernetes_utils.py
This PR adds:
-  `CoreWeaveLabelFormatter` to identify GPU nodes within our K8s cluster. 
- Code is formatted using `format.sh`.
> feat(update): Adding CoreWeave label to identify GPUs in K8s

- sky/optimizer.py
- sky/resources.py
- sky/task.py
Previously optimizer will fail when one of the multiple resources provided for the task is invalid. We now change it to allowing the optimization to continue as long as one of the resources is valid.
**The following issue was also the cause of the failure for `pytest tests/test_optimizer_random_dag.py::test_optimizer`.**
To reproduce:
```python
import sky
with sky.Dag() as d:
task = sky.Task(name='task')
task.set_resources({
sky.Resources(sky.SCP(), instance_type='g1v32v4', accelerators='V100-32GB:4'), 
sky.Resources(sky.SCP(), instance_type='g1v16v2', accelerators='V100-32GB:2'),
sky.Resources(sky.GCP(), instance_type='g2-standard-16', accelerators='L4:1'),
sky.Resources(sky.Lambda(), instance_type='gpu_8x_a100_80gb_sxm4', accelerators='A100-80GB:8'),
})
task.set_time_estimator(lambda _: …
```
> [Core] Fix optimizer for dag when some resources provided are not feasible

- sky/clouds/service_catalog/data_fetchers/fetch_gcp.py
We skip the catalog fetching for TPU v5 for now as we currently don't support it yet.
> skip v5 catalog fetching

- sky/cli.py
Previous PR #2541 disabled the glob job ids that previously supported when `--sync-down` is specified. This PR add the function back.
> [CLI] Restore `sky logs <cluster> * --sync-down`

- sky/clouds/cloud.py
- sky/clouds/cloud_registry.py
- sky/clouds/kubernetes.py
- sky/clouds/local.py
- sky/clouds/service_catalog/common.py
- sky/resources.py
- tests/common.py
- tests/conftest.py
- tests/test_optimizer_dryruns.py
Fixes #1882. Also, unregisters `Local` cloud, which is done to provide good 1-cloud hints.
Tested (added to unit tests too) with all clouds enabled incl. k8s:
OK cases:
```
» sky launch --region us-east1
» sky launch --zone us-west2-a
» sky launch --region us-east-2
» sky launch --zone us-west-2a
» sky launch
» sky launch --region us-east-1 --cloud aws
» sky launch --region us-east-1 --cloud lambda
```
Not OK cases:
```
» sky launch --region us-east-1
ValueError: Cannot infer cloud from (region 'us-east-1', zone None). Multiple enabled clouds have region/zone of the same names: [AWS, Lambda]. To fix: explicitly specify `cloud`.
» sky launch --zone us-west-2-a --cloud aws
ValueError: Invalid zone 'us-west-2-a'
Did you mean one of these: 'us-west-2a'?
» sky launch --zone us-west-2-a …
```
> UX: Allow inferring cloud from region or zone.

- sky/backends/cloud_vm_ray_backend.py
- sky/provision/logging.py
Current master will create a log dir `~/sky_logging/{timestamp}` under the dir you run `sky` commands:
This is because of one absent of `os.path.expanduser` introduced by the new provisioner. This PR fixed the bug.
- `sky launch --cloud aws` and check there is no extra dirs created
> Fix creation of `~/sky_logging/{timestamp}` under dir running `sky` commands

- sky/backends/cloud_vm_ray_backend.py
- sky/clouds/gcp.py
GCP generats some flaky error while launching causing #2666. We should add retry for the `ray up` during launching as well as the blocklist update for errors.
> [GCP] Add retry for transient error during launching GCP clusters

- sky/usage/usage_lib.py
> Fix usage by checking detailed_reason

- sky/cli.py
- sky/clouds/service_catalog/__init__.py
- sky/clouds/service_catalog/kubernetes_catalog.py
- sky/utils/kubernetes_utils.py
Implements `list_accelerators` function for Kubernetes catalog. The function is dynamic and iterates through all nodes (checking for GPUs) currently, but the output can also be cached similar to other catalogs. Right now, it only works with `sky show-gpus --cloud kubernetes` since `_ALL_CLOUDS` in service_catalog doesn't include `kubernetes` due to the lack of implementation of other catalog functions.
Example output:
```bash
sky show-gpus --cloud kubernetes          
COMMON_GPU  AVAILABLE_QUANTITIES  
T4          1                     
V100        1                     
Hint: use -a/--all to see all accelerators (including non-common ones) and pricing.
```
```bash
sky show-gpus --cloud kubernetes -a
COMMON_GPU  AVAILABLE_QUANTITIES  
T4          1                     
V100        1 …
```
> Add sky show-gpus support for Kubernetes

- sky/cli.py
- sky/setup_files/setup.py
- sky/utils/rich_utils.py
Fixes #2665
Previously, when `NoOp` is returned, `with rich_utils.safe_status() as status:`, the `status` is actually the return value of `__enter__` (None for the `NoOp`), causing failure if `status` is used later.
> [Core] Fix the NoOp for rich status

- docs/source/reference/faq.rst
- sky/clouds/service_catalog/common.py
More detailed FAQ documentation is available. It also throws out more detailed information when encountering relevant errors to better guide the user in troubleshooting.
Related Issue/PR: #2562 #2547 #2548 #2549 #2555
> refactor: 💡 update faq and add more detailed error message

- docs/source/reference/kubernetes/index.rst
- sky/templates/kubernetes-port-forward-proxy-command.sh.j2
- sky/utils/kubernetes_utils.py
Closes #2626. Adds preemptive check for netcat before trying provisioning.
> [k8s] Add netcat to dependency checks

- docs/source/reference/kubernetes/kubernetes-setup.rst
L4 uses a different driver installation YAML (see [gke docs](https://cloud.google.com/kubernetes-engine/docs/how-to/gpus#cos)). Updated our docs for users who may be running L4 GPUs.
> [Docs][k8s] Update GKE driver installation for L4 nodes

- sky/skylet/attempt_skylet.py
- sky/skylet/constants.py
- sky/skylet/events.py
Previously, the regex used is incorrect, causing failures to autostop an AWS cluster that just got updated to use the new provisioner.
**Before**
```
git checkout b1d8c9d8
sky launch -c dbg --cloud aws --cpus 4+
git checkout bf336028  # master
sky launch -c dbg --cloud aws --cpus 4+ -i0
```
Observe failure to autostop in the VM's skylet.log:
```
..
KeyError: 'head_setup_commands'
E 10-18 05:07:42 events.py:51] AutostopEvent error: Command '['ray', 'down', '-y', '/home/ubuntu/.sky/sky_ray.yml']' returned non-zero exit status 1.
E 10-18 05:07:42 events.py:53] Traceback (most recent call last):
E 10-18 05:07:42 events.py:53]   File "/opt/conda/lib/python3.10/site-packages/sky/skylet/events.py", line 48, in run
E 10-18 05:07:42 events.py:53]     self._run()
E 10-18 05:07:42 events.py:53] …
```
> Core: Fix AWS/GCP autostop with new provisioner.

- sky/utils/accelerator_registry.py
Adds L4 to accelerator registry. This allows us to bypass unnecessary calls to `service_catalog.list_accelerators` every time `resource.copy()` is called.
> [Core] Add L4 to accelerator_registry

- sky/cli.py
If `--ip` is used with `--refresh`, there will be an additional new line in the output (which is caused by the rich progress bar. It will make commands like `curl $(sky status --ip <cluster> -r)` to report illegal format (`curl: (3) URL using bad/illegal format or missing URL`). To reproduce:
```bash
$ echo "a$(sky status cluster-0 --ip)b"
a33.127.121.7b
$ echo "a$(sky status cluster-0 -r --ip)b"
a
33.127.121.7b
$ ip=$(sky status --ip cluster-0 -r); echo "a$ip b"; curl $ip
a
33.127.121.7 b
curl: (3) URL using bad/illegal format or missing URL
```
This PR disabled such option.
> [CLI] Disable `--ip` with `--refresh` when calling `sky status` to avoid additional empty lines in output

- sky/__init__.py
- sky/backends/wheel_utils.py
- sky/cli.py
- sky/setup_files/setup.py
- sky/skylet/events.py
- sky/usage/usage_lib.py
Make it possible to get commit hash of the current SkyPilot for both installed from pypi and source code.
> [UX] Add commit hash

- sky/provision/aws/instance.py
There will be some output that interrupts the progress bar when clean-up SG fails:
```bash
» sky down sky-serve-controller-8a3968f2-0
Tearing down sky serve controller: sky-serve-controller-8a3968f2-0.
To proceed, please check the information above and type 'delete': delete
Terminating 1 cluster ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% -:--:--I 10-19 21:52:21 instance.py:697] Security group sky-sg-sky-serve-controller-8a3968f2-0-8a39 is still in use. Retry.
Terminating cluster sky-serve-controller-8a3968f2-0...done.
Terminating 1 cluster ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
```
This PR makes the log silent by changing it to debug. See https://github.com/skypilot-org/skypilot/pull/2458#pullrequestreview-1689120059 for more information.
> [UX] Make retry clean up security group silent

- sky/provision/aws/config.py
This PR removes some stale code in the current new provisioner implementation.
- `sky launch --cloud aws --cpus 4 --ports 23783 'python -m http.server 23783'` and curl the endpoint
> [Provisioner] remove stale port code in new provisioner

- sky/backends/wheel_utils.py
To reproduce:
```bash
python -c 'from sky.backends import wheel_utils; wheel_utils.build_sky_wheel()'
```
This will replace the `_SKYPILOT_COMMIT_SHA` in `sky/__init__.py` with the current commit. This PR fixed the problem.
> [BugFix] Fix modification of `sky/__init__.py` when building sky wheels

- sky/setup_files/setup.py
This fixes an issue introduced by #2720: a permission error can be raised when there is no permission to write the `__init__` file during `sky launch`
```
PermissionError: [Errno 13] Permission denied: '/var/folders/cc/xxxxxx/T/tmp40gtc6r1/sky/__init__.py'
```
> [Setup] Make setup more robust when there is no permission to get/write commit hash

- sky/backends/cloud_vm_ray_backend.py
- sky/provision/instance_setup.py
- sky/provision/metadata_utils.py
- sky/provision/provisioner.py
- sky/skylet/skylet.py
Fixes #2714
We should not cache the internal file mounts based on the wheel hash, as the cloud credential can be changed, and the cache will cause the credentials on the remote VM failed to udpate. 
On master
```
sky launch -c test-cloud-account --cpus 2
time sky launch -c test-cloud-account --cpus 2
28s
```
On the current PR
```
sky launch -c test-cloud-account --cpus 2
time sky launch -c test-cloud-account --cpus 2
28s
```
That said, this change will not affect the performance.
This PR fixes the following reproduction:
1. `sky spot launch --cloud aws echo hi` with only AWS credentials setup
2. `sky spot launch --cloud gcp echo hi` with GCP credential setup already
> [Provisioner] Fix cache for internal file mounts

- sky/__init__.py
- sky/backends/cloud_vm_ray_backend.py
- sky/provision/instance_setup.py
- sky/provision/metadata_utils.py
- sky/provision/provisioner.py
- sky/skylet/skylet.py
```
```
```
sky launch -c dbg --cloud aws --num-nodes 16 --cpus 2+ --down echo hi  # without timeout bump
sky down dbg  
```
```
sky launch -c dbg --cloud aws --num-nodes 16 --gpus T4 --down --use-spot echo hi
sky down dbg
```
```
sky launch -c dbg --cloud gcp --num-nodes 8 --cpus 2+ --down  echo hi# with or without timeout bump
sky down dbg  
```
```
sky spot launch -n test-oom --cloud aws --cpus 2 sleep 86400
```
> Release 0.4.1

- sky/utils/schemas.py
- tests/test_config.py
A user reported that the `sky launch` fails when the following `config.yaml` is provided:
```
aws:
instance_tags:
mytag: myvalue
eu-west-1: null
us-east-1: null
vpc_name: abc
```
This is due to our recent schema check for `config.yaml` in #2645
> [Config] Fix ssh proxy command to be null

- docs/source/examples/spot-jobs.rst
This has come up quite a few times so adding a hint.
> Docs: add a hint to customizing spot controller.

- sky/backends/backend_utils.py
- sky/data/storage.py
- sky/utils/command_runner.py
A user reported the following error:
Repro
```
mkdir 'test dir with space'
cd 'test dir with space'
git init  # creates a .git/info/exclude
cd ..
sky launch --use-spot --cpus 2+ -i30 --down --workdir='test dir with space' -- ls -lthr
```
Before this PR, errors are thrown due to `--exclude-from=<path with spaces>`
```
...
I 11-07 09:46:32 log_utils.py:45] Head node is up.
I 11-07 09:47:09 cloud_vm_ray_backend.py:1692] Successfully provisioned or found existing VM.
rsync: failed to open exclude file /Users/zongheng/Dropbox/workspace/riselab/sky-computing/test: No such file or directory (2)
rsync error: error in file IO (code 11) at /AppleInternal/Library/BuildRoots/a0876c02-1788-11ed-b9c4-96898e02b808/Library/Caches/com.apple.xbs/Sources/rsync/rsync/exclude.c(1005) [client=2.6.9]
I 11-07 …
```
> Core: Fix syncing workdir with spaces in .git/info/exclude path.

- .github/workflows/pytest.yml
- sky/backends/backend.py
- sky/backends/cloud_vm_ray_backend.py
- sky/backends/local_docker_backend.py
- sky/cli.py
- sky/execution.py
- tests/test_api.py
- tests/test_smoke.py
This PR added return value for `sky/execution.py::_execute`.
> [Core] Return `job_id` and `handle` for `sky/execution.py::_execute`

- docs/source/cloud-setup/cloud-permissions/gcp.rst
- docs/source/reference/config.rst
- sky/backends/backend_utils.py
- sky/backends/cloud_vm_ray_backend.py
- sky/skylet/providers/gcp/config.py
- sky/skylet/providers/gcp/constants.py
- sky/templates/aws-ray.yml.j2
- sky/templates/gcp-ray.yml.j2
- sky/utils/schemas.py
- tests/test_config.py
Support specifying a specific VPC to use for GCP.
In `~/.sky/config.yaml`:
```yaml
gcp:
#
vpc_name: skypilot-vpc
```
TODO
- incorrect; reworded
- With 'default' vpc, that only has 1 subnet (us-central1):
- `sky launch --cloud gcp --cpus 2+ -c dbg2 --region us-west4` correctly fails + skips the entire region.
- With a 'nonexistent' vpc
- `sky launch --cpus 2+ -c dbg --use-spot` correctly skips GCP and fails over to AWS
- `sky launch --cloud gcp --cpus 2+ -c dbg --use-spot` correctly errors out with no failover
- `sky tpunode` correctly errors out with no failover
- Existing GCP spot controller under 'default' vpc (has 1 region, us-central1)
- set config.yaml to use 'skypilot-vpc' vpc (has all regions), launch a new spot job in GCP us-west4, check that new …
> GCP: Support for custom VPC.

- sky/data/storage.py
- tests/kubernetes/eks_test_cluster.yaml
- tests/test_smoke.py
* Addresses #2773. Adds `-y` introduced by #2726
* Cleans up (removes commas) an error str when storage is externally deleted
* Removes invalid test `def test_kubernetes_storage_mounts_with_stop` since k8s does not support autostopping.
* Removes redundant `test_xxx_storage_mounts`. Superseded by `test_xxx_storage_mounts_with_stop`
Tested:
> [Storage] Storage tests cleanup and fixes

- docs/source/cloud-setup/cloud-permissions/aws.rst
- docs/source/cloud-setup/cloud-permissions/gcp.rst
- docs/source/reference/config.rst
> Docs: add GCP bring-your-own-VPC docs.

- llm/vllm/serve-openai-api.yaml
Partially address #2692. Better fix is to update GCP default images to support CUDA 12.1?
- `HF_TOKEN=xxx sky launch serve-openai-api.yaml -c vllm-dbg2 --env HF_TOKEN -i30 --down`
> Example: Update vLLM example to use PyTorch <2.1 (CUDA 11.8)

- llm/axolotl/axolotl-spot.yaml
- llm/axolotl/axolotl.yaml
- llm/axolotl/mistral/qlora-checkpoint.yaml
- llm/axolotl/mistral/qlora.yaml
- llm/axolotl/readme.md
Added example for using axolotl
> axolotl example

- docs/source/cloud-setup/cloud-permissions/gcp.rst
- sky/resources.py
- sky/skylet/providers/gcp/node.py
- sky/skylet/providers/gcp/node_provider.py
- sky/templates/gcp-ray.yml.j2
Issue Addressed: [#2488](https://github.com/skypilot-org/skypilot/issues/2488)
As reported in the issue, it's clear that when launching a GCP cluster with a machine image originating from a 150 GB disk, specifying the `--disk-size 200` parameter results in an instance retaining the original 150 GB size.
Based on [GCP's documentation](https://cloud.google.com/compute/docs/disks/resize-persistent-disk) on resizing persistent disks, when we create a custom Linux image, we have to manually increase the size of the boot and non-boot disks. To achieve this, I used the [Compute Engine API](https://cloud.google.com/python/docs/reference/compute/latest/google.cloud.compute_v1.services.disks.DisksClient#properties ) to modify disk sizes within our custom GCP node provider. Comments have been added …
> [GCP] Fix `--disk-size` for Custom Machine Images

- llm/vicuna/README.md
- llm/vicuna/serve-openai-api-endpoint.yaml
This PR adds an OpenAI Compatible Endpoint for Vicuna. It also fixed a version issue in our Vicuna example.
This is required for our SkyServe User Doc; I feel like if we could start from an existing example, it would make the understanding easier.
> [Examples] Fix Vicuna serve example and add OpenAI Example for Vicuna

- README.md
Thanks to @manishiitg, we now have an Axolotl example that's easily launchable with one command.
> Docs: add Axolotl example to news in README.md

- sky/skylet/providers/kubernetes/node_provider.py
When trying provisioning on a Kubernetes cluster on a high latency connection (e.g., different geographic region + VPN), SkyPilot would get stuck on launching. This is because the `uptime` call run by the ray autoscaler to check for cluster liveness uses a very short `ConnectTimeout=5s`. Using a larger SSH timeout fixes the issue. 
This PR introduces a monkey patch to SSHCommandRunner in `kubernetes/node_provider.py`. It uses a larger timeout when running uptime to check cluster liveness. This monkeypatch to `SSHCommandRunner.run`is necessary since the ray autoscaler sets the timeout on a per-call basis (as an arg to `SSHCommandRunner.run`) and the 5s timeout is hardcoded in `updater.py::NodeUpdater.wait_ready()` is hard to modify without duplicating a large chunk of ray autoscaler code. …
> [k8s] Increase ssh timeout when calling `uptime`

- sky/authentication.py
- sky/clouds/service_catalog/data_fetchers/fetch_aws.py
This is to support #2690, adding Trainium in the catalog.
> [Catalog] Add trainium accelerator in aws catalog

- sky/provision/provisioner.py
Fixes #2796
The additional check for the ssh does not affect the provisioning speed significantly.
Tested with `sky launch -c test-launch --cloud aws --cpus 2`
Original: 3m20s, 2m53s
New: 2m39s, 2m36s
> [Provisioner] Additional check to make sure ssh works

- sky/utils/kubernetes/gpu_labeler.py
Closes #2752. Job names need to be unique, so we use a 32 len hash of the node name where the labelling job is running. 
> [k8s] Handle long node names in GPU Labeler

- sky/provision/azure/instance.py
> [Provisioner] Fix open ports on Azure

- sky/cli.py
`sky status` will raise unbounded local var when interrupted and goes into the following code path.
```
if spot_jobs_query_interrupted:
```
> [CLI] Fix undefined var for serve

- sky/skylet/providers/kubernetes/config.py
- tests/test_smoke.py
Closes #2608. 
Our resource detection from pod spec puts a minimum of 1 on CPU resource so that fractional CPU sized clusters can also be launched on k8s clusters. However, this was being incorrectly applied to GPU resources too, causing all clusters to be initialized with 1 GPU resource.
> [k8s] Fix GPU count detection from autoscaler YAML

- sky/execution.py
- sky/serve/core.py
- sky/setup_files/setup.py
- sky/templates/sky-serve-controller.yaml.j2
- sky/templates/spot-controller.yaml.j2
- sky/utils/controller_utils.py
Manually install the dependencies for the cloud sdk’s on Sky Serve controller.
> [SkyServe] New method to install cloud dependencies

- README.md
- llm/llama-2/chatbot-hf.yaml
Fixes the issue #2680 around Llama-2 example with requisite dependencies and a broken link in README.md
Below are a few issues deploying Llama-2 7B/70B models on GCP (with GPU config; A100-80GB:2 and L4:8), and the additional dependencies are based upon recursively fixing the dependency one-by-one (issues in case of Llama-2 70B deployment is given👇).
```
(setup pid=16754) Token will not been saved to git credential helper. Pass `add_to_git_credential=True` if you want to set the git credential as well.
(setup pid=16754) Token is valid (permission: read).
(setup pid=16754) Your token has been saved to /home/gcpuser/.cache/huggingface/token
(setup pid=16754) Login successful
(task, pid=16754) Starting controller...
(task, pid=16754) Starting model worker...
(task, pid=16754) Waiting for …
```
> Docs: Minor updates to Llama-2 example and README.md

- docs/source/examples/auto-failover.rst
- docs/source/examples/docker-containers.rst
- docs/source/reference/faq.rst
- docs/source/reference/job-queue.rst
- sky/optimizer.py
Docs
- added a few sections based on frequently asked questions
Minor change in Resources display
- This can be triggered by running the following
```yaml
resources:
any_of:
- region: eu-central-1
- region: eu-west-1
- region: eu-west-2
- region: eu-west-3
- region: eu-north-1
- region: europe-central2
- region: europe-north1
- region: europe-southwest1
- region: europe-west1
- region: europe-west10
- region: europe-west12
- region: europe-west2
- region: europe-west3
- region: europe-west4
- region: europe-west6
- region: europe-west8
- region: europe-west9
```
```console
» sky launch test-gdpr.yaml --gpus T4
Task from YAML spec: test-gdpr.yaml
I 11-28 20:52:25 optimizer.py:1223] No resource satisfying GCP({'T4': 1}, region=europe-southwest1) on GCP.
I 11-28 20:52:25 optimizer.py:1223] …
```
> Docs: various improvements.

- sky/cli.py
- sky/clouds/cloud.py
- sky/clouds/gcp.py
- sky/clouds/utils/gcp_utils.py
- tests/common.py
- tests/unit_tests/test_gcp.py
The previous implementation of GCP's reserved instance cache has different cache for multiple GCP() cloud objects. This can cause long optimization time if multiple resources are specified with different GCP() objects.
This PR refactors the cache out to a module to avoid querying the reservation list multiple times.
It reduces the time for optimization from 13 seconds to 4 seconds for the following yaml:
```yaml
resources:
any_of:
- region: us-east-1
- region: us-east-2
- region: us-west-1
- region: us-west-2
- region: us-central1
- region: us-east1
- region: us-east4
- region: us-west1
- region: us-west2
- region: us-west3
- region: us-west4
```
`sky launch -c test test.yaml`
> [GCP] Refactor the reserved instances cache

- docs/source/getting-started/quickstart.rst
- docs/source/reference/cli.rst
> Docs: explain cluster states

- sky/utils/kubernetes_utils.py
Quick fix to add support for `H100-80GB` - it also uses `cloud.google.com/gke-accelerator: nvidia-h100-80gb` naming convention.
> [k8s] Kubernetes H100-80GB support

- sky/backends/cloud_vm_ray_backend.py
- sky/utils/common_utils.py
Looks to resolve #2805
Replaces the use of exponential backoff with the static initial value each retry
Tested:
> Remove Exponential Backoff for Retry Until Up

- sky/clouds/service_catalog/data_fetchers/fetch_azure.py
Latest fetcher that produced https://github.com/skypilot-org/skypilot-catalog/pull/50 
> Azure: Update fetcher to handle H100 missing prices.

- sky/backends/cloud_vm_ray_backend.py
Reported by users in https://skypilot-org.slack.com/archives/C03J2KQQZSS/p1702058439433229.
> Backend: add missing None check in _update_blocklist_on_gcp_error.

- sky/backends/backend_utils.py
- sky/cli.py
- sky/utils/common_utils.py
- sky/utils/controller_utils.py
When running, the `sky spot launch hello_sky.yaml` failed due to the username (used as bucket name) containing the invalid characters (.) allowed by the Google Cloud Platform.
The [hello_sky.yaml](https://skypilot.readthedocs.io/en/latest/getting-started/quickstart.html) is the configuration used in the Quickstart tutorial.
```bash
Launching the spot job 'sky-f3d9-saihtaungkham'. Proceed? [Y/n]: Y
I 12-06 16:18:20 controller_utils.py:394] Translating workdir to SkyPilot Storage...
I 12-06 16:18:20 controller_utils.py:419] Workdir '.' will be synced to cloud storage 'skypilot-workdir-sai.htaungkham-75ee1a2f'.
I 12-06 16:18:20 controller_utils.py:492] Uploading sources to cloud storage. See: sky storage ls
E 12-06 16:18:32 storage.py:808] Could not create StoreType.GCS store with name …
```
> Clean the username on mounts directory.

- sky/skylet/providers/gcp/config.py
Previously we were filtering by subnet name (`name`), but rather we should be filtering by vpc name (`network`). We did not hit this bug because our subnets were named the same as the VPC:
```
» gcloud compute networks subnets list --network="skypilot-vpc" 
NAME          REGION                   NETWORK       RANGE          STACK_TYPE  IPV6_ACCESS_TYPE  INTERNAL_IPV6_PREFIX  EXTERNAL_IPV6_PREFIX
skypilot-vpc  us-central1              skypilot-vpc  10.128.0.0/20  IPV4_ONLY
..
```
while a user hit this bug because they are named differently:
```
NAME           REGION    NETWORK   RANGE          STACK_TYPE  IPV6_ACCESS_TYPE  INTERNAL_IPV6_PREFIX  EXTERNAL_IPV6_PREFIX
priv-subnet-1  us-west1  skypilot  10.10.72.0/22  IPV4_ONLY
pub-subnet-1   us-west1  skypilot  10.10.68.0/22  IPV4_ONLY
``` …
> GCP: Fix subnet filtering.

- README.md
- docs/source/index.rst
The mistral team has updated the URL to the docs for deploying mistral models with SkyPilot. This PR fixes the links.
> [Docs] Minor fix for mistral links

- sky/cli.py
- sky/serve/core.py
- sky/serve/replica_managers.py
- sky/serve/serve_state.py
- sky/serve/serve_utils.py
- sky/serve/service.py
This PR changed the representation of the `request_resources` field in service status. Now it will store a string to represent multiple accelerators, just like implementation for SkySpot.
```yaml
service:
readiness_probe: /
replicas: 1
resources:
accelerators: {L4:1, T4:1}
ports: 8000
run: python3 -m http.server 8000
```
- Previous YAML
- Backward compatibility test: launch a service on the old version, switch to this branch and launch a new service. Everything works fine.
> [SkyServe] Fix resource parse when multiple accelerators is used

- sky/cli.py
- sky/clouds/azure.py
- sky/clouds/service_catalog/azure_catalog.py
Removes the artificial restriction that was added due to our subscription not support spot instances. However, users' subscriptions have access so should be allowed.
Tested:
- `sky launch --cloud azure --use-spot --gpus A100-80GB` no longer shows our asserts, but rather proper errors from Azure 
> Azure: allow spot instances.

- docs/source/reference/config.rst
- sky/provision/aws/config.py
- sky/provision/aws/instance.py
- sky/provision/provisioner.py
- sky/utils/controller_utils.py
- tests/backward_compatibility_tests.sh
Removes two issues from before
- Previously, we test if a subnet is private by a hack (check if `private` is a substr in its name tag)
- Previously, SkyPilot does not allow launching VMs in a public subnet with `subnet.map_public_ip_on_launch` set to False. 
- This PR now allows so -- and changes the underlying ec2.create_instances call to assign public IPs
This PR uses a more robust method to test if a subnet is public: 
- Check if its associated route tables have a route to an IGW (`igw-*`)
- If it has no explicitly associated route tables, check if any "main" route table has a route to an IGW (`igw-*`)
-----
Tested:
Speed
- `for i in $(seq 3); do sky launch --cloud aws -i0 --down --use-spot --region us-east-1 -y >log-${i}; done`
- Grepped for provisioner.log "Provisioning ... took"
- …
> AWS: make public / private subnet selection robust.

- sky/execution.py
- sky/serve/core.py
- sky/utils/controller_utils.py
We left out the env var of the path for config yaml in #2819. This is problemetic as the spot job and service replica will fail to respect the settings in user config yaml
```yaml. 
spot:
controller:
resources:
cloud: aws
aws:
vpc_name: skypilot-test-vpc
us-east-1: ssh -W %h:%p -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -i ~/.ssh/sky-key ec2-user@xx.xxx.xxx.xxx
```
```yaml. 
spot:
controller:
resources:
cloud: aws
aws:
vpc_name: skypilot-test-vpc
us-east-1: ssh -W %h:%p -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -i ~/.ssh/sky-key ec2-user@xx.xxx.xxx.xxx
```
> [VPC] Fix config yaml env var for spot/serve controller

- Dockerfile_k8s
Fresh builds of our k8s CPU image would fail during provisioning with:
```
File "<string>", line 1, in <module>
File "/home/sky/.local/lib/python3.10/site-packages/sky/skylet/ray_patches/__init__.py", line 85, in patch
from ray.dashboard.modules.job import job_head
File "/home/sky/.local/lib/python3.10/site-packages/ray/dashboard/modules/job/job_head.py", line 9, in <module>
import aiohttp.web
ModuleNotFoundError: No module named 'aiohttp'
```
This is because ray dashboard dependencies are not correct installed.
This PR changes ray installation in our Dockerfile to also install dashboard dependencies. 
GPU image does not need this change since the base image installs `ray[default]` anyway. 
cc @kbrgl
> [k8s] Install ray dashboard dependencies in CPU k8s image

- docs/source/examples/auto-failover.rst
Users have asked about `any_of`/`ordered` fields not found when they installed the v0.4.1 release. 
Adds a tip on using nightly.
> Minor: update multiple resources docs.

- sky/data/storage.py
- 1.0.1 still in use & works
- upgraded to 1.3.0 & works
> GCP: upgrade GCSFuse to 1.3.0.

- llm/mixtral/README.md
- llm/mixtral/serve.yaml
We should change the tensor parallel value for different number of accelerators.
> [Minor] Fix mixtral eample for other accelerators

- sky/serve/service_spec.py
> [SkyServe] Warn min_replicas = 0

- docs/source/serving/service-yaml-spec.rst
- docs/source/serving/sky-serve.rst
* removing `controller_resources`
* some rewording
> Docs: update SkyServe docs.

- sky/skylet/constants.py
Fixes #2908 
This reverts changes in #2277, due to the update of GCP image has resolved the `conda init` issue in #2273
(Confirmed that the problem exists with the older image we used: `sky launch -c test-old-image --cloud gcp --image-id skypilot:cpu-debian-10 'conda activate'`. Though it takes longer to launch for older image, but it is not critical for user job.)
> [Setup] Not skipping `conda init`

- sky/skylet/constants.py
Revert part of the changes in #2909, as `conda init` requires conda to appear in the path.
```
resources: 
accelerators: tpu-v2-8
accelerator_args:
tpu_vm: True
run: |
echo "Hello World"
```
> [Setup] Fix conda init

- sky/cli.py
This is to enable `sky launch --disk-tier none -c test-mixtral --cloud azure llm/mixtral/serve.yaml`
> Allow --disk-tier to be None to remove the disk_tier setup in yaml

- sky/utils/kubernetes/create_cluster.sh
Fixes #2592. 
This pull request updates create_cluster.sh to enhance the handling of Docker permission errors. The revised script captures the output and error messages from `docker info`. It identifies and distinguishes between 'permission denied' errors and scenarios where Docker is not running, and alerts the user with an error message accordingly. 
> [k8s] Surface docker permission error for `sky local up`

- sky/utils/controller_utils.py
> [Spot] Add Azure dependency installation on SpotController.

- sky/backends/cloud_vm_ray_backend.py
- sky/provision/aws/config.py
> [Core/AWS] Skip association with no subnetId and fix autodown for spot instances

- sky/cli.py
- sky/clouds/service_catalog/__init__.py
- sky/clouds/service_catalog/aws_catalog.py
- sky/clouds/service_catalog/azure_catalog.py
- sky/clouds/service_catalog/common.py
- sky/clouds/service_catalog/gcp_catalog.py
- sky/clouds/service_catalog/ibm_catalog.py
- sky/clouds/service_catalog/kubernetes_catalog.py
- sky/clouds/service_catalog/lambda_catalog.py
- sky/clouds/service_catalog/oci_catalog.py
- sky/clouds/service_catalog/scp_catalog.py
This solves #2863 
show_gpus can now accept a new flag `--all-regions`, which displays all the regions for a given accelerator. It can be used as follows. 
`sky show-gpus <acclerator> --all-regions`
Additionally it can take a cloud argument as well. 
`sky show-gpus <acclerator> --cloud <cloud> --all-regions`
I compared the outputs against the catalog. 
> Added functionality in show_gpus to have an option to show all regions' pricing for an accelerator

- sky/cli.py
- sky/serve/load_balancer.py
I was curling a service with starting/provisioning replicas and got this message. "available replicas" in this case may be more misleading than "ready replicas".
> [SkyServe] Minor hint wording change.

- docs/source/examples/spot-jobs.rst
- sky/spot/spot_utils.py
This PR adds documents for the spot pipeline support based on the requirements from the users in #2928 and item 1 in #2075.
> [Docs] Add spot pipeline docs

- sky/clouds/aws.py
Since we remove the aws dependency from the `pip install skypilot`, we need to check the installation of the AWS dependency in `sky check`.
To reproduce this:
```
pip install .
pip install awscli
sky check
```
Error:
```
...
File "/home/gcpuser/skypilot/sky/clouds/service_catalog/aws_catalog.py", line 197, in validate_region_zone
return common.validate_region_zone_impl('aws', _get_df(), region, zone)
File "/home/gcpuser/skypilot/sky/clouds/service_catalog/aws_catalog.py", line 158, in _get_df
_user_df = _fetch_and_apply_az_mapping(_default_df)
File "/home/gcpuser/skypilot/sky/clouds/service_catalog/aws_catalog.py", line 114, in _fetch_and_apply_az_mapping
user_identity_list = aws.AWS.get_current_user_identity()
File "/home/gcpuser/skypilot/sky/clouds/aws.py", line 626, in …
```
> [Core] Fix aws dependency check

- examples/serve/min_replicas_zero.yaml
- sky/cli.py
- sky/serve/autoscalers.py
- sky/serve/constants.py
- sky/serve/controller.py
- sky/serve/serve_state.py
- sky/serve/service_spec.py
Related issue: https://github.com/skypilot-org/skypilot/issues/2893
Add a new status `NO_REPLICAS`.
Lower autoscaler decision interval when `target_num_replicas = 0`
> [SkyServe] Support `min_replicas = 0`

- docs/source/reference/kubernetes/kubernetes-setup.rst
- tests/kubernetes/gpu_test_pod.yaml
Clarifies that `nvidia` must also be set as the default runtime for the container engine. This is a common gotcha on RKE2, since users may use the [nvidia's default instructions](https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/latest/getting-started.html#install-nvidia-gpu-operator) instead of [their recommendation for RKE2](https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/latest/getting-started.html#custom-configuration-for-runtime-containerd). 
> [k8s][docs] Clarify `nvidia` runtime is required for k8s

- sky/serve/autoscalers.py
- sky/serve/service_spec.py
Currently, the `SkyServiceSpec` will add the fields `{up,down}scale_delay_seconds` even if there are no autoscaling enabled. This PR fixed the issue.
To reproduce:
```python
>>> import sky
>>> sky.serve.SkyServiceSpec.from_yaml_config({'readiness_probe': '/', 'replicas': 1}).to_yaml_config()
{'readiness_probe': {'path': '/', 'initial_delay_seconds': 1200}, 'replica_policy': {'min_replicas': 1, 'upscale_delay_seconds': 300, 'downscale_delay_seconds': 1200}}
```
```python
>>> import sky
>>> sky.serve.SkyServiceSpec.from_yaml_config({'readiness_probe': '/', 'replicas': 1}).to_yaml_config()
{'readiness_probe': {'path': '/', 'initial_delay_seconds': 1200}, 'replica_policy': {'min_replicas': 1}}
```
> [SkyServe] Not add default value of `{up,down}scale_delay_seconds` in service spec

- sky/provision/gcp/config.py
- tests/test_smoke.py
Fixes #2966
Assign the VMs laucnhed on GCP with service account. This is the original behavior which is missed in our new provisioner implementation.
> [GCP/Provisioner] Assign VMs launched on GCP with service account

- sky/backends/cloud_vm_ray_backend.py
- sky/utils/accelerator_registry.py
- tests/test_smoke.py
Fixes #2968. Bug fixed is when we are submitting a job request, do not request `GPU: <count>` resources. 
> [Core] Fix Inferentia job scheduling

- sky/backends/backend_utils.py
This is in relation to https://github.com/skypilot-org/skypilot/issues/1765
**Overview:**
This PR introduces a significant change to the SSHConfigHelper, where the configuration for cluster host details is now stored in a dedicated file within the .sky/generated/ssh folder. The user's primary configuration file now includes an Include statement to reference this folder.
**Backward Compatibility:**
For users adding existing clusters, the previous configuration for those clusters will be removed from the main configuration file, and a new configuration file will be created in the `.sky/generated/ssh folder.` This change ensures that removal of existing clusters performed prior to this update functions as expected.
**Testing:**
Extensive manual testing was conducted, as the existing tests …
> Revamped SSH Configuration Storage

- sky/cli.py
- sky/clouds/service_catalog/gcp_catalog.py
This is in relation to https://github.com/skypilot-org/skypilot/issues/2039. 
Added functionality to show the combined price for GCP GPU instance. 
```
GPU   QTY  CLOUD   INSTANCE_TYPE       DEVICE_MEM  vCPUs  HOST_MEM  HOURLY_PRICE  HOURLY_SPOT_PRICE  REGION
V100  1    AWS     p3.2xlarge          16GB        8      61GB      $ 3.060       $ 0.476            ap-northeast-1
V100  4    AWS     p3.8xlarge          16GB        32     244GB     $ 12.240      $ 1.596            ap-northeast-1
V100  8    AWS     p3.16xlarge         16GB        64     488GB     $ 24.480      $ 2.678            ap-northeast-1
V100  1    Azure   Standard_NC6s_v3    -           6      112GB     $ 3.060       $ 0.450            centralus
V100  2    Azure   Standard_NC12s_v3   -           12     224GB     $ 6.120 …
```
> [UI] Now show-gpus shows the combined price for GCP GPU instance

- docs/source/cloud-setup/cloud-permissions/aws.rst
In order to use the spot controller, the policy must allow service-linked roles. This modification allows for this.
> Update aws.rst to resolve AuthFailure

- docs/source/getting-started/installation.rst
- sky/clouds/runpod.py
- sky/provision/runpod/instance.py
- sky/setup_files/setup.py
1. Update the dependency for runpod
2. Fix the installation instruction for runpod
3. Add runpod installation instruction in docs
> [Docs] Add docs for runpod installation

- sky/clouds/service_catalog/common.py
- sky/provision/gcp/constants.py
This is to make sure the service account `skypilot-v1` automatically created by skypilot can access the user's bucket, to make it more convenient for the users.
> [GCP] Use storage.admin permission for automatically created skypilot-v1 service account

- sky/data/mounting_utils.py
- sky/data/storage.py
- sky/data/storage_utils.py
Until now, the mounting script(heredoc) from `mounting_utils.py` were only used from `storage.py`. But now, our new `CSYNC` design, #2336, requires to run cloud storage mounting command(`gcsfuse`, `goofys`) as well. To reuse scripts from `mounting_utils.py` for `CSYNC`(`sky_csync.py` from #2336), this modularization is necessary. 
`CSYNC` module will be utilizing:
- `storage_utils.get_*_install_cmd()`
- `storage_utils.get_*_mount_cmd()`
- `mounting_utils.get_mounting_script()
`
> [Storage] Mount command construction refactor
