skypilot-org/skypilot

- sky/authentication.py
- sky/backends/cloud_vm_ray_backend.py
This PR fixes https://github.com/skypilot-org/skypilot/issues/1023. Also a waiting operation is added to ensure the operation is complete or raise errors if there's any (refer to [code](https://github.com/ray-project/ray/blob/master/python/ray/autoscaler/_private/gcp/config.py#L717) in Ray's Autoscaler).
TODO:
> Fix bug in ssh key creation on GCP

- sky/authentication.py
> add ssh key generation when os-login is on

- sky/backends/backend_utils.py
- sky/backends/wheel_utils.py
- sky/setup_files/setup.py
- sky/utils/common_utils.py
This PR replaces the version parsing with the tool in `packaging.version`.
> Fix the version parsing with third-party tool

- sky/__init__.py
> Version to 0.1.1-rc.1

- sky/__init__.py
This PR changes the version number to `0.1.1-rc1`
> Change the version to 0.1.1-rc1

- README.md
This PR updates the example in README.md to run mnist training from the [pytorch examples](https://github.com/pytorch/examples). Also adds a gif demo for the example.
> Add demo to README

- sky/execution.py
Fixing message formatting issue + hinting what to do.
(In general, messages should try to hint at a fix/workaround.)
> UX: managed spot error messages.

- docs/source/reference/local/setup.rst
> [Onprem] Modify Sky Admin's Setup on Docs

- sky/backends/onprem_utils.py
- sky/cli.py
Refactors local cloud checking methods from `cli.py` into `backends/onprem_utils.py`
> [Onprem] Refactor Local methods out of CLI

- sky/core.py
> [Spot] Enable purge for spot controller

- sky/spot/spot_state.py
- sky/spot/spot_utils.py
- sky/utils/log_utils.py
> [Spot] Fix spot job duration

- README.md
- docs/source/conf.py
- docs/source/index.rst
- examples/README.md
> README polishes.

- docs/source/index.rst
- docs/source/reference/tpu.rst
- examples/tpu/tpu_node_mnist.yml
- sky/cli.py
- sky/clouds/service_catalog/__init__.py
This PR adds a document for TPU usage.
> Add TPU doc

- sky/backends/backend_utils.py
- sky/backends/cloud_vm_ray_backend.py
- sky/backends/wheel_utils.py
- sky/spot/recovery_strategy.py
- sky/templates/aws-ray.yml.j2
- sky/templates/azure-ray.yml.j2
- sky/templates/gcp-ray.yml.j2
- tests/test_wheels.py
> Install sky only when neccessary and add retry for spot cluster termination

- sky/backends/backend_utils.py
- sky/cloud_stores.py
- sky/clouds/gcp.py
- sky/data/storage.py
- sky/execution.py
- sky/templates/spot-controller.yaml.j2
This is a minor change to align the installation code for our cloud store and spot controller.
> Align gcloud installation for spot and cloud store

- sky/backends/backend_utils.py
- sky/cloud_stores.py
- sky/clouds/gcp.py
- sky/data/storage.py
- sky/execution.py
- sky/templates/spot-controller.yaml.j2
Reverts skypilot-org/skypilot#1155
The previous PR causes a problem with the spot launch due to incorrect indent. Reverting it.
> Revert "Align gcloud installation for spot and cloud store"

- README.md
- docs/source/index.rst
Main change is to promote "unified interface" a bit.
All: please help look over to see if the new messaging is better.
> Polishing README.

- docs/source/examples/syncing-code-artifacts.rst
- docs/source/reference/faq.rst
> Docs: add a hint on --no-setup to refresh file_mounts.

- sky/skylet/job_lib.py
- sky/spot/spot_utils.py
- sky/utils/common_utils.py
> [Spot] More robust message passing for spot jobs against system warnings

- examples/using_file_mounts.yaml
- sky/backends/backend_utils.py
- sky/backends/cloud_vm_ray_backend.py
- sky/utils/command_runner.py
- tests/test_smoke.py
This PR fixes https://github.com/skypilot-org/skypilot/issues/1189.
Test:
> fix rsync for paths with spaces

- sky/backends/backend.py
- sky/cli.py
- sky/core.py
- sky/execution.py
- sky/usage/usage_lib.py
Tested:
- manually called all programmatic APIs in a script and observed expected behaviors
- ensured that the cluster names are the same between CLI and programmatic
> Usage lib: cover all programmatic APIs.

- sky/backends/backend_utils.py
- tests/backward_comaptibility_tests.sh
> [Backward Compatibility] Fix backward compatibility

- docs/source/examples/spot-jobs.rst
- docs/source/reference/benchmark/cli.rst
- docs/source/reference/benchmark/config.rst
- docs/source/reference/interactive-nodes.rst
- examples/spot/bert_qa.yaml
This PR updates the docs for managed spot jobs with auto-translation added in #1081. Also, fixes #1269 
Tested:
- renderred locally.
> [Spot] Update docs for auto-translation

- docs/source/index.rst
This PR adds a badge for joining the slack channel. (I have to use absolute values for the height and vertical-align, so as to match the height of the github-buttons behind).
Original:
New:
> [Docs] Add badge for joining slack

- sky/skylet/job_lib.py
> [Multi-node/TPU-VM] Disable parallel cancel to fix the resource issue

- README.md
- docs/source/index.rst
Changes:
- Tweaks landing paragraphs
- Some changes throughout the body
> Improving README.

- examples/using_file_mounts.yaml
- sky/backends/cloud_vm_ray_backend.py
Closes #1314.
Do not merge until we get alignment on the [potential pros and cons](https://github.com/skypilot-org/skypilot/issues/1314#issuecomment-1294974383) from other project members. 
Tested:
> [Storage][Filemounts] Set relative dir root to workdir

- sky/backends/backend_utils.py
Fixes the issue mentioned in https://github.com/skypilot-org/skypilot/pull/1291#issuecomment-1297819030.
TODO:
> Fix TPU Pod

- sky/backends/backend_utils.py
> [LocalDockerBackend] Update `is_local_cluster` check for docker backend

- sky/spot/controller.py
- sky/spot/spot_utils.py
- sky/templates/aws-ray.yml.j2
- sky/templates/azure-ray.yml.j2
- sky/templates/gcp-ray.yml.j2
- tests/test_smoke.py
> [Spot] Fix spot recovery for multi node

- docs/source/examples/distributed-jobs.rst
- docs/source/examples/spot-jobs.rst
- docs/source/getting-started/tutorial.rst
- examples/huggingface_glue_imdb_app.yaml
- examples/resnet_distributed_torch.yaml
- examples/resnet_distributed_torch_app.py
- examples/resnet_distributed_torch_scripts/setup.sh
- examples/spot/bert_qa.yaml
- sky/__init__.py
- sky/backends/backend_utils.py
- sky/backends/onprem_utils.py
- sky/cli.py
- sky/clouds/aws.py
- sky/clouds/azure.py
- sky/clouds/gcp.py
- sky/optimizer.py
- sky/skylet/providers/azure/node_provider.py
Bump to `0.2.1`.
Cherry-pick the fix for the logging of the first launch and the pin torch version fixes.
Please let me know if any other commits need to be cherry-picked.
Tested:
> Creating 0.2.1 branch to prep for release.

- README.md
- docs/source/index.rst
Rendered locally and clicked on all added links.
> Link to blog on README and docs.

- sky/spot/controller.py
- sky/spot/recovery_strategy.py
- sky/spot/spot_utils.py
- tests/test_smoke.py
Reverts skypilot-org/skypilot#1414
Due to #1431
> Revert "[Spot] Let cancel interrupt the spot job"

- CONTRIBUTING.md
- README.md
These are tiny nits. Feel free to just ignore them and close the PR if you prefer.
> Add a few small warnings to README and CONTRIBUTING.

- sky/cli.py
- sky/core.py
- sky/skylet/configs.py
Changes
- Update formatting so docs HTML look nicer
- some clarifications
- some notes on autostop behavior introduced in #1458
Tested
- rendered `sky <cmd> -h`
- rendered HTML
> [docs] Update exec/status/autostop docs and formatting.

- .github/workflows/mypy-generic.yml
- .github/workflows/mypy.yml
- format.sh
- pyproject.toml
- requirements-dev.txt
- sky/adaptors/azure.py
- sky/data/data_utils.py
- sky/data/storage.py
- sky/global_user_state.py
- tests/mypy_files.txt
Fixes #1510.
This PR also adds the mypy type check for a single file `sky/data/storage.py`. The files to be checked should be added incrementally. 
> [Mypy] Add type check with mypy and fix storage

- sky/resources.py
> Backward compatibility for Image_id in Resources

- sky/cli.py
This is a minor PR that adds the error message to the `sky down` to improve the UX and debugging.
> [UX] Add error message to down

- sky/backends/backend_utils.py
- sky/cli.py
- sky/core.py
- sky/execution.py
- tests/test_spot.py
Fixes #1536. Fixes #1537.
```
sky cancel 1
sky cancel myclus  
sky cancel sky-spot-controller-xx -a                
sky cancel sky-spot-controller-xx 1             
```
> Logging UX for `sky cancel`.

- sky/clouds/aws.py
- sky/clouds/azure.py
- sky/clouds/gcp.py
- tests/test_optimizer_random_dag.py
Closes #1612 
From:
```
I 01-19 23:28:21 optimizer.py:739] -----------------------------------------------------------------------------------
I 01-19 23:28:21 optimizer.py:739]  CLOUD   INSTANCE         vCPUs   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 01-19 23:28:21 optimizer.py:739] -----------------------------------------------------------------------------------
I 01-19 23:28:21 optimizer.py:739]  AWS     m6i.2xlarge      8       -              us-east-1     0.38          ✔     
I 01-19 23:28:21 optimizer.py:739]  Azure   Standard_D8_v4   8       -              eastus        0.38                
I 01-19 23:28:21 optimizer.py:739]  GCP     n1-highmem-8     8       -              us-central1   0.47                
I 01-19 23:28:21 optimizer.py:739] …
```
> Upgrade default CPU instance types

- sky/data/storage.py
- sky/setup_files/setup.py
> [Setup] Remove the dependency for typing_extensions

- sky/backends/backend_utils.py
> Fix ssh config generation for multiple nodes

- README.md
- docs/source/index.rst
Update the links for joining our slack workspace.
> Update url for joining the slack

- sky/backends/cloud_vm_ray_backend.py
This minor refactoring (moving a segment of code into a method) makes it easier and cleaner to integrate #1702. This trivial refactoring does not change any behavior of Skypilot.
> Minor refactoring for new provisioner

- docs/source/getting-started/installation.rst
> [Docs] Change grpcio to conda-forge for apple silicon instructions

- sky/templates/gcp-ray.yml.j2
Fixes https://github.com/skypilot-org/skypilot/issues/1739.
> GCP onHostMaintenance config

- sky/backends/backend_utils.py
To reproduce:
1. `rm -r ~/.sky/spot_controller`
2. `sky spot launch echo hi`
- snippets above
> [Spot] Fix spot for new user

- examples/llama-llm-chatbots/README.md
> Minor typo fix in example.

- docs/source/getting-started/installation.rst
> Update Lambda Cloud docs.

- README.md
- docs/source/index.rst
> Add blog link to docs & README.

- README.md
- examples/vicuna-llm/README.md
> Add Vicuna example folder.

- docs/source/examples/spot-jobs.rst
> Update Managed Spot docs.

- sky/backends/backend_utils.py
This fixes #1849.
Tested:
```
sky launch --cloud lambda
sky status -r
sky status -r # I check both ip addrs are tested before erroring
```
For testing, I was not sure how to block one ip address (1.1.1.1) and not the other (8.8.8.8)
> Use multiple test ips to check network connection

- docs/source/reference/storage.rst
Cleaning up storage docs to make them more concise and easier to read.
> [Docs] Storage docs cleanup

- sky/clouds/service_catalog/data_fetchers/fetch_aws.py
Some users face the following exception when updating the AWS catalog using the `fetch_aws` module:
```
File ".../sky/describe_regions.py", line 6, in <module>
user_cloud_regions = aws_client.describe_regions()
File ".../python3.10/site-packages/botocore/client.py", line 530, in _api_call
return self._make_api_call(operation_name, kwargs)
File ".../lib/python3.10/site-packages/botocore/client.py", line 960, in _make_api_call
raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (UnauthorizedOperation) when calling the DescribeRegions operation: You are not authorized to perform this operation.
```
This occurs when the [relevant permission](https://iam.cloudonaut.io/reference/ec2/DescribeRegions.html) is not …
> Improve error handling for AWS region fetching

- sky/cli.py
To avoid 
```
sky.exceptions.ClusterNotUpError: Spot controller is not up.
```
> usage: Mark `spot queue` called by `status` as internal.

- docs/source/examples/spot-jobs.rst
Updated hyperlinks for Vicuna examples
> Fixed documentation link

- sky/execution.py
`_maybe_translate_local_file_mounts_and_sync_up()` translates local to Sky storage for not only `file_mounts`, but also `workdir` as well.
> Update on log and comment in execution.py

- README.md
- llm/vicuna/README.md
Fixing broken links in our Vicuna examples and README. Added a new banner for the Vicuna README.
> [Docs] Fix Vicuna links

- docs/source/index.rst
> Update index.rst to make it consistent with README.md

- sky/clouds/azure.py
This PR introduces auto disk tier failover in Azure and fixes one problem in #618 .
> Add auto disk tier failover in Azure

- README.md
> Update README.md: mention new clouds

- sky/adaptors/cloudflare.py
> Minor: missing period in message

- README.md
- docs/source/examples/spot-jobs.rst
- docs/source/getting-started/installation.rst
- sky/clouds/oci.py
This PR adds docs for the OCI to make the onboarding of new OCI users easier. cc @HysunHe 
> [OCI] Add instructions for OCI

- docs/source/examples/spot-jobs.rst
Some rewording to hopefully clarify things better.
> Docs: update spot controller docs in spot-jobs.rst

- docs/source/getting-started/installation.rst
- docs/source/index.rst
- docs/source/reference/cloud-administration.rst
- sky/clouds/aws.py
- sky/setup_files/setup.py
Prompted by https://github.com/skypilot-org/skypilot/issues/1883. 
- rendered manually
> Doc: add a "Cloud Administration" page.

- sky/templates/spot-controller.yaml.j2
> [UX/minor] Remove uneccessary spot setup log

- README.md
Minor Doc change: Include OCI to the cloud list.
NA
NA
> [OCI docs] Update README.md

- docs/source/reference/local/index.rst
Fixes duplicate deprecation warnings due to merge conflict.
> [Docs] Onprem docs merge fix

- sky/clouds/service_catalog/oci_catalog.py
> Fix show-gpus when oci not installed

- sky/clouds/azure.py
This PR fix interruption when the specified disk tier is not feasible with other resource requirements, i.e. accelerator.
> [Provisioner] Fix Azure disk tier interruption for optimize progress

- sky/clouds/service_catalog/gcp_catalog.py
Make the catalog update more frequent for GCP. Related to https://github.com/skypilot-org/skypilot-catalog/pull/36#discussion_r1241080560
> [Catalog] More frequent update for GCP catalog

- docs/source/conf.py
> Minor/docs: copyright 2022 -> 2023.

- sky/utils/ux_utils.py
Unintended change leaked in to master from #2135 - this reverts it.
> [UX] Revert traceback change

- docs/source/reference/auto-stop.rst
Changes
- Add autodown
- Some rewordings
> Docs: update autostop page.

- llm/vicuna/serve.yaml
- llm/vicuna/train.yaml
- llm/vllm/README.md
- llm/vllm/serve.yaml
This PR adds an example of launching the vLLM demo.
> [Example] Add vLLM example

- README.md
- llm/vllm/README.md
> [Example] Update vLLM banner

- sky/resources.py
> [Docs] Fix a typo in docs

- sky/skylet/log_lib.py
> [Core] Fix key interruption for sky launch

- llm/localgpt/README.md
- llm/localgpt/localgpt.yaml
Adds [localGPT](https://github.com/PromtEngineer/localGPT) example. Refer to README.md for more.
> [LLMs] LocalGPT example

- docs/source/reference/yaml-spec.rst
The previous comment seemed a bit confusing. Clarifying that the symlink's target will not be copied over. Felt like the distinction between the symlink content and it's target data was not so obvious.
> [Docs] Update symlink related comment in Task Yaml example doc

- docs/source/getting-started/installation.rst
Closes #2189.
Updates docker container from ecr to dockerhub `berkeleyskypilot/skypilot:latest`. This is running v0.3.2.
> [Docs] Update docker image path

- llm/localgpt/README.md
> [Examples] Update LocalGPT Readme

- sky/global_user_state.py
> [Core] Fix status refresh when manually restarted

- docs/source/getting-started/tutorial.rst
- docs/source/reference/auto-stop.rst
Fixes #1503. Added some touches to the Tutorial as well (3rd page we expect users to hit).
> Docs: minor enhancements.

- examples/deepspeed-multinode/sky.yaml
- sky/spot/spot_utils.py
Closes #1984.
To demonstrate how to construct a `/job/hostfile`.
If this becomes a more common request, SkyPilot can auto-write out such a file for each task.
> Example: add a DeepSpeed example

- sky/skylet/ray_patches/__init__.py
- sky/skylet/ray_patches/job_head.py.patch
> Patch ray for python 3.11

- README.md
- docs/source/index.rst
> Polish README.md.

- README.md
- llm/llama-2/README.md
> Fix wording in llama-2 README

- llm/llama-2/README.md
- llm/llama-2/chatbot-hf.yaml
- llm/llama-2/chatbot-meta.yaml
> [Example] Use L4 as an example

- docs/source/reference/yaml-spec.rst
- sky/clouds/gcp.py
- sky/templates/gcp-ray.yml.j2
Fixes #2275 
```
resources:
cloud: gcp
image_id: projects/my-project/global/machineImages/test-machine-image
```
or
```
sky launch -c test-machine-image-gcp --cloud gcp --image-id projects/my-project/global/machineImages/test-machine-image
```
> [GCP] Support machine image

- sky/clouds/cloud.py
- sky/clouds/ibm.py
- sky/clouds/lambda_cloud.py
- sky/clouds/scp.py
- sky/resources.py
Looks like a typo crept in with #2245 - quick PR to fix it.
> Fix `CUSTOM_DISK_TIER` typo

- sky/cli.py
Previous hint may leave users wondering "if it's not supported, how will it be stopped".
> Minor: change hint for 'sky stop <spot controller>'.

- sky/clouds/gcp.py
- sky/clouds/service_catalog/common.py
- sky/clouds/service_catalog/gcp_catalog.py
- tests/test_smoke.py
> [GCP] Use the latest debian image to align python 3.10

- .github/workflows/pytest.yml
> [CI] Disable random dag test to unblock PR CIs

- examples/jupyter_lab.yaml
> [Example] Add Jupyter Lab example

- sky/skylet/providers/gcp/config.py
> [GCP] Fix GCP type assert

- sky/backends/cloud_vm_ray_backend.py
- sky/clouds/azure.py
- sky/skylet/providers/azure/config.py
- sky/templates/azure-ray.yml.j2
- tests/test_smoke.py
> [Provisioner] Open ports in Azure

- README.md
- docs/source/getting-started/installation.rst
Add instructions for installing skypilot with the nightly build. 
> [Doc] Update the doc for nightly build

- sky/cli.py
- sky/execution.py
Enhance debug ability. otherwise we will get some error without message
```
Reason: builtins.RuntimeError: .
```
> surface debug msg

- sky/cli.py
- sky/execution.py
This PR fixes the failover problem.
> [SkyServe] Fix port failover

- .pylintrc
- sky/backends/docker_utils.py
- sky/backends/local_docker_backend.py
- sky/cli.py
- sky/clouds/cloud_registry.py
- sky/clouds/gcp.py
- sky/clouds/ibm.py
- sky/clouds/kubernetes.py
- sky/clouds/oci.py
- sky/clouds/service_catalog/__init__.py
- sky/clouds/service_catalog/aws_catalog.py
- sky/clouds/service_catalog/azure_catalog.py
- sky/clouds/service_catalog/common.py
- sky/clouds/service_catalog/ibm_catalog.py
- sky/clouds/service_catalog/lambda_catalog.py
- sky/clouds/service_catalog/oci_catalog.py
- sky/clouds/service_catalog/scp_catalog.py
- sky/data/data_utils.py
- sky/data/mounting_utils.py
- sky/data/storage.py
- sky/utils/kubernetes/generate_kind_config.py
Add a docstyle checker to make sure we follow the google style module/function docs.
> [Linter] Add docstyle checker

- sky/clouds/aws.py
- sky/clouds/cloud.py
- sky/clouds/gcp.py
- sky/clouds/ibm.py
- sky/clouds/oci.py
- tests/test_optimizer_dryruns.py
Fixes #2405
It reduces the optimization time from >20s to <5s
TODO:
> [GCP] Optimize gcp optimize speed with image_id specified

- sky/spot/recovery_strategy.py
Was trying to reason through our latest recovery strategy. Adding https://github.com/skypilot-org/skypilot/pull/2234#discussion_r1275507988 to the code.
> Minor: add some docs to recovery_strategy.py.

- sky/backends/backend_utils.py
- sky/skypilot_config.py
This PR adds debug message for the status query.
> [Minor] Add debug message

- sky/serve/examples/gorilla/gorilla.yaml
- sky/serve/examples/gorilla/run_gorilla.py
- sky/serve/examples/misc/cancel/README.md
- sky/serve/examples/misc/cancel/send_cancel_request.py
- sky/serve/examples/misc/cancel/server.py
- sky/serve/examples/misc/cancel/service.yaml
> [SkyServe] Add cancel and gorilla example

- llm/vllm/README.md
- llm/vllm/serve-openai-api.yaml
> [LLM] Serve Llama-2 with vLLM and OpenAI compatible API

- llm/vllm/README.md
- llm/vllm/serve-openai-api.yaml
- llm/vllm/serve.yaml
> [LLM] better format of vllm openai api README

- llm/vllm/README.md
> [LLM] Add vllm instruction for other clouds

- sky/usage/loki-s3-config.yaml
> [Usage] Increase the limit for query series for Loki

- sky/backends/backend_utils.py
- sky/backends/cloud_vm_ray_backend.py
- sky/core.py
- sky/execution.py
- sky/serve/infra_providers.py
- sky/skylet/job_lib.py
> [SkyServe] Reduce sky status usage collection for skyserve controller

- sky/cli.py
- sky/execution.py
- sky/serve/controller.py
- sky/serve/infra_providers.py
- sky/serve/serve_utils.py
This PR fixes several bugs:
* Initialize SSH key before launching any cluster to avoid race conditions;
* Set controller resources (previously only best_resources was set) to avoid provision failure for best resources;
* Check controller cluster name is valid before writing database record;
* Add hint message when tailing replica logs;
* Make variables thread safe.
> [SkyServe] Fix bugs

- examples/tpu/tpuvm_mnist.yaml
Fixes https://github.com/skypilot-org/skypilot/issues/2469. Tested on `tpu-v2-8` and `tpu-v2-32`.
> Pin flax version to fix tpu example

- docs/source/reference/config.rst
> [Docs] GCP reservation

- sky/execution.py
> [SkyServe] Fix user hash bug

- sky/backends/backend_utils.py
- sky/backends/cloud_vm_ray_backend.py
- sky/backends/provision_utils.py
- sky/provision/__init__.py
- sky/provision/aws/config.py
- sky/provision/aws/instance.py
- sky/provision/aws/utils.py
- sky/provision/config.py
- sky/provision/instance_setup.py
- sky/provision/metadata_utils.py
- sky/setup_files/setup.py
- sky/sky_logging.py
- sky/skylet/attempt_skylet.py
- sky/utils/rich_utils.py
> [Provisioner] Get rid of ray logging, dependency for AWS, and fix logging/ray cluster

- docs/source/reference/yaml-spec.rst
> [Doc] Fix the image_id example in yaml spec

- sky/serve/autoscalers.py
- sky/serve/controller.py
- sky/serve/infra_providers.py
- sky/serve/service_spec.py
- sky/utils/schemas.py
- tests/skyserve/auto_restart.yaml
- tests/test_smoke.py
> [SkyServe] Add option to auto restart

- docs/source/reference/storage.rst
> [Docs] Typo fix storage.rst

- .github/workflows/format.yml
- .github/workflows/mypy.yml
- .github/workflows/pylint.yml
- .github/workflows/pypi-nightly-build.yml
- .github/workflows/pytest.yml
- .github/workflows/test-poetry-build.yml
- docs/requirements-docs.txt
- sky/data/data_transfer.py
- sky/setup_files/setup.py
- tests/test_pycryptodome_version.py
This follows up #2514. We should be careful with our dependencies to reduce the chance of conflicting with user packages.
Also, adds a test for `poetry lock --no-update` for #2204
```
docker run -it --rm --name skypilot-debug berkeleyskypilot/skypilot-debug /bin/bash
conda install gh --channel conda-forge
gh pr checkout 2515
pip install -e .
sky launch --cloud aws --cpus 2 --down echo hi
sky status -r
```
```
docker run -it --rm --name skypilot-debug berkeleyskypilot/skypilot-debug /bin/bash
conda install gh --channel conda-forge
gh pr checkout 2515
pip install -e .
sky launch --cloud gcp --cpus 2 --down echo hi
sky status -r
```
> Cleanup dependencies

- .github/workflows/test-poetry-build.yml
> [CI] Fix poetry CI url for forked repository

- sky/clouds/service_catalog/data_fetchers/fetch_azure.py
refer #2548 
This approach is not very elegant and requires constant manual maintenance. Perhaps a Cron CI Job could be added to periodically check that this script is working properly.
In addition, looping access https://prices.azure.com/api/retail/prices inserts a large amount of data into RAM, which may also need to be optimized later.
> fix: 🐛 fetch_azure throws error AssertionError

- docs/source/examples/docker-containers.rst
> [Docs] Add native docker support doc

- docs/source/cloud-setup/cloud-permissions/gcp.rst
> [Docs] Add minimal permission for reserve instances

- sky/clouds/azure.py
- sky/clouds/cloud.py
- sky/clouds/gcp.py
- sky/clouds/ibm.py
- sky/optimizer.py
> [Optimizer] Fix NoneType for egress when pipeline is specified

- CONTRIBUTING.md
> [Docs] Add debugging container instructions to `contributing.md`

- CONTRIBUTING.md
> Minor: Update CONTRIBUTING.md

- README.md
- docs/source/index.rst
> README: update news and LLM list.

- sky/backends/cloud_vm_ray_backend.py
- sky/cli.py
- sky/exceptions.py
- sky/usage/usage_lib.py
- sky/utils/common_utils.py
- sky/utils/subprocess_utils.py
- sky/utils/ux_utils.py
This is to make the exception in usage message more informative.
> Add more details in exception

- sky/cli.py
Fixes a bug that crept in #2660.
- `pytest tests/test_smoke.py::test_cli_logs `
> [CLI] Fix bugs when specify job_id in `sky logs`

- sky/clouds/aws.py
- sky/skylet/events.py
- sky/spot/controller.py
- sky/spot/recovery_strategy.py
> [Core] enable traceback for better debugging

- docs/source/cloud-setup/cloud-permissions/gcp.rst
> [GCP] Fix minimal roles for users

- requirements-dev.txt
- sky/setup_files/setup.py
> [Dependency] Fix pandas dependency and dev requirements

- docs/source/examples/docker-containers.rst
> [Docs] Refactoring Docker Container Docs

- sky/setup_files/setup.py
Fixes #2757
Reference: https://github.com/googleapis/google-api-python-client/commit/f6e9d3869ed605b06f7cbf2e8cf2db25108506e6
> [Dependency] Update google-api-python-client version for discardLocalSsd

- sky/backends/cloud_vm_ray_backend.py
- sky/clouds/gcp.py
- sky/skylet/providers/gcp/constants.py
> [BugFix] Fix GCP Cloud Permission doc url

- llm/vllm/serve-openai-api.yaml
- sky/clouds/gcp.py
- sky/clouds/service_catalog/data_fetchers/fetch_aws.py
> [AWS] Update image for AWS to support CUDA 12.1

- docs/source/reference/yaml-spec.rst
> Docs: add missing 'memory' field to YAML spec page.

- docs/source/getting-started/installation.rst
Put the warning about `conda install -c conda-forge grpcio=1.43.0` earlier so user hasn't already installed skypilot.
and highlight availability of a Docker installation
No tests ran; documentation change only.
> Minor docs changes for sequencing clarity

- docs/requirements-docs.txt
- docs/source/conf.py
- docs/source/examples/auto-failover.rst
- docs/source/getting-started/installation.rst
Installation
- Make installation commands stand out 
- Highlight Nightly over Latest Release, using tabs
- Move `sky check` section up to immediately follow install
- Update docker image to the debug image, which clones the main branch
Auto-provisioning GPUs
- Basics of provisioning GPUs
> Docs: update Installation and Auto-provisioning GPUs.

- docs/source/serving/service-yaml-spec.rst
- docs/source/serving/sky-serve.rst
> Minor: shorter section titles for SkyServe docs.

- sky/utils/controller_utils.py
Fixes https://github.com/skypilot-org/skypilot/commit/7d8dec2ca4cbab34d0d9b47899aa785b56df049f#diff-8acc88bd4d951508e5ea2f822f65dbc0bfaaed24fd6f8c18027affe8fda7ce1fR363.
Tested
```
sky spot launch  --cloud gcp -y -- echo hi
```
> Minor: fix `spot launch` with empty `~/.sky/config.yaml`.

- README.md
- docs/source/index.rst
Makes news entry stand out by using the word "example".
> Docs: minor updates to Mixtral example.

- sky/adaptors/aws.py
> Minor: typo update

- docs/source/reference/kubernetes/index.rst
> [k8s][docs] Update note in kubernetes docs

- sky/provision/provisioner.py
IIRC, ran into this for an unmanaged spot instance.
> Minor: improve a logging message in provisioner.py

- docs/source/serving/update.rst
Some rewording. Is it more clear?
> [Docs] Polish SkyServe update docs a bit.

- sky/utils/resources_utils.py
> [Serve] Fix unmatched parenthesis in `sky serve status`

- examples/serve/http_server/task.yaml
- sky/serve/autoscalers.py
- tests/skyserve/update/num_min_one.yaml
- tests/skyserve/update/num_min_two.yaml
- tests/test_smoke.py
> [Serve] Update min_replicas

- sky/clouds/azure.py
- sky/clouds/cloud.py
- sky/clouds/lambda_cloud.py
- sky/clouds/runpod.py
- sky/clouds/scp.py
- sky/clouds/vsphere.py
- sky/resources.py
> [Minor] Add image-id into implementation features

- README.md
> [Minor] Update News in README.md

- README.md
- llm/codellama/endpoint.yaml
Temporary fix for the issue #3070 
We should have a deeper investigation for why the `Segmentation Fault` happens, and whether we can solve it by updating the images on the clouds.
> [Docs] Pin readme torch version

- docs/source/examples/auto-failover.rst
> [Docs] Fix typo in multiple candiate resources

- sky/clouds/aws.py
- sky/clouds/azure.py
- sky/clouds/cloud.py
- sky/clouds/gcp.py
- sky/clouds/ibm.py
- sky/clouds/kubernetes.py
- sky/clouds/lambda_cloud.py
- sky/clouds/local.py
- sky/clouds/oci.py
- sky/clouds/runpod.py
- sky/clouds/scp.py
- sky/clouds/service_catalog/__init__.py
- sky/clouds/service_catalog/aws_catalog.py
- sky/clouds/service_catalog/azure_catalog.py
- sky/clouds/service_catalog/common.py
- sky/clouds/service_catalog/gcp_catalog.py
- sky/clouds/service_catalog/ibm_catalog.py
- sky/clouds/service_catalog/lambda_catalog.py
- sky/clouds/service_catalog/oci_catalog.py
- sky/clouds/service_catalog/runpod_catalog.py
- sky/clouds/service_catalog/scp_catalog.py
- sky/clouds/service_catalog/vsphere_catalog.py
- sky/clouds/vsphere.py
> [Core] Remove unused function `accelerators_in_region_or_zone`

- sky/clouds/service_catalog/gcp_catalog.py
Reverts skypilot-org/skypilot#3083
Reverting the PR due to the performance issue. #3111
> Revert "[UX] Fix GCP show-gpus order after combining VM types"

- README.md
- llm/sglang/README.md
Add news for SGLang in the readme
> [LLM] Add news for SGLang

- llm/sglang/README.md
> [LLM] Update sglang logo

- docs/source/reference/faq.rst
Add a temporary solution for #3070.
> [Docs] FAQ for pytorch 2.2.0 compatibility issue

- sky/resources.py
Reverts skypilot-org/skypilot#3139
> Revert "[Provisioner] Check ports for cloud not specified cases"

- docs/source/serving/sky-serve.rst
Fixes #3181. Thanks @ScottLL for reporting this!
> [Minor] Update sky-serve.rst

- sky/backends/backend_utils.py
Fixes a bug introduced in #3037
> [Core] Fix local cloud check

- llm/gemma/README.md
> [LLM] Add logo for Gemma

- docs/source/_static/custom.css
- docs/source/_static/custom.js
Preview: https://skypilot.readthedocs.io/en/docs-frameworks/
With full width:
With insufficient width:
> [Docs] Show "New" icon next to new sections/pages in docs.

- tests/unit_tests/test_adaptor.py
> [Tests] test_aws_adaptor_resources_memory_leakage

- sky/serve/service.py
> [Serve][BugFix] Fix reference before assignment in #3214

- sky/serve/autoscalers.py
- sky/serve/controller.py
- sky/serve/replica_managers.py
- sky/serve/service.py
> [Serve] Redirector return URLs from replica version that has at least `min_replicas` replicas 

- examples/distributed_ray_train/ray_train.yaml
- examples/distributed_ray_train/train.py
Fix OOM issue with the ray train example.
After #3248, #2812 should be fixed.
> [Example] Update ray train example

- sky/cli.py
Use green to indicate success. 
> [Minor] `local up/down` colors

- docs/source/reference/kubernetes/index.rst
Adds a quick example for attaching k8s volume. Helps SEO for users trying to figure out how to attach volumes.
> [k8s][docs] Add a quick example attaching k8s volumes

- sky/serve/service_spec.py
> [Serve][Minor] Remove redundant comment

- docs/source/index.rst
- docs/source/reference/faq.rst
- docs/source/reference/kubernetes/index.rst
- docs/source/serving/user-guides.rst
> [Docs] Updates to serving tree & FAQ

- docs/source/reference/faq.rst
- docs/source/running-jobs/environment-variables.rst
- docs/source/serving/update.rst
- sky/cli.py
Fixes formatting issues caused by #3249 
> [Docs] Fix serve docs

- docs/source/reference/kubernetes/kubernetes-setup.rst
> [Docs][minor] Fix typos in nginx ingress instructions

- sky/provision/provisioner.py
- tests/test_smoke.py
> [Test/Debug] Add version/commit in provision output, and fix smoke test leak

- docs/build.sh
> [Docs] Fix build.sh not working on Mac.

- .gitignore
- docs/source/cloud-setup/cloud-permissions/gcp.rst
- sky/serve/constants.py
- sky/serve/controller.py
- sky/serve/core.py
- sky/serve/ha/README.md
- sky/serve/ha/create_or_update_lb.sh
- sky/serve/ha/lb-ha-deployment.yaml
- sky/serve/load_balancer.py
- sky/utils/controller_utils.py
> Support multiple services; script for create/update deployment

- docs/source/_gallery_original/index.rst
> [Docs] Minor fix for the AI gallery wording

- docs/source/conf.py
- docs/source/examples/docker-containers.rst
- sky/provision/provisioner.py
> [Docs] Docker docs improvements; remove breadcrumbs.

- docs/source/_gallery_original/index.rst
- docs/source/_gallery_original/llms/dbrx.md
- docs/source/_static/custom.js
- llm/dbrx/README.md
- llm/dbrx/dbrx.yaml
> [AI Gallery] Databricks DBRX LLM

- README.md
- docs/source/docs/index.rst
> [News] DBRX

- sky/serve/replica_managers.py
> [Serve] [Bug] `_should_use_spot` use spot bug fix. 

- llm/dbrx/dbrx.yaml
> [Examples] Minor fix in DBRX YAML usage  

- sky/utils/cluster_yaml_utils.py
> [Lambda] Fix lambda cloud provisioning

- sky/clouds/azure.py
- sky/provision/azure/instance.py
> Quick error handling fix

- llm/llama-3/README.md
> [LLM] Minor fix for Llama-3 readme

- docs/source/_static/custom.js
Preview: https://skypilot.readthedocs.io/en/test-kapa/docs/index.html
> [Docs] Change Kapa hint.

- sky/clouds/cloud_registry.py
- sky/data/storage.py
- sky/task.py
- sky/utils/controller_utils.py
> [Storage] Fix default storage with R2

- README.md
- docs/source/docs/index.rst
- llm/llama-3/README.md
> [Docs] Add Llama 3 news.

- examples/tpu/tpuvm_mnist.yaml
- tests/test_smoke.py
> [Tests] Fix tpuvm mnist

- sky/optimizer.py
> [minor] Use lower case for sky check hint in optimizer

- sky/cli.py
> [k8s] Check only kubernetes for `sky local down`

- docs/source/reference/kubernetes/index.rst
> [docs] Responsive kubernetes table of contents for mobile devices

- llm/llama-3/README.md
- llm/llama-3/llama3.yaml
> [LLM] Fix llama3 example for setuptools issue

- llm/qwen/README.md
- llm/qwen/serve-110b.yaml
- llm/qwen/serve-72b.yaml
- llm/qwen/serve-7b.yaml
> [LLM] Fix dependency for qwen2

- docs/source/examples/docker-containers.rst
Many users have been stumbling with docker on runpod. 
> [Docs] Update docker docs for runpod

- sky/provision/aws/config.py
> [AWS] Fix comment for AWS pass role permission

- Dockerfile
> [Docker] Change dockerfile to install v0.6

- docs/source/getting-started/installation.rst
- docs/source/reference/kubernetes/kubernetes-troubleshooting.rst
> [Docs] Clean up cudo installation docs

- docs/source/serving/spot-policy.rst
Based on Slack discussion. @Michaelvll 
> [Docs] Clarify spot policy docs

- docs/source/reference/config.rst
- docs/source/reference/yaml-spec.rst
> [Docs] Add docs for the task level config

- sky/utils/controller_utils.py
> [Jobs] Fix jobs controller dashboard

- README.md
- docs/source/docs/index.rst
- docs/source/reference/config.rst
- docs/source/reference/storage.rst
- docs/source/reference/yaml-spec.rst
- llm/vicuna-llama-2/scripts/hardcoded_questions.py
> [Storage][doc] Update our docs for Azure blob storage

- tests/test_smoke.py
- tests/test_yamls/test_storage_mounting.yaml.j2
Closes #3781.
Tested: `pytest tests/test_smoke.py::test_docker_storage_mounts --azure`
> [Tests] Fix test_docker_storage_mounts for azure blob

- tests/test_smoke.py
This is an azure specific test. Let's mark it as so.
> [Testing] [Azure] mark `test_azure_start_stop_two_nodes` for azure

- tests/test_optimizer_dryruns.py
> [Tests] Fix newly added CPU instance for lambda

- sky/data/storage.py
> Minor: typo fix.

- sky/clouds/utils/scp_utils.py
- sky/skylet/providers/scp/config.py
Fixed the code because SCP OpenAPI changed.
To test this code, please contact kihyo.moon@samsung.com (SCP account required)
> [SCP] Fix the code for openapi changes

- sky/provision/azure/config.py
> [Azure] Fix azure failover with `RoleAssigmentUpdateNotPermitted`

- tests/test_smoke.py
> [Test] minor fix for a typo in fluidstack test

- sky/serve/serve_utils.py
> Fix comments `with sky serve update`

- docs/source/examples/auto-failover.rst
A trivial spelling fix.
N/A -- no code was touched.
> spelling fix

- docs/source/_gallery_original/index.rst
- docs/source/_gallery_original/llms/pixtral.md
- llm/pixtral/README.md
- llm/pixtral/pixtral.yaml
> [LLM] Pixtral example

- README.md
- docs/source/_static/custom.js
- docs/source/docs/index.rst
- llm/pixtral/README.md
> Fix pixtral input used

- llm/qwen/README.md
- llm/qwen/qwen15-110b.yaml
- llm/qwen/qwen2-72b.yaml
- llm/qwen/qwen2-7b.yaml
Update the dependencies for qwen examples and minor fixes to the APIs called in the readme.
```bash
curl http://$ENDPOINT/v1/chat/completions \
-H "Content-Type: application/json" \
-d '{
"model": "Qwen/Qwen2-72B-Instruct",
"messages": [
{
"role": "system",
"content": "You are a helpful and honest code assistant expert in Python."
},
{
"role": "user",
"content": "Show me the python code for quick sorting a list of integers."
}
],
"max_tokens": 512
}' | jq -r '.choices[0].message.content'
```
> [LLM] Update qwen examples

- llm/qwen/README.md
- llm/qwen/qwen25-72b.yaml
- llm/qwen/qwen25-7b.yaml
> Qwen 2.5 support

- docs/source/serving/update.rst
> [Docs] Fix highlighting in code block

- README.md
- docs/source/_gallery_original/index.rst
- docs/source/_gallery_original/llms/llama-3_2.md
- docs/source/_static/custom.js
- llm/llama-3/README.md
- llm/llama-3_2/README.md
- llm/llama-3_2/llama3_2-vision-11b.yaml
- llm/llama-3_2/llama3_2-vision-90b.yaml
- llm/llama-3_2/llama3_2.yaml
Point, launch and serve vision llama 3.2
> [LLM] Llama 3.2 guide

- docs/source/examples/auto-failover.rst
- sky/execution.py
- sky/optimizer.py
- sky/sky_logging.py
- sky/utils/controller_utils.py
- sky/utils/env_options.py
Reverts skypilot-org/skypilot#3980
Reverting for
- Ensuring provision.log (and various other logfiles) get detailed logging prefix
- More UX testing
> Revert "[UX] default to minimal logging (no module/line number/timestamp)."

- tests/test_smoke.py
> [Tests] Fix smoke test for GCP disk tier `best`

- docs/source/serving/spot-policy.rst
> [Docs] Fix inconsistent example in spot instance documentation

- docs/source/getting-started/installation.rst
> Add a missing newline that was breaking formatting

- README.md
> Fixed Typo in Readme.md

- README.md
> [Docs] News revamps.

- docs/source/running-jobs/distributed-jobs.rst
> [Docs] Typo in distributed jobs docs

- sky/exceptions.py
- sky/jobs/recovery_strategy.py
- sky/usage/usage_lib.py
- sky/utils/common_utils.py
Fixed type checking issues reported by Pylance in jobs/ and serve/ directories. Most type errors have been resolved by adding appropriate type annotations and addressing invariant type parameter issues.
> Fix type checking issues in jobs/ and serve/ directories

- sky/check.py
- sky/clouds/oci.py
Resolve https://github.com/skypilot-org/skypilot/issues/3977
> Upload all cloud credentials to sky cluster regardless of sky check

- sky/clouds/service_catalog/images/README.md
- sky/clouds/service_catalog/images/skypilot-aws-cpu-ubuntu.pkr.hcl
- sky/clouds/service_catalog/images/skypilot-aws-gpu-ubuntu.pkr.hcl
- sky/clouds/service_catalog/images/skypilot-azure-cpu-ubuntu.pkr.hcl
- sky/clouds/service_catalog/images/skypilot-azure-gpu-ubuntu.pkr.hcl
Packer scripts for generating skypilot images for all US regions
> [Performance] Add Azure packer scripts for custom images

- docs/source/examples/managed-jobs.rst
To hopefully make it more clear.
> [Docs] Update Managed Jobs page.

- sky/setup_files/setup.py
Address https://github.com/skypilot-org/skypilot/issues/4202
> Upgrade Azure SDK version requirement

- sky/backends/cloud_vm_ray_backend.py
- sky/setup_files/setup.py
- tests/test_smoke.py
> [Core] Fix issue with the wrong path of setup logs

- docs/source/reference/faq.rst
- sky/clouds/service_catalog/images/README.md
- sky/clouds/service_catalog/images/provisioners/user-toolkit.sh
- sky/clouds/service_catalog/images/skypilot-aws-cpu-ubuntu.pkr.hcl
- sky/clouds/service_catalog/images/skypilot-aws-gpu-ubuntu.pkr.hcl
- sky/clouds/service_catalog/images/skypilot-azure-cpu-ubuntu.pkr.hcl
- sky/clouds/service_catalog/images/skypilot-azure-gpu-ubuntu.pkr.hcl
- sky/clouds/service_catalog/images/skypilot-gcp-cpu-ubuntu.pkr.hcl
- sky/clouds/service_catalog/images/skypilot-gcp-gpu-ubuntu.pkr.hcl
> Add user toolkits to all sky custom images and fix PyTorch issue on A10

- docs/source/reference/config.rst
This updates the doc for the feature added at #3764 
> [docs][azure] Update config doc for azure resource group specification

- sky/backends/backend_utils.py
- sky/clouds/cloud.py
- sky/jobs/core.py
- sky/optimizer.py
- sky/provision/__init__.py
- sky/utils/timeline.py
- Add the current stack trace to the "args" of reported events. This can be helpful to understand where an expensive function is being called.
It looks like this in Perfetto:
- Instrument some more functions that can be expensive. These are just ones I've come across while looking into performance improvements.
There are no functionality changes outside the timeline utility.
> improve tracing reporting and coverage

- sky/serve/serve_utils.py
- sky/skylet/log_lib.py
- sky/utils/log_utils.py
> Refactor: Consolidate log streaming logic into centralized `log_utils.follow_logs()`

- sky/clouds/service_catalog/data_fetchers/fetch_gcp.py
Fixes https://github.com/skypilot-org/skypilot-catalog/actions/runs/11760909066/job/32762128537
> [Catalog] fix GCP catalog missing SKUs

- docs/source/reference/kubernetes/index.rst
- docs/source/reference/kubernetes/kubernetes-getting-started.rst
Remove stale roadmap, add FAQs on autoscaling and multi-cluster.
Follow up to https://github.com/skypilot-org/skypilot/pull/3437.
> [Docs] Update k8s docs

- sky/execution.py
If a cluster is mid-initialization, its status will be INIT and autostop/down will not be set yet. In this case, the cluster refresh won't actually grab the cluster status lock and hard refresh the status. So, check_cluster_available will immeidately decide that the cluster is INIT and throw.
This could cause a bug where many parallel launches of `sky launch --fast` that are staggered can all decide that the cluster is INIT, and all decide that they need to launch the cluster. Since cluster initialization is locked with the cluster status lock, each invocation will sychronously re-launch the cluster.
Now, if we see that the cluster is INIT, we force a refresh. This will acquire the cluster status lock, which will block until any ongoing provisioning completes and the cluster is UP. If the …
> [fast] if cluster is INIT, force refresh before deciding to provision

- docs/source/examples/managed-jobs.rst
> [Docs] Fix some issues with Managed Jobs example.

- docs/source/_static/custom.js
> [Docs] Fix ask ai location

- sky/provision/azure/instance.py
- sky/templates/azure-ray.yml.j2
> Fix Spot instance on Azure

- sky/provision/azure/instance.py
Fixes https://github.com/skypilot-org/skypilot/pull/4408#issuecomment-2499122260
~~Testing now.~~
Tested with both OD and Spot and both of them works well.
> Fix OD instance on Azure

- sky/clouds/service_catalog/__init__.py
- sky/clouds/service_catalog/data_fetchers/fetch_azure.py
- sky/provision/kubernetes/utils.py
> [UX] Remove K80 and M60 from common GPU list

- docs/source/serving/sky-serve.rst
- examples/serve/minimal.yaml
- sky/serve/core.py
- sky/serve/load_balancer.py
- sky/serve/load_balancing_policies.py
- sky/serve/serve_state.py
- sky/serve/serve_utils.py
- sky/serve/service.py
- sky/serve/service_spec.py
- tests/skyserve/load_balancer/service.yaml
- tests/skyserve/update/new.yaml
- tests/skyserve/update/old.yaml
After studying in simulator (and double-checked in e2e experiment), we find that the simple least load policy (the `LPR` in the figure) performs reasonably well and often near our optimal solution. This PR add the least load policy and change the default policy to it.
_LPR stand for Least Processing Requests_
> [Serve] Add and adopt least load policy as default poicy.

- llm/ollama/ollama.yaml
The previous download link https://ollama.com/download/ollama-linux-arm64 is no longer available. It has been updated to the new universal download link: https://ollama.com/download/linux.
This change ensures that users can download Ollama from the correct source, regardless of their system architecture (ARM or x86).
Tested on GKE:
Launch command:
```
sky launch ~/skypilot/llm/ollama/ollama.yaml --env MODEL_NAME=llama2 -c ollama
```
```
~/skypilot on dev/hong/ollama *1 >  curl $ENDPOINT/v1/chat/completions \                                                                    py sky at 18:58:50
-H "Content-Type: application/json" \
-d '{
"model": "llama2",
"messages": [
{
"role": "system",
"content": "You are a helpful assistant."
},
{
"role": "user",
"content": "Who are you?"
}
]
}' …
```
> [Examples] Update Ollama setup commands

- docs/source/reference/yaml-spec.rst
> [docs] Add image_id doc in task YAML for OCI

- docs/source/_static/custom.js
Kapa's DNS outage (#4518) is resolved, we can enable it now.
> [Docs] Enable kapa

- sky/resources.py
> Minor: typo fix in resources.py

- sky/provision/gcp/instance_utils.py
When creating a new instance, SkyPilot will try to set the labels for the instance, but when there is another Cloud Function running in parallel that also tries to set the labels, there might be race condition causing the following error:
```
D 01-18 08:11:03 provisioner.py:154] bulk_provision for 't-gcp-stale-job-manua-6k-7b' failed. Stacktrace:
D 01-18 08:11:03 provisioner.py:154] Traceback (most recent call last):
D 01-18 08:11:03 provisioner.py:154]   File "/skypilot/sky/provision/gcp/instance.py", line 362, in run_instances
D 01-18 08:11:03 provisioner.py:154]     return _run_instances(region, cluster_name_on_cloud, config)
D 01-18 08:11:03 provisioner.py:154]   File "/skypilot/sky/provision/gcp/instance.py", line 291, in _run_instances
D 01-18 08:11:03 provisioner.py:154] …
```
> [GCP] Add retry for `set_labels` when creating instances

- sky/usage/loki-s3-config.yaml
> [Usage] Update loki to 3.3

- sky/usage/loki-s3-config.yaml
> [Usage] Increase frontend grpc size for loki

- docs/source/reference/kubernetes/multi-kubernetes.rst
> [Docs] Minor polishing on Multiple Kubernetes docs.

- sky/jobs/dashboard/templates/index.html
Finetune some texts, colors, tooltip.
Make Details not show full text by default (important for long failures):
> [Jobs dashboard] Minor polishing.

- sky/authentication.py
- sky/backends/cloud_vm_ray_backend.py
- sky/jobs/controller.py
- sky/jobs/core.py
- sky/jobs/recovery_strategy.py
- sky/jobs/state.py
- sky/jobs/utils.py
- sky/skylet/constants.py
- sky/utils/controller_utils.py
- sky/utils/dag_utils.py
- sky/utils/log_utils.py
- sky/utils/schemas.py
- tests/test_config.py
> remove remaining references to "spot" controller

- docs/source/reference/api-server/api-server-admin-deploy.rst
Updates the endpoint fetching step in the docs to reduce clutter and adds a tip to use static IPs for NodePort services.
> [Docs] Update endpoint fetching docs for client-server

- examples/vector_database/README.md
- llm/deepseek-r1/README.md
Update the readme with the latest figures and links
Doc Fix Only
> [Examples] Update Vector DB Doc

- docs/source/getting-started/installation.rst
> [Docs] Installation: move up k8s.

- llm/deepseek-r1/README.md
> [LLM] Update Deepseek r1 README.md

- llm/deepseek-r1/README.md
> minor update to example

- sky/clouds/service_catalog/data_fetchers/fetch_lambda_cloud.py
feat: Add australia-east-1 region
Add `australia-east-1` lambda cloud region.
> feat: Add australia-east-1 region

- sky/optimizer.py
- sky/resources.py
- tests/backward_compatibility_tests.sh
- tests/test_optimizer_dryruns.py
> [UX] Fix inferring cloud from instance type

- docs/source/conf.py
> [Minor] 2024 -> 2025 in docs.

- sky/provision/kubernetes/instance.py
> [k8s] Merge tolerations instead of overriding them when using TPUs

- sky/client/sdk.py
> [API Server] Fix single request in `api_cancel`

- sky/backends/backend_utils.py
> [Core] Add retry for file mounts optimization

- docs/source/reference/config.rst
- docs/source/reference/yaml-spec.rst
> Add doc reference for yaml-spec.rst

- docs/source/reference/api-server/api-server-admin-deploy.rst
> [Docs] Move helm repo setup earlier in the docs

- docs/source/_static/custom.js
- docs/source/docs/index.rst
> [Docs] Minor: move pages.

- llm/rag/README.md
- llm/rag/scripts/serve_rag.py
- llm/rag/scripts/templates/index.html
updated UI and link the readme to the blog post
> [Example] Polish RAG Example

- README.md
> [Docs] Fix docs badge

- sky/server/requests/serializers/decoders.py
> [APIServer] Cast job_id to int for `job_status` decoder

- docs/source/reference/kubernetes/kubernetes-getting-started.rst
> [Docs] Add quick start to k8s getting started docs

- sky/cli.py
We have a missing line in cli.py
> [Storage] Fix storage deletion for all

- sky/cli.py
> show managed jobs user column in `sky status -u`

- sky/clouds/service_catalog/data_fetchers/fetch_vast.py
Previously this file emitted to sys.stdout which prevented the catalog-fetcher from actually updating the catalog.
This has now been updated matching many of the patterns employed by other vendors in this directory.
> Updates the vast catalog to write directly to the vms.csv

- docs/source/getting-started/installation.rst
> [Docs] Minor updates to installation.rst

- README.md
- docs/source/docs/index.rst
- docs/source/examples/frameworks/index.rst
- docs/source/examples/training/index.rst
- docs/source/reference/kubernetes/examples/index.rst
- docs/source/reference/kubernetes/index.rst
- docs/source/reservations/reservations.rst
> [Docs] Add a few more examples for k8s.

- .github/pull_request_template.md
> update PR template to use CI tests

- docs/source/docs/index.rst
> [Docs] Minor: pull up a page.

- llm/gemma3/README.md
- llm/gemma3/gemma3.yaml
gemma 3 exampel
run with readme
> [Examples] LLM/Gemma3 Example 

- docs/README.md
- docs/source/reference/api-server/api-server.rst
> [Docs] Update benefits for client-server

- sky/provision/kubernetes/utils.py
This PR addresses comments made to https://github.com/skypilot-org/skypilot/pull/4935 after it has been merged to master.
> followup to #4935

- llm/batch_inference/README.md
- llm/batch_inference/batch_compute_vectors.py
- llm/batch_inference/compute_text_vectors.yaml
- llm/batch_inference/monitor_progress.yaml
- llm/batch_inference/scripts/base_vector_processor.py
- llm/batch_inference/scripts/monitor_progress.py
- llm/batch_inference/scripts/text_vector_processor.py
> [Example] Batch Inference 

- docs/source/docs/index.rst
> [Docs] Update ToC title to "Start a Development Cluster"

- docs/source/examples/applications/batch_inference.md
- docs/source/examples/applications/index.rst
> [docs] add batch inference example to examples dropdown

- sky/jobs/server/server.py
close https://github.com/skypilot-org/skypilot/issues/5043
@Michaelvll @cg505 PTAL
> [API server] Fixed jobs logs blocked by jobs launch

- sky/clouds/do.py
close https://github.com/skypilot-org/skypilot/issues/5060
> Fix job launch failed on master

- sky/cli.py
> [UX] Short hand for `sky jobs queue -a`

- charts/skypilot/templates/rbac.yaml
- values.yaml
close https://github.com/skypilot-org/skypilot/issues/5074
@romilbhardwaj PTAL, thanks!
> [API server] Auto create skypilot-system ns on helm install

- sky/core.py
- sky/global_user_state.py
- sky/models.py
- sky/server/requests/payloads.py
- sky/server/server.py
- Set optional default value to none to avoid the error `{"detail":[{"type":"missing","loc":["body","name"],"msg":"Field required"` when canceling managed jobs with `job_ids` only with API.
- Add users API
- Cancel the managed jobs with `job_ids` only with API
- Get users info through API
> [Core] Add users API and set optional default value to none

- README.md
Remove the badge for build
Before:
After:
> remove badge

- sky/adaptors/azure.py
> chore: update azure.py

- sky/backends/backend.py
- sky/backends/cloud_vm_ray_backend.py
- sky/backends/local_docker_backend.py
- sky/core.py
- sky/execution.py
- tests/smoke_tests/test_basic.py
> [fast] don't skip setup if we do provisioning

- sky/adaptors/nebius.py
- sky/cloud_stores.py
- sky/clouds/nebius.py
- sky/data/data_utils.py
- sky/data/mounting_utils.py
- sky/data/storage.py
- tests/smoke_tests/test_mount_and_storage.py
Fix support regions. Get the region and endpoint URL from the AWS configuration.
> [Nebius] Fix Nebius Object Storage support regions

- CONTRIBUTING.md
The existing development environment setup guide is outdated and may lead to confusion for new contributors.
1. Update the development environment setup instructions in the contributing guide to reflect the latest requirements
2. Add a step-by-step walkthrough to help contributors set up their environment smoothly
> [Docs] Update development environment setup in the contributing code

- tests/unit_tests/test_sky/utils/test_subprocess_utils.py
close https://github.com/skypilot-org/skypilot/issues/5215
> Fix failed test_subprocess_utils.py.test_multiple_processes test

- sky/utils/controller_utils.py
This regressed in #4835.
Fixes #5186.
> [controller] fix kubectl installation

- sky/utils/config_utils.py
- tests/unit_tests/test_sky/utils/test_config_utils.py
~Should fix~ Fixes https://github.com/skypilot-org/skypilot/issues/5104
Related PR: https://github.com/skypilot-org/skypilot/pull/4762 (which works on a related, but not the same, problem regarding config merging)
Specifically, this comment
The following snippet is a valid, complete kubernetes configuration from our [Advanced configuration](https://docs.skypilot.co/en/latest/reference/config.html#gcp-vpc-name) page:
```
kubernetes:
ports: loadbalancer
remote_identity: my-k8s-service-account
allowed_contexts:
- context1
- context2
custom_metadata:
labels:
mylabel: myvalue
annotations:
myannotation: myvalue
provision_timeout: 10
autoscaler: gke
pod_config:
metadata:
labels:
my-label: my-value
spec:
runtimeClassName: nvidia
```
Out of these fields, we only want to use `merge_k8s_configs` on …
> [k8s] only use merge_k8s_configs on specific k8s config fields

- docs/source/reference/config.rst
> [docs] add config spec for jobs.controller.autostop

- docs/source/_static/custom.css
- docs/source/conf.py
> [Docs] Add meetup banner

- docs/source/reference/api-server/api-server.rst
> [docs] add a note about -u flag to API server page

- docs/source/conf.py
> Minor docs change.

- docs/source/reference/api-server/api-server-admin-deploy.rst
> [Doc] Fix missing namespace in API server deployment doc

- sky/client/sdk.py
- tests/unit_tests/test_sky/server/test_sdk.py
close https://github.com/skypilot-org/skypilot/issues/5261
> Fix API login

- docs/source/reference/kubernetes/examples/index.rst
> Fix GKE example links

- examples/distributed-pytorch/train.yaml
- tests/smoke_tests/test_cluster_job.py
* Add a smoke test case
* #5181 already resolved in #5195, so we only need to add test case
- [Failure](https://buildkite.com/skypilot-1/smoke-tests/builds/719#_)
- Success -- see github test status
> Test for `examples/distributed-pytorch/train.yaml`

- charts/skypilot/templates/api-deployment.yaml
- charts/skypilot/values.yaml
- docs/source/reference/api-server/api-server-admin-deploy.rst
closes https://github.com/skypilot-org/skypilot/issues/5218
> [Helm] Make secret name configurable

- sky/clouds/service_catalog/data_fetchers/fetch_gcp.py
Fixes
https://github.com/skypilot-org/skypilot-catalog/actions/runs/14527666105/job/40762115785
> [Catalog] Fix unstable GCP TPU v6e pricing api

- .github/workflows/fusermount-server-image.yaml
- addons/fuse-proxy/cmd/fusermount-wrapper/main.go
- addons/fuse-proxy/go.mod
- addons/fuse-proxy/go.sum
- sky/data/mounting_utils.py
- tests/smoke_tests/test_mount_and_storage.py
- tests/test_yamls/test_storage_mounting.yaml.j2
close https://github.com/skypilot-org/skypilot/issues/5307
> [Azure] fix multiple blobfuse2 mount on kubernetes

- docs/source/conf.py
> [Docs] Remove meetup announcement banner

- Dockerfile
- sky/__init__.py
Bump the release to 0.9.1 to include the dashboard out files
> Release 0.9.1

- docs/source/reference/api.rst
- docs/source/reference/async.rst
- docs/source/reference/faq.rst
> [Docs] Fix migration guide version

- tests/smoke_tests/test_cluster_job.py
> Fix broken test `test_gcp_disk_tier` 

- sky/server/requests/executor.py
close https://github.com/skypilot-org/skypilot/issues/5408
> [API server] Fix worker number for non-local low resource env

- sky/cli.py
- tests/smoke_tests/test_region_and_zone.py
> [k8s] Fix IPv6 SSH

- README.md
- llm/qwen/README.md
- llm/qwen/qwen3-235b.yaml
> Qwen3 235b example 

- docs/source/examples/frameworks/index.rst
> [Docs] Fix DWS/Kueue title and URL

- sky/resources.py
Fixes #5439.
This PR cherry-picks #5441 into the 0.9.2 release.
> avoid using removed LEGACY_SINGLETON_REGION constant (#5441)

- sky/dashboard/src/data/connectors/clusters.jsx
- sky/server/common.py
- sky/server/constants.py
- sky/server/server.py
> remove API version bump, add bw compatibility code

- sky/server/requests/payloads.py
close https://github.com/skypilot-org/skypilot/issues/5510
> Reload AWS default profile for local API server

- llm/llama-3_1-finetuning/lora.yaml
Fixes https://github.com/skypilot-org/skypilot/issues/5530.
> [Examples] Llama 3.1 lora finetuning torch version pin

- docs/source/examples/docker-containers.rst
- sky/provision/docker_utils.py
- sky/templates/gcp-ray.yml.j2
> [Docker] Add private docker registry

- sky/provision/gcp/instance.py
- sky/provision/gcp/instance_utils.py
- tests/smoke_tests/test_images.py
> [GCP] Correctly delete cpu mig instance

- docs/source/reference/yaml-spec.rst
> [Docs] move `ordered` to a section

- README.md
- docs/source/examples/frameworks/index.rst
- llm/llama-4/README.md
- llm/sglang/README.md
> [Docs] Add a few tutorial links.

- docs/source/examples/docker-containers.rst
> [Docs] Minor fix to the container tabs

- docs/source/reference/api-server/api-server.rst
- examples/k8s_cloud_deploy/README.md
> [Docs] Fix quote for URL

- llm/gemma3/gemma3.yaml
> [LLM] Update gemma example

- sky/templates/nebius-ray.yml.j2
> [Nebius] add ~/.ssh/sky-cluster-key

- .github/workflows/release-publish.yml
close #5432 
@zpoint PTAL, thanks!
> Add helm release in release pipeline

- sky/backends/backend_utils.py
- sky/backends/cloud_vm_ray_backend.py
- sky/global_user_state.py
- sky/server/requests/executor.py
- sky/server/requests/requests.py
- sky/server/server.py
- sky/server/uvicorn.py
- sky/sky_logging.py
- sky/skylet/log_lib.py
- sky/skylet/log_lib.pyi
- sky/utils/command_runner.py
- sky/utils/context.py
- sky/utils/context_utils.py
- sky/utils/rich_utils.py
- sky/utils/subprocess_utils.py
- tests/unit_tests/test_sky/server/test_server.py
- tests/unit_tests/test_sky/test_sky_logging.py
- tests/unit_tests/test_sky/utils/test_context_utils.py
- tests/unit_tests/test_sky/utils/text_context.py
close https://github.com/skypilot-org/skypilot/issues/4767
Reopen this PR to address backward compatibility issue
The review and smoke test history can be found in the original PR: https://github.com/skypilot-org/skypilot/pull/5366
commit to fix the compatibility issue: https://github.com/skypilot-org/skypilot/pull/5582/commits/e1691afe897694fbc8298d0538ef9281f8b184d7
> [API server] handle logs request in coroutine

- .github/workflows/pypi-nightly-build.yml
- .github/workflows/release-publish.yml
Fix check script in build actions
> [Build] Fix check script in build actions

- tests/smoke_tests/test_cluster_job.py
We recently failed on `test_gcp_disk_tier`:
```bash
[gcp-disk-tier-ultra] Reason: name=`gcloud compute instances list --filter="labels.ray-cluster-name:t-gcp-disk-tier-ce-ultra-e5e52a56" --format="value(name)"`; gcloud compute disks list --filter="name=$name" --format="value(type)" \| grep pd-extreme
```
The issue is: when launching an instance with this command:
```bash
sky launch -y -c t-gcp-disk-tier-9f-ultra --cloud gcp --region us-west2 --cpus 2+ --memory 4+ --disk-tier ultra
```
We pass the instance type `n2-standard-64` to `GCP._get_disk_type()`, making it think we have 64 CPUs and return `pd-extreme`. But the actual launched instance is `n2-standard-2`, which should use `pd-ssd` (as noted in #5457: `n2 series with less than 64 vCPUs doesn't support pd-extreme, use pd-ssd for …
> Fix `test_gcp_disk_tier`

- .github/workflows/release-build.yml
> Release branch name fix

- charts/skypilot/templates/api-deployment.yaml
- charts/skypilot/values.yaml
- docs/source/reference/api-server/api-server-admin-deploy.rst
Add support of https://github.com/skypilot-org/skypilot/issues/5603
> [Nebius] Nebius credentials for the API server deployment

- sky/utils/kubernetes/deploy_remote_cluster.py
- sky/utils/kubernetes/ssh-tunnel.sh
> Fix IPv6 tunneling by force IPv4

- sky/utils/kubernetes/cleanup-tunnel.sh
- sky/utils/kubernetes/deploy_remote_cluster.py
- sky/utils/kubernetes/ssh-tunnel.sh
- sky/utils/log_utils.py
> [Clouds] Allow removal of SSH targets

- sky/backends/cloud_vm_ray_backend.py
- tests/smoke_tests/test_cluster_job.py
> [Core] Fix retry for command `too large` with cloudflare proxy

- sky/utils/kubernetes/deploy_remote_cluster.py
> [Fix] SSH Tunnel cleanup

- sky/dashboard/src/components/infra.jsx
> [Dashboard] Add ssh node pool

- docs/source/examples/auto-failover.rst
- docs/source/overview.rst
- docs/source/reference/kubernetes/kubernetes-priorities.rst
- docs/source/reference/yaml-spec.rst
- examples/aws_efa/nccl_efa.yaml
- sky/check.py
Mainly added some examples in earlier parts of the docs, to orient reader on the schema & example values.
https://docs.skypilot.co/en/minor-infra/docs/index.html
> [Docs] Clarify --infra.

- sky/check.py
- sky/clouds/aws.py
- sky/clouds/azure.py
- sky/clouds/cloud.py
- sky/clouds/cudo.py
- sky/clouds/do.py
- sky/clouds/fluidstack.py
- sky/clouds/gcp.py
- sky/clouds/ibm.py
- sky/clouds/kubernetes.py
- sky/clouds/lambda_cloud.py
- sky/clouds/nebius.py
- sky/clouds/oci.py
- sky/clouds/paperspace.py
- sky/clouds/runpod.py
- sky/clouds/scp.py
- sky/clouds/ssh.py
- sky/clouds/vast.py
- sky/clouds/vsphere.py
- sky/utils/kubernetes/deploy_remote_cluster.py
> [UX][SSH] Fix UX for SSH & K8S Cloud

- sky/cli.py
- sky/clouds/__init__.py
- sky/clouds/cloud.py
- sky/clouds/kubernetes.py
- sky/clouds/ssh.py
> [UX] Show infra in sky status

- sky/utils/kubernetes/deploy_remote_cluster.py
- sky/utils/log_utils.py
Adding:
1. Detailed logging information for failures.
2. Directly fail on master node failure (fig 1).
3. Ignore worker nodes failure (fig 2).
> Error handing for sky ssh up

- sky/check.py
- sky/cli.py
- sky/client/sdk.py
- sky/data/storage.py
- sky/global_user_state.py
- sky/jobs/utils.py
- sky/optimizer.py
- sky/server/requests/payloads.py
- sky/skypilot_config.py
When there are multiple workspaces
When there is only one workspace
> [Workspace] `sky check` chceks all workspaces

- sky/check.py
Fixing:
1. Remove the identity when no ssh pools.
2. Show disabled for cluster that has not been configured.
3. Remove unavailable node pools at the end.
> Fix UX for sky check SSH

- charts/skypilot/templates/ingress.yaml
- docs/source/reference/api-server/api-server-admin-deploy.rst
- docs/source/reference/api-server/api-server-troubleshooting.rst
close https://github.com/skypilot-org/skypilot/issues/5508
close https://github.com/skypilot-org/skypilot/issues/4777
@SeungjinYang Please take a look, thanks!
> API server mulitple deployment docs

- sky/check.py
- sky/clouds/kubernetes.py
> Fix k8s check bug

- sky/core.py
- sky/dashboard/src/components/infra.jsx
- sky/dashboard/src/data/connectors/infra.jsx
- sky/server/server.py
> [Dashboard] Infra page with cpu nodes

- docs/source/reference/yaml-spec.rst
> [Docs] Make Volumes a subsection.

- docs/source/extension/linting.py
- docs/source/reference/api-server/api-server.rst
- docs/source/reservations/existing-machines.rst
> Fix docs lints.

- sky/utils/kubernetes/deploy_remote_cluster.py
- sky/utils/log_utils.py
> [SSH] Enable tcp forwarding in `sky ssh up`

- sky/utils/kubernetes/deploy_remote_cluster.py
- sky/utils/log_utils.py
> [SSH] Fix host in ssh config detection

- docs/source/reference/config.rst
- sky/clouds/nebius.py
- sky/provision/nebius/instance.py
- sky/provision/nebius/utils.py
- sky/templates/nebius-ray.yml.j2
- sky/utils/schemas.py
> [Nebius] Add support filesystem

- docs/source/overview.rst
> [Docs] Minor: Add --infra ssh to Overview.

- sky/cli.py
> [SSH] Use appropriate column title for `show-gpus`

- docs/source/admin/workspaces.rst
This PR updates the configuration doc to make the update of workspaces in helm deployment more clear.
> Update workspace configuration doc

- sky/client/sdk.py
https://github.com/skypilot-org/skypilot/actions/runs/15203935479/job/42762919806
> [show-gpus] Fix show-gpus body

- sky/check.py
- sky/skypilot_config.py
> [Workspace] fix ws context in `sky check`

- sky/utils/kubernetes/deploy_remote_cluster.py
- sky/utils/log_utils.py
> [SSH] Continue after one ssh pool failed

- charts/skypilot/templates/ingress.yaml
> fix http for auth proxy helm chart

- sky/dashboard/src/data/connectors/jobs.jsx
> [dashboard] fix job count on users page

- docs/source/reference/api-server/api-server-admin-deploy.rst
- docs/source/reference/api-server/examples/api-server-auth-proxy.rst
Based on dogfooding experience today.
> [Docs] Polishing oauth docs

- docs/source/images/client-server/auth-proxy-internals.svg
This was a mistake, I meant for them to be happy the whole time.
> [docs] smiley face

- sky/global_user_state.py
Fixes a duplicate add column line identified at https://github.com/skypilot-org/skypilot/pull/5634#discussion_r2105239779
> remove duplicated add column line

- sky/utils/kubernetes/deploy_remote_cluster.py
- sky/utils/kubernetes/kubernetes_deploy_utils.py
> [SSH] Fix `sky ssh up` errors not surfaced to user, log paths

- docs/source/admin/workspaces.rst
> [Docs] Add CLI override for workspaces

- docs/source/reference/api-server/api-server-admin-deploy.rst
- docs/source/reservations/existing-machines.rst
Moved docs to the helm deployment page, added some notes and comments based on dogfooding.
> [Docs] Update SSH Node Pool docs for helm

- examples/nebius_infiniband/README.md
> [Docs] Fix nccl link

- sky/server/constants.py
There have been significant amount of features added to API server, and the newly added API won't be covered by old API server. To have people update SkyPilot API server with their client, we now bump the API version.
> [Core] Bump API version

- docs/source/reference/auto-stop.rst
> [Docs] Update autostop page.

- docs/source/reference/api-server/examples/api-server-auth-proxy.rst
- docs/source/reference/yaml-spec.rst
> [docs] fix minor formatting typos

- docs/source/examples/index.rst
- docs/source/examples/skypilot-deployment/api-deploy-gke-nebius-okta.md
- docs/source/examples/skypilot-deployment/index.rst
- examples/api-deploy-gke-nebius-okta/README.md
> [Example] API server deployment docs

- sky/setup_files/dependencies.py
> pin pyopenssl version

- docs/source/cloud-setup/cloud-permissions/nebius.rst
closes https://github.com/skypilot-org/skypilot/issues/5637
> [docs] simplified nebius service account docs

- sky/cli.py
- sky/client/sdk.py
- sky/server/common.py
> [CLI] Redirect jobs dashboard to API dashboard

- docs/source/examples/managed-jobs.rst
- docs/source/reference/yaml-spec.rst
> [Docs] Priority.

- sky/backends/cloud_vm_ray_backend.py
partially addresses https://github.com/skypilot-org/skypilot/issues/5011
> delete the cluster yaml on cleanup

- sky/authentication.py
- sky/backends/backend_utils.py
- sky/global_user_state.py
> stash ssh key files into database

- docs/source/reservations/existing-machines.rst
> [Docs][SSH] Specify that private-ip connections is required for ssh

- sky/jobs/utils.py
> [jobs] indicate when job is blocked by higher priority

- tests/smoke_tests/test_mount_and_storage.py
> [Tests] Fix `tmp_multiple_custom_source_storage_obj`

- docs/source/examples/managed-jobs.rst
> [Docs] Update term for job priority

- sky/adaptors/kubernetes.py
- sky/clouds/kubernetes.py
- sky/provision/kubernetes/utils.py
close https://github.com/skypilot-org/skypilot/issues/5862
> [Core] Avoid importing kubernetes when processing credential file mounts

- sky/server/constants.py
> [API] Bump API version

- sky/server/constants.py
- sky/templates/websocket_proxy.py
> use default cookie file for websocket proxy

- sky/resources.py
- tests/unit_tests/test_resources.py
close https://github.com/skypilot-org/skypilot/issues/5885
> Fix autodown smoke test

- sky/clouds/kubernetes.py
Fixes #5837 
ps: ssh cloud overrides `existing_allowed_contexts` so won't conflict
> [SSH][k8s] Support k8s incluster check when SSH is enabled 

- sky/dashboard/src/pages/clusters/[cluster].js
> [Dashboard] Avoid showing cluster yaml for controllers

- sky/server/stream_utils.py
- tests/smoke_tests/test_basic.py
- tests/smoke_tests/test_cluster_job.py
close https://github.com/skypilot-org/skypilot/issues/5857
> Fix: add buffer to log streaming and test output

- docs/source/reference/api-server/api-server-admin-deploy.rst
- docs/source/reference/config.rst
- docs/source/reference/training-guide.rst
> [Docs] A few touches on network_tier and db.

- sky/dashboard/src/components/users.jsx
> [Dashboar] Make ID a new column in user page

- .github/workflows/release-build.yml
Resolve #5599
See [this link](https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication) explaining why auto-created PRs won't trigger checking workflows.
> [About the GITHUB_TOKEN secret](https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication#about-the-github_token-secret):
> 
> When you use the repository's GITHUB_TOKEN to perform tasks, events triggered by the GITHUB_TOKEN, with the exception of workflow_dispatch and repository_dispatch, will not create a new workflow run. This prevents you from accidentally creating recursive workflow runs. For example, if a workflow run pushes code using the repository's GITHUB_TOKEN, a new workflow will not run even when the repository contains …
> Enable workflow trigger in release PR 

- sky/serve/serve_state.py
> lazy initialization of services db

- llm/gpt-2/gpt2.yaml
Fixes #5520 
I didn't have time to run the entire gpt2 example (takes too long) used a modified yaml file for testing:
btw, calling `conda activate` on both setup and run is important
[yaml file](https://github.com/kyuds/skyutils/blob/main/custom_image.yaml)
```
resources:
image_id: docker:nvidia/cuda:12.4.1-cudnn-devel-ubuntu22.04
accelerators: A100
infra: gcp
setup: |
conda activate base
python --version
run: |
conda activate base
echo "python version"
python --version
echo "end of output"
```
> [Examples] Fix GPT2 Example

- sky/backends/backend.py
- sky/backends/backend_utils.py
- sky/backends/cloud_vm_ray_backend.py
- sky/backends/local_docker_backend.py
- sky/cli.py
- sky/client/sdk.py
- sky/core.py
- sky/dashboard/src/components/infra.jsx
- sky/dashboard/src/data/connectors/clusters.jsx
- sky/execution.py
- sky/global_user_state.py
- sky/optimizer.py
- sky/provision/provisioner.py
- sky/resources.py
- sky/server/requests/payloads.py
- sky/skylet/log_lib.py
- sky/utils/registry.py
- sky/utils/ux_utils.py
> [DOV] `ssh up` on clusters

- sky/adaptors/kubernetes.py
- sky/check.py
- sky/cli.py
- sky/clouds/ssh.py
- sky/provision/kubernetes/instance.py
- sky/provision/kubernetes/utils.py
- sky/resources.py
- sky/utils/common_utils.py
- sky/utils/infra_utils.py
- sky/utils/string_utils.py
- tests/unit_tests/test_sky/clouds/test_ssh.py
> [Core] removes lstrip('ssh-')

- sky/jobs/server/core.py
- sky/resources.py
- sky/utils/schemas.py
- tests/unit_tests/test_resources.py
- tests/unit_tests/test_sky/utils/test_schemas.py
> add priority to resources

- docs/source/reference/yaml-spec.rst
Added network tier docs in the yaml
> Added docs for network_tier in yaml

- sky/client/cli/command.py
- sky/jobs/server/core.py
- sky/task.py
- sky/utils/schemas.py
Follows up on #6038 and actually removes support of job priority from code.
> code implementation of job priority removal

- llm/llama-3_1-finetuning/readme.md
Correct some typos found while running through the example.
> [Examples] Fix path and URL in Llama 3.1 finetuning example

- tests/test_api_compatibility.py
See discussion [here](https://github.com/skypilot-org/skypilot/pull/6046#discussion_r2159130281)
> Remove `test_no_new_models_added`

- docs/source/_static/custom.js
> Add badge to external logging doc

- sky/utils/context.py
> Fix Popen in context

- docs/source/reference/api-server/api-server-upgrade.rst
- sky/server/rest.py
> [Docs] Add a gif in upgrade doc

- docs/source/reference/api-server/api-server-upgrade.rst
> [Docs] Minor: typos.

- charts/skypilot/values.yaml
- docs/source/cloud-setup/cloud-permissions/aws.rst
- docs/source/cloud-setup/cloud-permissions/vsphere.rst
nothing fancy, just fixed some typos
> fix: multiple typos of different importance

- sky/adaptors/kubernetes.py
- tests/test_config.py
> add custom objects api, fix test bug

- sky/server/common.py
> fix server healthcheck

- .github/workflows/docker-build.yaml
- .github/workflows/nightly-build.yml
- .github/workflows/release-build.yml
- .github/workflows/release-publish.yml
- Dockerfile
- Dockerfile_local
Reverts #5842 and #6127. We will follow up and make sure these get fixed and re-merge them.
> Revert changes to docker build

- sky/skypilot_config.py
> ephemeral engine for skypilot config

- charts/skypilot/templates/api-deployment.yaml
- charts/skypilot/values.yaml
- sky/server/server.py
- sky/skylet/constants.py
> allow customizing the API server auth header

- sky/server/common.py
> use os.replace to atomically write the cookies file

- sky/backends/backend_utils.py
Loop thru the records in the helper function instead of looping outside.
> minor refactor of get_clusters

- tests/test_api_compatibility.py
This PR fix the test failure introduced by https://github.com/skypilot-org/skypilot/pull/6105
Also the case is refined to avoid further regression
> Test: fix api compatibility test

- .github/workflows/nightly-build.yml
> [Dev] Move the nightly build earlier

- sky/global_user_state.py
- sky/jobs/state.py
Switches Postgres from pooling connections forever, to using a `NullPool` so connections are closed after being finished. This is due to the large number of processes sky pilot uses, eating into the maximum connection limit that postgres has.
Previous (master):
~20 jobs -> over 100 connections which is enough to fill up all connections on a local postgres.
Current (`NullPools`):
~20 jobs -> less than 10 connections. this will not fix the case where there are long running queries or a sudden large number of concurrent connections.
> [Core] Switch Postgres to use `NullPools`

- docs/source/reservations/reservations.rst
Follow up on #6110 
https://docs.skypilot.co/en/update-dws-docs/reservations/reservations.html#gcp-dynamic-workload-scheduler-dws
> [Docs] Update DWS doc

- .github/workflows/docker-build.yaml
Resolve #6172
Delete tag after creation
[test build log](https://github.com/zpoint/skypilot/actions/runs/16137045899/job/45535887046)
> Avoid intermediate docker tag in docker build pipeline 

- tests/smoke_tests/test_mount_and_storage.py
> Fix flaky for `test_ignore_exclusions`

- sky/jobs/state.py
> better codepath for get_managed_jobs

- sky/dashboard/src/components/clusters.jsx
Before Change:
After Change:
Overview:
This PR is to support multiple filters to the users.
> [UI] Update Search Bar in Clusters Page.

- sky/global_user_state.py
- sky/jobs/state.py
- tests/test_failover.py
- tests/test_global_user_state.py
- tests/test_jobs.py
- tests/test_jobs_and_serve.py
Close https://github.com/skypilot-org/skypilot/issues/6220
> Fix db init race condition

- sky/dashboard/src/components/clusters.jsx
- sky/dashboard/src/components/jobs.jsx
> [Dashboard] Tweak filter box style and layout

- charts/skypilot/values.yaml
- sky/__init__.py
Release 0.10.0
Buildkite Test Links:
- [Full Smoke Tests](https://buildkite.com/skypilot-1/full-smoke-tests-run/builds/42) - ✅ Success
- [Quicktest Core](https://buildkite.com/skypilot-1/quicktest-core/builds/643) - ✅ Success
- [Release Tests](https://buildkite.com/skypilot-1/release/builds/61) - ⏳ (not waiting for completion)
*Release Tests may take up to 24 hours to complete and might fail due to resource constraints.*
> Release 0.10.0

- examples/distributed-pytorch/train.yaml
Update dependency to fix test failure for test_min_gpt_kubernetes
> [Test] Fix test failure

- sky/dashboard/src/components/workspaces.jsx
> [Dashboard] Fix workspace aggregation for jobs

- docs/source/reference/kubernetes/examples/kueue-example.rst
- docs/source/reservations/reservations.rst
Update docs for DWS configuration to make it clear that which fields can be set in task yaml and which fields need to be set in config.yaml.
> [Doc] Update docs for DWS configuration

- docs/source/reference/api-server/examples/example-deploy-gke-nebius-okta.rst
- docs/source/reference/volumes.rst
Update example deploy doc for volumes
> [Doc] Update example deploy doc for volumes

- sky/dashboard/src/data/connectors/clusters.jsx
- sky/dashboard/src/data/connectors/jobs.jsx
- sky/dashboard/src/pages/clusters/[cluster]/[job].js
- sky/dashboard/src/pages/jobs/[job].js
- sky/jobs/server/core.py
> [UX] Git commit shows up on dashboard

- sky/jobs/utils.py
> [ManagedJobs] Add retry for job status fetch

- charts/skypilot/templates/api-deployment.yaml
- charts/skypilot/values.yaml
- docs/source/reference/api-server/api-server-admin-deploy.rst
- docs/source/reference/api-server/helm-values-spec.rst
Tested on an API server hosted on GKE.
> [Helm] Add vast support to helm chart

- docs/source/getting-started/installation.rst
- docs/source/reference/config.rst
- examples/oci/config.yaml
- sky/clouds/utils/oci_utils.py
- sky/utils/config_utils.py
- sky/utils/schemas.py
- tests/test_config.py
> [OCI] Standardize Configs

- README.md
- docs/source/cloud-setup/external-logging.rst
- docs/source/docs/index.rst
- docs/source/extension/linting.py
> [Docs] Add demo to docs and GH home; clean up external logging.

- .github/workflows/publish-helm.yml
- charts/skypilot/README.md
Use markdown format for the html contents in the chart readme
- GitHub action test for the final readme https://github.com/skypilot-org/skypilot/actions/runs/16548441694/job/46799685203
> [Chart] Use markdown format for the html contents in the chart readme

- sky/jobs/server/core.py
- sky/serve/server/core.py
- sky/utils/schemas.py
> move force_disable_cloud_bucket outside the `controller` field

- .github/workflows/publish-helm.yml
- charts/skypilot/README.md
> [Chart] Update chart readme

- sky/dashboard/package-lock.json
- sky/dashboard/package.json
- sky/dashboard/src/components/YamlHighlighter.jsx
- sky/dashboard/src/components/clusters.jsx
- sky/dashboard/src/hooks/useTour.js
- sky/dashboard/src/pages/clusters/[cluster].js
- sky/dashboard/src/pages/jobs/[job].js
> [Dashboard] YAML syntax highlighter.

- sky/jobs/state.py
- sky/jobs/utils.py
Show logs of all the tasks in a managed job. Fix https://github.com/skypilot-org/skypilot/issues/5399
> [Log] Show logs of all the tasks in a managed job

- docs/source/admin/workspaces.rst
- docs/source/reference/volumes.rst
Update docs for volume and workspace:
- Follow up https://github.com/skypilot-org/skypilot/pull/6400#issuecomment-3134594892
- Fix https://github.com/skypilot-org/skypilot/issues/6435
> [Doc] Update docs for volume and workspace

- examples/using_file_mounts_with_env_vars.yaml
- sky/backends/cloud_vm_ray_backend.py
- sky/global_user_state.py
- sky/jobs/server/core.py
- sky/serve/replica_managers.py
- sky/task.py
- sky/utils/dag_utils.py
- tests/smoke_tests/test_mount_and_storage.py
- tests/unit_tests/test_sky/backends/test_cloud_vm_ray_backend.py
- tests/unit_tests/test_sky/jobs/test_server_core_secrets.py
- tests/unit_tests/test_sky/test_task.py
- tests/unit_tests/test_sky/utils/test_dag_yaml_utils.py
> [Core] Fix secrets filling and redaction v2

- sky/data/data_utils.py
- sky/data/storage.py
Nebius is lacking cached mounts. This PR adds it.
> [Storage] Nebius add cached storage mount

- charts/skypilot/templates/api-deployment.yaml
> Fixed api server metrics config

- sky/server/daemons.py
- sky/sky_logging.py
> Fixed cluster status refresh daemon crash

- sky/templates/kubernetes-loadbalancer.yml.j2
Allows users to expose ports on CW clusters.
> [Coreweave] Fix annotation for public load balancer

- sky/client/cli/command.py
- tests/test_cli.py
> display GPU counts without .0 if the count is a whole number

- sky/dashboard/src/components/utils.jsx
- sky/dashboard/src/pages/clusters/[cluster]/[job].js
- sky/dashboard/src/pages/jobs/[job].js
- sky/skylet/log_lib.py
This PR adds support for rich progress bars in skypilot cluster jobs and managed jobs logs in the skypilot dashboard. Before this PR, rich progress bars would get printed on new lines as they got updated which makes for a poor UX. 
This PR was tested by running a test script with a simple for loop wrapped in tqdm. I verified by launching a cluster as well as a managed job and checked the logs to make sure that the tqdm progress bar was rendered properly. 
> [Dashboard ] rich progress bar support

- docs/source/cloud-setup/cloud-permissions/aws.rst
- docs/source/extension/linting.py
preview link: https://docs.skypilot.co/en/ssm-docs/cloud-setup/cloud-permissions/aws.html#using-aws-systems-manager-ssm
> [docs] example of setup with AWS SSM

- docs/source/examples/models/index.rst
- llm/gpt-oss/README.md
> [LLM] Lower case for gpt-oss

- README.md
- docs/source/docs/index.rst
https://docs.skypilot.co/en/docs-open/docs/index.html
> [Docs] Tweaks.

- docs/source/reservations/existing-machines.rst
As mentioned in comments to #6004 
> [Docs][SSH] Update SSH Infra Prereqs

- sky/task.py
While working on #6561, I noticed that there is a significant usecase for having multi-lined commands in task run or setup, as shown in our quickstart.
```
run: |
echo "Hello, SkyPilot!"
conda env list
```
To instantiate a `sky.Task` using the sdk, setting the run command is currently like so:
```
commands = [
'echo "Hello, SkyPilot!"',
'conda env list'
] 
task = sky.Task(setup='echo "Running setup."',
run='\n'.join(commands),
workdir='.')
```
Users should not have to manually call `join` to concatenate their commands. This PR allows users to submit multi-line commands as a list, and within `sky.Task`, the list will automatically be joined using `\n`.
```
commands = [
'echo "Hello, SkyPilot!"',
'conda env list'
] 
task = sky.Task(setup='echo "Running setup."',
run=commands, # note now we …
```
> [Core] Allow ingesting multiple commands for `Task`

- README.md
> [Docs] Fix the link to gpt-oss-finetuning

- sky/serve/serve_state.py
- sky/serve/server/impl.py
> [Serve][DB] SQLAlchemy support for sky serve database

- sky/schemas/db/serve_state/001_initial_schema.py
- sky/serve/serve_state.py
- sky/setup_files/alembic.ini
- sky/utils/db/migration_utils.py
- tests/unit_tests/test_hyperbolic.py
> [Serve][DB] Alembic support

- sky/client/cli/command.py
- sky/client/sdk.py
- sky/client/sdk_async.py
- sky/core.py
> [sdk] fix type issues

- sky/client/cli/command.py
- sky/jobs/utils.py
- sky/serve/serve_utils.py
> [Serve] Add consolidation mode change validation

- .github/workflows/release-build.yml
- .github/workflows/release-publish.yml
> Use PAT token for release publish

- sky/catalog/data_fetchers/fetch_nebius.py
Update VRAM calculation in Nebius fetcher
Fix https://github.com/skypilot-org/skypilot/issues/6622
run fetch
> [Nebius] Update VRAM calculation in Nebius fetcher

- sky/backends/backend_utils.py
- sky/backends/cloud_vm_ray_backend.py
> Add comment to clarify grpcio lazy imports

- sky/client/cli/command.py
> [Pool] Fix pool cli

- examples/admin_policy/example_policy/example_policy/skypilot_policy.py
- sky/client/cli/command.py
- sky/client/sdk.py
- sky/core.py
- sky/schemas/api/responses.py
- sky/server/requests/serializers/decoders.py
- sky/server/requests/serializers/encoders.py
- sky/server/server.py
- sky/utils/cli_utils/status_utils.py
> [sdk] better type definition for status response

- sky/setup_files/MANIFEST.in
- sky/skylet/ray_patches/__init__.py
- sky/skylet/ray_patches/autoscaler.py.diff
- sky/skylet/ray_patches/cli.py.diff
- sky/skylet/ray_patches/command_runner.py.diff
- sky/skylet/ray_patches/log_monitor.py.diff
- sky/skylet/ray_patches/resource_demand_scheduler.py.diff
- sky/skylet/ray_patches/updater.py.diff
- sky/skylet/ray_patches/worker.py.diff
Patch ray files with python module
> [Core] Patch ray files with python module

- charts/skypilot/templates/rbac.yaml
Fixed formatting in `charts/skypilot/templates/rbac.yaml` to make `helm lint` happy.
> charts: fix rbac.yaml to make helm lint happy

- docs/source/_static/custom.js
- docs/source/_templates/layout.html
> [Docs] Improve doc tags

- sky/users/permission.py
Optimize logs for permission module. Fix #6496
> [Log] Optimize logs for permission module

- README.md
- docs/source/docs/index.rst
- docs/source/overview.rst
> [Docs] Some touches.

- docs/source/reference/api.rst
- sky/client/sdk.py
> [docs] add endpoints to sky sdk doc

- sky/clouds/nebius.py
> [Clouds] Add memory to nebius

- sky/__init__.py
Release 0.10.2
Buildkite Test Links:
- [Full Smoke Tests](https://buildkite.com/skypilot-1/full-smoke-tests-run/builds/65) - ✅ Success (~~except for #6843 and #6872~~ Both of them passed after a lot retries)
- [Quicktest Core](https://buildkite.com/skypilot-1/quicktest-core/builds/1020) - ✅ Success
- [Smoke Tests Remote Server Kubernetes](https://buildkite.com/skypilot-1/smoke-tests/builds/2816) - ✅ Success
- [Quicktest Core (vs Previous Minor)](https://buildkite.com/skypilot-1/quicktest-core/builds/1019) - ✅ Success
- [Release Tests](https://buildkite.com/skypilot-1/release/builds/86) - ✅ Success (except for flacky 24 spot test)
*Release Tests may take up to 24 hours to complete and might fail due to resource constraints.*
> Release 0.10.2

- sky/backends/backend_utils.py
> correct regex expression for duplicate event matching

- sky/backends/backend.py
- sky/backends/backend_utils.py
- sky/backends/cloud_vm_ray_backend.py
- sky/backends/local_docker_backend.py
- sky/core.py
- sky/global_user_state.py
> [k8s] do not delete events on cluster down

- sky/global_user_state.py
- sky/schemas/db/global_user_state/007_cluster_event_request_id.py
- sky/utils/db/migration_utils.py
This will allow us to trace state changes back to the corresponding request, which may help get additional logs etc.
> [events] add request_id column

- docs/source/getting-started/installation.rst
> [docs] update installation docs for python 3.13 support

- docs/source/examples/spot-jobs.rst
- docs/source/examples/spot/bert_qa.rst
- docs/source/examples/spot/lightning_cifar10.rst
- docs/source/examples/spot/resnet.rst
- docs/source/examples/vector_database.rst
- docs/source/gallery/tutorials/finetuning.rst
- docs/source/llm/vicuna.rst
- docs/source/llm/vicuna/train.rst
- docs/source/serving/service-yaml-spec.rst
> [Docs] Add redirects from dead links.

- README.md
- docs/source/docs/index.rst
- docs/source/getting-started/installation.rst
Minor edits in installation page
1. Fix title structure:
This PR
master:
3. Add nebius managed k8s
> [Docs] minor changes to the installation page

- docs/source/cloud-setup/cloud-permissions/nebius.rst
- docs/source/reference/config.rst
- sky/clouds/nebius.py
- sky/provision/nebius/instance.py
- sky/provision/nebius/utils.py
- sky/templates/nebius-ray.yml.j2
- sky/utils/schemas.py
Add support for static IP configuration in Nebius cloud
run several VMs and chek type of IP
> [Nebius] Add support for static IP configuration in Nebius cloud

- sky/server/daemons.py
It's a similar rationale as https://github.com/skypilot-org/skypilot/blob/a5750884dc37f2134ae8d1ddacc247d12d8fa74e/sky/server/requests/executor.py#L413-L422 - and it couldn't possibly hurt.
> [core] kill subprocesses after each daemon run

- docs/source/getting-started/installation.rst
> [Docs] Fix Together URL

- sky/__init__.py
Release 0.10.3
Buildkite Test Links:
- [Full Smoke Tests](https://buildkite.com/skypilot-1/full-smoke-tests-run/builds/70) - ✅ Success(except for `test_gcp_network_tier_with_gpu` due to availability issue and `test_cancel_pytorch` on azure fixed by https://github.com/skypilot-org/skypilot/pull/7047/commits/44a3e40bae1da7395748ff28d8a9dd0fb580f678)
- [Quicktest Core](https://buildkite.com/skypilot-1/quicktest-core/builds/1148) - ✅ Success
- [Smoke Tests Remote Server Kubernetes](https://buildkite.com/skypilot-1/smoke-tests/builds/3106) - ✅ Success
- [Quicktest Core (vs Previous Minor)](https://buildkite.com/skypilot-1/quicktest-core/builds/1147) - ✅ Success
- [Release Tests](https://buildkite.com/skypilot-1/release/builds/90) - ⏳ (not waiting for completion)
*Release Tests may take up to …
> Release 0.10.3

- .pre-commit-config.yaml
- requirements-dev.txt
- sky/backends/backend_utils.py
- sky/clouds/aws.py
- sky/data/storage.py
- sky/jobs/utils.py
- sky/provision/aws/config.py
- sky/provision/gcp/config.py
- sky/server/requests/serializers/encoders.py
- sky/server/server.py
- sky/utils/command_runner.pyi
- sky/volumes/volume.py
mypy 1.17 drops support for python 3.8, so this is the latest version that works.
I did this to get python/mypy#15896, which will allow us to properly typecheck context_utils.to_thread.
> [dev] update mypy to 1.14.1

- tests/load_tests/simulated_workload.py
- tests/load_tests/test_ssh_proxy.py
- tests/load_tests/workload_benchmark.py
- tests/load_tests/workloads/basic.sh
Benchmark the API server with concurrent load.
```bash
python tests/load_tests/workload_benchmark.py -t 8 -r 10 -s workloads/basic.sh --cloud kubernetes
```
New workload can be added via bash script.
> Concurrent workload load test script

- sky/utils/controller_utils.py
> do not enable high_availability for things that are not controllers

- tests/test_optimizer_random_dag.py
workaround https://github.com/skypilot-org/skypilot/issues/7187
> Workaround non-canonicalized L40S GPU name

- docs/source/reference/faq.rst
Update faq for private git repo
> [Doc] Update faq for private git repo

- sky/logs/agent.py
- sky/logs/aws.py
- sky/utils/yaml_utils.py
- tests/smoke_tests/test_aws_logs.py
Adding a [regex parser](https://docs.fluentbit.io/manual/data-pipeline/parsers/regular-expression) to the fluent-bit config for external logging. 
parses the ray log lines into:
- `worker_name`: the first part of the line `head`, `worker{n}`, or the task name (there might be a more descriptive name than `worker_name`, not sure what)
- `rank`: for multiple ranks
- `pid`: process id
- `ip`: ip of the worker
- `log_line`: the actual line being logged
Also checking for a prior installation of fluent-bit properly, and checking for an existing fluent-bit process to make sure there's only one process.
tested launching a cluster:
```bash
$ sky launch -c "fluent-parser-test" --image-id ubuntu:noble -n "parser-test" --num-nodes 2 --cpus 1 --memory 2 -d --infra k8s -y 'echo this should be logged; …
```
> [logs] Add regex parser for fluent-bit, make aws add to parent config

- sky/logs/agent.py
- sky/logs/aws.py
- sky/utils/yaml_utils.py
- tests/smoke_tests/test_aws_logs.py
Reverts skypilot-org/skypilot#7135.
Caused test_log_collection_to_gcp to fail.
See #7233.
> Revert "[logs] Add regex parser for fluent-bit, make aws add to parent config"

- tests/smoke_tests/test_cluster_job.py
> Fix `test_min_gpt`

- docs/source/reservations/existing-machines.rst
> [Docs] Fix Typo

- .github/workflows/test-doc-build.yml
- docs/source/conf.py
> [Docs] Align the test with the readthedocs.yml

- sky/backends/cloud_vm_ray_backend.py
- sky/execution.py
- sky/global_user_state.py
- sky/jobs/server/core.py
- sky/jobs/utils.py
- sky/serve/replica_managers.py
- sky/serve/serve_utils.py
- sky/server/requests/preconditions.py
- sky/utils/controller_utils.py
> [db] Misc. cluster fetching efficiency improvements

- sky/backends/backend_utils.py
- sky/global_user_state.py
> add workspaces filter to cluster glob matching query

- tests/unit_tests/test_sky/server/requests/test_process.py
> Make disposble pool UT robust

- tests/smoke_tests/test_pools.py
> [Pool] Skip test_vllm_pool.

- Dockerfile
- tests/smoke_tests/docker/Dockerfile_test
This PR adds the session manager plugin needed for AWS SSM into the skypilot dockerfile. I built this locally to ensure installation works.
> [Core] Add Session Manager Plugin to Dockerfile

- sky/dashboard/src/components/clusters.jsx
- sky/dashboard/src/data/connectors/clusters.jsx
- sky/global_user_state.py
> [Dashboard] Add time range drop down for cluster history

- examples/training/torchtitan/README.md
> [Example] Fix torchtitan example

- tests/load_tests/db_scale_tests/run_scale_test.py
```
❯ python tests/load_tests/db_scale_tests/run_scale_test.py --test jobs \
--managed-job-id 1
Starting Scale Test
============================================================
Test mode: jobs
Using sample data:
Active cluster: scale-test-active
Terminated cluster: scale-test-terminated
Managed job ID: 1
============================================================
3. Testing Managed Jobs (10000 jobs)
------------------------------------------------------------
Injecting 10000 test managed jobs...
Total injected: 10000 managed jobs
Testing get_managed_jobs (raw DB query):
get_managed_jobs: 20001 jobs in 0.194s
Rate: 103315 jobs/sec
Testing get_managed_job_queue (filtering + enrichment):
get_managed_job_queue: 20001 jobs in 4.331s
Rate: 4618 jobs/sec
Testing load_managed_job_queue (JSON …
```
> [tests] add fine grained benchmarks for bottlenecks in jobs queue code path

- sky/clouds/cudo.py
> [cudo] fix import check

- docs/source/robots.txt
Previous robots.txt changes have caused problems with Google search of our docs.
> [Docs] robots.txt: allow Googlebot.

- addons/fuse-proxy/pkg/server/server.go
Add success/error logging when closing fusermount-server file descriptor to let users know if things worked properly or not.
Untested.
> Log file description close event in fuse-proxy

- sky/utils/db/migration_utils.py
1. Make the logging level debug
2. Only emit the log from the API server, not client
> migration utils log hygiene
