sky/serve/service_spec.py

Our autoscaling metric `target_qps_per_replica` should be a positive number. This PR adds a check on the constraint.
```yaml
service:
readiness_probe: /
replica_policy:
min_replicas: 2
max_replicas: 10
target_qps_per_replica: -2.5 # also tested with 0
resources:
ports: 5000
```
```bash
$ sky serve up neg-tar-qps.yaml
Service from YAML spec: neg-tar-qps.yaml
ValueError: target_qps_per_replica must be greater than 0
```

[SkyServe] Check positive for `target_qps_per_replica`

---

docs/source/index.rst
docs/source/serving/autoscaling.rst
docs/source/serving/service-yaml-spec.rst
docs/source/serving/sky-serve.rst

[Docs][SkyServe] Autoscaling doc for SkyServe

---

docs/source/running-jobs/distributed-jobs.rst

Distributed jobs will result in `OSError: [Errno 24] Too many open files` unless ulimit is increased. I put a note in the instructions incase others run into this issue.

Update distributed-jobs.rst to address ulimit issue

---

sky/setup_files/setup.py

The direct reference causes error in our pypi release: https://github.com/skypilot-org/skypilot/actions/runs/7638977430

[Dependency] Remove direct reference for sphere

---

sky/clouds/azure.py

To reproduce:
1. `sky launch -c test --gpus A100-80GB:2`; ctrl-c immediately after the cluster is INIT.
2. `sky launch -c test` again.

[Azure] Fix empty string for status query

---

llm/mixtral/README.md
llm/mixtral/serve.yaml
sky/templates/azure-ray.yml.j2
sky/templates/gcp-ray.yml.j2
tests/test_smoke.py

Fixes #2905
Fix mixtral example for Azure by removing the problemetic nccl config file on Azure.
With this PR, after #2434 is merged, we should be able to change the examples to `disk_tier: best`, so that Azure is allowed to be part of the candidates.

[LLM] Fix mixtral example for Azure

---

docs/source/examples/docker-containers.rst

Previously, our hint for only support Debian-based containers was hard to spot. This PR added a sentence for that.

[Doc] Highlight debian-based image in docker as runtime env doc

---

sky/clouds/gcp.py

[GCP] Ignore missing gcp credentials

---

sky/resources.py
sky/utils/accelerator_registry.py

[Minor] Improve completion of accelerator name when cloud is specified

---

sky/clouds/scp.py

To reproduce: in an environment that does not have scp credentials, run `sky check`:
```bash
$ sky check
Checking SCP...Traceback (most recent call last):
File "/home/txia/miniconda3/envs/skyserve/bin/sky", line 8, in <module>
File "/home/txia/miniconda3/envs/skyserve/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
File "/home/txia/miniconda3/envs/skyserve/lib/python3.9/site-packages/click/core.py", line 1078, in main
File "/home/txia/skypilot/sky/utils/common_utils.py", line 315, in _record
File "/home/txia/skypilot/sky/cli.py", line 1219, in invoke
File "/home/txia/miniconda3/envs/skyserve/lib/python3.9/site-packages/click/core.py", line 1688, …
```

[BugFix] Fix SCP error raised in `sky check`

---

docs/source/index.rst
docs/source/serving/update.rst

[SkyServe] Update Documentation

---

sky/backends/cloud_vm_ray_backend.py
sky/provision/gcp/instance_utils.py
sky/setup_files/setup.py
tests/test_smoke.py

Fixes #3027
The `bulkInsert` API fails to create VMs using `machineImage` along with disk parameter override, as it does a check for the source of the disk, which should not be applied when `machineImage` is specified (bug of GCP API).
This PR makes it fallback to the regular `insert` API instead to support the creation of instances using machine image.
rojects/skypilot-375900/global/machineImages/test-machine-image --disk-size 256 --cpus 2 --num-nodes 4`, successfully create the cluster

[GCP] Fix machine image for cluster creation

---

sky/backends/backend_utils.py
sky/provision/runpod/instance.py

Errors during fetching IP should correctly raise an error, which is important for `sky down`.
Fixes #3029

[Core] Make the IP fetch more robust

---

docs/source/serving/autoscaling.rst
docs/source/serving/update.rst

Before
```
SkyServe: Model Serving
[Serving Models](https://skypilot.readthedocs.io/en/latest/serving/sky-serve.html)
[Service YAML](https://skypilot.readthedocs.io/en/latest/serving/service-yaml-spec.html)
[Autoscaling](https://skypilot.readthedocs.io/en/latest/serving/autoscaling.html)
[Scale-to-Zero](https://skypilot.readthedocs.io/en/latest/serving/autoscaling.html#scale-to-zero)
[Updating a Service](https://skypilot.readthedocs.io/en/latest/serving/update.html)
[Example](https://skypilot.readthedocs.io/en/latest/serving/update.html#example)
```
Now
```
SkyServe: Model Serving
[Serving Models](https://github.com/skypilot-org/skypilot/compare/serving/sky-serve.html)
[Service YAML](https://github.com/skypilot-org/skypilot/compare/serving/service-yaml-spec.html) …
```

[Docs] Minor: fix header levels

---

sky/provision/docker_utils.py
sky/resources.py
sky/skylet/providers/command_runner.py
sky/task.py

Previously, when we `sky serve up` a yaml w/ docker login config, it will throw an error saying `DockerLoginConfig is not JSON serializable`, which is because we accidentally added the docker login to resources' `to_yaml_config` function. This PR addressed the problem and fixed #2982 .
```yaml
service:
readiness_probe: /
replicas: 1
resources:
cloud: aws
cpus: 2
image_id: docker:txia-test-ecr:latest
ports: 5000
envs:
SKYPILOT_DOCKER_USERNAME: AWS
SKYPILOT_DOCKER_PASSWORD: <password here>
SKYPILOT_DOCKER_SERVER: <uid>.dkr.ecr.us-east-1.amazonaws.com
run: |
echo $SKYPILOT_DOCKER_USERNAME
python -m http.server 5000
```
```bash
$ sky serve up docker_login_service.yaml
Service from YAML spec: docker_login_service.yaml
Service Spec:
Readiness probe method:           GET /v1/models
Readiness …
```

[SkyServe] Fix `sky serve up` with docker login config

---

sky/backends/backend_utils.py
sky/execution.py
sky/serve/__init__.py
sky/serve/constants.py
sky/serve/core.py
sky/serve/serve_utils.py
sky/skylet/constants.py

In the SkyServe PR, we exposed the `_execute` api for the call in `sky/serve/core.py`. This PR changes it back and calling `sky.launch` instead.

[Core][Serve] Hide `execute` api from `sky.execution`

---

llm/codellama/README.md

Old URL to tabby vscode extension does not work. Fixed and added a line on where to configure the endpoint.

[Docs] Fix Tabby dead URL in codellama guide

---

sky/backends/backend_utils.py

The current implementation does not add the `Include ~/.sky/generated/ssh/*` in users' `~/.ssh/config` if the config file does not have any lines with `Host` in it.
Fixes #3065 

[Core] Make sure the `Include ~/.sky/generated/ssh/*` is added in `~/.ssh/config` for empty config

---

sky/clouds/azure.py

To reproduce:
```bash
$ sky launch --cloud azure
Clusters
NAME                           LAUNCHED        RESOURCES                                                 STATUS   AUTOSTOP  COMMAND                       
sky-ccca-txia                  a few secs ago  1x Azure(Standard_D8s_v5, disk_tier=medium)               INIT     -         sky launch --cloud azure
```

[Provisioner] Fix Azure disk tier explicitly shown in resources str

---

sky/provision/aws/instance.py

A user encountered an issue where the AWS cluster takes a long time (>40 mins) to raise the no capacity issue when restarting a STOPPED cluster. This PR mitigates the problem by adding more logs when we are waiting an instance that is in STOPPING state and fail fast for the restart with capacity issue.

[AWS] More logging for restarting an instance in STOPPING state and fail fast for the restart

---

sky/clouds/service_catalog/common.py

This pertains to https://github.com/skypilot-org/skypilot/issues/2863, and updates previous PR https://github.com/skypilot-org/skypilot/pull/2892
Minor update to fix the sorting issue mentioned by @concretevitamin  https://github.com/skypilot-org/skypilot/pull/2892#issuecomment-1872572086
```
sky show-gpus V100 --all-regions                                                                                             ─╯
*NOTE*: for most GCP accelerators, INSTANCE_TYPE == (attachable) means the host VM's cost is not included.
GPU   QTY  CLOUD   INSTANCE_TYPE       DEVICE_MEM  vCPUs  HOST_MEM  HOURLY_PRICE  HOURLY_SPOT_PRICE  REGION
V100  1    AWS     p3.2xlarge          16GB        8      61GB      $ 3.060       $ 1.024            us-west-2
V100  1    AWS     p3.2xlarge          16GB …
```

Minor update to sort by price in show-gpus

---

sky/provision/instance_setup.py
sky/provision/provisioner.py
sky/utils/subprocess_utils.py

Fixes #3002. This should be compatible with #3004.

[Provisioner] Reduce parallelism for file mounts based on fd limit

---

docs/source/serving/autoscaling.rst
docs/source/serving/service-yaml-spec.rst

[Docs] Minor: change heading level.

---

sky/provision/azure/instance.py

On the latest master branch when we provisioned an Azure cluster w/ ports, it printed out a lots of logs and corrupted the CLI. This PR fixed the issue.

[UX] Suppress azure logs when opening ports

---

sky/clouds/service_catalog/gcp_catalog.py

The current price order for GCP in `sky show-gpus` is incorrect, because:
1. The VM price used for the total price is the cheapest one across all regions instead of the current region.
2. We only sort the price before combining the price of VM and GPUs. This PR re-sort the price/spot price after combining GPU and host VM price.
It also fixes #2953.
Before this PR
```
sky show-gpus v100:1 --cloud gcp --all-regions
GPU   QTY  CLOUD  INSTANCE_TYPE  DEVICE_MEM  vCPUs  HOST_MEM  HOURLY_PRICE  HOURLY_SPOT_PRICE  REGION        
V100  1    GCP    n1-highmem-8   -           8      52GB      $ 2.953       $ 0.811            asia-east1    
V100  1    GCP    n1-highmem-8   -           8      52GB      $ 2.953       $ 1.013            us-central1   
V100  1    GCP …
```

[UX] Fix GCP show-gpus order after combining VM types

---

sky/task.py
tests/skyserve/llm/service.yaml

Fixes https://github.com/skypilot-org/skypilot/issues/3048

[Serve] Support env var in service yaml

---

docs/source/reference/config.rst
docs/source/reference/kubernetes/index.rst
examples/serve/http_server/task.yaml

Updates our config documentation for `pod_config` to include more common jobs-to-be-done - setting pod-wide environment variables and adding volume mounts. 
Adding these examples is important because users may often make errors while adding these fields, so something they can copy-paste is easier to use.

[k8s][docs] Add `containers` example to pod_config example

---

docs/source/reference/config.rst
sky/utils/schemas.py

The `security_group_name` feature was accidentally removed when we added the schema check for `~/.sky/schemas.py`. This PR is to add it back and fixes user requests in #1354.
```yaml
aws:
security_group_name: launch-wizard-7
```

[AWS] Add security_group_name back

---

llm/vllm/serve-openai-api.yaml
llm/vllm/serve.yaml
llm/vllm/service.yaml

This is to simplify the dependencies for the vllm examples.

[LLM] Update dependencies for vllm example

---

sky/clouds/service_catalog/data_fetchers/fetch_gcp.py

Fixes #3136
GCP recently added the on-demand price for the hidden TPUs in us-east1-d  in their SKU, but not spot prices, which causes the failure of our fetching fail due to the assertion we have in the fetcher.

[Catalog] Fix gcp fetch for tpu with none price

---

README.md
docs/source/index.rst

Adding missing LLMs in docs (sync with readme)

[Docs] Adding LLMs in docs

---

sky/backends/backend_utils.py
sky/backends/cloud_vm_ray_backend.py
sky/clouds/azure.py
sky/provision/instance_setup.py
sky/templates/azure-ray.yml.j2
sky/templates/ibm-ray.yml.j2
sky/templates/lambda-ray.yml.j2
sky/templates/oci-ray.yml.j2
sky/templates/scp-ray.yml.j2
sky/utils/common_utils.py

Fixes #3129
This PR also raises proper error for the case when Azure have an invalid state string. Fixes #3134

[Core] Wait `ray status` to be ready

---

sky/clouds/cudo.py
sky/clouds/service_catalog/cudo_catalog.py

[show-gpus] Fix catalog API call for cudo compute

---

sky/execution.py
sky/resources.py

As mentioned in #3125, previously SkyPilot would not print correct ports not supported message if the resources has no cloud specified, and all enabled cloud has no ports support. This PR fixes the problem.
```bash
(base) root@26a1fb705d3d:/sky_repo/skypilot# SKYPILOT_DEBUG=0 sky serve up ../a.yaml 
Service from YAML spec: ../a.yaml
ValueError: Cannot specify ports without enabling a cloud that supports open ports.
```

[Provisioner] Check ports for cloud not specified cases

---

sky/authentication.py
sky/backends/backend_utils.py
sky/provision/kubernetes/instance.py
sky/provision/provisioner.py
sky/provision/vsphere/common/custom_script.py
sky/skylet/log_lib.py

We now explicitly set the permission for the ssh config file writen by SkyPilot, because sometimes if the user changed the username of their local machine, and still use the conda environment with skypilot installed under the old `/home/old-user` folder. In this case, the files writen to `~/.sky/generated/ssh` can have a permssion `dwxr-rw-rw--` which violates the permission required for ssh, causing all `ssh` fails.
This is one of the potential reasons for #2689. This PR also prints out the output of the last ssh command if the wait ssh timeout.
Reproducible steps:
1. `docker run -it --rm centos:centos7 /bin/bash`
2. `adduser -m test-original; adduser -m test-new`
3. `passwd test-original; passwd test-new`
4. `sermod -aG wheel test-new; sermod -aG wheel test-original`
5. `su …

[Core] Set file permission when writing the ssh config file

---

sky/cli.py

Closes #3061. Allows purging of serve controller if cluster identity mismatch happens (common on k8s).
Still shows the prompt and requires user to enter 'delete'. 
Blocked on #3093 and #3043 for full functionality on k8s. 
```
$ sky down sky-serve-controller-2ea485ea --purge
sky.exceptions.ClusterOwnerIdentityMismatchError: 'sky-serve-controller-2ea485ea' (Kubernetes) is owned by account ['gke_skypilot-375900_us-central1-c_gkeusc2_gke_skypilot-375900_us-central1-c_gkeusc2-skypilot-sa_default'], but the activated account is ['gke_skypilot-375900_us-central1-c_gkeusc2_gke_skypilot-375900_us-central1-c_gkeusc2_default'].
Since --purge is set, errors will be ignored and controller will be removed from local state.
To proceed, please type 'delete':
```

[Serve] Allow purging controller for identity mismatch

---

sky/check.py
sky/provision/vsphere/vsphere_utils.py
sky/utils/subprocess_utils.py

Changes
- Show a nicer table at the end, since now we have many clouds and it's hard to see what's enabled.
- Check clouds in alphabetical order
- Changed colors
- `sky check` then `sky launch --down -y --use-spot --cpus 2`
- `sky check -v`

[UX] `sky check`: show enabled clouds in a table

---

sky/clouds/kubernetes.py

[k8s] Use KUBECONFIG envvar to specify kubeconfig path

---

sky/serve/constants.py
sky/serve/core.py
sky/serve/serve_utils.py

The service initialization timeout is confusing with `initial_delay_seconds`. This PR rephrased to `failed to register service` to avoid such confusion.
```bash
$ sky serve up @temp/serve.yaml 
Service from YAML spec: @temp/serve.yaml
Service Spec:
Readiness probe method:           GET /
Readiness initial delay seconds:  1200
Replica autoscaling policy:       Fixed 1 replica        
Each replica will use the following resources (estimated):
I 02-17 07:55:20 optimizer.py:691] == Optimizer ==
I 02-17 07:55:20 optimizer.py:702] Target: minimizing cost
I 02-17 07:55:20 optimizer.py:714] Estimated cost: $0.4 / hour
I 02-17 07:55:20 optimizer.py:714] 
I 02-17 07:55:20 optimizer.py:837] Considered resources (1 node):
I 02-17 07:55:20 optimizer.py:907] …
```

[UX] Rephrase service initialization timeout

---

sky/check.py

[minor] Allow sky check to set enabled_clouds to empty

---

sky/cli.py

When multiple ports are opened, `sky status --endpoint 8888 <cluster>` would fail. This is because the `handle.launched_resources.ports` contains a str like `'8888-8889'`. We need to convert to a set of ints and then compare in our code.
Repro:
```
resources:
ports:
- 8888
- 8889
run: |
python -m http.server 8888 & python -m http.server 8889;
```
```
$ sky status --endpoint 8889 mycluster
ValueError: Port 8889 is not exposed on cluster 'test'.
$ sky status --endpoint 8889 mycluster
34.67.101.159:8889
```
FYI - code paths for endpoints are refactored out of cli.py in #3109.

[Core] Fix for `sky status --endpoints` when a range of ports is opened

---

docs/source/reference/kubernetes/kubernetes-setup.rst
sky/provision/kubernetes/network_utils.py

On some on-prem clusters, ingresses may be exposed through a NodePort service that is backed by a custom external-ip set by the cluster admin. We should return this ip when queries through `sky status --endpoints` instead of returning `localhost`.
This PR adds support for reading external-ip if it is set. Also updates docs for clarity on how to use nginx ingress.
```
$ sky status --endpoints test
8888: http://localhost:30008/skypilot/test-2ea4/8888
$ sky status --endpoints test
8888: http://192.156.211.1:30008/skypilot/test-2ea4/8888 
$ sky status --endpoints test
8888: http://localhost:30008/skypilot/test-2ea4/8888 
```
This is also helpful for skyserve on nginx ingress, since `localhost` is not accessible from the skyserve controller.
Cherry-picking this change from #3109 for v0.5 …

[K8s] Use external-ip if configured on nginx ingress

---

tests/test_smoke.py

Smoke tests seem broken on the current master:
```
$ pytest tests/test_smoke.py::test_minimal
_________________________________________________________________________________________________________________________________________________________________________________ test_minimal _________________________________________________________________________________________________________________________________________________________________________________
[gw0] darwin -- Python 3.9.13 /Users/romilb/tools/anaconda3/bin/python
tests/test_smoke.py:281: in test_minimal
run_one_test(test)
tests/test_smoke.py:161: in run_one_test
proc.wait(timeout=test.timeout)
../../../../tools/anaconda3/lib/python3.9/subprocess.py:1187: in wait
endtime = _time() + timeout
E   TypeError: unsupported operand …
```

[Tests] Fix `_get_timeout` in smoke tests

---

sky/clouds/kubernetes.py

Our current custom image text parsing for k8s uses `lstrip` incorrectly. The arg to lstrip specifies a set of characters, not a string. As a result, any image starting with the letters d,o,c,k,e,r or a permutation of docker gets parsed incorrectly:
```
>>> "rayproject/ray".lstrip('docker:')
'ayproject/ray'
```
Tested with the `sky launch` this YAML:
```
resources:
image_id: docker:rayproject/ray:2.4.0-py310-cpu
```

[k8s] Fix custom image parsing 

---

llm/codellama/endpoint.yaml
llm/mixtral/README.md
llm/mixtral/serve.yaml
llm/vllm/serve-openai-api.yaml
llm/vllm/serve.yaml
llm/vllm/service.yaml
sky/task.py
sky/templates/aws-ray.yml.j2
tests/skyserve/llm/service.yaml

`sky launch -c test-mixtral --use-spot ./llm/mixtral/serve.yaml`
It fail to work with our current master, due to the failure of accessing `"https://aws-ml-conda-ec2.s3.us-west-2.amazonaws.com"` when running `conda create`.
Fixes #3195

[AWS/LLM] Remove the conda channel that is not working on AWS and fix dependencies in LLMs

---

sky/data/mounting_utils.py

Fixes `test_aws_custom_image` for #3211.
On certain images, chmod +x on `/usr` doesn't work:
e.g. on [ami-062ddd90fb6f8267a](https://aws.amazon.com/marketplace/pp/prodview-rf7na2b2ttvdg)
```
(base) ubuntu@ip-172-31-4-126:~/.sky$ sudo chmod 700 /usr/local/bin/goofys
(base) ubuntu@ip-172-31-4-126:~/.sky$ ls -lah /usr/local/bin/goofys
-rwx------ 1 root root 28M Apr  6  2022 /usr/local/bin/goofys
(base) ubuntu@ip-172-31-4-126:~/.sky$ sudo chmod +x /usr/local/bin/goofys
(base) ubuntu@ip-172-31-4-126:~/.sky$ ls -lah /usr/local/bin/goofys
-rwx------ 1 root root 28M Apr  6  2022 /usr/local/bin/goofys # Didn't work
(base) ubuntu@ip-172-31-4-126:~/.sky$ sudo chmod 755 /usr/local/bin/goofys
(base) ubuntu@ip-172-31-4-126:~/.sky$ ls -lah /usr/local/bin/goofys
-rwxr-xr-x 1 root root 28M Apr  6  2022 …
```

[Storage] Storage mounting tool permissions fix

---

sky/backends/backend_utils.py
sky/backends/cloud_vm_ray_backend.py
sky/provision/docker_utils.py
sky/skylet/providers/command_runner.py
sky/templates/aws-ray.yml.j2
sky/templates/azure-ray.yml.j2
sky/templates/gcp-ray.yml.j2
tests/test_smoke.py

`pytest tests/test_smoke.py::test_job_queue_with_docker --azure` fails because `ray cluster` fail to start on the remote machine. Logs: https://gist.github.com/Michaelvll/4528e47faa9a008e1b204ea8b6873947
The main reason is that the `docker pull` fails due to the docker daemon not ready when the cluster is just up, and our retry in cloud_vm_ray_backend tries `ray up` again with `--no-restart` passed, which causes the ray cluster fail to start due to some bug in ray.
https://github.com/skypilot-org/skypilot/blob/ad755dfa7e96d4d049a301440c0ffefe8f7b2eb4/sky/backends/cloud_vm_ray_backend.py#L1832-L1843
In this PR, we retry the `docker pull` when the cluster is just up, so it does not error out and trigger that retry.
Future TODO:

[Docker] Add retry for docker pull due to daemon not ready

---

sky/__init__.py

Release 0.5.0

---

sky/serve/core.py

Originally the SkyServe does not allow multiple resources using different cloud. This PR fixed the issue.

[Serve] Enable multiple cloud in resources

---

sky/clouds/gcp.py

Our previous way for ignoring the application key is problemetic, as we will raise a `FileNotFoundError` when calling `self._find_application_key_path()` and the key file is not found, i.e., the later `if os.path.exists(os.path.expanduser(application_key_path)):` does not help for ignoring the credential file.

[GCP] fix application key upload

---

sky/templates/gcp-ray.yml.j2

Fixes #3235 
We have some missing configurations for launching spot instances on GCP with machine image, which seems caused by the API update of GCP.
Note: all the configs added are required to make spot work with machine image.
```yaml
resources:
cloud: gcp
region: us-west1
image_id: projects/skypilot-xxxx/global/machineImages/test-machine-image
cpus: 2+
memory: 4+
disk_size: 256
use_spot: true
num_nodes: 2
```
```yaml
resources:
cloud: gcp
region: us-west1
cpus: 2+
memory: 4+
disk_size: 256
use_spot: true
num_nodes: 2
```

[GCP] Fix spot with machine image

---

docs/source/serving/autoscaling.rst

https://github.com/skypilot-org/skypilot/pull/3194#discussion_r1496952029

[Serve] [Doc] Add a tip for retry mechanism in scale-to-zero

---

llm/gemma/serve.yaml

Minor fix for gemma transformers requirement: https://github.com/huggingface/transformers/releases/tag/v4.38.1

[LLM] Fix gemma's transformer version

---

sky/cli.py
sky/skylet/autostop_lib.py
sky/skylet/constants.py
tests/test_smoke.py

[UX] Reset autostop timer whenever autostop config changes on remote machine

---

Dockerfile
llm/qwen/README.md
llm/qwen/gui.yaml
llm/qwen/serve-72b.yaml
llm/qwen/serve-7b.yaml

```
curl -L http://$IP:8000/v1/chat/completions     -H "Content-Type: application/json"     -d '{
"model": "Qwen/Qwen1.5-72B-Chat",
"messages": [
{
"role": "system",
"content": "You are a helpful and honest chat expert."
},
{
"role": "user",
"content": "What is the best food?"
}
],
"max_tokens": 512
}' | jq -r '.choices[0].message.content'
```

[LLM] Add example for Qwen

---

sky/clouds/fluidstack.py

`norway_2_eu` VMs on fluidstack seem to use `ubuntu` username instead of `fsuser`.
Tested:
March 2 9:20a PT - Unable to test as fluidstack seems to be having issues provisioning on norway_2_eu (stuck on `customizing`). Was working as of 9a. Will test when it's back up.

[fluidstack] Fix norway_2_eu username for fluidstack

---

sky/utils/kubernetes/k8s_gpu_labeler_setup.yaml

Currently, a `RTX A6000` gets labelled as `A6000`, which is a different card. This further causes confusion when the user tries to run `sky launch --gpus a6000` as prompted by `sky local up` output:
```
...
Local Kubernetes cluster created successfully with 8 CPUs and 1 a6000 GPUs. `sky launch` can now run tasks locally.
$ sky launch --gpus a6000
ValueError: Accelerator name 'a6000' is ambiguous. Please choose one of ['A6000', 'RTXA6000'].
```
with this PR, the naming for RTX series card is aligned with runpod, fluidstack and other clouds' catalogs. 
* RTX A6000 - `RTXA6000`
* Nvidia Geforce RTX 4090 - `RTX4090`
etc.

[k8s] Fix GPU labelling nomenclature

---

sky/clouds/gcp.py
sky/clouds/service_catalog/data_fetchers/fetch_gcp.py
sky/clouds/service_catalog/gcp_catalog.py

Fixes #3150 and https://github.com/skypilot-org/skypilot-catalog/issues/63

[GCP] Support H100 for GCP

---

docs/source/cloud-setup/cloud-permissions/gcp.rst
sky/clouds/gcp.py
sky/provision/gcp/config.py
sky/provision/gcp/constants.py

We now skip the check for `iam.serviceAccounts.actAs` to make sure a user with more fine grained permission setup (only allowing the user to use `skypilot-v1` permission) could work.
This is requested by an organization user.

[GCP] Skip checking for `iam.serviceAccounts.actAs`

---

sky/backends/cloud_vm_ray_backend.py
sky/cli.py
sky/core.py

User found the previous docstr confusing
> When calling sky.down, do you recommend setting purse=True? Since these clusters are running on ephemeral cloud machines, I want to make sure that all clusters are killed at the end of the task, no matter what.
Semantics of `--purge` does not mean "no matter what". This PR updates the docstr.

[Docs] Clarify `--purge` in `sky down`, `sky.down`, `sky.stop`

---

sky/provision/runpod/utils.py

[RunPod] Fix multi-gpu provisioning.

---

sky/authentication.py

This is to avoid the racing condition when multiple spot, services or launch run concurrently on a new environemnt. Previously, it is possible that two process generates the public key and private key concurrently causing unmatched keys. For example,
1. process 1 writes private key
2. process 2 writes private key
3. process 2 writes public key
4. process 1 writes public key
This PR adds a lock for the key generation to avoid this race condition

[Core] Avoid race condition for key generation

---

sky/clouds/fluidstack.py
sky/provision/fluidstack/__init__.py
sky/provision/fluidstack/instance.py
sky/utils/controller_utils.py

[Fluidstack] Support opening ports and service

---

.github/workflows/pytest.yml
sky/backends/backend_utils.py
sky/cli.py
sky/core.py
sky/serve/core.py
sky/sky_logging.py
sky/spot/spot_utils.py
sky/utils/command_runner.py
sky/utils/command_runner.pyi
sky/utils/controller_utils.py
tests/test_spot.py
tests/test_spot_serve.py

Fixes #1592, #3285
TODO:
- ```for i in `seq 1 100`; do sky spot launch -n test-$i --cloud gcp --cpus 2 -y -d "echo hi; sleep 120"; done```; during the submission

[Serve/Spot] Allow spot queue/cancel/logs during controller INIT state

---

sky/serve/serve_state.py

I encourtered issues with service db locked, like the following
```
E 03-12 05:28:23 subprocess_utils.py:84]   File "<string>", line 1, in <module>
E 03-12 05:28:23 subprocess_utils.py:84]   File "/opt/conda/lib/python3.10/site-packages/sky/serve/serve_utils.py", line 451, in wait_service_registration
E 03-12 05:28:23 subprocess_utils.py:84]     record = serve_state.get_service_from_name(service_name)
E 03-12 05:28:23 subprocess_utils.py:84]   File "/opt/conda/lib/python3.10/site-packages/sky/serve/serve_state.py", line 311, in get_service_from_name
E 03-12 05:28:23 subprocess_utils.py:84]     rows = _DB.cursor.execute('SELECT * FROM services WHERE name=(?)',
E 03-12 05:28:23 subprocess_utils.py:84] sqlite3.OperationalError: database is locked
```
This PR adopts the `safe_cursor` we used …

[Serve] Use `safe_cursor` for serve state

---

docs/source/getting-started/installation.rst
sky/backends/backend_utils.py
sky/backends/cloud_vm_ray_backend.py
sky/setup_files/setup.py

In rare cases, the spot controller can stay in INIT state with autostop column reset after `sky status` as the spot job queue fetcher can refresh the controller status when it is autostopping and not stopped yet.
Since our previous code does not refresh status again when the controller is in INIT state and autostop column resetted. This PR fixes this issue, so that when the user run `sky status` twice the controller will be shown STOPPED. 

[Core] Refresh for spot controller in INIT status

---

docs/source/running-jobs/distributed-jobs.rst

Docs: Added warning in documentation against installing Ray in base environment

Docs: Add warning against installing Ray in base environment

---

sky/clouds/azure.py
sky/templates/azure-ray.yml.j2

Fixes #3310
We now manually add `--num-gpus` for starting ray cluster on the MV, to make sure the GPUs are considered.

[Azure] Add num_gpus for ray status

---

sky/provision/kubernetes/network.py
sky/provision/kubernetes/network_utils.py
sky/templates/kubernetes-ingress.yml.j2

Each ingress rule creation triggers a hot reload of the nginx controller. Since previously SkyPilot generates the listed ingresses sequentially, this could lead to multiple reloads of the Nginx-Ingress-Controller within a brief period. 
Consequently, the Nginx-Controller pod might spawn an excessive number of sub-processes. This surge triggers Kubernetes to kill and restart the Nginx due to the `podPidsLimit` parameter, which is typically set to a default value like 1024, and thus disrupts normal request handling.
This PR fixes this issue by batching ingress creation into one object containing multiple rules. 

[k8s] Optimize ingress creation to avoid nginx hot-reloads

---

docs/source/cloud-setup/cloud-permissions/gcp.rst
sky/clouds/utils/gcp_utils.py
sky/provision/gcp/constants.py
sky/provision/gcp/instance_utils.py

This PR moves the reservation permission into the optional list, as users without the reservations set in `config.yaml` will not need to have the reservation permissions.
It also fixes #3327.

[GCP] Docs for GCP reservation permission and fix auto reservation

---

sky/provision/kubernetes/instance.py

Closes #3320. Our parsing for k8s envvars -> ssh envvars would break if the envvar value contained equals signs or spaces. This PR fixes it. 
Example, if the env is set as `ENV GIT_SSH_COMMAND="ssh -o HostKeyAlgorithms=+ssh-rsa -o PubkeyAcceptedKeyTypes=+ssh-rsa"`.
Before, our custom envs script would contain:
```
...
export GIT_SSH_COMMAND=ssh -o HostKeyAlgorithms
...
```
After (handles equals sign, adds quotes to handle spaces):
```
...
export GIT_SSH_COMMAND="ssh -o HostKeyAlgorithms=+ssh-rsa -o PubkeyAcceptedKeyTypes=+ssh-rsa"
...
```

[k8s] Fix for spaces and equals signs in docker env vars

---

sky/backends/backend_utils.py
sky/backends/cloud_vm_ray_backend.py
sky/clouds/aws.py
sky/execution.py
sky/provision/instance_setup.py
sky/serve/serve_utils.py
sky/skylet/attempt_skylet.py
sky/skylet/autostop_lib.py
sky/skylet/constants.py
sky/skylet/job_lib.py
sky/skylet/log_lib.py
sky/spot/spot_utils.py
sky/templates/azure-ray.yml.j2
sky/templates/gcp-ray.yml.j2
sky/templates/ibm-ray.yml.j2
sky/templates/lambda-ray.yml.j2
sky/templates/oci-ray.yml.j2
sky/templates/scp-ray.yml.j2
sky/templates/spot-controller.yaml.j2
tests/test_smoke.py
tests/test_yamls/test_custom_default_conda_env.yaml

Fixes #3324 
master ([823999a](https://github.com/skypilot-org/skypilot/commit/823999af850ee93138f45d01abba6c54a93d3c1e))
`for i in {1..5}; do time sky launch -c test-gcp-$i --cloud gcp --cpus 2 -y; done`
```
1m59.195s
2m0.108s
1m56.507s
1m54.553s
1m54.242s
```
mean: 1m56.921s
This PR ([39daf35](https://github.com/skypilot-org/skypilot/pull/3326/commits/39daf35d26e235bd84bb209c9f63df358294f8fb)):
`for i in {1..5}; do time sky launch -c test-gcp-$i --cloud gcp --cpus 2 -y; done`
```
1m53.456s
2m7.647s
1m55.891s
1m59.496s
2m7.193s
```
mean: 2m0.7366s (3.8156s overhead)
```yaml
resources:
cpus: 2+
setup: |
conda activate myenv
if [ $? -ne 0 ]; then
conda create -n myenv python=3.10 -y
conda activate myenv
fi
grep -qxF 'conda activate myenv' ~/.bashrc || echo …
```

[Core] Use original Python path for SkyPilot runtime

---

sky/skylet/constants.py

Fixes #3335 
The issue was caused by the ray package in our kubernetes default image being installed in `~/.local/bin` instead of the same dir as python `/opt/conda/bin` which is likely due to some write permission issue. We now use the original ray path by saving the executable path in a file.

[Core] Use original ray path instead of using python dir for ray path

---

examples/tensorflow_distributed/tf_distributed.yaml
llm/vicuna/train.yaml

`SKYPILOT_JOB_ID` envvar was deprecated after v0.5. This PR updates examples in our repo to use the new `SKYPILOT_TASK_ID` envvar instead.
Tested:

[examples] Update examples using deprecated `SKYPILOT_JOB_ID `

---

docs/source/running-jobs/environment-variables.rst

Was showing: `:widths: 20 70 10 :header-rows: 1` in https://skypilot.readthedocs.io/en/latest/running-jobs/environment-variables.html#environment-variables-for-run

[Docs] Fix misaligned table; mention task logs.

---

.github/workflows/test-doc-build.yml
docs/build.sh
docs/source/conf.py

Add CI test for documentation build failure. 

[Tests] Add CI test for doc build

---

Dockerfile_k8s
Dockerfile_k8s_gpu
tests/test_smoke.py

[k8s] Update k8s docker image to use ray 2.9.3

---

docs/source/reference/config.rst
sky/authentication.py
sky/backends/backend_utils.py
sky/provision/kubernetes/network.py
sky/provision/kubernetes/utils.py
sky/templates/kubernetes-ssh-jump.yml.j2
sky/utils/schemas.py

Closes #3317. Adds the ability to attach custom metadata to all objects created by SkyPilot. Useful for accounting and management of SkyPilot specific resources.

[k8s] Attach custom metadata to objects created by SkyPilot

---

sky/provision/docker_utils.py
tests/test_smoke.py

Storage mounting was not working when running inside a docker container on the new provisioner. This PR fixes it and adds smoke tests.
Minimal repro:
```
resources:
cloud: gcp
image_id: docker:ubuntu:latest
file_mounts:
/mymnt:
source: s3://fah-public-data-covid19-cryptic-pockets #romileubucket2
mode: MOUNT
/mynotebooks:
source: gs://romilb-notebooks/ #romileubucket2
mode: MOUNT
setup: |
echo hi
run: |
ls -l /mynotebooks
ls -l /mymnt
echo run > /mynotebooks/hellotest.txt
```

[docker] Add /dev/fuse for mounting containers in docker

---

sky/serve/autoscalers.py
sky/serve/service_spec.py

Fixes #3359
1. Autoscaling enabled
```yaml
service:
readiness_probe:
path: /health
initial_delay_seconds: 20
replica_policy:
min_replicas: 1
max_replicas: 2
target_qps_per_replica: 1
```
```bash
$ sky serve up -n http @temp/svc.yaml
Service from YAML spec: @temp/svc.yaml
Service Spec:
Readiness probe method:           GET /health
Readiness initial delay seconds:  20
Replica autoscaling policy:       Autoscaling from 1 to 2 replicas with Target 1 QPS/replica
Spot Policy:                      No spot policy
```
2. Error (`target_qps_per_replica` not set)
```yaml
service:
readiness_probe:
path: /health
initial_delay_seconds: 20
replica_policy:
min_replicas: 1
max_replicas: 2
```
```bash
$ sky serve up -n http @temp/svc.yaml
Service from YAML spec: …
```

[UX][Serve] More comprehensive `target_qps_per_replica` check

---

sky/data/data_utils.py
sky/data/storage.py
sky/task.py
tests/test_smoke.py

Closes #3114. Uses the optimizer's `best_resources` or the the tasks' resource spec to infer the region for the bucket, if available.
Note that currently the bucket is eagerly provisioned in the first region that will be tried by the provisioner. If failover is trigerred, the bucket and compute may lie in a different region. A better fix could have been to make store init lazy and create the bucket in the region where the VM actually gets provisioned, but that requires deeper changes + considerations on wasted VM time while data is uploaded to the object store.
TODO:
Tested:

[Storage] Use task's region for initializing new stores

---

.github/workflows/pypi-nightly-build.yml

When the nightly build experience a temporary failure (eg network issue), and we retry the CI/CD, it could fail as the file could already exist on testpypi (though not exists on pypi). 
This PR adds `skip-existing: true` to ignore the error for existing file on the remote repo.
Reference:
First attempt: https://github.com/skypilot-org/skypilot/actions/runs/8466029811/attempts/1
second attempt: https://github.com/skypilot-org/skypilot/actions/runs/8466029811/attempts/2

[pypi] Allow existing file on pypi

---

sky/check.py

Cloud implementations may misbehave and throw exceptions up to `check.check()`. This blocks `sky check` from running on other clouds, and can often be hard to fix without disabling the cloud by moving files around/uninstalling dependencies. Examples:
* #3385
* OCI - if the path specified in `key_file` in `~/.oci/config` does not exist
* ...
This PR adds a broad exception catch to sky check to catch unexpected failures and gracefully fail by show the traceback as the reason for cloud disable.
Example:
```
AWS: enabled
Azure: enabled
Cloudflare, for R2 object store: disabled
Reason: [r2] profile is not set in ~/.cloudflare/r2.credentials. Additionally, Account ID from R2 dashboard is not set. Run the following commands:
$ pip install boto3 …
```

[core] Prevent clouds from blocking `sky check`

---

llm/dbrx/README.md
llm/dbrx/dbrx.yaml

Adds Kubernetes and other clouds (azure, paperspace, fluidstack) to optimizer table by showing on-demand instances.
`cpus` and `memory` are added to better select pod shape for Kubernetes.

[Examples] Update DBRX example for on-demand instances

---

sky/clouds/service_catalog/data_fetchers/fetch_gcp.py

Previously, `DEVICE_MEM` is missing in `sky show-gpus` GCP results. This was because GCP APIs didn't explicitly return such info.
Now:
```console
» sky show-gpus L4:1 --cloud gcp
GPU  QTY  CLOUD  INSTANCE_TYPE  DEVICE_MEM  vCPUs  HOST_MEM  HOURLY_PRICE  HOURLY_SPOT_PRICE  REGION
L4   1    GCP    g2-standard-4  24GB        4      16GB      $ 0.705       $ 0.248            us-east4
» sky show-gpus A100:1 --cloud gcp
GPU   QTY  CLOUD  INSTANCE_TYPE  DEVICE_MEM  vCPUs  HOST_MEM  HOURLY_PRICE  HOURLY_SPOT_PRICE  REGION
A100  1    GCP    a2-highgpu-1g  40GB        12     85GB      $ 3.673       $ 1.469            us-central1
GPU        QTY  CLOUD  INSTANCE_TYPE   DEVICE_MEM  vCPUs  HOST_MEM  HOURLY_PRICE  HOURLY_SPOT_PRICE  REGION   
A100-80GB  1    GCP    a2-ultragpu-1g  80GB        12 …
```

[UX/Catalog] Add DEVICE_MEM info to GCP GPUs.

---

sky/check.py
sky/clouds/cloud.py
sky/clouds/runpod.py
sky/execution.py
sky/task.py

RunPod does not support storage mounting since the container is not run in privileged mode (or with CAP_SYS_ADMIN). As a result, `/dev/fuse` is not available inside the container and goofys/gcsfuse cannot function.
For a user, this reflects very late into their workflow when mounting fails after provisioning.
This PR adds `CloudImplementationFeatures.STORAGE_MOUNTING` to provide early failover for clouds which don't support mounting.
```
I 03-28 15:25:27 optimizer.py:690] == Optimizer ==
I 03-28 15:25:27 optimizer.py:701] Target: minimizing cost
I 03-28 15:25:27 optimizer.py:713] Estimated cost: $0.3 / hour
I 03-28 15:25:27 optimizer.py:713] 
I 03-28 15:25:27 optimizer.py:836] Considered resources (1 node):
I 03-28 15:25:27 optimizer.py:906] …
```

[Storage] Add CloudImplementationFeature for Storage Mounting

---

docs/source/reference/yaml-spec.rst
sky/adaptors/azure.py
sky/clouds/azure.py
sky/clouds/service_catalog/azure_catalog.py
sky/provision/azure/instance.py
sky/resources.py
tests/test_optimizer_dryruns.py
tests/test_smoke.py

This PR adds support for custom images on Azure. Partially fixes #2910.
Related: skypilot-org/skypilot-catalog#66

[Core] Support custom image on Azure

---

sky/clouds/aws.py
sky/provision/aws/instance.py
sky/templates/aws-ray.yml.j2

A user reported that when the security group is specified in `~/.sky/config.yaml`, SkyPilot still tries to delete the security group when terminating the cluster.

[AWS] Do not delete user-specified security group

---

sky/clouds/cloud.py
sky/clouds/kubernetes.py
sky/execution.py

Adds `CloudImplementationFeatures.HOST_CONTROLLERS` to check if a cloud supports hosting controllers. cc #3377 #3363
Example output with `spot.controller.resources.cloud: Kubernetes` in config.yaml:
```
(base) ➜  sky-experiments git:(core_host_controllers) ✗ sky spot launch --cloud gcp -- echo hi
Task from command: echo hi
Managed spot job 'sky-cmd' will be launched on (estimated):
I 04-02 09:18:00 optimizer.py:690] == Optimizer ==
I 04-02 09:18:00 optimizer.py:701] Target: minimizing cost
I 04-02 09:18:00 optimizer.py:713] Estimated cost: $0.1 / hour
I 04-02 09:18:00 optimizer.py:713] 
I 04-02 09:18:00 optimizer.py:836] Considered resources (1 node):
I 04-02 09:18:00 optimizer.py:906] --------------------------------------------------------------------------------------------------
I …
```

[Core] Add `HOST_CONTROLLERS` check for clouds 

---

sky/clouds/lambda_cloud.py
sky/skylet/providers/lambda_cloud/node_provider.py

This includes the `terminating` status for Lambda Cloud, and `non_terminated_nodes` should filter out the terminating and terminated nodes.
`sky launch -c test-lambda --cloud lambda --gpus A10; sky down test-lambda`
Error out with:
```
File "/home/azureuser/skypilot/sky/clouds/utils/lambda_utils.py", line 183, in remove_instances
response = _try_request_with_backoff(
File "/home/azureuser/skypilot/sky/clouds/utils/lambda_utils.py", line 118, in _try_request_with_backoff
raise_lambda_error(response)
File "/home/azureuser/skypilot/sky/clouds/utils/lambda_utils.py", line 95, in raise_lambda_error
raise LambdaCloudError(f'{code}: {message}')
sky.clouds.utils.lambda_utils.LambdaCloudError: global/unknown: An unknown error occurred.
```

[Lambda] Fix termination for lambda

---

docs/source/reference/config.rst
sky/clouds/kubernetes.py
sky/provision/kubernetes/instance.py
sky/utils/schemas.py

Autoscaling clusters or clusters with admission control may require tweaking the provisioning timeout. This PR adds support for that by adding `kubernetes.provision_timeout` field to ~/.sky/config.yaml.

[k8s] Add `provision_timeout` to config for k8s provisioning

---

sky/provision/paperspace/instance.py

Resolves #3416 
`sky stop` now runs properly for Paperspace VMs
```
sky launch --cloud paperspace -c test
sky stop test
```

[Paperspace] hotfix stop

---

sky/clouds/aws.py
sky/clouds/service_catalog/common.py
tests/test_optimizer_random_dag.py

The newly included g6 instances in AWS fails the optimizer test, as there is no on-demand price (but only spot price) for that instance. Removing it from the test for now to let the CI pass.

[Tests] Fix test for g6 instance type

---

sky/skypilot_config.py

If the user's `SKYPILOT_CONFIG` does not point to a file, currently, it will just slient go through without any message. We should error out as it is likely unintentional.

[Core] Error out for a non-exist SKYPILOT_CONFIG

---

Dockerfile_k8s
Dockerfile_k8s_gpu

This is to improve the dependency installation by pinning the version of the dependencies.
master: `for i in `seq 1 5`; do sky launch -y -c test-dep-$i --cloud kubernetes --cpus 1 echo hi; done`
```
1m21s
1m19s
1m22s
1m22s
1m24s
```
avg: 1m21.6s
this PR: `for i in `seq 1 5`; do sky launch -y -c test-dep-$i --cloud kubernetes --cpus 1 echo hi; done`
```
1m20s
1m27s
1m18s
1m20s
1m17s
```
avg: 1m20.4s

[kubernetes] Add curl and other dependencies in k8s image

---

sky/__init__.py
sky/backends/backend_utils.py
sky/cli.py
sky/core.py
sky/execution.py
sky/spot/__init__.py
sky/spot/core.py
sky/utils/command_runner.py
sky/utils/common_utils.py
sky/utils/controller_utils.py
sky/utils/dag_utils.py
tests/backward_compatibility_tests.sh

This PR refactors spot APIs `core.spot_xxx` into `spot.xxx`.
Closes #3283
Blocking #3419

[Spot] Refactor spot APIs into `spot.xxx`

---

sky/clouds/azure.py
sky/clouds/gcp.py

This is a bug introduced by #3362 , where the code assume `image_id` is always of format `<publisher>:<offer>:<sku>:<version>` but ignore the case of docker image as runtime environment.
To reproduce:
```bash
$ sky launch --cloud azure --image-id docker:ubuntu:20.04
I 04-18 18:55:57 optimizer.py:693] == Optimizer ==
I 04-18 18:55:57 optimizer.py:704] Target: minimizing cost
I 04-18 18:55:57 optimizer.py:716] Estimated cost: $0.4 / hour
I 04-18 18:55:57 optimizer.py:716] 
I 04-18 18:55:57 optimizer.py:839] Considered resources (1 node):
I 04-18 18:55:57 optimizer.py:909] ----------------------------------------------------------------------------------------------
I 04-18 18:55:57 optimizer.py:909]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN …
```

[Core][BugFix] Fix docker runtime env on Azure

---

sky/task.py

The error message specifically states that upper case letters are allowed, but the regex previously did not allow them.
Allow uppercase letters in task names

Allow uppercase letters in task names

---

sky/resources.py

Fixes #3456 
```python
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sky
>>> sky.Resources().to_yaml_config()
{'disk_size': 256}
```

[Core][BugFix] Remove extra field `_require_fuse` in `Resources.to_yaml_config()`

---

sky/clouds/service_catalog/oci_catalog.py

~~Fixes #3462~~
~~The problem is caused by we setting the controller resources with an empty resource field when no cloud is specified.~~
#3462 should be fixed in #3363.
This PR now only fixes the issue where OCI is imported even if the user does not have it enabled. This is introduced by #3394.
This can affect all new users of SkyServe who don't have OCI setup.

[Dependency] Fix the lazy import failure for OCI

---

sky/backends/cloud_vm_ray_backend.py
sky/resources.py
sky/utils/schemas.py

We should add the internal configs to the `schemas.py` to make sure managed spot and serving can load the dumped task with those internal configs set.

[Core] Add internal configs in schema.py to avoid spot job and serve failure

---

tests/test_smoke.py

[Tests] Fix docker test to avoid using python 3.12

---

sky/utils/controller_utils.py

The previous code fetch the controller record with the wrong name causing the controller fail to use the same resources when starting a service/spot job when the controller already exists.
To reproduce:
1. Have a serve controller on AWS
2. `sky serve up --cloud gcp ...`
The service launching command will fail with the following error:
```
sky.exceptions.ResourcesMismatchError: Requested resources do not match the existing cluster.
Requested:    {1x GCP(cpus=4+, disk_size=200, ports=['30001-30100'])}
Existing:     1x AWS(m6i.xlarge, disk_size=200, ports=['30001-30100'])
```

[Spot/Serve] Fix controller resources fetching

---

sky/clouds/service_catalog/data_fetchers/fetch_fluidstack.py
sky/provision/fluidstack/fluidstack_utils.py

* Add A100-80GB and H100 Nvlink accelerator mappings
* Remove custom/configurable plans
*Changes Description*
- New gpu types mapped to Skypilot types
- Removed unsupported custom plans
*Tests ran*
`sky launch` 
`python sky/clouds/service_catalog/data_fetchers/fetch_fluidstack.py` 
- [* ] Code formatting: `bash format.sh`
- [* ] Any manual or new tests for this PR (please specify below)
* `sky launch`

[FluidStack] Add Nvlink Accelerator Mappings

---

sky/skylet/events.py
sky/skylet/job_lib.py

The periodic job status update was accidentally dropped due to the job queue scheduling. This will cause job failed in `ray job` failed to be set to `FAILED` but stuck in RUNNING.
The following could reproduce the issue:
1. `git reset --hard 1bdc` (the commit before the fix for the ray.wait timeout, #3460)
2. Add `timeout=600` for `ray.wait` to simulate the issue in `cloud_vm_ray_backend.py`
3. `sky serve up -n test-index-recover-2 examples/serve/http_server/task.yaml --cloud gcp`
After 10 mins, the serve controller job fails, but the service is shown `READY` forever, and `sky queue sky-serve-controller-<hash>` shows the controller job is running, while `ray job list` shows the job is failed already on the controller VM.

[Core] skylet periodically update job status

---

sky/task.py
sky/utils/common_utils.py
tests/test_yaml_parser.py

To reproduce:
```yaml
envs:
- my_env1: abc
- my_env2: abc
- my_env3: abc
```
`sky launch -c test task.yaml`
```
AttributeError: 'list' object has no attribute 'update'
```
With this PR:
```
ValueError: Invalid task YAML: [{'my_env1': 'abc'}, {'my_env2': 'abc'}, {'my_env3': 'abc'}] is not of type 'dict'. Check problematic field(s): $.envs
```

[UX] Fix task schema check for env

---

sky/utils/controller_utils.py

Fixes an issue introduced by #3476, where we access storage_mounts with the key that does not exist.

[Spot/Serve] Fix file mount translate

---

sky/skylet/providers/azure/node_provider.py

A user reported that when launching a spot Azure VM, it is possible that a state code does not contain `/` which causes the following error:
```
File "/home/azureuser/miniconda3/lib/python3.10/site-packages/sky/skylet/providers/azure/node_provider.py", line 105, in <listcomp>
nodes = [self._extract_metadata(vm) for vm in filter(match_tags, vms)]
File "/home/azureuser/miniconda3/lib/python3.10/site-packages/sky/skylet/providers/azure/node_provider.py", line 119, in _extract_metadata
code, state = status["code"].split("/")
ValueError: too many values to unpack (expected 2)
```
We now add a handling for this special case.

[Provisioner] make azure state check more robust

---

sky/provision/docker_utils.py
sky/skylet/providers/command_runner.py
tests/test_smoke.py

Fixes issue introduced in #3436, as some cloud's default images do not have `/etc/docker/daemon.json` by default, which causes the following error, during initializing docker image
```
E 04-25 19:02:45 subprocess_utils.py:84] jq: error: Could not open file /etc/docker/daemon.json: No such file or directory
E 04-25 19:02:45 subprocess_utils.py:84] Job for docker.service failed because the control process exited with error code.
E 04-25 19:02:45 subprocess_utils.py:84] See "systemctl status docker.service" and "journalctl -xe" for details.
E 04-25 19:02:45 subprocess_utils.py:84] 
E 04-25 19:02:54 subprocess_utils.py:84] Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

[Core] Fix docker in image_id

---

README.md
docs/source/_gallery_original/index.rst
docs/source/_gallery_original/llms/qwen.md
docs/source/_static/custom.js
docs/source/docs/index.rst
llm/qwen/README.md
llm/qwen/gui.yaml
llm/qwen/serve-110b.yaml

Updates qwen docs to include 110B. Also fixes the GUI which was not working due to missing fields in model_info and old version of openai. 
Serve section still uses 72b because the terminal outputs shown in the readme include a diversity of hardware (L4, A100-80GB), which is untested on 110B.

[Examples] Add qwen-110B and fix GUI

---

sky/templates/aws-ray.yml.j2
sky/templates/gcp-ray.yml.j2

This PR updates jinja2 ray templates for gcp and aws when utilizing Tags.
Currently, boolean strings are inserted into the Ray YAML without being escaped. This fixes that by using the builtin `tojson` function for jinja2.
Otherwise, tags which had the values: `false` or `true` would fail to launch.
* AWS launch with tags which which include values of `false` and `true` set in the `~/.sky/config.yaml` `aws.instance_tags` section

[Core] Bug fix for Tag Values representing booleans being loaded as boolean instead of strings

---

sky/setup_files/setup.py

Since ray is now changed its releasing loop to be every week, we now remove the upper bound of ray to avoid blocking users to use higher version of ray locally. (This relies on ray's backward compatibility)

[Dependency] Remove the upper bound for ray in setup

---

docs/source/reference/config.rst
sky/provision/kubernetes/network.py
sky/provision/kubernetes/network_utils.py
sky/provision/kubernetes/utils.py
sky/utils/kubernetes_enums.py

Adds a `podip` mode for exposing ports on Kubernetes clusters. This is useful when the ports need to only be internally accessible from within the Kubernetes cluster and user wants to reduce the number of svcs running.
Since ports exposed using `podip` are not accessible from outside the cluster, we are not adding this mode to our main docs for now. Only covered in the config.yaml documentation, can add to main docs based on demand. 
Added after feedback from user.
Tested manually with `sky launch -c test2 --cloud kubernetes --ports 8888 -- 'python -m http.server 8888'` -> `sky status --endpoints test2` -> Access endpoint from within cluster.

[k8s] Add podip mode support for exposing ports

---

sky/provision/kubernetes/instance.py

Our current k8s multi-node implementation enforces strict pod anti-affinity requirements. As a result, if your Kubernetes cluster contains a single physical node, SkyPilot cannot launch multi-node jobs even though logically multiple pods can fit on the node. Notably, this is contrary to the inline code comments.
Repro - `sky local up` then try `sky launch -c clus --num-nodes 2 --cpus 1`. This will fail to get scheduled even though the cluster has enough resources.
This PR changes the pod anti-affinity to be a soft requirement.  Multi-node SkyPilot pods are now spread across nodes when possible, but can still be placed on the same node if resources are unavailable on other nodes.

[k8s] Use soft constraints on pod anti-affinity for multi-node tasks

---

sky/clouds/kubernetes.py
tests/unit_tests/test_resources.py

Fixes label validation for Kubernetes, where it was not accepting the `kueue.x-k8s.io/queue-name` label as valid. Also added unit tests to make sure validators are tested.

[Core] Fix label validation for Kubernetes, add unit tests

---

sky/provision/paperspace/constants.py

Paperspace disabled some older Ubuntu 22.04 MLiaB image defaults we had for certain instances which prevented users from being able to launch images for the higher end GPU instances such as A100 and H100. This updates these images accordingly. Resolves #3498 

[Paperspace] Update machine images

---

sky/utils/kubernetes/create_cluster.sh

User shared bug report on slack:
```
No kind clusters found.
Generating /tmp/skypilot-kind.yaml
Creating cluster "skypilot" ...
• Ensuring node image (kindest/node:v1.21.1) 🖼  ...
✓ Ensuring node image (kindest/node:v1.21.1) 🖼
• Preparing nodes 📦   ...
✓ Preparing nodes 📦 
• Writing configuration 📜  ...
✓ Writing configuration 📜
• Starting control-plane 🕹️  ...
✓ Starting control-plane 🕹️
• Installing CNI 🔌  ...
✓ Installing CNI 🔌
• Installing StorageClass 💾  ...
✓ Installing StorageClass 💾
Set kubectl context to "kind-skypilot"
You can now use your cluster with:
kubectl cluster-info --context kind-skypilot
Have a nice day! 👋
Kind cluster created.
Enabling GPU support...
ln: failed to create symbolic link '/sbin/ldconfig.real': File exists
```
Kind node may have ldconfig.real already …

[k8s] `sky local up` gpu support - ignore if ldconfig.real already exists

---

sky/benchmark/benchmark_utils.py

Smoke test `test_sky_bench` had been failing with:
```
File "/opt/conda/bin/sky", line 8, in <module>
File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1078, in main
File "/home/gcpuser/.sky/file_mounts/sky_repo/sky/utils/common_utils.py", line 354, in _record
File "/home/gcpuser/.sky/file_mounts/sky_repo/sky/cli.py", line 805, in invoke
File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File …
```

[Tests] Fix benchmark smoke test `test_sky_bench`

---

docs/source/reference/config.rst
sky/backends/backend_utils.py
sky/clouds/aws.py
sky/templates/aws-ray.yml.j2
sky/utils/schemas.py

This PR updates the schema config to allow specification of IAM roles for resources based on the skypilot naming conventions.
Address: https://github.com/skypilot-org/skypilot/issues/3487
In `~/.sky/config.yaml`:
* When setting for the controller and all other resources (`default`)
```yaml
aws:
remote_identity:
sky-serve-controller-*: skypilot-v1-fake
"*": skypilot-default-fake
```
* When setting for everything by specifying a default
```yaml
aws:
remote_identity:
"*": skypilot-default-fake
```
* When setting for everything by specifying just the `remote_identity` via string
```yaml
aws:
remote_identity: skypilot-default-fake
```
* When first profile doesn't match it chooses the next in line if viable
```yaml
aws:
remote_identity:
does-not-match: skypilot-default-fake
"*": …
```

[Core][AWS] Allow specification of IAM roles for resources.

---

docs/source/reference/config.rst
sky/cli.py
sky/clouds/kubernetes.py
sky/provision/kubernetes/utils.py
sky/utils/kubernetes_enums.py
sky/utils/schemas.py

Adds `autoscaler` field to config.yaml to allow the user to specify the autoscaler used in the underlying kubernetes cluster:
```
kubernetes:
autoscaler: gke/karpenter/generic
```
Setting this field:
1. Disables gpu capacity checks during provisioning
2. Uses the appropriate label formatter for specifying GPU labels
When used in conjunction with `provision_timeout`, this allows users to bring in their scale-to-zero k8s clusters and use them with SkyPilot.
Currently supported autoscalers: GKE nodepools, Karpenter, any generic CA that can label new nodes with `skypilot.co/accelerator` (Related - https://github.com/skypilot-org/skypilot/issues/3432)
More context: https://docs.google.com/document/d/17LRYGCKDsY9AygAJbUIiQR4KkHZqSakL8G0SF7WNOR8/edit?usp=sharing

[k8s] Add support for autoscaling kubernetes clusters

---

docs/source/reference/config.rst
sky/backends/backend_utils.py
sky/skypilot_config.py
sky/utils/schemas.py

Fix the syntax for the AWS IAM profile introduced in #3488, so that the wildcard matching will follow the order the user specified.
from 
```yaml
aws:
remote_identity:
my-cluster1-*: my-service-account1
my-cluster2-*: my-service-account2
```
to
```yaml
aws:
remote_identity:
- my-cluster1-*: my-service-account1
- my-cluster2-*: my-service-account2
```
```yaml
jobs:
controller:
resources:
cloud: aws
aws:
remote_identity:
- sky-jobs-controller-*: SERVICE_ACCOUNT
- "*": ray-autoscaler-v1
```

[AWS] Fix config syntax for IAM profile

---

sky/backends/cloud_vm_ray_backend.py

[Core] Allow a very long user program

---

.gitignore
sky/clouds/aws.py

Prior to this PR, ECS containers could not launch skypilot jobs because as the type is considered: `container-role` as opposed to `iam-role` when evaluating `aws configure list`.
This PR:
* Allows ECS container assumed iam credentials to be found by adding the `CONTAINER_ROLE` value to the `AWSIdentityType`.
* adds `.env` to the .gitignore 
* Evaluated `sky check` w/o the update in an ECS container (failed)
* Evaluated running  `sky up ...` w/o the update in an ECS container (failed)
* Evaluated `sky check` w/ the update in an ECS container (passed)
* Evaluated running  `sky up ...` w/ the update in an ECS container (passed)

[Core][AWS] Allow assumption of AWS Credentials provided in ECS Containers

---

sky/skylet/autostop_lib.py
sky/skylet/providers/azure/config.py
sky/skylet/providers/azure/node_provider.py

This is to reduce the autostopping speed for azure. 
Previously, auto stopping takes `5m11s`, and with the current branch, it takes `39s` (8x faster)

[Azure] Optimize autostopping speed for azure

---

sky/backends/cloud_vm_ray_backend.py

Fixes an assertion issue introduced in #3521

[k8s] Allow autodown for k8s

---

sky/utils/common_utils.py

We previously keep dots in the user name, which can cause an error for the GCP's labels.
Fixes #3526

[UX/Core] Remove dots in user name

---

docs/source/reference/config.rst
sky/backends/backend_utils.py
sky/clouds/cloud.py
sky/clouds/kubernetes.py
sky/core.py
sky/execution.py
sky/provision/kubernetes/utils.py
sky/utils/schemas.py

Makes `SERVICE_ACCOUNT` default remote identity for Kubernetes. This helps with lesser config required for exec based clusters (GKE), and does not cause issues since we anyway need to create an SA for the ssh jump pod. 
Also adds checks for autodown support, and disable autodown when using exec based auth with `LOCAL_CREDENTIALS` on Kubernetes clusters.

[k8s] Use `SERVICE_ACCOUNT` as default remote_identity, add checks for autodown support

---

sky/backends/cloud_vm_ray_backend.py

[Core] `source ~/.bashrc` when tailing managed jobs logs

---

sky/cli.py
tests/test_cli.py

Previous, prices across clouds + within cloud are not sorted properly.
This PR:
```
```
Comparison: two text files in https://gist.github.com/concretevitamin/1fda666bfa129aedd3a3ced485e8f05c
Speed seems the same:
```bash
#!/bin/bash
set -ex
export BASH_XTRACEFD=1
sky show-gpus L4
sky show-gpus L4:1
sky show-gpus L4:1 --all-regions
sky show-gpus L4 --cloud aws
sky show-gpus A100
sky show-gpus A100:8
sky show-gpus A100:8 --all-regions
sky show-gpus A100:8 --cloud aws
```
```
master: median 15.454 total
15.454 total
14.471 total
16.712 total
PR: median 15.391 total
15.391 total
15.497 total
14.612 total
```

[UX/show-gpus] Improve sorting.

---

sky/serve/core.py

Fixes  #3545
This returns the generated (or specified) service name and the generated endpoint.  This moves closer to supporting `sky.serve.core.up` as a library function.
Manually ran the following:
```
import sky
from sky.serve.service_spec import SkyServiceSpec 
run_str = """
docker run  \
--runtime nvidia \
--gpus all \
--shm-size 1g \
-v ~/.cache/huggingface:/root/.cache/huggingface \
--env "HUGGING_FACE_HUB_TOKEN=${HUGGINGFACE_TOKEN}" \
--ipc=host \
-p 8000:8000 \
vllm/vllm-openai:latest \
--trust-remote-code \                                                                            
--tensor-parallel-size $SKYPILOT_NUM_GPUS_PER_NODE \
--max-model-len 18000 \
--chat-template '<s>[INST] You are a fair judge assistant tasked with providing clear, objective feedback based on specific …
```

[Serve] Return service name and endpoint from `sky.serve.up`

---

docs/source/getting-started/installation.rst
sky/cli.py

[docs] Docs for sky check specific cloud

---

docs/source/running-jobs/environment-variables.rst
examples/serve/llama2/llama2.yaml
examples/spot_pipeline/bert_qa_train_eval.yaml
llm/axolotl/axolotl-spot.yaml
llm/axolotl/axolotl.yaml
llm/dbrx/README.md
llm/dbrx/dbrx.yaml
llm/falcon/falcon.yaml
llm/gemma/serve.yaml
llm/llama-2/README.md
llm/llama-2/chatbot-hf.yaml
llm/llama-2/chatbot-meta.yaml
llm/llama-3/README.md
llm/llama-3/llama3.yaml
llm/sglang/llama2.yaml
llm/vicuna-llama-2/README.md
llm/vicuna-llama-2/train.yaml
llm/vicuna/train.yaml
llm/vllm/serve-openai-api.yaml
llm/vllm/service.yaml
sky/task.py
sky/utils/schemas.py
tests/test_yaml_parser.py

When an env var is specified in YAML but is empty, `sky launch` without `--env` will fail.

[UX] Error out for null env var

---

sky/backends/cloud_vm_ray_backend.py
sky/serve/core.py

#3377 changes the autostop for skyserve controller to autodown, which will teardown the controller when the sky serve controller job exited unexpectedly and remove any related replica information/logs. This PR changes it back to autostop to preserve the info.
```yaml
jobs:
controller:
resources:
cpus: 4+
memory: 4+
kubernetes:
remote_identity: SERVICE_ACCOUNT
serve:
controller:
resources:
cpus: 4+
memory: 4+
```

[Serve] Change back from autodown to autostop

---

sky/cli.py
tests/test_jobs_and_serve.py

We used `sys.exit(1)` for CLIs like `sky local up` which will cause the error message failed to be exposed by the usage collection. We now change them to error raising for more complete error message.

[Usage] Collect failure message

---

docs/source/reference/config.rst
sky/adaptors/cloudflare.py
sky/check.py
sky/utils/schemas.py

Adds a `allowed_clouds` field to config.yaml which limits the clouds that will be checked/enabled by `sky check`.
```
allowed_clouds:
- kubernetes
- aws
- gcp
```

[core] Add `allowed_clouds` to config to check only specific clouds

---

sky/cli.py

Simple optimization to check only kubernetes after running `sky local up`. Enabled by our recent improvements to `sky check`.
Reduces `sky local up` time by ~13 seconds.

[k8s] Check only kubernetes after `sky local up`

---

docs/source/examples/managed-jobs.rst

We add a hint box for managed spot jobs comparing to `sky launch --use-spot` in docs.

[Docs] Clarify managed spot jobs against sky launch

---

sky/clouds/aws.py
sky/clouds/azure.py
sky/clouds/cloud.py
sky/clouds/cudo.py
sky/clouds/fluidstack.py
sky/clouds/gcp.py
sky/clouds/ibm.py
sky/clouds/kubernetes.py
sky/clouds/lambda_cloud.py
sky/clouds/oci.py
sky/clouds/paperspace.py
sky/clouds/runpod.py
sky/clouds/scp.py
sky/clouds/vsphere.py

[Minor] Refactor `is_same_cloud`

---

llm/vllm/service-with-auth.yaml
sky/serve/replica_managers.py
sky/serve/service_spec.py
sky/utils/schemas.py

Closes #3549 by adding headers configuration in readiness probe.
```bash
$ sky serve up llm/vllm/service-with-auth.yaml --gpus L4
Service from YAML spec: llm/vllm/service-with-auth.yaml
Service Spec:
Readiness probe method:           GET /v1/models with headers {"Authorization": "Bearer sky-authkey-3d2105b9-a9ba-4f13"}
Readiness initial delay seconds:  1200
Replica autoscaling policy:       Fixed 1 replica
Spot Policy:                      No spot policy
$ curl $(sky serve status --endpoint sky-service-4233)/v1/models -H 'Authorization: Bearer sky-authkey-3d2105b9-a9ba-4f13' 
{"object":"list","data":[{"id":"meta-llama/Llama-2-7b-chat-hf","object":"model","created":1715746959,"owned_by":"vllm","root":"meta-llama/Llama-2-7b-chat-hf","parent":null,"permission": …
```

[Serve] Support headers in Readiness Probe

---

sky/backends/cloud_vm_ray_backend.py
sky/provision/instance_setup.py
sky/skylet/constants.py
sky/utils/command_runner.py

We did not quote the command to be executed by SSH correctly when the command_runner runs a command with `source_bashrc=False`.
This should also fix #3531 without adding `source_bashrc=True` for the jobs and serve logs in #3536 and #3537

[Core] Fix quote in command runner

---

sky/templates/kubernetes-ray.yml.j2

Adds `skypilot-user` label to pods to help with observability.

[k8s] Add `skypilot-user` label to pods

---

sky/backends/cloud_vm_ray_backend.py

Previously, we used base64 for the commands to be run on remote machine, which caused malware detection software to misclassify the commands as malicious. We now change it to plain text instead to get around it

[Core] Avoid base64 to prevent malware detection software misclassifying the commands

---

docs/source/_gallery_original/index.rst
docs/source/reference/kubernetes/index.rst
docs/source/reference/kubernetes/kubernetes-getting-started.rst
llm/gemma/serve.yaml

Updates the Kubernetes docs intro to add feature cards targeted at different user personas.
TODOs

[k8s][docs] Add feature cards for users and admins

---

examples/stable_diffusion/README.md
examples/stable_diffusion/stable_diffusion_docker.yaml

Stable diffusion example was broken because docker-compose was not working (prints nothing, shows no error). This PR gets rid of the docker-compose dependency.
Tested:

[Examples] Update stable diffusion example

---

sky/jobs/utils.py

[Jobs] Fix back compatibility for `sky jobs logs` from 0.5

---

sky/__init__.py

```
sky jobs launch --gpus A100:8 --cloud aws echo hi -y
sky jobs logs --controller
```
```
sky down dbg
```

Release 0.6.0

---

sky/data/mounting_utils.py

As discovered in the test from this [thread](https://github.com/skypilot-org/skypilot/issues/3353#issuecomment-2141052374), there was a significant performance update since version `1.3.0`, which we by default currently install for the users. This PR updates the version to `2.2.0`.

[Storage] gcsfuse version update to 2.2.0

---

docs/source/serving/auth.rst
docs/source/serving/sky-serve.rst
docs/source/serving/user-guides.rst

Adding docs for authorization (introduced in #3552)

[Serve][Doc] Authorization doc

---

sky/provision/kubernetes/utils.py

`get_gke_accelerator_name` returns the incorrect label for H100 (`nvidia-tesla-h100` instead of `nvidia-h100`). This PR fixes it by removing the incorrect conditional check for H100.
Tested:

[k8s] Fix GKELabelFormatter for H100s

---

sky/backends/backend_utils.py

[Core] Fix backward compatibility for old clusters

---

sky/clouds/service_catalog/kubernetes_catalog.py

When none of the GPUs is available in a kubernetes cluster, the following error will occur:
```bash
sky show-gpus --cloud kubernetes
File "/home/gcpuser/skypilot/sky/utils/common_utils.py", line 388, in _record
File "/home/gcpuser/skypilot/sky/cli.py", line 3331, in show_gpus
for out in _output():
File "/home/gcpuser/skypilot/sky/cli.py", line 3104, in _output
k8s_realtime_table = _get_kubernetes_realtime_gpu_table()
File "/home/gcpuser/skypilot/sky/cli.py", line 3048, in _get_kubernetes_realtime_gpu_table
assert (set(counts.keys()) == set(capacity.keys()) == set(
AssertionError: Keys of counts (['T4', 'V100']), capacity (['T4', 'V100']), and available ([]) must be same.
```

[Kubernetes] Fix kubernetes available GPUs

---

sky/clouds/kubernetes.py

Add cluster name truncation for Kubernetes

---

sky/skylet/constants.py
sky/skylet/log_lib.py
tests/test_smoke.py

Fixes #3638.
```yaml
setup: |
conda create -n vllm python=3.10
conda activate vllm
pip install vllm
run: |
conda activate vllm
python -m vllm.entrypoints.openai.api_server
```

[Core] Deactivate SkyPilot runtime env for jobs

---

docs/source/cloud-setup/cloud-permissions/kubernetes.rst
docs/source/reference/kubernetes/kubernetes-getting-started.rst
docs/source/reference/kubernetes/kubernetes-setup.rst
sky/provision/kubernetes/config.py
sky/provision/kubernetes/utils.py
sky/utils/kubernetes/generate_static_kubeconfig.sh

This PR has a few updates for k8s SA and namespace support:
Code:
1. Moves the `skypilot-system` namespace creation to happen only if the default `SERVICE_ACCOUNT` remote_identity is used. This is to reduce the scope of permissions required if a SA already exists. 
2. Update namespace fetching logic to also account for the case when the cluster is running in a in-cluster auth config but in a namespace different than 'default'. Previously we had been testing on `default` namespace so this bug was not caught.
Docs:
1. Updated the minimum permissions for Kubernetes docs and confirms that the permissions listed in the docs work. 
3. Added permissions required if storage mounting is used
4. Add comments if the user needs to specify their own namespace.
Ran the following tests for two scenarios …

[k8s] Robust service account and namespace support

---

sky/backends/backend_utils.py
sky/templates/kubernetes-ray.yml.j2

A yaml like this would fail:
```
resources:
labels:
my-label: 'True'
```
Because when the cluster YAML was dumped for the provisioner in ~/.sky/generated/, it would remove the quotes and write `my-label: True`. This would be parsed as a bool value (instead of str) by yaml.safe_load, which would cause issues with downstream code (e.g., Kubernetes python API does not allow submitting bools as label values). 
This PR adds single quotes around all dumped labels to make sure they are parsed as strings by the provisioner.
Tested:

[Core] Allow boolean-like strs in resources.labels

---

sky/skylet/constants.py
sky/usage/usage_lib.py

For some image_id specified by users, there might be `setuptools>=70` installed, which will cause the runtime setup to fail for SkyPilot with the following error. We should downgrade the `setuptools` in SkyPilot runtime environment.
```
File "/home/ray/anaconda3/lib/python3.10/site-packages/ray/dashboard/modules/dashboard_sdk.py", line 10, in <module>
from pkg_resources import packaging
ImportError: cannot import name 'packaging' from 'pkg_resources' (/home/sky/skypilot-runtime/lib/python3.10/site-packages/pkg_resources/__init__.py)
```

[Core] Downgrade setup tools for runtime setup

---

sky/backends/cloud_vm_ray_backend.py

A user reported that the following task yaml fails:
```
num_nodes: 30
setup: echo setup
run: echo run
```
This is due to the length checking before does not include the quotes, which will add significant length. We derived the current threshold with binary search.

[Core] Fix inline script length checking

---

sky/provision/aws/config.py

skypilot-v1 IAM role requires permission for passing the role and getting the instance profile, so a controller started with this IAM role with this account can create an instance with this IAM role assigned.
The change was included in the previous ray autoscaler-based provisioner, but accidentally dropped in the new provisioner refactoring #1702. Adding it back now:
https://github.com/skypilot-org/skypilot/blob/19ebc3d394b2adf26f72bbb5f341ac9763f3bdf0/sky/skylet/providers/aws/config.py#L361C13-L386C45

[AWS] Add pass role permission back for skypilot-v1

---

docs/source/cloud-setup/cloud-permissions/kubernetes.rst
docs/source/reference/kubernetes/index.rst
docs/source/reference/kubernetes/kubernetes-deployment.rst
docs/source/reference/kubernetes/kubernetes-getting-started.rst
docs/source/reference/kubernetes/kubernetes-ports.rst
docs/source/reference/kubernetes/kubernetes-setup.rst
sky/provision/kubernetes/utils.py
sky/skylet/constants.py
sky/utils/kubernetes/generate_kubeconfig.sh
tests/kubernetes/scripts/deploy_k3s.sh

Cluster admin docs are now sequential, showing clear steps to be taken to setup a cluster. 
Incorporated minimal permissions setup and namespacing.
Add reference to generate_kubeconfig.sh.
Moved ports and deployment guides to separate pages since they were too long.
Updated GPU labelling guide and other fixes.

[Docs][k8s] Revamp k8s cluster admin docs

---

sky/utils/kubernetes/create_cluster.sh

This PR speeds up `sky local up` on GPU machines to ~2 min 30s, down from ~12 min on current master.
We remove the GPU labelling step, which is no longer required after #3493 since we can use nvidia's official labels.
We also remove the image pre-pull steps, since kubernetes (kind) pulling the image directly during launch is faster than `docker pull` -> `kind load`, which takes ~2x the time.
Tested on T4 and L4 GCP instances with `sky local up` and `sky launch --gpus T4/L4:1 --cloud kubernetes -- nvidia-smi`.

[k8s] `sky local up` speed up for GPUs

---

Dockerfile_k8s
Dockerfile_k8s_gpu
sky/provision/kubernetes/instance.py

Optimizes the Kubernetes GPU image for >2x faster provisioning (87s vs 201s). The new image is 1.96G compressed vs 6.39G compressed for the previous image.
```
sky launch -y -c test --cloud kubernetes --gpus T4:1 -- nvidia-smi  7.72s user 4.54s system 6% cpu 3:21.66 total
sky launch -y -c test2 --cloud kubernetes --gpus T4:1 -- nvidia-smi  4.74s user 4.30s system 9% cpu 1:27.87 total
```
Also adds kubectl to the dependencies pre-installed in the image for faster controller setup.
Closes #3435 and #2461.
Related - https://github.com/skypilot-org/skypilot-catalog/pull/72/
Tested:

[k8s] GPU Image debloat

---

sky/clouds/kubernetes.py
sky/provision/kubernetes/utils.py
sky/templates/kubernetes-ray.yml.j2
tests/common.py

Closes #3667.
Adds support for using spot instances with `--use-spot` if the underlying cluster supports spot instances. 
This is supported only for GKE to start and is enabled only if the cluster already has spot instances or the user has set `autoscaler: gke` in config.yaml. 

[k8s] Allow spot instances on supported k8s clusters

---

sky/provision/docker_utils.py
sky/provision/kubernetes/instance.py
sky/utils/command_runner.py

We now make the home dir retrieving for the docker and k8s cluster more robust by avoiding the stderr polluting the stdout.
To reproduce:
1. Dockerfile
```dockerfile
FROM continuumio/miniconda3:23.3.1-0
RUN apt update -y && \
apt install gcc rsync sudo patch openssh-server pciutils nano fuse socat netcat curl -y && \
rm -rf /var/lib/apt/lists/* 
RUN mkdir -p /var/run/sshd && \
sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config && \
sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd && \
cd /etc/ssh/ && \
ssh-keygen -A
RUN useradd -m -s /bin/bash sky && \
echo "sky ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers && \
echo 'Defaults        secure_path="/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin: …
```

[Docker/k8s] Make retrieving home dir more robust to warnings

---

sky/provision/aws/instance.py

Currently, ports check for the specific port, but for AWS, `-1` signifies all ports and all protocols.
* Skypilot currently tries to add the port even if all ports are available to an existing SG.
* Now treats -1 as all protocols for `IpProtocol`
* Now treats -1 as all ports for `FromPort` and `ToPort`
Additional:
* If an SG name is specified in the configuration, it should probably not modify if it isn't managed by SkyPilot.
* tested launching via aws with a custom SG

[SERVE][AWS] Don't open ports when all ports and all protocols are specified

---

sky/serve/service_spec.py

Previously, when no spot fallback policy was specified, `No spot policy` would be shown on the terminal, which is confusing when users are using spot resources. This PR reword it to `No spot fallback policy` to reduce confusion.
```bash
$ sky serve up -n http examples/serve/http_server/task.yaml --cloud aws --use-spot
Service from YAML spec: examples/serve/http_server/task.yaml
Service Spec:
Readiness probe method:           GET /health
Readiness initial delay seconds:  20
Readiness probe timeout seconds:  15
Replica autoscaling policy:       Fixed 2 replicas
Spot Policy:                      No spot policy
$ sky serve up -n http examples/serve/http_server/task.yaml --cloud aws --use-spot
Service from YAML spec: examples/serve/http_server/task.yaml
Service Spec:
Readiness probe method: …
```

[Serve] Reword no Spot Policy in SkyServe

---

llm/vllm/README.md
llm/vllm/serve-openai-api-docker.yaml

Using vLLM container image saves ~2 min during provisioning. 

[Examples] Add vLLM container example

---

sky/adaptors/azure.py
sky/skylet/providers/azure/config.py
sky/skylet/providers/azure/node_provider.py
sky/utils/common_utils.py

Mitigates #3695. 
This PR avoids an additional configuration which causes a significant slow down.
```
multitme -n 5 sky launch --cloud azure -y
Mean        Std.Dev.    Min         Median      Max
real        214.837     11.941      203.255     211.937     237.772
user        9.281       0.455       8.990       9.093       10.186
sys         2.748       0.080       2.641       2.761       2.873
```
```
multitime -n 5 sky launch -c test-azure-skip-deploy --cloud azure --cpus 2 -y
Mean        Std.Dev.    Min         Median      Max
real        28.327      0.950       27.159      28.309      29.676      
user        10.261      0.166       10.113      10.187      10.582      
sys         1.497       0.066       1.442       1.472       1.623 
```
```
multitime -n 5 sky launch --cloud azure -y …
```

[Azure] Avoid azure reconfig everytime, speed up launch by up to 5.8x

---

sky/clouds/azure.py
sky/provision/azure/__init__.py
sky/provision/azure/instance.py
sky/provision/common.py
sky/provision/instance_setup.py
sky/skylet/providers/azure/config.py
sky/skylet/providers/azure/node_provider.py

This PR uses SkyPilot provisioned to query the VM status for Azure, making it more robust against the original CLI-based query.

[Azure] Use SkyPilot provisioner for status query

---

sky/provision/kubernetes/utils.py

GCP recently introduced `a3-mega` instances with improved bandwidth instances. On GKE, such nodes are labeled as `cloud.google.com/gke-accelerator=nvidia-h100-mega-80gb` which was causing these to be recognized as `H100-MEGA-80GB`. This change fixes this.
Before
```
(sky) Andrews-MacBook-Air:skypilot asai$ sky show-gpus --cloud kubernetes
Kubernetes GPUs
GPU             QTY_PER_NODE            TOTAL_GPUS  TOTAL_FREE_GPUS  
H100-MEGA-80GB  1, 2, 3, 4, 5, 6, 7, 8  16          16               
(sky) Andrews-MacBook-Air:skypilot asai$ sky launch --cloud kubernetes --gpus H100:8
I 06-26 15:58:20 optimizer.py:1264] No resource satisfying Kubernetes({'H100': 8}) on Kubernetes.
sky.exceptions.ResourcesUnavailableError: Kubernetes cluster does not contain any instances satisfying the request: …
```

map gke h100 megas to 'H100'

---

sky/provision/kubernetes/utils.py

Currently running `sky launch ...` against a K8S cluster requires the namespace.create permission even if the namespace already exists, because it checks existence using the create call. This changes it to use `read_namespace` instead to reduce the permissions surface area required to launch a cluster.
There are no existing unit tests for this functionality, as far as I can tell. For now, I just tried submitting a job using an account that only has read namespaces permission and it started working.

Don't require create namespace permission in cluster launch flow

---

sky/provision/aws/instance.py

This PR fixes a bug introduced by #3637: AWS skip the ports opening for all the instances.
To reproduce:
1. `sky launch -c test-aws-port --cloud aws --cpus 2 --ports 8000 "python -m http.server 8000"
2. `curl $(sky status --endpoint 8000 test-aws-port)`

[AWS] Fix opening ports

---

sky/clouds/service_catalog/data_fetchers/fetch_azure.py

Resolves (partially) #3718 by removing those fractional types

[Catalog] Remove fractional A10 instance types in catalog

---

docs/source/reference/kubernetes/kubernetes-troubleshooting.rst

[Docs] Add out of disk to k8s troubleshooting docs

---

examples/nccl_test.yaml

Adds NCCL test example. Closes #3164. I've pasted a dump of my run of it on GCP. The network interface names change depending on the cloud provider I noticed, so to make it more portable, it might make sense to add something to `grep` the interface name. Also CUDA path would be more consistent if we run inside a container.
```
(worker1, rank=1, pid=20075, ip=10.164.15.193) 10.164.15.192,10.164.15.193
(head, rank=0, pid=21170) 10.164.15.192,10.164.15.193
(head, rank=0, pid=21170) Warning: Permanently added '10.164.15.193' (ECDSA) to the list of known hosts.
(head, rank=0, pid=21170) # nThread 1 nGpus 8 minBytes 8 maxBytes 134217728 step: 2(factor) warmup iters: 5 iters: 20 agg iters: 1 validation: 1 graph: 0
(head, rank=0, pid=21170) #
(head, rank=0, pid=21170) # Using devices
(head, …
```

add nccl test example

---

sky/backends/cloud_vm_ray_backend.py
sky/clouds/azure.py
sky/skylet/providers/azure/node_provider.py
sky/templates/azure-ray.yml.j2

Fixes #3651. [A10 GPUs require a special type of driver, Grid Driver](https://forums.developer.nvidia.com/t/ubuntu-22-04-installation-driver-error-nvidia-a10/285195/2), which is [suggested to be installed by enabling the `NvidiaGpuDriverLinux` extension](https://learn.microsoft.com/en-us/azure/virtual-machines/extensions/hpccompute-gpu-linux). This PR added this extension for A10 instances.

[Core] Fix A10 GPU on Azure

---

sky/data/storage.py

This resolves #3729 with some refactoring.
```
$ sky launch test.yaml --cloud gcp -y
Task from YAML spec: test.yaml
I 07-06 21:59:14 storage.py:1380] Created S3 bucket no-log-s3-creation in us-east-1
I 07-06 21:59:18 storage.py:1824] Created GCS bucket log-gcs-creation in US with storage class STANDARD
I 07-06 21:59:22 optimizer.py:695] == Optimizer ==
I 07-06 21:59:22 optimizer.py:706] Target: minimizing cost
I 07-06 21:59:22 optimizer.py:718] Estimated cost: $0.4 / hour
I 07-06 21:59:22 optimizer.py:718]
I 07-06 21:59:22 optimizer.py:843] Considered resources (1 node):
I 07-06 21:59:22 optimizer.py:913] ----------------------------------------------------------------------------------------------
I 07-06 21:59:22 optimizer.py:913]  CLOUD   INSTANCE …
```

[Storage] Make s3 bucket creation log visible to the users

---

sky/clouds/aws.py
tests/unit_tests/test_aws.py

Fix #3733
Oneline code fix + new unit tests to properly validate labels for AWS launches.
Created new unit tests with several cases.  Ensured `aws:` is prejected and not `aws:` is accepted.
Skipped running any other tests due to the unit-tests and narrowly scoped changes.
Ran `tests/unit_tests/test_resources.py` and `tests/unit_tests/test_aws.py`

Ensure AWS labels are appropriately validated

---

.github/workflows/format.yml
.github/workflows/mypy-generic.yml
.github/workflows/pylint.yml
.github/workflows/pytest-generic.yml
.github/workflows/pytest.yml
.github/workflows/test-doc-build.yml
.github/workflows/test-poetry-build.yml

`merge_group` trigger is required for enabling merge group. Merge group could help us queue multiple PRs to be merged without waiting for the CI to finish.
Reference: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/merging-a-pull-request-with-a-merge-queue

[CI] Add trigger for merge group

---

docs/source/cloud-setup/cloud-permissions/gcp.rst
docs/source/reference/config.rst
sky/clouds/gcp.py
sky/provision/gcp/config.py
sky/templates/gcp-ray.yml.j2
sky/utils/schemas.py
tests/test_smoke.py
tests/test_yamls/force_enable_external_ips_config.yaml
tests/test_yamls/use_internal_ips_config.yaml

This PR adds a new configuration to the `~/.sky/config.yaml` for gcp, `force_enable_external_ips`. Setting this configuration to `true` (default is `false` for backwards compatibility) will cause the gcp subnet provisioner to create VMs with a public ip address even if `use_internal_ips` is set to `true`; this is useful when communication within a vcp is desired _and_ the VM needs to make calls to the public internet.

[GCP] Add gcp.force_enable_external_ips configuration

---

docs/source/reference/config.rst
sky/backends/backend_utils.py
sky/backends/cloud_vm_ray_backend.py
sky/cli.py
sky/clouds/aws.py
sky/clouds/azure.py
sky/clouds/cloud.py
sky/clouds/cudo.py
sky/clouds/fluidstack.py
sky/clouds/gcp.py
sky/clouds/ibm.py
sky/clouds/kubernetes.py
sky/clouds/lambda_cloud.py
sky/clouds/oci.py
sky/clouds/paperspace.py
sky/clouds/runpod.py
sky/clouds/scp.py
sky/clouds/vsphere.py
sky/execution.py
sky/provision/provisioner.py
sky/resources.py
sky/utils/resources_utils.py
sky/utils/schemas.py
tests/test_yamls/test_aws_config.yaml
tests/unit_tests/test_backend_utils.py
tests/unit_tests/test_resources.py

Similar to https://github.com/skypilot-org/skypilot/pull/3488 but for SGs
This PR:
* Allows specification of SGs for controllers vs workers.
* **Currently removes the port requirement to be able to allow SG specification in serve.**
Addresses: https://github.com/skypilot-org/skypilot/issues/3473
In `~/.sky/config.yaml`:
* When setting for a controller wildcard and all other resources ("*")
```yaml
aws:
security_group_name:
- sky-serve-controller-*: skypilot-controller-fake-sg
- "*": skypilot-default-fake-sg 
```
* When setting for everything by specifying a default ("*")
```yaml
aws:
security_group_name:
- "*": skypilot-default-fake-sg
```
* When setting for everything by specifying just the `security_group_name` via string
```yaml
aws:
security_group_name: skypilot-default-fake-sg
``` …

[Core][AWS] Allow specification of Security Groups for resources.

---

README.md
docs/source/getting-started/installation.rst

[Docs] Update nightly installation recommendation

---

examples/nemo/nemo_gpt_distributed.yaml
examples/nemo/nemo_gpt_singlenode.yaml
examples/nemo/nemo_gpt_train.yaml

Updates NeMo GPT examples.
* Use nvcr nemo container to make startup faster (~5 min to pull and start vs 1.5 hr of setup in the previous YAML)
* Uses newer `McoreGPTModel` instead of the deprecated `GPTModel`
* Added notes and customization on checkpointing destination
* Fixed some dependency issues
Tested on Kubernetes and GCP.

[Examples] Update nemo gpt examples

---

.gitignore
sky/provision/kubernetes/network_utils.py
sky/templates/kubernetes-ingress.yml.j2
sky/templates/kubernetes-loadbalancer.yml.j2

This forwards kubernetes annotation values in the `~/.sky/config` to sub services such as the load balancer.  This ensures users can set custom annotations, such as for AWS, to ensure load balancers are internet facing.
Manually update my `~/.sky/config` to have the following contents:
```
kubernetes:
ports: loadbalancer
custom_metadata:
annotations:
service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
```
And ran sky launch with this config:
```
service:
readiness_probe: /v1/models
resources:
accelerators: A100:2
cpus: 22
memory: 500
disk_size: 400
ports: 8000
image_id: docker:vllm/vllm-openai:latest
envs:
MODEL: ""
setup: |
conda deactivate
python3 -c "import huggingface_hub; huggingface_hub.login('${HUGGINGFACE_TOKEN}')" …
```

Propagate kubernetes custom metadata annotations to sub-services

---

sky/clouds/aws.py
sky/templates/aws-ray.yml.j2
sky/utils/schemas.py
tests/test_config.py
tests/unit_tests/test_resources.py

Fixes https://github.com/skypilot-org/skypilot/issues/2483
Users can now specify a disk_encrypted option under the resources stanza to enable disk encryption at rest. This is currently only setup for AWS but can easily be extended for other providers given their capability.
Manually updated my `~/.sky/config` with 
```
aws:
disk_encrypted: true
```
Then launched 
```
sky launch -c minimal examples/minimal.yaml
```
and confirmed that the attached EBS disks were encrypted.

Supporting encrypted disks for AWS

---

docs/source/reference/config.rst

This is to add the docs for encrypted disk introduced by #2483 

[Docs] Add docs for disk encrypted

---

sky/provision/kubernetes/utils.py
sky/templates/kubernetes-port-forward-proxy-command.sh

This PR allows `ssh <cluster-name>` to work even if the current active context is switched. Requested by users.
* On master, launch a cluster `oldclus` on `context1`
* Switch to this branch, launch a cluster `newclus1` on `context1`. Verify `ssh oldclus`, `ssh newclus1` and `sky exec` works on both clusters
*   Switch to `context2`, launch `newclus2`. Verify `ssh newclus1`, `ssh newclus2` and `sky exec newclus1 newclus2` works.
* `ssh oldclus` will not work on `context2`, as expected.

[k8s] Kubecontext agnostic SSH

---

llm/axolotl/axolotl-spot.yaml
sky/provision/kubernetes/instance.py

Closes #3702.
Tested with:
1. Base case - bad image, no init container, returns clear error message: `sky launch -c test --cloud kubernetes --image-id romilb/fakeimage -- echo hi`
```
run_instances: Error occurred when creating pods: Failed to create container while launching the node. Error details: failed to pull and unpack image "docker.io/romilb/fakeimage:latest": failed to resolve reference "docker.io/romilb/fakeimage:latest": pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed.
```
2. Healthy init container - `sky launch -c test --cloud kubernetes` with this config.yaml:
```
kubernetes:
pod_config:
spec:
initContainers:
- name: init-myservice
image: busybox
command: ['sh', '-c', 'echo hi']
```
3. Bad …

[k8s] Update waiting logic for init containers

---

README.md
docs/source/_gallery_original/index.rst
docs/source/_gallery_original/llms/llama-3_1.md
docs/source/_static/custom.js
docs/source/docs/index.rst
llm/llama-3_1/README.md
llm/llama-3_1/llama-3_1.yaml

[LLM] Llama 3.1 serving example

---

sky/benchmark/benchmark_utils.py
tests/test_smoke.py

Closes #3731.
Sky Benchmark works reliably only with S3. If the object store is created on GCS, it fails (possibly related to https://github.com/GoogleCloudPlatform/gsutil/issues/417, but special casing for the error seems to break other parts of sky benchmark code). 
`test_sky_bench` has been restricted now to run only if AWS is used for the test.

[SkyBench] Allow only s3 for sky benchmark

---

sky/adaptors/kubernetes.py

Closes #3774. This was a regression in https://github.com/skypilot-org/skypilot/pull/3674 which decorated the kubernetes API methods multiple times, blowing up the stack depth and causing the recursion error.
This PR fixes it by decorating methods only once.

[k8s] Fix recursive decoration of kubernetes API methods

---

sky/adaptors/azure.py
sky/data/storage.py
tests/test_smoke.py

`pytest tests/test_smoke.py::TestStorageWithCredentials::test_private_bucket --azure` has been failing.

[Azure blob] fix `test_private_bucket` for azure blob

---

Dockerfile
sky/__init__.py

```
sky jobs launch --gpus A100:8 --cloud aws echo hi -y
sky jobs logs --controller
```
```
sky down dbg
```

Release 0.6.1

---

sky/task.py
tests/test_yaml_parser.py

Allows the workdir to be configured using environment variables.
Closes #3271 

Allow setting the workdir using environment variables

---

README.md
docs/source/docs/index.rst
docs/source/examples/interactive-development.rst

Preview: https://skypilot.readthedocs.io/en/docs-revamp-tmp2/docs/index.html

Docs revamp: polishing landing docs.

---

sky/backends/cloud_vm_ray_backend.py

Users were reporting instances being terminated before they fully booted up. From the paperspace console it looks like some of the larger instances can take up to 10 minutes. This bumps up the timeout to 10 minutes.
```
sky launch --gpus A100-80GB:1 --cloud paperspace
```

[Paperspace] increase timeout

---

sky/clouds/service_catalog/data_fetchers/fetch_lambda_cloud.py
sky/clouds/service_catalog/lambda_catalog.py

Lambda recently added CPU instance type which causes our catalog fetcher fail. This PR fixes this.

[Catalog] Fix lambda fetcher

---

tests/test_smoke.py

Some of our smoke tests were bypassed while mentioning that the spot instances are not supported by Azure, which are incorrect. Bypassed tests consists of:
- `test_smoke.py::test_use_spot`
- `test_smoke.py::test_job_pipeline`
- `test_smoke.py::test_managed_jobs_failed_setup`
- `test_smoke.py::test_managed_jobs_pipeline_failed_setup`
- `test_smoke.py::test_managed_jobs_recovery_default_resources`
- `test_smoke.py::test_managed_jobs_storage`
Confirmed all the tests passes with Azure.

[Azure][Tests] Update false pytest marks on spot instances

---

sky/provision/kubernetes/instance.py

This PR adds logging for surfacing errors during pod provisioning due to insufficient resources.
Previously, any non-cpu/memory related failure would be shown as insufficient GPU, even though other resources may be missing.
We now surface the underlying error message and add special handling for when FUSE device is unavailable (reported by users).

[k8s] Surface provisioning errors + handling for fuse failures

---

sky/backends/cloud_vm_ray_backend.py
sky/provision/common.py

Follow up to https://github.com/skypilot-org/skypilot/pull/3699, which introduced the `gcp.force_enable_external_ips` setting to the skypilot configuration. E.g.
```
gcp:
vpc_name: default
force_enable_external_ips: true
```
With this configuration, however, skypilot will attempt to communicate with the VMs via the external ips, despite `use_internal_ips: true`, since the existence of external ips is implicitly interpreted to mean `use_internal_ips = false`; this assumption was broken in https://github.com/skypilot-org/skypilot/pull/3699.
This PR fixes by having `ClusterInfo.get_feasible_ips` check the `provider_config` for `use_internal_ips` respecting it's setting if found.

[GCP] Cluster info respects `use_internal_ips`

---

sky/cli.py
sky/clouds/service_catalog/kubernetes_catalog.py
sky/provision/kubernetes/utils.py

Updates `sky show-gpus --cloud kubernetes` to also show per node GPU availability information. Helps users debug out of resource errors and get better visibility into their cluster. 
Example:
```
$ sky show-gpus --cloud kubernetes
Kubernetes GPUs
GPU   QTY_PER_NODE  TOTAL_GPUS  TOTAL_FREE_GPUS
T4    1             4           3
V100  1, 2          4           1
Kubernetes per node GPU availability
NODE_NAME                               GPU_NAME  TOTAL_GPUS  FREE_GPUS
gke-gkeusc5-default-pool-93c7cbf8-6ll6  T4        1           1
gke-gkeusc5-default-pool-93c7cbf8-czx8  T4        1           1
gke-gkeusc5-default-pool-93c7cbf8-fdhf  T4        1           0
gke-gkeusc5-default-pool-93c7cbf8-mfj8  T4        1           1
gke-gkeusc5-v100-570bede1-kwsf          V100      2           1 …
```

[k8s] Show per node status in sky show-gpus

---

sky/provision/kubernetes/utils.py

Adds  a debugging hint to run `kubectl` when get_nodes or get_pods fails. This is usually caused by network issues, and running `kubectl` for debugging will assure the user the issue is related to k8s reachability, not SkyPilot. 

[k8s] Add debug message for timeout

---

sky/provision/azure/config.py
sky/templates/azure-ray.yml.j2

```yaml
resources:
cloud: azure
image_id: docker:michaelvll/skypilot-test:v4
envs:
SKYPILOT_DOCKER_USERNAME: michaelvll
SKYPILOT_DOCKER_PASSWORD: "xxxx"
SKYPILOT_DOCKER_SERVER: docker.io
```

[Azure] Fix docker login on Azure

---

sky/provision/gcp/instance_utils.py
sky/provision/gcp/mig_utils.py
sky/templates/gcp-ray.yml.j2

It is possible that the `provision_timeout` is set to None in our cluster yaml, which will cause a wrong CLI to wait for MIG.
To reproduce:
```
experimental:
config_overrides:
gcp:
managed_instance_group:
run_duration: 36000
provision_timeout: 1800
resources:
accelerators: H100:8
cpus: 32+
```

[GCP DWS] Fix None issue when no provision timeout is provided

---

sky/clouds/service_catalog/data_fetchers/fetch_azure.py

Fixes #3750.
In Azure SKU, there is a cloud service series that we should filter out.
Reference: https://learn.microsoft.com/en-us/azure/cloud-services/cloud-services-choose-me
Also, for some H100 series, the windows product description is `Win` instead of `Windows`. This PR also fixes that.
```python
import pandas as pd
import os
file_path = os.path.expanduser('~/.sky/catalogs/v5/azure/vms.csv')
df = pd.read_csv(file_path)
grouped = df.groupby(['InstanceType', 'Region']).size().reset_index(name='count')
filtered_instances = grouped[grouped['count'] >= 2]
instance_types = filtered_instances['InstanceType'].unique()
print(instance_types)
```

[Catalog] Fix Azure catalog duplications

---

sky/provision/docker_utils.py
sky/templates/aws-ray.yml.j2
sky/templates/azure-ray.yml.j2
sky/templates/gcp-ray.yml.j2
sky/templates/paperspace-ray.yml.j2

There seems no harm to add `--gpus all` when GPUs exist, which is a newer version of the option `--runtime nvidia` and seems docker's official doc is using this: https://docs.docker.com/engine/containers/resource_constraints/#access-an-nvidia-gpu 

[Docker] Add `--gpus all` for docker when GPU is available

---

sky/provision/kubernetes/manifests/smarter-device-manager-daemonset.yaml

Currently smarter-device-manager isn't running on spot or queued-provisioning nodes that have tolerations applied to them, which makes it impossible to schedule pods with file_mounts enabled. This tells it to run on all nodes, regardless of taints.

Allow smarter device manager to schedule on all nodes

---

docs/source/reference/config.rst
sky/clouds/aws.py
sky/clouds/cloud.py
sky/clouds/gcp.py
sky/clouds/utils/aws_utils.py
sky/optimizer.py
sky/provision/aws/instance.py
sky/templates/aws-ray.yml.j2
sky/utils/schemas.py

Blocked by #3850.
This adds support for targeted capacity reservations. A user can have the following `~/.sky/config.yaml` to ask SkyPilot to consume a list of targeted capacity reservations:
```
aws:
specific_reservations:
- cr-a0123456
- cr-b0123456
```

[AWS] Support targeted on-demand capacity reservations

---

sky/backends/wheel_utils.py

If a user has multiple Sky versions installed (e.g., in different conda envs), `sky launch` would fail with:
```
FileNotFoundError: Could not find built SkyPilot wheels with glob pattern **/skypilot-1.0.0.dev20240823-*.whl under PosixPath('/Users/romilb/.sky/wheels')
```
This is because we cleanup all except the latest wheels:
https://github.com/skypilot-org/skypilot/blob/bca709b5554858fc630695a1d867c2d84593a291/sky/backends/wheel_utils.py#L51-L57
This PR updates our wheel creation behavior to check if a wheel for the version exists and create it if it doesn't already exist.
Manual tests:

[Core] Fix wheel creation when multiple versions are installed

---

docs/source/examples/docker-containers.rst
sky/provision/docker_utils.py
sky/provision/runpod/utils.py
sky/skylet/providers/command_runner.py

Previously, if the docker image had an entry point that was not default (`/bin/bash`), it would fail when running as runtime env on real clouds (in k8s it works since we have special handling for this), e.g. the vllm official docker uses `python3 -m vllm.entrypoints.openai.api_server` as entry point, as ref here: https://github.com/vllm-project/vllm/blob/9db93de20ca282feb4dfaabbc56032c9312bde7b/Dockerfile#L222
This PR fixed it by overriding the entry point to `/bin/bash`.
```python
resources:
cloud: aws
image_id: docker:vllm/vllm-openai:latest
accelerators: T4
run: |
conda deactivate
python3 -c "import huggingface_hub; huggingface_hub.login('$HF_TOKEN')"
python3 -m vllm.entrypoints.openai.api_server --model meta-llama/Llama-2-7b-chat-hf --tokenizer …
```

[Core] Enable use docker image w/ non-default entrypoint as runtime env

---

docs/source/reference/faq.rst

The bug is fixed in the latest release 2.4.0; ref here https://github.com/pytorch/pytorch/issues/119989
Removing the faq now.

[Doc] Remove FAQ on workarounds for pytorch 2.2

---

sky/provision/runpod/utils.py

Sometimes when the RunPod cluster is in the process of being created, the `port` field in the runtime is None and that causes some problems (see logs below). This PR fixes the issue.
```bash
File “/home/memory/install/miniconda3/envs/sky/bin/sky”, line 8, in <module>
File “/home/memory/install/miniconda3/envs/sky/lib/python3.9/site-packages/click/core.py”, line 1157, in __call__
File “/home/memory/install/miniconda3/envs/sky/lib/python3.9/site-packages/click/core.py”, line 1078, in main
File “/home/memory/skypilot/sky/utils/common_utils.py”, line 367, in _record
File “/home/memory/skypilot/sky/cli.py”, line 806, in invoke
File …
```

[Core][RunPod] Fix list instances in RunPod Provisioner

---

sky/clouds/service_catalog/common.py

To reproduce,
```
rm -r ~/.sky/catalogs/v5/aws
sky launch -c test-aws --cloud aws
```

[AWS] Fix catalog folder not exists issue

---

sky/backends/cloud_vm_ray_backend.py

We have a message on A10 driver installation takes a lot of time and it keeps appearing every time launching on the cluster, even if it is launching on an existing cluster and the driver installation won't actually be executed. This PR fixes that.

Remove A10 warning when re-launching on existing cluster

---

sky/provision/kubernetes/utils.py

This distinguishes between `H100` and `H100-MEGA-80GB` on GKE. Closes #3890 
List gpus `H100` and `H100-MEGA-80GB` with `sky show-gpus --cloud kubernetes`
schedule a skypilot cluster on `H100` and `H100-MEGA-80GB` with `sky launch --cloud kubernetes --gpus {H100,H100-MEGA-80GB}`
Test output [here](https://gist.github.com/asaiacai/be2a95c31c4057fc10b5c47dc8866e57)

[k8s][GKE] distinguish between h100 and h100-mega on gke

---

sky/backends/backend_utils.py
sky/skylet/constants.py

Fixes https://github.com/skypilot-org/skypilot/pull/3874#discussion_r1731898801
Just found a more elegant way to do this..

Avoid using lambda in `skylet.constant`

---

sky/cli.py

As discussed in #3885.
I extend the bash command that installs the shell completion to explain to the user that their bash is too old, if the version check added in #2433 fails.

[Core] Inform user if bash too old for shell completion

---

sky/cli.py

With this pull request, `sky --install-shell-completion` searches the PATH for `bash` and rruns that version when it comes to installing shell completion, rather than systematically using `/bin/bash`.
Indeed we cannot assume that `/bin/bash` is the active bash. For example the system bash on macOS in `/bin/bash` is quite old (v3), so some users install bash v5 with homebrew, which installs in `/opt`, leaving `/bin` untouched.`
This matters because bash completion for skypilot requires bash >= v4.
Fixes https://github.com/skypilot-org/skypilot/issues/3885

[Core] Install completion using whichever bash in PATH

---

sky/backends/cloud_vm_ray_backend.py
sky/exceptions.py
tests/test_smoke.py

[Core] Add retry for ssh max length

---

sky/backends/cloud_vm_ray_backend.py
tests/test_smoke.py

This is to fix a missing line from #3884, where we should update the command used for `run` section.
Fixes #3900 

[Core] Fix dumping and retry for run section

---

sky/provision/kubernetes/utils.py
sky/templates/kubernetes-port-forward-proxy-command.sh

Switching the namespace of a kube context would cause `ssh my_cluster` to fail. This embeds the namespace into the ssh command so it doesn't lose track. 
Created a namespace, ran ssh, changed the kubeconfig namespace, ran ssh again.

Fix ssh breaking if kube context namespace changes

---

sky/adaptors/azure.py
sky/data/storage.py
tests/test_smoke.py

This updates the temporary solution implemented at #3791 
Error was incorrectly handled when the user attempted to access a private container without access. This PR fixes with correct error response.
```
sky.exceptions.StorageBucketGetError: Failed to access existing bucket 'test'. This is likely because it is a private bucket you do not have access to.
To fix:
1. If you are trying to create a new bucket: use a different name.
2. If you are trying to connect to an existing bucket: make sure your cloud credentials have access to it.
```

[Azure][Storage] Update Error response for accessing private container without access

---

sky/utils/kubernetes/generate_kubeconfig.sh

generate_kubeconfig.sh would fail when a cluster doesn't have ingress:
```
Error from server (NotFound): error when creating "STDIN": namespaces "ingress-nginx" not found
Error from server (NotFound): error when creating "STDIN": namespaces "ingress-nginx" not found
```
This PR makes it optional, and any errors due to ingress not being present are ignored.

[k8s] Fix generate_kubeconfig.sh when ingress is not used

---

sky/clouds/azure.py
sky/provision/azure/instance.py
sky/templates/azure-ray.yml.j2
tests/test_optimizer_dryruns.py

Added a high disk tier for Azure. The new tier uses P50 on Premium_LRS.
Discussions

[Core][Disk] High disk tier on Azure

---

examples/resnet_distributed_torch.yaml
examples/tpu/tpuvm_mnist.yaml

The test scripts has not been updated for long and there are some version compatibility issues. When running `tests/test_smoke.py::test_tpu_vm`, I encountered
```
File "/home/gcpuser/sky_workdir/flax/examples/mnist/main.py", line 29, in <module>
import train
File "/home/gcpuser/sky_workdir/flax/examples/mnist/train.py", line 25, in <module>
from flax import linen as nn
File "/home/gcpuser/sky_workdir/flax/flax/__init__.py", line 24, in <module>
from flax import core
File "/home/gcpuser/sky_workdir/flax/flax/core/__init__.py", line 24, in <module>
from .lift import (
File "/home/gcpuser/sky_workdir/flax/flax/core/lift.py", line 44, in <module>
from . import axes_scan, meta
File "/home/gcpuser/sky_workdir/flax/flax/core/meta.py", line 31, in <module>
from …
```

[Test] Resolve version compatibility issues in `tests/test_smoke.py`

---

docs/source/reference/config.rst
sky/data/storage.py

Adding ability to add tags from global config to buckets created

[AWS] Add tags on bucket creation time

---

sky/provision/__init__.py

Issues addressed
- #3813 
Changes made

Resolve param credential typo

---

sky/adaptors/kubernetes.py

If user uses disables tls for k8s with `insecure-skip-tls-verify` in their kubeconfig, urllib3 prints warnings for each connection:
```
/Users/romilb/tools/anaconda3/lib/python3.9/site-packages/urllib3/connectionpool.py:1103: InsecureRequestWarning: Unverified HTTPS request is being made to host '150.136.46.159'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
warnings.warn(
```
This PR disables warnings with the [method recommended](https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings) by urllib3.

[k8s] Suppress insecure request warnings

---

sky/provision/kubernetes/instance.py

Launching a CPU cluster on k3s cluster with the Nvidia GPU runtime class installed but no Nvidia GPU operator would stay stuck on launching with this error in `k describe pods`:
```
Warning  FailedCreatePodSandBox  0s (x3 over 28s)  kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to get sandbox runtime: no runtime for "nvidia" is configured
```
This PR adds a check for to add the nvidia runtime only if the Nvidia GPU operator is installed.

[k8s] Use default runtime on k3s for CPU tasks

---

sky/skylet/log_lib.py
sky/skylet/subprocess_daemon.py
tests/test_smoke.py

This resolves #3898.
We completely separate the `subprocess_daemony.py` process from `ray::task` process. Originally, `subprocess_daemon.py` was ran as child process of `ray::task` process, and this resulted in termination of the `subprocess_daemon.py` process as well when ray's `stop_job` API was ran to terminate `ray::task` process. And this resulted in failing to terminate all of `ray::task` process's child processes in the tree.
- `test_managed_jobs_storage`
- `test_multiple_accelerators_unordered_with_default`
- `test_tpu_vm_pod`
- `test_skyserve_fast_update`
- `test_tpu_vm`
- `test_managed_jobs_tpu`

[Core] Update subprocess_daemon.py to terminate all child processes from ray job when 'sky cancel' is ran 

---

sky/clouds/aws.py

A user reported that even if they have capacity reservation for a specific GPU, they cannot utilize them with SkyPilot because they have 0 on-demand quota for that GPU and our optimization for quota skips that region.
This PR skips the quota check when reservations are used.

[AWS] Avoid quota check when reservation is specified

---

sky/clouds/service_catalog/data_fetchers/fetch_gcp.py

Sometimes the return body of GCP is empty and that causes a key error in our fetcher. This happenes to zones that we does not have access to. This PR fixes the problem.
Reference: https://github.com/skypilot-org/skypilot-catalog/actions/runs/10800668225/job/29959644303
```bash
WARNING:googleapiclient.http:Encountered 403 Forbidden with reason "PERMISSION_DENIED"
TPU API is not enabled or you don't have TPU access to zone: 'asia-east1-a'.
File "/home/txia/miniconda3/envs/sky-serve/lib/python3.9/runpy.py", line 197, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/home/txia/miniconda3/envs/sky-serve/lib/python3.9/runpy.py", line 87, in _run_code
exec(code, run_globals)
File …
```

[Catalog] Fix GCP Fetcher

---

sky/clouds/gcp.py
sky/clouds/service_catalog/gcp_catalog.py

https://cloud.google.com/compute/docs/disks/extreme-persistent-disk#machine_shape_support
On GCP, disk tier ultra only supports handful of instance type. This PR adds the check and fixes #3933.
From the documentation, it seems like we could still attach the pd-extreme disk to some instance type but will get a degraded performance. We should benchmark and see how severe the degradation is, as the instance type that officially supports the ultra tier is too small (no GPU instance types is officially supported).

[GCP][Disk] Add supported instance type check for disk tier ultra

---

tests/kubernetes/README.md

Adds quick instructions to mock GPU nodes on `sky local up` clusters to our dev testing guide for Kubernetes.

[k8s][dev] Instructions to mock GPU node

---

sky/clouds/service_catalog/__init__.py

TPU table is outdated in `sky show-gpus`, shows v2 and v3 only:
Before:
```
GOOGLE_TPU   AVAILABLE_QUANTITIES
tpu-v2-8     1
tpu-v2-32    1
tpu-v2-128   1
tpu-v2-256   1
tpu-v2-512   1
tpu-v3-8     1
tpu-v3-32    1
tpu-v3-64    1
tpu-v3-128   1
tpu-v3-256   1
tpu-v3-512   1
tpu-v3-1024  1
tpu-v3-2048  1
```
After:
```
GOOGLE_TPU         AVAILABLE_QUANTITIES
tpu-v2-512         1
tpu-v3-2048        1
tpu-v4-8           1
tpu-v4-16          1
tpu-v4-32          1
tpu-v4-3968        1
tpu-v5litepod-1    1
tpu-v5litepod-4    1
tpu-v5litepod-8    1
tpu-v5litepod-256  1
tpu-v5p-8          1
tpu-v5p-32         1
tpu-v5p-128        1
tpu-v5p-12288      1
```

[TPUs] Update sky show-gpus for TPUs

---

llm/pixtral/pixtral.yaml

Recent Pixtral model on HF requires login. This PR adds `HF_TOKEN` for the access.

[LLM] Add huggingface token due to recent change of Pixtral on HF

---

llm/yi/README.md
llm/yi/qwen2-7b.yaml
llm/yi/yi15-34b.yaml
llm/yi/yi15-6b.yaml
llm/yi/yi15-9b.yaml
llm/yi/yicoder-1_5b.yaml
llm/yi/yicoder-9b.yaml

Integrating the Yi series models.We have added several files that utilize the Yi models.

Integrating the Yi series models

---

tests/skyserve/update/bump_version_after.yaml
tests/skyserve/update/bump_version_before.yaml

This PR fixes a bug for smoke test `test-skyserve-fast-update` in latest master.
Related: https://github.com/skypilot-org/skypilot/pull/3832#discussion_r1763927901

[Test] Fix Smoke Test `test-skyserve-fast-update`

---

llm/qwen/README.md
llm/qwen/qwen2-vl-7b.yaml

[LLM] Add Qwen2-VL multimodal example

---

sky/backends/cloud_vm_ray_backend.py

This PR sets the serve controller to autodown (instead of being left to run indefinitely) when running on Kubernetes. This is to avoid dangling controllers.

[k8s] Autodown Serve controller on Kubernetes

---

tests/skyserve/update/bump_version_after.yaml
tests/skyserve/update/bump_version_before.yaml

git cloning SkyPilot repo takes too long for the test, making the test fail due to initial delay exceed.

[Tests] Add missing changes from #3966 for fast service update test

---

sky/provision/paperspace/constants.py

adds some new paperspace gpus. closes #3988 and depends on skypilot-org/skypilot-catalog#85
```
sky launch --cloud paperspace --gpus {M4000,P4000,P4000:2,A4000,A4000:2,A4000:4} -y -d
```

[Paperspace] add A4000, P4000, GPU+

---

docs/source/examples/auto-failover.rst
sky/execution.py
sky/optimizer.py
sky/sky_logging.py
sky/utils/controller_utils.py
sky/utils/env_options.py

`sky launch --gpus T4`
Before:
After:

[UX] default to minimal logging (no module/line number/timestamp).

---

docs/source/examples/docker-containers.rst
docs/source/reference/kubernetes/kubernetes-getting-started.rst

Current docs are confusing because private registry instructions don't apply to k8s. This PR adds a note for k8s with appropriate pointers.

[Docs] Clarify k8s private registry usage in docs

---

README.md
docs/source/_gallery_original/index.rst
docs/source/_static/custom.js
docs/source/docs/index.rst
llm/llama-2/README.md
llm/llama-3/README.md
llm/llama-3_2/README.md

[Docs] Various polishing.

---

examples/deepspeed-multinode/sky.yaml

Adds example for how to pass environment variables to deepspeed jobs.

[Examples] Add env vars to deepspeed example

---

sky/authentication.py
sky/clouds/kubernetes.py
sky/provision/kubernetes/config.py
sky/provision/kubernetes/instance.py
sky/provision/kubernetes/network_utils.py
sky/provision/kubernetes/utils.py
sky/utils/command_runner.py
sky/utils/command_runner.pyi
sky/utils/controller_utils.py

In-cluster auth broke after our recent multi-context support. This is because incluster auth does not have any kubeconfig (and consequently, does not have any contexts) and relies solely on mounted service accounts.
As a result, SkyServe controller (and sky jobs controller) was not able to launch replicas.
This PR fixes it by making context optional throughout our codebase, and using the in-cluster auth when context is not detected.
Note: we probably need to update our docs/elsewhere to mention that multiple contexts may not work when the controller runs in a Kubernetes cluster.
Tested

[k8s] Fix incluster auth after multi-context support

---

sky/resources.py
tests/unit_tests/test_resources.py

[Fix #3965] If users use resource labels, they no longer need to specify `cloud` under Resource. For example, they can do
```
resources:
labels:
abc: test
```
If `cloud` is not specified, we validate each label against ALL clouds, so if the label doesn't work for any one of the clouds, the label will not get passed down to any clouds.

[UX] Remove requirement to specify cloud in Resources to use labels

---

sky/jobs/state.py
sky/serve/autoscalers.py
sky/serve/controller.py
sky/serve/load_balancer.py
sky/serve/replica_managers.py
sky/serve/serve_state.py
sky/serve/service.py

This PR refactors multiple files within the Serve module to address type-checking errors and improve type annotations. Key changes include:
- Adjustments to method signatures and variable types in modules like autoscalers.py and replica_managers.py for better type safety.
- Modifications to ensure consistent use of `aiohttp.ClientTimeout` in load_balancer.py to prevent timeouts.
- Refactoring of methods in serve_state.py to make paths considered as `str` rather than `str | Path` using helper functions.
- Cleaning up and streamlining processes in service.py for managing service states and cleanup tasks.

[Serve] Refactor to Fix Type Checking Errors

---

sky/serve/controller.py

Fixes #3997
Replace deprecated `@app.on_event('startup')` decorator with lifespan event handler in `sky/serve/controller.py`.
* Remove the `@app.on_event('startup')` decorator.
* Add a lifespan event handler to configure the logger.
* Update the `SkyServeController` class to use the lifespan event handler.

Stop using deprecated `on_event()` decorator

---

docs/source/reference/kubernetes/kubernetes-ports.rst

Adds docs for internal load balancers for AWS, GCP and Azure.

[docs] Add docs for internal load balancers on k8s

---

sky/serve/controller.py
sky/serve/serve_utils.py
sky/utils/subprocess_utils.py

Fixes #4030
Address error handling inconsistency in service update process.
* **sky/serve/controller.py**
- Modify `/controller/update_service` endpoint to return appropriate HTTP status codes.
- Return 400 for client errors and 500 for server errors.
- Use `responses.JSONResponse` for returning responses.
* **sky/serve/serve_utils.py**
- Update `update_service_encoded` function to handle different status codes.
- Raise exceptions based on the response body for 400 and 500 status codes.
* **sky/utils/subprocess_utils.py**
- Add `stream_logs` parameter in the comment to reflect the code.

Fix error handling in service update process

---

sky/clouds/aws.py
sky/templates/aws-ray.yml.j2

Usage of IDMSv2 is considered a best practice for security. To facilitate [fully disabling IDMSv1](https://aws.amazon.com/blogs/security/get-the-full-benefits-of-imdsv2-and-disable-imdsv1-across-your-aws-infrastructure/) we should switch to using v2 everywhere.
This change was tested manually on an ec2 instance using this test script:
```
import subprocess
from typing import Optional
class Constants:
SKY_PYTHON_CMD = "python3"  # Assuming this is what constants.SKY_PYTHON_CMD refers to
constants = Constants()
class EC2InstanceMetadata:
@classmethod
def get_zone_shell_cmd(cls) -> Optional[str]:
command_str = (
'TOKEN=`curl -X PUT "http://169.254.169.254/latest/api/token" '
'-H "X-aws-ec2-metadata-token-ttl-seconds: 21600"` && '
'curl -H "X-aws-ec2-metadata-token: $TOKEN" -s ' …
```

aws: use IDMSv2 in zone shell cmd

---

sky/provision/paperspace/instance.py

Increases the paperspace `MAX_POLLS_FOR_UP_OR_STOP` from 8 to 16 minutes.
Spawning a larger number of CPU instances on paperspace can be quite slow. I've had to manually monkeypatch this limit several times to spawn a C8 clusters on paperspace. This is definitely set too low.

Up paperspace MAX_POLLS_FOR_UP_OR_STOP

---

sky/utils/command_runner.py
sky/utils/kubernetes/rsync_helper.sh

Currently, when context name contains `:` or `/`, rsync can wrongly parse the string to be passed to our rsync_helper. We now escape those special characters.
Tested with a context and namespace: `arn:xxx:xxx:xx-xxx-x:xxx:cluster/xxx` and `test-namespace`

[k8s] Fix rsync for context name with `:` and `/`

---

sky/cli.py
sky/data/storage_utils.py
sky/jobs/__init__.py
sky/jobs/core.py
sky/jobs/utils.py
sky/provision/kubernetes/utils.py
sky/utils/cli_utils/status_utils.py
sky/utils/common_utils.py

Adds a `--kubernetes` flag to `sky status` to show the global state of the Kubernetes cluster, including SkyPilot clusters created by other users. Helps users see the current state of the Kubernetes cluster.
Example:
```
(base) ➜  sky-experiments git:(k8s_global_status) ✗ sky status --kubernetes
SkyPilot Clusters on Kubernetes
NAME        USER    LAUNCHED     RESOURCES                                      STATUS  
test-2ea4   romilb  45 secs ago  2x Kubernetes(cpus=2.0, mem=2.0)               UP      
train-j49a  test    1 min ago    2x Kubernetes(cpus=2.0, mem=8.0, {'H100': 1})  UP     
```
TODO:

[k8s] Add `sky status` flag to query global Kubernetes status

---

sky/clouds/oci.py

1.  Bug fix for sky config file path resolution:
This bug will cause the created workder nodes located in different compartment and VCN than the header node if user specifies compartment_id in the sky config file, because the ~/.sky/config is not sync-ed to the remote machine. 
The workaround is to set the sky config file path using ENV before running
the sky launch: export SKYPILOT_CONFIG=/home/ubuntu/.sky/config.yaml 
2.  Bug fix for image_id in task YAML:
We can specify the image to use for node provision by setting the image_id parameter in the task YAML.  The image_id in the task YAML can be an tag in the images.csv catalog file such as skypilot:gpu-ubuntu-2004. 
Some customers would also perfer to specify the ocid of the image in the image_id field, and we already supported this in …

[OCI]: Bug fix: 1. sky config file path resolution. 2. fill in image_id as ocid in task YAML

---

sky/skylet/job_lib.py
sky/utils/db_utils.py

Issues Addressed
- #3863 
Changes Made

[Core] Turn on WAL mode for cluster job table

---

docs/source/reference/kubernetes/kubernetes-ports.rst

Removes tab-set to make docs easier to search through.

[docs] Unroll k8s internal load balancer docs

---

docs/source/reference/kubernetes/kubernetes-getting-started.rst
docs/source/reference/kubernetes/kubernetes-setup.rst

[docs] `sky status --kubernetes` docs

---

sky/backends/cloud_vm_ray_backend.py
sky/provision/provisioner.py
sky/utils/ux_utils.py

Previously, when the window is narrow the logger output can be messed up due to the overflow of the status.
Also, in this PR, we should the log path after failure happens for skypilot runtime setup

[UX] Show log after failure and fix the color issue with narrow window

---

sky/clouds/gcp.py
sky/skylet/constants.py

Use the new custom image for GCP's GPU VM creation. 
Benchmark results:
|  VM Type 💻   | Old Provision 🕐                 | New Provision 🕐     | % Improvement ✅ |
| --------------- | ---------------------------- | ----------- | ----------- |
| GCP GPU      | 3min 35s      | 1min 15s    | 65% |
| AWS GPU       | 3min 30s     | 2min 20s | 30% |
| GCP CPU       | 1min 45s   | 1min 10s | 32% |
* Provision Time = from start of launching an instance to instance setup and ready to run any user workloads (does not include time to search for the available instance)

[Performance] Use new GCP custom images

---

sky/clouds/gcp.py
sky/clouds/service_catalog/data_fetchers/fetch_gcp.py
sky/clouds/service_catalog/gcp_catalog.py

```
(sky-cmd, pid=13008) Thu Oct 17 01:47:13 2024       
(sky-cmd, pid=13008) +---------------------------------------------------------------------------------------+
(sky-cmd, pid=13008) | NVIDIA-SMI 535.183.06             Driver Version: 535.183.06   CUDA Version: 12.2     |
(sky-cmd, pid=13008) |-----------------------------------------+----------------------+----------------------+
(sky-cmd, pid=13008) | GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
(sky-cmd, pid=13008) | Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
(sky-cmd, pid=13008) |                                         |                      |               MIG M. |
(sky-cmd, pid=13008) …
```

[GCP] Add H100 mega

---

docs/source/reference/config.rst
sky/clouds/gcp.py
sky/provision/gcp/config.py
sky/templates/gcp-ray.yml.j2
sky/utils/schemas.py

Adds gVNIC support. 
Throughput on gvnic is 1.8x higher than regular virtio NICs. Benchmarks: https://gist.github.com/romilbhardwaj/89f8399d8a5307df5d880cf1495ce957

[GCP] Add gVNIC support

---

docs/source/reference/kubernetes/kubernetes-deployment.rst

GKE no longer requires manual driver installation for [1.30.1-gke.1156000](https://cloud.google.com/kubernetes-engine/docs/how-to/gpus#create-gpu-pool-auto-drivers) and later. Updating our docs to reflect this

[Docs] GKE Nvidia Driver installation instructions update

---

sky/clouds/aws.py

Use the new custom image for AWS's VM creation. 
Benchmark results:
|  VM Type 💻   | Old Provision 🕐                 | New Provision 🕐     | % Improvement ✅ |
| --------------- | ---------------------------- | ----------- | ----------- |
| AWS GPU      | 2min 27s      | 1min 41s    | 31% |
| AWS CPU       | 2min 44s   | 1min 13s | 56% |
* Provision Time = from start of launching an instance to instance setup and ready to run any user workloads (does not include time to search for the available instance)

[Performance] Use new AWS custom images

---

docs/source/examples/syncing-code-artifacts.rst
docs/source/reference/yaml-spec.rst

[Docs] .skyignore doc

---

sky/backends/backend_utils.py

The original assertion is not well handled in sky serve, when the cluster is preempted.

[Core] Raise error for none existing cluster when endpoint is called

---

sky/clouds/service_catalog/aws_catalog.py

refresh local images.csv by pulling from github catalog again

Refresh local aws images.csv when image not found

---

sky/clouds/azure.py
sky/clouds/gcp.py
sky/clouds/lambda_cloud.py
sky/provision/docker_utils.py
sky/provision/paperspace/utils.py
sky/resources.py
sky/templates/lambda-ray.yml.j2
sky/utils/command_runner.py

Support docker as runtime on Lambda Cloud and TPU. TPU part is inherit from #3819.

[Provisioner] Support docker in Lambda Cloud and TPU

---

sky/serve/serve_utils.py

Fixes #4096
Add `ux_utils.print_exception_no_traceback()` to error handling blocks in `sky/serve/serve_utils.py` to simplify error messages and reduce traceback clutter.
* Add `ux_utils.print_exception_no_traceback()` to the error handling block in the `set_service_status_and_active_versions_from_replica` function.
* Add `ux_utils.print_exception_no_traceback()` to the error handling block in the `_get_service_status` function.
* Add `ux_utils.print_exception_no_traceback()` to the error handling block in the `update_service_encoded` function.
* Add `ux_utils.print_exception_no_traceback()` to the error handling block in the `check_service_status_healthy` function.
* Add `ux_utils.print_exception_no_traceback()` to the error handling block in the `stream_replica_logs` function.

[Serve] Add `ux_utils.print_exception_no_traceback()` for cleaner error output

---

sky/serve/serve_utils.py

Accidentally added wrappers around some return statements in the previous #4111 
This PR removes these unnecessary wrappers while keeping other intended changes.

Partially revert: Remove unnecessary `ux_utils.print_exception_no_traceback()` wrappers

---

examples/deepspeed-multinode/sky.yaml

Our deepspeed example requires versioning pinning due to deprecation of `transformers.deepspeed` module.
Also adds specific instructions for k8s (related to #4122).
Tested on GCP and Kubernetes A100s.

[examples] Deepspeed fixes + k8s support

---

sky/clouds/service_catalog/data_fetchers/fetch_gcp.py

Our GCP fetcher fails again. Silently ignore this before we figured out why.
https://github.com/skypilot-org/skypilot-catalog/actions/runs/11449564946/job/31855393437

[Catalog] Silently ignore TPU price not found.

---

README.md
docs/source/cloud-setup/quota.rst
docs/source/getting-started/quickstart.rst
docs/source/reference/job-queue.rst
docs/source/reference/kubernetes/kubernetes-setup.rst
docs/source/reference/yaml-spec.rst
docs/source/running-jobs/distributed-jobs.rst
llm/vllm/README.md

Updates GPUs used in our docs from V100 to A100 or H100. A100:8 is used at many places because it's a configuration that is available across all 3 hyperscalers (AWS, GCP, Az). Other places use H100 to showcase the use of latest GPUs.
`tutorial.rst` and `distributed-jobs.rst` will be updated in a separate PR with a newer example (newer than BERT).
`managed-jobs.rst` will stay with V100s for now because the plots use V100 BERT training. 
Similarly `benchmark/*.rst` will also continue to use V100s because the benchmark measurements shown in examples are based on V100s..

[docs] Update GPUs used in docs

---

sky/utils/kubernetes/k8s_gpu_labeler_job.yaml

GPU labelling pods would fail on EKS with this error:
```
Events:
Type     Reason     Age   From               Message
----     ------     ----  ----               -------
Normal   Scheduled  25m   default-scheduler  Successfully assigned kube-system/sky-gpu-labeler-6d605bbb187adc86ce55ad1b77759882-6nrsm to ip-192-168-55-105.ec2.internal
Normal   Pulling    25m   kubelet            Pulling image "us-central1-docker.pkg.dev/skypilot-375900/skypilotk8s/skypilot-gpu:latest"
Normal   Pulled     24m   kubelet            Successfully pulled image "us-central1-docker.pkg.dev/skypilot-375900/skypilotk8s/skypilot-gpu:latest" in 55.832s (55.832s including waiting)
Normal   Created    24m   kubelet            Created container gpu-labeler
Warning  Failed     24m   kubelet            Error: failed to …
```

[k8s] Fix GPU labeling for EKS

---

sky/utils/command_runner.py
sky/utils/kubernetes/rsync_helper.sh

eksctl generates context names like `romildev@my-cluster.us-east-1.eksctl.io`. 
The `@` in the context name causes our rsync pipeline to crash.
This PR adds handling for `@` in context name.

[k8s] Handle @ in context name

---

sky/cli.py

Fish will automatically pick up the completions and does not need to be reloaded. Remove the message about reloading config.fish, which isn't necessary and won't do anything.
Didn't seem like there were really any particularly relevant tests for this.

[cli] remove shell reload message for fish

---

docs/source/reference/kubernetes/kubernetes-getting-started.rst

[k8s] Add info on base images used for k8s

---

sky/provision/kubernetes/instance.py
sky/provision/provisioner.py

Runs ssh initialization and setup asynchronously for faster startup. Closes #4156 

multithreaded ssh setup

---

docs/source/reference/kubernetes/kubernetes-deployment.rst
docs/source/reference/kubernetes/kubernetes-getting-started.rst
docs/source/reference/kubernetes/kubernetes-setup.rst
docs/source/reservations/existing-machines.rst
examples/k8s_cloud_deploy/README.md
sky/cli.py
sky/clouds/service_catalog/kubernetes_catalog.py

Users were confused by `QTY_PER_NODE` in our show-gpus output. This PR changes it to `REQUESTABLE_QTY_PER_NODE`. Also updates the quantities to be shown in powers of 2.
Tested:

[k8s] Rename show-gpus field to `REQUESTABLE_QTY_PER_NODE`

---

examples/serve/http_server/task.yaml
sky/utils/controller_utils.py
tests/unit_tests/test_controller_utils.py

[Serve] Make controller regions/ choose from replica resources

---

sky/clouds/azure.py
sky/clouds/service_catalog/azure_catalog.py
sky/clouds/utils/azure_utils.py
sky/resources.py
tests/unit_tests/test_azure_utils.py

You can pass an Azure community gallery image as `image-id` arg at `sky launch`.
You can find all available community images in Azure console: https://portal.azure.com/?feature.msaljs=true#browse/Microsoft.Compute%2Flocations%2FcommunityGalleries%2Fimages 
```
sky launch --cloud=azure --region <region> --image-id=/CommunityGalleries/<gallery-name>/Images/<image-definition-name>
```
Invalid image ID: `sky launch --cloud=azure -y --image-id=xx`
Valid community image: `sky launch --cloud=azure -y -t Standard_B2s --region centralus --image-id=/CommunityGalleries/skypilot-fc3311ab-d34c-4589-b2fb-a95b8a84ceb1/Images/skypilot-cpu-gen2`
Invalid community image: `sky launch --cloud=azure -y -t Standard_DS1_v2 --region westus2 …

[Performance] Allow users to pass in Azure community images at --image-id

---

sky/clouds/azure.py
sky/clouds/service_catalog/azure_catalog.py

Use the new custom image for Azure's VM creation. 
Example performance change (with fixed region):
|  VM Type 💻   | Old Provision 🕐                 | New Provision 🕐     | % Speedup ✅ |
| --------------- | ---------------------------- | ----------- | ----------- |
| Azure GPU      |   4min    | 2min 40s   | 35% (1.5x) |
| Azure CPU       |  4min  | 2min |  50% (2x) |
Example benchmark commands:
CPU: `time sky launch --cloud=azure --region=centralus -y`
GPU: `time sky launch --cloud=azure --region=centralus -y --gpus=A100-80GB:1`
`pytest tests/test_smoke.py::test_minimal --azure`
`pytest tests/test_smoke.py::test_huggingface --azure`
`pytest tests/test_smoke.py::test_job_queue_with_docker --azure`
`pytest tests/test_smoke.py::test_cancel_azure`

[Performance] Use new Azure custom images

---

sky/clouds/oci.py

Putting ImportError and oci_adaptor.oci.exceptions.ConfigFileNotFound on the same line will fail to catch ImportError caused by oci_adaptor.oci.exceptions.ConfigFileNotFound

Fix OCI import issue

---

sky/provision/kubernetes/instance.py

[k8s] Add retry for apparmor failures

---

docs/source/examples/managed-jobs.rst

The prev version reads better.

Minor: Jobs docs fix.

---

docs/source/examples/managed-jobs.rst
docs/source/reference/faq.rst
examples/managed_job_with_storage.yaml
llm/axolotl/axolotl-spot.yaml
llm/axolotl/readme.md
llm/falcon/README.md
llm/vicuna-llama-2/README.md
llm/vicuna/README.md
sky/cli.py
sky/jobs/controller.py
tests/backward_compatibility_tests.sh

There are a few lingering uses of the `sky spot` CLI, which has been deprecated since v0.6.0. Replace them with `sky jobs`.
- starting from 7

[UX] remove all uses of deprecated `sky jobs`

---

sky/dag.py
sky/jobs/core.py

Replace `is_chain()` with `is_dag()` check to:
1. Enable future DAG execution support
2. Validate DAG structure before job launch
Also, Lets create another PR to check the inputt graph is a connected DAG?
_Originally posted by @cblmemo in https://github.com/skypilot-org/skypilot/pull/4128#discussion_r1817400139_

[Job] Support DAG execution by replacing `is_chain` with `is_dag` check

---

sky/jobs/controller.py

Extract repeated task failure state update logic into `_update_failed_task_state()` helper to reduce code duplication.
Good catch! Could submit this change to master first.
_Originally posted by @cblmemo in https://github.com/skypilot-org/skypilot/pull/4128#discussion_r1817404695_

[Jobs] Refactor: Extract task failure state update helper

---

sky/backends/backend_utils.py
sky/backends/cloud_vm_ray_backend.py
sky/provision/gcp/instance.py
sky/serve/core.py
sky/serve/serve_state.py
sky/serve/serve_utils.py
sky/serve/service_spec.py
sky/skylet/job_lib.py
sky/skylet/log_lib.py
sky/utils/schemas.py
tests/test_jobs_and_serve.py
tests/test_smoke.py

Try to remve backward compatibility code for 0.6.0 & 0.7.0

[Core] Remove backward compatibility code for 0.6.0 & 0.7.0

---

sky/backends/cloud_vm_ray_backend.py

This PR removes the outdated pylint disabling comments related to `abstract-class-instantiated` in the `cloud_vm_ray_backend.py` file. The comments were no longer necessary as the filelock version has been updated.

Remove outdated pylint disabling comments

---

tests/conftest.py

generic_cloud default gcp -> aws
default enabled clouds [gcp, azure] -> [aws, azure]

[test] update default clouds for smoke tests

---

format.sh

Use a similar approach to what we do with yapf to limit pylint to only files that have changed from master.
On my machine this shaves about a minute off pylint runtime, making pylint 7-8x faster and format.sh 3-4x faster.

[dev] restrict pylint to changed files

---

sky/backends/cloud_vm_ray_backend.py
sky/clouds/azure.py
sky/clouds/service_catalog/images/README.md
sky/clouds/service_catalog/images/provisioners/cuda-azure-grid.sh
sky/clouds/service_catalog/images/skypilot-aws-cpu-ubuntu.pkr.hcl
sky/clouds/service_catalog/images/skypilot-aws-gpu-ubuntu.pkr.hcl
sky/clouds/service_catalog/images/skypilot-azure-cpu-ubuntu.pkr.hcl
sky/clouds/service_catalog/images/skypilot-azure-gpu-ubuntu.pkr.hcl
sky/clouds/service_catalog/images/skypilot-gcp-cpu-ubuntu.pkr.hcl
sky/clouds/service_catalog/images/skypilot-gcp-gpu-ubuntu.pkr.hcl
sky/provision/azure/instance.py
sky/templates/azure-ray.yml.j2

Use the new custom image for Azure's A10 VM creation. 
Example performance change (with fixed region):
|  VM Type 💻   | Old Provision 🕐                 | New Provision 🕐     | % Speedup ✅ |
| --------------- | ---------------------------- | ----------- | ----------- |
| Azure GPU      |   21min    | 2min 50s   | 85% (7x) |

[Performance] Speed up Azure A10 instance creation

---

examples/managed_job_with_storage.yaml

sky-imagenet-data is no longer public. Changes to an actual public S3 bucket.

[Tests] Fix public bucket tests

---

sky/clouds/service_catalog/data_fetchers/fetch_gcp.py

This PR adds hardcoded TPU V6e price to our catalog. Currently, TPU V6e is not in [GPC SKUs](https://cloud.google.com/skus?hl=en&filter=tpu&currency=USD), so we use the pricing in [GCP TPU Pricing](https://cloud.google.com/tpu/pricing) first.
There are some missing zones in the pricing page and I set their price to 0.0 so user can launch on those regions.
The hardcode catalog is generated by this script:
```python
zones = ['us-east5-b', 'us-east5-c', 'us-south1-a', 'europe-west4-a', 'us-central1-c', 'us-south1-c', 'us-central1-b', 'asia-northeast1-b', 'us-east1-d', 'us-central2-b']
acc_nums = [1, 4, 8, 16, 32, 64, 128, 256]
region2price = {
'us-east1': 2.7,
'us-east5': 2.7,
'europe-west4': 2.97,
'asia-northeast1': 3.24,
}
no_pricing_info_region = set()
for n in acc_nums:
acc_name = …
```

[Catalog] Add TPU V6e.

---

tests/conftest.py
tests/test_smoke.py

Changes:
* **don't wait for old pending jobs controller messages**
`sky jobs queue` used to output a temporary "waiting" message while the managed jobs controller was still being provisioned/starting. Since #3288 this is not shown, and instead the queued jobs themselves will show PENDING/STARTING.
This also requires some changes to tests to permit the PENDING and STARTING states for managed jobs.
* **wait for RECOVERING more quickly**
Smoke tests were failing because some managed jobs were fulling recovering back to the RUNNING state before the smoke test could catch the RECOVERING case (see e.g. #4192 `test_managed_jobs_cancellation_gcp`). Change tests that manually terminate a managed job instance, so that they will wait for the managed job to change away from the RUNNING state, …

[test] smoke test fixes for managed jobs

---

sky/backends/cloud_vm_ray_backend.py

A user reported that they saw an error that shows `cluster_yaml` somehow becomes `/local~/.sky/...` which is likely due to the replacement of home dir not very robust. This PR makes it more robust.

[Core] Make home address replacement more robust

---

sky/cli.py
sky/jobs/core.py

This flag will make the jobs controller launch use `sky launch --fast`. There
are a few known situations where this can cause misbehavior in the jobs
controller:
- The SkyPilot wheel is outdated (due to changes in the SkyPilot code or a
version upgrade).
- The user's cloud credentials have changed. In this case the new credentials
will not be synced, and if there are new clouds available in `sky check`, the
cloud depedencies may not be correctly installed.
However, this does speed up `jobs launch` _significantly_, so provide it as a
dangerous option. Soon we will add robustness checks to `sky launch --fast` that
will fix the above caveats, and we can remove this flag and just enable the
behavior by default.

[ux] add sky jobs launch --fast

---

sky/backends/backend_utils.py

Previously for controller process on the `sky queue sky-jobs-controller-<hash>`, we are showing `CPU:8` as the resources, it is a bit confusing for how many jobs can be run in parallel. This PR makes it `CPU:0.25` instead.
See job ID 10 (new) vs job ID 9 (old)
```bash
$ sky queue sky-jobs-controller-a37461fd 
Fetching and parsing job queue...
Job queue of cluster sky-jobs-controller-a37461fd
ID  NAME                         SUBMITTED    STARTED      DURATION    RESOURCES     STATUS     LOG                                        
10  test                         39 secs ago  34 secs ago  34s         1x[CPU:0.25]  RUNNING    ~/sky_logs/sky-2024-10-31-18-18-15-660126  
9   test                         5 mins ago   5 mins ago   1m 24s      1x[CPU:8.0]   SUCCEEDED …
```

[UX] Show 0.25 on controller queue

---

sky/data/storage.py
tests/test_smoke.py

Mitigates #3405 by defaulting to `us-east-1` if any opt-in region is specified. This is only a band-aid, we should implement a proper fix for #3405 soon.
`eu-south-1` often gets picked up for the cheapest spot CPU region, so mitigating this for 0.7 release is critical.
Tested with `sky launch` with `us-east-1` and `eu-south-1`. 
Also has a minor fix for smoke tests.

[Storage] Avoid opt-in regions for S3

---

sky/skylet/constants.py

Solve https://github.com/skypilot-org/skypilot/issues/4097
Remove the flag so that sky's venv won't link to the global (system) site-packages directory which can be modified by users.
No regression on latency for all clouds.

Remove --system-site-packages when setup sky cluster

---

Dockerfile
sky/__init__.py
sky/data/storage.py
tests/test_smoke.py

```
sky jobs launch --gpus A100:8 --cloud aws echo hi -y
sky jobs logs --controller
```
```
sky down dbg
```

[Release] Release 0.7.0

---

sky/clouds/aws.py
sky/clouds/azure.py

A user reported that a error occurs during the resource cleanup on jobs controller triggered by `sky jobs cancel`, and the cleanup of the resources did not complete, although we have the retry setup for teardown: https://github.com/skypilot-org/skypilot/blob/17a1fee67d2daa38f48509a1f90d19b99b5aad56/sky/jobs/controller.py#L465
```
botocore.exceptions.NoCredentialsError: Unable to locate credentials
```
The credential issue could be caused by the assumed role of the controller being rotated, and our dag creation from yaml causes an issue with the resource validation (when `image_id` is specified), even before we get to the teardown retries:
https://github.com/skypilot-org/skypilot/blob/17a1fee67d2daa38f48509a1f90d19b99b5aad56/sky/jobs/controller.py#L460-L469
This PR gets rid of the …

[AWS/Azure] Avoid error out during image size check

---

sky/templates/aws-ray.yml.j2

Related to #4246
Master:
```
multitime -n 5 sky launch --cpus 2 --use-spot -y --region us-east-2 --down
===> multitime results
1: sky launch --cpus 2 --use-spot -y --region us-east-2 --down
Mean        Std.Dev.    Min         Median      Max
real        44.757      2.256       42.070      44.111      48.014      
user        4.977       0.757       4.574       4.605       6.490       
sys         0.482       0.053       0.442       0.454       0.585   
```
Current:
```
===> multitime results
1: sky launch --cpus 2 --use-spot -y --region us-east-2 --down
Mean        Std.Dev.    Min         Median      Max
real        46.844      2.892       43.189      46.732      51.460      
user        4.856       0.579       4.508       4.587       6.013       
sys         0.511       0.070       0.437 …
```

[AWS] Disable additional auto update services for ubuntu image with cloud-init

---

sky/clouds/service_catalog/images/aws_utils/image_gen.py
sky/clouds/service_catalog/images/provisioners/skypilot.sh
sky/templates/aws-ray.yml.j2

Disable more potential unattended upgrade sources for AWS

---

docs/source/getting-started/installation.rst

This PR is to clarrify the key_file path configuration in the oci config file.

[docs]: OCI key_file path clarrification

---

sky/provision/kubernetes/instance.py
sky/utils/command_runner.py
sky/utils/subprocess_utils.py

Parallelizes env var init and privilege check steps in our k8s provisioning pipeline. 3x speedup for a 20 node cluster (and larger speedup for bigger clusters).
Measuring pod init time for `sky launch -c k8s --num-nodes 20 --cpus 1 -- echo hi`:
Master: 117s
This PR: 36s

[k8s] Parallelize setup for faster multi-node provisioning

---

sky/backends/cloud_vm_ray_backend.py
sky/provision/instance_setup.py

Should fix #4199.
Note: we can't use the subprocess log filtering in _handle_io_stream because the stderr output we see is from the ray invocation, within the run script itself (not in the subprocess).

do not redirect stderr to /dev/null when submitting job

---

sky/provision/lambda_cloud/lambda_utils.py
sky/skylet/providers/scp/node_provider.py

This pull request simply updates comments pointing to [Lambda's docs](https://docs.lambdalabs.com/).

Update comments pointing to Lambda's docs

---

examples/multi_echo.py
sky/skylet/events.py
sky/skylet/job_lib.py
tests/test_smoke.py
tests/test_yamls/pipeline_aws.yaml

Fixes #4263 
It also speed up the job scheduling by avoid update status for all the jobs:
Previously, gap between jobs to be scheduled is ~4-5s, ie with 60s duration of a task, there will be 12 jobs running in parallel (the additional RUNNING (with more than 1 min job duration) ones below are invoking the scheduling step for jobs which takes a long time waiting for the job scheduler to finish).
```
221  sky-cmd  11 mins ago  -               -         1x[CPU:1+]  PENDING    ~/sky_logs/sky-2024-11-05-19-30-10-870719  
220  sky-cmd  11 mins ago  -               -         1x[CPU:1+]  PENDING    ~/sky_logs/sky-2024-11-05-19-30-09-092916  
219  sky-cmd  11 mins ago  -               -         1x[CPU:1+]  PENDING    ~/sky_logs/sky-2024-11-05-19-30-07-104709  
218  sky-cmd  11 mins ago  - …
```

[Core] Avoid PENDING job to be set to FAILED and speed up job scheduling

---

sky/provision/instance_setup.py

This pull request sets the minimum port number a Ray worker can listen on to 11002. Without this change, when running [examples/k8s_cloud_deploy/launch_k8s.sh](https://github.com/skypilot-org/skypilot/blob/master/examples/k8s_cloud_deploy/launch_k8s.sh), k3s/containerd will fail with the error:
```
/var/lib/rancher/k3s/agent/containerd/containerd.log
time="2024-11-06T18:12:48.119844117Z" level=fatal msg="Failed to run CRI service" error="stream server error: listen tcp 127.0.0.1:10010: bind: address already in use"
```
See:
- https://github.com/skypilot-org/skypilot/pull/3929
- https://github.com/k3s-io/k3s/issues/4984

Set minimum port number a Ray worker can listen on to 11002

---

docs/build.sh
docs/source/reference/kubernetes/kubernetes-deployment.rst
docs/source/reference/kubernetes/kubernetes-getting-started.rst
docs/source/reference/kubernetes/kubernetes-setup.rst
docs/source/reference/kubernetes/kubernetes-troubleshooting.rst
docs/source/reservations/existing-machines.rst
sky/cli.py

Update the docs after #4151.
We may want to wait until after 0.7 release to merge.

[docs] use k8s instead of kubernetes in the CLI

---

sky/jobs/recovery_strategy.py

If all goes correctly, the managed job controller should tear down a managed job cluster once the managed job completes. However, if the controller fails somehow (e.g. crashes, is terminated, etc), we don't want to leak resources.
As a failsafe, set autodown on the job cluster. This is not foolproof, since the skylet on the cluster can also crash, but it's likely to catch many cases.

[jobs] autodown managed job clusters

---

sky/backends/cloud_vm_ray_backend.py

Enhance the formatting of logs shown after job creation for better readability and consistency with serve module's style, where:
https://github.com/skypilot-org/skypilot/blob/c0c17483d1f692ad639144050f5f6fa0966e47a5/sky/serve/core.py#L275-L304

[UX] Improve Formatting of Post Job Creation Logs

---

sky/jobs/utils.py

Fixes #4273 
- Use `Set[int]` to manage unique `job_id`s for duplicate job names.
- Raise `ValueError` with improved messaging if multiple jobs with the same name exist.
- Import `ux_utils` for clearer error display.
This fix prevents type errors and ensures clearer handling of duplicate job names.
- Fix `sky jobs logs --controller --name
=pipeline`

Fix `stream_logs` Duplicate Job Handling and TypeError

---

sky/clouds/service_catalog/data_fetchers/fetch_lambda_cloud.py

This PR updates Lambda Cloud's regions:
- `us-east-2` → Washington DC, USA
- `us-south-2` → North Texas, USA
- `us-south-3` → Central Texas, USA

Update Lambda Cloud regions

---

sky/dag.py
sky/task.py
sky/utils/dag_utils.py

Closes #4254 
This PR introduces edge-based data flow support in DAGs, allowing users to specify data transfer paths and sizes between tasks. This provides a more explicit and flexible way to define data dependencies between tasks.
1. Added `TaskEdge` dataclass to represent edges between tasks:
- Stores source task, target task, data path, and data size
- Provides `with_data()` method for fluent API
2. Enhanced DAG implementation:
- Store edge metadata in networkx graph
- Added methods to get/manipulate edges and their properties
3. Updated YAML format:
- Replaced `downstream` with new `edges` field for explicit edge definition
- Added support for data transfer specifications on edges
Python API:
```python
with sky.Dag() as dag:
preprocess = sky.Task(name='preprocess', run='python …
```

[DAG] Add Edge-Based Data Flow Support

---

sky/clouds/service_catalog/images/aws_utils/image_gen.py
sky/jobs/dashboard/dashboard.py
sky/jobs/state.py

WAL is more robust for more parallel access, as we have done for #3863 #3923 
```
import subprocess
from multiprocessing.pool import ThreadPool
def run_task(task):
print(f'Running task {task}')
subprocess.run(
f'sky jobs launch -n job-{task} -dy --fast --cloud aws -t t3.medium --use-spot "echo hi {task}; sleep 3600"',
shell=True
)
with ThreadPool(8) as pool:
pool.map(run_task, range(1000))
```

[Jobs] Managed jobs database use WAL mode

---

sky/dag.py

Resolve #4277.
Adds a `plot` method to the `Dag` class to visualize task dependencies. Automatically displays inline in Jupyter or saves to a file in other environments.
```python
from sky import Dag, Task
with Dag() as dag:
task_a = Task(name="A")
task_b = Task(name="B")
task_c = Task(name="C")
task_a >> task_b >> task_c
dag.plot()
```
**Notes:**
- Requires `matplotlib` and `networkx`.
- Tested in Jupyter Notebook (`.ipynb`)
- Tested in regular Python environment

[DAG] Add DAG Visualization with Jupyter Support

---

sky/provision/runpod/instance.py

[RunPod] Fix assertion in ports query.

---

sky/data/mounting_utils.py
sky/exceptions.py
sky/utils/command_runner.py
tests/test_smoke.py

User's custom proxy may drop the connection for idleness. Since we are using the SSH control master, the master connection (the first connection made with the remote machine) can be idle even though the later connection is doing work. We now disable the control master for custom ssh proxy command.

[Core] Make ssh connection more robust with custom proxy

---

tests/test_optimizer_dryruns.py

Lambda recently added us-east-1 region #4291  which conflicts with the name of AWS causing our unittest to fail for inferring cloud from region/zone. 

[Test] Fix unittest for region infer

---

sky/provision/aws/config.py

Log error before throwing exception
Route tables returned by the config.py _get_route_tables() function were incorrect after being called once because of the @functools.lru_cache defined on the function. I added region to the function call to keep the cache and have it return the correct results (switching regions before the change caused the issue).
Also added a logger.error() call to the _skypilot_log_error_and_exit_for_failover() function to actually log an error which shows up in stderr. Without this you get a generic error that does not tell you the actual cause of the error. You needed to go into the provision log to get the actual error.
Ran successful A10G:1 deploys and unsuccessful H100:8 deploys across all my regions in AWS and the appropriate …

Fix AWS Route Table caching which causes invalid failures in other regions after an initial valid failure.

---

sky/templates/kubernetes-ray.yml.j2

Many images (e.g., ubuntu, nemo) don't have `lsof` installed by default, which would cause our log tailing to k8s container output to fail.
This PR removes the dependence on lsof by using our own minimal version of lsof. 
Tested:
In both cases verified logs are written to container stdout and can be read with `kubectl logs -f`. Also made sure the `tail` process is terminated after the task completes.

[k8s] Remove `lsof` dependence for tailing logs

---

docs/source/cloud-setup/policy.rst
sky/cli.py
sky/dag.py
sky/execution.py
sky/jobs/core.py
sky/serve/core.py
sky/utils/admin_policy_utils.py

Previously, the admin policy is only applied in the backend, which will cause wrong output of the optimizer table in the CLI. We now apply the policy to dag in CLI as well.

[Admin Policy] Apply policy in CLI

---

sky/backends/cloud_vm_ray_backend.py
sky/cli.py
sky/core.py
sky/skylet/constants.py
sky/skylet/job_lib.py
sky/skylet/log_lib.py

Trying to add this feature: https://github.com/skypilot-org/skypilot/issues/4222
Config file:
```bash
(sky) ➜  skypilot git:(dev/zeping/support_tail_n) cat ~/Desktop/hello-sky/long_log.yaml 
workdir: .
resources:
cloud: aws
instance_type: t3.small
num_nodes: 1
setup: |
echo "Running setup."
run: |
i=1
while [ $i -le 1000 ]; do
echo "This is test log line number $i"
i=$((i + 1))
done
```
Launch command:
```bash
sky launch -c long_log_small ~/Desktop/hello-sky/long_log.yaml
...
(task, pid=1789) This is test log line number 985
(task, pid=1789) This is test log line number 986
(task, pid=1789) This is test log line number 987
(task, pid=1789) This is test log line number 988
(task, pid=1789) This is test log line number 989
(task, pid=1789) This is test log line number 990
(task, pid=1789) …
```

[UX] Support --tail parameter for sky logs

---

examples/dag/diamond.yml

Update the diamond example to use the new data API syntax, replacing the old `downstream` format with explicit edges and data transfer specifications.

[DAG] Update Diamond Example For New Tentative Data API

---

sky/skylet/job_lib.py

Another race condition in job scheduling besides #4264 ...
The pending jobs should be queried during the pending loop, otherwise, a same job can be submitted twice to ray job in the following condition.
1. Two threads calling `schedule_step()` and both get the list of pending jobs
2. The first thread submitted the first pending job
3. The second thread look at the stale pending job list and found the first job not submitted yet, so it will submit the job again.
23 jobs in parallel now, a bit more than #4264
```
290  sky-cmd  8 mins ago      -               -         1x[CPU:1+]  PENDING    ~/sky_logs/sky-2024-11-09-04-39-25-046022  
289  sky-cmd  8 mins ago      a few secs ago  2s        1x[CPU:1+]  RUNNING    ~/sky_logs/sky-2024-11-09-04-39-23-183791  
288  sky-cmd  8 mins ago      a few …
```

[Core] Avoid job scheduling race condition

---

tests/test_smoke.py

Fix smoke tests that were broken by #4198 which changed the job creation log format. The following tests were updated:
- test_minimal
- test_launch_fast  
- test_launch_fast_with_autostop
The tests now validate the new log format where "Job ID" appears before "Useful Commands".
- `pytest tests/test_smoke.py::test_minimal --gcp -v -s`

[Tests] Fix smoke tests for new job creation log format

---

docs/source/cloud-setup/cloud-permissions/kubernetes.rst
docs/source/reference/kubernetes/kubernetes-getting-started.rst
sky/cli.py
sky/clouds/service_catalog/kubernetes_catalog.py
sky/provision/kubernetes/utils.py
sky/utils/kubernetes/generate_kubeconfig.sh

Updates our minimal permissions doc to add permissions required by show-gpus, and updates show-gpus to work with limited permissions:
```
W 10-29 18:36:09 kubernetes_catalog.py:112] Failed to get pods in the Kubernetes cluster (forbidden). Please check if your account has necessary permissions to list pods. Realtime GPU availability information may be incorrect.
Kubernetes GPUs (context: gke_sky-dev-465_us-central1-c_gkeusc6)
GPU   REQUESTABLE_QTY_PER_NODE  TOTAL_GPUS  TOTAL_FREE_GPUS
H100  1, 2, 4, 8                8           NA
Kubernetes per node GPU availability
NODE_NAME                               GPU_NAME  TOTAL_GPUS  FREE_GPUS
gke-gkeusc6-default-pool-db727de5-62gm  H100      8           NA
```
Also adds a quick snippet for specifying custom resources in pod_config.

[k8s] Fix show-gpus when limited permissions are available

---

docs/source/running-jobs/environment-variables.rst

* Add the parameter `--env-file` to `environment-variables.rst` to complete the doc and example.
* Trailing-whitespace hook automatically fixes some white spaces.
Tested [here](https://github.com/skypilot-org/skypilot/pull/4345#discussion_r1841531611)

Update `--env-file` to sky doc

---

sky/jobs/controller.py

---
Previously, global optimization was only performed on the user's machine for display purposes, and its results were not propagated to the controller. This PR adds global optimization on the controller side, which is particularly important when data transfer costs are involved (#4320).
To illustrate the changes of global optimization, we need to test it with #4320, since without data consideration, the global optimization would not make a difference compared to single node optimization. Only with data dependencies, can a node's position choosing affect another.
```python
import sky
from sky import Resources
from sky import clouds
from sky.optimizer import OptimizeTarget
import sky.jobs
with sky.Dag() as dag:
task1 = sky.Task(name="task1", run="echo …
```

[DAG] Run global optimization on controller for task placement

---

sky/jobs/core.py

A user reports when launch a managed jobs, following assertion error appears:
```bash
File "sky/jobs/core.py", line 128, in launch
assert len(controller_task.resources) == 1, controller_task
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
This is due to the multi-controller resources we introduces in #4053. Fixed now

[Jobs] Remove assertion for one single controller resources.

---

sky/utils/controller_utils.py

Resolve the issue #4367  
After fix, the message shown:
Launching a new service 'http-server'. Proceed? [Y/n]:
⚙︎ Translating workdir to SkyPilot Storage...
Workdir: 'examples/serve/http_server' -> storage: 'skypilot-workdir-hysunhe-f650b5f9'.
sky.exceptions.NotSupportedError: Unable to use workdir - no cloud with object store is enabled. Please enable at least one cloud with object store support (AWS, GCP, Azure, IBM, Cloudflare) by running `sky check`, or remove workdir from your task.
Hint: If you do not have any cloud access, you may still download data and code over the network using curl or other tools in the `setup` section of the task.

[Core] NoCloudAccessError check is escaped from storage sync

---

sky/backends/backend_utils.py
sky/backends/cloud_vm_ray_backend.py
sky/clouds/service_catalog/aws_catalog.py
sky/global_user_state.py
sky/utils/timeline.py

Previously, every time we want the status of a cluster with spot VMs or with autostop set, we will fetch the latest actual status from the cloud. This is needed since these clusters can be terminated from "outside", and the state in the local state database will be out of date.
However, we often end up fetching the status multiple times in a single invocation. For instance, `sky launch` will check the status in cli.py, then again almost immediately after as part of the provisioning codepath.
To mitigate this, we can keep track of the last time we fetched the status from the cloud. If it is within the past 2 seconds, assume that it's still accurate (that is, the cluster hasn't been terminated/stopped since then).
Caveats:
- ~The updated timestamp check/set is not atomic, so if multiple …

[ux] cache cluster status of autostop or spot clusters for 2s

---

sky/provision/kubernetes/utils.py

1. initialize a new dict if the destination is None, and add the source key/value to it
2. use the cpu/memory to k8s resources limits, or the pod will fail to create if there is LimitRange configured in the namespace, as the default cpu/memory maybe smaller than the requests.

[k8s] fix managed job issue on k8s

---

docs/source/reference/config.rst
sky/backends/backend_utils.py
sky/utils/schemas.py

User reported they are using an external mechanism to inject AWS credentials in their k8s pods, which should be used for accessing buckets. However, we upload AWS credentials from the local machine if they exist, and as a result these local user credentials were overriding the injected credentials.
This PR adds a `NO_UPLOAD` flag to `remote_identity`, to explicitly skip uploading cloud credentials even if they exist on the local machine.

[Core] Add `NO_UPLOAD` for `remote_identity`

---

sky/clouds/service_catalog/data_fetchers/fetch_fluidstack.py
sky/provision/fluidstack/instance.py

* Add new provisioning status to fix failed deployments
* Add H100 SXM5 GPU mapping
- Implement logic for new `provisioning` status
- Add H100 SXM5 mapping
- `sky launch --cloud fluidstack --gpus A6000:1`
- `pytest tests/test_smoke.py::test_minimal --fluidstack  --terminate-on-failure`

    [FluidStack] Fix provisioning and add new gpu types

---

sky/execution.py

Before:
> Choosing resources for JOBS_CONTROLLER...
After:
> Choosing resources for managed jobs controller...
This was what was intended in #4341, but it broke during PR review and I didn't notice.

[ux] display human-readable name for controller

---

sky/provision/kubernetes/instance.py

`apt update` log from container init may not be written by the time we check it in our provisioner. This PR handles that by retrying till the timeout is hit. PR tested/verified by user running into the bug.

[k8s] Handle apt update log not existing

---

sky/clouds/kubernetes.py

Resolve [issue #4324](https://github.com/skypilot-org/skypilot/issues/4324)
Catch exceptions for the `sky check` command in Kubernetes.
Before:
```bash
Kubernetes: disabled                              
Reason: Traceback (most recent call last):
File "/Users/zepingguo/Desktop/skypilot/sky/adaptors/common.py", line 31, in load_module
self._module = importlib.import_module(self._module_name)
File "/Users/zepingguo/miniconda3/envs/sky/lib/python3.10/importlib/__init__.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module …
```

[UX] user-friendly message shown if Kubernetes is not enabled.

---

sky/backends/cloud_vm_ray_backend.py
sky/provision/instance_setup.py

We previously have the `RAY_DEDUP_LOGS` set for the ray cluster, but it becomes not effective for the jobs as we got rid of `ray job submit` #4318 , making the job not inheriting the env var from the ray cluster. We now set those env vars directly to the driver process.
To reproduce:
```
sky launch --num-nodes 4 echo hi
...
(worker2, rank=2, pid=2043, ip=10.0.2.206) hi
(worker1, rank=1, pid=2038, ip=10.0.2.205) hi [repeated 3x across cluster] (Ray deduplicates logs by default. Set RAY_DEDUP_LOGS=0 to disable log deduplication, or see https://docs.ray.io/en/master/ray-observability/ray-logging.html#log-deduplication for more options.)
✓ Job finished (status: SUCCEEDED).
```

[Jobs] Disable deduplication for logs

---

sky/provision/oci/instance.py

The run_instance returned a ProvisionRecord with zone set to None. 
This PR is to fix this issue: set the right zone to the ProvisionRecord .

[OCI] set zone in the ProvisionRecord

---

examples/oci/serve-qwen-7b.yaml

The latest released vLLM v0.6.4.post1 has issue. So we specify the vLLM version as v0.6.3.post1 in the serve-qwen-7b.yaml file. So we specify the vLLM to v0.6.3.post1, which works fine.
The current latest released version of vLLM is 0.6.4.post1. Exec serve-qwen-7b.yaml will cuz the following issue due to the  vllm version 0.6.4.post1:
(qwen-llm2, pid=9356)   File "/home/ubuntu/miniforge3/envs/vllm/lib/python3.12/site-packages/transformers/utils/import_utils.py", line 1778, in _get_module
(qwen-llm2, pid=9356)     return importlib.import_module("." + module_name, self.__name__)
(qwen-llm2, pid=9356)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(qwen-llm2, pid=9356)   File "/home/ubuntu/miniforge3/envs/vllm/lib/python3.12/importlib/__init__.py", line 90, in …

[Examples] Specify version for vllm cuz vllm v0.6.4.post1 has issue

---

sky/backends/backend_utils.py
sky/clouds/kubernetes.py
sky/provision/instance_setup.py
sky/provision/kubernetes/instance.py
sky/provision/provisioner.py
sky/skylet/constants.py
sky/templates/kubernetes-ray.yml.j2

Moved setup/ray start to the kubernetes pod args to make them async
TODO:

[k8s] Move setup and ray start to pod args to make them async

---

sky/skylet/constants.py
sky/templates/kubernetes-ray.yml.j2

uv is a tool that can replace pip and venv (and some other stuff we're not using I think). It's written in rust and in testing is significantly faster for many operation, especially things like `pip list` or `pip install skypilot` when skypilot or all its dependencies are already installed.
- manually created clusters on k8s, aws, azure, lambda, gcp

use uv for pip install and for venv creation

---

docs/source/getting-started/installation.rst

docs change for OCI: Add content to specify a compartment for OCI resources.

[docs] Specify compartment for OCI resources.

---

sky/provision/provisioner.py

If the ray cluster is healthy, this skips the worker node `ray start` command, i.e. save N-1 ssh connections, each taking 2 seconds (divided by the parallelism).
This optimization comes from #4389 

[Core] Skip worker ray start for multinode

---

sky/skylet/constants.py
sky/templates/kubernetes-ray.yml.j2

This reverts #4394, which was merged in as part of #4393.

remove `uv` from runtime setup due to azure installation issue

---

sky/clouds/service_catalog/kubernetes_catalog.py

Our optimizer invokes `list_accelerators` to get the list of GPUs available in a cloud. In our k8s implementation, this was being routed to `list_accelerators_realtime`, which would make an expensive and permission-heavy call to `list_pod_for_all_namespaces`. Users reported this call can take a long time, which would slow down `sky launch`.
We now add a short circuit arg to skip fetching realtime info when `list_accelerators` is called.
Tested:

[k8s] Skip listing all pods to speed up optimizer

---

sky/skylet/constants.py
sky/templates/kubernetes-ray.yml.j2

Closes #4397.
Fixes backward compatibility by:
* Adding a marker file to distinguish newer nimbus clusters vs older clusters.
* Waiting/checking log files only this marker exists
* UV/pip handling depending on what's installed
Note that this is partial backward compatibility - if a user launches a cluster with older version, upgrades, and sky launches again, we will not re-run some provisioning steps (e.g., ray setup). Supporting full backward compatibility would require maintaining two very different code paths in the k8s provisioning pipeline, and probably not a good idea. If users need to re-initialize the cluster, they can do `sky down` and `sky launch` again. 
Tested:

[k8s] Nimbus backward compatibility

---

sky/execution.py

Closes #4315, a regression recently introduced in #4023. `backend.sync_file_mounts` syncs both, rsync based file mounts and storage based file mounts, so it should be invoked if either of those are specified.

[Storage] Call `sync_file_mounts` when either rsync or storage file_mounts are specified 

---

sky/cli.py

This is to allow:
`sky launch --cloud lambda --ports none llm/llama-3_2/llama3_2.yaml`

[UX] Allow disabling ports in CLI

---

sky/templates/aws-ray.yml.j2

[AWS] Get rid of credential files if `remote_identity: SERVICE_ACCOUNT` specified

---

docs/source/reference/comparison.rst

Updates comparison page image to accurately reflect the steps in iterative development on k8s.

[k8s] Update comparison page image

---

sky/provision/kubernetes/utils.py

SkyPilot, when run inside a k8s pod, does not respect the namespace configured in the kubeconfig context. This PR fixes that by using the same logic for namespace loading as for load_config(). 
Tested

[k8s] Fix in-cluster auth namespace fetching

---

.pre-commit-config.yaml
CONTRIBUTING.md

Step 1 install pre-commit
```bash
pip install pre-commit
pre-commit install
```
Step 2, now just run `git commit`. The command will use the `pre-commit` hook, it will behave exactly the same as [format.sh](https://github.com/skypilot-org/skypilot/blob/master/format.sh)
Refer to this [comment](https://github.com/skypilot-org/skypilot/pull/4258#issuecomment-2469513779) if you're using cursor/vscode and encounter env problem

Add a pre commit config to help format before pushing

---

.pre-commit-config.yaml

The previous [PR](https://github.com/skypilot-org/skypilot/pull/4258) added the pre-commit configuration.
The Pylint hook was not set correctly; it is now properly configured and works the same as [format.sh](https://github.com/skypilot-org/skypilot/blob/master/format.sh).
```bash
(sky) ➜  skypilot git:(dev/zeping/pre_commit_same_as_format) ✗ (sky) ➜  skypilot git:(dev/zeping/pre_commit_same_as_format) ✗ git commit -m "test"                                          
trim trailing whitespace.................................................Passed
fix end of files.........................................................Passed
check yaml...............................................................Passed
check for added large files..............................................Passed
black …
```

fix the pylint hook for pre-commit

---

sky/clouds/kubernetes.py
sky/resources.py

User reported upgrading from 0.6.1 to 0.7.0 broke `sky status` and other commands when state.db had a k8s cluster using a custom image:
```
$ sky status
ValueError: image_id {'kubernetes': 'docker:ubuntu:22.04'} should contain the image for the specified region
```
This happens because we renamed the default region for k8s from the constant `kubernetes` to the context name. 
This PR fixes backward compatibility for `sky.Resources` by replacing `kubernetes` in `_image_id` dict with the current active context when an older version is detected. Ideally we should use the context used in the previous launch, but that information is not available to us. 
Tested:

[k8s] Fix resources.image_id backward compatibility

---

sky/clouds/service_catalog/kubernetes_catalog.py

When nvidia drivers are not installed, `sky show-gpus --cloud kubernetes` would fail with:
```
AssertionError: Keys of counts ([]), capacity ([]), and available (['T4']) must be same.
```
This is because we were adding GPUs to the available table if the label was present, even if the resource did not exist. This PR fixes it by adding a GPU to available only if both conditions are satisfied - resource exists and labels are present.
Tested:

[k8s] Fix `show-gpus` availability map when nvidia drivers are not installed

---

sky/__init__.py
sky/backends/cloud_vm_ray_backend.py
tests/test_smoke.py
tests/test_yamls/test_only_setup.yaml

Fixes #4419
```
resources:
cloud: aws
cpus: 2+
region: us-east-1
setup: hostname
```

[Core] Execute setup when `--detach-setup` and no `run` section

---

sky/setup_files/dependencies.py
sky/setup_files/setup.py
sky/skylet/constants.py
sky/templates/kubernetes-ray.yml.j2
sky/utils/controller_utils.py

This was previously merged in as #4394, which was reverted in #4401 due to a bug.
This PR:
- readds the old uv changes
- fixes the bug on Azure (see below)
- uses the `--seed` flag with `uv venv` to make sure pip is installed in the venv
**Performance impact:**
- Cluster provisioning:
- Using skypilot custom images:
- AWS: saves about 0.5s (8.5s -> 8s)
- Azure: saves about 5s (26s -> 21s)
- Using stock ubuntu images **~3x speedup**:
- AWS: saves about 30s (45s -> 15s)
- Azure: saves about 100s (130s -> 30s)
- These results likely also apply to other user-provided images, including custom kubernetes images.
- Job controller setup/cloud dependency installation saves about 45s (85s -> 25s) on first run
- with GCP, AWS, and Azure enabled
- on run 2+ with the controller already setup, saves …

[perf] use uv for venv creation and pip install

---

README.md
docs/source/docs/index.rst
tests/test_smoke.py

[Minor] README updates.

---

sky/templates/kubernetes-ray.yml.j2

Currently if an accelerator is not specified and FUSE is not required by the pod, we set `limits` to null. This PR adds resource limits to the pod spec only if they exist.
```
#~/.sky/config.yaml
kubernetes:
pod_config:
spec:
containers:
- resources:          # Custom resource requests and limits
requests:
rdma/rdma_shared_device_a: 1
limits:
rdma/rdma_shared_device_a: 1
```
`sky launch --cloud kubernetes -- echo hi`

[k8s] Add resource limits only if they exist

---

sky/backends/backend_utils.py
sky/backends/cloud_vm_ray_backend.py
sky/global_user_state.py
sky/provision/azure/instance.py
sky/provision/gcp/instance.py
sky/provision/lambda_cloud/instance.py
sky/provision/paperspace/instance.py

Includes the following changes: 
**[if a newly-created cluster is missing from the cloud, wait before deleting](https://github.com/skypilot-org/skypilot/pull/4443/commits/4daf50098c87d8a44c0864236cacae144bad5679)**
This protects against leaking instances that haven't appeared yet, because they were just created.
Addresses #4431, see that issue for more details.
- This is observed to affect AWS if the timing is exactly right - there's a <1s window where the instances have not yet appeared.
- Haven't been able to reproduce this on any other clouds.
**[confirm cluster actually terminates before deleting from the db](https://github.com/skypilot-org/skypilot/pull/4443/commits/b18b95980ffbaafe420a21c1a99d794f7b475dff)**
Previously, we optimistically assumed that a successful termination request …

[robustness] cover some potential resource leakage cases

---

tests/test_smoke.py
tests/test_yamls/test_storage_mounting.yaml.j2

Feature for #4423 
* Add the smoke test:
* `test_aws_storage_mounts_with_stop_only_mount`
* Implement a command generator function to improve code reusability.
* Modify the `test_storage_mounting.yaml.j2` template to support an additional parameter, `only_allow_mount`, which specifies if only `MOUNT` is allowed and disables `COPY`.
Test:
* `pytest tests/test_smoke.py::test_aws_storage_mounts_with_stop --aws`
* `pytest tests/test_smoke.py::test_aws_storage_mounts_with_stop_only_allow_mount --aws`
* `pytest tests/test_smoke.py::test_gcp_storage_mounts_with_stop --gcp`
All pass
*  `pytest tests/test_smoke.py::test_azure_storage_mounts_with_stop --azure`
All fail on master, success on 0.7.1. These two test cases fail on the master branch but pass on …

smoke tests support storage mount only

---

sky/provision/runpod/api/commands.py

Fixes runpod import issues introduced in #4447.

use lazy import for runpod

---

sky/utils/controller_utils.py

Without deepcopy, `cloud_python_dependencies.remove(dependencies.AZURE_CLI)` will end up modifying the constant, affecting other runtimes that are referencing this module, and if other runtime tries to remove the same item again, ValueError will get thrown.

Not mutate azure dep list at runtime

---

sky/clouds/service_catalog/data_fetchers/fetch_gcp.py
sky/clouds/service_catalog/gcp_catalog.py

Adds 1, 2, and 4 sized instance types for H100's to GCP catalog

add 1, 2, 4 size H100's to GCP

---

sky/clouds/service_catalog/constants.py
sky/clouds/service_catalog/gcp_catalog.py

Due to the recent update of GCP catalog that adds H100 instances with 1,2,4 ACC counts #4456, our `gcp_catalog.py` met an backward compatibility issue, where the newly added H100:1 instances causes a `KeyError`.
```
File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sky/clouds/service_catalog/gcp_catalog.py", line 448, in <lambda>
lambda x: _get_host_instance_type(x['AcceleratorName'],
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sky/clouds/service_catalog/gcp_catalog.py", line 391, in _get_host_instance_type
instance_types = _ACC_INSTANCE_TYPE_DICTS[acc_name][acc_count]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 1
```
We have to bump the catalog schema …

[Catalog] Bump catalog schema version

---

sky/backends/backend_utils.py

[core] skip provider.availability_zone in the cluster config hash

---

sky/cli.py
sky/jobs/core.py

The --fast behavior is now always enabled. This was unsafe before but since #4289 it should be safe.
We will remove the flag before 0.8.0 so that it never touches a stable version.
sky launch still has the --fast flag. This flag is unsafe because it could cause setup to be skipped even though it should be re-run. In the managed jobs case, this is not an issue because we fully control the setup and know it will not change.

remove sky jobs launch --fast

---

sky/adaptors/oci.py
tests/unit_tests/sky/adaptors/test_oci.py

[UX] Fix unnecessary OCI logging

---

tests/smoke_tests/test_cluster_job.py

Test case for: #4423
Add test case: `test_azure_spot_instance_verification`
```
Test Azure spot instance provisioning with explicit verification.
This test verifies that when --use-spot is specified for Azure:
1. The cluster launches successfully
2. The instances are actually provisioned as spot instances
```

Add tests for Azure spot instance

---

docs/source/getting-started/tutorial.rst
docs/source/running-jobs/distributed-jobs.rst

[docs] Add newer examples for AI tutorial and distributed training

---

sky/provision/kubernetes/utils.py
tests/unit_tests/kubernetes/test_gpu_label_formatters.py

Changes Nvidia GFD label formatter to use boundary matching instead of substring matching to handle L40 vs L4 detection.
Closes #4404.

[k8s] Fix L40 detection for nvidia GFD labels

---

docs/source/reference/storage.rst
docs/source/reference/yaml-spec.rst

This is the related doc-change for PR https://github.com/skypilot-org/skypilot/pull/4501

[docs] Support OCI Object Storage

---

docs/source/_static/custom.js

Kapa ai seems to be having issues loading on certain ISPs, including comcast. Causes our docs page to keep loading indefinitely. Disabling Kapa until it is resolved.

[Docs] Disable Kapa AI

---

docs/source/reference/kubernetes/kubernetes-getting-started.rst

Makes kubernetes.pod_config it's own subsection for easier referencing, adds NFS example.

[Docs] Refactor pod_config docs

---

examples/oci/gpu-oraclelinux9.yaml
examples/oci/gpu-ubuntu-2204.yaml
sky/clouds/utils/oci_utils.py

Set the default image for both GPU and CPU to ubuntu 22.04. 
Please also help review the catalog PR https://github.com/skypilot-org/skypilot-catalog/pull/107 
All images are validated with the following passed tests:
test1:  sky launch -c gpu-2204 examples/oci/gpu-ubuntu-2204.yaml (GPU ubuntu 22.04)
test2: sky launch -c gpu-ol9 examples/oci/gpu-oraclelinux9.yaml (GPU oraclelinux9)
test3: sky launch -c gpu-ol8 hysun_sky.yaml --image-id skypilot:gpu-oraclelinux8 (GPU oraclelinux8)
test4: sky launch -c gpu-2204 examples/oci/gpu-ubuntu-2204.yaml (comment out the image_id for testing the gpu default image)
test5: sky launch -c cputest --cloud oci --region us-sanjose-1 uptime (CPU default image: ubuntu 22.04)
test6: sky launch -c cputest --cloud oci --region us-sanjose-1 --image-id …

[OCI] Set default image to ubuntu LTS 22.04

---

sky/clouds/oci.py
sky/provision/oci/query_utils.py

1. Support specify OS type when specify custom image with --image-id. (Currently ubuntu/oraclelinux)  
2. A corner case fix when ctrl+c during creating cluster, which might cause the cluster cannot be terminated if the vNIC is not attached to the provisioning instance.
I'll create a doc PR later to add image-id description for OCI in task yaml.
sky launch -c img-ol8 --cloud oci --region ap-seoul-1 --cpus 2 --image-id ocid1.image.oc1.ap-seoul-1.aaaaaaaarhw7elbcsnsxmtetmicg5eh5yf5yodmjozhxzrg7h4glptqfiwua:oraclelinux "cat /etc/os-release"

[OCI] 1. Support specify OS with custom image id. 2. Corner case fix

---

docs/source/examples/managed-jobs.rst

Update intermediate bucket related doc

---

sky/backends/backend_utils.py
sky/provision/kubernetes/utils.py
tests/test_config.py

Check pod_config when run 'sky check k8s' by using k8s  #4206 
This commit extends the functionality of `sky check k8s` by adding a check for `pod_config` in this step. The method used to check pod_config is by calling the K8s API. This approach has some advantages and disadvantages:
- Advantages:
1. Minimal code changes and 100% reliable check results.
2. Future K8s extensions to the pod format will not require any adjustments to skypilot's code.
- Disadvantages:
1. Requires interaction with the K8s cluster and cannot be validated locally offline.
Of course, any other suggestions are welcome for discussion.
The test config.yaml
```yaml
kubernetes:
pod_config:
metadata:
name: local-test
labels:
my-label: my-value    # Custom labels to SkyPilot pods
spec:
#runtimeClassName: nvidia    # …
```

[k8s] Add validation for pod_config #4206

---

sky/backends/wheel_utils.py

Previously, we were only taking the max timestamp of all the subdirectories of the given directory. So the timestamp could be incorrect if only a file changed, and no directory changed. This fixes the issue by looking at all directories and files given by os.walk().

[core] fix wheel timestamp check

---

sky/backends/backend_utils.py
sky/backends/cloud_vm_ray_backend.py
sky/cli.py
sky/clouds/aws.py
sky/clouds/cloud.py
sky/clouds/gcp.py

issue link: https://github.com/skypilot-org/skypilot/issues/4433
Solution:
context:
- Jobs controller or server need permission to launch/down nodes of multiple clouds.
detail:
- Get clouds whose remote identities are `LOCAL_CREDENTIALS` and credentials are expiring and warning to the user before provision.
Test case 1:
config in `~/.sky/config.yaml`
```
gcp:
remote_identity: LOCAL_CREDENTIALS
aws:
remote_identity: LOCAL_CREDENTIALS
jobs:
controller:
resources:
cloud: gcp
```
Local `AWS` credential configured by `SSO`
Launch controller on `GCP` and task on `AWS`
Command to run:
```bash
python cli.py jobs launch ~/hello-sky/hello_sky.yaml -y
```
Logs:
```bash
~/skypilot/sky on dev/hong/controller wip *1 > python cli.py jobs launch ~/hello-sky/hello_sky.yaml -y                      took 49s …
```

[UX] warning before launching jobs/serve when using a reauth required credentials

---

sky/clouds/utils/oci_utils.py
sky/provision/oci/query_utils.py
sky/utils/schemas.py

User may demand to reuse the existing VCN. We already support that for sky launch with "vcn_subnet" config. Now we add "vcn_ocid" for SkyServe (need vcn_ocid to create network security group (NSG)).
Example ./sky/config.yaml:
```
oci:
default:
compartment_ocid: ocid1.compartment.oc1..aaaaaaaam5akmizz6fzm7old5rqjlsrrckelfv6tyw24woxhtwzmpu4x6ioq
us-sanjose-1:
vcn_ocid: ocid1.vcn.oc1.ap-seoul-1.amaaaaaaak7gbriarkfs2ssus5mh347ktmi3xa72tadajep6asio3ubqgarq
vcn_subnet: ocid1.subnet.oc1.ap-seoul-1.aaaaaaaa5c6wndifsij6yfyfehmi3tazn6mvhhiewqmajzcrlryurnl7nuja
```
Then run:
`sky serve up ./examples/oci/serve-http-cpu.yaml`
Related docs will be updated later.

[OCI] Support reuse existing VCN for SkyServe

---

docs/source/reference/config.rst

This is the doc for: 
1. Some suggested changes for OCI advanced configuration
2. added vcn_ocid ( PR https://github.com/skypilot-org/skypilot/pull/4530 )

[docs] OCI: advanced configuration & add vcn_ocid

---

sky/backends/cloud_vm_ray_backend.py

Fixes issue reported here: https://github.com/skypilot-org/skypilot/issues/2807#issuecomment-2564567890
`sky down --purge` now works again even with stale or invalid context.

[k8s] Fix `--purge` not cleaning up cluster in stale k8s context

---

sky/authentication.py

Closes #4472. Our k8s secret creation had a race condition where multiple parallel `sky launch` operations would fail due to secret already existing.

[k8s] Fix race condition in k8s secret creation 

---

docs/source/cloud-setup/cloud-permissions/aws.rst
sky/provision/aws/config.py

Adding a filter for the default AWS VPC when no VPC is specified. This is matching the [docs](https://docs.skypilot.co/en/latest/reference/config.html): 
```
aws:
#
#
vpc_name: skypilot-vpc
```

[AWS] Adding filter for default aws vpc if not specified

---

.buildkite/generate_pipeline.py
tests/conftest.py

support
```bash
PYTHONPATH=$(pwd)/tests:$PYTHONPATH python .buildkite/generate_pipeline.py --filter-marks managed_jobs
```
So that we can configure Buildkite to call this script with this flag, supporting arbitrary pytest flags.
Now we can comment on PR: 
* `/smoke-test` to trigger all smoke tests.
* Or use `/smoke-test managed_jobs` to trigger smoke tests marked by certain pytest mark.
* Format: `/smoke-test <mark1>,<mark2>`

support filter flag for buildkite

---

sky/clouds/aws.py

Adding the option for AWS credentials provided by custom process. This auth method already worked, it just wasn't recognized properly when checked.

[AWS] Adding custom process as an option for aws credentials

---

sky/templates/jobs-controller.yaml.j2
sky/utils/controller_utils.py

closes #4299 by systemd
```
sky start sky-jobs-controller-<hash>
sky jobs launch --fast echo hi
curl localhost:5000
```

[Jobs] Refactor dashboard controller launching with systemd

---

sky/clouds/aws.py

Adding an option for an AWS identity that is an assumed role, set by using the `source_profile` and `role_arn` options in your `~/.aws/config`. Also refactored the identity option check to a for loop as it was getting repetitive. Also made it so the env var identity is recognized by `sky check`
```
sky check aws     
AWS: enabled                              
Hint: AWS env is set. It will work if you use AWS only, but will cause problems if you want to use multiple clouds. To set up static credentials, try: aws configure
```
```
sky check aws
AWS: enabled                              
Hint: AWS assume-role is set. It will work if you use AWS only, but will cause problems if you want to …
```

[AWS] Adding aws assume role option, and env var detection

---

CONTRIBUTING.md
sky/adaptors/common.py
sky/usage/usage_lib.py
sky/utils/log_utils.py

I've investigated python profiling tools when developing #3159 since `python -m cProfile` only [sees profile on main thread](https://stackoverflow.com/questions/653419/how-can-i-profile-a-multithread-program-in-python) and profiling multi-thread applications using cProfile [is tedious](https://dev.to/oryaacov/how-to-profile-your-multi-threaded-running-python-code-programmatically-collect-periodically-and-analyze-the-results-5fh3). I evaluated [yappi](https://pypi.org/project/yappi/) and [py-spy](https://github.com/benfred/py-spy), it turns out the latter one has better UX and broader adoption. Therefore, I propose changing the profiling approach in dev guide to py-spy.
Also, I found some minor optimization chances and made some quicks in this PR. `sky launch` speed ​​up 100ms in average: …

[UX] minor optimizations for launch and introduce py-spy

---

sky/clouds/service_catalog/kubernetes_catalog.py

Fixes #4556.
Before this PR:
```
(base) ➜  ~ sky show-gpus --cloud kubernetes
File "/Users/romilb/tools/anaconda3/bin/sky", line 8, in <module>
File "/Users/romilb/tools/anaconda3/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
File "/Users/romilb/tools/anaconda3/lib/python3.9/site-packages/click/core.py", line 1078, in main
File "/Users/romilb/Romil/Berkeley/Research/sky-experiments/sky/utils/common_utils.py", line 366, in _record
File "/Users/romilb/Romil/Berkeley/Research/sky-experiments/sky/cli.py", line 838, in invoke
File "/Users/romilb/tools/anaconda3/lib/python3.9/site-packages/click/core.py", line 1688, …
```

[k8s] Fix AssertionError in show-gpus when all GPUs were allocated

---

sky/utils/db_utils.py

In certain high-load scenarios, we see `sqlite3.OperationalError: database is locked`. This was first reported in #1507 and various fixes changes have partially addressed it (notably, WAL: #1509, #3923, #4283).
However, I still observed the issue on the spot database while cancelling or completing 1000+ managed jobs at once.
This PR avoids this issue by increasing the sqlite timeout to a high value (60 seconds), that should be well beyond what we expect to see in practice.
SQLite has various locking mechanisms to ensure consistency. If a transaction tries to execute but cannot obtain the necessary lock, it will give an [SQLITE_BUSY error](https://www.sqlite.org/rescode.html#busy). In Python, this is translated to  `sqlite3.OperationalError: database is locked`.
If the necessary lock is …

[core] increase sqlite3 lock timeout to 60s

---

docs/source/reference/storage.rst
examples/oci/dataset-mount.yaml
sky/data/storage.py

This is an enhancement of OCI cloud storage support.
Before this change, the region the bucket belongs to is restricted to be same as the region in the OCI config file. This becomes the default setting if no region specified with this enhancement.
With this change, we can specify the region with the bucket name in the source or name attribute.
oci://<bucket_name>  -->  oci://<bucket_name>@<region>
sky launch -c teststore ./examples/oci/dataset-upload-and-mount.yaml
sky launch -c teststore ./examples/oci/dataset-mount.yaml

[OCI]: Storage: support buckets from different region

---

sky/utils/kubernetes/deploy_remote_cluster.sh

When `sky local up --ips` is run on a remote cluster with CPUs only, our script incorrectly detects GPUs and gets stuck at installing nvidia GPU operator. This is because the check_gpu function is silently failing but the output is still being interpreted as truthy. This PR fixes it by explicitly returning true/false values. 

[k8s] Fix GPU detection when running with `sky local up --ips`

---

sky/provision/kubernetes/instance.py

Resolve #4582
Test:
Before:
```
sky down sky-serve-controller-220e162b
File "/home/buildkite-generic-4074b/miniconda3/lib/python3.10/site-packages/click/core.py", line 1443, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/home/buildkite-generic-4074b/miniconda3/lib/python3.10/site-packages/click/core.py", line 788, in invoke
return __callback(*args, **kwargs)
File "/home/buildkite-generic-4074b/.buildkite-agent/builds/gke/ip-10-0-35-236-1/skypilot-1/release/sky/utils/common_utils.py", line 386, in _record
File "/home/buildkite-generic-4074b/.buildkite-agent/builds/gke/ip-10-0-35-236-1/skypilot-1/release/sky/cli.py", line 2656, in down
_down_or_stop_clusters(clusters,
File "/home/buildkite-generic-4074b/.buildkite-agent/builds/gke/ip-10-0-35-236-1/s …
```

Fix type error -- Kubernetes sky down exception

---

tests/skyserve/auto_restart.yaml
tests/skyserve/llm/service.yaml
tests/skyserve/restart/user_bug.yaml
tests/skyserve/spot/base_ondemand_fallback.yaml
tests/skyserve/update/bump_version_after.yaml
tests/skyserve/update/bump_version_before.yaml
tests/skyserve/update/new_autoscaler_after.yaml
tests/skyserve/update/new_autoscaler_before.yaml
tests/skyserve/update/num_min_one.yaml
tests/skyserve/update/num_min_two.yaml
tests/skyserve/update/old.yaml
tests/smoke_tests/test_sky_serve.py

This PR fixes several broken SkyServe smoke tests:
1. LLM tests failed cuz this breaking change in transformers: huggingface/transformers#35639. Fix transformer version before this change.
2. `test_skyserve_fast_update`'s port has been accidentally changed by #3832. Revert it back.
3. Replacing several `workdir` with `wget` to avoid storage creation.
4. Fixes #4565 by waiting all provisioning resources has a `vCPU=2` representation.
5. When the controller is put in `INIT` status by other services, the `sky serve status --endpoint` is likely to return a `-` due to the following check. This PR do retry on getting a `-` when fetching the endpoint.
https://github.com/skypilot-org/skypilot/blob/0a810eeb0a1b649185925ddce782536f2f55ba61/sky/serve/serve_utils.py#L793-L798
An example:
```bash
+ …
```

[Tests] Fix SkyServe Smoke Test

---

sky/jobs/state.py

This fixes a bug where `sky jobs queue` will fail on a controller that already had jobs in the `job_info` table before #4485, because the `schedule_state` column will be null, which is not valid for the enum.

[jobs] allow for null schedule_state

---

sky/provision/kubernetes/utils.py

Merge dict logic had some redundant code - destination can (and should) never be None, so this code path would never be reached. 
Tested:
TODO: Add unit tests.

[k8s] Minor: fix dictionary merging logic

---

sky/check.py
sky/clouds/kubernetes.py

[k8s] Show enabled contexts in `sky check`

---

sky/provision/kubernetes/utils.py

K8s API server may have transient issues, in which case we should retry instead of failing on the first attempt. 

[k8s] Add retries for pod and node fetching to handle transient errors

---

sky/jobs/controller.py
sky/jobs/state.py
sky/jobs/utils.py
sky/skylet/constants.py
sky/skylet/events.py

1. Jobs cannot get stuck in CANCELLING - it's no longer "terminal".
2. We use schedule_state rather than job status to determine whether a controller has exited cleanly. This allows us to reliably see if the controller crashed and simplifies some of the checking logic.
3. Even if jobs are in a terminal status (including SUCCEEDED), we can still set them to FAILED_CONTROLLER if the controller died abnormally, e.g. during cleanup.
In combination with #4552 and #4562, the internal state machine for job status and schedule state should be much more robust and likely to eventually get to a consistent state, even under high load.

[jobs] make status updates robust when controller dies

---

tests/smoke_tests/test_sky_serve.py

The return value for self signed certificates is sometimes with the dash and sometimes not. This PR fixes it.

[Test] Fix HTTPS Test self signed str

---

sky/skylet/constants.py

Users may have `UV_SYSTEM_PYTHON=true` in their environments, esp. in their Dockerfiles. This breaks our `uv pip` commands since they end up installing to system python, instead of `skypilot-runtime`.
This PR sets SkyPilot UV commands to use `UV_SYSTEM_PYTHON=false` to force uv to use the specified `VIRTUAL_ENV`.

[Core] Force UV to not use system python

---

sky/__init__.py
sky/cli.py

[The v0.6.0 release](https://github.com/skypilot-org/skypilot/releases/tag/v0.6.0) said these "will be removed in the next minor release", but the comments say v0.8.0. We will wait til 0.8.0.

[UX] remove deprecated `sky spot` CLI and `sky.spot_xxx` API

---

sky/adaptors/aws.py
sky/clouds/aws.py
sky/provision/aws/instance.py
tests/unit_tests/test_adaptor.py

On an AWS instance with an assigned role (via instance metadata), AWS credentials are automatically fetched from the Instance MetaData Service (IMDS). At least, they should be.
In high-concurrency environments, we can fail to fetch the credentials because the IMDS will ratelimit/throttle requests. In an ideal world, this is automatically handled by the botocore/boto3. In the real world, this case is indistinguishable from having no AWS credentials.
_btw, this also means that any session creation, when we don't already have credentials, will try to contact IMDS, and will only fail after the 1s timeout. :)_
To handle this case, we assume that we should never see `session.get_credentials() is None`. If we do, we will retry the session creation, with backoff.
Open questions:
- Is it …

[aws] catch the case where get_credentials is None

---

sky/jobs/core.py

User report: it's hard to get job_id after submitting job with python API, requires correlating against jobs.queue and gets even harder is submitting concurrent jobs. 
This PR returns `job_id` and handle from `sky.jobs.launch()`.
```
import sky
task = sky.Task(
name='test',
run='echo "Hello, World!"'
)
job_id = sky.jobs.launch(task=task)
print(job_id)
job_id = sky.jobs.launch(task=task)
print(job_id)
```

[Python API] Return job_id on `sky.jobs.launch`

---

sky/cli.py
sky/serve/core.py
sky/serve/replica_managers.py
sky/serve/service_spec.py
sky/utils/schemas.py
tests/skyserve/multi_ports.yaml
tests/smoke_tests/test_sky_serve.py

Current implementation of SkyServe only allows the replicas to expose one port. In some cases, services may need to expose multiple ports for custom controller, GUI interface, etc. This PR adds support for it by allowing multiple ports, but requiring user to specify one as the main port in the service section, if multiple ports are provided.
```yaml
service:
readiness_probe: /
replicas: 2
port: 8000
resources:
ports:
- 8000-8001
- 3000
cpus: 2
```
The output of `sky serve status` will look like:
```
Services
NAME              VERSION  UPTIME  STATUS  REPLICAS  ENDPOINT            
sky-service-xxxx  1        28s     READY   2/2       xxxx:30001  
Service Replicas
SERVICE_NAME      ID  VERSION  ENDPOINT             LAUNCHED     RESOURCES       STATUS  REGION     
sky-service-xxxx  1   1 …
```

[Serve] Enable multiple ports in SkyServe replicas

---

sky/jobs/core.py
sky/serve/core.py
sky/skylet/constants.py
sky/utils/controller_utils.py

When a user is using the python API to submit jobs the `usage_run_id` will not be updated across multiple jobs.launch as we save the `usage_run_id` as a global variable, this causes multiple jobs always to share the same bucket.
When one job finishes, it will delete the bucket and cause the other jobs to fail to find the bucket.
https://github.com/skypilot-org/skypilot/blob/db90a41f4dff842aaaacd105d77f9e9a4e29b4bc/sky/utils/controller_utils.py#L676

[Jobs/Serve] Use unique id for intermediate bucket

---

sky/setup_files/dependencies.py

Follow up to #4604.
K8s seems to have fixed the bug in https://github.com/kubernetes-client/python/pull/2338, future releases should be ok to use.

[k8s] Allow kubernetes python client versions != 32.0.0

---

sky/cli.py
sky/jobs/core.py

The flag was already deprecated, this fully removes it before 0.8.0.

remove --fast flag from sky jobs launch

---

sky/jobs/controller.py
sky/jobs/utils.py
sky/utils/controller_utils.py

After the managed job completes, there are a few cases where we still try to access the cluster. If that fails, don't crash the controller.

[jobs] catch unimportant errors in controller proccess

---

docs/source/reference/kubernetes/kubernetes-getting-started.rst
sky/provision/kubernetes/utils.py

Adds support for autoscaling TPU node pools on GKE.
Currently single-host TPU v5 is supported.
Users must configure `autoscaler: gke` and a large `provision_timeout` to let the cluster autoscale.
```
kubernetes:
autoscaler: gke
provision_timeout: 900
```
Tested on scale-from-zero nodepool with`ct5lp-hightpu-1t` (tpu v5e, 1x1):
1. Script to create GKE cluster with an autoscaling TPU nodepool:
```
gcloud beta container --project "sky-dev-465" clusters create "tputest" --region "us-west1" --tier "standard" --no-enable-basic-auth --cluster-version "1.31.4-gke.1256000" --release-channel "regular" --machine-type "e2-standard-8" --image-type "COS_CONTAINERD" --disk-type "pd-balanced" --disk-size "100" --metadata disable-legacy-endpoints=true --scopes …
```

[k8s] Support autoscaling TPU node pools

---

sky/serve/serve_state.py

A long-running command that applies a migration (e.g. adding a column) could indefinitely lock the database. Example case:
1. User upgrades skypilot
2. User runs sky launch that takes a long time.
a. This sky process adds a new column, obtaining a write lock on sqlite. But it doesn't commit, so it holds the write lock open, blocking other users of the database.
3. User tries to use sky in another process. (e.g. sky status)
a. Because the transaction from 2a hasn't been committed, this one also tries to add the new column.
b. But because the process from 2. is still alive, it can't get the write lock.

commit after adding columns to skyserve db

---

sky/provision/lambda_cloud/instance.py
tests/unit_tests/test_lambda.py

Handle the setup failure when single-node A6000 VMs on Lambda Cloud do not return a private IP: in this case, cluster info now returns `127.0.0.1`.
Tested: `sky launch -c private-ip-bug --cloud lambda --gpus A6000` is successful.

[Lambda] Fix missing private ip

---

sky/jobs/scheduler.py

Based on testing, we start to hit other significant issues past this point, such as global_user_state sqlite database breaking.

[jobs] set a global limit of 2000 parallel jobs

---

sky/jobs/dashboard/dashboard.py
sky/jobs/utils.py

This allows it to be excluded from dashboard.

[jobs queue] move scheduler state to its own column

---

sky/exceptions.py
sky/jobs/state.py

Descriptions from the commits:
**[[jobs] don't set end_at for CANCELLING](https://github.com/skypilot-org/skypilot/pull/4637/commits/cf45bfe917af19f6b87439bbcf093b21acc0c0a6)**
CANCELLING is no longer a terminal status - we shouldn't set end_at.
~~**[[jobs] don't require job to be CANCELLING to become CANCELLED](https://github.com/skypilot-org/skypilot/pull/4637/commits/93966374a768c649f122dfc6c3dfbe1a38bb9aab)**
It's possible that the job status erroneously gets set to some other value (e.g. RUNNING) by another process after getting set to CANCELLING - we should avoid this case, but if we end up here, we should still transition to CANCELLED.~~
**[[jobs] avoid status transitions that don't make sense](https://github.com/skypilot-org/skypilot/pull/4637/commits/805ea0df3af82fa44f0b5d943d462d …

[jobs] fix possible managed job status issues

---

sky/jobs/state.py
sky/jobs/utils.py
sky/skylet/constants.py

Usually, a job should always transition to a terminal status before it is set to DONE. However, if a bug makes that fail for some reason (e.g. the issues fixed in #4637), we should still catch this state.

[jobs] catch jobs that are DONE but non-terminal

---

sky/clouds/service_catalog/data_fetchers/fetch_aws.py

Fixes #4652.
I manually run `python -m sky.clouds.service_catalog.data_fetchers.fetch_aws --no-az-mappings --check-all-regions-enabled-for-account`, and got different `Accelerator Name` on `p5en.48xlarge`:
```
1,6c1,6
< p5en.48xlarge,NVIDIA,8.0,192.0,2048.0,"{'Gpus': [{'Name': 'NVIDIA', 'Manufacturer': 'NVIDIA', 'Count': 8, 'MemoryInfo': {'SizeInMiB': 144384}}], 'TotalGpuMemoryInMiB': 1155072}",106.0,28.050400,ap-northeast-1,apne1-az4
< p5en.48xlarge,NVIDIA,8.0,192.0,2048.0,"{'Gpus': [{'Name': 'NVIDIA', 'Manufacturer': 'NVIDIA', 'Count': 8, 'MemoryInfo': {'SizeInMiB': 144384}}], 'TotalGpuMemoryInMiB': 1155072}",84.8,21.160300,us-east-2,use2-az1
< p5en.48xlarge,NVIDIA,8.0,192.0,2048.0,"{'Gpus': [{'Name': 'NVIDIA', 'Manufacturer': 'NVIDIA', 'Count': 8, …
```

[Catalog] Workaround for wrong accelerator name of `p5en.48xlarge` returned by AWS api

---

sky/clouds/do.py

Previously
```
DO: disabled                              
Reason: sky.provision.do.utils.DigitalOceanError: no credentials file found from the following paths ['/home/vscode/Library/Application Support/doctl/config.yaml', '/home/vscode/.config/doctl/config.yaml']
During handling of the above exception, another exception occurred:
ModuleNotFoundError: No module named 'pydo'
The above exception was the direct cause of the following exception:
ImportError: Failed to import dependencies for DO. Try pip install "skypilot[do]"
```
Now
```
DO: disabled                              
Reason: Failed to import dependencies for DO. Try pip install "skypilot[do]"
```

[UX] Remove do exception in `sky check`

---

tests/smoke_tests/test_managed_job.py

This fixes an issue from #4680, where we removed the test identifier causes the smoke test to fail since there can be jobs with the same name from previous tests.

[Test] Keep the test identifier for cancellation test

---

sky/provision/kubernetes/utils.py

Our TPU support broke `sky show-gpus` for GKE clusters containing GPUs. Since the labelformatter now returns multiple possible label types, our `show-gpus` logic would try to detect TPUs in the GKE cluster and mark GPU name as none when it was not found.
```
Kubernetes GPUs (context: gke_sky-dev-465_us-central1-c_testclusterromil)
GPU   REQUESTABLE_QTY_PER_NODE  TOTAL_GPUS  TOTAL_FREE_GPUS
L4    1                         2           2
T4    1                         2           2
V100  1                         2           2
Kubernetes per node accelerator availability
NODE_NAME                                        GPU_NAME  TOTAL_GPUS  FREE_GPUS
gke-testclusterromil-default-pool-41dc668e-10t7  None      1           1
gke-testclusterromil-default-pool-41dc668e-5x09  None      1 …
```

[k8s] Fix sky show-gpus not showing GPU name on GKE

---

examples/multi_echo.py
sky/templates/kubernetes-ray.yml.j2
tests/smoke_tests/test_basic.py

Fixes a few bugs for v0.8.0:
* Fix FUSE not getting installed on Miniconda base image due to debconf conflicts
* Fix multi-echo test for k8s (2CPU default limits number of concurrent jobs)
* Disable fast launch test for k8s since it requires autostop.

[Tests] Bug fixes for v0.8.0

---

.buildkite/generate_pipeline.py
tests/smoke_tests/test_basic.py
tests/smoke_tests/test_cluster_job.py
tests/smoke_tests/test_managed_job.py
tests/smoke_tests/test_mount_and_storage.py
tests/smoke_tests/test_sky_serve.py

* We now support the `--kubernetes` flag for the test command. 
* Buildkite will launch an EKS/GKE cluster, and tests marked with `resource_heavy` will be scheduled on it when `--kubernetes` flag is specified. 
* Tested under branch #4673.
Kubernetes tests don't yet pass 100%, but this PR introduces running them on EKS clusters in Buildkite. Subsequent PRs can focus on fixing the Kubernetes tests.

Buildkite support for the `--kubernetes` flag with EKS/GKE cluster

---

sky/server/common.py

My autostarted local API server was dying when I ctrl+c the CLI command that autostarted it.
This prevents the ctrl+c / SIGINT from being passed through to the API server.

[client-server] avoid killing the API server on SIGINT

---

docs/source/running-jobs/distributed-jobs.rst
examples/distributed_ray_train/ray_train.yaml

Closes https://github.com/skypilot-org/skypilot/issues/4695. 
Seems like our subprocess handling kills the user started raylet processes after the SkyPilot job terminates. This PR fixes it by stalling the worker job with a sleep after `ray start`, presumably giving `ray start` enough time to daemonize.
Tested on AWS and Kubernetes.

[Examples] Fix ray distributed training example

---

tests/skyserve/http/kubernetes.yaml
tests/skyserve/multi_ports.yaml
tests/skyserve/update/bump_version_after.yaml
tests/skyserve/update/bump_version_before.yaml

[Tests] Update initial_delay for serve tests to account for slow EKS load balancer provisioning

---

sky/clouds/service_catalog/data_fetchers/fetch_lambda_cloud.py

This pull request adds `IAD02` (`us-east-3`) to Lambda Cloud's regions.
Closes: #4702

Add IAD02 (us-east-3) to Lambda Cloud regions

---

Dockerfile
sky/__init__.py

Freeze the version on the master branch on ~~2025-02-08~~ 2025-02-12.
The `releases/*` branches are protected, so use the `cut_version_date` branch for code review.
base branch: `cut_version_date` is the master branch on 2025-02-12.
current branch: base branch + following changes:
* And the [bump up version commit](https://github.com/zpoint/skypilot/commit/77c1286b880d20b3eed5b7cbaff3f7b5f0aaa628)
Release Test:
The release test was conducted in the branch [0.8.0_rc_20250212_test](https://github.com/zpoint/skypilot/tree/dev/zeping/0.8.0_rc_20250212_test), [diff here](https://github.com/zpoint/skypilot/compare/dev/zeping/0.8.0_rc_20250212_test...dev/zeping/0.8.0_rc)
After the test:
* #4700  
* #4699  
* #4697  
were merged without additional testing, which should be fine.  
Therefore, we …

[Release] Release 0.8.0

---

sky/clouds/kubernetes.py

Before this change, `sky launch --cloud k8s --cpus 0.5` will be broken. It will run `ray start --num-cpus=0` which means that the job PG will never be scheduled, so all jobs will just be pending forever.
Ideally we can set num-cpus to a fractional value, but this is not supported in ray. So just make sure it is at least `1`.

[k8s] make sure ray num-cpus is at least 1

---

sky/data/storage.py
tests/smoke_tests/test_mount_and_storage.py

This PR resolves two issues:
**Issue 1:** When there is an existing Azure bucket in SkyPilot storage database, the sub path will be ignored. This affects the smoke test `pytest tests/test_smoke.py::test_managed_jobs_storage --azure`.
To reproduce:
1. set `jobs.bucket: https://xxx.blob.core.windows.net/yyy` that is previously created by SkyPilot in `~/.sky/config.yaml`
2. `sky jobs launch -n test-azure-upload test.yaml`
```yaml
#
#
file_mounts:
/tmp/workdir: ~/tmp-workdir
~/tmpfile: ~/tmpfile
~/a/b/c/tmpfile: ~/tmpfile
run: |
set -ex
cat ~/tmpfile
cat ~/a/b/c/tmpfile
echo "hello world!" > /output_path/output.txt
```
The bucket will be polluted with in the root directory, and the job above fails with:
<details>
<summary>Detailed Error</summary>
```
E 02-13 01:43:29 subprocess_utils.py:149] …
```

[Storage] Azure bucket sub directory is ignored if the bucket previously exists

---

docs/source/examples/docker-containers.rst
docs/source/reference/yaml-spec.rst
examples/airflow/workflow_clientserver/README.md
sky/clouds/kubernetes.py
sky/clouds/runpod.py
sky/provision/provisioner.py
sky/provision/runpod/utils.py
sky/resources.py
sky/server/requests/executor.py
sky/server/requests/queues/mp_queue.py
sky/server/server.py
sky/skylet/constants.py
sky/task.py
sky/templates/runpod-ray.yml.j2
sky/utils/common_utils.py
tests/smoke_tests/test_mount_and_storage.py

1. change the default port of QueueManager to avoid conflict with WeCom (HDFS datanode also uses 50010 by default)
2. QueueManager will bind at `localhost` instead of `0.0.0.0`
3. Check port availability explicitly to fail fast
```
I 02-13 21:55:12 executor.py:400] SkyPilot API server will start 24 workers for blocking requests and will allow at max 53 non-blocking requests in parallel.
I 02-13 21:55:12 executor.py:407] Creating shared request queues
ERROR:__main__:Failed to start SkyPilot API server: [RuntimeError] Queue manager port 50010 is already in use.
INFO:__main__:Shutting down SkyPilot API server...
File "/opt/homebrew/anaconda3/envs/sky/lib/python3.10/runpy.py", line 196, in _run_module_as_main
return _run_code(code, main_globals, None,
File …
```

[Client-server] fix address confliction check on MacOS

---

README.md

[Docs] README polishes.

---

llm/deepseek-r1-distilled/README.md

[Examples] Fix deepseek link

---

sky/provision/vast/utils.py

Fixed Vast instance creation to include the disk size argument. If a disk size is not passed it defaults to just 10 GiB.

fix: Include disk size during instance creation

---

sky/server/common.py

Currently, the python executable can be different from the one used by the current sky program, which can cause module not found issue reported by a user.

[Core] Use the same python to run API server

---

llm/deepseek-r1-distilled/README.md
llm/deepseek-r1-distilled/deepseek-r1-vllm.yaml
llm/deepseek-r1/README.md
llm/deepseek-r1/deepseek-r1-671B-A100.yaml
llm/deepseek-r1/deepseek-r1-671B.yaml

Resolves #4723
A100 does not support FP8, but the current example incorrectly lists `A100` as a valid accelerator.
This PR removes A100 from the default accelerator list and introduces a dedicated job YAML for running DeepSeek-R1 on A100 with BF16 conversion. It also adds a documentation section explaining how to use A100 properly.
Additionally, this PR addresses several documentation inconsistencies and improves wording for clarity.

[Docs] Fix A100 Support for DeepSeek-R1 671B: Clarify FP8 Issue & YAML Inconsistencies

---

sky/clouds/service_catalog/data_fetchers/fetch_gcp.py

TPU V6e's pricing is missing in a new zone. This PR add it to the blocked list.

[Catalog] Add TPU v6e missing zone southamerica-west1

---

sky/provision/kubernetes/utils.py
tests/unit_tests/kubernetes/test_instance_type.py

Update the instance type format for Kubernetes to support number-only accelerator type, which is reported in https://github.com/skypilot-org/skypilot/issues/4608.
```
✗ python -m sky.cli launch -y -c mygpucluster --cloud k8s --gpus 4090:1 --cpus 1 --memory 6 --dryrun -- "nvidia-smi"
Command to run: nvidia-smi
Running on cluster: mygpucluster
D 02-20 10:15:11 optimizer.py:301] #### Task<name=sky-cmd>(run='nvidia-smi')
D 02-20 10:15:11 optimizer.py:301]   resources: Kubernetes(cpus=1, mem=6, {'4090': 1}) ####
D 02-20 10:15:11 optimizer.py:316] Defaulting the task's estimated time to 1 hour.
D 02-20 10:15:11 optimizer.py:338] resources: Kubernetes(1CPU--6GB--4090:1, cpus=1, mem=6, {'4090': 1})
D 02-20 10:15:11 optimizer.py:357]   estimated_runtime: 3600 s (1.0 …
```

[k8s] Update the instance type format to support number only accelerator type

---

sky/backends/cloud_vm_ray_backend.py
sky/jobs/controller.py
sky/jobs/server/core.py
sky/skylet/constants.py
sky/task.py
sky/templates/jobs-controller.yaml.j2
sky/utils/controller_utils.py

Avoids the need for a cloud bucket for simple file mounts in managed jobs, by syncing files over two hops:
1. First hop is local -> jobs controller
2. Second hop is jobs controller -> managed job cluster
See `translate_local_file_mounts_to_two_hop()`:
This strategy will upload the local files to the controller first, using
a normal rsync as part of sky.launch(). Then, when the controller launches
the task, it will also use local file_mounts from the destination path of
the first hop.
Local machine/API server        Controller              Job cluster
------------------------  -----------------------  --------------------
|      local path -----|--|-> controller path --|--|-> job dst path   |
------------------------  -----------------------  --------------------
Tested (run the relevant …

[jobs] two-hop file_mounts upload

---

charts/skypilot/Chart.yaml
charts/skypilot/templates/ingress-nodeport.yaml
charts/skypilot/templates/ingress.yaml
charts/skypilot/values.yaml

close #4777 
A quick fix to allow me test multiple API server in one k8s. After this PR, I can deploy an API server under `host:port/test1` and use `sky api login -e http://host:port/test1` to access the server.
Minimal Helm command to deploy more API servers after the first one:
```bash
helm upgrade --install second-server charts/skypilot \
--namespace skypilot \
--set ingress.authCredentials=$AUTH_STRING \
--set ingress-nginx.enabled=false \
--set ingress.path=/yourpathhere
```
TODO: udpate doc

[API server] allow multiple deployment in one k8s

---

docs/source/reference/api-server/api-server-admin-deploy.rst

Adds a quick warning that the API server deployment using VMs does not have any auth out of the box. 
Longer term TODO is to add the nginx reverse proxy with auth in our example YAML.

[Docs] Add notes on authentication for VM based API server depoyment

---

sky/server/common.py

[server] redirect stdin on server launch

---

sky/cli.py
sky/jobs/server/server.py
sky/server/common.py
sky/server/requests/executor.py
sky/server/requests/payloads.py
sky/server/server.py
sky/usage/usage_lib.py
sky/utils/common_utils.py

[Usage] Fix usage for remote API server

---

sky/global_user_state.py

Fixes for a problem with newer versions of sqlite3 that might have SQLITE_DQS=0 setting enable, which disables the double-quoted string literal misfeature.

Small fixes for a problem with newer versions of sqlite3

---

charts/skypilot/templates/api-deployment.yaml

close #4772 
follow up https://github.com/skypilot-org/skypilot/pull/4776#discussion_r1968820376

[API server] output all logs to stdout in helm deployment

---

charts/skypilot/templates/ingress-nodeport.yaml

close https://github.com/skypilot-org/skypilot/issues/4815

[API server] fix nodeport sevice selector

---

sky/adaptors/kubernetes.py

We now surface underlying kubeconfig errors directly to the user, even if they don't have debug flag set. This is important to help users debug issues themselves.

[k8s] Surface kubeconfig errors to users

---

sky/cli.py

A user experience the following issue when running `sky status`:
```
File "sky/cli.py", line 137, in _get_cluster_records_and_set_ssh_config
credentials = record['credentials']
~~~~~~^^^^^^^^^^^^^^^
KeyError: 'credentials'
```

[Core] Only set credentials when it exists

---

.github/workflows/weekly-smoke-tests-trigger.yaml
README.md

* Trigger smoke tests pipeline weekly, Add a new pipeline that will trigger the following commands in one single build:
* `/smoke-test --aws`
* `/smoke-test --gcp`
* `/smoke-test --azure`
* `/smoke-test --kubernetes`
* Tested on my personal [repo](https://github.com/zpoint/skypilot/pull/14), successfully triggered this [build](https://buildkite.com/skypilot-1/full-smoke-tests-run/builds/1)
* A `workflow_dispatch` trigger
* Add badge on readme file
* Replacement of #4755 since external PR can not read secret from repo.

Weekly smoke tests trigger on Github action

---

charts/skypilot/templates/api-deployment.yaml
sky/cli.py
sky/client/sdk.py
sky/server/common.py
sky/server/requests/executor.py
sky/server/server.py

In #4843 , API server can not start in 12 seconds on a 176 core machine since API server starts as many unvicorn processes as the cores.
Follow up https://github.com/skypilot-org/skypilot/pull/4776#discussion_r1968820376 , add a new arg `--foreground` to `sky api start` command that runs the API server in current process instead of background, so that:
1. The startup check is bypassed, enables the configurable k8s liveness/readiness probe to take effect;
2. The server can be the pid 1 process (or a direct child of pid 1 init process) in the container, enables correct signal handling in container;
3. The redundant log file in container and tail process can be eliminated;
close #4776 
close #4771 
It is a bit complicated to run smoke test for `--foreground` since we need an isolated sandbox …

[API server] run API server in foreground in k8s Pod

---

sky/utils/controller_utils.py

This change is a quick fix of the message given by the command `sky status`
When you run it the output is similar to 
```
Clusters                                                                                                          
No existing clusters.                                                                                             
Managed jobs                                             
No in-progress managed jobs. (See: sky jobs -h)                                                                   
Services                                                                                                          
NAME              VERSION  UPTIME       STATUS  REPLICAS  ENDPOINT                    
sky-service-xxxx  1        19h 11m 18s  READY   1/1 …
```

[Utils] Quickfix serve status message

---

docs/source/reservations/existing-machines.rst
sky/cli.py
sky/client/sdk.py
sky/core.py
sky/server/requests/payloads.py
sky/utils/kubernetes/deploy_remote_cluster.sh
sky/utils/kubernetes/kubernetes_deploy_utils.py

This PR adds support for specifying a custom Kubernetes context name when using sky local up to deploy a remote cluster. This provides better control over kubeconfig context naming, especially useful when merging multiple kube contexts. 
Also adds multi-cluster docs.

[Existing clusters] Add `--context-name` arg, multi-cluster docs

---

.github/workflows/docker-build.yaml
Dockerfile
Dockerfile_k8s
Dockerfile_k8s_gpu
docs/source/reservations/existing-machines.rst
sky/backends/backend_utils.py
sky/cloud_stores.py
sky/clouds/gcp.py
sky/clouds/service_catalog/images/provisioners/cuda.sh
sky/clouds/service_catalog/images/skypilot-k8s-image.sh
sky/data/mounting_utils.py
sky/exceptions.py
sky/setup_files/dependencies.py
sky/skylet/constants.py
sky/utils/controller_utils.py
tests/smoke_tests/test_cluster_job.py

Mitigates #4793
Fixes #4601 
This enables the SkyPilot clusters to run on arm architecture with the default image.
ARM support is becoming more important as the NV's GH200, GB200 (offered by Lambda clouds, GCP) come with ARM CPUs by default, but our docker image does not support ARM CPU well.
Original k8s gpu image does not support ARM architecture
```
sky launch --cloud lambda --gpus gh200 nvidia-smi --image-id docker:us-docker.pkg.dev/sky-dev-465/skypilotk8s/skypilot-gpu:latest -c test-lambda-arm-origin
```
Error:
```
latest: Pulling from sky-dev-465/skypilotk8s/skypilot-gpu
no matching manifest for linux/arm64/v8 in the manifest list entries
⨯ Failed to set up SkyPilot runtime on cluster.  View logs: sky api logs -l sky-2025-02-27-22-36-28-562705/provision.log …
```

[Core] Support ARM architecture

---

docs/source/reference/kubernetes/kubernetes-getting-started.rst

[Docs] Elevate k8s volume mounting to its own section

---

docs/source/reference/faq.rst

[Docs] Avoid back links in FAQ

---

sky/cli.py

[jobs] catch NotSupportedError for `sky down --purge`

---

sky/jobs/utils.py
tests/backward_compatibility_tests.sh

close https://github.com/skypilot-org/skypilot/issues/4886
Covered by Backward compatibility tests, so no new case is added
Note that backward compatibility test of **THIS PR** will still fail since the skylet is deployed using the code on master branch. I verified this PR by changing the base branch of compatibility test to current branch. Checkout the test result here: https://buildkite.com/skypilot-1/quicktest-core/builds/172#019566fe-818b-4571-9a5c-279fada58ef2

[Test] fixed managed job return code with --no-follow for compatibility test

---

examples/airflow/README.md
examples/airflow/sky_train_dag.py

Our airflow example DAG has a `k8s` in the filename and DAG name even though it's not limited to k8s by any means. This PR renames it to a more general `sky_train_dag.py`.

[Examples] Rename airflow DAG

---

sky/server/server.py

close #4882
Test:
```
$ export SKYPILOT_DEBUG=0
$ sky api stop && sky api start && tail -f ~/.sky/api_server/server.log
...
I 03-05 17:22:50 executor.py:349] [Worker(id=1, schedule_type=short)] Submitting request: skypilot-status-refresh-daemon
I 03-05 17:22:50 executor.py:366] [Worker(id=1, schedule_type=short)] Submitted request: skypilot-status-refresh-daemon
I 03-05 17:22:51 executor.py:241] Running request skypilot-status-refresh-daemon with pid 43591
$ export SKYPILOT_DEBUG=1
$ sky api stop && sky api start && tail -f ~/.sky/api_server/server.log
...
D 03-05 17:23:19 payloads.py:60] The following keys ({"allowed_clouds": ["kubernetes"]}) are specified in the client SkyPilot config at '/Users/aylei/.sky/config.yaml'. This will be ignored. If you want to specify it, please modify it …
```

[API server] honor SKYPILOT_DEBUG env in server log

---

sky/jobs/server/core.py
sky/jobs/utils.py

Only the API server has full view of all the users. Neither the jobs controller or the client will necessarily have it. So we need to make sure that the resolution of user_id -> user name happens when the API server loads the managed jobs table.

[jobs] resolve jobs queue user on API server side

---

docs/source/reference/config.rst
docs/source/reference/kubernetes/kubernetes-getting-started.rst

Minor updates:
* Fix the k8s autoscaler config.yaml docs
* Link to multi-kubernetes docs in the getting started page.

[Docs] K8s docs updates

---

sky/jobs/server/core.py
sky/jobs/server/server.py
sky/templates/jobs-controller.yaml.j2
sky/utils/command_runner.py

Now the jobs controller will be started using SERVER_ID - the dashboard also needs to use SERVER_ID as the USER_ID, so that it can get cluster info.
Fix a couple of other bugs with the dashboard plumbing.
Fixes #4825.

[jobs] fix dashboard for remote API server

---

docs/source/reference/config.rst

[docs] add jobs controller resource tuning reference in config page

---

sky/utils/rich_utils.py
tests/unit_tests/sky/utils/test_rich_utils.py

Closes #4905.
Our chunking may chunk in the middle of a UTF-8 sequence, which would cause decoding to break. We now store the undecoded bytes in a buffer and wait to receive the next chunk before trying to decode again.

[Core] Handle mid-sequence chunking in log streaming

---

sky/backends/wheel_utils.py

The `test_launch_fast --kubernetes` test has been failing intermittently on buildkite and occasionally on local machines. Upon investigation, it was discovered that the `config_hash` was changing due to modifications in `.pyc` files, specifically `sky/clouds/service_catalog/__pycache__/kubernetes_catalog.cpython-310.pyc`. This caused the `--fast` flag to not work as expected, as the cached wheel was not being reused.
[Failure build with detail log](https://buildkite.com/skypilot-1/smoke-tests/builds/290#01956494-3ed6-4dc9-8c4e-37883f35df0b)
* `_get_latest_modification_time` excludes `.pyc` and `__pycache__` files. This ensures that `build_sky_wheel` reuses the cached wheel if no changes are detected in the source code files.

Exclude `.pyc` and `__pycache__` files from config hash calculation to fix `test_launch_fast --kubernetes` failures

---

sky/server/requests/executor.py
sky/server/server.py
sky/server/uvicorn.py
sky/utils/subprocess_utils.py
tests/unit_tests/sky/utils/test_subprocess_utils.py

For https://github.com/skypilot-org/skypilot/issues/4843, the number of uvicorn workers and skypilot's background long workers are proportional to available CPU cores, which cause issues if the machine is not dedicated to our API server. e.g. the machine has 128 cores but the API server can only get 10 due to contention. The CPU pressure of launching 128 + 256 worker processes simultaneously would severely slow the startup.
This PR introduces TCP-like start for unvicorn workers and long workers. The launch delay is set to fix value based on profiling (2 seconds now) for simplicity.
Test on simulated high resource contention env on my 12 core laptop:
```bash
$ export SKYPILOT_POD_CPU_CORE_LIMIT=64
$ export SKYPILOT_POD_MEMORY_GB_LIMIT=256
/usr/bin/time sky api start --deploy …
```

[API server] accelerate start by slowly start workers

---

sky/backends/backend_utils.py

fixes #4873, fixes #4752, and fixes #4753.
In some cases, immediately after a cluster is provisioned, not all nodes may yet show in `ray status`.
Work around this case by double-checking the (relatively rare) case where all the nodes are up on the cloud side but some are missing from `ray status`.

[core] if not all nodes are in ray status, double check after 5s

---

docs/source/reference/config.rst

First step to removing `networking: nodeport` (#4927). The docs entries were incorrect anyway - the possible values are `portforward` and `nodeport`.

[Docs] Remove `networking: nodeport` from config docs

---

sky/backends/cloud_vm_ray_backend.py

The old failvoer handler is not in used for lambda and oci cloud. Moving it to version 2 now.

[Core] Fix failover handler for clouds moved to new provisioner

---

sky/setup_files/dependencies.py

This seems to resolve the crashes we've been seeing in CI ([example](https://github.com/skypilot-org/skypilot/actions/runs/13818935203/job/38662591200?pr=4930)). Seems something changed in downstream deps, but this at least works around whatever happened.
Broken: `uv pip install --prerelease=allow 'azure-cli>=2.65.0' && uv pip install skypilot[aws,azure,ibm]`
After this PR, it works.
Note that this also affects uv installation of stable. We could release 0.8.1 to work around.

[deps] pin ibm-platform-services to >=0.48.0 to work around issue

---

sky/client/sdk.py
sky/server/common.py
sky/server/requests/requests.py

Before, on API server startup, we would delete ~/.sky/api_server/requests.db, but not requests.db-wal or requests.db-shm. This could lead to inconsistent SQLite state on startup, which would surface as `sqlite3.OperationalError: disk I/O error`, if the previous API server exited abnormally (e.g. kill -9).
To fix, make sure to remove all three files.
This may also mitigate the impact of #4894.
- `sky api start`
- `ps -ef | grep -- '-m sky.server'` and `lsof -i :50011` to find PIDs
- `kill -9` the two PIDs from before
- `sky api start` again. It will fail with `sqlite3.OperationalError: disk I/O error` before this PR, but works after this PR.

[api server] avoid deleting requests.db but not -wal/-shm

---

sky/provision/kubernetes/utils.py

When evaluating k8s nodes to serve jobs, only consider nodes that have enough GPU capacity to serve the job.
Note: Here we use the total node GPU, not free node GPU, to determine node eligibility. The idea is a node that has enough total GPUs which are not free at the moment can serve the (queued) job once the current job is done, but if a node's total GPU count is less than what the job requires then the node can _never_ serve the job.
The check is performed via calling `get_node_accelerator_count` on `node.status.allocatable`, which is used on `sky/clouds/service_catalog/kubernetes_catalog.py:L209-L211`
```
accelerator_count = (
kubernetes_utils.get_node_accelerator_count(
node.status.allocatable))
```
to generate the total free GPUs for the node when using `sky show-gpus`.
Tested …

[k8s] filter out nodes with less accelerators than requested

---

sky/adaptors/gcp.py
sky/clouds/gcp.py
sky/data/storage.py
sky/utils/controller_utils.py

If a cloud is not enabled, we should error out if it is used as an intermediate bucket for jobs.
This slightly mitigate the issue in #4946

[Jobs] Error out for intermediate bucket on cloud not enabled

---

tests/smoke_tests/test_basic.py

See this [build](https://buildkite.com/skypilot-1/smoke-tests/builds/400#01959882-6771-450a-a559-d7dae30683e0). The first 8 times, the cluster just shows `UP` when checking for sky status. Wait for either `INIT` or `UP` status to make the test less flaky. Save @SeungjinYang's manual click 😄.

Fix flaky for test_cancel_launch_and_exec_async

---

sky/clouds/kubernetes.py
sky/provision/kubernetes/utils.py

Addresses https://github.com/skypilot-org/skypilot/issues/4875 
Currently, if a node autoscaler is configured in a k8s cluster, the only thing skypilot knows about the autoscaler is the [configuration](https://docs.skypilot.co/en/latest/reference/config.html#kubernetes-autoscaler) provided by the user. Specifically, skypilot has no idea if there is a node pool with the node type that may be able to handle a job that has simply been autoscaled to zero. Currently, skypilot gets around this by simply submitting a pod to each context with autoscaler enabled and seeing if the pod is scheduled before timeout.
While this approach is functional, it is inefficient because:
- A context (=cluster) may have an autoscaling node pool, but the node pool may not provide the VM needed to satisfy the …

[k8s] better support for GKE scale-to-zero autoscaling node pools

---

sky/provision/kubernetes/utils.py

The check for vcpu/memory here was backwards.

fix incorrect vcpu/mem checks for GKE autoscaler

---

charts/skypilot/templates/ingress.yaml

Fixed Helm warning: annotation "kubernetes.io/ingress.class" is deprecated #4922 

fix annotation "kubernetes.io/ingress.class" is deprecated

---

sky/optimizer.py

[UX] Fix dense cli for resources not enough

---

tests/backward_compatibility_tests.sh

Currently, the `backward_compatibility_tests.sh` file runs on bash, but some mac computers (like mine) has ZSH. These macs have bash too and specifying `#!/bin/bash` works fine to run the code, but when it tries to access non-existent `.bashrc` files, then it errors out. 
Obviously, the simple fix to this is to just create a bashrc file. This fix automatically adds that feature so that manual intervention is not necessary.

[Test] Add support for missing bashrc file in zsh shells

---

docs/source/reference/kubernetes/kubernetes-setup.rst

Per-task examples were missing `kubernetes` key.

[Docs] Fix NFS mounting docs for k8s

---

sky/provision/kubernetes/utils.py

[k8s] GKE support for TPU V6

---

tests/smoke_tests/test_managed_job.py

See detail failure from [weekly somke tests run](https://buildkite.com/skypilot-1/full-smoke-tests-run/builds/12#_)

Fix test_managed_jobs_storage failure on azure in master branch

---

.buildkite/generate_pipeline.py
tests/smoke_tests/test_cluster_job.py

Separate different parameters into different steps for better visualization of logs on buildkite, and also increase timeout to fix #4943.
See [comment](https://github.com/skypilot-org/skypilot/issues/4943#issuecomment-2724104230)
Previously:
```yaml
- agents:
queue: generic_cloud
command: pytest tests/smoke_tests/test_cluster_job.py::test_job_queue_with_docker
--aws
label: test_job_queue_with_docker on aws
retry:
automatic: true
```
Now:
```yaml
- agents:
queue: generic_cloud
command: pytest tests/smoke_tests/test_cluster_job.py::test_job_queue_with_docker
--aws -k docker:nvidia/cuda:11.8.0-devel-ubuntu18.04-accelerator0
label: test_job_queue_with_docker on aws with param docker:nvidia/cuda:11.8.0-devel-ubuntu18.04-accelerator0
retry:
automatic: true
- agents:
queue: generic_cloud …
```

[Test]Separate different param into different steps on buildkite and fix flacky of test_job_queue_with_docker

---

sky/provision/gcp/instance.py

Fixes https://github.com/skypilot-org/skypilot/issues/4981
Manually tested (via print debugging) that `GCPTPUVMInstance.load_resource` is no longer called when launching sky serve controller instance.
The pattern here is already established at other places in this file:
https://github.com/skypilot-org/skypilot/blob/master/sky/provision/gcp/instance.py#L73-L75
https://github.com/skypilot-org/skypilot/blob/master/sky/provision/gcp/instance.py#L410-L412
https://github.com/skypilot-org/skypilot/blob/master/sky/provision/gcp/instance.py#L473-L475
https://github.com/skypilot-org/skypilot/blob/master/sky/provision/gcp/instance.py#L524-L547
so it's most likely that the pattern was simply left out in this one place.
Before
```
% sky serve up --cloud gcp service.yaml 
YAML to run: service.yaml …
```

[GCP] Don't require TPU support for serve:gcp if TPU support is not required

---

sky/serve/replica_managers.py

Previously, when there is an `any_of` field in the yaml, it will be load as a set and store back as a list in the YAML, which sometimes cause the list order not correct and version bump to fail. This PR fixed it.

[Serve] BugFix: `any_of` field order issue cause version bump to not work

---

sky/adaptors/kubernetes.py

[k8s] Fix kubeconfig path in error if `KUBECONFIG` envvar is used

---

sky/data/storage_utils.py
sky/exceptions.py
sky/utils/command_runner.py
tests/unit_tests/test_storage_utils.py

Fixes #4933, where we don't properly handle the output of `git status` when in a subdirectory of a git repo. Make this handling more robust by
- using `git ls-files` and handling relative paths correctly
- recursing into submodules of the current directory
Unit tests written by windsurf cascade/sonnet with heavy feedback/direction.
A follow-up is to use this same codepath for rsync (instead of just bucket upload), for consistency.

[storage] use `git ls-files` to handle .gitignore more robustly

---

sky/jobs/utils.py

If there is a local API server running on the jobs controller (could be triggered by the jobs dashboard), then preempted clusters may get automatically cleaned up during regular status refresh.
This could cause an AssertionError in the controller code, which assumed that clusters should only be cleaned up by itself.
To fix, explicitly handle the case where the cluster has already been cleaned up.

[jobs] fix AssertionError for preempted cluster

---

.github/workflows/weekly-smoke-tests-trigger.yaml

Tested under my personal repo:

[Test] Github action trigger support param

---

tests/skyserve/streaming/send_streaming_request.py
tests/smoke_tests/test_cluster_job.py
tests/smoke_tests/test_images.py
tests/smoke_tests/test_managed_job.py
tests/smoke_tests/test_sky_serve.py

We achieved a [100% pass rate](https://buildkite.com/skypilot-1/full-smoke-tests-run/builds/13#_) on the full smoke tests.
However, some tests still required retries to pass. By inspecting the logs, we found that modifying the test code could reduce flakiness in some tests.

[Test]fix flaky smoke tests
