- sky/adaptors/cloudflare.py
- sky/check.py
- sky/clouds/cloud.py
- sky/core.py
- sky/data/storage.py
- sky/optimizer.py
- sky/server/server.py
- sky/utils/kubernetes/kubernetes_deploy_utils.py
- tests/common_test_fixtures.py
A few improvements to `sky check` output to better expose the capabilities enabled for each cloud:
- A cloud shows up as enabled for a capability even if its compute is disabled. See example screenshots: If GCP credentials is enough for storage but not compute, the new output correctly characterizes the credential.
- Each enabled cloud also shows the capabilities that are enabled for the cloud.
- Hints and reasons are associated with one or more cloud capabilities. 
- `clouds` in `To enable a cloud, follow the hints above and rerun: sky check <clouds>` is lowercased.
- Cloudflare no longer displays `(for R2 object store)`, as that part is now made obvious by capabilities enabled.
Before:
After:
> [UX] "sky check" output improvements to reflect independent capability checks

- sky/clouds/nebius.py
Fixes after https://github.com/skypilot-org/skypilot/pull/4977, https://github.com/skypilot-org/skypilot/pull/4993
Introduce `check_storage_credentials` method to verify if the Nebius Object Storage profile is configured in AWS credentials. Also, refactor credential setup messages for better readability and add utility `_INDENT_PREFIX` for consistent formatting.
> [Nebius] Fix check storage credentials for Nebius

- sky/utils/kubernetes/gpu_labeler.py
Before:
```
% python -m sky.utils.kubernetes.gpu_labeler
<sky-payload>"<rich_init>Setting up GPU labeling</rich_init>"</sky-payload>
<sky-payload>"<rich_update>Setting up GPU labeling</rich_update>"</sky-payload>
<sky-payload>"<rich_start>Setting up GPU labeling</rich_start>"</sky-payload>
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>
<sky-payload>"<rich_init>Creating GPU labeler jobs</rich_init>"</sky-payload>
<sky-payload>"<rich_update>Creating GPU labeler jobs</rich_update>"</sky-payload>
<sky-payload>"<rich_start>Creating GPU labeler jobs</rich_start>"</sky-payload>
Found 1 GPU nodes in the cluster
Using default RuntimeClass for GPU labeling.
Created GPU labeler job for node ip-192-168-0-11.ec2.internal
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>
GPU labeling started - …
```
> [UX] GPU labeler UX improvement

- charts/skypilot/templates/api-deployment.yaml
- charts/skypilot/values.yaml
Signed-off-by: David Young <davidy@funkypenguin.co.nz>
Hi guys,
In our environment we use various policy controls to prevent insecure deployments, and in order to deploy skypilot-api, I needed basic securityContexts applied to both the pod and the container. 
I've updated the chart to set some working securityContext defaults (*can be tightened one day if we don't run as root*), 
as well as the option for a custom runtimeClassName (*we use kata containers, for example*)
The changes are tested and running happily in our Kubernetes 1.30 cluster. The `runtimeClassName` feature was released as stable in Kubernetes 1.20.
Cheers!
D
> Add options to set pod/container securityContext, runtimeClassName

- sky/backends/cloud_vm_ray_backend.py
- sky/server/requests/requests.py
The recent PR #4867 adds a new column in request db, but does not have a backward compatibility handling for existing request DB. It is ok for API server, which will remove the request DB during restart, but it fails the managed jobs with the following reproduce:
1. `sky jobs launch` with a verion before #4867, so that the controller gets a request DB without the `status_msg` column
2. Switch to the master branch, restart the API server
3. `sky jobs launch` again and `sky jobs cancel`. The job shows `FAILED_CONTROLLER` due to the missing `status_msg` during terminating the cluster.
```
File "/home/sky/skypilot-runtime/lib/python3.10/site-packages/sky/jobs/utils.py", line 101, in terminate_cluster
core.down(cluster_name)
File …
```
> [Jobs] Fix kill cluster request issue during tearing down for managed jobs

- sky/provision/gcp/constants.py
Fixes a regression introduced in https://github.com/skypilot-org/skypilot/issues/5020
Pre-https://github.com/skypilot-org/skypilot/pull/4977, having `roles/owner` role was sufficient to use both compute and storage in GCP. However, the PR incorrectly classifies `roles/owner` role as not having enough permission to use GCP storage. See the following `sky check` failure:
```
GCP: enabled [compute]
Reason [storage]: The following permissions are not enabled for the current GCP identity (apiserverbeta@sky-dev-***.iam.gserviceaccount.com [project_id=sky-dev-***]):
{'storage.objects.delete', 'storage.objects.create', 'storage.objects.get', 'storage.buckets.get', 'storage.objects.update', 'storage.objects.list'}
For more details, visit: …
```
> [GCP] relax storage minimal permissions

- sky/utils/rich_utils.py
Fixes #4907. As #4907 mentioned, there is two rich status related bug in our SkyServe system:
1. `AttributeError: 'NoneType' object has no attribute 'start'`
2. `LiveError('Only one live display may be active at once')`
The first issue is due to:
1. a side thread logger try to stop the status through `safe_logger` (code block 1, L203);
2. during emitting logs, the status has been set to `None` (code block 2, L150);
3. the side thread logger try to start the status again (code block 1, L206), causing this error.
The second issue is due to:
1. a side thread logger stop the status (code block 1, L203);
2. main thread exit a status (`__exit__` function);
3. main thread start a new status (`__enter__` function), the first live status is started;
4. the side thread logger restart the status, …
> [Serve] BugFix: LiveError on controller

- sky/backends/cloud_vm_ray_backend.py
Fixes #4769 . 
Skypilot was crashing as it was unable to find the kubernetes cluster in the `_detect_abnormal_non_terminated_nodes` helper method under `cloud_vm_ray_backend.py`. This happens because of an earlier no-cluster exception in the port cleanup section. The order of the function calls is such that during port clean up skypilot will also clean up the metadata in the state tables. However, the relevant method calls for port cleanups is processed BEFORE the metadata, this means that when an exception is raised on port clean up, metadata is not cleared, hence leading to a call of `_detect_abnormal_non_terminated_nodes`. As that function call is the last in the chain, we simply check if purge is set and clear any metadata. 
> [UX] Allow purging non-existent k8s cluster

- sky/clouds/service_catalog/data_fetchers/fetch_ibm.py
Create catalog (`ibm/vms.csv`) file from the IBM instance profiles fetched by the API.
Unfortunately, it seems that currently, it is not possible to fetch pricing. There is the pricing API but it doesn't work for the `kind:instance.profile`. It works for the `kind:service` as described in the IBM documentation (https://cloud.ibm.com/docs/account?topic=account-getting-pricing-api).
> Fetch IBM instance profiles

- tests/common_test_fixtures.py
- tests/smoke_tests/test_backward_compat.py
- tests/test_cli.py
Add one more test case: `test_client_server_compatibility` in `tests/smoke_tests/test_backward_compat.py`
First, launch managed jobs and start the cluster in the `BASE` branch. Then switch to the `CURRENT` branch without restarting the `API server`. Run the CLI commands and verify they succeed.  
Cover the following tests:
| API Version | CLI Version | Result                  | Notes                                  |
|-------------|-------------|-------------------------|----------------------------------------|
| 1           | 2           | ❌ Fails immediately    | Version mismatch error                |
| 2           | 1           | ❌ Fails immediately    | Version mismatch error                |
| 2           | 2           | ✅ Works normally       | Make sure `sky jobs`, `sky launch` …
> [Test]test client server compatibility

- sky/adaptors/gcp.py
- sky/authentication.py
- sky/backends/backend_utils.py
- sky/backends/cloud_vm_ray_backend.py
- sky/exceptions.py
- sky/provision/aws/utils.py
- sky/provision/azure/config.py
- sky/provision/kubernetes/utils.py
- sky/provision/provisioner.py
- tests/unit_tests/kubernetes/test_kubernetes_utils.py
- tests/unit_tests/test_authentication.py
- tests/unit_tests/test_aws_utils.py
Fix #4373
- For Kubernetes with expired credentials, auto-exclude the contexts
- For invalid credentials of aws, azure, and gcp after enabled in cache, failover to the other clouds for provisioning 
- Details are posted in separate comments
> [core] optimizer/provisioner fails over for cloud with expired credentials

- docs/source/reservations/existing-machines.rst
- sky/cli.py
- sky/client/sdk.py
- sky/core.py
- sky/server/requests/payloads.py
- sky/utils/kubernetes/deploy_remote_cluster.sh
- sky/utils/kubernetes/kubernetes_deploy_utils.py
Fix #4795 
- Update doc to recommend using passwordless sudo when deploying remote clusters with `sky local up`
- If passwordless sudo is not available, support setting sudo password when deploying remote clusters with `sky local up`
> [Core] Support setting sudo password when deploying remote clusters

- sky/data/storage.py
Fix bug found during https://github.com/skypilot-org/skypilot/pull/5010
Changed the prefix from 's3://' to 'nebius://' for Nebius storages to ensure consistency and accuracy in storage type representation. This update prevents confusion with AWS S3 prefixes and aligns with Nebius-specific requirements.
> [Nebius] Update Nebius storage prefix to 'nebius://'

- sky/clouds/do.py
Fix bug found during https://github.com/skypilot-org/skypilot/pull/5010
The redundant call to do_utils.client() has been removed as it required sky-pilot[do].
Issue: If you have DO and another cloud and try to serve over the other cloud, you will receive an error message saying that the DO dependencies are not installed because get_credential_file_mounts requires all DO dependencies.
> [DO] Remove unnecessary client call in get_credential_file_mounts

- charts/skypilot/values.yaml
Remove the pod security context values, they were just a dupe of the container ones, which is incorrect and causes errors.
[Pod securityContext](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#security-context) does not have `allowPrivilegeEscalation` nor `capabilities`
[Container securityContext](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#security-context-1) does have `allowPrivilegeEscalation` and `capabilities`
Manual test:
I had to set the value to `null` when I was deploying the helm chart, otherwise it didn't work.
Not sure other tests for the helm chart now
> correct security contexts

- .github/workflows/pytest.yml
- sky/cli.py
- sky/optimizer.py
This PR introduces a new test job `limited-deps-test` to the GitHub Actions workflow that:
* Tests core functionality with only essential cloud dependencies installed (Kubernetes, AWS, GCP, Azure)
* Verifies our code works when only a subset of cloud services are installed
* Runs on a subset of test files (`test_cli.py` and `test_jobs_and_serve.py`)
The change helps ensure basic functionality remains intact even when not all cloud providers are installed, improving the robustness of the package's dependency management.
> [Test] Add limited dependencies test workflow

- sky/server/common.py
- sky/server/requests/executor.py
- sky/server/requests/queues/mp_queue.py
- sky/server/server.py
close https://github.com/skypilot-org/skypilot/issues/5057
Backward compat test is now flaky due to resource contention issue. Before we get API server more resource-efficient, we can just be patient on timeout if the waited process is alive.
```
$ sky api start
Failed to connect to SkyPilot API server at http://127.0.0.1:46580. Starting a local server.
sky.exceptions.ApiServerConnectionError: Could not connect to SkyPilot API server at http://127.0.0.1:46580. Please ensure that the server is running. Try: curl http://127.0.0.1:46580/api/health
During handling of the above exception, another exception occurred:
RuntimeError: SkyPilot API server process exited unexpectedly.
View logs at: ~/.sky/api_server/server.log
```
```
$ sky api start --foreground
..... …
```
> [API server] Be patient if process is alive

- sky/data/storage_utils.py
- tests/smoke_tests/test_mount_and_storage.py
After #4988, this [test](https://buildkite.com/skypilot-1/smoke-tests/builds/464#0195d568-bb6b-4d64-ac04-442f139e66f5) is broken.
This PR:
* Resolves #5045 by adding `git init` when creating test data so that we won't ignore the `.gitignore` file. On master it goes to this [code branch](https://github.com/skypilot-org/skypilot/blob/master/sky/data/storage_utils.py#L149) and uploads all files which is not expected.
* Replaces the `['.']` with `['']` so that our upload command changes to the correct one:
* Before: 
```bash 
sync_command: aws s3 sync --no-follow-symlinks --exclude './double_asterisk/*' --exclude ./double_asterisk/double_asterisk_excluded --exclude './double_asterisk/double_asterisk_excluded_dir/*' --exclude './double_asterisk_parent/*' --exclude …
```
> Fix .gitignore incorrect upload issue and broken tests

- sky/cli.py
Before this change, when using `-y`, we would see the "Managed job will be launched on (estimated):" but then nothing would follow.
This hides the message in this case.
> [ux] don't show optimization message if info is hidden

- sky/adaptors/kubernetes.py
- sky/utils/kubernetes/gpu_labeler.py
1. Use existing helper functions where applicable instead of re-doing a lot of custom logic within the script, which prepares this script to eventually be run on the server as a result of an API call.
2. Allow the script to be called on a specific context, not just the active context.
UX:
if `--context` is specified
```
$ python -m sky.utils.kubernetes.gpu_labeler --context syang@my-cluster-2.us-east-1.eksctl.io                      
Found 1 GPU node(s) in the cluster
Using default RuntimeClass for GPU labeling.
Created GPU labeler job for node ip-192-168-56-224.ec2.internal
GPU labeling started - this may take 10 min or more to complete.
To check the status of GPU labeling jobs, run `kubectl get jobs -n kube-system -l job=sky-gpu-labeler --context syang@my-cluster-2.us-east-1.eksctl.io` …
```
> [k8s] refactor gpu labeler script / gpu labeler optionally accepts a context

- sky/jobs/controller.py
In #5031 we see that a managed job failing with FAILED_DRIVER causes an `AssertionError`.
Explicitly handle this case and provide a better error message.
This will also handle a CANCELLED job explicitly instead of similarly causing an `AssertionError`.
Both cases still result in `FAILED_CONTROLLER`, since these are internal failures rather than user code failures.
> [jobs] handle FAILED_DRIVER jobs explicitly

- sky/clouds/kubernetes.py
- sky/provision/kubernetes/utils.py
- sky/utils/kubernetes/gpu_labeler.py
Adds a hint to kubernetes `sky check` for any nodes with accelerators that are not properly labeled for use with SkyPilot.
The logic to detect contexts without proper labels can later be used to automatically label GPUs on those contexts.
Related issue: https://github.com/skypilot-org/skypilot/issues/4958
Fixes https://github.com/skypilot-org/skypilot/issues/5023
```
$ python -m sky.utils.kubernetes.gpu_labeler   
Found 2 unlabeled GPU nodes in the cluster
Using default RuntimeClass for GPU labeling.
Created GPU labeler job for node ip-192-168-14-191.ec2.internal
Created GPU labeler job for node ip-192-168-24-7.ec2.internal
GPU labeling started - this may take 10 min or more to complete.
To check the status of GPU labeling jobs, run `kubectl get jobs -n …
```
> [k8s] sky check detects unlabeled nodes

- sky/data/storage.py
- sky/task.py
- sky/utils/controller_utils.py
1. define a `DEFAULT_STORAGE_MODE` constant so places where `StorageMode.MOUNT` is used as the default storage mode becomes more clear.
2. set `requires_fuse` to true when a mount is using cached mode as well. rclone/vfs still relies on fuse. This was left behind on https://github.com/skypilot-org/skypilot/pull/4369
> [chore] storage mode audit

- .buildkite/generate_pipeline.py
More consistent with real pytest behavior
Before:
`/smoke-test --aws -k test_basic` 
triggers no test.
After 
`/smoke-test --aws -k test_basic` 
triggers all tests in file `tests/smoke_tests/test_basic.py`
^ Manual test screenshot
> CI `-k` support file name matcing

- sky/jobs/server/server.py
If you have a lot of jobs and a lot of failover logs, the 1s timeout could be insufficient.
Fixes #5108.
> jobs dashboard: increase the timeout

- sky/check.py
- sky/clouds/kubernetes.py
- sky/provision/kubernetes/utils.py
1. `sky/clouds/kubernetes.py: _check_compute_credentials` is the only place that cares about `kubernetes_utils.check_credentials`'s message if the check has passed. Add a `run_optional_checks` argument for `kubernetes_utils.check_credentials` so the function short-circuits in the case where additional checks are not required.
2. `kubernetes_utils.check_credentials` seems like a better place to check for unlabeled accelerators given this is where other non-critical k8s checks are being done. Moved the unlabeled accelerator detection logic there.
3. Both `get_unlabeled_accelerator_nodes` and `get_accelerator_label_key_value` produces a warning when there are unlabeled accelerator nodes. Suppress warning from `get_accelerator_label_key_value` when `get_unlabeled_accelerator_nodes` flags …
> [k8s] sky check refactor

- sky/cli.py
Fixes #4090 
Simple fix to skip clusters that have `ClusterStatus.STOPPED`
> [UX] Skip `STOPPED` cluster when calling `sky stop`

- requirements-dev.txt
The latest version of `runpod` (`1.7.7`) requires the `aiohttp[speedups]` module with a minimum version of `3.9.3`, as shown below:
Upgrade `aiohttp` to version `3.9.3` in `requirements-dev.txt`.
> Make `aiohttp` compatible with the latest `runpod`

- sky/backends/cloud_vm_ray_backend.py
This problem was identified in `test_env_check` smoke test.
https://buildkite.com/skypilot-1/smoke-tests/builds/557#019601d3-c17d-434c-a898-fefe53e2c783
```
2025-04-04 10:25:56 PDT | (setup pid=2033) hello world
-- | --
  | 2025-04-04 10:25:56 PDT | Traceback (most recent call last):
  | 2025-04-04 10:25:56 PDT | File "/home/ubuntu/.sky/sky_app/sky_job_2", line 447, in <module>
  | 2025-04-04 10:25:56 PDT | script += rclone_flush_script
  | 2025-04-04 10:25:56 PDT | TypeError: unsupported operand type(s) for +=: 'NoneType' and 'str'
  | 2025-04-04 10:30:22 PDT | ✓ Job finished (status: FAILED_DRIVER).
```
> [storage] Fix failing job when script is None

- charts/skypilot/templates/api-deployment.yaml
Hey guys,
Further to https://github.com/skypilot-org/skypilot/pull/5018, I discovered (when I tried to add AWS credentials), that the AWS / GCP initContainers should also get default securityContexts, so this PR simply adds these :)
Cheers!
D
> [helm chart] Also add securityContexts to initContainers

- sky/data/data_utils.py
- sky/server/requests/executor.py
Fixes https://github.com/skypilot-org/skypilot/issues/5067
**Symptom**
When `sky api cancel` is called on a launch, any local directory upload to remote (when `source` is specified in `file_mounts`) is not cancelled with the request.
**Context**
When a request is executed, it is executed with a signal handler that translates `SIGTERM` to `KeyboardInterrupt`.
```
def _sigterm_handler(signum: int, frame: Optional['types.FrameType']) -> None:
raise KeyboardInterrupt
def _request_execution_wrapper(request_id: str,
ignore_return_value: bool) -> None:
"""Wrapper for a request execution.
It wraps the execution of a request to:
1. Deserialize the request from the request database and serialize the
return value/exception in the request database;
2. Update the request status based on the execution …
```
> [storage] Abort all subprocesses for a request when cancelled

- sky/clouds/lambda_cloud.py
- sky/provision/lambda_cloud/instance.py
- sky/provision/lambda_cloud/lambda_utils.py
- tests/smoke_tests/test_basic.py
- tests/unit_tests/test_lambda.py
> [Lambda] Add open port support

- docs/source/compute/show-gpus-h100-8.txt
- docs/source/examples/models/index.rst
- docs/source/examples/models/llama-4.md
- llm/llama-4/README.md
- llm/llama-4/llama4.yaml
~~Waiting for #5124 as that enables lambda cloud for available high-end GPU~~
Let's merge this first
~~Waiting for vllm to merge this PR: https://github.com/vllm-project/vllm/pull/16104~~
> [LLM] Add llama 4 example

- charts/skypilot/templates/NOTES.txt
- charts/skypilot/templates/_helpers.tpl
- charts/skypilot/values.yaml
- docs/source/reference/api-server/api-server-admin-deploy.rst
- docs/source/reference/api-server/api-server-troubleshooting.rst
- docs/source/reference/api-server/api-server.rst
close https://github.com/skypilot-org/skypilot/issues/5093
```bash
helm upgrade --install skypilot-test ./charts/skypilot -f values.yaml --set ingress.nodePortEnabled=true
Release "skypilot-test" does not exist. Installing it now.
Error: execution error at (skypilot/templates/NOTES.txt:2:4): Error
API server requires at least 4 CPU cores and 8 GiB memory. You can either:
1. increase .apiService.resources.requests.* to meet the requirements or unset them to use defaults
2. add `--set apiService.skipResourceCheck=true` in command args to bypass this check (not recommended for production)
```
```
helm upgrade --install skypilot-test ./charts/skypilot -f values.yaml --set ingress.nodePortEnabled=true --set apiService.skipResourceCheck=true
Release …
```
> [API server] Set default min resources and warning on low resources

- .buildkite/generate_pipeline.py
- tests/conftest.py
- tests/smoke_tests/docker/docker_utils.py
Resolve #5126
Currently, multiple containers in the same VM are binding to the same port, causing only the first container to succeed while the others fail.
* Hash a port instead of using constant value.
* Add a new queue to lower the concurrency of `remote-test` jobs
> `--remote-server` option in buildkite support parallel execution

- docs/source/reference/storage.rst
- sky/backends/cloud_vm_ray_backend.py
If the `run` section is empty (e.g. only setup section of the task is specified), don't create a run section just to trigger an rclone flush.
Additionally, modify the documentation to clarify the task waits for any data written in `run` section specifically.
> [storage] Don't wait for rclone flush if run section is empty

- sky/utils/common_utils.py
- sky/utils/validator.py
this pr fix a potential race conditon caused by importing `jsonschema`. This could be resolved by adding sleep to some lines in between, which leads to a hypothesis in race condition when doing lazy import in `jsonschema` and its dependencies. Directly importing the library resolves this issue. 
to reproduce the earlier error 
```
aws:
```
commands
```
(sky) kych@kych-dev:~/skypilot$ sky status 
Clusters
ImportError: cannot import name 'NothingType' from 'attr' (/home/kych/miniconda3/envs/sky/lib/python3.10/site-packages/attr/__init__.py)
(sky) kych@kych-dev:~/skypilot$ sky status 
Clusters
NAME           LAUNCHED     RESOURCES                                   STATUS  AUTOSTOP   COMMAND                       
sky-3b3b-kych  14 mins ago  1x …
```
> [fix] potential race condition for aws internal_ip configuration 

- tests/smoke_tests/test_sky_serve.py
Resolve   #5123 
From the log, it seems the test case is checking for `SHUTTING_DOWN` right after the sky server update, but the sky server hasn't updated the original replica to `SHUTTING_DOWN` yet. 
After the test fails, the sky status shows the correct status with the replica in `SHUTTING_DOWN`. So we need to wait longer - adding a 60-second delay before failing should fix this flaky test.
> Fix flaky for test skyserve rolling update

- docs/source/cloud-setup/cloud-permissions/vsphere.rst
- docs/source/reference/config.rst
- docs/source/reservations/reservations.rst
- docs/source/running-jobs/distributed-jobs.rst
- docs/source/running-jobs/environment-variables.rst
- docs/source/serving/sky-serve.rst
"Advanced Configurations" in the docs has bothered me for a while because "configuration" is almost never plural. I believe these changes feel much more natural.
> [docs] avoid "configurations"

- docs/source/running-jobs/many-jobs.rst
> [Docs] Remove deprecated retry_until_up in docs

- sky/setup_files/dependencies.py
> pin wheel <0.46.0

- sky/jobs/server/server.py
Fix https://github.com/skypilot-org/skypilot/issues/5111
Retry dashboard forwarding when ping returns non-200 status code
- Launch `sky jobs dashboard`
- Restart the API server
- Launch `sky jobs dashboard` again and it succeeds
> [UX] Retry dashboard forwarding when ping returns non-200 status code

- Dockerfile
- sky/__init__.py
- sky/setup_files/dependencies.py
Patch release to mitigate https://github.com/skypilot-org/skypilot/issues/5153.
v0.8.1 = 0.8.0 + https://github.com/skypilot-org/skypilot/pull/5155.
Skipping tests since wheel < 0.46 is known to be good.
> [Release] Release v0.8.1

- charts/skypilot/values.yaml
> [API server] Fix default kubernetes permissions

- sky/clouds/gcp.py
- sky/clouds/service_catalog/gcp_catalog.py
- tests/test_optimizer_dryruns.py
https://github.com/skypilot-org/skypilot/issues/4098
Recent GCP GPU instances come with accelerators built into the machine type itself, which means users no longer need to explicitly specify the GPU type. For example, launching the following should just work:
```bash
sky launch -t a3-highgpu-8g
```
However, this isn't supported. 
Automatically infer the GPU type from the specified `instance_type`. The result is shown as follows:
> [GCP] Automatically infer the GPU type from the instance type

- charts/skypilot/templates/api-deployment.yaml
- charts/skypilot/values.yaml
close https://github.com/skypilot-org/skypilot/issues/5157
1. Mount entire configmap instead of subPath so that the change will be reflected to the container by kubelet (about ~10s delay)
2. Use symbolic link instead of cp to reflect the changes to API server
> [API server] Propagate configmap update to API server

- .github/workflows/pypi-nightly-build.yml
Problem, the build number is not conencted correctly in our [nighty-build](https://github.com/skypilot-org/skypilot/actions/runs/14355169009/job/40242872696)
[Test on my personal repo](https://github.com/zpoint/skypilot/actions/runs/14369488125/job/40289746203):
> Fix connect issue for pypi-nightly-build.yml

- sky/skypilot_config.py
- tests/test_config.py
Simplify the logic of temporarily overriding config - notably, without relying on the use of tmpfile / env var.
Note: The existing code **does** account for the case where child processes are spun up, as assign to `os.environ` does propagate to children processes. I am running a full smoke test suite to catch any case where this would cause any problems - I did some looking and I do not think this would cause any issues.
> [API Server] simpler override function that doesn't rely on tmpfile

- tests/smoke_tests/smoke_tests_utils.py
- tests/smoke_tests/test_basic.py
- tests/smoke_tests/test_images.py
- tests/smoke_tests/test_managed_job.py
- tests/smoke_tests/test_region_and_zone.py
- tests/unit_tests/test_admin_policy.py
- tests/unit_tests/test_backend_utils.py
- tests/unit_tests/test_resources.py
As part of a larger effort to revamp config management, I have a potential need to modify the behavior of `skypilot_config.ENV_VAR_SKYPILOT_CONFIG` environment variable. This requires keeping track of where this variable is used today and how they are used.
This PR changes every instance of `SKYPILOT_CONFIG` environment variable in hardcoded string format to `skypilot_config.ENV_VAR_SKYPILOT_CONFIG`, such that every usage of the environment variable is command+click able.
> chore: use the python constant instead of hardcoded string for SKYPILOT_CONFIG envvar

- tests/unit_tests/test_sky/server/requests/queues/test_mp_queue.py
part of https://github.com/skypilot-org/skypilot/issues/5171
We now don't have a limit on the queue length, with this test I think we can be confident that this is okay in most cases and we can keep it as is.
> Unit test for mp queue memory usage

- sky/client/common.py
- sky/client/sdk.py
- sky/jobs/client/sdk.py
- sky/serve/client/sdk.py
- sky/server/common.py
- sky/server/constants.py
- tests/unit_tests/test_sky/server/test_sdk.py
Adding an env var `SKYPILOT_API_COOKIE_FILE` that allows for pointing to a [curl cookie file](https://curl.se/docs/http-cookies.html) and passing those cookies to all the requests call that talk to the api server.
Tested connecting to an api server that needs a cookie for the proxy auth in front of it.
Added unit tests for parsing cookie files and checking server health.
Connecting to cookie-necessary server:
```
$ sky api info  
Using SkyPilot API server: https://skypilot-api.my.tld
├── Status: healthy, commit: 5025c819176d48aa8643fe9ec058158ce2bece9a, version: 1.0.0.dev20250406
└── User: clayros (c5fd9f9e)
$ curl -I -sSL https://skypilot-api.my.tld
HTTP/2 302 
server: awselb/2.0
date: Thu, 10 Apr 2025 22:32:43 GMT
content-type: text/html
content-length: …
```
> Adding cookie support for api server

- sky/optimizer.py
Import numpy directly to workaround the lazy import issue
> [Core] Import numpy directly to workaround the lazy import issue

- sky/cli.py
- sky/setup_files/dependencies.py
- sky/templates/websocket_proxy.py
- tests/test_cli.py
Adding support for using `wss` instead of `ws` for websocket proxying. I pass the full URL instead of just the fqdn to the proxycommand, then in the proxy command use the appropriate protocol based on http vs https. 
I also added some tests for the function where that ssh config is updated, and did some rearranging to [de-nest](https://en.wikibooks.org/wiki/Computer_Programming/Coding_Style/Minimize_nesting) some code.
Added a test to check the functionality I added.
They're all in `tests/test_cli.py:TestHelperFunctions.test_get_cluster_records_and_set_ssh_config`. If needed I could break them into separate tests
without fix:
```
$ ssh test-from-api
File "/Users/clayros/.local/pipx/venvs/skypilot-nightly-testing/lib/python3 …
```
> Adding support for wss protocol for websockets

- sky/utils/kubernetes/rsync_helper.sh
> chore: fix rsync helper

- sky/clouds/kubernetes.py
- sky/provision/kubernetes/utils.py
Fixes #4796 
Check whether `socat` and `netcat` are properly downloaded when trying to use Kubernetes as a cloud.
Also handles the case when relevant dependencies are installed and pass `sky check`, and then the dependencies are uninstalled. 
> [k8s] Check k8s dependencies on `sky check`

- .buildkite/generate_pipeline.py
See status section
We now group all steps triggered by a single GitHub comment together and display their notification status on the GitHub PR, using a key from the GitHub comment.
For example:
`/smoke-test --aws -k test_minimal` will show one status
`/smoke-test --gcp` will show another status
`/smoke-test --azure` will show a third status
If you run `/smoke-test --aws -k test_minimal` again, it will overwrite the first status (each key can only have one status).
The GitHub status issue is that if we trigger N tests from buildkite and then commit a new one, the previous statuses disappear due to GitHub's display logic.
> Better buildkite notify status on PR

- .github/workflows/extract-buildkite.yml
- .github/workflows/pypi-nightly-build.yml
- .github/workflows/release-build.yml
Previous failure [here](https://github.com/skypilot-org/skypilot/actions/runs/14458287722/job/40545985713)
If the API endpoint response contains bash scripts, `echo` might interpret them. Use `printf` to avoid interpretation, and make this logic reusable across different pipelines.  
Manual test in my [personal repo](https://github.com/zpoint/skypilot/actions/runs/14460359978/job/40551733724)
> Fix extract build number bug in release pipeline

- sky/cli.py
- sky/resources.py
- sky/setup_files/dependencies.py
- sky/skypilot_config.py
Support overriding configuration per-request using CLI argument.
CLI now accepts a `--config` flag. This flag could either point to a file (relative to $pwd) or a comma separated dotlist (e.g. `--kubernetes.provision_timeout=900,gcp.remote_identity=SERVICE_ACCOUNT`.
Only one instance of `--config` flag is allowed. Among other things, this means a user is not allowed to specify a config file and a dotlist. This saves us the hassle of having to define what takes priority if a config file and a dotlist (or multiple config files, or multiple dotlists, or multiple of both) are specified, making the hierarchy more intuitive.
The specified config modifies the global `_dict`. This is considered fine as the each CLI command is a fresh invocation of the program.
The modified `_dict` is passed to …
> [UX] CLI config overrides

- sky/provision/kubernetes/utils.py
Related to #5005 
Gives users a more detailed error message on why `sky check kubernetes` fails when we have multiple PATHS in a `KUBECONFIG` envvar. This is a preliminary fix, and moving forwards we would ideally want to handle multiple kube configs. 
> [k8s] Disallow`KUBECONFIG` Path List

- charts/skypilot/templates/ingress-nodeport.yaml
- charts/skypilot/values.yaml
- sky/backends/cloud_vm_ray_backend.py
- sky/clouds/kubernetes.py
- sky/serve/load_balancing_policies.py
- sky/serve/serve_state.py
- sky/skylet/job_lib.py
Closes #5211.
Key removals (for release notes):
- deprecated env vars starting with `SKY_` are no longer supported. Use `SKYPILOT_` env vars instead.
- old services from 0.7.0 (before #4439) may not work
- `kubernetes` is no longer a valid _region_ name - you must instead use the k8s context name
> remove deprecations for 0.9.0

- sky/provision/kubernetes/instance.py
Fixes https://github.com/skypilot-org/skypilot/issues/5180
The issue asks to fix the unexpected output when tearing down a multinode k8s cluster:
```
sky down sky-fc31-zhwu 
Terminating 1 cluster: sky-fc31-zhwu. Proceed? [Y/n]: 
Terminating 1 clustexr ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% -:--:--terminate_instances: Tried to delete service sky-fc31-zhwu-xxx-2cc9ba-worker, but the service was not found (404).
Terminating 1 cluster ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% -:--:--terminate_instances: Tried to delete service sky-fc31-zhwu-xxx-2cc9ba-worker-ssh, but the service was not found (404).
Terminating cluster sky-fc31-zhwu...done.
Terminating 1 cluster ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
```
This happens because Skypilot is trying to delete services …
> [k8s] don't attempt to delete nonexistent services in multinode cluster teardown

- sky/adaptors/kubernetes.py
- sky/utils/kubernetes/gpu_labeler.py
Fixes https://github.com/skypilot-org/skypilot/issues/5179
The asks from the issue were:
- Add color
- Wait for the label to be attached
- Have a green tick at the end showing the labelling is finished.
Functionality changes:
`python -m sky.utils.kubernetes.gpu_labeler` now waits for the labeling job to complete. One side effect of waiting for the labler jobs to complete is the fact that this command can clean up the resources used for labeling once the labeling is finished.
UX changes:
Added various styling to the command output - check out the GIF.
Note to reviewers:
I kept the original behavior (of not waiting for the job to complete) under `wait_for_completion` switch - should we:
- Get rid of this behavior outright
- Expose this behavior with `--async` flag or something similar …
> [UX] gpu labeling script waits for job to complete

- tests/smoke_tests/test_managed_job.py
Trying to resolve this [buildkite error](https://buildkite.com/skypilot-1/smoke-tests/builds/688#019636c3-4527-46ce-a854-2d443d2b269e)
Double the timeout of `--kubernetes`
> test_managed_jobs_storage on kubernetes longer timeout for kubernetes

- sky/resources.py
- tests/test_yaml_parser.py
closes: https://github.com/skypilot-org/skypilot/issues/5194
Introduce yaml config aliasing for top-level fields: "gpus" can stand in for "accelerators." Nested configurations are not supported. 
Unlike the cli behavior, "gpus" does not override "accelerators." Either the canonical or the alias can be used otherwise and `InvalidSkyPilotConfigError` is raised.
A nice follow-up here would be to use pydantic as it offers schema validation and [aliasing](https://docs.pydantic.dev/latest/concepts/alias/)
Added unittests to `test_yaml_parser.py`
- verify that `gpus` is parsed and added to the compiled `resources.accelerators`
- verify that `gpus` overrides `accelerators` when specified
> [UX] Allow resources.gpus in SkyPilot YAML to alias resources.accelerators

- sky/server/common.py
- sky/sky_logging.py
- sky/skypilot_config.py
- tests/unit_tests/test_sky/server/test_common.py
close https://github.com/skypilot-org/skypilot/issues/5231
The issue of adding allowed_clouds does not take effect without `sky check` is tracked separately here: https://github.com/skypilot-org/skypilot/issues/4487
> [API server] reload config for new request

- sky/client/sdk.py
- sky/skypilot_config.py
Before hierarchical config was introduced, api login could simply grab the parsed `_dict` on the client side and reasonably expect it to contain the global configration.
How, with hierarchical config, the `_dict` is not just sourced from global config - this config can be tainted by project config, CLI config overrides, etc. This PR ensures `sky api login` mutates the global config only.
> [config] api login mutates global config only

- sky/cli.py
- sky/client/sdk.py
- sky/exceptions.py
- sky/models.py
- sky/provision/kubernetes/utils.py
- sky/server/constants.py
- sky/server/requests/serializers/decoders.py
- sky/server/requests/serializers/encoders.py
- sky/server/server.py
close https://github.com/skypilot-org/skypilot/issues/5245
**NOTE**: this is a break change so the API version is bumped. Requires an upgrade for both client-server. I've actually implemented a compatible version in https://github.com/skypilot-org/skypilot/pull/5255/commits/3e03113bf7522e1cb8a5a3032dfab8f5fc500315. But considering the maintenance burden, I think it is a good time to do some break changes before we release 0.9.0 so I remove the code about compatibility. How do you like? @cg505 @romilbhardwaj @Michaelvll 
Behavior with mocked labels:
```
sky show-gpus
Kubernetes GPUs
GPU   REQUESTABLE_QTY_PER_NODE  TOTAL_GPUS  TOTAL_FREE_GPUS
H100  1, 2, 4, 8                8           8
L4    1, 2, 4, 8                8           8
Kubernetes per node accelerator availability (Note: …
```
> Fix querying kubernetes nodes at client-side

- sky/templates/kubernetes-ray.yml.j2
close https://github.com/skypilot-org/skypilot/issues/5232
Thanks @zpoint for the investigation!
> Fix dependency installation in k8s pod

- examples/admin_policy/example_policy/example_policy/skypilot_policy.py
I find this policy useful for starting to learn about admin policies because I have a blank slate to start modifying behaviors, e.g. add a print statement to try figure out where this function is called, etc. I think we should include it as an example for all to use.
> [admin policy] add DoNothingPolicy to example policy

- sky/serve/autoscalers.py
This PR fixes a bug where sometimes the `num_ondemand_to_provision` can be negative. in such case the `num_ondemand_to_scale_down` will exceed `num_nonterminal_ondemand` and thus generate an assertion error.
```bash
I 04-03 09:11:38 autoscalers.py:657] Number of spot instances to scale down: 1 [5]
E 04-03 09:11:38 controller.py:94] Error in autoscaler: AssertionError: ('Not enough replicas to scale down. Available replicas: ', '[ReplicaInfo(replica_id=6, cluster_name=sky-service-dfea-6, version=1, replica_port=8080, is_spot=False, status=ReplicaStatus.READY, launched_at=1743670813)], num_replica_to_scale_down: 2.')
E 04-03 09:11:38 controller.py:97]   File "/home/ubuntu/skypilot-runtime/lib/python3.10/site-packages/sky/serve/controller.py", line 78, in _run_autoscaler
E 04-03 09:11:38 …
```
> [Serve] BugFix: Negative num od to provision

- sky/resources.py
Followup to https://github.com/skypilot-org/skypilot/pull/5207
Fixes https://github.com/skypilot-org/skypilot/issues/5194
Closes https://github.com/skypilot-org/skypilot/issues/5236
Allows `gpus` -> `accelerators` alias to also apply on `any_of` fields.
> [UX] GPU alias applies to any_of

- sky/data/data_transfer.py
- sky/provision/provisioner.py
- sky/server/requests/payloads.py
- sky/sky_logging.py
- tests/test_config.py
Mini proposal: 
There are times when we want to print a piece of info to a debug log, but that info isn't readily available. In such cases, we need to perform some operations to get this piece of information that is only used to print the debug log.
We don't want to incur the penalty of retrieving / constructing this piece of information if the debug log isn't even going to be printed. This PR introduces a way (and a few examples) to avoid expensive logging in cases where it is not required.
The advantage of introducing this mechanism now is we can be more aggressive on debug logging in the future, without having to worry much about potential penalty it incurs in the case where loglevel is on INFO.
To be clear, I'm not advocating we do this for every debug log - just for ones where this …
> [logging] A way to avoid doing expensive operations for logs

- .github/workflows/release-build.yml
* Release version must be greater than pypi exist version
Test on my personal repo
[Failure](https://github.com/zpoint/skypilot/actions/runs/14508096073/job/40701128162): 
[Success](https://github.com/zpoint/skypilot/actions/runs/14508137401):
> Add version check for release pipeline

- sky/data/storage.py
https://community.cloudflare.com/t/an-error-occurred-internalerror-when-calling-the-putobject-operation/764905/13
> Hi folks. R2 added CRC32 support. The AWS CLI changed recently and defaulted their client to send CRC64-NVME which we do not support. Most if not all official SDKs default to CRC32. The workaround when using the cli tool is to add --checksum-algorithm CRC32.
> 
> Apologies for any inconvenience, we will be sure to improve the response messages you get back when using the CLI to make this more apparent.
> 
> Support for CRC32C and CRC64NVME will be added shortly.
Such is life.
> [R2] make R2 use CRC32 as checksum

- sky/server/requests/executor.py
- sky/skypilot_config.py
- sky/utils/config_utils.py
Reformat debug logs to be more human readable. This change allows a user to see what files are being used for each config layer, what each config layer is providing and the final configuration for both client and the server.
```
sky launch --dryrun
D 04-17 14:11:53 skypilot_config.py:143] using default user config file: ~/.sky/config.yaml
D 04-17 14:11:53 skypilot_config.py:316] Config loaded from /Users/seungjinyang/.sky/config.yaml:
D 04-17 14:11:53 skypilot_config.py:316] api_server:
D 04-17 14:11:53 skypilot_config.py:316]   endpoint: http://127.0.0.1:46580
D 04-17 14:11:53 skypilot_config.py:316] 
D 04-17 14:11:53 skypilot_config.py:316] aws:
D 04-17 14:11:53 skypilot_config.py:316]   security_group_name: seungjins-security-group
D 04-17 14:11:53 skypilot_config.py:316] 
D 04-17 …
```
> [UX] better config related debug logs

- sky/optimizer.py
Before:
```
D 04-17 16:17:54 optimizer.py:339] resources: Kubernetes(2CPU--2GB)
D 04-17 16:17:54 optimizer.py:358]   estimated_runtime: 3600 s (1.0 hr)
D 04-17 16:17:54 optimizer.py:362]   estimated_cost (not incl. egress): $0.0
D 04-17 16:17:54 optimizer.py:339] resources: AWS(m6i.2xlarge)
D 04-17 16:17:54 optimizer.py:358]   estimated_runtime: 3600 s (1.0 hr)
D 04-17 16:17:54 optimizer.py:362]   estimated_cost (not incl. egress): $0.4
D 04-17 16:17:54 optimizer.py:339] resources: AWS(m6i.2xlarge)
D 04-17 16:17:54 optimizer.py:358]   estimated_runtime: 3600 s (1.0 hr)
D 04-17 16:17:54 optimizer.py:362]   estimated_cost (not incl. egress): $0.4
D 04-17 16:17:54 optimizer.py:339] resources: AWS(m6i.2xlarge)
D 04-17 16:17:54 optimizer.py:358]   estimated_runtime: 3600 s (1.0 hr)
D 04-17 …
```
> [logging] more concise logging for resource optimization

- sky/dashboard/package-lock.json
When I ran `npm install` to install dashboard packages I got this message:
```
$ npm install
npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated domexception@4.0.0: Use your platform's native DOMException instead
npm warn deprecated abab@2.0.6: Use your platform's native atob() and btoa() methods instead
npm warn deprecated eslint@8.57.1: This version is no longer supported. Please see https://eslint.org/version-support for other options.
npm warn deprecated @humanwhocodes/config-array@0.13.0: Use …
```
> [dashboard] npm audit fix

- tests/unit_tests/kubernetes/test_kubernetes_utils.py
follow up 
- https://github.com/skypilot-org/skypilot/pull/5255
- https://github.com/skypilot-org/skypilot/pull/5257
> [Test] Unit test for get_kubernetes_node_info

- .github/workflows/release-build.yml
- .github/workflows/release-publish.yml
Since the [releases/xxx](https://github.com/skypilot-org/skypilot/actions/runs/14564878962/job/40860218455) branch is protected, we can't use GitHub Actions to create it. The workflow is now:
1. Human creates the releases/a.b.c branch (must override if it already exists when making PR)
2. Human triggers the release pipeline
3. human reviews the PR created by pipeline
4. Human decides whether to abort or proceed
We had to remove the automatic trigger because some human actions are required before the pipeline runs.
> Refactor release pipeline

- llm/deepseek-r1/README.md
- llm/deepseek-r1/deepseek-r1-671B-A100.yaml
- llm/deepseek-r1/deepseek-r1-671B.yaml
> [Docs] Update deepseek r1 example with correct initial delay seconds config

- sky/adaptors/aws.py
- sky/clouds/aws.py
- sky/server/requests/payloads.py
This fixes the "Using several profiles or accounts" story for local API server without restarting - e.g. switching between different AWS profiles for different clusters.
Some concern that this could lead to unexpected behavior in the remote API server case, where local AWS profiles may not correspond to the profiles on the API server.
> reload AWS_PROFILE on each request

- docs/source/reference/config-sources.rst
- sky/cli.py
- sky/skypilot_config.py
Closes https://github.com/skypilot-org/skypilot/issues/5296
The CLI config flag currently accepts a comma separated list of config overrides. For example:
`--config kubernetes.provision_timeout=600,kubernetes.pod_config.spec.priorityClassName=high-priority`
is a valid CLI flag.
The CLI parsing logic currently simply splits the input string by commas and feed the result into a dotlist parser. While this logic works for example above, the logic fails at parsing config overrides such as:
`--config kubernetes.allowed_contexts=[context1,context2]`
or
`--config gcp.labels.mylabel="one,two,three"`
because CLI splits the input by the commas within the value designation.
I've originally attempted to solve it by having the parsing logic account for curly braces, square braces and quotes - but the …
> improve CLI config flag's parsing

- tests/smoke_tests/smoke_tests_utils.py
- tests/smoke_tests/test_cluster_job.py
- tests/smoke_tests/test_region_and_zone.py
Resolve #5270
Reason:
The issue is with the `test_aws_with_ssh_proxy_command` test itself. It [overrides](https://github.com/skypilot-org/skypilot/blob/master/tests/smoke_tests/test_region_and_zone.py#L67) the server endpoint in the middle of the test, even though we configured `--remote-server` to a different endpoint before running the test.
For `test_multi_echo`, I'm not sure if it's a bug.
The issue is: if the client and server are different, and we launch the sky cluster via the SDK (not CLI), we call [add_cluster](https://github.com/skypilot-org/skypilot/blob/master/sky/utils/cluster_utils.py#L111) on the server side during provisioning.
However, the SSH record isn’t added then, causing the test to fail.
> Fix smoke test failures when using `--remote-server`

- sky/backends/wheel_utils.py
- sky/server/common.py
- sky/server/constants.py
- sky/server/server.py
- sky/setup_files/setup.py
We compare two versions:
1. The version of the code that's currently loaded into the API server process.
2. The version of the code on the disk where the API server was started.
If these two don't match, it probably means the user upgraded SkyPilot without restarting the API server.
This can lead to unintuitive behavior if the user tries to use new features or bugfixes, since the API server running on old code may not have them. It can also cause some crashes, e.g. #5311. This PR fixes #5311.
In general, we mostly expect this to affect the local API server case. Usually when an admin upgrades the remote API server, they will know to restart it, or it will be automatically handled by the helm chart. So we will just print the warning in either case.
> [server] warn the user if the API server is stale

- sky/backends/backend_utils.py
- sky/skylet/constants.py
Fixes https://github.com/skypilot-org/skypilot/issues/4814
This issue is fixed by deactivating any conda environment we activate if conda was not installed in the image and the image we are on is a custom docker image.
Fixes https://github.com/skypilot-org/skypilot/issues/5265
This issue is fixed by not running `conda init && source ~/.bashrc;` (regardless of conda was or was not installed in the base image) if the image is a custom docker image.
Tests
Manual tests:
BW Compatibility: Check that launching a cluster with SkyPilot image on following clouds still give a conda environment with `base` env activated:
---
Issue 5265
---
Issue 4814
> [Core] Do not initialize conda for users if using docker image

- sky/provision/aws/instance.py
Closes https://github.com/skypilot-org/skypilot/issues/3688
This was a doozy one.
In the function modified in the PR, a list of instances comprising the cluster is terminated. If a security group needs to be deleted as part of the teardown process, this function also waits until the instances are actually done terminating.
The bug here is a probabilistic race condition. It's good to note that `instances` here doesn't stay constant (like a list) - instead, it seems every use of it returns a new list (like a generator) that could be different from the previous time the variable is used.
`instances` is generated by calling `_filter_instances` which filters for the VM state being in `pending`, `running`, `stopping` or `stopped`. Notably, this filter does not include `terminating` as a state …
> [AWS] Use consistent list for instance termination logic

- .github/workflows/pytest.yml
- pytest.ini
- requirements-dev.txt
- sky/dag.py
- sky/execution.py
- sky/server/server.py
- sky/task.py
- tests/load_tests/test_load_on_server.py
- tests/test_failover.py
- tests/unit_tests/test_sky/server/test_server.py
Make `validate` non-blocking, close https://github.com/skypilot-org/skypilot/issues/5300
Benchmark result:
- this branch:
```bash
$ python tests/load_tests/test_load_on_server.py -n 100 --apis validate
Latency Statistics:
----------------------------------------------------------------------------------------------------
Kind                 Count    Total(s)   Avg(s)     Min(s)     Max(s)     P95(s)     P99(s)
----------------------------------------------------------------------------------------------------
API /validate        100      43.96      0.44       0.24       0.58       0.58       0.58
```
- master:
```bash
$ python tests/load_tests/test_load_on_server.py -n 100 --apis validate
Latency Statistics:
-------------------------------------------------------------------------------- …
```
> Fix: validate dag should not block uvicorn

- Dockerfile
- docs/source/getting-started/installation.rst
This helps mitigate #5355 from the docs side.
Also fixes the Dockerfile.
> update installation docs and Dockerfile to reflect omegaconf

- requirements-dev.txt
- sky/adaptors/aws.py
- sky/adaptors/common.py
- sky/clouds/aws.py
- sky/clouds/service_catalog/data_fetchers/fetch_aws.py
- sky/data/storage.py
- sky/provision/aws/config.py
- sky/provision/aws/instance.py
Needed this while checking #5316, and it seems to work relatively well for autocompletions at least in Pycharm.
> add typechecking for boto clients/resources

- sky/clouds/gcp.py
Addresses https://github.com/skypilot-org/skypilot/issues/4952
When gcloud is installed with wget, gcloud modifies the user rc file which the user must source again. The added snippet in the rcfile essentially modifies the PATH variable to add the path to gcloud executable,
This is different from other methods of installation, such as brew, where the gcloud executable is installed within the existing PATH (e.g. path to brew executables)
If skypilot API server is started before gcloud is installed via wget, the API server's PATH does not have the correct path to gcloud executable even if the user sources the rcfile again. This is because in python, os.environ is loaded once at the beginning of the program and is not affected by the underlying environment once the program starts running. …
> [GCP] add helptext about API srv missing `gcloud` when installed using wget

- tests/smoke_tests/smoke_tests_utils.py
- tests/smoke_tests/test_backward_compat.py
> support `all_users` in wait for job status in back compact tests

- sky/clouds/gcp.py
The extra comma there was causing this variable to be interpreted as a struct not a string :<
> fixes from #5335

- sky/adaptors/kubernetes.py
> [k8s] Hints for querying stale kube current context

- sky/clouds/gcp.py
https://github.com/skypilot-org/skypilot/issues/4705
According to the [GCP doc](https://cloud.google.com/compute/docs/disks#hd-vs-pd), Hyperdisk offers better performance and flexibility compared to Persistent Disks. It allows tuning performance independently of size and provides higher IOPS and throughput.
GCP recommends using Hyperdisk when it’s supported by the machine. Notably, `hyperdisk-balanced` is the only Hyperdisk type that supports boot disks.
This PR proposes integrating `hyperdisk-balanced` as one of the disk types for GCP A3 series instances.
* Map `ULTRA` disk tier to `hyperdisk-balanced` type
* Propagate `MEDIUM` disk tier (which maps to `pd-balanced`) to `LOW` as A3 series doesn't support `pd-standard`
* `sky launch -t a3-highgpu-8g --disk-tier ultra --dryrun`
* `sky …
> [GCP] Support hyperdisk-balanced for a3 series

- sky/exceptions.py
- sky/jobs/server/core.py
- sky/task.py
Fixes #4268 
~~Noticed that `task.py` is the only place that actually validates resources AND we can know for sure that the task in question is indeed a jobs controller.~~
Got feedback and changed to updating and checking cluster status on jobs.launch
> [k8s] Better error message for stale jobs controller

- docs/source/reference/config-sources.rst
Note: the functionality associated with SKYPILOT_GLOBAL_CONFIG is still there in code, this PR simply removes the mentions of it in the doc.
The idea here is that using SKYPILOT_GLOBAL_CONFIG to change the global config directory away from `~/.sky/config.yaml` should be a rare thing for a user to do, so we remove it from docs.
> [UX] remove references to SKYPILOT_GLOBAL_CONFIG envvar in docs

- sky/provision/aws/instance.py
https://github.com/skypilot-org/skypilot/commit/f0f4de8d310032e467627c999918281a100bbbb3#diff-83ddf91a29dd4a792b795f4f2a403ae13f22692e2854bf8e342c88d19be78ef0R726-R740
This commit has the right idea, but the introduction of another for loop ends up complicating the `break` logic a tad bit. This PR fixes the logic.
Closes https://github.com/skypilot-org/skypilot/issues/5331
The current codepath opens a chance for a probabilistic bug in cases where some ports need to be opened for a cluster and those rules already exist for the chosen security group. If the SkyPilot added rule with `IpProtocol` of `-1` is returned in the list before the other rules, the current codepath breaks and never becomes aware of the other rules that are opening the ports requires. SkyPilot attempts to open these …
> [aws] fix logic to detect rule with all traffic from security group

- sky/cli.py
- sky/client/sdk.py
- sky/server/common.py
- tests/unit_tests/test_sky/server/test_common.py
Remove credentials from the dashboard URL and update the dashboard build hint
- Local API Server (Verify the output of the following commands)
- sky api info
- sky dashboard
- sky api start
- sky api login
- Remote API Server 
- sky api info
- sky dashboard
- sky api login
> [UX] Remove credentials from the dashboard URL and update the dashboard build hint

- pyproject.toml
- tests/conftest.py
We see these test warning recently:
```bash
D 04-24 09:58:10 skypilot_config.py:384]
  | /home/buildkite/miniconda3/lib/python3.10/site-packages/pytest_asyncio/plugin.py:217: PytestDeprecationWarning: The configuration option "asyncio_default_fixture_loop_scope" is unset.
  | The event loop scope for asynchronous fixtures will default to the fixture caching scope. Future versions of pytest-asyncio will default the loop scope for asynchronous fixtures to function scope. Set the default fixture loop scope explicitly in order to avoid unexpected behavior in the future. Valid fixture loop scopes are: "function", "class", "module", "package", "session"
  |  
  | warnings.warn(PytestDeprecationWarning(_DEFAULT_FIXTURE_LOOP_SCOPE_UNSET))
  | bringing up …
```
> supress warning by setting default value of `asyncio_default_fixture_loop_scope`

- sky/provision/kubernetes/instance.py
Closes https://github.com/skypilot-org/skypilot/issues/3755.
> [k8s] Force terminate misbehaving pods

- docs/source/reference/api-server/api-server-admin-deploy.rst
Refine API server deployment guide:
- Most notablely, move configuring cloud credentials to an optional (advanced) step because we've seen some of our users got misled in this complex chapter. The new structure guide users to deploy a usable API server as quickly as possible and then incrementally add various cloud permissions;
- Unify some terms and flags used;
- More details about multi-kubernetes setup;
- Use dropdown to elaborate referencing existing secrets (which is an advanced use case) to save some vertical space;
I think this can help avoiding some onboarding problems we've seen before, so I'd like to include this in our 0.9.0 doc if possible (maybe not necessarily, at least I'm always referencing the latest doc and rarely open the versioned one), cc @romilbhardwaj 
- close …
> Refine API server deployment doc

- sky/cli.py
- sky/server/common.py
Previous
```
» sky api info
Using SkyPilot API server: http://skypilot:alpha1@api.skypilot.co:30050 Dashboard: http://api.skypilot.co:30050/dashboard
├── Status: healthy, commit: 607eee0a24e50718d783e92081f141f45cac6cda, version: 1.0.0-dev0
└── User: zongheng (8a3968f2)
```
This PR
```
» sky api info
Using SkyPilot API server: http://skypilot:alpha1@api.skypilot.co:30050
├── Status: healthy, commit: 607eee0a24e50718d783e92081f141f45cac6cda, version: 1.0.0-dev0
├── User: zongheng (8a3968f2)
└── Dashboard: http://api.skypilot.co:30050/dashboard
```
Easier to discover + click.
> [UX] `api info`: display dashboard on last line

- sky/client/sdk.py
Missed this in #5417.
Before
```
» sky api login -e http://127.0.0.1:46580
Logged in to SkyPilot API server at http://127.0.0.1:46580. Dashboard: http://127.0.0.1:46580/dashboard
```
This PR
```
» sky api login -e http://127.0.0.1:46580
Logged in to SkyPilot API server at: http://127.0.0.1:46580
└── Dashboard: http://127.0.0.1:46580/dashboard
```
> [UX] Minor fix.

- .github/workflows/release-build.yml
- Dockerfile
- docs/source/getting-started/installation.rst
- sky/setup_files/dependencies.py
- sky/skypilot_config.py
- tests/test_config.py
The only logic that needs to be implemented to remove omegaConf is the dotlist parsing logic. This actually turned out to be pretty simple to implement using `yaml.safe_load()`.
Added some unit test to make sure the logic implemented to replace omegaConf still acts as expected.
> [config] remove omegaconf as dependency

- sky/clouds/kubernetes.py
- sky/provision/kubernetes/utils.py
- sky/templates/kubernetes-ray.yml.j2
I was looking at `GFDLabelFormatter` and found this comment snippet
```
This LabelFormatter can't be used in autoscaling clusters since accelerators
may map to multiple label, so we're not implementing `get_label_values`
...
def get_label_value(cls, accelerator: str) -> str:
"""An accelerator can map to many Nvidia GFD labels
(e.g., A100-80GB-PCIE vs. A100-SXM4-80GB).
As a result, we do not support get_label_value for GFDLabelFormatter."""
```
GFDLabelFormatter is a pretty versatile formatter as it essentially comes for free with NVIDIA GPU operator. So I'd actually like this formatter to support get_label_value. This PR removes the current blocker preventing GFDLabelFormatter's `get_label_value` implementation.
> [k8s] idea: allow an accelerator to map to multiple label values

- sky/adaptors/nebius.py
- sky/clouds/nebius.py
This update introduces a `force_update` flag to `sdk`, `get_iam_token`, and `get_tenant_id` functions, ensuring credentials can be refreshed on demand. It addresses scenarios where cached values are outdated or invalid, improving reliability during authentication. This change ensures up-to-date credentials are used when necessary.
> [Nebius] Don't cache session across multiple requests

- sky/cli.py
- sky/clouds/service_catalog/kubernetes_catalog.py
- sky/core.py
Fixes #5313 
~~**IMPORTANT! Feedback Please**
I didn't know whether it would be desirable, but I think it would be a good idea to show a final table that would merge all available accelerators across all k8s clusters? The user might want to only know the total availability across clusters. I think that might be a helpful summary feature. For instance, for the above image, we would have:~~
```
Kubernetes GPUs (all allowed contexts):
GPU: T4, TOTAL_GPUS: 2, TOTAL_FREE_GPUS: 2
```
**EDIT (25.04.27): implemented above feature as suggested in below comment**
**Some Behavioral Changes:**
- specifying an accelerator and the kubernetes context (aka region) at the same time ignored the kubernetes context. Fixed that to take into account the k8s context.
- in kubernetes_catalog. …
> [UX][k8s] show-gpus for all allowed contexts

- sky/clouds/service_catalog/constants.py
Related to: https://github.com/skypilot-org/skypilot-catalog/pull/116
Can be merged after the PR above
fixes #5418
> [Catalog] use v7 for latest runpod

- sky/utils/aws/get_default_security_group.py
Currently, a user has no good way of figuring out what their default AWS security group is. A user should be able to determine the default security group name used by SkyPilot, but this seems niche enough that I don't really think such functionality deserves a place in the CLI. The compromise is to write a simple script that can be invoked using
`python -m sky.utils.aws.get_default_security_group`
similar to how we run GPU labeler script for k8s today
`python -m sky.utils.kubernetes.gpu_labeler`
The expected first user of this script is our buildkite containers, which can figure out the security group it may have created and delete the security group if one exists.
> [aws] script to get default security group name for aws

- sky/resources.py
Fixes #5439.
This was missed in #5212 due to #5442.
> avoid using removed LEGACY_SINGLETON_REGION constant

- .github/workflows/release-publish.yml
We want github pipeline to trigger on this #5333: `releases/0.9.0` from `test_releases/0.9.0`
We don't want github pipeline to trigger on this #5350, `releases/0.9.0` from `DanielZhangQD:dashboard2`
So we add a rule to filter based on branch name: `test_releases/xxx`
> release pipeline trigger filter based on name

- charts/skypilot/templates/api-deployment.yaml
- charts/skypilot/values.yaml
- docs/source/reference/api-server/api-server-admin-deploy.rst
close https://github.com/skypilot-org/skypilot/issues/5429
Local preview:
> [Doc] Add runpod credentials setup for API server

- .github/workflows/release-publish.yml
This backports #5373 and #5367, which fix issues with the release pipeline github actions.
THERE ARE NO CODE CHANGES.
> release pipeline fixes

- sky/provision/docker_utils.py
- sky/provision/runpod/utils.py
- sky/templates/kubernetes-ray.yml.j2
Fixes https://github.com/skypilot-org/skypilot/issues/5306
The docker container environment (environment variables including $PATH) does not apply when a user ssh'es in - a fresh environment is created for the session.
For our kubernetes implementation, the container environment is exported to all users (including ssh sessions) by creating a file in `/etc/profile.d/`. This was missed in the runpod implementation. This PR adds an equivalent command to the runpod implementation of SkyPilot.
While working on the PR, I found a better way to generate an export file from the current environment, which I've applied to both k8s and runpod implementations.
> [runpod] preserve docker configured environment variables

- sky/provision/kubernetes/instance.py
- sky/templates/kubernetes-ray.yml.j2
Closes https://github.com/skypilot-org/skypilot/issues/4851
There have been reports that launching jobs on k8s clusters with GPUs don't bin pack jobs properly. I was able to reproduce this report by preparing a 2 node cluster, with each node having 4 X L40S GPUs, and creating 8 jobs each requesting 1 X L40S GPU sequentially. The following is the sequence at which these jobs were placed (either on node 1 or node 2)
Run 1: 1 2 1 2 1 1 2 2
Run 2: 1 2 1 1 2 2 1 2
With the changes in this PR, the following is the sequence:
Run 1: 1 1 1 1 2 2 2 2
Runs 2/3: (same as run 1)
The following is the sequence seeded with 1 pod already running on node 2
Run: [2] 2 2 2 1 1 1 1
These tests demonstrate the affinity specified in the PR works to bin-pack the GPUs.
As with …
> [k8s] gpu bin packing via affinity

- docs/source/getting-started/installation.rst
While the master branch of SkyPilot does not depend on omegaconf, the latest stable release does. Therefore, the instructions to deal with omegaconf as a dependency is needed until the next stable release is published.
> [docs] leave in instructions to deal with omegaconf until next stable release

- sky/clouds/kubernetes.py
- sky/provision/kubernetes/utils.py
- sky/templates/kubernetes-ray.yml.j2
Problem statement: In a k8s cluster with multiple node pools, it is possible to have a heterogenous cluster where some nodes are CPU instances and some nodes are GPU instances.
In such cases, we would like to _prefer_ that CPU only tasks get scheduled on CPU nodes, so they don't take up resources from GPU nodes.
Solution: We already have access to GPU label formatters which provide us with the label key(s) a node with accelerators should have. It should therefore be possible to specify an affinity to the nodes without these labels for CPU only jobs.
Reference: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity
1. Create a k8s cluster with 1 CPU only instance (16 vCPUs) and 2 GPU instances
2. Create 8 pods …
> [k8s] CPU only jobs to prefer nodes without GPUs

- tests/smoke_tests/test_basic.py
Resolve #5437
Test broken after #5362 because the display logic changed.
> Fix failure of `test_kubernetes_context_failover`

- tests/smoke_tests/test_basic.py
Resolve #5436 
The issue only occurs in the `UP` state. If we call sky down then, the job won't show as cancelled, and the `grep "cancelled"` command will fail.
When it's in `INIT` state, the test succeeds. This failure is more likely to happen in kubernetes tests because the kubernetes cluster provisions too quickly to reach the `UP` state.
~~I'm not sure if fixing the test case is the right approach, or if we should modify the `sky` job system to also cancel jobs for clusters in the `UP` state when `sky down` called? @aylei~~
> Fix flaky of `test_cancel_launch_and_exec_async`

- sky/clouds/gcp.py
Closes https://github.com/skypilot-org/skypilot/issues/4705.
GCP instances have series-specific disk type supports which are summarized as follows:
| Machine series | pd-standard | pd-balanced | pd-ssd | pd-extreme |
|----------------|-------------|-------------|--------|------------|
| N2             | V           | V           | V      | V   (>= 64 vCPUs)      |
| N1             | V           | V           | V      | —          |
| N1+GPU         | V           | V           | V      | —          |
| A2             | V           | V           | V      | —          |
| G2             | —           | V           | V      | —          |
To make SkyPilot smart at figuring out the best disk type for each specific machine series, we consider remapping disk types for those unsupported, other …
> [GCP] Remap series-specific disk types

- sky/jobs/utils.py
When event_callback is called, we want to pass in the task environment to get the callback access to extra context (like secrets).
There are no unit tests that specifically cover the event_callback.
- [ x] Code formatting: install pre-commit (auto-check on commit) or `bash format.sh`
issue: 5475
> add task envs to event_callback

- sky/clouds/nebius.py
Previously, AWS credential files were always mounted, even when unnecessary. This change ensures they are only mounted if the Nebius profile is referenced in the AWS credentials and config files. This reduces redundancy and improves configuration flexibility.
Fixing: https://github.com/skypilot-org/skypilot/issues/5338
> [Nebius] Conditionally mount AWS credential files for Nebius profile

- requirements-dev.txt
- sky/setup_files/dependencies.py
This pull request removes the `urllib3<2` dependency specification from the `aws_dependencies` group.
Fixes #5467.
(none of the above -- I had some issues setting up a test environment, and the changes here are pretty minimal, so I'm hoping CI coverage is sufficient)
> Remove upper limit on urllib3 version

- sky/backends/backend_utils.py
- sky/utils/controller_utils.py
This attempts to fix an issue I hit that caused two jobs controllers to be created.
> fix controller cluster name breaking

- sky/cli.py
As mentioned in this [pr](https://github.com/skypilot-org/skypilot/pull/5362)
also fixes the color misalignment and removes the `----`
> [UX][k8s] backwards compatibility for k8s show-gpus

- sky/server/requests/payloads.py
> reload AWS_SESSION_TOKEN and KUBECONFIG on local API server

- docs/source/cloud-setup/cloud-permissions/nebius.rst
- docs/source/getting-started/installation.rst
- docs/source/reference/config.rst
- sky/adaptors/nebius.py
- sky/clouds/nebius.py
- sky/provision/nebius/utils.py
- sky/utils/schemas.py
The Nebius project ID file support has been removed in favor of configuration in `~/.sky/config.yaml`, which now includes `project_id` and `fabric` options. Enhancements include streamlined GPU cluster creation and clearer documentation for Nebius configurations.
> [Nebius] Add support config file and remove hardcode

- sky/provision/kubernetes/utils.py
The k8s codepath decides if a node can fit a job/task by looking at the CPU/mem capacity, not CPU/mem allocatable. The assumption here is that even if a node doesn't have the CPU/mem necessary right now, maybe there is another SkyPilot job running that will complete, free up the resources, and let the job schedule.
A good example where this approach fails is when a job requiring 8 CPUs being matched by a node with 8 CPU capacity. This seems theoretically sound at first glance, but in reality a node always has _some_ kube-system (or *-system) pods running that prevents this job from being scheduled. This PR attempts to account for this real life scenario.
> [k8s] do not consider nodes with exact cpu/mem requirements

- charts/skypilot/templates/system-rbac.yaml
**Before**:
```
$ export NAMESPACE=team2  
$ export RELEASE_NAME=skypilot-team2
$ export WEB_USERNAME=skypilot
$ export WEB_PASSWORD=yourpassword
$ export AUTH_STRING=$(htpasswd -nb $WEB_USERNAME $WEB_PASSWORD)
$ helm upgrade --install $RELEASE_NAME ./charts/skypilot --devel \
--namespace $NAMESPACE \
--create-namespace \
--set ingress.authCredentials=$AUTH_STRING
...
$ sky api login --endpoint http://skypilot:yourpassword@<host>
$ sky jobs launch "echo hello"
Command to run: echo hello
Managed job 'sky-cmd' will be launched on (estimated):
Considered resources (1 node):
---------------------------------------------------------------------------------------------
CLOUD        INSTANCE    vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN …
```
> [k8s] fix helm chart deployment of API server

- .github/workflows/release-build.yml
* Scheduled release pipeline, triggers every month on the 1st and 15th  
* Automatically determines the next release version based on Sky API version, while also supporting manual version input  
* GitHub Action now has permission to create `releases/xxx` branches and will create them automatically  
* If the release succeeds in one attempt, everything works smoothly  
* If the release fails and needs to be retried with the same version:  
* Currently requires manual deletion of the `releases/xxx` branch before retrying, otherwise the workflow fails(Implemented in this PR)
* Alternative solution: Grant delete permission for `releases/xxx` branches to avoid manual deletion during retries(Not implemented)
> Release pipeline refactor - automated release

- sky/dashboard/src/data/connectors/clusters.jsx
- sky/dashboard/src/data/connectors/jobs.jsx
- sky/server/common.py
- sky/server/constants.py
- sky/server/server.py
x-request-id is a very common header name that we're already using internally, causing conflicts. This namespaces the header to the actual service
> Use more specific header name

- docs/source/reference/api-server/api-server-admin-deploy.rst
ran into this issue while working on https://github.com/skypilot-org/skypilot/pull/5498, this change makes the command work
> chore: minor fix to api server documentation

- sky/check.py
- sky/clouds/gcp.py
- sky/core.py
- sky/global_user_state.py
- sky/skylet/constants.py
- sky/skypilot_config.py
- sky/utils/schemas.py
- tests/test_global_user_state.py
Sample server-side config:
```
workspaces:
my_workspace:
gcp:
project_id: <project>
disabled: true
aws:
disabled: true
fluidstack:
disabled: true
```
Sample client-side config:
```
...
active_workspace: my_workspace
```
If no workspace is specified, `default` workspace is used.
Enabled clouds are now cached per workspace.
If a non-default workspace is specified and the corresponding workspace does not exist in the server, request errors out.
Each workspace can disable a cloud specified in `allowed_clouds` using `disabled` field.
> [WIP] workspaces implementation

- .github/workflows/docker-build.yaml
- .github/workflows/release-publish.yml
The `docker-build.yaml` pipeline accepts an optional input parameter to use as the version for publishing.
In [release 0.9.2](https://github.com/skypilot-org/skypilot/actions/runs/14744833982/job/41390569148), it publishes to PyPI and then fetches the latest version for the Docker build. However, the latest version is still 0.9.1. This could be because the process is too quick, so passing a parameter might help avoid this issue.
> Add optional version parameter to docker build pipeline to prevent version mismatch

- docs/source/compute/gpus.rst
- docs/source/reference/kubernetes/kubernetes-deployment.rst
- docs/source/reference/kubernetes/kubernetes-getting-started.rst
- docs/source/reference/kubernetes/kubernetes-setup.rst
- docs/source/reference/kubernetes/multi-kubernetes.rst
- docs/source/reservations/existing-machines.rst
- examples/k8s_cloud_deploy/README.md
- sky/cli.py
This is a minor refactoring of #5488 to improve the code readability and add back the 0 GPU nodes.
It also proposes a new UX:
New:
Original:
Original
> [k8s] New UX for`show-gpus`, and add back the 0 GPU nodes

- sky/dashboard/src/components/elements/modals.jsx
Adds a quick copypaste-able snippet for connecting vscode to remote cluster and fixes a minor padding being too large between the video and the h3. 
Desktop:
Mobile:
> [Dashboard] Add vscode connection snippet

- docs/source/cloud-setup/cloud-permissions/nebius.rst
- docs/source/reference/config.rst
- sky/provision/nebius/instance.py
- sky/provision/nebius/utils.py
- sky/templates/nebius-ray.yml.j2
- sky/utils/schemas.py
Introduced `use_internal_ips` and `ssh_proxy_command` fields in Nebius configuration to enable private IP communication for SkyPilot instances. Updated relevant documentation, templates, and schemas to reflect these changes. Ensured proper handling of public IP association in the provisioning process based on the new configuration.
> [Nebius] Add support for internal IP usage in Nebius configurations

- docs/source/cloud-setup/cloud-permissions/gcp.rst
https://docs.skypilot.co/en/iap-docs/cloud-setup/cloud-permissions/gcp.html#using-internal-ips
> [docs] add docs for setting up TCP IAP tunneling

- sky/templates/websocket_proxy.py
Solve part of #5538 
Benchmark:
```bash
$ rsync -Pav /home/ubuntu/test2/ aylei:/home/sky/
3,735,552   0%   48.31kB/s    6:09:08
$ rsync -Pav /home/ubuntu/test2/ aylei:/home/sky/
1,073,741,824 100%   13.11MB/s    0:01:18 (xfr#1, to-chk=0/2)
1,073,741,824 100%   43.51MB/s    0:00:23 (xfr#1, to-chk=0/2)
```
The number is still worse than 0.8.0 but much better than master, so I think we can merge this PR first and keep investigating the regression further in the mean time. @Michaelvll @cg505 PTAL
This PR improves the performance of websocket_proxy at client-side by:
1. avoid creating a new thread for every io operation;
2. increase the read buffer size when piping from stdin to the websocket connection, which is the main-bottlenect;
> Optimize the throughput of websocket proxy

- docs/source/getting-started/installation.rst
- docs/source/reservations/existing-machines.rst
Fix https://github.com/skypilot-org/skypilot/issues/4477
Add link to local kind deployment doc in the `Installation` and `Using Existing Machines` docs.
> [Doc] Add link to local kind deployment doc

- sky/backends/cloud_vm_ray_backend.py
- sky/resources.py
If you `sky launch` with new docker credentials on an existing cluster, the cluster resources will now be updated with the new credentials.
> [docker] update docker login creds when relaunching cluster

- sky/provision/kubernetes/utils.py
- tests/unit_tests/kubernetes/test_instance_type.py
Fix https://github.com/skypilot-org/skypilot/issues/5574
Add backward compatibility for instance naming in k8s
- sky launch/exec with new clusters
- sky launch/exec/status/queue/down with old clusters
> [Core] Add backward compatibility for instance naming in k8s

- sky/backends/cloud_vm_ray_backend.py
- sky/core.py
- sky/execution.py
- sky/jobs/server/core.py
- sky/resources.py
- sky/serve/server/core.py
- sky/utils/cli_utils/status_utils.py
- sky/utils/controller_utils.py
- sky/utils/schemas.py
- tests/unit_tests/test_controller_utils.py
Fixes #3953.
Add an `autostop` field to the `resources` spec in the SkyPilot YAML, much like the config added in #5182.
Examples:
```
resources:
autostop: true
```
```
resources:
autostop: 10
```
```
resources:
autostop:
down: true
idle_minutes: 3
```
```
resources:
autostop: false
```
Issues:
- multiple different autostop configs for different resources
- sky start will forget autostop config
> allow specifying autostop in resources

- .github/workflows/release-build.yml
close https://github.com/skypilot-org/skypilot/issues/5503
The tag will be eventually replaced with the release version in the publish-helm workflow: https://github.com/skypilot-org/skypilot/blob/f40f78e27b076a2171f209d87db4c34758abf92b/.github/workflows/publish-helm.yml#L106
So this is no relevant to release, update the tag just to:
1. avoid confusion;
2. in case some users install the helm chart from source code
> Bump image tag in helm default values

- sky/setup_files/dependencies.py
close https://github.com/skypilot-org/skypilot/issues/5596
Test:
```
$ pip install click==8.2.0
...
$ pip install -e ".[all]"
....
Installing collected packages: click, skypilot
Attempting uninstall: click
Found existing installation: click 8.2.0
Uninstalling click-8.2.0:
Successfully uninstalled click-8.2.0
Attempting uninstall: skypilot
Found existing installation: skypilot 1.0.0.dev0
Uninstalling skypilot-1.0.0.dev0:
Successfully uninstalled skypilot-1.0.0.dev0
Successfully installed click-8.1.8 skypilot-1.0.0.dev0
$ sky api start --deploy
Failed to connect to SkyPilot API server at http://0.0.0.0:46580. Starting a local server.
✓ SkyPilot API server started.
├── SkyPilot API server: http://0.0.0.0:46580 Dashboard: http://0.0.0.0:46580/dashboard
└── View API server logs at: …
```
> Pin click version for correct argument parsing

- charts/skypilot/templates/api-deployment.yaml
- charts/skypilot/values.yaml
- docs/source/reference/api-server/api-server-admin-deploy.rst
Docs page: https://docs.skypilot.co/en/helm-lambda/reference/api-server/api-server-admin-deploy.html#optional-configure-cloud-accounts
> [API server] support for specifying lambda credential in helm deployment

- sky/exceptions.py
- sky/server/requests/executor.py
- sky/server/server.py
close #5609 
follow up: https://github.com/skypilot-org/skypilot/issues/5610
```
(sky) ➜  skypilot git:(fix-duplicate-scheduling) sky api start --deploy
Failed to connect to SkyPilot API server at http://0.0.0.0:46580. Starting a local server.
✓ SkyPilot API server started.
├── SkyPilot API server: http://0.0.0.0:46580 Dashboard: http://0.0.0.0:46580/dashboard
└── View API server logs at: ~/.sky/api_server/server.log
(sky) ➜  skypilot git:(fix-duplicate-scheduling) cat ~/.sky/api_server/server.log
I 05-17 08:34:23 config.py:143] SkyPilot API server will start 12 server processes with 21 background workers for long requests and will allow at max 22 short requests in parallel.
I 05-17 08:34:23 executor.py:514] Creating shared request queues
I 05-17 08:34:23 …
```
> Fix worker exits on duplicate scheduling

- sky/clouds/service_catalog/data_fetchers/fetch_gcp.py
Recently we got this error on catalog syncing, see [log](https://github.com/skypilot-org/skypilot-catalog/actions/runs/15006877021/job/42169564439): 
```bash
File "/home/runner/.local/share/uv/python/cpython-3.10.17-linux-x86_64-gnu/lib/python3.10/runpy.py", line 196, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/home/runner/.local/share/uv/python/cpython-3.10.17-linux-x86_64-gnu/lib/python3.10/runpy.py", line 86, in _run_code
exec(code, run_globals)
File "/home/runner/catalogs-venv/lib/python3.10/site-packages/sky/clouds/service_catalog/data_fetchers/fetch_gcp.py", line 787, in <module>
catalog_df = get_catalog_df(region_prefix_filter)
File "/home/runner/catalogs-venv/lib/python3.10/site-packages/sky/clouds/service_catalog/data …
```
> Fix fetch gcp timeout error

- examples/README.md
- examples/tpu/tpu_app.yaml
- tests/smoke_tests/test_cluster_job.py
See fail detail in #5562
According to the doc, the [region](https://cloud.google.com/tpu/docs/regions-zones) and [accelerator-type](https://cloud.google.com/tpu/docs/v2) is valid, TPU nodes are still [supported](https://cloud.google.com/tpu/docs/system-architecture-tpu-vm#tpu-node-arch) on v2 and v3, It might be Google's internal change without updating the docs.
```bash
gcloud compute tpus create t-tpu-97-a5bbd67e --project=sky-dev-465 --zone=us-central1-b --version=2.12.0 --accelerator-type=v2-8 --network=default
ERROR: (gcloud.compute.tpus.create) FAILED_PRECONDITION: Your request to provision TPU Node has been denied. Please migrate to TPU VM Architecture or contact Cloud TPU team to gain TPU Node access. https://cloud.google.com/tpu/docs/system-architecture-tpu-vm#from-tpu-node-to-tpu …
```
> Remove `test_tpu`

- sky/exceptions.py
- sky/server/requests/executor.py
- sky/server/server.py
follow up: https://github.com/skypilot-org/skypilot/pull/5598#issuecomment-2888755388
> Cherry-pick: Fix worker exits on duplicate scheduling (#5611)

- docs/source/_templates/header.html
- docs/source/_templates/layout.html
- docs/source/conf.py
Thanks to https://github.com/vllm-project/vllm/pull/5979
It adds a banner for docs on master branch, so people know that issues might be caused by version mismatch.
> [Docs] Add warning warning for developer preview version for docs

- sky/provision/kubernetes/instance.py
close https://github.com/skypilot-org/skypilot/issues/5618
Tested manually with:
```yaml
service:
readiness_probe:
path: /health
initial_delay_seconds: 180  # Use a large delay for EKS LB to be ready
replicas: 1
ports: 8080
resources:
ports:
- 8080
- 8081
setup: |
wget https://raw.githubusercontent.com/skypilot-org/skypilot/refs/heads/master/examples/serve/http_server/server.py
run: |
python3 server.py --port 8080 &
python3 server.py --port 8081
```
```yaml
sky serve up serve.yaml -n test
```
> Fix labeling of HA serve controller deployment

- docs/source/reference/config.rst
- sky/provision/provisioner.py
- sky/utils/schemas.py
This PR moves the ssh timeout for the probe during provisioning into config. This resolves the issue where users who are using VPNs or otherwise experiencing a delay to ssh into their clusters see provisioning fail due to the hardcoded 10s timeout despite their clusters actually being up and running. 
This adds a top-level config variable called `provision_ssh_timeout` which allows users to specify their own ssh timeouts for provisioning clusters. 
Updated docs: https://docs.skypilot.co/en/provision-ssh-timeout-config/reference/config.html
> move ssh timeout for provisioning to config

- sky/server/common.py
Fixes: https://github.com/skypilot-org/skypilot/issues/5572
This PR fixes an issue where the local API server fails to start when SkyPilot is installed in a venv with a space in its path. For example, for the venv at `~/my folder/.venv/bin/sky`, running `sky api start` results in the API server log complaining that `~/my: No such file or directory`.
The issue was that the call to `Popen` was being made with `shell=True`. This was done to handle the redirection operators `>`, `2>&1`, and `<` to redirect stdout to a log file, stderr to stdout (log file), and stdin to /dev/null respectively. However, this also meant that spaces are interpreted as argument separators. `Popen` has parameters to specify sdout, stderr, and stdin redirections, so this PR utilizes those parameters and removes …
> FIX: api server does not work when venv has space in path

- sky/core.py
- sky/execution.py
- sky/jobs/server/core.py
- sky/serve/server/core.py
- sky/server/requests/executor.py
- sky/server/server.py
- sky/skypilot_config.py
- sky/utils/admin_policy_utils.py
- sky/utils/context.py
- sky/utils/context_utils.py
- tests/test_config.py
- tests/unit_tests/test_admin_policy.py
- tests/unit_tests/test_backend_utils.py
- tests/unit_tests/test_sky/server/test_server.py
- tests/unit_tests/test_sky/utils/text_context.py
close #5621
This PR makes skypilot config context-aware, so that skypilot config can be safely mutated by `AdminPolicy` in request scope.
> [Core] fixed skypilot config mutation in admin policy

- .github/workflows/release-build.yml
* Add one more param: `skip_version_checks` to resolve [comment](https://github.com/skypilot-org/skypilot/pull/5470#pullrequestreview-2810772543)
> Allow bypass version check on release pipeline

- sky/clouds/__init__.py
- sky/clouds/cloud.py
- sky/optimizer.py
- sky/resources.py
- tests/test_optimizer_dryruns.py
- tests/test_optimizer_random_dag.py
Bug:  
`/.sky/config.yaml`:  
```yaml
aws:
specific_reservations:
- cr-xxx
- cr-yyy
```  
Command: `sky launch --gpus A100:8 --cloud aws`  
```bash
AssertionError: Cloud, instance type, region must be specified
```  
This test broke after #5528.  
The issue is that we have a [dummy sink node in the DAG](https://github.com/skypilot-org/skypilot/blob/master/sky/optimizer.py#L307), and then call `get_available_reservations` with this node.  
This calls `DummyCloud.get_reservations_available_resources`. Since `DummyCloud`'s `instance_type` and `region` are `None` by default, it violates the signature of `get_reservations_available_resources`. We need special handling for `DummyCloud`.
> Dummy cloud special handle for `specific_reservations`

- sky/check.py
- sky/cli.py
- sky/clouds/ssh.py
Fixing:
1. red & dim style for disabled node pools
2. k8s leakage: `Kubernetes contexts {'ssh-my-pool'} specified in "allowed_contexts" not found in kubeconfig. Ignoring these contexts.`
3. Weird triple space in show-gpus
4. sort the SSH / cloud segments
> [UX] UX updates in ssh targets

- sky/cli.py
> [Core] Client side should not rely on global_user_state

- charts/skypilot/templates/api-configmap.yaml
- charts/skypilot/templates/api-deployment.yaml
- charts/skypilot/templates/api-secrets.yaml
- charts/skypilot/values.yaml
- docs/source/reference/api-server/helm-values-spec.rst
- docs/source/reservations/existing-machines.rst
> [Docs] Add ssh node pools config doc for helm deployment

- sky/global_user_state.py
- sky/setup_files/dependencies.py
- sky/utils/db_utils.py
- tests/test_db_utils.py
- tests/test_failover.py
- tests/test_jobs.py
- tests/test_jobs_and_serve.py
Migrate `sky/global_user_state.py` to use SQLAlchemy, with follow-up goal to support postgressql as another backend to `global_user_state`.
> Migrate `sky/global_user_state.py` to use SQLAlchemy

- Dockerfile
- Dockerfile_k8s
- Dockerfile_k8s_gpu
- sky/utils/kubernetes/kubernetes_deploy_utils.py
- sky/utils/kubernetes/ssh-tunnel.sh
- tests/smoke_tests/docker/Dockerfile_test
Tested manually:
When jq is installed:
```bash
$ sky check ssh
Checking credentials to enable infra for SkyPilot.
SSH: enabled [compute]
SSH Node Pools:
└── my-cluster: enabled. Note: Could not detect GPUs in SSH Node Pool 'my-cluster'. If this cluster contains GPUs, please ensure GPU drivers are installed on the node and re-run `sky ssh up --infra my-cluster`.
🎉 Enabled infra 🎉
SSH [compute]
SSH Node Pools:
└── my-cluster
```
When jq is not installed:
```bash
$ sky ssh up
RuntimeError: `jq` is required to setup ssh cluster.
On Debian/Ubuntu, install the missing dependenc(ies) with:
$ sudo apt install jq
On MacOS, install with:
$ brew install jq
```
When jq is previously available and `sky ssh up` success, but get purged later:
```
$ sky check ssh
sky check ssh
Checking credentials to …
```
> Make jq a prerequisite for ssh cluster

- Dockerfile
- charts/skypilot/templates/api-deployment.yaml
- docs/source/reference/api-server/api-server-admin-deploy.rst
- sky/utils/kubernetes/exec_kubeconfig_converter.py
Adds support for exec-based auth on managed k8s clusters on nebius.
Required the installation of Nebius CLI and updating our exec auth convertor to use a standard `sky` profile.
Because the CLI needs write access to `~/.nebius`, needed to change the credential init pattern from using an initContainer to mounting credentials directly and symlinking specific files.
> [Helm] Fix Nebius credentials for API server

- .github/workflows/helm-docker-release.yaml
- .github/workflows/nightly-build.yml
Disable the scheduled run for `helm-docker` nightly and make `pypi-nightly-build` trigger `helm-docker` instead.  
This ensures `helm-docker` runs only after `pypi` updates (event-based instead of time-based).  
Since we now control everything in `pypi-nightly-build`, rename it to `nightly-build` for better clarity.  
Resolve #5712
> Refactor nightly build logic

- .buildkite/generate_pipeline.py
- tests/conftest.py
- tests/smoke_tests/smoke_tests_utils.py
Related PR #5707
* Assume the system has `postgresql` installed.
* Test cases will set the `SKYPILOT_DB_URI` environment variable.(Assume `postgresql` already started before each test)
* If successful, it will proceed; if failed, it will exit immediately.
> support `--postgres` on smoke test

- .github/workflows/nightly-build.yml
- .github/workflows/publish-and-validate.yml
Minor change, rename to keep consistent
And we fail to pass the [expect version in today's build](https://github.com/skypilot-org/skypilot/actions/runs/15273151597/job/42963353202), fix the dependency bug.
> Consistent name for `nightly-build` and fix bug

- sky/server/server.py
With the additional field in `RequestBody`:
```
model_config = pydantic.ConfigDict(extra='allow')
```
Pydantic starts strictly interpreting the argument, causing the `cluster_name` failed ot be parsed
> [k8s] Fix SSH for k8s SSH proxy

- sky/adaptors/kubernetes.py
- sky/clouds/kubernetes.py
- sky/provision/kubernetes/utils.py
- sky/server/server.py
- sky/utils/context.py
- tests/unit_tests/kubernetes/test_kubernetes_utils.py
close https://github.com/skypilot-org/skypilot/issues/5725
Two issues are addressed:
1. Add env var override to `/validate` handler;
2. Fix KUBECONFIG reload issue of kubernetes lib;
```
(sky) ➜  skypilot git:(master) ✗ export KUBECONFIG=~/.kube/config
(sky) ➜  skypilot git:(master) ✗ sky launch --cpus 2 "echo hello" --cloud kubernetes --region gke_sky-dev-465_us-central1-c_skypilotalpha -c aylei2
The --cloud, --region, and --zone options are deprecated. Use --infra instead.
Command to run: echo hello
ValueError: Context gke_sky-dev-465_us-central1-c_skypilotalpha not found in kubeconfig. Kubernetes only supports context names as regions. Available contexts: ['kind-kind']
(sky) ➜  skypilot git:(master) ✗ export KUBECONFIG=~/.kube/gke
(sky) ➜  skypilot …
```
> Fix kubeconfig override

- sky/dashboard/src/components/elements/version-display.jsx
- sky/dashboard/src/pages/config.js
This PR adds the API server version to the "Configuration" page in the dashboard. 
This was tested by reloading the dashboard and verifying that the correct version showed up. 
> [Dashboard] Add API server version to dashboard

- sky/setup_files/dependencies.py
smoke test failure https://buildkite.com/skypilot-1/smoke-tests/builds/1126#01971865-48aa-402b-af4d-76b6dcec62d3
due to 
```
module 'OpenSSL.crypto' has no attribute 'sign'
```
caused by https://github.com/googleapis/google-api-python-client/issues/2554
> also pin upper version of pyopenssl

- sky/client/oauth.py
- sky/client/sdk.py
- sky/server/html/token_page.html
- sky/server/server.py
Use oauth2 flow when browser is available, so that user don't have to copy-paste the token string.
UI:
Try it out:
```bash
$ git checkout oauth2-flow
$ sky api login -e http://dogfood.skypilot.co
```
> [API server] Adopt oauth2 flow if browser is avaiable

- charts/skypilot/templates/api-deployment.yaml
- charts/skypilot/templates/api-secrets.yaml
- charts/skypilot/values.yaml
- docs/source/reference/api-server/api-server-admin-deploy.rst
- docs/source/reference/api-server/helm-values-spec.rst
- make skypilot helm chart accept SSH keys directly via `apiService.sshKeys`
- create secret and mount automatically when `sshKeys` are provided
- update admin docs for one-step SSH node pool setup
- document new helm value
- `bash format.sh`
- `pytest -k nothing -q` *(fails: KeyboardInterrupt due to network restrictions)*
> Add sshKeys helm value

- sky/server/stream_utils.py
- sky/utils/rich_utils.py
- tests/test_api.py
close https://github.com/skypilot-org/skypilot/issues/5750
Explanation: https://github.com/skypilot-org/skypilot/issues/5750#issuecomment-2918711119
> [API server] Add heartbeat to streaming response

- sky/check.py
Previously, when multiple workspaces existed, if a user ran sky check with a cloud or list of clouds specified (e.g. `sky check  gcp` or `sky check gcp azure aws`), the cli would not display the reason for a cloud being disabled. The only way to see the reason for a cloud being disabled when multiple workspaces exist was to use the `-v` flag or `-w {WORKSPACE_NAME}`. This PR makes it such that when a user expresses a specific intent (specifies a single cloud or list of clouds), that intent is respected and the reason for certain clouds being disabled will be displayed. 
I created a test workspace in addition to the default workspace and then ran `sky check gcp` before and after this change to verify that it does indeed now show the reason for why gcp is disabled. 
Tested (run the relevant …
> [Workspaces] Show reason for cloud disabled in sky check when clouds specified

- sky/exceptions.py
- sky/server/common.py
Prior to this PR, when a user was not authenticated via SSO and tried to run a command such as `sky status`, there would be an extremely verbose and completely unhelpful error message essentially printing the entire html for the sso page (okta, google, etc.). 
This was because the client code was not properly handling the NEEDS_AUTH server response. This PR fixes the client-side NEEDS_AUTH handling and returns a simple error message to the user indicating that they need to authenticate and what command to run to do so. 
I tried running `sky status` on a remote API server where I was not authenticated and saw the following response:
```
❯ sky status
sky.exceptions.ApiServerAuthenticationError: Authentication required for SkyPilot API server at http://dogfood.skypilot.co. Please run:
sky …
```
> [SSO] Cleanly error out if user is not authenticated to API server

- sky/clouds/kubernetes.py
Nvidia device plugin has a known issue where if no GPUs are requested, it exposes all GPUs to the pod: https://github.com/NVIDIA/k8s-device-plugin/issues/61
As a result, `sky launch -c cpus --infra kubernetes --image-id us-docker.pkg.dev/sky-dev-465/skypilotk8s/skypilot-gpu:latest -- nvidia-smi` would show all GPUs, even though not GPUs were requested.
The "right" way to fix it is to have the cluster admin install the gpu-operator such that it does not mount the GPU devices when no GPUs are requested by setting this in their [gpu operator helm chart](https://github.com/NVIDIA/k8s-device-plugin/issues/61#issuecomment-2401284348):
```
toolkit:
env:
- name: ACCEPT_NVIDIA_VISIBLE_DEVICES_ENVVAR_WHEN_UNPRIVILEGED
value: "false"
- name: ACCEPT_NVIDIA_VISIBLE_DEVICES_AS_VOLUME_MOUNTS
value: …
```
> [k8s] Fix GPU isolation when no GPUs are requested

- sky/backends/cloud_vm_ray_backend.py
- sky/dashboard/src/components/utils.jsx
- sky/dashboard/src/data/connectors/jobs.jsx
- sky/dashboard/src/pages/jobs/[job].js
- sky/jobs/client/sdk.py
- sky/jobs/constants.py
- sky/jobs/server/core.py
- sky/jobs/utils.py
- sky/server/constants.py
- sky/server/requests/payloads.py
This PR brings two main improvements:
1. Significantly improved log loading speed in the managed jobs dashboard. Logs were previously stored as an array in the frontend, but JavaScript is much faster at appending to a string than an array ([ref](https://stackoverflow.com/a/7299040)). Furthermore, the frontend was previously streaming the entire log from the backend before formatting and displaying it on the dashboard. This PR formats the logs as they come in and displays them in a streaming fashion which makes for a much faster UX. 
2. Implements log tailing for managed jobs. Even with the optimizations outlined above, once logs reach a certain length (> 100k lines) the dashboard loading speed becomes too long and can make the entire dashboard unresponsive. This change makes it such that …
> [Managed Jobs] speed up log loading time in dashboard and implement managed jobs log tailing

- sky/dashboard/src/components/infra.jsx
- sky/dashboard/src/components/jobs.jsx
- sky/dashboard/src/components/workspaces.jsx
- sky/dashboard/src/data/connectors/clusters.jsx
- sky/dashboard/src/data/connectors/infra.jsx
- sky/dashboard/src/data/connectors/jobs.jsx
- sky/dashboard/src/lib/README.md
- sky/dashboard/src/lib/cache-preloader.js
- sky/dashboard/src/lib/cache.js
- sky/dashboard/src/pages/clusters/[cluster].js
- sky/dashboard/src/pages/jobs/[job].js
This PR implements caching of specific cluster and managed jobs pages in the dashboard. 
This PR was tested by rapidly switching between the top level pages and specific cluster and managed jobs pages and verifying that the loading speed was reduced when visiting pages repeatedly. 
> [Dashboard] Cluster-Specific and Managed Job-Specific Page Caching

- charts/skypilot/values.yaml
- sky/execution.py
- sky/utils/controller_utils.py
The code of HA serve controller seems fine when used in HA jobs controller. Did some manual test:
1. Enable HA job controller:
Add the following configuration to skypilot.yaml
```yaml
jobs:
controller:
resources:
high_availability: true
```
2. Test launch:
```bash
$ sky jobs launch -n j1 --cpus 1+ "echo hi; sleep 5; echo done;"
....
✓ Managed job finished: 1 (status: SUCCEEDED).
```
3. Test the state is persistent:
```bash
$ kubectl get po
NAME                                                              READY   STATUS    RESTARTS   AGE
sky-jobs-controller-a246a9e3-a246a9e3-deployment-6f5775557bh4h5   1/1     Running   0          10m
$ kubectl delete po sky-jobs-controller-a246a9e3-a246a9e3-deployment-6f5775557bh4h5
pod …
```
> [core] support HA job controller

- sky/backends/cloud_vm_ray_backend.py
Fixes #4232. Prints:
> ERROR: Job X failed with return code list: [137, 1, 137 137] (A worker failed with return code 1, SkyPilot cleaned up the processes on other nodes with return code 137)
Manually ran with a yaml file that runs `exit 1`
> [UX] Improve error message when one node fails

- docs/source/reference/kubernetes/kubernetes-troubleshooting.rst
Internally, SSH Node Pools are k3s clusters with context name prefixes of `ssh-`. This information was added to the kubernetes troubleshooting docs. 
> [Docs][k8s/ssh] Update k8s troubleshooting for SSH Node Pools

- sky/catalog/__init__.py
- sky/catalog/common.py
- sky/catalog/constants.py
- sky/cli.py
- sky/skylet/constants.py
- sky/utils/schemas.py
The catalog package has a non-empty `__init__.py` - so any package that needs catalog constants have `__init__.py` run, which causes unnecessary circular imports. This change moves the constants to skylet, which has an empty `__init__.py`.
> move catalog constants to skylet constants

- sky/skypilot_config.py
- sky/workspaces/core.py
- tests/unit_tests/test_sky/utils/kubernetes/test_skypilot_config_configmap_sync.py
1. rename the function u`pdate_api_server_config_no_lock` to communicate this function is meant for modifying server configs, not client configs
2. Attempt to use `_resolve_server_config_path` first to find the config path. `_resolve_server_config_path` accounts for `SKYPILOT_GLOBAL_CONFIG` environment variable being set which can change the location of the server side config file.
> refactor update_config_no_lock

- examples/admin_policy/example_policy/example_policy/__init__.py
- examples/admin_policy/example_policy/example_policy/skypilot_policy.py
- examples/admin_policy/set_max_autostop_idle_minutes.yaml
- sky/admin_policy.py
- sky/client/sdk.py
- sky/execution.py
- sky/resources.py
- sky/server/requests/payloads.py
- tests/smoke_tests/backward_compat/test_backward_compat.py
- tests/test_yamls/autostop.yaml
- tests/unit_tests/test_admin_policy.py
- tests/unit_tests/test_resources.py
close https://github.com/skypilot-org/skypilot/issues/5642
Manual test:
**Task YAML**
```bash
$ cat task.yaml
resources:
autostop:
idle_minutes: 5
```
**Enable the new policy**
```bash
$ cat ~/.sky/config.yaml
admin_policy: example_policy.SetMaxAutostopIdleMinutesPolicy
```
**sky launch failed since Kubernetes does not support autostop**
```bash
$ sky launch task.yaml
⨯ Failed to provision resources. View logs: sky api logs -l sky-2025-06-05-13-26-34-315923/provision.log
sky.exceptions.ResourcesUnavailableError: Failed to provision all possible launchable resources. Relax the task's resource requirements: 1x Kubernetes(cpus=1+)
...
```
**Override with autodown, succeed**
```bash
$ sky launch task.yaml --down
✓ Cluster launched: sky-b461-aylei
$ sky status
NAME …
```
> [Core] make autostop in task the source of truth

- sky/serve/load_balancer.py
A user reports the error triggered by sync with controller is breaking the LB process and hence not responding to further requests. This PR catches more exception to prevent such behavior. We should investigate more for the root cause.
> [Serve] Catch more exceptions in syncing with controller

- tests/conftest.py
- tests/smoke_tests/test_mount_and_storage.py
These tests don't actually submit the operations to the API server, and therefore doesn't use API server's db backend. This causes problems when the API server is not using the SQLite db. Skip these tests for now and fix them later.
> mark certain smoke tests with no_postgres

- .github/workflows/buildkite-trigger-wait.yml
- .github/workflows/nightly-build.yml
- .github/workflows/publish-and-validate-both.yml
- .github/workflows/release-build.yml
- .github/workflows/smoke-tests-trigger.yaml
Follow up on #5889  
The helm-release wasn't triggered when the PyPI test was skipped.  
Simplify the logic by creating two more YAML files:  
1. Trigger and wait for Buildkite  
2. Publish and validate PyPI (both test PyPI and PyPI)  
Then in the nightly workflow, we can call these two files. This way, we only need one `if` condition in one step, instead of having `if` conditions in every step and using `always()` everywhere to make GitHub Actions work. The current approach is harder to read and understand.
> Refactor release pipeline -- fix the skip options in nightly build

- .github/workflows/smoke-tests-trigger.yaml
Currently hardcode master, change to selected github ref
> Use selected branch to trigger buildkite test in github action

- .github/workflows/nightly-build.yml
The scheduled job failed because it had no input. See the [scheduled build](https://github.com/skypilot-org/skypilot/actions/runs/15488687390/job/43622658656).
> Fix schedule input on nightly build pipeline

- docs/source/reservations/existing-machines.rst
- sky/backends/backend_utils.py
- sky/provision/kubernetes/utils.py
- sky/skylet/constants.py
Adds docs and plumbing for mounting host paths into SkyPilot jobs running on SSH node pools.
Future TODO: support this through a more native file_mounts? This is a very common JTBD for fixed clusters.
> [SSH] Volume mounting for SSH Node Pools

- sky/skypilot_config.py
To repro
1. On a brand new machine with no config yaml, but a `.sky.yaml` in the cwd
2. `sky check`
```
E 06-04 20:43:10 sdk.py:1601]   File "/home/ubuntu/sky_workdir/sky/server/requests/executor.py", line 244, in override_request_env_and_config
E 06-04 20:43:10 sdk.py:1601]     with skypilot_config.override_skypilot_config(
E 06-04 20:43:10 sdk.py:1601]   File "/home/ubuntu/miniconda3/lib/python3.10/contextlib.py", line 135, in __enter__
E 06-04 20:43:10 sdk.py:1601]     return next(self.gen)
E 06-04 20:43:10 sdk.py:1601]   File "/home/ubuntu/sky_workdir/sky/skypilot_config.py", line 650, in override_skypilot_config
E 06-04 20:43:10 sdk.py:1601]     assert _get_loaded_config_path() is not None
E 06-04 20:43:10 sdk.py:1601] TypeError: unsupported operand type(s) for +: 'NoneType' and …
```
> [config] return empty list when no config is loaded

- charts/skypilot/templates/api-deployment.yaml
- charts/skypilot/values.yaml
Allowing user-specified init containers to be deployed alongside the API server container in a sidecar pattern can be helpful. One example is running Cloud SQL Auth Proxy as a sidecar to facilitate GKE pod access to GCP Cloud SQL server.
> [API server] add extraInitContainers field to helm deployment

- docs/source/reference/api-server/api-server-admin-deploy.rst
- docs/source/reference/api-server/examples/api-server-persistence.rst
- docs/source/reference/config.rst
- sky/global_user_state.py
- sky/skypilot_config.py
If `db` is specified in server config, the config file is not allowed to contain any other config. Additional config can be supplied to the API server by using the dashboard (or REST API directly), which is persisted in the remote db.
To avoid circular import dependency between this package and `global_user_state.py`, I've had to initialize a separate DB engine here.
> Support DB as a store for server-side config

- tests/test_config.py
> [Test] fix test_config.py test_get_override_skypilot_config_from_client

- .buildkite/generate_pipeline.py
- .github/workflows/helm-docker-release.yaml
- .github/workflows/nightly-build.yml
- tests/conftest.py
- tests/kubernetes/scripts/helm_gcp.sh
- tests/smoke_tests/docker/Dockerfile_test
- tests/smoke_tests/test_images.py
* A bash script to launch GKE cluster and deploy helm with our specific skypilot version on it
* Verify the `${ENDPOINT}/api/health` work after deploy
* Trigger this test on release pipeline
> Support helm deploy test on GKE in smoke test and release pipeline

- docs/source/cloud-setup/policy.rst
- docs/source/reference/api-server/api-server-admin-deploy.rst
- examples/admin_policy/example_policy/example_policy/__init__.py
- examples/admin_policy/example_policy/example_policy/client_policy.py
- examples/admin_policy/use_local_gcp_credentials.yaml
- sky/admin_policy.py
- sky/client/sdk.py
- sky/jobs/client/sdk.py
- sky/serve/client/sdk.py
- sky/server/requests/payloads.py
- sky/skylet/constants.py
- sky/utils/admin_policy_utils.py
- sky/utils/context.py
- tests/unit_tests/test_admin_policy.py
This PR introduce client-side admin policy support and update the doc of admin policy to reflect our client-server architecture.
Also, an example policy is added to illustrate the usage of client-side admin policy, which always override the GCP credentials at the task to the local GCP credentials instead of the API server's.
Test:
A relevant unit test case is also added.
> [Core] Support client-side admin policy

- .github/workflows/nightly-build.yml
- tests/smoke_tests/test_workspaces.py
The skip mark was removed in #5922 but the test itself will fail even if the test infra supported.
Restore the change for now to unblock the nightly-build.
> Restore skip `test_workspace_switching`

- sky/jobs/state.py
- sky/jobs/utils.py
Lazily initialize `~/.sky/spot_jobs.db` on first query. This has the effect of avoiding DB initialization on client side.
> lazy initialization of spot_jobs db

- docs/source/examples/managed-jobs.rst
- docs/source/reference/yaml-spec.rst
- sky/cli.py
- sky/jobs/scheduler.py
- sky/jobs/state.py
- sky/jobs/utils.py
Now, a higher priority value indicates that the job is higher priority.
> [jobs] invert priority value

- sky/users/permission.py
- tests/unit_tests/test_sky/users/test_permission.py
Lazily initialize the permissions service on first request. This has the effect of saving the initialization on the client side.
> lazy initialization of permissions service

- sky/dashboard/src/components/infra.jsx
- sky/dashboard/src/data/connectors/infra.jsx
- sky/models.py
- sky/provision/kubernetes/utils.py
- sky/server/server.py
This PR adds the k8s node ip address to the infra dashboard page, so it can be used to identify instances in the dcgm exporter dashboard. 
The instances in the dcgm exporter dashboard were originally showing pod ips which differed from the node ips, but running the following command and then deleting the old dcgm exporter pods made the pods use the node ips:
```
kubectl patch daemonset nvidia-dcgm-exporter -n gpu-operator --type='merge' -p='
{
"spec": {
"template": {
"spec": {
"hostNetwork": true,
"dnsPolicy": "ClusterFirstWithHostNet"
}
}
}
}'
```
Tested by verifying the IPs showing up in the infra dashboard and the updated node ips showing up in dcgm exporter dashboard in grafana. 
> [Metrics] Add k8s node ip to infra dashboard page

- .github/workflows/helm-unittest.yaml
- charts/skypilot/.helmignore
- charts/skypilot/templates/api-deployment.yaml
- charts/skypilot/unittests/deployment_test.yaml
close https://github.com/skypilot-org/skypilot/issues/5972
This is introduced by https://github.com/skypilot-org/skypilot/pull/5742, only `sshNodePools` enabled and both `kubeconfig` and `sshNodePools` enabled are tested in that PR. So unit test cased are added to avoid regression.
Also tested manually on real kubernetes cluster.
> [Bug] Fixed kubeconfig mounting in helm deployment

- sky/check.py
- sky/utils/controller_utils.py
- tests/unit_tests/test_controller_utils.py
Tested: jobs controller running on GKE and `sky jobs launch` to run job on Nebius k8s cluster.
> [Jobs] Fix jobs controller access to Nebius k8s cluster

- sky/benchmark/benchmark_state.py
- sky/jobs/state.py
- sky/server/requests/requests.py
- sky/skylet/configs.py
- sky/skylet/job_lib.py
1. add locks to lazily initialized DBs that don't have locking
2. do not initialize directory until the DB is initialized
3. do not use `_db_initialized` boolean if another variable is available to determine if a DB has been initialized or not.
> standardize db initialization

- .github/workflows/release-publish.yml
Previously, when we closed the release [PR](https://github.com/skypilot-org/skypilot/pull/5828), it triggered this build error:  
https://github.com/skypilot-org/skypilot/actions/runs/15604281205  
> Fix `release-publish` pipeline failure

- tests/conftest.py
- tests/kubernetes/scripts/helm_gcp.sh
See failure [logs](https://buildkite.com/organizations/skypilot-1/pipelines/full-smoke-tests-run/builds/40/jobs/01977708-50e0-4556-9366-dea1e2ffccf2/log) in release
If we are using the latest version, it could be the previously published version at any time - we don't verify in this case.
> Fix latest version mismatch on helm_gcp deployment tests

- sky/utils/command_runner.py
- sky/utils/context.py
Description:  
This pull request corrects minor typos in the codebase:
- In `sky/utils/command_runner.py`, the word "comamnd" in a comment was corrected to "command".
- In `sky/utils/context.py`, the word "intialize" in a docstring was corrected to "initialize".
These changes improve code readability and maintain documentation accuracy. No functional code was modified.
> Fix Typos in Comments and Docstrings

- docs/source/reference/api-server/api-server-admin-deploy.rst
- docs/source/reference/api-server/examples/api-server-gpu-metrics-setup.rst
- docs/source/reference/api-server/examples/api-server-metrics-setup.rst
Adds docs pages on enabling metrics. Has some TODOs to be fixed in the `add-metrics-to-server-exp` branch.
> [Docs] Add metrics docs

- sky/users/permission.py
- tests/unit_tests/test_sky/users/test_permission.py
This reverts commit 71ac633a5421948ce665935e30e85e5bbc985a26.
Unfortunately the commit causes race conditions on CI unit tests - until we can fix this race condition properly, we should revert this change.
> Revert "lazy initialization of permissions service (#5942)"

- sky/utils/controller_utils.py
Previously we will install K8s & SSH dependencies twice on the controller. This PR fixes it
> [UX] Fix SSH Cloud Dependency Installation on Controller

- tests/smoke_tests/backward_compat/test_backward_compat.py
* Skip autostop
* Upgrade the BuildKite VM from `r5a.2xlarge` to `m6a.4xlarge` (from 8 CPU/64GB to 16 CPU/64GB). -- Manual deploy, no code change needed
> Fix kubernetes quicktest core

- sky/utils/kubernetes/deploy_remote_cluster.py
This is an improvement to #6003, and places the checks and path expansions in a single place: when parsing the ssh_node_pools.yaml file
I would still like to keep the file check on `run_remote` as a last minute sanity check.
> [SSH] identity file check improvement

- docs/source/reference/kubernetes/examples/kueue-example.rst
> docs change to enable waitForPodsReady

- docs/source/examples/managed-jobs.rst
- docs/source/reference/yaml-spec.rst
Code deprecation of `job.priority` will follow, but first we should remove mentions of it in docs.
> remove job.priority from docs

- charts/skypilot/templates/oauth2-proxy-deployment.yaml
- charts/skypilot/values.yaml
- docs/source/reference/api-server/examples/api-server-auth-proxy.rst
Add a config option so that the OAuth Client ID/Client Secret used the oauth2-proxy can be specified in a kubernetes secret rather than in the helm values.
If using this feature, the secret should be defined as follows:
```
apiVersion: v1
kind: Secret
metadata:
name: oauth2-proxy-credentials
namespace: skypilot
data:
client-id: XXXXXXX
client-secret: XXXXXX
```
Where the namespace and name match those specified in helm
> [auth] read client id/secret from k8s secret

- tests/smoke_tests/test_cluster_job.py
- tests/smoke_tests/test_mount_and_storage.py
- tests/smoke_tests/test_sky_serve.py
> We have change the VM instance size, See if its possible to let kind cluster run sky server tests to save resource and improve stability. If so, this would bring huge stability improvements to the k8s tests and save significant time.
Follow up PR for #6010
> Remove resource heavy for sky serve test

- tests/smoke_tests/backward_compat/test_backward_compat.py
[Failure logs](https://buildkite.com/skypilot-1/quicktest-core/builds/466#019770f2-ae79-476f-b7a8-d61e9d25bf55)
> Fix backward compatibility test failures for release 0.10.0

- tests/smoke_tests/test_sky_serve.py
[Failure logs](https://buildkite.com/skypilot-1/full-smoke-tests-run/builds/40#_) in release 0.10.0
It seems GCP provisioning speed has improved. The `sky serve` status shows replicas are sometimes in `READY` state instead of the `PROVISIONING` state we used to see.
> Fix `test_skyserve_dynamic_ondemand_fallback`

- sky/dashboard/src/components/clusters.jsx
- sky/dashboard/src/components/jobs.jsx
- sky/dashboard/src/components/utils.jsx
- sky/dashboard/src/pages/clusters/[cluster].js
- sky/dashboard/src/pages/clusters/[cluster]/[job].js
- sky/dashboard/src/pages/jobs/[job].js
Changes
- Display short timestamps in a dotted underline 
- Consistent timestamps across clusters + jobs
- more than 1d old gets the YYYY-mm-dd format instead of "3d ago" or "1mo ago"
Now
> [UI] Timestamp tweaks

- sky/dashboard/src/components/clusters.jsx
A text string was updated in `sky/dashboard/src/components/clusters.jsx`.
Initially, the change was requested for `users.jsx`, but a codebase search revealed the target string "Show History (last 30 days)" was located in `clusters.jsx`.
The string was modified to "Show history (Last 30 days)", specifically:
*   "History" was changed to "history" (lowercase 'h').
*   "last" was changed to "Last" (uppercase 'L').
This adjustment ensures consistent casing for the display text.
> Update text capitalization in users.jsx

- sky/users/permission.py
Was seeing some casbin logging despite having SKYPILOT_DEBUG=0. Fixed by setting logging levels for more casbin modules.
```
(py310) ➜  volumes git:(storage) ✗ export SKYPILOT_MINIMIZE_LOGGING=1
export SKYPILOT_DEBUG=0
(py310) ➜  volumes git:(master) ✗ sky api info                      
INFO:casbin.model.assertion:Role links for: g
INFO:casbin.rbac.default_role_manager.role_manager:12345678 < admin, 2ea485ea < admin, 2ea485ef < admin, skypilot-system < admin, 68cc6558 < admin, de5111f4 < admin, 9ed23267 < admin
INFO:casbin.model.assertion:Role links for: g
INFO:casbin.rbac.default_role_manager.role_manager:12345678 < admin, 2ea485ea < admin, 2ea485ef < admin, skypilot-system < admin, 68cc6558 < admin, de5111f4 < admin, 9ed23267 < admin
Using SkyPilot API server and dashboard: …
```
> [RBAC] Hide more casbin logging

- docs/source/examples/index.rst
- docs/source/examples/periodic-and-trigger/airflow.md
- docs/source/examples/periodic-and-trigger/cron.md
- docs/source/examples/periodic-and-trigger/github_actions.md
- docs/source/examples/periodic-and-trigger/index.rst
- examples/cron/README.md
- examples/github_actions/README.md
- examples/github_actions/run_sky.yaml
Docs link: https://docs.skypilot.co/en/cron-example/examples/periodic-and-trigger/index.html
We already have an airflow example, and arguably airflow can be trigger based, so I included it in the toc
> [docs] cron and github actions example

- llm/llama-4-finetuning/README.md
- llm/llama-4-finetuning/llama-4-maverick.yaml
- sky/backends/cloud_vm_ray_backend.py
- sky/provision/kubernetes/instance.py
- sky/templates/kubernetes-ray.yml.j2
Closes #4140 and adds an example for training llama 4 maverick (400B MoE). The example needed a fix for rdvz on k8s, inspired by #3800.
> [k8s][examples] rdvz fix for k8s and Llama 4 example

- sky/dashboard/src/utils/grafana.js
> [Metrics] make metrics table only show up if grafana returns code 200

- docs/source/reference/api-server/api-server-admin-deploy.rst
- docs/source/reference/config.rst
We should get into the habit of including which version a change is made available - this PR does it for the recently introduced environment variable specification of DB backend.
> show version info for db changes in docs

- sky/server/constants.py
- sky/server/requests/requests.py
- sky/server/server.py
> [API server] Add automatic restart of daemon and traceback

- sky/utils/subprocess_utils.py
The previous way to get the python executable is not robust in the local env. To reproduce:
1. `sky launch -c dev`
2. `ssh dev`
3. `git clone skypilot-repo` and install from source in a different env and start an API server with the code
4. `rm ~/skypilot-runtime -r` and run `sky launch -c test`
Error occurs:
```
E 06-27 18:32:16 sdk.py:1730]   File "/home/ubuntu/skypilot-dev/sky/utils/subprocess_utils.py", line 347, in kill_process_daemon
E 06-27 18:32:16 sdk.py:1730]     subprocess.Popen(
E 06-27 18:32:16 sdk.py:1730]   File "/home/ubuntu/miniconda3/lib/python3.10/subprocess.py", line 971, in __init__
E 06-27 18:32:16 sdk.py:1730]     self._execute_child(args, executable, preexec_fn, close_fds,
E 06-27 18:32:16 sdk.py:1730]   File "/home/ubuntu/miniconda3/lib/python3.10/subprocess.py", …
```
> [Core] Use current python path for daemon process

- charts/skypilot/templates/ingress.yaml
- sky/server/server.py
> enforce auth for Bearer tokens that aren't skypilot SA tokens

- sky/utils/ux_utils.py
This seems to have inadvertently regressed in #4660.
> print exception stacktrace when SKYPILOT_DEBUG=1

- charts/skypilot/templates/grafana-ingress.yaml
This PR enables automatically logging into grafana once the user logs into the api server using an oauth proxy.
> [Metrics] Grafana auto login using oauth proxy

- sky/jobs/server/core.py
We still need to upload files in consolidation mode, for each job to have a separate environment.
> [Core][Jobs] filemounts upload for job consolidation

- sky/catalog/data_fetchers/fetch_cudo.py
- sky/clouds/cudo.py
- sky/provision/cudo/cudo_utils.py
- sky/provision/cudo/cudo_wrapper.py
Fixes https://github.com/skypilot-org/skypilot/issues/5208
Fixes https://github.com/skypilot-org/skypilot/issues/3829
**Changes:**
- Replaced all `list_vm_machine_types` calls with `list_vm_machine_types2`. `list_vm_machine_types2` has a different call signature, wherein it doesn't accept any argument, and just returns a list of instances coupled with availability info.
- Updated Cudo catalog to include all GPUs.
- Fixed `sky check` command for Cudo cloud.
- Here's the `skypilot-catalog` PR: https://github.com/skypilot-org/skypilot-catalog/pull/136
**Open Questions:**
1. Cudo offers two variants of A40 and L40S: "graphics mode" and "compute mode". Should the catalog include both and choose the lower cost of the two? Or should it just include "compute mode"?
2. Cudo doesn't offer H100 …
> Fix Cudo Integration

- sky/clouds/aws.py
AWS configure list is a bit slow on MAC (~3s)
This is coming from the client -- the main bottleneck is `aws configure list`. Reduced 6s -> 3s.
> [Perf] Sky status `aws configure list`

- sky/jobs/client/sdk.py
- sky/jobs/server/core.py
Some additional fields critical to CLI/dashboard were missing from docstr. Also ~`duration`~ -> `job_duration`
> [Jobs] Fix return type docstr

- sky/server/uvicorn.py
- tests/load_tests/test_load_on_server.py
- tests/unit_tests/test_sky/server/test_server.py
This PR fixes a bug introduced by https://github.com/skypilot-org/skypilot/pull/6048 which breaks the behavior event loop selecting. Now uvicorn will use uvloop by default if available.
Benchmark:
uvloop:
```bash
$ python tests/load_tests/test_load_on_server.py -n 100 --apis api_status
Latency Statistics:
----------------------------------------------------------------------------------------------------
Kind                 Count    Total(s)   Avg(s)     Min(s)     Max(s)     P95(s)     P99(s)
----------------------------------------------------------------------------------------------------
API /status          100      14.50      0.14       0.04       0.18       0.18       0.18
```
default loop:
```bash
$ python tests/load_tests/test_load_on_server.py -n 100 --apis api_status
Latency …
```
> [API server] Use uvloop by default

- sky/templates/kubernetes-ray.yml.j2
This PR changes the imagePullPolicy for ray-node to Always instead of IfNotPresent. This resolves an issue where nodes can get into inconsistent state in the case where a cluster is sky launched on a single node (pulls image v1) and then the cluster is torn down and another cluster is sky launched on the same node and others and the other nodes pull image v2. 
This value was initially set to IfNotPresent to reduce the amount of time pulling images if they have already been pulled, but the following benchmarking results for Always seem reasonable and will fix the bug described above:
IfNotPresent:
1st sky launch: ~30s spent pulling image
2nd sky launch: 0s spent pulling image ("already present on machine")
Always:
3rd sky launch: ~1s spent pulling image
> [K8s] update ray node imagePullPolicy to Always from IfNotPresent

- sky/clouds/kubernetes.py
- sky/provision/kubernetes/utils.py
Previously our label formatter returned `nvidia-tesla-h200`. Now it returns the correct GKE label `nvidia-h200-141gb`.
Also updates timeouts for DWS flex start.
> [GKE] Fix GKE label formatter for H200

- sky/dashboard/src/data/connectors/jobs.jsx
Now the truncation will keep both head and tail of the string.
Before:
After:
> [Dashboard] Fix jobs table context truncation

- docs/source/reference/kubernetes/examples/kueue-example.rst
- docs/source/reservations/reservations.rst
- sky/provision/kubernetes/instance.py
- sky/provision/kubernetes/utils.py
- sky/templates/kubernetes-ray.yml.j2
- Fix multi nodes cluster issue with GKE DWS enabled
- Update doc for Kueue config with GKE DWS enabled
- Fix the issue when requesting H200 GPU
- L4 GPU, flex start mode, 1 node
- L4 GPU, flex start mode, 2 nodes
- L4 GPU, flex start with queued provisioning mode, 1 node
- L4 GPU, flex start with queued provisioning mode, 6 nodes
- H100 GPU, flex start mode, 1 node
- H100 GPU, flex start mode, 2 nodes
- H100 GPU, flex start with queued provisioning mode, 1 node
- H100 GPU, flex start with queued provisioning mode, 2 nodes
- CPU, 1 node
- CPU, 2 nodes
> [Core] Fix multi nodes cluster issue with GKE DWS enabled

- sky/users/permission.py
This function
```
adapter = sqlalchemy_adapter.Adapter(engine)
```
calls `Base.metadata.create_all`, as shown in the code snippet for the adapter code
```
class CasbinRule(Base):
__tablename__ = "casbin_rule"
id = Column(Integer, primary_key=True)
ptype = Column(String(255))
v0 = Column(String(255))
v1 = Column(String(255))
v2 = Column(String(255))
v3 = Column(String(255))
v4 = Column(String(255))
v5 = Column(String(255))
def __str__(self):
arr = [self.ptype]
for v in (self.v0, self.v1, self.v2, self.v3, self.v4, self.v5):
if v is None:
break
arr.append(v)
return ", ".join(arr)
def __repr__(self):
return '<CasbinRule {}: "{}">'.format(self.id, str(self))
class Filter:
ptype = []
v0 = []
v1 = []
v2 = []
v3 = []
v4 = []
v5 = []
class Adapter(persist.Adapter, persist.adapters.UpdateAdapter): …
```
> Safely precreate casbin tables before creating adapter

- sky/backends/backend_utils.py
- sky/jobs/utils.py
This PR disables the use of consolidation mode (`jobs.controller.consolidation_mode`) when running the API server locally. This is done by raising a `NotSupportedError` exception when a user tries to enable it locally.
Tested manually by doing `sky jobs launch "echo hello"` against a local API server, and verifying that the exception is raised if `SKYPILOT_DEV` is false/unset.
> raise exception when running locally with consolidation mode enabled

- tests/smoke_tests/backward_compat/test_backward_compat.py
Fix the failure happened [here](https://buildkite.com/skypilot-1/quicktest-core/builds/628#0197f3e2-c0a7-436d-86cd-3f2318bde7d9)
The test reads the constant from the file, but if we're comparing with the previous PyPI package rather than source code, we don't have the constant.
> [Test] Read constant from package rather than source code file

- sky/optimizer.py
- tests/test_optimizer_dryruns.py
We were not returning the full list of resources candidates in `_fill_in_launchable_resources`, as we were overwriting it each time we process the same `cloud` (with `resources.any_of`, you could have the same cloud with different regions/zones). As a result, in `_print_candidates`, what would happen is the list of candidates might not match the optimizer’s chosen resource, thus making it inconsistent with the printed plan on the table right above it.
For example here, the chosen instance is `g6.4xlarge[Spot]`, but below it says `The cheapest [spot](gpus=A10G:1, g5.xlarge, ...) is considered ...`
```
YAML to run: hello_sky.yaml
Considered resources (1 node):
--------------------------------------------------------------------------------------
INFRA              INSTANCE           vCPUs …
```
> fix logging in optimizer's `_print_candidates`

- llm/llama-4-finetuning/configs/llama4_maverick_full_sft_cpu.yaml
- llm/llama-4-finetuning/configs/offload_cpu.yaml
- llm/llama-4-finetuning/llama-4-maverick_gke_llama_factory_sft_cpu.yaml
This PR adds an example with training maverick on a nebius cluster (cpu offloading)
> [Example] Training 400b maverick model with CPU offloading

- sky/setup_files/dependencies.py
Resolve #6226
Test in Ubuntu
```
uv venv --seed ~/test-env
source ~/test-env/bin/activate
uv pip install --prerelease=allow "azure-cli>=2.65.0"
uv pip install -e ".[azure]"
sky check azure
```
```bash
(test-env) zpoint:~/codes/skypilot (master)$ sky check azure
Checking credentials to enable infra for SkyPilot.
Azure: disabled 
Reason [compute]: Getting user's Azure identity failed. Run the following commands:
$ az login
$ az account set -s <subscription_id>
For more info: https://docs.microsoft.com/en-us/cli/azure/get-started-with-azure-cli
Details: sky.exceptions.CloudUserIdentityError: Failed to get Azure user identity with unknown exception.
Reason: [ImportError] You need to install 'msrestazure' to use this feature
Reason [storage]: Getting user's Azure identity failed. Run the …
```
> Azure dependency fix

- sky/resources.py
- tests/unit_tests/test_resources.py
In `RetryingVmProvisioner`, we store a set of `_blocked_resources`, which gets added to each time a resource fails to be provisioned.
This set is used to filter resources that are indicated to be unavailable from previous attempts:
https://github.com/skypilot-org/skypilot/blob/784b2e329d9d58c00caaa94f53d437f6158f8c7d/sky/backends/cloud_vm_ray_backend.py#L1396-L1415
The issue lies in the `should_be_blocked_by()` call. It doesn't take into account the `use_spot` property of the resources.
This means, if let's say you have this resources config:
```yaml
resources:
cpus: 16+
any_of:
- infra: aws/us-west-2/us-west-2c
use_spot: true
accelerators: "L4:1"
- infra: aws/us-west-2/us-west-2c
accelerators: "L4:1"
```
and you failed to provision a `g6.4xlarge` spot instance in …
> take use_spot into account when comparing Resources

- sky/utils/kubernetes/generate_kubeconfig.sh
Previously generated kubeconfigs  would fail with:
```
D 07-11 12:23:13 provisioner.py:169] HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"clusterroles.rbac.authorization.k8s.io \"skypilot-service-account-cluster-role\" is forbidden: User \"system:serviceaccount:default:sky-sa\" cannot list resource \"clusterroles\" in API group \"rbac.authorization.k8s.io\" at the cluster scope","reason":"Forbidden","details":{"name":"skypilot-service-account-cluster-role","group":"rbac.authorization.k8s.io","kind":"clusterroles"},"code":403}
```
This PR adds the necessary permissions required by skypilot.
> [k8s] Update generate_kubeconfig.sh

- sky/client/cli/command.py
- sky/utils/command_runner.py
Testing: initialized a skypilot repo under a filepath that contains a space, try launching a k8s cluster and ssh into the cluster.
Before: launch / ssh fails
with PR: launch / ssh succeeds
> Escape filepaths that may contain a space

- sky/server/requests/executor.py
- sky/server/requests/process.py
- sky/server/server.py
- tests/unit_tests/test_sky/server/requests/test_process.py
This PR fixes an issue that a disrupted executor process will break the entire process pool:
- **Previously**: when a executor process exited (e.g. OOM killed), the entire process will be broken and neither user requests nor background daemons can proceed;
- **PR**: when the pool is broken, rebuild a new pool to replace the broken pool. Background daemon and retryable request will be retried.
User will see the following logs when this issue happens:
```
Error processing request: [...] [concurrent.futures.process.BrokenProcessPool[] A child process terminated abruptly, the process pool is not usable anymore
```
Test:
```bash
$ kill -9 14749
$ cat  ~/.sky/api_server/server.log
...
Process SpawnProcess-442:
Process SpawnProcess-448:
Process SpawnProcess-444:
KeyboardInterrupt …
```
> [API server] Rebuild broken pool

- docs/source/reference/config.rst
Resolves #6249 
1. Fix the format issues on nebius config examples - following the other cloud specific examples, I removed the reference links.
2. change `ssh_proxy_command` example to specify a map, not both a string and a map (which is invalid format)
3. add description for `tenant_id`
> Fix nebius config docs

- sky/adaptors/nebius.py
- sky/catalog/data_fetchers/fetch_nebius.py
- sky/setup_files/dependencies.py
Upgraded the Nebius dependency to version 0.2.37 and introduced a new data-fetching module to retrieve and process Nebius VM pricing. Added relevant API adaptations to support billing operations and output pricing data to CSV.
> [Nebius] Add fetch_nebius.py

- sky/clouds/hyperbolic.py
- sky/provision/hyperbolic/__init__.py
- sky/provision/hyperbolic/instance.py
Fix prevent cleanup_custom_multi_network error during Hyperbolic cluster teardown
**Problem**
`sky down` on Hyperbolic clusters was calling `cleanup_custom_multi_network()` and failing with `NotImplementedError` because Hyperbolic didn't declare this feature as unsupported.
**Solution**
- Added `CUSTOM_MULTI_NETWORK` to Hyperbolic's unsupported features list
- Implemented cleanup_custom_multi_network() function for proper routing
- Added necessary import in __init__.py
> [Hyperbolic] fix: mark `CUSTOM_MULTI_NETWORK ` un-supported

- sky/catalog/common.py
- tests/unit_tests/test_catalog.py
When a new catalog file is fetched, there might be a difference for the catalogs among different executor processes, despite there being a single source of truth, on disk at `~/.sky/catalogs/*`.
TL;DR this is because `read_catalog` returns a `LazyDataFrame`, which gets assigned to a global variable, for each unique (cloud, catalog) pair. And `LazyDataFrame`  caches the DataFrame in memory for the duration of the process' lifetime, because it only calls `update_func` if `self._df` is None, which is only when it's first called.
This PR changes the behaviour of `LazyDataFrame`, such that now, `update_if_stale_func` returns a bool, that indicates if an update was done or not, and this is called on every read (`_load_df`), to ensure that a long running executor process is aware if it is time …
> Make sure catalogs get updated periodically on the executor processes

- sky/__init__.py
This was missing before. This allows users to do `import sky; sky.api_login()` instead of having to write like `from sky.client import sdk; sdk.api_login()`.
> Add api_login to sky module

- tests/test_optimizer_dryruns.py
https://cloud.google.com/compute/docs/general-purpose-machines N4 is cheaper and usually more efficient, so our optimizer start to choose N4 after the latest catalog update:  https://github.com/skypilot-org/skypilot-catalog/commit/4c4ffa869c8aa28550323ca992ce9cf873d771db
This PR fix the relevant UT.
There is also a bug of optimizer I think, which is workarounded in this UT fix to unblock the CI first: https://github.com/skypilot-org/skypilot/issues/6290
> Fix optimizer UT

- tests/unit_tests/test_hyperbolic.py
The `1x-T4-4-17` instance type were missing in the latest catalog ([commit](https://github.com/skypilot-org/skypilot-catalog/commit/06cb4087855609446f3ce9739d863ffd92cdbcd6)), causing this unit test to fail, as it's explicitly looking for that type.
This PR fixes it by switching to a valid instance type which exist on the latest catalog.
We probably should still investigate though why `1x-T4-4-17` went missing.
> Fix hyperbolic unit test

- sky/client/sdk.py
backends package is only used during type checking. Move the import statement to execute during type checking only.
> [SDK] Import backends during type checking only

- sky/utils/db/migration_utils.py
https://github.com/skypilot-org/skypilot/pull/6196 causes db lock path to be created in a literal "~" directory within the pwd. This changes fixes this bug.
> [db] fix db lock paths

- sky/backends/backend_utils.py
Sometimes for `sky status` for a remote api server, it checks the network connection by pinging endpoints. It tests two endpoints with 3 retries each for a three second timeout. This means that `https://1.1.1.1` is tested for 9 seconds before testing google's endpoint `https://8.8.8.8`. This PR swaps the order (google's endpoint first) and then the timeout is reduced to 1s instead of 3s. This was tested without any jobs running.
> [Perf] Remote API server checking network connection times out slowly

- sky/client/cli/command.py
- sky/client/sdk.py
Fixes #6308 
When local api server is not up and we call `sky api status`, we show the same log as when we call `sky api stop` in the same situation.
** note this pr is only relevant for **local** api server. hence, the check for whether the server is configured to be local. 
> [UX] better logs for `sky api status` when local api server is not running

- sky/skylet/constants.py
> change constants to use correct lock dir

- examples/api-deploy-gke-nebius-okta/README.md
> [Docs] Update nebius to use `network_tier` instead of suggesting to set env

- sky/client/cli/command.py
- sky/client/sdk.py
- sky/utils/common_utils.py
Fixes #6326 
As a follow up, it is important to REMOVE ALL SESSIONS AND REVOKE ANY OAUTH2 TOKENS. The motivation of this PR is to logout so to enable users to easily switch between local/remote api servers, to change server urls without modifying `config.yaml`. However, from a security standpoint, this would cause a session leak. 
> [UX] implement `sky api logout`

- sky/client/sdk.py
> Fixed sky api login when local one is running

- sky/global_user_state.py
- sky/jobs/state.py
- sky/utils/db/migration_utils.py
This PR fixes and issue where adding new alembic revisions breaks backwards compatibility. 
The issue was that when a new PR adds a new revision #{x+1}, the db gets initialized at that revision #. Then when master gets checked out (assuming master is set to use revision #{x}, an error would get thrown, causing the api server to fail to start because when alembic tries to "upgrade" to revision #{x} it checks the current version of the db which is at #{x+1} which it does not recognize. 
This PR adds a check before upgrading the database such that the db only gets upgraded if the current version of the database either does not exist (pre-alembic) or is older than the desired version. 
> [db] Alembic fix new revisions backwards compatibility

- sky/utils/config_utils.py
Currently, we're printing the incompatibility logs if the nebius config being searched for does not exist in the new region config location. However, it is possible the config being searched for does not exist anywhere, because the user didn't set them. This is not a case of user still using the old configuration format, so we should not be printing the deprecation notice in that case.
> [nebius] suppress superflous nebius config logs

- sky/admin_policy.py
This fixes an error where managed jobs will fail to be correctly added to the `spot` database on the jobs controller when a RESTful admin policy is in use.
> preserve task.managed_job_dag in RESTful admin policy

- charts/skypilot/values.yaml
- docs/source/reference/api-server/helm-values-spec.rst
Clarify the default image strategy, so that the helm chart and our python code are consistent by default.
Note that there is no exact consistency when user install the chart from source since we do not release image for every commit, in this case, the closest version is used by default (`skypilot-nightly:latest`)
> Update default image of the helm chart

- docs/source/reference/api-server/api-server-admin-deploy.rst
- docs/source/reference/api-server/examples/example-deploy-gcp-cloud-sql.rst
Note: `extraVolumes` field doesn't seem to be supported yet, so this doesn't work with nightly helm chart yet. To merge once the latest nightly helm chart supports `extraVolumes` field.
Tested by going through the steps manually.
Docs: https://docs.skypilot.co/en/gke-sql-tutorial/reference/api-server/examples/example-deploy-gcp-cloud-sql.html
> [Docs] Tutorial to deploy API server on GKE with Cloud SQL

- docs/source/reference/config.rst
- sky/backends/backend_utils.py
- sky/templates/aws-ray.yml.j2
- sky/utils/schemas.py
- tests/test_yamls/test_aws_config_runcmd.yaml
- tests/unit_tests/test_backend_utils.py
This PR adds a new config for AWS, called `post_provision_runcmd`, for running custom commands during the final boot stage, right after the instance starts.
Under the hood, for AWS we're already passing a cloud-init cloud config YAML (see [aws-ray.yml.j2](https://github.com/skypilot-org/skypilot/blob/master/sky/templates/aws-ray.yml.j2)) to the UserData of the EC2 instance we're provisioning. So to pass in the commands from the user's config, we just need to append it as is under the [runcmd](https://cloudinit.readthedocs.io/en/latest/reference/modules.html#runcmd) field to the existing cloud-config.
Why this is needed: One of our users met an issue where MitM cert needs to be installed on the EC2 instance with the UserData / runcmd during the provisioning. The user tried installing the …
> [AWS] Add post_provision_runcmd config for running commands during final boot stage

- sky/utils/db/migration_utils.py
The helptext for `set_section_option` says:
```
:param value: the value. Note that this value is passed to
ConfigParser.set, which supports variable interpolation using pyformat (e.g. %(some_value)s). A raw percent sign not part of an interpolation symbol must therefore be escaped, e.g. %%. The given value may refer to another value already in the file using the interpolation format.
```
We add escape for '%' value (which may be used on URL escapes) to make sure this value is being handled correctly.
> [db] interpolation fix for alembic migration

- sky/global_user_state.py
- sky/jobs/state.py
- sky/server/server.py
- sky/utils/db/migration_utils.py
This PR deterministically initializes the global user state db when starting the api server. This is an improvement from the current method of db initialization where many processes may race to initialize the global user state db, creating lock contention. 
This PR also refactors the way that global user state db and the jobs state db get initialized, further reducing lock contention by checking if a db upgrade is necessary before trying to acquire the lock as well as after in case another process upgraded the db while the current process was waiting for the lock. 
The refactor also significantly improves readability of the db initialization code for the global user state and job state databases, making it easier to reason about. 
> [db] single init global user state, refactor migrations

- sky/templates/aws-ray.yml.j2
- sky/templates/azure-ray.yml.j2
- sky/templates/do-ray.yml.j2
- sky/templates/lambda-ray.yml.j2
- sky/templates/nebius-ray.yml.j2
- sky/templates/paperspace-ray.yml.j2
- sky/templates/runpod-ray.yml.j2
Fixes #6363, related to #6356
GCR/GAR docker passwords are json files. Previously, such multi-line passwords were only supported for GCP. This PR introduces support to the rest of the relevant clouds.
> [GCR][Docker] Support Multi-Line Docker Password for All Relevant Clouds

- sky/backends/backend_utils.py
This PR fixes an issue where launch command using `--retry-until-up` sometimes fails after a retry due to the error
```
AssertionError: Trying to launch cluster '<cluster-name>' recently terminated on the cloud, but the handle is not a CloudVmRayResourceHandle (None).
```
This error is caused by https://github.com/skypilot-org/skypilot/pull/5556. In this PR, the worker process yields on retry instead of busy-waiting on an executor. Notably, before this PR, the while loop that busy-waits the request has the `to_provision_config` declared and constant, whereas after the PR the `to_provision_config` is calculated on every retry attempt.
From my understanding, `to_provision_config` is only calculated when the optimizer runs, and the optimizer does not run if the cluster record already exists …
> [core] do not refresh cluster[s] that has an active request associated with it

- Dockerfile
- tests/conftest.py
- tests/smoke_tests/docker/Dockerfile_test
- tests/smoke_tests/smoke_tests_utils.py
- tests/smoke_tests/test_cluster_job.py
- tests/smoke_tests/test_managed_job.py
- tests/smoke_tests/test_volume_mount.py
Reduce docker image size by:
- Install google-cloud-sdk via multi-stage build
- Replace the base image with `python:3.10-slim`
The image size for installing from wheel package is reduced from 4.13GB to 2.64GB, about 36% decrease.
- Local smoke test for gcp (partial cases)
- gcloud command line operations in API server container
- Launch a cluster on GKE with remote API server
> [Core] Reduce docker image size

- sky/backends/backend_utils.py
- sky/exceptions.py
- tests/smoke_tests/test_cluster_job.py
Fixes #5946 
Context: 
When we refresh a cluster's status, either every 60s (through `skypilot-status-refresh-daemon`) or `sky status --refresh`, we check the status of the nodes using the cloud APIs, and also the status of the Ray cluster. And if it's "abnormal", as defined here: https://github.com/skypilot-org/skypilot/blob/de717752a6e06b3f1c154da25f6c00dd07780d9b/sky/backends/backend_utils.py#L2138-L2153
We cancel the autostop, because we cannot guarantee that autostop will happen correctly, as the Ray cluster is probably down in this case.
But this code path was written back when deprovisioning/stopping of clusters were done through Ray, and not the cloud APIs. Now that we're using cloud APIs invoked through skylet, which runs on the head node, we can improve this. Now, the property …
> [Core] Don't reset autostop/down for abnormal clusters if head node is still alive

- .github/workflows/release-build.yml
Resolve #5447
Tested in my personal repo:
https://github.com/zpoint/skypilot/pull/80
> Test two minor version for backward compatiability during release

- tests/smoke_tests/test_cluster_job.py
> Fix `test_autostop_with_unhealthy_ray_cluster` failure

- sky/logs/agent.py
- sky/logs/aws.py
- tests/unit_tests/test_sky/logs/test_aws.py
Removing fallback for cloudwatch logs, wasn't super useful as the logs are already just written to disk. Caused issues for some setups.
Fixed `tests/unit_tests/test_sky/logs/test_aws.py` to match new behaviour.
> Remove fallback for cloudwatch logs

- sky/server/server.py
Skip basic auth for /api/health only, which is required for health check in kubelet
- Curl /api/health succeeds without credentials
-  `sky api status/logs/cancel` requires credentials
> [Auth] Skip basic auth for /api/health only

- sky/logs/aws.py
Changing the metadata check to read the `AWS_EC2_METADATA_ENDPOINT` env var, so users can change the exact endpoint they use to check for if they can use a role.
Tested this on a setup with a non-default endpoint
> [external logs] Add ec2 metadata env var for cloudwatch logs

- sky/global_user_state.py
- sky/jobs/state.py
There is a rare race condition in the db initialization code where two threads may call `_init_db()` at the same time, thread one sets the global `_SQLALCHEMY_ENGINE` to "e1", and then creates a session `with orm.Session(_SQLALCHEMY_ENGINE) as session:` and begins performing some operations on the db. Then, thread two modifies the global `_SQLALCHEMY_ENGINE` to "e2", resulting in "e1" being garbage collected due to a lack of strong references. 
This PR addresses this issue by adding a thread lock around the global `_SQLALCHEMY_ENGINE` initialization, ensuring that only a single thread within a process ever sets the value.
This PR was manually tested by deleting the `~/.sky` folder, restarting the api server, and testing the cluster lifecycle.
> [db] make engine definition thread safe

- sky/clouds/nebius.py
Noticed this when doing `sky check nebius`:
```bash
% sky check nebius
Checking credentials to enable infra for SkyPilot.
Nebius: disabled
Reason [compute]: Copy your tenat ID from the web console and save it to file
$ echo $NEBIUS_TENANT_ID_PATH > ~/.nebius/NEBIUS_TENANT_ID.txt
Or if you have 1 tenant you can run:
...
```
> [UX] Fix typo in Nebius' missing tenant ID message

- sky/client/common.py
- tests/smoke_tests/test_sky_serve.py
```
secrets:
HF_TOKEN:
VLLM_API_KEY:  # Provide value at launch time that will be used as API key for the service
service:
readiness_probe:
path: /v1/models
headers:
Authorization: Bearer $VLLM_API_KEY
replicas: 1
tls:
keyfile: ~/skypilot-dev/test-key.pem
certfile: ~/skypilot-dev/test-cert.pem
resources:
ports: 8080
workdir: ~/skypilot-dev/examples
setup: |
uv venv
uv pip install vllm
run: |
uv run python -m vllm.entrypoints.openai.api_server \
--tensor-parallel-size $SKYPILOT_NUM_GPUS_PER_NODE \
--host 0.0.0.0 --port 8080 \
--model mistralai/Mixtral-8x7B-Instruct-v0.1 \
--api-key "$VLLM_API_KEY"
```
Master: `ValueError: File mount source '/root/.sky/api_server/clients/xxx/file_mounts/~/skypilot-dev/test-key.pem' does not exist locally. To fix: check if it exists, and correct the path.` …
> [Serve] Fix TLS key files upload path

- sky/client/common.py
- sky/server/server.py
This PR addresses two issues:
1. Service account token is not added for `/upload` API
2. `/upload` should use the authed user_id 
> Fixed service account token auth in upload

- llm/llama-4-finetuning/llama-4-maverick-lora.yaml
- llm/llama-4-finetuning/llama-4-maverick-sft.yaml
- llm/llama-4-finetuning/llama-4-maverick.yaml
- llm/llama-4-finetuning/llama-4-scout-sft.yaml
- sky/provision/nebius/constants.py
- sky/resources.py
This PR adds a default image when `network_tier: best` is selected on nebius for infiniband. Otherwise, infiniband will not be used
> [Network] Add specific image for infiniband on nebius

- sky/catalog/data_fetchers/fetch_aws.py
> fix AWS catalog fetcher with fractional L4s (g6f/gr6f)

- sky/users/server.py
This was intended to be 16 random chars, but due to how secrets.token_hex works, it was actually 32, for a total user_id length of 35 chars (too long!).
This was causing SSH to give the error `unix_listener: path "/tmp/skypilot_ssh_blahblahblah" too long for Unix domain socket`. Since we construct the ControlPath including the user_id, the length was contributing to the problem.
Confirmed that we don't see the unix_listener error after shortening the SA user_id.
> fix service account user_id length

- sky/skypilot_config.py
- sky/utils/db/migration_utils.py
Our config gets printed in many places for debugging purposes.
The db connection string, which could be set on the API server config file or as an environment variable, is a sensitive value that should not be logged. The current design puts the db connection string into the config, which gets printed for debugging purposes, leaking the connection string to the logs. We would like to avoid that.
Trying to track down every place the config is used and patching the code to not print db is impractical. Trying to change the print function to somehow not print the db value is also impractical, as that would involve somehow patching `logger.info/debug` or `print` functions which SkyPilot does not own.
The simplest way to make sure the db string is not printed when config is printed to make sure …
> do not include db info in config after parsing

- tests/test_config.py
Add a unit test to better clarify the behavior when a per-context config is mutated (e.g. within admin policy)
> [config] test config mutation in per context config

- sky/catalog/__init__.py
- sky/catalog/common.py
Resolves the following error with `tests/test_optimizer_random_dag.py::test_optimizer`:
```
tests/test_optimizer_random_dag.py:183: in test_optimizer
compare_optimization_results(dag, minimize_cost=True)
tests/test_optimizer_random_dag.py:154: in compare_optimization_results
optimizer_plan = sky.Optimizer._optimize_dag(dag,
sky/optimizer.py:1107: in _optimize_dag
Optimizer._estimate_nodes_cost_or_time(local_topo_order,
sky/optimizer.py:298: in _estimate_nodes_cost_or_time
resource_hints) = (_fill_in_launchable_resources(
sky/optimizer.py:1356: in _fill_in_launchable_resources
feasible_list = subprocess_utils.run_in_parallel(
sky/utils/subprocess_utils.py:131: in run_in_parallel
return [func(args[0])]
sky/optimizer.py:1358: in <lambda>
(cloud, cloud.get_feasible_launchable_resources(r, …
```
> allow float AcceleratorCount in catalog/optimizer

- sky/catalog/aws_catalog.py
- sky/catalog/data_fetchers/fetch_aws.py
This PR restores `eu-south-2` availability. It was previously disabled due to the lack of DL AMIs, which are now available.
As discussed on [Slack](https://skypilot-org.slack.com/archives/C03J2KQQZSS/p1753903697396199?thread_ts=1753843339.363879&cid=C03J2KQQZSS), I also added the latest generations to the list of default instance families because `eu-south-2` does not carry the older ones (though it has some variants like `m6in`).
* I generated new `az_mappings.csv` and `vms.csv` with:
```
python sky/catalog/data_fetchers/fetch_aws.py
```
* I replaced the files in my `.sky/catalogs/v7/aws` with the newly generated files
* I launched a cluster with a basic YAML config (just running nvidia-smi on L4)
* I verified that the nvidia-smi output was as expected
``` …
```
> Enable AWS eu-south-2 region

- sky/provision/runpod/utils.py
- tests/smoke_tests/test_cluster_job.py
Partially addresses #6430.
Previously, we only had GPU instances in the Runpod catalog, and so the Runpod provisioner code we had only supported launching GPU instances.
But with https://github.com/skypilot-org/skypilot-catalog/pull/140, we're adding CPU instances for Runpod to the catalog. 
Useful reference for the parameters supported by `runpod.create_pod`: https://github.com/runpod/runpod-python/blob/84654b9ad6afeeda20f7218094c4692a177779b6/runpod/api/ctl_commands.py#L89-L142
Note: For CPU instances, the maximum [Container volume](https://docs.runpod.io/pods/storage/types#container-volume) size is 10x the number of vCPUs. I couldn't find the documentation for this, but I hit this during my testing.
Manual tests:
1. `sky launch --infra runpod` launches `cpu3c-2-4` by default (cheapest) …
> [Runpod] Refactor provisioner to support launching CPU instances

- sky/client/cli/command.py
Without this fix, `sky status` will error out from the pools request, instead of just skipping the pools.
```
cooperc@crispy ~> sky status
sky.exceptions.APINotSupportedError: Function pool_status is introduced after the remote server version '1.0.0-dev0 (commit: {{SKYPILOT_COMMIT_SHA}})' is released. Please upgrade the remote server.
```
> don't show pools on old remote API server

- .github/workflows/release-build.yml
We have an error in [release pipeline](https://github.com/skypilot-org/skypilot/actions/runs/16662669238/job/47163010425):
```bash
Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.10.18/x64
LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.10.18/x64/lib
UV_PYTHON: 3.10
UV_CACHE_DIR: /home/runner/work/_temp/setup-uv-cache
/home/runner/work/_temp/c5b9fa87-6e19-4258-bbfb-2c40ef3b00b0.sh: line 15: [: API_VERSION = 12: integer expression expected
Incrementing from 0.10.0 to 0.11.0
```
Before:
```bash
zpoint:~/codes/skypilot (master)$ grep "^API_VERSION = " sky/server/constants.py | sed "s/API_VERSION = '\\(.*\\)'/\\1/"
API_VERSION = 12
```
After:
```bash
zpoint:~/codes/skypilot (master)$ grep "^API_VERSION = " sky/server/constants.py | awk '{print $3}'
12
```
> Fix release pipeline API version extract error

- tests/smoke_tests/test_cluster_job.py
Resolve #6465
The optimized setting seems to have changed the default instance type. Previously, we didn't specify the launch instance type and assumed the optimizer would choose `n2-standard-2`, then we used the gcloud command to filter based on this instance type.  
Now we'll specify the instance type in the launch command.  
> Fix `test_gcp_disk_tier` failure

- .github/workflows/release-build.yml
Remove sky API version check, always bump up patch version. No bump up for minor version.
Test in my [personal repo](https://github.com/zpoint/skypilot/actions/runs/16670578155/job/47185728499)
> Remove minor version bump for release

- sky/dashboard/src/components/clusters.jsx
http://127.0.0.1:46580/dashboard/clusters?history=true
so that browser nav doesn't lose the toggle state.
> [UI] Clusters: make history toggle part of URL.

- sky/catalog/data_fetchers/fetch_nebius.py
- sky/setup_files/dependencies.py
Nebius introduced spot-like instances called Preemtible VMs. This PR upgrades the pricing fetcher to support new types of instances.
-  local run generated spot pricing in SpotPrice column for existing catalog lines.
> Add spot pricing for Nebius

- sky/catalog/data_fetchers/fetch_nebius.py
Fix bad spec generating for Nebius spot pricing.
> Fix wrong spec for Nebius spot pricing

- sky/backends/cloud_vm_ray_backend.py
- sky/client/cli/command.py
- sky/client/cli/flags.py
- sky/client/sdk.py
- sky/client/sdk.pyi
- sky/core.py
- sky/execution.py
- sky/resources.py
- sky/server/constants.py
- sky/server/requests/payloads.py
- sky/skylet/autostop_lib.py
- sky/skylet/events.py
- tests/unit_tests/test_controller_utils.py
- tests/unit_tests/test_resources.py
This PR fixes backwards compatibility issues introduced in #6361, by following https://github.com/skypilot-org/skypilot/blob/master/CONTRIBUTING.md#backward-compatibility-guidelines.
1. New client <-> old server errors with
```
% sky launch --infra aws -i 10
sky.exceptions.InvalidSkyPilotConfigError: Invalid resources YAML: {'idle_minutes': 10, 'down': False, 'wait_for': 'jobs_and_ssh'} is not valid under any of the given schemas. Check problematic field(s): $.autostop
```
This is because in `resources.AutostopConfig`, `wait_for` got serialized on the client, but the server does not recognize because it's still using the old schema
2. Old client <-> new server errors with
```
% sky autostop -i 20 mycluster
...
request_task = requests_lib.Request.decode( …
```
> [Refactor] Fix backwards compatibility issues introduced by `wait_for` Autostop config

- sky/backends/backend_utils.py
- sky/provision/kubernetes/utils.py
- sky/skylet/constants.py
Allow `config.kubernetes.custom_metadata` overrides to let users set annotations. Required on certain clouds to set args for loadbalancers when opening ports, scraping pods for metrics etc. 
More generally - we should look into fixing #5585 so we don't require allow listing like this.
> [config] Allow `config.kubernetes.custom_metadata` overrides in task

- sky/client/cli/command.py
In the previous code, `versions.get_remote_api_version()` will always be `None` because we haven't yet run `check_server_healthy_or_start` at this point.
Calling `check_server_healthy_or_start` earlier in the `status` command would probably slow things down.
Instead, just catch the incompatible API exception and skip the pools display in this case.
> [pools] fix backwards compatibility detection in `sky status`

- sky/client/cli/command.py
- tests/unit_tests/test_sky/test_cli_infra_override.py
closes #5821 
This PR fixes the issue of infra override flag '*'. Now infra flag set to '*' will always takes precedence.
* Add special handling for `*` and always return with fields set to `*` for `InfraInfo` object.
* Ensure `*` is properly propagated through the override dictionary.
* Added unit test for this use case
Unit test
Case 1 - `--infra *` **Highest Priority**
* `*` takes precedence, it ignores any yaml settings and is the same as not setting any preference for cloud, region and zone
Case 2 - `--cloud *`or `--region *` or `--zone *`
* In this case, we set respecting field to None in the infraInfo object. Consequently, it's still respecting the yaml file config.
* Example: if yaml file set cloud to aws and the cli is called with `--cloud *`, we still use aws as the cloud …
> [Bug] Fix infra override to ensure * takes precedence

- sky/dashboard/src/components/infra.jsx
- sky/dashboard/src/data/connectors/infra.jsx
This PR addresses issue [6470](https://github.com/skypilot-org/skypilot/issues/6470) where newly added credentials were not being "discovered" by the dashboard until the user ran `sky check`. If a user is clicking the refresh button or hard refreshing the page with cmd/ctrl+r, we should respect their intent and run `sky check` to pick up on newly added/removed credentials.
This PR was tested by manually adding and removing clouds from the `allowed_cloud:` section of the global sky config yaml and verifying that the updates show up in the dashboard on refresh. This is in comparison to the previous behavior where the dashboard would not pick up on the change until the user runs `sky check`. 
> [dashboard] sky check on infra page hard refresh

- tests/smoke_tests/test_sky_serve.py
The HTTPS support on the kind cluster seems problematic, causing release 0.10.1 to [fail](https://buildkite.com/organizations/skypilot-1/pipelines/full-smoke-tests-run/builds/50/jobs/01987482-413a-4905-993f-b66df5d5d4b0/log).  
The `resource_heavy` mark was accidentally removed in #6423 - we should add it back so the test runs on the EKS cluster instead of the kind cluster.
> Fix `test_skyserve_https` failure

- sky/clouds/kubernetes.py
- sky/provision/kubernetes/utils.py
- tests/unit_tests/kubernetes/test_instance_type.py
`sky launch --gpus H100_NVLINK_80GB:1` would not work on CoreWeave clusters because SkyPilot converted underscores to spaces during parsing, breaking name matching (`H100_NVLINK_80GB` would become `H100 NVLINK 80GB` -> match fail). This was breaking H100 support on CW:
```
(py310) ➜  sky-experiments git:(cw_fix_h100) ✗ sky show-gpus --infra k8s
GPU label cloud.google.com/gke-accelerator matched for label formatter type, but has invalid value H100_NVLINK_80GB. Reason: Invalid accelerator name in GKE cluster: H100_NVLINK_80GB. Skipping...
GPU label cloud.google.com/gke-accelerator matched for label formatter type, but has invalid value H100_NVLINK_80GB. Reason: Invalid accelerator name in GKE cluster: H100_NVLINK_80GB. Skipping...
Kubernetes GPUs
Context: sky-dev
GPU …
```
> [k8s] Fix GPU name matching w/ underscores

- sky/client/sdk.py
The function signature/docstring of get makes it seem like the request_id must be the full request ID. 
In reality, all functions that takes in a request ID as an argument work even if the request ID is a prefix of a full request ID.
Modify the docstring to make this fact clear.
> [sdk] specify request ID can be prefix

- sky/catalog/nebius_catalog.py
- sky/clouds/nebius.py
- sky/provision/nebius/instance.py
- sky/provision/nebius/utils.py
- sky/setup_files/dependencies.py
- sky/templates/nebius-ray.yml.j2
- tests/smoke_tests/test_cluster_job.py
- tests/smoke_tests/test_managed_job.py
- tests/smoke_tests/test_sky_serve.py
Add support for GPU-based spot instances
`sky launch -c t-minimal-2d --use-spot --gpus H100 --cloud nebius  tests/test_yamls/minimal.yaml`
> [Nebius] Add support for GPU-based spot instances

- sky/skylet/log_lib.py
- sky/templates/kubernetes-ray.yml.j2
This PR makes rich progress bars (like tqdm) render properly in the skypilot client-side for skypilot jobs launched on kubernetes. 
We had some ray patches to override their handling of `\r`, but they were only being applied to cloud vms, not kubernetes. This PR applies these patches to ray when launching skypilot clusters on kubernetes.
This PR was tested by running a test script that runs a basic for loop wrapped by tqdm. I verified that the tqdm progress bar shows up in a single line rather than the previous "pyramid" behavior. 
> [UX] rich progress bar support on k8s

- sky/server/daemons.py
- sky/server/server.py
Tested with only jobs consolidation mode and the serve refresh event is skipped. the cpu usage also becomes normal now.
> [API Server] Fix busy loop when consolidation mode is disabled

- charts/skypilot/templates/oauth2-proxy-deployment.yaml
- charts/skypilot/tests/oauth2_test.yaml
Fixed helm templating for OAuth when new config is not set under `auth.oauthn`
> Fixed helm template for oauth

- sky/client/cli/command.py
Fixes #6508.
See #6508 and #6509 for details.
This PR is an alternative approach that aims to keep all the `show_gpus` behavior the same as before. The special `'*'` value was intended to interact only with the task overrides, and the effect on `show_gpus` was unintentional. So this will revert to the previous behavior for `show_gpus`.
> fix '*' handling in show_gpus

- sky/skylet/ray_patches/__init__.py
- sky/templates/kubernetes-ray.yml.j2
This PR addresses issue [6540](https://github.com/skypilot-org/skypilot/issues/6540) where sky launching a cluster on `--infra k8s` with a docker image fails because we try to apply the ray patches before the `patch` command has been installed. This happens because the k8s provisioning runs multiple steps in parallel. 
This PR was tested by manually running `sky launch -y -c t-docker-storage-15-d7 --infra kubernetes --cpus 2+ --memory 4+ --image-id docker:continuumio/miniconda3:24.1.2-0` which hangs on master due to the `patch` command not being installed, but runs successfully on this branch.
> fix patch installation on docker image

- sky/backends/cloud_vm_ray_backend.py
Adds a timeout to the cluster lock acquired during provisioning to enable notification to the user of the reason for hang.
Fixes #5689
> [UX] Add lock timeout to notify user

- tests/smoke_tests/test_sky_serve.py
Fixes #6539.
Before, `--infra` flag would not override all of cloud/region/zone. After #6392, it will override all three, even if only one is specified. (So `--infra gcp` means "GCP, any region", even if there is a region specified in the YAML.)
Since the region info is specified in the YAML, the CLI `--infra gcp` flag is not needed. So we just remove it.
> [test] fix test_skyserve_dynamic_ondemand_fallback failure

- charts/skypilot/Chart.yaml
Upgrade the default ingress-nginx version in favor of https://github.com/kubernetes/kubernetes/issues/131009
4.11.8 release note: https://github.com/kubernetes/ingress-nginx/releases/tag/helm-chart-4.11.8
> Helm: upgrade ingress-nginx to 4.11.8

- sky/schemas/db/global_user_state/003_fix_initial_revision.py
- sky/schemas/db/global_user_state/003_fix_initial_schema.py
- sky/utils/db/db_utils.py
- sky/utils/db/migration_utils.py
There are a few issues with the initial alembic revision for global user state:
There are a few columns missing (in the schema, not in the revision):
- storage_mounts_metadata
- cluster_ever_up
- status_updated_at
There are a few extra columns (not in the schema, in the revision):
- launched_nodes
- disk_tier
- config_hash_locked
- handle_locked
- num_failures
- configs
The missing columns are critical to add because while they are missing, there is a potential for someone who initialized their db prior to those columns being added, trying to upgrade to a new version of the db and will not see those columns show up. The exact user impact should be minimal because the most recent of the missing columns is 9 months ago, so only users who are currently running a db older than 9 months and …
> [DB] fix initial alembic revision for global user state clusters table

- sky/jobs/client/sdk.py
- sky/server/constants.py
> [Pool][API Server] Fix API server version requirements for pool logs sdk

- sky/dashboard/src/data/connectors/clusters.jsx
- sky/dashboard/src/data/connectors/jobs.jsx
This PR adds log tailing for cluster jobs (managed jobs already had log tailling) and bumps up the tail limit to 10,000 instead of 1000. 
Tailing is necessary because if we stream the entire logs, the dashboard can crash (this can be reproduced by generating a log file of 100,000 lines).
Note:
This PR will be followed by further improvements to the log rendering in the dashboard. The first improvement will be a download button which allows users to download the full log file if they so choose.
Ran a bash script to print 100,000 lines and verified that only the last 10,000 lines showed up in the dashboard.
> [Dashboard] Cluster & managed jobs log tailing

- sky/dashboard/src/hooks/useTour.js
The frontend tour was not displaying for first-time visitors after #6473. This was caused by an overly aggressive ESLint dependency fix in `useTour.js`.
In `sky/dashboard/src/hooks/useTour.js` line 1729, the `useEffect` dependency array was changed from `[isFirstVisit]` to `[isFirstVisit, markTourCompleted, router, tourAutoStarted]`. This created a problematic dependency cycle:
- When `isFirstVisit` is true, the effect runs and calls `startTour()`
- `startTour()` sets `setTourAutoStarted(true)`
- This causes the `useEffect` to re-run because `tourAutoStarted` changed
- But now `tourAutoStarted` is already true, so the condition `if (isFirstVisit && !tourAutoStarted)` fails
- The tour never starts
Reverted the dependency array back to `[isFirstVisit]` only. This restores the original logic …
> Restore frontend tour functionality

- tests/test_api_compatibility.py
Fixing https://github.com/skypilot-org/skypilot/actions/runs/16816637819/job/47634899714?pr=6571
Previously the order of Union type will break the test. This pr fixes it.
```bash
master=typing.Union[int, str, NoneType] != current=typing.Union[str, int, NoneType]
```
> [Tests] Fix endpoint comparison in unittests

- sky/backends/cloud_vm_ray_backend.py
Addresses following comments https://github.com/skypilot-org/skypilot/pull/6530#discussion_r2261296452.
Tweaked the delay message when waiting to grab the cluster lock to happen in the spinner message instead of a standalone message. Also changed "tasks" in message to "requests".
This PR was tested by launching two sky launch requests simultaneously to the same cluster and verifying that the later request displays the desired "Launching delayed" message in the spinner.
> [UX] Move delay message into spinner

- sky/adaptors/kubernetes.py
When running SkyPilot from within a Kubernetes pod using in-cluster authentication, the current code unconditionally overwrites the `KUBERNETES_SERVICE_HOST` and `KUBERNETES_SERVICE_PORT` environment variables with hardcoded values. Some clusters may not use these defaults.
This PR updates the logic to use existing values if present.
> [k8s] Fix in-cluster `KUBERNETES_SERVICE` env var parsing

- sky/backends/backend_utils.py
- sky/backends/cloud_vm_ray_backend.py
- sky/core.py
- sky/execution.py
- sky/global_user_state.py
- sky/jobs/recovery_strategy.py
- sky/jobs/server/core.py
- sky/jobs/utils.py
- sky/provision/provisioner.py
- sky/schemas/db/global_user_state/005_cluster_event.py
- sky/utils/cli_utils/status_utils.py
- sky/utils/db/migration_utils.py
- tests/unit_tests/test_sky/utils/test_cli_utils.py
Added a cluster event table which keeps track of state transitions and events that happen. The goal of this is to provide more description to the user about why the cluster reaches certain states. This PR adds a column in sky status -v detailing the latest event that happened to a cluster to aid in debugging.
This PR was tested by starting an AWS cluster and then terminating one of the worker nodes, verifying that the "LAST_EVENT" column in sky status -v showed the various stages of the cluster (provisioning, launching instances, successfully reaching UP, returning to INIT due to worker termination). The attached image shows the output at the end of this process where the cluster returned to INIT.
The new column does cause line wrap in sky status -v which …
> [UX] Add cluster event table to explain state changes to user

- sky/backends/backend_utils.py
- sky/backends/cloud_vm_ray_backend.py
- sky/clouds/aws.py
- sky/provision/__init__.py
- sky/provision/aws/instance.py
- sky/provision/azure/instance.py
- sky/provision/cudo/instance.py
- sky/provision/do/instance.py
- sky/provision/fluidstack/instance.py
- sky/provision/gcp/instance.py
- sky/provision/hyperbolic/instance.py
- sky/provision/kubernetes/instance.py
- sky/provision/lambda_cloud/instance.py
- sky/provision/nebius/instance.py
- sky/provision/oci/instance.py
- sky/provision/paperspace/instance.py
- sky/provision/runpod/instance.py
- sky/provision/scp/instance.py
- sky/provision/vast/instance.py
- sky/provision/vsphere/instance.py
This change is a preparation for https://github.com/skypilot-org/skypilot/pull/6593 where `add_cluster_event` is called within `query_instances`. `add_cluster_event` requires the cluster name. Currently `query_instances` only has access to the cluster name on cloud, which is not the cluster name and there is no good way to derive cluster name from cluster name on cloud.
> pass in raw cluster name to `query_instances`

- sky/global_user_state.py
- sky/utils/cli_utils/status_utils.py
Co-authored-by: kyuds
References: PR #6609 and issue #6606.
This PR addresses the cluster record not being populated in functions that return these records. It also handles situations where the cluster event table might not exist for backwards compatibility.
> [Core] last_event not populated in cluster records

- sky/client/cli/command.py
This PR addresses an issue where running the command suggested by the hint during `sky launch` results in the following error:
```
❯ sky api logs -l sky-2025-08-11-13-29-04-142869/provision.log
RuntimeError: Failed to stream logs: Only one of request_id and log_path can be provided
```
Manually verified that with this PR the `sky api logs -l` command works out of the box during `sky launch`.
> [UX] fix api logs

- docs/source/getting-started/quickstart.rst
- sky/__init__.py
Extending #6561 to:
- sky exec
- sky stop/down
- sky jobs launch
**NOTE**: Because we don't actually expose the managed jobs sdk, I added it to sky `__init__.py`. Please review if my placement is appropriate, or lmk if there is another official way we import the sdk.
> [Docs] Add SDK Examples to QuickStart (2)

- docs/source/getting-started/quickstart.rst
- sky/__init__.py
Followup to https://github.com/skypilot-org/skypilot/pull/6597. Come to think of it, we should not just import big packages like this in sky willy nilly. Modify the quickstart to work with the change.
> undo import jobs in sky init

- docs/source/reference/config.rst
- sky/clouds/aws.py
- sky/templates/aws-ray.yml.j2
- sky/utils/schemas.py
- tests/test_yamls/test_aws_config_ssh_user.yaml
- tests/unit_tests/test_resources.py
Support customizing ssh user for aws
- Launch a cluster with `aws.ssh_user: test-user` in `config.yaml` 
- Launch a managed job with `aws.ssh_user: test-user` in `config.yaml` 
- Launch a cluster without setting `aws.ssh_user` in `config.yaml`
> [Core] Support customizing ssh user for aws

- docs/source/reference/api-server/api-server-admin-deploy.rst
Fixed the doc description about the default service scheme of ingress svc
> Fixed doc about helm ingress svc

- sky/global_user_state.py
- sky/serve/serve_utils.py
- sky/serve/service.py
> [Serve] Skip `core.down` on failed replica records

- sky/backends/backend_utils.py
- sky/backends/cloud_vm_ray_backend.py
- sky/clouds/aws.py
- sky/global_user_state.py
- sky/provision/__init__.py
- sky/provision/aws/instance.py
- sky/provision/azure/instance.py
- sky/provision/cudo/instance.py
- sky/provision/do/instance.py
- sky/provision/fluidstack/instance.py
- sky/provision/gcp/instance.py
- sky/provision/hyperbolic/instance.py
- sky/provision/kubernetes/instance.py
- sky/provision/lambda_cloud/instance.py
- sky/provision/nebius/instance.py
- sky/provision/oci/instance.py
- sky/provision/paperspace/instance.py
- sky/provision/runpod/instance.py
- sky/provision/scp/instance.py
- sky/provision/vast/instance.py
- sky/provision/vsphere/instance.py
- sky/utils/db/db_utils.py
If a k8s pod disappears, try to investigate the reason behind pod deletion by inspecting k8s events.
The hard part about the PR was that k8s events are only stored for an hour. Therefore, I add a mechanism to not clear the event out if the new event doesn't contain a meaningful status message (and previous event may have).
> [k8s] infer reason behind disappeared nodes from k8s events

- sky/backends/backend_utils.py
- sky/backends/cloud_vm_ray_backend.py
After #6574, which introduced `grpc` as a dependency, our GCP catalog fetcher started failing: https://github.com/skypilot-org/skypilot-catalog/actions/runs/16925022238 as `grpc` is not part of the dependency of our GCP extras.
```bash
File "/home/runner/.local/share/uv/python/cpython-3.10.18-linux-x86_64-gnu/lib/python3.10/runpy.py", line 187, in _run_module_as_main
mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
File "/home/runner/.local/share/uv/python/cpython-3.10.18-linux-x86_64-gnu/lib/python3.10/runpy.py", line 110, in _get_module_details
__import__(pkg_name)
File "/home/runner/catalogs-venv/lib/python3.10/site-packages/sky/__init__.py", line 83, in <module>
from sky import backends
File …
```
> [Core] Lazy import grpc

- sky/admin_policy.py
- sky/jobs/recovery_strategy.py
- sky/resources.py
- sky/serve/replica_managers.py
- sky/serve/server/impl.py
- sky/task.py
- sky/volumes/server/core.py
- sky/volumes/server/server.py
- tests/unit_tests/test_sky/volumes/test_core.py
- tests/unit_tests/test_sky/volumes/test_server.py
`import sky` statement in internal code imports a lot of (unnecessary) things at once, causing unnecessary circular import issues and overall making the codepath slower. Reduce the occurrence of `import sky` statements by importing more targeted modules whenever possible.
> Reduce occurance of import sky

- tests/unit_tests/test_controller_utils.py
- tests/unit_tests/test_dag.py
- tests/unit_tests/test_dag_utils.py
- tests/unit_tests/test_sky/server/test_sdk_types.py
- tests/unit_tests/test_sky/test_cli_git_repo.py
- tests/unit_tests/test_sky/test_task.py
- tests/unit_tests/test_sky/utils/test_cli_utils.py
We want to reduce the use of `import sky` unless necessary. This PR removes `import sky` from 7 test files. Further work will continue to reduce the use of `import sky` in the future.
> reduce use of import sky in test files (1)

- sky/dashboard/src/hooks/useFirstVisit.js
Resolve #6542
**Problem:**  
After restoring tour auto-start in #6565, opening a new browser tab triggers the tour again. It should only auto-start once per browser profile/session.
**Root cause:**  
`FIRST_VISIT_KEY` was stored in `sessionStorage`, which is scoped per tab. Each new tab appeared as a "first visit."
**Change:**  
Switch `FIRST_VISIT_KEY` from `sessionStorage` to `localStorage` to share state across tabs.
**Behavior:**
- Tour auto-starts only once across all tabs for the same browser profile.
- Manual start via the help button still works.
- Completion is still tracked via `TOUR_COMPLETED_KEY` in `localStorage`.
`sky/dashboard/src/hooks/useFirstVisit.js`
- Read/write/remove `FIRST_VISIT_KEY` from `localStorage` instead of `sessionStorage`.
- Updated inline comment to …
> [Dashboard] Prevent tour auto-start in new tabs by using localStorage for first-visit flag

- sky/utils/config_utils.py
- tests/unit_tests/test_sky/utils/test_config_utils.py
A user reported that setting the `env` in admin policy multiple times would result in duplicate env entires, this PR fixes the merge issue.
> Fixed patch strategy when merging k8s config

- examples/tpu/tpuvm_mnist.yaml
Resolve #6669
Actually its older version of jaxlib get deprecated in pypi.
We need to specific the source link of older version of jaxlib.
And also some dependency need to be updated.
> Fix tpu test example failure

- sky/client/cli/command.py
> [Pools] Revamp CLI args from `--pool-name` to `--pool`

- docs/source/reference/config.rst
- sky/global_user_state.py
- sky/server/server.py
- sky/utils/schemas.py
- tests/test_global_user_state.py
This PR introduces retention for the cluster event table. It adds a new entry to `sky/config.yaml` to change the rate of retention.
This was tested with a new unit test that ensures that the retention daemon waits for enough time and calls the new clean up function to remove entries from the cluster event table. I also tested it manually by starting a cluster, confirming that corresponding entries existed in the cluster event table and then watching the retention daemon kick in and remove those entries.
> [Core] Enable retention for cluster event table

- sky/provision/aws/config.py
- sky/provision/aws/instance.py
This PR catches errors when we attempt to create a default security group for quick AWS deletion if the user does not have the permission.
This PR was tested by creating an IAM user that has all EC2 permissions except for security group creation and then ensuring the user is still able to launch a cluster by supplying a pre-created security group in `.sky/config/yaml`. 
> [Core] Prevent errors when user can't create security group

- sky/serve/replica_managers.py
- sky/utils/resources_utils.py
- tests/unit_tests/test_resources.py
Previously, update this yaml on the same svc/pool will fail due to dict is an unhashable type. This pr fixes this.
```yaml
pool:
workers: 10
resources:
accelerators: {H100:1, H200:1}
setup: |
echo "Setup complete!"
```
```bash
sky jobs pool apply --pool gpu-pool new-pool.yaml                
YAML to run: new-pool.yaml
Pool spec:
Worker policy:  Fixed-size (10 workers)
Each pool worker will use the following resources (estimated):
Disk size 256 is not supported by Kubernetes. To add additional disk, use volumes.
Disk size 256 is not supported by Kubernetes. To add additional disk, use volumes.
Considered resources (1 node):
-------------------------------------------------------------------------------------------------------
INFRA                 INSTANCE                         vCPUs …
```
> [Serve] Fix version bump

- sky/adaptors/nebius.py
- sky/clouds/nebius.py
- sky/provision/nebius/utils.py
Nebius has an issue that may cause the request blocks infinitely when called in sync code even if there is a timeout https://github.com/nebius/pysdk/issues/76, this PR workaround this issue by calling nebius sdk in coroutines with a read timeout for readonly requests.
close https://github.com/skypilot-org/skypilot/issues/6657
```bash
$ sky launch --infra nebius --cpus 2+ -y
$ sky launch --infra nebius --cpus 2+ -y
$ while true; do SKYPILOT_DEBUG=1 sky status -r; done
$ SKYPILOT_DEBUG=1 sky stop -a -y
$ SKYPILOT_DEBUG=1 sky start -a -y
```
> Fixed nebius infinite waiting

- sky/server/common.py
The requests library will dynamically load `simplejson` if it is installed, and otherwise will load the built-in python `json` library. This means that the decode exception will be different depending on which library was loaded. Use `requests.JSONDecodeError` instead so it will work in either case.
> [auth] fix login detection when `simplejson` is installed

- sky/provision/kubernetes/instance.py
https://github.com/skypilot-org/skypilot/pull/6593 added a bug where status for pods that no longer exist are being returned even when `non_terminated_only` is specified. This PR fixes the issue.
> Do not include missing pods if `non_terminated_only` is set to true

- sky/backends/backend.py
- sky/backends/backend_utils.py
- sky/backends/cloud_vm_ray_backend.py
- sky/backends/local_docker_backend.py
- sky/core.py
- sky/dashboard/src/data/connectors/clusters.jsx
- sky/global_user_state.py
The goal of this PR is to enable users to inspect the reason why clusters terminated. It changes when we delete the cluster event table's records to ensure that if the user did not intend to delete the cluster the logs will remain and can be inspected via the dashboard.
This code was tested by checking three conditions. 
1. If the user explicitly runs sky down the cluster event entries are wiped
2. If the user runs sky stop the entries remain in the table.
3. If we kill all of the nodes in the cluster the dashboard will show the last event despite the cluster being 'history' as shown by the below screenshot.
> [UX] Provide last event info for clusters stored in cluster_history

- sky/dashboard/src/components/jobs.jsx
- sky/dashboard/src/data/connectors/jobs.jsx
- sky/dashboard/src/lib/jobs-cache-manager.js
- sky/jobs/constants.py
- sky/jobs/server/core.py
- sky/jobs/server/utils.py
- sky/jobs/utils.py
- sky/server/requests/payloads.py
- sky/server/requests/serializers/encoders.py
- tests/unit_tests/test_sky/jobs/test_server_queue.py
Support filtering with status and returning status counts in API server
> [Dashboard] Support filtering with status and returning status counts in API server

- tests/smoke_tests/test_sky_serve.py
Resolve #6694 
Check the service status after termination is submitted, and ensure all services are terminated.
```bash
(sky) zpoint:~/codes/skypilot (master)$ pytest tests/smoke_tests/test_sky_serve.py::test_skyserve_aws_http --aws
D 08-18 17:22:34 skypilot_config.py:245] using default user config file: ~/.sky/config.yaml
D 08-18 17:22:34 skypilot_config.py:505] Config loaded from /home/zpoint/.sky/config.yaml:
D 08-18 17:22:34 skypilot_config.py:505] {}
D 08-18 17:22:34 skypilot_config.py:505] 
D 08-18 17:22:34 skypilot_config.py:512] Config syntax check passed for path: /home/zpoint/.sky/config.yaml
D 08-18 17:22:34 skypilot_config.py:272] using default project config file: .sky.yaml
D 08-18 17:22:34 skypilot_config.py:627] client config (before task and CLI overrides): 
D 08-18 …
```
> [Test] Check serve status after termination

- sky/provision/provisioner.py
One of our users report that the `StopFailoverError` on kubernetes is unclear, this PR makes the error message clear with more context for diagnosis.
> Refined error message on kubernetes failover

- charts/skypilot/templates/rbac.yaml
I've accidentally broken chart in #6737 (forgot to remove unnecessary whitespace trim). Now it should work as intended.
> charts: fix rbac template rendering for default values after #6737

- sky/setup_files/dependencies.py
Previously, `grpcio` is not included as a server dependency:
```
% pip install 'skypilot-nightly[aws,gcp,server]==1.0.0.dev20250818'
% pip show grpcio
WARNING: Package(s) not found: grpcio
```
This PR now includes it.
> Add grpcio and protobuf to [server] extra depedencies

- sky/serve/replica_managers.py
Fixes #6729. We change the location of `ProcessStatus` to `common_utils` in #6666. Previously created replica info object will still try to import the related module from replica managers which causes this bug. This PR fixes it.
> [Serve] Fix unpickle issue on class location change

- .github/workflows/buildkite-trigger-wait.yml
- .github/workflows/nightly-build.yml
- tests/smoke_tests/test_cluster_job.py
Resolve #6730
Add staggered timing between AWS tests, Kubernetes tests, and remote server tests.  
- **Kubernetes tests** run on a local Kind cluster.  
- **Remote server tests** require launching a local Docker image and connecting to it.  
Both are resource-heavy on the Buildkite agent VM, increasing failure risk if run alongside other tests.  
**Before this PR**
**Fully sequential tests** (e.g., waiting for AWS → Kubernetes → remote, totaling **2.5 hours**):  
```bash
|-----aws tests-----|(1 hour)  
|-----kubernetes tests-----|(2 hours total, 1 hour runtime)  
|-----remote server tests-----|(2.5 hours total, 0.5 hour runtime)  
```
**After this PR:** 
**Tests overlap** intelligently to reduce total time and resource contention:  
```bash
|-------------aws tests-------------|(1 hour) …
```
> [Test]Stagger test execution to reduce resource contention and total runtime

- sky/core.py
- sky/jobs/server/core.py
- sky/serve/server/impl.py
Previously in #6668, we changed the order from
1. Resolve volumes
2. Apply admin policy
To
1. Apply admin policy
2. Resolve volumes, including volumes added by the admin policy
This means that users are able to add volumes in the admin policy.
However, for managed jobs, we manually resolve the volumes on the API server before sending the dag to the jobs controller, so that it has the volumes info from the API server. (Which won't be there on the jobs controller side.)
So, we need to swap the order for managed jobs as well.
> [jobs] resolve volumes before applying dag

- docs/source/reference/config.rst
> [Docs] Fix typo in gcp.force_enable_external_ips section

- .github/workflows/nightly-build.yml
- tests/conftest.py
Resolve #6770
Add another section to trigger `resource-heavy` Kubernetes tests first. Since these tests run on EKS clusters, they won't impact other tests.
> Kubernetes test need to run all tests in nightly build to improve coverage

- sky/provision/do/utils.py
- sky/server/server.py
- sky/utils/common.py
- sky/utils/common_utils.py
This PR persist the server hash to db and restore it when API server restarts.
Tests:
> Persist server user hash to db

- examples/admin_policy/example_policy/example_policy/skypilot_policy.py
Skip applying volume policy to job/serve controller
- Launch a cluster with volume admin policy enabled, volumes are updated
- Launch a managed job  with volume admin policy enabled, volumes are updated to the job cluster but not to the job controller
> [Policy] Skip applying volume policy to job/serve controller

- sky/dashboard/src/components/jobs.jsx
- sky/dashboard/src/data/connectors/jobs.jsx
- sky/dashboard/src/pages/jobs/[job].js
- sky/skylet/job_lib.py
This PR adds a download button for managed jobs logs similar to the one for cluster job logs. 
I tested running a managed job and verifying that I could indeed download the logs as a zip file (`Managed Job Logs Aug 19 2025.zip`) which unzips to `1-long-logs-test/run.log`. 
> [UX] Download button for managed jobs logs

- sky/backends/cloud_vm_ray_backend.py
This PR adds a `managed_jobs/` prefix to managed jobs controller logs that are downloaded by the client. Previously this prefix was not being used and was resulting in the following confusing behavior:
```
❯ sky logs -s sky-475f-rsonecha 1
Job 1 logs: ~/sky_logs/1-long-logs-test
```
```
❯ sky jobs logs -s --controller 1
Job 1 logs (controller): ~/sky_logs/1-long-logs-test
```
where cluster job logs and managed jobs controller logs for jobs with the same job id and name would get downloaded to the same local directory.
I manually verified that downloading managed jobs controller logs now uses the `~/sky_logs/managed_jobs/` prefix:
```
❯ sky jobs logs -s --controller 1
Job 1 logs (controller): ~/sky_logs/managed_jobs/1-long-logs-test
```
> [UX] Add jobs_controller prefix to avoid overwriting downloaded logs

- charts/skypilot/templates/grafana-ingress.yaml
This PR updates the `grafana-authed` Ingress to support the newer `auth.oauth` configuration, while still handling the deprecated `ingress.oauth2-proxy`. It also adds dynamic configuration of the `auth-response-headers` annotation based on the `auth.proxy` settings in `grafana.ini`.
The main objective is to fix an issue where Grafana did not properly apply the OAuth2 Proxy when using Google OAuth with the auth.oauth values.
> Fix missing auth.oauth in grafana-auted ingress

- sky/client/sdk.py
- sky/exceptions.py
- sky/server/rest.py
Test:
Launch with network issue, can be recovered by retry:
```bash
$ SKYPILOT_DEBUG=1 sky launch --infra aws -c bastion --cpus 4+ -y
...
Running on cluster: bastion
D 08-21 23:47:01 rest.py:119] Retry stream_and_get due to ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read)), attempt 1/5
I 08-21 15:49:35 optimizer.py:918] Considered resources (1 node):
I 08-21 15:49:35 optimizer.py:986] -----------------------------------------------------------------------------
I 08-21 15:49:35 optimizer.py:986]  INFRA             INSTANCE     vCPUs   Mem(GB)   GPUS   COST ($)   CHOSEN
I 08-21 15:49:35 optimizer.py:986] -----------------------------------------------------------------------------
I 08-21 15:49:35 optimizer.py:986] …
```
> Retry on transient error when streaming API request

- sky/client/cli/command.py
- tests/test_cli.py
This PR adds client version and commit to sky api info.
This PR was tested by running sky api info and verifying the client and server version.
> [UX] Add client version and commit to sky api info

- sky/jobs/utils.py
Previously, if pools were supported by the jobs controller, but a job did not belong to a pool, the `None` value would be exposed to the user. Now, it just shows `-`.
> [pools] don't show None in sky status / sky jobs queue

- tests/unit_tests/test_sky/clouds/test_kubernetes.py
I'm tracking down a potential issue related to k8s and volumes specified in `kubernetes.pod_config`, and realized we don't have a unit test for testing merging of configs from `kubernetes.pod_config` with the cluster yaml. This PR adds a unit test for that.
- `pytest tests/unit_tests/test_sky/clouds/test_kubernetes.py::TestKubernetesVolumeMerging`
> [Test] Add TestKubernetesVolumeMerging unit test

- sky/server/rest.py
- tests/unit_tests/test_sky/server/test_rest.py
On transient retries - if we determine the retry to have succeeded, then reset the retry count. This allows the function decorator to deal with any number of transient errors that the function can recover from.
To determine if a retry has succeeded, we use the `line_processed` field as a proxy for progress. The idea is that if the function, on retry, were able to process more lines, the function must have overcome whatever transient error was thrown before.
This PR has no effect on functions that don't interact with `line_processed` field, preserving the current behavior where requests are retried `max_retries` times.
> [SDK] reset transient failure count if function made progress on latest retry

- sky/backends/backend_utils.py
- sky/client/sdk.py
- sky/client/sdk_async.py
- sky/execution.py
- sky/jobs/constants.py
- sky/jobs/controller.py
- sky/jobs/recovery_strategy.py
- sky/jobs/scheduler.py
- sky/jobs/server/core.py
- sky/jobs/server/utils.py
- sky/jobs/state.py
- sky/jobs/utils.py
- sky/provision/provisioner.py
- sky/serve/replica_managers.py
- sky/serve/serve_utils.py
- sky/serve/server/impl.py
- sky/serve/service.py
- sky/server/common.py
- sky/server/config.py
- sky/server/constants.py
- sky/server/daemons.py
- sky/server/server.py
- sky/setup_files/dependencies.py
- sky/skylet/attempt_skylet.py
- sky/skylet/constants.py
- sky/skylet/events.py
- sky/utils/controller_utils.py
- sky/utils/db/migration_utils.py
- sky/utils/rich_utils.py
- sky/utils/subprocess_utils.py
Reverts skypilot-org/skypilot#6459
During the upgrade path, there is a short period of time between killing the old controllers and starting the new ones. If, during this time, we check the status of the job (e.g. by running `sky jobs cancel`, which calls `utils.update_managed_jobs_statuses`) then the job may incorrectly transition to FAILED_CONTROLLER.
There's a few possible fixes but I need to think more and I don't want this to go into nightly as-is.
> Revert "[Core] Pool Job Consolidation"

- tests/conftest.py
- tests/smoke_tests/test_cluster_job.py
- tests/smoke_tests/test_provision_logs.py
- tests/smoke_tests/test_sky_serve.py
- tests/smoke_tests/test_workspaces.py
> Support `no_remote_server` mark on smoke tests

- sky/provision/kubernetes/instance.py
In heterogeneous GPU clusters(NVIDIA, AMD, etc.), pods on AMD GPUs were failing because the nvidia runtime class was being incorrectly applied.
This change ensures the nvidia runtime class is added only when using NVIDIA GPUs.
> Fix: Exclude NVIDIA runtime for non-NVIDIA GPUs

- .github/workflows/nightly-build.yml
> Trigger k8s remote server test on nightly build

- sky/server/rest.py
This PR fixes connection drops issue when a single SDK process initiates > 10 HTTP connections to the API server.
Tested manually in benchmark, now a single process can file up to 200 concurrent connections.
> Fixed client http pool config

- sky/server/rest.py
- tests/unit_tests/test_sky/server/test_rest.py
This PR limits the error types that will be retried for streaming request to avoid unnecessary retries when there is an application error like https://buildkite.com/skypilot-1/full-smoke-tests-run/builds/63#0198d571-b764-4dbb-8136-bf6524367ce0
Tested locally:
```bash
$ SKYPILOT_DEBUG=1 sky launch -c c -y --cpus 1+ 'for i in {1..100}; do echo "$i" && sleep 1; done' --cloud kubernetes
(simulate network error)
(sky-cmd, pid=1561) 1
(sky-cmd, pid=1561) 2
(sky-cmd, pid=1561) 3
(sky-cmd, pid=1561) 4
(sky-cmd, pid=1561) 5
(sky-cmd, pid=1561) 6
(sky-cmd, pid=1561) 7
(sky-cmd, pid=1561) 8
(sky-cmd, pid=1561) 9
D 08-25 11:53:53 sdk.py:151] To stream request logs: sky api logs e13a8439-b723-4017-a75e-ab100d332df6
D 08-25 11:53:53 rest.py:144] Retry tail_logs due to ("Connection broken: …
```
> Fixed retry on non-transient errors

- sky/server/auth/authn.py
- sky/server/server.py
Reduce memory usage in file upload.
The regression is introduced by `override_user_info_in_request_body`, which consume the request body without streaming. This PR skips that middleware for `/upload` API. As a follow-up, we should remove this middleware cc @DanielZhangQD 
Tests: **launch with 3GiB file mounts**
Before:
Takes ~2GiB mem to process the request:
After:
No obvious mem peaks when process the request
> Fixed memory usage in file upload

- sky/client/common.py
- sky/schemas/api/responses.py
- sky/server/server.py
I was debugging this error where a file that should have been uploaded does not exist in the remote server:
```
sky launch workdir.yaml -c sjtest
YAML to run: workdir.yaml
⚙︎ Uploading files to API server
✓ Files uploaded  View logs: ~/sky_logs/file_uploads/sky-2025-08-25-12-07-20-327404-aa0e49a9.log
ValueError: File mount source '/root/.sky/api_server/clients/1dcc8143/file_mounts/Users/seungjinyang/.netrc' does not exist locally. To fix: check if it exists, and correct the path.
```
The file upload log shows the following:
```
I 08-25 12:07:20 common.py:334] Zipping files to be uploaded: ['/Users/seungjinyang/.netrc', '/Users/seungjinyang/largefile']
I 08-25 12:07:21 common.py:338] Zipped files to: /var/folders/4t/b03l11jx2lz6krkxv815mhmm0000gn/T/tmpd1fnckgd.zip
I 08-25 12:07:21 …
```
> [Client] Retry all chunk uploads if no upload displays completed status

- sky/provision/kubernetes/instance.py
This will help us debug some issues in flaky k8s environments.
> [logs] add additional debug logs for terminated k8s pods

- sky/server/common.py
- sky/server/server.py
- sky/setup_files/dependencies.py
- sky/users/server.py
- tests/unit_tests/test_sky/users/test_server.py
Internal basic auth supported only `apr_md5_crypt` hashing, which is [deprecated](https://passlib.readthedocs.io/en/stable/lib/passlib.hash.html#deprecated-hashes).
I switched it to`passlib`'s `CryptContext` which is a tool to support multiple hash types at once, thus basic auth can use either legacy `apr_md5` hashes or something more modern. It also uses `bcrypt` by default (e.g. when users are created in UI) which gives pretty robust hashes.
I tested:
* creating user via UI and INITIAL_BASIC_AUTH env (k8s);
* importing/exporting user list from UI;
* creating users and changing their passwords in UI.
> api server: add proper hashing support for internal basic auth

- sky/client/sdk.py
- sky/clouds/aws.py
- sky/server/common.py
Corrected misspellings in comment:
- `compatbility` → `compatibility`
- `evalute` → `evaluate`
- `empheral` → `ephemeral`
> chore: fix typos in comment

- sky/logs/aws.py
Setting `AWS_DEFAULT_REGION` and region via `aws configure set`, because it seems like the cloudwatch command later in this string doesn't respect `AWS_REGION`
Tested manually on our clusters
> Setting region more explicitly in aws logs

- sky/templates/nebius-ray.yml.j2
Fix https://github.com/skypilot-org/skypilot/issues/6881 after bumping os versions
tested to run 
```
resources:
image_id: docker:ubuntu:20.04
```
> [Nebius] Fix `image_id: docker:`

- sky/server/server.py
If you start the API server with `sky api start --foreground`, as in our Helm chart, `sky api logs --server-logs` will not work (TODO: make it work).
Before this change, `sky api logs --server-logs` would silently return nothing. Now, it should return a somewhat more helpful error message.
> [logs] show a better error when server logs are not available

- sky/provision/kubernetes/instance.py
Include some stats regarding the number of k8s events processed and inserted for debugging purposes
Prints the following loglines:
```
I 08-27 15:27:31 daemons.py:86] === Refreshing cluster status ===
D 08-27 15:27:31 instance.py:1281] Analyzing events for pod <pod-name>
D 08-27 15:27:31 instance.py:1318] [pod <pod-name>] encountered new event: 2025-08-27 21:57:13+00:00 TaintManagerEviction Cancelling deletion of Pod default/<pod-name>
D 08-27 15:27:31 instance.py:1318] [pod <pod-name>] encountered new event: 2025-08-27 21:55:19+00:00 NodeNotReady Node is not ready
D 08-27 15:27:31 instance.py:1318] [pod <pod-name>] encountered new event: 2025-08-27 21:53:53+00:00 Pulled Successfully pulled image "us-docker.pkg.dev/sky-dev-465/skypilotk8s/skypilot:latest" in 16.629s (16.629s including …
```
> [k8s] better logs for pod missing events analysis

- docs/source/reference/config.rst
- sky/global_user_state.py
- sky/utils/schemas.py
- tests/test_global_user_state.py
This PR separates the retention of `STATUS_CHANGE` and `DEBUG` events. There is a new option `api_server.cluster_debug_event_retention_hours` that solely configures the retention of debug events. The default is set to 30 days.
I tested this by setting the regular retention setting very low (60 seconds) while leaving the debug retention setting alone, starting a GKE cluster, killing some nodes, verifying that the table had entries for both event types, waiting for 60 seconds and seeing that only debug events remain.
> [Core] Add separate cluster event retention for events with type DEBUG

- sky/server/auth/oauth2_proxy.py
- tests/unit_tests/test_sky/server/auth/test_oauth2_proxy.py
On some network topology, keep `content-length` without actually sending the body will cause a client timeout. This PR fixes this issue by strip the `content-length` and `content-type` header when calling oauth2-proxy.
Also, relevant UTs are added to cover this.
> [API server] Fixed oauth2 request body strip

- sky/backends/cloud_vm_ray_backend.py
- sky/server/common.py
- sky/server/daemons.py
- sky/utils/annotations.py
- sky/utils/cluster_utils.py
- sky/utils/lock_events.py
- sky/utils/timeline.py
- tests/unit_tests/test_catalog.py
- tests/unit_tests/test_sky/utils/test_timeline.py
Problem 1: Since the daemon is a single request that runs a while, the request level cache is not cleared after each periodic run of the daemon. Treat each run as a request in cacheing terms by clearing out request level cache after each run of the daemon.
Problem 2: timeline events can grow without bound. Do not store timeline events if the events won't be used for anything.
> long running request daemon memory hygiene

- sky/backends/cloud_vm_ray_backend.py
TL;DR this global cacheing causes a memory leak on the status refresh daemon.
- When the cluster is fetched from the DB, the handle is re-created on every read from the DB:
```1293:1315:sky/global_user_state.py
'handle': pickle.loads(row.handle),
```
- When status refresh=FORCE runs, we eventually do a Ray health check that calls a method on the handle:
```2065:2073:sky/backends/backend_utils.py
runners = handle.get_command_runners(force_cached=True)
```
- That method is globally lru-cached on the instance (self), which retains a strong reference to the handle in the cache key:
```2501:2507:sky/backends/cloud_vm_ray_backend.py
@context_utils.cancellation_guard
@annotations.lru_cache(scope='global')
@timeline.event
def get_command_runners(self,
force_cached: bool = False, …
```
> remove global cacheing of get_command_runner

- docs/source/reference/config.rst
- docs/source/reference/kubernetes/kubernetes-getting-started.rst
- sky/provision/kubernetes/utils.py
- sky/utils/kubernetes_enums.py
- tests/unit_tests/kubernetes/test_kubernetes_utils.py
Adds support for CW cluster autoscaler: https://docs.coreweave.com/docs/products/cks/nodes/autoscaling
Users need to add this to config.yaml to make it work:
```
kubernetes:
provision_timeout: 3600 # Wait 1 hour for nodes to get provisioned before failover. Set to -1 to wait indefinitely.
autoscaler: coreweave
```
~Do not merge - testing on CW cluster~
Tested on CW H200 cluster. Scaled up from 0->1 in ~20 min.
> [Coreweave] Add Coreweave autoscaler support

- sky/server/server.py
- sky/setup_files/dependencies.py
- tests/unit_tests/test_zip_and_unzip.py
This code turns IO intensive synchronous codepaths in `/upload` endpoint to be asynchronous.
Empirically, the `unzip_file` call can take dozens of seconds (for file mounts with many GBs) to complete. This call currently blocks the event loop, manifesting in hangs in, for example, k8s ssh (which is proxied through the API server).
This PR changes some IO intensive calls to be asynchronous.
> [API server] fix /upload endpoint from blocking the event loop

- sky/backends/cloud_vm_ray_backend.py
Currently, the spinner will show `Launching - blocked by other requests` for a short period of time after we actually obtain the cluster lock and start doing stuff. This will reset the spinner message immediately upon obtaining the lock.
> [ux] avoid showing "blocked by other requests" after we obtain lock

- tests/conftest.py
- tests/smoke_tests/smoke_tests_utils.py
- tests/smoke_tests/test_api_server.py
- tests/smoke_tests/test_cluster_job.py
- tests/smoke_tests/test_logs.py
- tests/smoke_tests/test_mount_and_storage.py
- tests/smoke_tests/test_region_and_zone.py
- tests/smoke_tests/test_sky_serve.py
- tests/smoke_tests/test_workspaces.py
* Skip tests that require server restart or changing `USER_ENV`, which is not supported via API endpoints and service accounts token(The user will fixed if we use that, `USER_ENV` won't work then)  
* Change some GPU types
* Still working on it, PR for sync and convenience tests.
> Fix coreweave k8s cluster smoke tests failures

- sky/jobs/server/server.py
- sky/serve/server/server.py
- sky/server/requests/executor.py
- sky/server/requests/preconditions.py
- sky/server/requests/requests.py
- sky/server/server.py
- sky/server/stream_utils.py
- sky/setup_files/dependencies.py
- sky/utils/db/db_utils.py
- tests/test_api.py
- tests/unit_tests/test_sky/server/requests/test_precond.py
- tests/unit_tests/test_sky/server/requests/test_requests.py
This PR add asyncio support for request DB to avoid sync operations block the uvicorn event loop.
Test:
**Before this PR**, 
**After this PR**, slow request operations now longer affect the event loop:
Note that there is a significant diff on the duration of `get_request` and `get_request_async`, because previously `get_request` was executed in uvicorn's event loop, which has a fixed concurrency (equal to CPU cores, 4 in my test) and will not be affected by coroutine scheduling once `get_request` start. The async version has the same concurrency with client requests (30 in my test) and with the coroutine scheduling time. The final throughput is same as before.
> Request DB asyncio support

- sky/server/stream_utils.py
- tests/load_tests/test_load_on_server.py
Increase the poll interval in https://github.com/skypilot-org/skypilot/pull/6889 introduce high latency for short requests, should consider other potential solution to reduce the CPU usage.
Master: 
```
multitime -n 5 sky status
Mean        Std.Dev.    Min         Median      Max
real        3.889       0.163       3.656       3.831       4.117
user        1.084       0.136       0.881       1.122       1.277
sys         0.743       0.197       0.518       0.670       1.103
```
This PR:
```
multitime -n 5 sky status
1: sky status
Mean        Std.Dev.    Min         Median      Max
real        1.610       0.261       1.353       1.459       2.025
user        0.841       0.085       0.775       0.785       1.000
sys         0.811       0.151       0.618       0.763       0.993
```
Before …
> Reverted poll interval when waiting request status

- sky/client/common.py
Before, calling `sky logs --sync-down` while using a service account token would error with:
```bash
% sky logs sky-102a-kevin 1 --sync-down
Syncing down logs to local...
...
File "/Users/kevin/git/skypilot/sky/client/sdk.py", line 998, in download_logs
remote2local_path_dict = client_common.download_logs_from_api_server(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/kevin/git/skypilot/sky/client/common.py", line 132, in download_logs_from_api_server
raise Exception(
Exception: Failed to download logs: 400 {"detail":"Invalid folder path: ~/.sky/api_server/clients/sa-8b5cf11ca1481511/sky_logs/1-sky-cmd; ~/.sky/api_server/clients/de1a4b69/sky_logs"}
```
So I added some debug logs on the server and found something interesting:
```
I 08-29 17:25:59 authn.py:19] request.url.path: …
```
> [SDK] Use `make_authenticated_request` instead of `requests.post` when calling POST /download

- sky/utils/command_runner.py
Came across this while testing on the Coreweave Kubernetes cluster. On Kubernetes, we were getting partial errors (return code 23) from rsync due to the default securityContext on our helm charts which drops all capabilities:
```bash
I 08-29 06:55:36 command_runner.py:369] rsync: [generator] chown "/root/.sky/api_server/clients/de1a4b69/sky_logs/1-sky-cmd/." failed: Operation not permitted (1)
I 08-29 06:55:36 command_runner.py:369] rsync: [generator] chown "/root/.sky/api_server/clients/de1a4b69/sky_logs/1-sky-cmd/tasks" failed: Operation not permitted (1)
I 08-29 06:55:36 command_runner.py:369] rsync: [receiver] chown "/root/.sky/api_server/clients/de1a4b69/sky_logs/1-sky-cmd/.run.log.tGvrAf" failed: Operation not permitted (1)
I 08-29 06:55:36 command_runner.py:369] rsync: [receiver] …
```
> [Core] add --no-owner --no-group to CommandRunner._rsync

- sky/global_user_state.py
- sky/server/server.py
- sky/utils/db/migration_utils.py
This PR allows `get_engine` to cache and reuse engines across databases.
Additionally, have the main API server process use QueuePool instead of NullPool, which is more efficient when the process is expected to submit db requests frequently and concurrently.
I am still unsure on whether each executor process should get a QueuePool for itself, because large API server deployments can have many dozens of executors and each executor being able to have ~5 concurrent connections may put quite a bit of pressure on the DB. However, we know the main API server will be interacting with the DB frequently, so giving that process access to persistent reusable connections make sense.
> [db] reuse db engine across databases, API server process uses QueuePool for postgres

- sky/server/requests/requests.py
- sky/server/server.py
- sky/server/stream_utils.py
- tests/test_api.py
close https://github.com/skypilot-org/skypilot/issues/6945
According profile, there is a non-trivial CPU cost of `get_request_async` call since it is called in busy loops (`/api/get`, `/api/stream`), this PR simplifies the SQL to check status.
Test:
```bash
python test.py
10000 times get_request_status Time taken: 3.0183849334716797
10000 times get_request_status_async Time taken: 0.4276120662689209
```
About 7x improvement.
```python
$ cat test.py
import asyncio
import time
from sky.server.requests import requests
async def main():
now = time.time()
for _ in range(10000):
req_status = await requests.get_request_async('skypilot-status-refresh-daemon')
end = time.time()
print(f'10000 times get_request_async Time taken: {end - now}')
now = time.time()
for _ in range(10000):
req_status = …
```
> [db] Optimized request polling cost

- sky/utils/resource_checker.py
- tests/unit_tests/test_sky/utils/test_resource_checker.py
This pull request makes a small change to the job retrieval logic in `sky/utils/resource_checker.py`. The function `get_all_managed_jobs()` now returns only the filtered jobs instead of the full output from `managed_jobs_core.queue()`, ensuring that only relevant job data is provided.
> Fix type error by unpacking tuple in get_all_managed_jobs

- sky/dashboard/src/components/jobs.jsx
- sky/dashboard/src/data/connectors/clusters.jsx
- sky/dashboard/src/pages/clusters/[cluster].js
This PR converts the job IDs passed to the server to strings in the download logs request from the cluster detail page. This fixes an issue where the download button works from the cluster job detail page but not the cluster detail page. The reason why it works for the cluster job detail page is that we were parsing the job id from the url which by default will be a string.
I manually verified that the download logs button from the cluster detail page is now working. 
> [Dashboard] Fix cluster detail page job log download

- sky/dashboard/src/components/jobs.jsx
The managed jobs page in the dashboard currently shows four buttons under the logs column:
1. view job logs
2. download job logs
3. view controller logs
4. download controller logs
This PR removes 3 and 4, making for a cleaner and less confusing UX. Users can still view/download controller logs from the managed jobs detail page. 
Manually verified that buttons 3 and 4 are no longer there and 1 and 2 still work as expected. 
> [Dashboard] Deduplicate Managed Jobs Download Button

- sky/dashboard/next.config.mjs
- sky/dashboard/src/components/config.js
This PR addresses an issue where the "View API Server Metrics" button in the config page of the dashboard injects an incorrect app into the grafana url. Previously, we were using the api server hostname as the app name. However, the app name should actually be set to `"$SKYPILOT_RELEASE_NAME"-api`. 
I tested this PR by first reproducing the issue by deploying an api server on a kubernetes cluster with api server metrics enabled and verified that when I click on the "View API Server Metrics" it opened the api server metrics grafana dashboard with app set to `89.169.110.123` which is the api server hostname. As you can see, this shows no data:
Then I redeployed the api server using the following docker image: `rohanskypilot/skypilot:api-metrics-v1` which I built with the changes in this PR …
> [Dashboard] Fix api server metrics app parameter

- sky/dashboard/src/components/infra.jsx
- sky/dashboard/src/data/connectors/infra.jsx
This PR addresses an issue on fresh deployments where no enabled clouds show up in the dashboard until the user refreshes the page or the page auto-refreshes in 30s. We fix the issue by setting forceRefresh to true in the `getInfraData` and `getCloudInfrastructure` functions.
I manually verified that this works by removing my `~/.sky/` directory, restarting the api server, and checking that all my enabled clouds show up in the infra page on first load. Previously, it showed no enabled clouds. 
> [Dashboard] Fix enabled clouds not showing up on first load

- sky/global_user_state.py
- sky/jobs/state.py
- sky/serve/serve_state.py
- sky/server/config.py
- sky/server/requests/executor.py
- sky/server/server.py
- sky/server/uvicorn.py
- sky/skypilot_config.py
- sky/utils/db/db_utils.py
- sky/utils/db/migration_utils.py
If postgres DB supports enough connections for every process (executor, uvicorn worker, main loop), use a persistent connection instead of NullPool (which does connection setup/teardown for every DB op) to save on connection setup/teardown time.
We have been using NullPools to save on total # of connections at any given time because we didn't have visibility on the number of connections a PSQL instance supports. Now that we are able to get this number, we're able to make smart choices in the trade-offs to make.
Testing:
Running `sky status` on a remote API server on GKE with GCP cloud SQL backend, using IAM auth.
Initial few runs of `sky status` are discarded to fully load modules and initialize the db connections.
this PR
2.921
2.810
2.874
2.970
2.850
avg: 2.885
master
5.515
5.492
6.008 …
> [db] connection pool optimization - 2x speedup in remote postgres environment

- sky/server/requests/requests.py
- sky/utils/db/db_utils.py
- tests/unit_tests/test_sky/server/requests/test_requests.py
```
E 09-05 15:44:34 requests.py:842] Error running requests GC daemon: object NoneType can't be used in 'await' expression
Running cluster event retention daemon...
```
This PR fixes the request retention daemon and make it non-blocking. The UT failed to capture this regression since `clean_finished_requests_with_retention` is mocked in `test_requests_gc_daemon` , this PR also refines the UT to cover such case.
> Fixed request retention daemon

- sky/provision/__init__.py
- sky/provision/kubernetes/__init__.py
- sky/provision/kubernetes/volume.py
- sky/provision/runpod/volume.py
- sky/volumes/server/core.py
- tests/unit_tests/test_sky/volumes/test_core.py
- tests/unit_tests/test_sky/volumes/test_runpod_volume.py
This PR modifies the way we list volumes for a speedup. In running `volume_list()` we get the pod information with the ultimate goal of linking each volume to the cluster associated with it. 
With this change instead of going through each volume and then using `list_namespaced_pod()` to get all of the pods associated with the volume we first get all of the namespaces associated with each of the pods, then get all of the pods in each of the namespaces by calling `list_namespaced_pod()`. This way we only make one call per-context, per-namespace.
Another approach would have been to call `list_pod_for_all_namespaces()`. This would allow us to only make one API call. The issue is you can't filter this call based on namespace, that means if the user has a large amount of pods we have to parse …
> [Core] Improve speed of volume list

- sky/provision/aws/config.py
- tests/unit_tests/test_aws.py
This pull request aims to give more information to the user when they are unable to launch a cluster on AWS due to a VPC error.
This was tested by verifying the output messages provided more clarity in each case and ensuring the normal code path functions as expected.
Case 1: The default VPC has no subnets or does not exist
Output is now:
```bash
E 08-19 11:07:15 config.py:52] SKYPILOT_ERROR_NO_NODES_LAUNCHED: The default VPC in ap-south-2 either does not exist or has no subnets.
```
Case 2: You specified a VPC with no subnets.
Output is now:
```bash
E 08-19 11:22:15 config.py:52] SKYPILOT_ERROR_NO_NODES_LAUNCHED: No candidate subnets found in specified VPC vpc-05c3bc628da4d4f1c.
```
Case 3: All the subnets are public and use_internal_ips is True
Output is now:
```bash
E 08-19 11:38:40 …
```
> [UX] Improve messages for VPC errors.

- docs/source/cloud-setup/cloud-permissions/aws.rst
- sky/backends/backend_utils.py
- sky/utils/schemas.py
- tests/smoke_tests/smoke_tests_utils.py
- tests/smoke_tests/test_ssm.py
- tests/test_smoke.py
This PR adds the use_ssm flag (default false) to turn on SSM for clusters.
I added multiple smoke tests for this PR:
- One to test that the flag works with public instances
- One to test that the flag works with private instances
- One to test that if the user sets use_internal_ips to True but doesn't specify a proxy command we default to ssm. In that case the user will see the following message
```
use_internal_ips is set to true, but ssh_proxy_command is not set. Defaulting to using SSM. Specify ssh_proxy_command to use a different https://docs.skypilot.co/en/latest/reference/config.html#aws.ssh_proxy_command.
```
- One to test that the flag is compatible with a custom AMI and ssh user name
- One to test that if the user has both `use_internal_ips` set to …
> [Core] Add a new use_ssm flag instead of relying on proxy command

- charts/skypilot/templates/oauth2-proxy-redis.yaml
- charts/skypilot/values.schema.json
- charts/skypilot/values.yaml
This PR adds `redis-image` to values.yaml in the oauth sections to enable specifying a speific redis image. This is useful for users who want to can't pull public images or just want more flexibility. 
> [sso] add redis image value

- sky/catalog/__init__.py
Currently need to run `sky show-gpus -a` to see B200s. This PR fixes it to show in regular `sky show-gpus`.
> Add B200 to common accelerators in `sky show-gpus`

- docs/source/cloud-setup/cloud-permissions/aws.rst
This line removes the jq line from the doc for SSM since the new command doesn't use it.
> [UX] Remove unnecessary line in doc for SSM

- charts/skypilot/values.schema.json
- charts/skypilot/values.yaml
Azure requires an `https` redirect uri unless the endpoint is localhost. This PR adds a `use-https` field to the values file which should be set to `true` if using Azure or another SSO provider that requires an `https` redirect uri.
This works because we already have the following handling of `use-https` in `charts/skypilot/templates/oauth2-proxy-deployment.yaml`:
```
{{- if not (index $oauth2 "use-https" | default false) }}
- --cookie-secure=false
{{- end }}
```
By setting `use-https=true` we don't set `--cookie-secure=false` and since `--cookie-secure` has a default value of true according to the oauth [docs](https://oauth2-proxy.github.io/oauth2-proxy/configuration/overview?_highlight=cookie&_highlight=secure#cookie-options), `cookie-secure` will be set to `true`. Then, by …
> [sso] add use-https to auth.oauth values

- CONTRIBUTING.md
- sky/dashboard/src/data/connectors/jobs.jsx
- sky/jobs/server/core.py
- sky/jobs/server/server.py
- sky/server/constants.py
- sky/server/requests/payloads.py
- sky/server/requests/serializers/decoders.py
- sky/server/requests/serializers/encoders.py
- sky/utils/resource_checker.py
- tests/conftest.py
- tests/smoke_tests/backward_compat/test_backward_compat.py
- tests/unit_tests/test_sky/jobs/test_server_queue.py
- tests/unit_tests/test_sky/utils/test_resource_checker.py
Add backward compatibility for jobs queue api
- controller 0.10.1, server 0.10.1,       Client 0.10.2,       - success
- controller 0.10.1, server 0.10.1,       Client branch 7052,  - success
- controller 0.10.1, server 0.10.2,       Client 0.10.1,        - fail
- controller 0.10.1, server 0.10.2,       Client 0.10.2,       - success
- controller 0.10.1, server 0.10.2,       Client branch 7052,  - success
- controller 0.10.1, server branch 7052,  Client 0.10.1,         - success
- controller 0.10.1, server branch 7052,  Client 0.10.2,        - success
- controller 0.10.1, server branch 7052,  Client branch 7052,   - success
- controller 0.10.2, server 0.10.2,       Client 0.10.1,        - fail
- controller 0.10.2, server 0.10.2,       Client 0.10.2, …
> [Core] Add backward compatibility for jobs queue api

- sky/server/metrics.py
- sky/server/requests/executor.py
- sky/server/uvicorn.py
- sky/utils/common_utils.py
Add more metrics per process, like a continuous top view:
I expect this to help us locate issues when there is a CPU saturation or OOM.
> More metrics per process

- sky/serve/controller.py
- sky/serve/serve_utils.py
- sky/serve/service.py
This PR hardens SkyServe cleanup paths:
- Skip Route53 hard assertions during teardown (service/controller).
- If `hosted_zone`/`target_hosted_zone_id` is missing, log a warning and continue LB teardown to avoid resource leaks.
- Wrap cleanup in service finalizer to catch any unexpected exceptions and mark services as `FAILED_CLEANUP` instead of crashing.
Rationale: best-effort teardown should not be blocked by DNS configuration issues; resources should always be terminated and state surfaced via `FAILED_CLEANUP` when partial failures occur.
> Serve cleanup hardening: skip Route53 asserts, ensure teardown continues

- sky/authentication.py
- tests/unit_tests/test_authentication.py
This PR aims to address https://github.com/skypilot-org/skypilot/issues/7065 where launching a cluster on gcp results in `Caught 'int' object is not iterable` error. I was able to reproduce the issue by injecting a malformatted gcp api response, specifically in the `commonInstanceMetadata` section of the response. 
This PR adds safety checks during the parsing of the `commonInstanceMetadata` section of the `projects.get` response from the gcp api. It also adds a few unit tests to verify the logic is working as expected and does not error out upon receiving a malformatted api response. 
> [core] add safety checks while parsing gcp project metadata

- sky/backends/cloud_vm_ray_backend.py
If the cloud doesn't support ports / multi networks, we should treat them as being fully cleaned up, so that we remove the cluster config correctly.
> [core] make sure to delete cluster_yaml if cloud has missing feature

- sky/serve/service_spec.py
- sky/utils/controller_utils.py
- Only import boto3 and validate Route53 hosted zones when running on serve controller
- Add SKY_SERVE_CONTROLLER env var to identify controller runtime environment
- Defer validation to controller on client side to avoid ExpiredToken errors
Users encounter AWS credential errors when running `sky serve up` with Route53 configuration:
```
botocore.exceptions.ClientError: An error occurred (ExpiredToken) when calling the ListHostedZones operation: 
The security token included in the request is expired
```
The issue occurs because the code imports boto3 on both client and server side, attempting to validate hosted zones using local AWS credentials instead of the shared server credentials.
- Check `SKY_SERVE_CONTROLLER` environment variable to determine if running on controller
- Only import …
> Fix: Defer Route53 validation to controller to avoid client-side AWS credential issues

- charts/skypilot/templates/api-deployment.yaml
- sky/utils/common_utils.py
This PR handle the case where resource request and limit are far apart. Currently k8s deployed API server uses resource limits to calculate the number of workers. In this case, the pod can easily blow past resource requests if it's set too low compared to the limit, and get throttled.
Verified the environment variable is populated with the expected value.
Testing:
I've tested the current behavior of the API server in three cases.
Case 1: Request = Limit
```
Limits:       
cpu:     4  
memory:  8Gi
Requests:     
cpu:      4 
memory:   8Gi 
SkyPilot API server will start 4 server processes with 8 background workers for long requests and will allow at max 11 short requests in parallel.
```
API server follows request/limit.
Case 2: Request < Limit
```
Limits:
cpu:     8
memory:  16Gi …
```
> [API server] use k8s resource requests to compute number of workers

- docs/source/getting-started/installation.rst
- sky/setup_files/dependencies.py
- Upgrade local Ray requirement from >= 2.2.0 to >= 2.6.1
- Remove outdated Apple Silicon grpcio installation instructions
- Better version consistency with remote Ray (2.9.3)
Ray 2.6.0+ (July 2023) resolved grpcio issues on Apple Silicon, making the special installation steps unnecessary.
**Ray team confirmation**: Ray's documentation removed Apple Silicon grpcio workarounds in [PR #36029](https://github.com/ray-project/ray/pull/36029) (June 29, 2023), indicating the issue was resolved.
- `sky/setup_files/dependencies.py`: Update Ray version requirement and comments
- `docs/source/getting-started/installation.rst`: Remove Apple Silicon grpcio instructions
Fixes #7072
> [Dependencies] Upgrade Ray version and remove Apple Silicon grpcio workaround

- tests/test_ssh_proxy_lag.py
tests that are based on empirical performance are always flaky. Add some retries on event loop lag tests to only flag endpoints that are consistently laggy.
> [test] retry event loop lag tests

- docs/source/admin/workspaces.rst
- docs/source/reference/config.rst
Just noticed that I used wrong default API domain for Nebius, changing it to the correct one to make less noise.
> docs: fix default Nebius API domain

- charts/skypilot/manifests/dcgm-cluster-dashboard.json
- charts/skypilot/manifests/dcgm-cluster-filter-dashboard.json
- sky/dashboard/server.js
- sky/dashboard/src/components/infra.jsx
Currently, the dashboard only provides metrics for NVIDIA GPUs. This PR adds support for AMD GPU metrics and basic system metrics.
- (feat) Add AMD GPU metrics to Grafana dashboard
- Displayed alongside existing NVIDIA GPU metrics
- Enabled AMD GPU node selection
- (feat) Add system metrics to Grafana dashboard
- CPU utilization
- Memory utilization
- (feat) Add additional Grafana panels to Skypilot dashboard
- GPU temperature
- CPU utilization
- Memory utilization
- (feat) Add a middleware proxy to enable the use of Grafana for Skypilot dashboard development.
The container image has been built and tested.
https://hub.docker.com/layers/ibparkmoreh/skypilot-moreh/support-amd-dashboard/images/sha256-4d7b6708c5b88a581607fe41c331c7e4ee1c9229c2580715e10c80a587cf4c30
Tested (run the relevant …
> [Dashboard] Add AMD GPU and system metrics to the dashboard

- sky/skylet/constants.py
Fixes #6705 
So basically, what happens is we never actually explicitly activate the `uv` environment, but it seems that there is a discrepancy between how containerization and ray workers work in kubernetes and non-kubernetes environments. The `uv` environment is essentially inherited when the `ray.remote` function is called to invoke `log_lib.py::run_bash_command_with_log` on the cluster.
I was able to intercept some relevant information and logged its output:
```
Env vars: {'HOME': '/home/sky', 'HOSTNAME': 'mycluster-5b9e2381-head', 'KUBERNETES_PORT': 'tcp://34.118.224.1:443', 'KUBERNETES_PORT_443_TCP': 'tcp://34.118.224.1:443', 'KUBERNETES_PORT_443_TCP_ADDR': '34.118.224.1', 'KUBERNETES_PORT_443_TCP_PORT': '443', 'KUBERNETES_PORT_443_TCP_PROTO': 'tcp', 'KUBERNETES_SERVICE_HOST': …
```
> [Core] comprehensive deactivation for default UV environment

- .github/workflows/pytest.yml
Run pytest (limited deps) check on both 3.8 (oldest version possible) and also 3.13 (latest compatible version) to make sure we aren't breaking compatibility with either python version.
> [test] update unit test python version

- sky/provision/kubernetes/utils.py
- tests/smoke_tests/test_basic.py
we moved the GPU matching from node selector to affinity; this PR updates the `status_kubernetes` code to reflect this change.
before:
```
sky status --kubernetes
SkyPilot clusters
USER          NAME                   RESOURCES                                  STATUS  LAUNCHED  
seungjinyang  sky-903a-seungjinyang  1x Kubernetes(cpus=2, mem=2)               UP      1 hr ago  
seungjinyang  sky-dbaa-seungjinyang  1x Kubernetes(cpus=2, mem=8, {'None': 1})  UP      1 hr ago
```
after:
```
sky status --kubernetes
SkyPilot clusters
USER          NAME                   RESOURCES                                STATUS  LAUNCHED  
seungjinyang  sky-903a-seungjinyang  1x Kubernetes(cpus=2, mem=2)             UP      1 hr ago  
seungjinyang  sky-dbaa-seungjinyang  1x Kubernetes(cpus=2, mem=8, {'L4': …
```
> Fix k8s gpu status

- sky/provision/kubernetes/instance.py
- sky/utils/command_runner.py
- tests/smoke_tests/test_cluster_job.py
Container images with a login MOTD (like `nvcr.io/nvidia/quantum/cuda-quantum:cu12-0.10.0`) break SkyPilot on Kubernetes due to contaminated command output:
```
D 09-13 09:54:06 command_runner.py:356] Running rsync command: chmod +x /Users/romilb/Romil/Berkeley/Research/sky-experiments/sky/utils/kubernetes/rsync_helper.sh &&  rsync -Pavz --filter='dir-merge,- .gitignore' -e /Users/romilb/Romil/Berkeley/Research/sky-experiments/sky/utils/kubernetes/rsync_helper.sh '/private/var/folders/98/hhq8wrtx6y13196q61xphjsm0000gn/T/sky-tmphgkn98ck/tmp7ucqa_p0/' test-2ea485ef-head@default%2Bcoreweave-dev:'=========================\n      NVIDIA CUDA-Q      \n=========================\n\nVersion: cu12-0.10.0\n\nCopyright (c) 2025 NVIDIA Corporation & Affiliates \nAll rights reserved.\n\nTo run a …
```
> [k8s] Fix login MOTD contamination in Kubernetes command execution

- sky/dashboard/src/components/workspaces.jsx
- sky/dashboard/src/data/connectors/workspaces.jsx
- sky/server/requests/executor.py
- sky/skypilot_config.py
This PR allows users to hit the `GET /workspaces` endpoint without checking workspace credentials. This is safe because the `/workspaces` endpoint only returns workspaces that are accessible by the caller. 
This PR also adds some more debug logging around the workspace authorization codepath and revamps the workspaces page in the dashboard to first determine which workspaces are accessible by the current user and then pass this information to subsequent server requests to determine the number of clusters/managed jobs as well as enabled infra for each workspace. 
This PR addresses https://github.com/skypilot-org/skypilot/issues/7131 for the workspaces page and will be followed by a few other PRs that update the other pages in the dashboard to be more workspace-aware.
Tested (run the …
> [Dashboard] Fix workspace page when default workspace is private

- sky/backends/cloud_vm_ray_backend.py
1. move force unlock statement closer to lock acquisition to lessen the chance that the lock is grabbed inbetween.
2. add "blocking=False" argument to the lock acquisition. Since we force unlock the lock, we don't expect the lock to be acquired - so this makes sense. Currently there is no lock timeout - so if for some reason the lock is acquired at this time, this codepath may block indefinitely until the lock is released.
> do not wait indefinitely if lock acquisition fails

- sky/core.py
- tests/unit_tests/test_core.py
For sky status, if validation fails for a cluster, still return other clusters and emit a log for failed cluster - allowing best effort result.
> best-effort sky status if model validation fails for a cluster

- sky/templates/kubernetes-ray.yml.j2
Since https://github.com/skypilot-org/skypilot/pull/7207 is failing smoke test due to fixes to https://github.com/skypilot-org/skypilot/issues/7192, this PR separates out the working change to exit on error file creation so this part can be merged in while I figure out what the problem is regarding the `set -e` fix.
> [k8s] exit on error during setup, not just successful completion

- sky/backends/backend_utils.py
- sky/global_user_state.py
- tests/test_global_user_state.py
In routines such as status refresh, it is possible to encounter a TOCTTOU bug - between the time the cluster is gotten and the cluster is updated, the cluster record with given name may have been deleted and recreated by `sky down` and `sky launch` in quick succession.
This PR guards against such case by requiring the cluster hash be equal if cluster is being updated.
> [db] when updating cluster, check the hash matches

- sky/jobs/state.py
- tests/test_jobs_state_async_vs_sync.py
> [jobs] fix set_backoff_pending_async bug

- tests/smoke_tests/test_pools.py
- tests/test_smoke.py
This PR adds a smoke test for vLLM using pools to deal with the issue seen in issue #6931.
> [Pools] Add smoke test for vLLM.

- sky/dashboard/src/components/clusters.jsx
- sky/dashboard/src/lib/cache-preloader.js
This PR addresses an issue where a browser refresh (cmd/ctrl + r) causes the dashboard to fetch the cost report which calls the super [inefficient](https://github.com/skypilot-org/skypilot/issues/7190) `get_clusters_from_history` from the global user state db. When the cluster history table is long (~1000 clusters), this db query takes around 20 seconds. 
Currently, the dashboard cache preloader loads the cluster history regardless of whether or not the user has actually clicked the "Show history" toggle which means that loading the page takes 20 seconds. Worse yet, instead of showing a loading spinner on the clusters table, we show "No active clusters" during that loading period instead of a loading spinner which makes for a super confusing UX. This PR also addresses this issue by adding …
> [Dashboard] Speed up clusters page first load by 20x for long cluster history

- sky/templates/kubernetes-ray.yml.j2
> [k8s] properly write to failure file on cluster setup failure (env-setup)

- sky/provision/docker_utils.py
Fixes #7180
This PR fixes FAILED_DRIVER errors that occur when using Docker images containing `RAY_RUNTIME_ENV_HOOK` environment variable (common in images with Ray 2.48.0+).
Docker images with Ray 2.48.0+ set `RAY_RUNTIME_ENV_HOOK=ray._private.runtime_env.uv_runtime_env_hook.hook` for UV package manager support. When SkyPilot exports container environment variables to `/etc/profile.d/container_env_var.sh`, this incompatible variable causes jobs to fail with:
```
ModuleNotFoundError: No module named 'ray._private.runtime_env.uv_runtime_env_hook'
```
Filter out `RAY_RUNTIME_ENV_HOOK` when exporting Docker container environment variables to prevent version conflicts between container's Ray and SkyPilot's Ray 2.9.3.
Before fix:
```bash
sky launch test.yaml  # …
```
> [Docker] Fix `RAY_RUNTIME_ENV_HOOK` causing `FAILED_DRIVER` errors

- sky/skylet/constants.py
If something in the workdir causes the `uv run` to use a different environment (e.g. a `pyproject.toml` in the workdir), uv may use that environment even if `VIRTUAL_ENV` environment variable is specified. We need to add `--active` flag to make `uv run` respect the environment variable.
Testing: see https://github.com/skypilot-org/skypilot/pull/7232
> [k8s] use environment specified by VIRTUAL_ENV when running "uv run"

- tests/smoke_tests/test_aws_logs.py
- tests/smoke_tests/test_logs.py
The existing test will not just grep the actual job output, but also some setup log lines. In some case, those log lines can contain all the digits 1-9 as well as "10", which would cause the test to erroneously pass. This occured in #7135 with
test_log_collection_to_gcp, because this log line was present:
```
2025-09-17 21:53:46,296\tINFO worker.py:1719 -- Connected to Ray cluster. View the dashboard at \u001b[1m\u001b[32m127.0.0.1:8266 \u001b[39m\u001b[22m
```
Which matches all numbers from 1 to 10.
> [test] make test_log_collection more robust

- sky/server/requests/executor.py
We saw a consistent RSS increment after a same request get executed multiple times, this PR clear cache after each request to:
1. Reduce memory footprint before the next cache clear (currently the cache is only cleared before a new request get executed on the executor);
2. Make RSS increment more meaningful by eliminating ephemeral memory usage from the statistics;
> Clear cache after request

- sky/dashboard/src/components/jobs.jsx
- sky/dashboard/src/data/connectors/jobs.jsx
- Remove duplicate requests during refresh
- Query active jobs only for pool status
- Refresh button can refresh the data
- Job count in pool table works
> [Dashboard] Remove duplicate requests during refresh and query active jobs for pool status

- sky/core.py
- sky/dashboard/src/data/connectors/clusters.jsx
- sky/dashboard/src/pages/clusters/[cluster].js
- sky/global_user_state.py
- sky/server/requests/payloads.py
- sky/server/requests/serializers/encoders.py
- tests/unit_tests/test_sky/test_cost_report.py
Improve speed of calling cost_report endpoint in dashboard by doing the minimal work necessary to serve the UI.
Tests:
Measured loading time of historical clusters on an API server with around 1200 terminated clusters - this change drops the loading time from 6 to 3 seconds.
> Cost report optimization (2)

- sky/skylet/constants.py
This flag was added in https://github.com/skypilot-org/skypilot/pull/7230/files to deal with the case where `pyproject.toml` exists in workdir or root dir. smoke tests were added in https://github.com/skypilot-org/skypilot/pull/7232.
I'm getting rid of the `--active` flag for two reasons:
1. https://github.com/skypilot-org/skypilot/pull/7259 should also do the same thing, making this flag unnecessary.
2. older versions of `uv` does not support `--active` flag.
As long as the smoke tests added in https://github.com/skypilot-org/skypilot/pull/7232 still passes we should be fine.
> remove use of --active flag

- docs/build.sh
Fixing a bug where https://docs.skypilot.co/en/latest/llms.txt uses local URLs (`http://127.0.0.1:8000/...`) 
Related PR:  https://github.com/skypilot-org/skypilot/pull/6809
> Fix doc build script

- docs/source/examples/ports.rst
[Opening ports](https://docs.skypilot.co/en/latest/examples/ports.html) page had dated instructions using `--ip`. This PR updates it to use `--endpoint` and `--endpoints`.
> [Docs] Update docs to use `--endpoints`

- sky/setup_files/dependencies.py
#7287 is having a serious impact. 
`uvicorn` upgrade is breaking our nightly/release builds. 
Since our code doesn’t specify a uvicorn version in the requirements, any pip install will pull the latest version, causing the sky server to fail to launch.
This is a workaround and a patch to fix existing code to use the original dependency.  
We can patch the nightly/release using this PR.
We should deprecate this after #7289 is merged.
```bash
uv venv --seed --python=3.10 ~/test_sky
cd ~/test_sky && source ~/test_sky/bin/activate
uv pip install --prerelease=allow "azure-cli>=2.65.0" && uv pip install "skypilot-nightly[all]"
sky api stop && sky api start
SkyPilot API server is not running.
Failed to connect to SkyPilot API server at http://127.0.0.1:46580/. Starting a local server. …
```
> Fix uvicorn dependency

- docs/source/examples/ports.rst
- sky/server/auth/oauth2_proxy.py
- sky/setup_files/dependencies.py
- tests/unit_tests/test_sky/server/auth/test_oauth2_proxy.py
close https://github.com/skypilot-org/skypilot/issues/7293
Tests:
```
> pip install -e .
> sky api stop; sky api start
> pip install fastapi==0.103.1
Successfully installed anyio-3.7.1 fastapi-0.103.1 starlette-0.27.0
> sky api stop; sky api start
> pip install fastapi==0.114.2
Successfully installed fastapi-0.114.2 starlette-0.38.6
> sky api stop; sky api start
```
For legacy uvicorn, warning raised:
```
> pip install uvicorn==0.28.0
Collecting uvicorn==0.28.0
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)'))': /packages/25/bd/c20daf18824b1552d37579fc2f8cc147355c113d55aff21211443a2f89b9/uvicorn-0.28.0-py3-none …
```
> Fixed fastapi compatibility issue and pin uvicorn >= 0.33

- tests/test_optimizer_random_dag.py
Since the issue has been fixed in https://github.com/skypilot-org/skypilot-catalog/commit/a459d8881e2c5bdacd56485709d4938ee0ed1bea, We can now revert skypilot-org/skypilot#7189
> Revert "Workaround non-canonicalized L40S GPU name"

- sky/clouds/kubernetes.py
Closes https://github.com/skypilot-org/skypilot/issues/7149
The current default resources given to a GPU enabled k8s pod is 2 CPU + 8 GB mem per GPU. I am reevaluating the default resources to see what a good default would be.
Long story short, I want to give the pods as much CPU / memory resources but not too much that CPU / memory becomes the constraining factor. To pick the right defaults, I tried our own optimizer on different cloud providers and different GPUs to see what resources clouds give to GPU instances.
Out of the common GPU types, L4s generally get the lowest CPU/mem resources per GPU, as demonstrated by this output
```
---------------------------------------------------------------------------------
INFRA              INSTANCE        vCPUs   Mem(GB)   GPUS   COST ($) …
```
> [k8s] improved default resources for GPU VMs

- sky/__init__.py
Release 0.10.3.post1
Buildkite Test Links:
- [Full Smoke Tests](https://buildkite.com/skypilot-1/full-smoke-tests-run/builds/73) - ❌ 2 failures
- custom gke deploy script failed so those tests were skipped
- `test_cancel_pytorch on azure with param accelerator0` times out during setup - increasing setup timeout causes the test to pass
- [Quicktest Core](https://buildkite.com/skypilot-1/quicktest-core/builds/1309) - ❌ Failed due to #7301. Ignoring since there are no code changes since 0.10.3 so we can be pretty confident backcompat is okay.
- [Smoke Tests Remote Server Kubernetes](https://buildkite.com/skypilot-1/smoke-tests/builds/3554) - ✅ Success
- [Quicktest Core (vs Previous Minor)](https://buildkite.com/skypilot-1/quicktest-core/builds/1310) - ✅ Success
- [Release …
> Release 0.10.3.post1

- sky/backends/backend_utils.py
- sky/utils/cli_utils/status_utils.py
- sky/utils/ux_utils.py
1. in backend_utils, do not call `_get_glob_clusters` (a db operation) if none of the query strings is a glob string. This saves on some DB round trip times and makes the codepath more efficient, especially on single cluster queries which happens quite frequently.
2. Improve the UX such that `Cluster <pattern> not found.` is not emitted if the glob pattern did resolve to at least one cluster. Example:
before
```
$ sky status 'sky*' 'aaa*'
...
Clusters
NAME                   INFRA             RESOURCES               STATUS  AUTOSTOP  LAUNCHED     
sky-cab9-seungjinyang  Kubernetes (test) 1x(cpus=2, mem=2, ...)  UP      -         37 mins ago  
sky-bce0-seungjinyang  Kubernetes (test) 1x(cpus=2, mem=2, ...)  UP      -         4 hrs ago
Cluster sky*, aaa* not found.
```
this {R
```
$ sky …
```
> [ux] cluster query glob improvements

- sky/global_user_state.py
- sky/server/server.py
- sky/server/stream_utils.py
- sky/setup_files/dependencies.py
This PR makes it such that `sky logs --provision <CLUSTER_NAME>` terminates once the cluster is no longer in init state (ie either up or stopped). This improves the UX of using provision log because currently the command will not terminate even once the provisioning has completed.
> [Logs] terminate provision log once provisioning is complete

- sky/client/cli/command.py
- sky/client/sdk.py
- sky/client/sdk_async.py
- sky/core.py
- sky/server/requests/payloads.py
- sky/server/server.py
- sky/utils/kubernetes/create_cluster.sh
- sky/utils/kubernetes/delete_cluster.sh
- sky/utils/kubernetes/generate_kind_config.py
- sky/utils/kubernetes/kubernetes_deploy_utils.py
Fixes #5704
** I know endpoint schema changed, but this won't break backwards compatibility as we don't allow using this command in the client/server model anyways
> [local up] support launching multiple kind clusters

- sky/client/sdk.py
- sky/server/rest.py
- tests/chaos/chaos_proxy.py
- tests/smoke_tests/test_cli.py
Add a network failure smoke test to verify the retry mechanism of skypilot CLI. The failure injected is deterministic so the test will definitely fail if there is no proper retry.
> Add retry on network failure smoke test

- sky/jobs/controller.py
- sky/utils/context.py
This resolves an issue seen in managed jobs where `sdk.launch` would ignore the env vars and log redirection set in the context, because `@context.contextual` was completely overriding those previously set values.
Instead, update this decorator to initialize from a copy of the current context, if a context already exists.
Also, address a minor issue where the redirected log file descriptor could be leaked.
> [thread] avoid destroying existing context in @contextual

- sky/client/cli/command.py
- sky/server/constants.py
- sky/server/requests/payloads.py
- sky/volumes/client/sdk.py
- sky/volumes/server/server.py
- sky/volumes/volume.py
- tests/smoke_tests/backward_compat/test_backward_compat.py
- tests/unit_tests/test_sky/server/requests/test_process.py
- tests/unit_tests/test_sky/volumes/test_runpod_volume.py
- tests/unit_tests/test_sky/volumes/test_volume.py
Previously, a client using a remote API server would still have to install the `[kubernetes]` extra, because we validate the k8s context name on the client side. This is not ideal, since we want clients to not need any extra dependency when using a remote API server.
This PR fixes this by moving validation to a server side, on `POST /volumes/validate`. We also add a corresponding SDK function for it and call it from the CLI, before calling apply.
Backwards compatibility:
- New client <-> old server: Fallback to best-effort client-side validation, without validating k8s context
- Old client <-> new server: No issues, since old client will still be using client-side validation
Tested manually that with this change, clients using a remote API server don't need to have kubernetes installed. …
> [Volume] Move volume validation to server side

- sky/global_user_state.py
- sky/schemas/db/global_user_state/009_last_activity_and_launched_at.py
- sky/schemas/db/global_user_state/009_last_activity_time.py
- sky/utils/db/db_utils.py
- sky/utils/db/migration_utils.py
This PR adds `last_activity_time` and `launched_at` columns to the `cluster_history` table in global user state. This is done in preparation to move the `last_activity-time`-based filtering out of the db client and into the db query itself. Similarly, we want to sort on `launched_at` in the db query rather than in code. We also add indices on these columns to make the previously mentioned db operations as efficient as possible. 
- [] Any manual or new tests for this PR (please specify below)
> [DB] add last activity time and launched at to cluster history

- sky/skylet/constants.py
- sky/templates/kubernetes-ray.yml.j2
Apply fixes introduced to `SKY_UV_CMD` to the standalone uv command in the standalone uv commands in `kubernetes_ray.yaml.j2`.
Additionally fix the ray patch script to use the correct python executable.
> fix uv command in k8s inline script

- sky/setup_files/dependencies.py
I noticed the CI is failing with the following error
Apparently some other projects (e.g. https://github.com/langflow-ai/langflow/issues/1173) have encountered this and the fix was to pin bcrypt version, so here we go
> pin bcrypt version

- sky/backends/backend_utils.py
- tests/smoke_tests/test_ssm.py
- tests/unit_tests/test_aws.py
This PR removes defaulting to SSM if `use_internal_ips` is set to true but `ssh_proxy_command` is empty. If a user wants to use internal IPs without SSM that should be allowed.
I added a new unit test that tests
- We don't set use_ssm to true if it's explicitly set to False in the above case
- We do set it to true if not explicitly set in the above case
> [SSM] Only Default to SSM if not Explicitly Set

- tests/smoke_tests/test_sky_serve.py
When controller is down, it is also possible to show an `No live services` output instead of the original service not found.
> [Test][Serve] Fix sky serve smoke test cleanup

- sky/global_user_state.py
This PR optimizes the `get_clusters_from_history` db query by moving the filtering and sorting operations to the database query. This saves us from querying all the clusters in the cluster history table and then iterating over all of them to filter records that are not within the time range of interest. We also avoid sorting these values in code by utilizing the index on the newly added `launched_at` field and sorting as part of the db query. 
**Correctness:**
I tested this PR on an api server with a db with over 2000 clusters in the cluster history table. I verified that the clusters returned prior to this PR and on this feature branch are the same. 
**Performance:**
I also benchmarked the performance improvement of the server response times to load the historical clusters across a few …
> [DB] move get clusters from history filtering and sorting to db

- sky/volumes/server/core.py
- sky/volumes/server/server.py
- sky/volumes/volume.py
- tests/smoke_tests/backward_compat/test_backward_compat.py
- tests/smoke_tests/test_cluster_job.py
- tests/unit_tests/test_sky/volumes/test_core.py
- tests/unit_tests/test_sky/volumes/test_volume.py
Fixes #7380.
PR #7370 moved the volume validation to server side, but we missed keeping the logic to fallback to inferring `self.cloud` from `self.type` if `self.infra` is unset on the client side. So what happens is, if infra is unset, cloud will also be unset, and this gives a validation error during apply because `cloud` is required in `VolumeApplyBody`.
This PR fixes this by reverting that validation back to the client side, so that `cloud` is never null.
I've reverted the test workaround too from #7382.
Backwards compatibility:
- New client <-> PR 7370 server: Bug fixed on the client side, there's no need to upgrade the server
- PR 7370 client <-> new server: Still fail, as expected, client will need to upgrade to latest. Workaround by setting `--infra`
Tested (run the relevant …
> [Volume] Infer cloud from volume type on the client side if infra is unset

- sky/jobs/controller.py
- sky/server/requests/payloads.py
- tests/smoke_tests/smoke_tests_utils.py
- tests/smoke_tests/test_managed_job.py
- tests/test_config.py
- tests/unit_tests/test_sky/utils/test_context.py
After we unify the job controller process, `sdk.launch()`  is now called by job controller in a single process. So the skypilot config is not reloaded before each `sdk.launch()`, causing the tasks get stale skypilot config.
This PR fixes this issue by always reloading config before sending the client config to server.
The reload takes about 2ms, thus will not introduce visible overhead.
New smoke test cases and unit test cases are added to verify this change.
> Fixed skypilot config propagation in jobs launch

- sky/client/cli/command.py
- sky/client/cli/table_utils.py
- sky/client/sdk.py
- sky/client/sdk_async.py
- sky/core.py
- sky/schemas/api/responses.py
- sky/server/requests/serializers/decoders.py
- sky/server/requests/serializers/encoders.py
- sky/skylet/job_lib.py
Improve the return type of `queue` SDK call. currently this call returns a list of dictionaries and it is unclear what fields are in each dictionary. By returning a concrete type, the user can better understand what is returned when cluster queue endpoint is called.
> [SDK] cluster job queue return type improvements

- sky/dashboard/src/pages/jobs/pools/[pool].js
This PR adds the version of the pool that the worker is on in the dashboard under `/jobs/pools` under 'Pool Version' addressing issue https://github.com/skypilot-org/skypilot/issues/6930.
> [Pools] Add Pool Version to Workers in Dashboard

- docs/source/examples/managed-jobs.rst
This PR updates the pools docs to say (Experimental) instead of [EXPERIMENTAL] and fixes the indentation inside the warning.
> [Docs] Pools - Fix Indent and Tweak Wording

- sky/provision/kubernetes/instance.py
The init-copy-home takes too long with the coreweave PVC. We increase the timeout here.
> [K8s][Controller] Increase timeout for HA controller

- tests/smoke_tests/test_mount_and_storage.py
This smoke test will fail until a nightly build including https://github.com/skypilot-org/skypilot/pull/7424 is published, hence it is on a separate PR.
> [test] smoke test for "Fix improper argument parsing in fusermount"

- sky/utils/cluster_utils.py
- sky/utils/command_runner.py
- sky/utils/command_runner.pyi
- tests/unit_tests/test_sky/utils/test_command_runner.py
Fixes #7054
This PR lets the docker SSH tunnel honor users' jump-host proxy command so docker workloads can run on private IPs.
- docker nodes run sshd on localhost:10022 inside the container. SkyPilot used to clear `ssh_proxy_command` whenever `docker_user` was set, because the outer hop incorrectly attempted to run through the jump host. That broke the connection for private-only nodes.
- cluster_utils wrote both `ProxyCommand` values into `~/.ssh/config`, triggering `AssertionError: Cannot specify both proxy_command and docker_proxy_command.` in recent builds.
- Inject the user proxy into the inner hop only (`ssh -W host:port gcpuser@vm`), while the outer hop stays pointed at localhost. `%h`/`%p` placeholders are resolved before assembling the docker proxy string so the jump host sees …
> [core] support docker ssh proxy via jump host

- sky/backends/backend_utils.py
- sky/backends/cloud_vm_ray_backend.py
- sky/jobs/server/core.py
When launching a managed job, we may update the status of the job controller without holding the necessary lock. This can cause two simultaneous `job launch`es to crash.
This regression was introduced in #5274 (cc @kyuds)
We observed some issues due to this issue in e.g. https://buildkite.com/skypilot-1/smoke-tests/builds/3746/steps/canvas?jid=019987f3-fbda-4df7-bacc-778e00d2b4fa. I reproduced this locally and diagnosed the issue through cluster event table logs.
Also, clarify the corresponding variable to avoid this kind of issue in the future.
> [jobs] make sure we don't update the cluster status without locking

- sky/task.py
- tests/smoke_tests/test_cluster_job.py
- tests/unit_tests/test_sky/test_task.py
This PR adds the ability for us to parse environment variables set by the task yaml and substitute these names into volume names.
I added multiple unit tests that test the parsing of volume names to ensure:
- When there is no valid substitution we don't change the name
- When there are one or more valid substitutions we change the name accordingly
- We handle cases where the volume is a dictionary instead of a string.
I added a smoke test testing end-to-end functionality of using `sky launch --env USERNAME=<username>` with a volume name such as `${USERNAME}-pvc`. 
> [Volumes] Add ENV Variable Parsing to Volumes

- sky/client/cli/command.py
- sky/client/cli/table_utils.py
- sky/client/sdk.py
- sky/core.py
- sky/data/storage_utils.py
- sky/schemas/api/responses.py
- sky/server/requests/serializers/decoders.py
- sky/server/requests/serializers/encoders.py
Add proper typing to storage ls endpoint, allowing users to better understand the response.
In addition, move the storage table formatting code to table_utils.py
Changes:
- Add a response schema at `schemas/api/responses.py`. Have the server (`sky/core.py`) return said response type, and have the SDK (`sky/client/sdk.py`) return the said response type to user.
- Change the encoder/decoder for this endpoint to encode and decode `StorageRecord` response properly.
- Move the volume table formatting utility (used for pretty print CLI response) from `sky/data/storage_utils.py` to `sky/client/cli/table_utils.py` and have the table formatting utility accept `StorageRecord` as argument.
> [SDK] storage ls typing improvement

- sky/server/common.py
- tests/unit_tests/test_sky/server/test_common.py
Fixes #7407.
It is difficult to smoke test this because smoke tests do not expect to run in an isolated environment where they can start/stop the API server.
> clear cache before retrying server status

- sky/client/cli/command.py
- sky/client/cli/table_utils.py
- sky/client/sdk.py
- sky/core.py
- sky/jobs/client/sdk.py
- sky/jobs/server/core.py
- sky/jobs/server/server.py
- sky/jobs/utils.py
- sky/schemas/api/responses.py
- sky/server/requests/serializers/decoders.py
- sky/server/requests/serializers/encoders.py
Instead of returning an ambiguous`Dict[str, Any]` to the user when managed job queue (or kubernetes status) is called, return a pydantic response which makes the response fields easier to use by the user.
Changes:
- Add a response schema at `schemas/api/responses.py`. 
- Have the server (`sky/jobs/server/core.py`) return said response type for jobs queue API, and have the SDK (`sky/jobs/client/sdk.py`) return the said response type to user.
- Have the server (`sky/core.py`) return said response type for status_kubernetes API, and have the SDK (`sky/client/sdk.py`) return the said response type to user.
- Add a jobs table formatting utility in `sky/client/cli/table_utils.py` which takes in the new `ManagedJobRecord` as argument.
> [SDK] managed jobs queue / status kubernetes typing improvements

- sky/provision/kubernetes/utils.py
- tests/unit_tests/kubernetes/test_kubernetes_utils.py
In `get_kubernetes_node_info`, we call `get_all_pods_in_kubernetes_cluster`, which is expensive for clusters with a lot of pods. The reason we need to call this is to get the real-time resource usage of accelerators, which we get by reading each pod's `pod.spec.containers[*].resources.requests`.
But this is only relevant for clusters with accelerators, we can skip this otherwise. This PR optimizes for this case by moving the call to `get_all_pods_in_kubernetes_cluster` down, after we check that at least one node have `accelerator_count` > 0.
Tested on a CPU-only cluster with 1000 pods and 100 requests each to `/kubernetes_node_info`:
- Before: 
```
Min:  2836.28ms
p50:  2947.82ms
p95:  3849.55ms
p99:  7867.67ms
Max:  7896.89ms
```
- After: 
```
Min:  611.65ms
p50:  717.43ms
p95: …
```
> [k8s] Optimize `/kubernetes_node_info` for clusters with no accelerators by 3x

- sky/global_user_state.py
- sky/jobs/state.py
- sky/jobs/utils.py
This PR optimizes the number of db queries made in `get_managed_job_queue` from O(N) to O(1). Instead of making the `get_pool_from_job_id`, `get_pool_submit_info`, and `get_handle_from_cluster_name` db queries on each job, we run  batch `get_pool_and_submit_info_from_job_ids` and `get_handles_from_cluster_names ` queries such that the number of db queries made by `get_managed_job_queue` does not scale linearly with the number of managed jobs. 
I tested this with a local api server with 20,000 mock entries in the spot_jobs sqlite db and observed a 15x improvement (4.211s --> 0.289s).
> [Core] optimize get_managed_job_queue from O(N) to O(1)

- sky/dashboard/src/components/jobs.jsx
- sky/dashboard/src/lib/cache.js
- sky/dashboard/src/lib/cache.test.js
This PR eliminates duplicate calls to the api server during jobs page load and also enforces request deduplication at the dashboard cache layer. I observed this eliminate many duplicate calls to `sky.status`, `sky.jobs.queue`, and `sky.jobs.pool_status`.
On a remote api server (jobs consolidation mode enabled) and remote postgres db, I found that this resulted in a 6x speedup (30s --> 5s) and also significantly reduces api server load. In particular, prior to this PR, by observing the network tab in the browser console, I found that loading the jobs page made:
```
5 calls to sky.status
9 calls to sky.jobs.queue
2 calls to sky.jobs.pool_status
```
With this PR we make:
```
1 call to sky.status
1 call to sky.jobs.queue
1 call to sky.jobs.pool_status
```
> [Core/Dashboard] cache deduplication (6x jobs page load speedup and 5x server load reduction)

- sky/provision/kubernetes/utils.py
- sky/setup_files/dependencies.py
- tests/smoke_tests/test_basic.py
`get_kubernetes_node_info` calls the k8s API to list all nodes and pods. On large kubernetes clusters, this can be expensive in many ways, as the size of the response body can get really big. On a mock API server setup using [kwok](https://kwok.sigs.k8s.io/), I mocked 500 nodes and 5000 pods. The response size is 4MB for list nodes, and 34MB for list pods. I would expect real clusters to be bigger than this, as real nodes and pods would contain a lot more labels, annotations, etc.
This large response size contributes to both increased memory usage, as we have to load everything to memory to deserialize it into python objects, and also increased CPU usage and latency, which is mainly caused by a long standing [issue](https://github.com/kubernetes-client/python/issues/1921) on the …
> [k8s] Use streaming json parser for listing nodes and pods: up to 2x speedup, 50% less memory for large clusters

- sky/schemas/api/responses.py
In `volume_list`, we read record['region'] and record['size'] from `VolumeConfig`, and in `VolumeConfig`, both of them are optional, so we should also make it optional in `VolumeRecord`.
https://github.com/skypilot-org/skypilot/blob/727ea9a60a919fd2ea477dea03a4096136355d20/sky/models.py#L101-L117
This was causing an issue on one of our older API server, where `sky volumes ls` failed with:
```
sky.exceptions.CloudError: pydantic_core error (ValidationError): 1 validation error for
VolumeRecord
region
Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
For further information visit https://errors.pydantic.dev/2.11/v/string_type
```
The record that made it fail had `region` set to None:
```
{'name': 't-volume1', 'launched_at': 1757037347, 'user_hash': …
```
> [Volumes] make VolumeRecord region and size optional to match VolumeConfig

- sky/skypilot_config.py
- tests/smoke_tests/test_cli.py
Example from my use
Before:
```
Error: Invalid value for '--config': Invalid config override: ('gcp.label.cooperc-label-test=test-value',). Check if config file exists or if the dotlist is formatted as: key1=value1,key2=value2
```
After:
```
Error: Invalid value for '--config': Invalid config override: ('gcp.label.cooperc-label-test=test-value',). Check if config file exists or if the dotlist is formatted as: key1=value1,key2=value2.
Details: Invalid config YAML from (CLI). See: https://docs.skypilot.co/en/latest/reference/config.html. Error: Instead of 'label', did you mean 'labels'?
```
Latter message is way more helpful.
> [ux] add error details when --config is invalid

- examples/deepspeed-multinode/sky.yaml
PyTorch 2.6+ breaks sets `torch.load()` to use weights_only=True, breaking our current example. Tested by launching on 2x H100:1.
> [Examples] Fix deepspeed examples by pinning pytorch version

- docs/source/examples/managed-jobs.rst
- docs/source/running-jobs/many-jobs.rst
- sky/jobs/constants.py
- tests/unit_tests/test_controller_utils.py
Now, we are way more CPU limited than memory. Change the controller so that the memory/cpu ratio is 4x.
> [jobs] adjust default controller size

- .buildkite/generate_pipeline.py
- .github/workflows/nightly-build.yml
Introduce a new queue `kind`, and use separate AWS auto scale groups for resource management.
Need to work with https://github.com/assemble-org/prototype/pull/83 together.
> Scale buildkite `kind` test cluster

- sky/templates/kubernetes-ray.yml.j2
Setting `-x` on runtime setup scripts logs the actual command being run during runtime setup, making debugging easier.
`-x` makes debugging especially easier for k8s runtime setup, as the command being run is rather dynamically assembled from different places in code + from environment variables.
> [k8s] Add set -x to runtime setup scripts

- tests/load_tests/db_scale_tests/README.md
- tests/load_tests/db_scale_tests/README_POSTGRES.md
- tests/load_tests/db_scale_tests/cleanup_postgres_clusters.py
- tests/load_tests/db_scale_tests/cleanup_postgres_managed_jobs.py
- tests/load_tests/db_scale_tests/cleanup_test_clusters.py
- tests/load_tests/db_scale_tests/cleanup_test_managed_jobs.py
- tests/load_tests/db_scale_tests/inject_minimal_test.py
- tests/load_tests/db_scale_tests/inject_postgres_clusters.py
- tests/load_tests/db_scale_tests/inject_postgres_managed_jobs.py
- tests/load_tests/db_scale_tests/inject_test_cluster_history.py
- tests/load_tests/db_scale_tests/inject_test_clusters.py
- tests/load_tests/db_scale_tests/inject_test_managed_jobs.py
- tests/load_tests/db_scale_tests/run_postgres_cleanup.py
- tests/load_tests/db_scale_tests/run_postgres_injection.py
- tests/load_tests/db_scale_tests/scale_test_utils.py
This PR adds postgres equivalent scripts to run db scale testing by injecting active clusters, terminated clusters, and managed jobs into the database.
> [tests] Utility scripts for testing postgres operations at scale

- sky/provision/kubernetes/utils.py
This subtle change can reduce the credential check time of k8s by significant amount for following reasons:
1. `get_kubernetes_nodes` is a much cheaper call than `list_namespaced_pod`. Since the purpose of making a call here is that _a_ k8s API call succeeds, we should call a much cheaper API endpoint.
2. `get_kubernetes_nodes` is a cached call, and codepaths further down in `check_credentials` makes calls to `get_kubernetes_nodes`. Therefore, calling `get_kubernetes_nodes` is essentially free as future invocations will simply use a cached response from this call.
`get_kubernetes_nodes` implementation already sets the API timeout of `kubernetes.API_TIMEOUT`. Since no caller of `check_credentials` actually specifies a timeout different from default, the timeout logic stays identical. …
> [k8s] reduce API calls during k8s check

- sky/jobs/utils.py
It's possible that backend.get_job_status throws a TypeError or ValueError in some rare cases. This just indicates that the cluster was cleaned up in the middle of the status check, probably by the skypilot-status-refresh-daemon. This is fine, and we should just treat the cluster is down and recover the managed jobs.
We should gracefully handle these errors within backend.get_job_status, but this will make sure that managed jobs aren't broken in the mean time.
I saw these two stacktraces in job controller tests:
```
I 10-02 06:44:58 utils.py:289] === Checking the job status... ===
E 10-02 06:45:21 controller.py:756] Unexpected error in JobsController run for task 0
E 10-02 06:45:21 controller.py:759] Traceback (most recent call last):
E 10-02 06:45:21 controller.py:759]   File …
```
> [jobs] catch some errors from get_job_status

- sky/backends/cloud_vm_ray_backend.py
Comment out the removal of cluster YAML to prevent stability issues. See #5011.
> [core] skip deleting cluster YAML for stability

- tests/conftest.py
The default value for `--dependency` is `'all'`, not `None`. But when checking whether to skip tests marked with `no_dependency`, we just check the truthiness of the `--dependency` arg. This is regression from https://github.com/skypilot-org/skypilot/pull/7510. We should make sure to only skip these tests if the value is changed from the default.
> [test] don't disable no_dependency tests by default

- docs/source/reference/config.rst
Add descriptions for container name in pod_config
> [Doc] Add descriptions for container name in pod_config

- sky/server/requests/executor.py
- sky/server/requests/requests.py
- tests/common_test_fixtures.py
- tests/conftest.py
- tests/smoke_tests/test_basic.py
- tests/test_api.py
- tests/unit_tests/test_sky/server/requests/test_executor.py
There is a race condition when `sky.launch` is executed asynchronously, below is the most common case that will cause the cluster get leaked.
| Timeline | launch  | api.cancel      | down                |
|----------|---------|-----------------|---------------------|
| T0       | Queued  |                 |                     |
| T1       |         | Cancel, success |                     |
| T2       |         |                 | no cluster, success |
| T3       | Executed |                 |                     |
IIUC, when launch is not queued, there is still a potential race condition with low probability, since `update_request` does not acquire a filelock, it is possible that the launch process read a stale request status that has been modified by an `api.cancel` request.
This PR …
> Fixed requests api cancel race condition

- tests/smoke_tests/test_cluster_job.py
This PR addresses a problem introduced in https://github.com/skypilot-org/skypilot/pull/7497 that changes the output of kubernetes jobs which caused some tests to fail due to the change in expected output. The previous PR adds the following lines due to `set -x`
```
+ '[' 1000 -eq 0 ']'
+ true
+ STEPS=("apt-ssh-setup" "runtime-setup" "env-setup")
+ set +x
+ '[' 0 -ne 0 ']'
+ '[' 0 -ne 0 ']'
+ '[' 0 -ne 0 ']'
```
I changed the tests to check explicitly for the lines it wants rather than test for exact line count.
> [Test] Fix Container Logs Tests

- tests/smoke_tests/test_mount_and_storage.py
After we introduce nebius credential, the nebius storage is auto selected sometime and the ls command does not include nebius causing flaky.
> Fix `test_kubernetes_storage_mounts` flaky

- sky/metrics/utils.py
- sky/server/metrics.py
- tests/unit_tests/test_sky/metrics/test_metrics_util.py
- tests/unit_tests/test_sky/server/test_metrics.py
One of our user saw thousands of `kubectl port-forward` process to the prometheus server, I cannot repro this but according to the code, if there is any error raised in the `start_svc_port_forward` function, the process will never be cleaned. This PR fixes this potential issue.
A unit test is added.
> Fixed potential gpu-metrics port-forawrd process leak

- tests/smoke_tests/test_basic.py
- tests/smoke_tests/test_workspaces.py
Skip tests that required client side sky restart or import kubernetes utils from client side
> [test]skip `--dependency` tests

- .buildkite/generate_pipeline.py
- tests/smoke_tests/backward_compat/test_backward_compat.py
`quicktest-core` fails on master, the parsing logic accidentally get `sky-jobs-controller-4a9ad66d\nD` thus break the bash script. This PR refines the parsing logic to unblock the test.
```
* To see all managed jobs: sky jobs queue
--
  | * 1 cluster has auto{stop,down} scheduled. Refresh statuses with: sky status --refresh
  | Jobs controller: sky-jobs-controller-4a9ad66d
  | D name ended
  | Warning: Permanently added '18.232.133.63' (ED25519) to the list of known hosts.
  | bash: line 1: D: command not found
```
> Robustly parsing job controller name in smoke test
